### ISSUE TITLE
Flow-based typing should work for negative conditions

### ISSUE THREAD

**Issue by Timmmm** [dart-lang/language#1011]
In Typescript you can do something like this:

```
const foo: number | null = ...;
if (foo === null) {
   return false;
}
// At this point the compiler and IDE know that `foo` is a `number`.
```

But if I try something similar in Dart it does not work:

```
final foo = jsonDecode(...);
if (foo is! Map<String, dynamic>) {
  throw Exception('invalid json');
}
// At this point I expect the compiler and IDE to know that `foo` is a `Map<String, dynamic>`, but it doesn't.
```

I have to contort my code to this:

```
final foo = jsonDecode(...);
if (foo is Map<String, dynamic>) {
  .... lots of code, more nested ifs ...
} else {
   throw Exception('invalid json');
}
```

Incidentally it would be nice if the `jsonDecode()` docs had an example for how you are supposed to deal with the `dynamic` it returns. As a Dart noob it is difficult to work out (and it's difficult to search for `is`).

**Comment by leafpetersen** [comment]
> final foo = jsonDecode(...);
> if (foo is! Map<String, dynamic>) {
>   throw Exception('invalid json');
> }

This will work as requested in the upcoming null safety release planned for later this year (note that access to the feature will require opting into null safety and updating your code, since this is a breaking change).

We're separately exploring usability issues with `jsonDecode` but don't have anything concrete to say about that yet.
