### ISSUE TITLE
NNBD: Dart needs an operator to assert that a variable isn't null (like Kotlin's !! suffix), for backwards-compatibility

### ISSUE THREAD

**Issue by hacker1024** [dart-lang/language#1033]
I'm using NNBD with a package that hasn't opted in.
This package ([udp](https://pub.dev/packages/udp)) has a [method](https://pub.dev/documentation/udp/latest/udp/UDP/bind.html) that returns a `UDP` object - it has no chance of ever returning `Null`.

My problem is that I need to use this variable right after assigning it, and since the compiler/analyzer doesn't know that it can't be `Null`, this creates an error.

```dart
_udpConnection = await UDP.bind(Endpoint.broadcast());
return _udpConnection.publicVariable
```

```
The expression (_udpConnection.publicVariable) is nullable and must be null-checked before it can be used.  Try checking that the value isn't null before using it.
```

I know for sure that this variable is not `Null`, because I just assigned it with a non-`Null` value. Right now, there are two workarounds for this error:
- Adding a `?.` operator, which is a waste of `Null` checking
- Casting - ```return (_udpConnection as UDP).publicVariable``` - which may also be unoptimized, and is very clunky to embed in a line like that.

Kotlin (which is NNB, but is 100% interoperable with Java, a nullable language) gets around this problem quite nicely - [with the !! suffix.](https://kotlinlang.org/docs/reference/null-safety.html#the--operator)

It'd be great if Dart included this.

**Comment by rrousselGit** [comment]
Are you looking for `.!`?

```dart
int? nullable
int nonNullable = nullable!;
```

**Comment by hacker1024** [comment]
Oops - I didn't know about that. Where's it documented?

It works.

**Comment by kwalrath** [comment]
It's documented here: https://dart.dev/null-safety

I also recommend going through all the examples in the **Learn with Snippets!** menu of https://nullsafety.dartpad.dev.

Please let us know if you find any issues, or have ideas for making the docs & tools clearer!

**Comment by mraleph** [comment]
@hacker1024 I am a bit puzzled, based on your description of the issue it is `_udpConnection.publicVariable` that is considered nullable and not `_udpConnection` itself. 

Could you provide an actual code that is triggering the issue? 

The reason I am asking this is because if `udp` package itself is not opted in into nullability then all types originating from that package should be treated in a special way, meaning that the code like this:

```
Future<void> connect() async {
  final udp = await UDP.bind(Endpoint.any());
  bool b = udp.closed;
  print(b);
}
```

should (in my understanding, @leafpetersen can confirm) type check _just fine_. You should not need to rewrite this code like this:

```
Future<void> connect() async {
  final udp = await UDP.bind(Endpoint.any());
  bool b = udp!.closed!;
  print(b);
}
```

which is what you would need to do if all types from non-opted in libraries were treated as nullable, but they are not (they are treated as a special legacy nullability).

So to return to my original question: Could you provide an actual code that is triggering the issue? It would be good to understand the context in which it occurred just to make sure that things are working as expected.

**Comment by leafpetersen** [comment]
Yes, sorry I missed that in the original question.  I also don't understand what is causing the error.  Assuming that the udp package is *not* opted in, and the code in question *is* opted in, then there should be no nullability errors when using the udp package.
