### ISSUE TITLE
Abstract method should force children to override it even if it is already defined in a grandparent class

### ISSUE THREAD

**Issue by leddy231** [dart-lang/language#1042]
Using the following code as an example:
```dart
class GrandParent {
  void foo() {
    print("I am foo");
  }
}

abstract class Parent extends GrandParent {
  void foo();
}

class Child extends Parent {

}
```
This will compile, as `Child` has inherited `foo` from `GrandParent`, even though `Parent` has attempted to override it with an abstract stub. For comparison, both Java and Kotlin ([playground link](eyJ2ZXJzaW9uIjoiMS4zLjcyIiwicGxhdGZvcm0iOiJqYXZhIiwiYXJncyI6IiIsImpzQ29kZSI6IiIsIm5vbmVNYXJrZXJzIjp0cnVlLCJ0aGVtZSI6ImlkZWEiLCJjb2RlIjoiLyoqXG4gKiBZb3UgY2FuIGVkaXQsIHJ1biwgYW5kIHNoYXJlIHRoaXMgY29kZS4gXG4gKiBwbGF5LmtvdGxpbmxhbmcub3JnIFxuICovXG5cbm9wZW4gY2xhc3MgR3JhbmRQYXJlbnQge1xuICBvcGVuIGZ1biBmb28oKSB7XG4gICAgcHJpbnQoXCJJIGFtIGZvb1wiKTtcbiAgfVxufVxuXG5hYnN0cmFjdCBjbGFzcyBQYXJlbnQ6IEdyYW5kUGFyZW50KCkge1xuICBhYnN0cmFjdCBvdmVycmlkZSBmdW4gZm9vKCk7XG59XG5cbmNsYXNzIENoaWxkOiBQYXJlbnQoKSB7XG4gICAgXG59XG5cbmZ1biBtYWluKCkge1xuICAgIHByaW50bG4oXCJIZWxsbywgd29ybGQhISFcIilcbn0ifQ))
does not allow this example to compile, and forces `Child` to re-implement the abstract overridden method.

The only situation I can think of where this example would arise is when the behavior shown by Java and Kotlin is desired, i.e. the abstract class has additions that would make redefining the method necessary, and it wants to communicate that to any extending class by marking it as abstract.

A simple real world example, apart from complex class hierarchies, would be to mark `toString()` as abstract. This wold ensure that all extending classes implement some `toString()`,  making debug printing a bit easier.

Additionally, I think it would be useful for the `Child` class to be able to use `super.foo()` as its implementation (`void foo() => super.foo();`), as the Grandparent implementation still exists. This does not work in Java or Kotlin, but I think it makes sense. The abstract class has communicated that the method might need to be re-implemented, but the programmer have chosen to keep the existing implementation. Keeping the `GrandParent` implementation would then be an active choice, instead of a fallback when forgetting to re-implement the method.

**Comment by lrhn** [comment]
Dart has deliberately chosen not to go the same route as Java and Kotlin her.

The most direct reason for the current behavior is mixins, which is a feature that Java does't have. You can declare an "abstract" mixin like:
```dart
mixin Foo { 
  String foo() => "${bar()}";
  DateTime bar();
}
```
which declares an abstract `bar` method. It can be applied to any class, but if that class is non-abstract, it must then ensure that there is a `bar` implementation.
You would want to be able to apply `Foo` to `Bar` declared as:
```dart
class Bar {
  DateTime bar() => DateTime.now();
}
class FooBar = Foo with Bar;
```
If the abstract `bar` method of `Foo` overrode the `bar` method of `Bar`, then this would not work.


The underlying Dart model is that *abstract* method go into the interface of a class declaration, and concrete methods go into the class. Java does not have this distinction because they separate `class` and `interface` declarations. Dart does not, which is why an abstract method declaration in a Dart `class` declaration doesn't necessarily have to introduce something into the class.


So, the behavior is deliberate, and we have no current plans to change it.

**Comment by leddy231** [comment]
Ah, that would indeed be problematic with mixins. Even some variant where this change only applied to classes extending each other would probably be confusing

 [#30175](https://github.com/dart-lang/sdk/issues/30175) would be a good solution.
