### ISSUE TITLE
Why doesn't dart allow to declare enums in class?

### ISSUE THREAD

**Issue by gupta-shrinath** [dart-lang/language#1050]
I tried to declare an enum inside the class and it gave me an error stating can't have enum inside a class. I wanted to know the reason why but I didn't find anything on the internet. Declaring enum inside a class is allowed by major languages why not dart?

**Comment by lrhn** [comment]
Dart does not allow classes to be declared inside other classes. See #336.
Since enums are classes, they also cannot be declared inside other classes.

**Comment by gupta-shrinath** [comment]
Oh, I also thought that this might be the case. But why doesn't dart allow nested class? I just want to know I also understand that this might sound naive.

**Comment by lrhn** [comment]
Dart does not allow nested classes mainly because it's simpler not to.

If you nest classes, there are two ways to do it:
1. Static nested classes, which really is just a way to put the declaration into the namespace of the other class, but is otherwise the same as declaring another top-level class.
2. Virtual classes, where subclasses inherit the class and can perhaps even override it.

The latter is pretty complicated, and not something we have found a good enough reason to prioritize yet.
The former is fairly simple, but also not very powerful, so it too hasn't been a priority.

**Comment by gupta-shrinath** [comment]
I appreciate your reply:+1: . Closing the issue
