### ISSUE TITLE
Use 'is' keyword for enums

### ISSUE THREAD

**Issue by Ferdzzzzzzzz** [dart-lang/language#1051]
Describe the new syntax or language feature you'd like to see incorporated into
Dart. Ideally you can relate this to a `request` issue filed separately.

Is there any reason why we can't use the 'is' keyword for enums? I know the 'is' keyword is technically for type-checking and enum values aren't types, but it would be great for readability.

eg. Instead of:
`if (currentView == Views.homeView){}`

we can do

`if (currentView is Views.homeView){}`

Not crucial at all, I just find the 'is' keyword reads nicely and enums are often used in the same sort of context as checking types :)

**Comment by lrhn** [comment]
You could argue similarly for using `is` for any equality check: `if (x is 2)`, `while (y is! null)`. There is nothing inherently special about enums here.
Dart uses `==` and `!=` for equals and not-equals. 

There is no *technical* reason we couldn't allow you to use `is` to mean `==` and `is!` to mean `!=` whenever the second operand is not  a type. It would make some things slightly awkward: `Type fooType = foo.runtimeType; if (fooType is int) ....` would *not* work as `==`.

From a language design point of view, allowing this would break the "similar syntax means similar things, different things look different" rule. By having `x is dogma` and `x is pragma` mean different things (because `pragma` happens to be a type), code becomes less readable. By having `x == 1` and `x is 1` mean the same thing, we make it harder for people writing code to decide.

All in all, the ambiguity is reason enough to not go this way.

**Comment by Ferdzzzzzzzz** [comment]
"similar syntax means similar things", that makes sense thanks @lrhn, I actually fully agree with that 😄
