### ISSUE TITLE
permit eager loading of deferred imports

### ISSUE THREAD

**Issue by mraleph** [dart-lang/language#1067]
Current spec describes deferred imports in a way which mandates issuing dynamic errors if deferred prefix is accessed before the `loadLibrary` is called.

This implies code size penalty even if no libraries are actually deferred, at minimum code needs to be generated to check the status of the library prefix and state of the library prefix needs to be stored somewhere. This accounts for as much as 0.4% on large internal apps - and is essentially completely dead payload.

I propose to amend the spec with something like the following paragraph: 

> An implementation is free to treat _all_ deferred imports in the program as if they were eagerly loaded i.e. `loadLibrary` was invoked on each and every single one of deferred prefixes in the program before execution of the main begins.

Note: this all or nothing mode - either all deferred imports are eagerly loaded or none of them, which makes it predictable and understandable. 

This is more or less how Dart VM implementation behaved since the switch to Kernel based pipeline - so amending the spec simply ratifies Dart VM behaviour. 

/cc @lrhn @leafpetersen @rmacnak-google

**Comment by eernstg** [comment]
I do not have strong opinions on this, but [here](https://github.com/dart-lang/language/pull/1071)'s a PR that proposes how we could say it.

**Comment by lrhn** [comment]
I'd state it as:

> A deferred library import with prefix *p* may be loaded lazily at the compiler's discretion. 
> Accessing any declaration through the prefix *p* other than *p.loadLibrary* causes a run-time error
> if evaluated before the deferred import has been loaded.
> Invoking <code>*p*.loadLibrary</code> will cause the import to be loaded, 
> and the returned future completes when the library has been loaded.
> *(A compiler may choose to eagerly load the deferred library, and if so, accessing the imported 
> declarations will not cause a run-time error even though <code>*p*.loadLibrary</code> has not 
> been invoked yet.)*

I don't want to have "all or none" requirements. Either all deferred imports require a `loadLibrary`, or they don't. If they don't, I see no reason to make any further requirements.

A deferred library is like a global `late` variable. It's up to the user to use it correctly, we can't help them because that would require global flow analysis.

**Comment by leafpetersen** [comment]
cc @rakudrama @sigmundch

**Comment by sigmundch** [comment]
I feel that making optional would defeat the purpose of this check - we wanted it so that you can have consistent semantics regardless of whether code was actually deferred.

DDC doesn't have this check today but we do want to add it: we want to prevent users from finding in production that they accidentally accessed something before it was available.

Using the parallel of late variables from @lrhn - you get an error if you access an uninitialized late variable, I think we should do the same here.

I would like to understand better the associated cost, and see if there are thing we can do to improve it, though.

A couple thoughts:
* Could we do a kernel transformation to remove the check when the load dominates the uses? I think this is a common scenario. Would that reduce the cost you see?

* Should we consider a toggle for the check (e.g. treat it as an assertion or add a different flag to disable it in production?) Dart2js will not remove it because it is actually deferring code so it will have to check for the code to be available. AOT with deferred loading disabled could disable the checks in that case?

**Comment by mraleph** [comment]
> I feel that making optional would defeat the purpose of this check - we wanted it so that you can have consistent semantics regardless of whether code was actually deferred.

I do however fully understand the benefit of it - that is why my initial proposition is all or nothing, essentially what I propose is that VM has a flag which switches between two behaviours - similar to what you propose in the second bullet item: you either get deferred libraries as they are speced today with full checking (and potentially with benefits) or you don't get any deferred libraries (no benefit, no overhead of the checking). There is a draw back the the code which worked in "eager" mode might not work in "deferred" mode, but we can address some of the concern here by only making AOT "eager" and keeping JIT deferred. 

> Could we do a kernel transformation to remove the check when the load dominates the uses? I think this is a common scenario. Would that reduce the cost you see?

We could try to crunch the numbers, but it requires some investigation. I know that if I revert CL that reintroduces checks into the VM we save 0.4% of binary size - this is good enough motivation for me to propose the "eager loading mode".

**Comment by sigmundch** [comment]
Interesting - thanks for sharing!

I was reading your comment from the change, I'll post some additional questions there.

**Comment by sigmundch** [comment]
> ... I'll post some additional questions there.

I changed my mind :), more details here to keep the discussion in one place.

Do you mean that the VM implementation is incurring in a cost regardless of whether an import is marked as deferred? Is the 0.4% regression present in apps with no deferred imports?

For context, in the case of dart2js, there is no cost if there is no deferred import. We tree-shake any methods used for that purpose. We also have a flag to do eager loading (`--disable-program-split`), where we keep the load and check instructions.

I just did some quick and dirty measurements on a large internal app. With eager loading our cost was about 0.07% of unminified code. The cost was spread among a call per load (~440), a call per check (~790), the load and check methods themselves, a table specifying data per prefix (mostly empty because we do eager loading), and a hashset to do bookkeeping of loaded prefixes.

**Comment by mraleph** [comment]
I have look at the size difference again and discovered that majority of data is pulled through the symbol table by accident.

I have made a [CL](https://dart-review.googlesource.com/c/sdk/+/153768) that fixes that and takes overhead from `0.4%` to `0.01%`. This here is a pure overhead of adding support for deferred libraries and adding checks on those prefixes which are actually deferred (apparently not so many prefixes are).

Given the new information I think I am fine dropping this request - as it is not going to yield significant code size improvement.

| Type                     | Size (Bytes) | Percent | Of total |
| :--- | ---: | ---: | ---: |
| (RO) Instructions        |         1732 |  47.69% |    0.01% |
| (RO) _OneByteString      |          512 |  14.10% |    0.00% |
| (RO) CodeSourceMap       |          416 |  11.45% |    0.00% |
| Function                 |          339 |   9.33% |    0.00% |
| DispatchTable            |          165 |   4.54% |    0.00% |
| Array                    |          121 |   3.33% |    0.00% |
| (RO) CompressedStackMaps |           80 |   2.20% |    0.00% |
| ObjectPool               |           61 |   1.68% |    0.00% |
| Type                     |           56 |   1.54% |    0.00% |
| Class                    |           50 |   1.38% |    0.00% |
| ClosureData              |           35 |   0.96% |    0.00% |
| int                      |           17 |   0.47% |    0.00% |
| TypedData                |           16 |   0.44% |    0.00% |
| Field                    |           14 |   0.39% |    0.00% |
| OneByteString            |           12 |   0.33% |    0.00% |
| ExceptionHandlers        |           11 |   0.30% |    0.00% |
| CodeSourceMap            |           11 |   0.30% |    0.00% |
| PatchClass               |            7 |   0.19% |    0.00% |
| TypeArguments            |           -1 |  -0.03% |   -0.00% |
| (RO) InstructionsSection |           -4 |  -0.11% |   -0.00% |
| Code                     |           -5 |  -0.14% |   -0.00% |
| ArtificialRoot           |          -13 |  -0.36% |   -0.00% |
