### ISSUE TITLE
Allow named function arguments anywhere in the argument list

### ISSUE THREAD

**Issue by lrhn** [dart-lang/language#1072]
Since named arguments are distinguishable from positional ones, allowing named arguments to be placed anywhere in the argument list can be done without changing calling semantics.

It is an advantage in some cases where you want to put a function argument last. Example:

```dart
expectAsync(() {
  ...
}, count: 2);
```

would be more readable as:

```dart
expectAsync(count: 2, () {
  ...
});
```

**Comment by devoncarew** [comment]
@eernstg @chloestefantsova - do you have a link to the spec for this?

**Comment by eernstg** [comment]
> do you have a link to the spec for this?

Not yet, it will be mentioned in https://github.com/dart-lang/language/issues/1948 when it is available.

**Comment by TimWhiting** [comment]
@hixie
Is this syntax for flutter https://github.com/dart-lang/language/issues/1072#issuecomment-403278142 being considered? I imagine it wouldn't be too hard to take advantage of this new feature and make all child or children properties positional without being a breaking change by creating a dart fix.

**Comment by Hixie** [comment]
I doubt flutter would move towards making subwidgets positional, because it would force a very inconsistent API (some widgets have multiple optional children), and would remove some of the affordances that help clarify the APIs (e.g. sliver/slivers vs child/children). We've looked at doing this kind of thing many times, but while it often seems attractive at first, IMHO the complete story is never sufficiently compelling.

**Comment by leafpetersen** [comment]
This feature is now turned on by default at HEAD, and will be available without a flag in the upcoming beta. Work on downstream tooling support is still in progress.

**Comment by rrousselGit** [comment]
Going back to this:

> I doubt flutter would move towards making subwidgets positional, because it would force a very inconsistent API (some widgets have multiple optional children), and would remove some of the affordances that help clarify the APIs (e.g. sliver/slivers vs child/children). We've looked at doing this kind of thing many times, but while it often seems attractive at first, IMHO the complete story is never sufficiently compelling.

I think the sliver case could be dealt with by the linter instead of a naming convention. By maybe annotating sliver widgets with a `@sliver` and have parameters that expect Slivers use an `@expectSliver`

As for widgets which have multiple children, I don't think they should be impacted. 

I'd expect this syntax change to **only** apply to parameters currently called `children` or `child`.
Amything that uses a different name would stay as a named parameter

This would match how React handles this:

```
<Column>
  <Container />
</Column>
```

vs:
```
<Scaffold
  appBar={<AppBar />}
  body={<Container/>}
/>
```

**Comment by mit-mit** [comment]
Enabled in language version 2.17 and above
