### ISSUE TITLE
Explicit support for interfaces

### ISSUE THREAD

**Issue by bwilkerson** [dart-lang/language#1098]
I would like to be able to declare a set of members that define a type without defining a class. I want this type to be usable in the `implements` clause of classes and mixins, and in the `on` clause of mixins and extensions, and, obviously, as a type annotation, but it should not be possible to extend or mixin an interface. Interfaces should be allowed to implement other interfaces, but should not be allowed to extend or mixin any classes.

In my mind, the cleanest syntax for doing this would be to use the builtin identifier `interface` to introduce a declaration similar to, but more limited than, a class declaration. The grammar could probably be improved, but would look something like this:
```
<interfaceDeclaration> ::= 'interface' <identifier> <typeParameters>? <interfaces>?
    '{' (<metadata> <interfaceMemberDeclaration>)* '}'
```
where `<interfaceMemberDeclaration>` would allow methods (including getters, setters and operators) without any bodies.

I would suggest disallowing fields in order to make it clear that interfaces can't introduce fields into the types that implement them.

**Comment by lrhn** [comment]
You can currently make an `abstract class` with a private generative constructor. That should introduce an interface and prohibit any mxin/extension use. (A class declaring a constructor cannot be used as a mixin, a class with no accessible generative constructor cannot be extended).

It would be nice to not have to write the constructor, which only exists for secondary, technical reasons, not because you actualyl want a constructor, and an `interface` declaration would achieve that.

**Comment by eernstg** [comment]
Long ago, the language team had a discussion about approximately 4 bits of "permissions" for a class:

1. Can an instance of this class be created?
2. Can a class extend this class? Controls `extends`.
3. Can a class mix in this class? Controls `with`.
4. Does the declaration introduce a type? Controls `implements`, `on` with extensions/mixins, usages as a type.

We can disable instance creation with `abstract`, but we can't specify the other permissions (or deny them) declaratively. Some combinations are not very useful, and it may be too verbose to specify the bits separately (`abstract class C ... deny extends, deny with, deny implements {}`), so we may want to package certain combinations using special keywords (like `interface` which would imply `deny extends, deny with`).

The idea that an interface `I` should not be able to extend a class is new. At first, it wouldn't make a difference (because no instance and no subclass of `I` can be created, so nobody can ever observe any implementations associated with `I`).

But if we add in the notion of 'interface default members' (which are automatically mixed into any concrete class implementing `I` but not implementing the given member) then it would be useful to be able to add implementations to the interface using `extends` or `with`, such that the interface default method implementations wouldn't have to be duplicated textually in the case where they can be obtained using `extends` or `with`.

**Comment by passsy** [comment]
From a language standpoint I'm quite fine and satisfied with what `abstract class` offers. 

But I really like the `interface` keyword, and miss it regularly when teaching Dart. Especially when working with juniors, doing their first babysteps in OOP, `abstract class` and `class` blur into the same thing.

[The Dart language spec](https://spec.dart.dev/DartLangSpecDraft.pdf) has a whole chapter about interfaces (Capter 11), demonstrating the importance of this concept.

> Each interface is the implicit interface of a class, in which case we call it a class interface, or a combination of several other interfaces, in which case we call it a combined interface.

Because interfaces in Dart can only be created implicitly, I vote for the `interface` keyboard to allow creating an interface *explicitly* without inheriting the characteristics and restrictions of classes and mixins.

**Comment by iiw** [comment]
Google: "we'll reduce the complexity by removing an interface keyword, you could use abstract class instead"
Real world: "thanks, Google, okey, Google, now we can't read the code and define where is abstract classes and where is just an interface, and we have to make some unusual things to restrict abstract classes extension and make its behaviour like interface" 😄

**Comment by munificent** [comment]
The [proposal I wrote for "packaged libraries"](https://github.com/dart-lang/language/blob/master/working/packaged-libraries/feature-specification.md#syntax) includes an `interface` keyword. It doesn't work exactly like `interface` in other languages, though. With that proposal, an `interface` declaration *may* contain members. What it means is that code *outside of the package* where the interface is declared cannot directly construct or extend it. In other words, to them, it appears as an interface.

**Comment by SAGARSURI** [comment]
I have confusion regarding the implicit interface every Dart class have. Does that mean I don't need an abstract class to define a contract for an implementation?  Instead, I can inject the implementation directly because it has an implicit interface? Isn't the implementation of `PaymentRepository` visible to `CheckoutUseCase`? 
```
class PaymentRepository {
  PaymentRepository(this._pay);
  
  final FlutterPay _pay;
  
  bool canMakePayment() {
    return _pay.canMakePayment();
  }
}
```
```
class CheckoutUseCase {
  CheckoutUseCase(this._repo);
  
  final PaymentRepository _repo;
  void execute() {
    if(_repo.canMakePayment()) {
      //Do something
    }
  }
}
```

**Comment by eernstg** [comment]
If you're thinking about interfaces in a way which is similar to the situation in languages like Java and C# then it's all about specifying the formal contract (that is, the stuff that the type analysis takes into account, like names and signatures of members, but nothing about behavior).

The point which has traditionally been emphasized is that you're free to change the implementation as long as your code only depends on interfaces, not on specific implementations. This has been a core idea of software design since Parnas wrote [On the criteria to be used in decomposing software ...](https://dl.acm.org/doi/10.1145/361598.361623) (it's not hard to find this paper outside any payment walls).

In Dart this principle has been taken yet one step further: _Every_ class declaration implicitly gives rise to the creation of an interface in this sense. So when you're asking 

> Isn't the implementation of `PaymentRepository` visible to `CheckoutUseCase`?

the answer is No!, because we're able to replace that implementation by any other implementation that we may prefer, as long as it implements the same interface:

```dart
class PaymentRepository {
  PaymentRepository(this._pay);
  final FlutterPay _pay;
  bool canMakePayment() {
    return _pay.canMakePayment();
  }
}

class CheckoutUseCase {
  CheckoutUseCase(this._repo);
  final PaymentRepository _repo;
  void execute() {
    if(_repo.canMakePayment()) {
      //Do something
    }
  }
}

// If we want to use a different payment repository, we can do this:

class MyPaymentRepository implements PaymentRepository {
  MyPaymentRepository(this._pay);
  final FlutterPay _pay;
  bool canMakePayment() {
    // ... whatever you want.
  }
}

void main() {
  var x = CheckoutUseCase(MyPaymentRepository(...));
  ...
}
```

**Comment by passsy** [comment]
This issue can be closed. 

Dart 3 introduced [class modifiers](https://dart.dev/language/class-modifiers) allowing us to define `abstract interface class` which acts as pure interface.

```dart
abstract interface class Car {
  void honk();
}

void main() {
  final car = Car();
  // Error: The class 'Car' is abstract and can't be instantiated.
  // final car = Car();
  //             ^^^
  // Error: Compilation failed.
}
```

**Comment by munificent** [comment]
Yeah, I'm going to go ahead and close this. We *could* allow bare `interface Foo { ... }`  declarations which means `abstract interface` and also prevent you from having non-abstract members in the body, but the latter doesn't seem like a very *useful* feature to me. It's your declaration, so if you don't want non-abstract members in there, don't write any.

Given that, I think just having `abstract interface` is sufficient.
