### ISSUE TITLE
Should `e!` be a valid const expression?

### ISSUE THREAD

**Issue by leafpetersen** [dart-lang/language#1112]
Null safety adds the new expression `e!` as a null assertion operator that throws if `e` is `null`.  It is not currently specified as a valid constant expression.  Should we add this as a valid const?

```
class Foo {
  final int y;
  const Foo(int? x) : y = x!;
}
void main() {
  const Foo(null);
}
```

Note that the analyzer currently rejects the above, but the CFE hits an internal error on it.

cc @jacob314 @eernstg @munificent @lrhn @jakemac53 @natebosch @stereotype441 @a14n

**Comment by eernstg** [comment]
It seems straightforward, and perhaps it would be surprising to many developers if it is not supported.

However, we could also say that the null check can be performed using `assert(x != null)`. This yields the same expressive power (and it might be enabled at all times, https://github.com/dart-lang/language/issues/447). The assertion could also be considered better documentation than a `!` in an expression.

**Comment by lrhn** [comment]
I'm not sure it's very important. 

When doing constant computation, it's rare to have an expression which does not have the exact type of the constant value, given that the constant value is definitely known. So, for compile-time constant expressions, I doubt we'll see much need for coercing from `T?` to `T`, because it will already be `T`.

The other use would be in *potentially constant* expressions (const constructor initializer list expressions).
It still doesn't make much sense to pass something in as `T?` and then do `!` on it unconditionally, and if you do it conditionally, then you've already promoted the variable. The only real use-case would be having multiple linked parameters, where testing one of them implies that another is non-null (or it's an error).

I think it makes sense to make `e!` a potentially and definitely constant expression when `e` is, for orthogonality and consistency, but I also think it's not going to be in high demand.

**Comment by munificent** [comment]
I think we should support `e!` since we do support `e as T` now and `!` is a shorthand for the same kind of cast.

**Comment by eernstg** [comment]
`e!` is a potentially constant expression today if `e` is ditto, and constant if `e` is constant and evaluates to a `bool`.
