### ISSUE TITLE
Short form of if statement

### ISSUE THREAD

**Issue by dmitryuck** [dart-lang/language#1126]
if (cond) doSmth;

to be equivalent to:

cond ? doSmth;

kind of short form of:

cond ? doSmth : elseSmth;

**Comment by lrhn** [comment]
The reason `if` statements can omit the `else` branch is that there is a "no-op" statement: The empty statement which does nothing when executed. Doing nothing is an option for statements.

The conditional expression operator, `e1 ? e2 : e3`, is an expression. Expressions must evaluate to a value (or throw). Doing *nothing* is not an option, so even if we allowed `e1 ? e2` as an expression by itself, we'd still have to define what `var x = e1 ? e2;` it would do if `e1` evaluates to `false`.
The simplest options are throwing and evaluating to `null`. Neither is a particularly *good* choice. Introducing a `null` implicitly can easily be surprising, and it's not so much shorter than `e1 ? e2 : null` that there is any *real* advantage to outweigh the loss of explicit readability.
Throwing has the same issues, and whatever error we'd throw would be arbitrary. It's better to do `e1 ? e2 : throw TheExactErrorYouWant()` than having to catch a `MissingElseError` and convert it.
The only place where it would actually make a difference is where the value of the expression is never used, like if someone is using a conditional expression instead of an `if` statement: `e1 ? print("something");` instead of `if (e1) print("something");`. There are people out there who will do things like that, but supporting that kind of shenanigans and code-golfing is a non-goal.

The way Dart's syntax is currently wired up, allowing you to omit the else-branch of a conditional expression would be *very* bad for parsing. We allow `{e1 : e2}` as a map literal, but if `e1` could be `e3 ? e4`, then `{e3 ? e4 : e2}` would be ambiguous. It could either be a map literal or a set literal. Adding ambiguities to that grammar is something we try to avoid unless the feature it enables is worth the pain.

So, all in all, that particular syntax shorthand is so *very* unlikely to happen that it's not worth considering.
