### ISSUE TITLE
please consider support is! in generic type declaration

### ISSUE THREAD

**Issue by Silentdoer** [dart-lang/language#1164]
for example:

```
class SplayTreeMap<K is! dynamic, V> extends _SplayTree<K, _SplayTreeMapNode<K, V>>
    with MapMixin<K, V> {...}
```

then the following code will not be analyzed successfully:

```
var splayTreeMap = SplayTreeMap();
```

because splayTreeMap is SplayTreeMap<dynamic, dynamic>;
user must use:

```
var splayTreeMap = SplayTreeMap<aConcreteType, dynamic>();
```

or:

```
SplayTreeMap<aConcreteType, dynamic> splayTreeMap = SplayTreeMap();
```

**Comment by Silentdoer** [comment]
thanks for your reply, my mean is SplayTreeMap in dart:collection should be refactor to class SplayTreeMap<**K extends Comparable<K>,** V> extends _SplayTree<K, _SplayTreeMapNode<K, V>>
    with MapMixin<K, V> {...} ?

**Comment by lrhn** [comment]
Changing a platform class in this way would be breaking, so we probably won't do it.

I hope that we'll at some point do a change to the language that makes `dynamic` less likely to occur by accident, perhaps changing the default bound from `dynamic` to `Object?` (since it will be post null safety) so you won't get `dynamic` by omitting type parameters, only by explicitly asking for it. That too would be a breaking change, but we have versioning of the language so migration can be gradual, and in this case migration can likely be automated.

So, a "no" to changing `SplayTreeMap` right now.

**Comment by Silentdoer** [comment]
with nnbd, if i need T can be Object and Object?, but cant not be dynamic, how to do?

**Comment by lrhn** [comment]
You cannot allow `Object?` and disallow `dynamic` because the two are indistinguishable by subtype checks, and the only constraints we have on type parameters are subtype checks. 

It is as if `dynamic` only exists at compile-time, as a special alias for the type `Object?` which allows you to invoke any member on it, and to implicitly down-cast to any type. At run-time, there is no way to distinguish a `List<Object?>` instance from a `List<dynamic>` instance (except comparing run-time types).

That also means that you shouldn't try. If you class accepts *any* type (which it must if it accepts `Object?`), then there is no reason to prevent a caller from passing `dynamic`. It will work, because it works for every type.
