### ISSUE TITLE
String is not type of bool

### ISSUE THREAD

**Issue by Gorniv** [dart-lang/language#1172]
Error:
```dart
void main() {
  final Map<String,dynamic> message = {'link':'test'};
  final link = message['link']?.toString() ?? message['data'] != null ? message['data']['link']?.toString() : null;
  print(link);
}
```
Work:
```dart
void main() {
  final Map<String,dynamic> message = {};
  final link = message['link']?.toString() ?? message['data'] != null ? message['data']['link']?.toString() : null;
  print(link);
}
```

Work:
```dart
void main() {
  final Map<String,dynamic> message = {};
  final link = message['link']?.toString() ?? testM();
  print(link);
}
String testM(){
  return 'test';
}
```

**Comment by lrhn** [comment]
The looks correct. What behavior did you expect?

If you want the error to go away, you could put parentheses around `(message['link']?.toString() ?? message['data'])`.

**Comment by munificent** [comment]
I *think* this issue is about the relative precedence between `??` and `!=` being unexpected. I don't disagree with that in principle—any time you add a new operator, users won't have much intuition about its precedence.

But we have shipped the operator already, so we can't change its precedence without massive breakage.
