### ISSUE TITLE
Function should be rename function keyword like C# delegate

### ISSUE THREAD

**Issue by Silentdoer** [dart-lang/language#1180]
void Function() to void function(), otherwise it is confused with abstract class Function

**Comment by lrhn** [comment]
The abstract `Function` class is already special in Dart. All functions types are subtypes of the type `Function`, and you can call an object of type `Function` like it had type `dynamic`. It's special, so using it in `void Function()` as well fits right in, rather than inventing a new special word.

Changing it is a large breaking change with very little obvious value, so it's very unlikely to happen.
