### ISSUE TITLE
It's not consistent in Function type

### ISSUE THREAD

**Issue by Silentdoer** [dart-lang/language#1181]
typedef kk = void Function(int);

void test(void Function(int) k) {
  print(k.runtimeType);  // prints (int) => int
  print(k is kk);  // prints true, why? ss is (int) => int but kk is (int) => void
  k(4);
}

void main() {
  int Function(int) ss = (int s) {print(8);return 0;};
  print(kk);  // prints (int) => void
  print(ss.runtimeType);  // prints (int) => int
  test(ss);  // it's ok, why ?
}

**Comment by Silentdoer** [comment]
and may be we can support return void? like rust return ();, then when () {print(0);return void;} will be infer () => void not () => Null

**Comment by Silentdoer** [comment]
reflectType(void Function(int)) can not be analyze successfully.
but can be typedef ss = void Function(int), reflectType(ss) is ok.

**Comment by lrhn** [comment]
In Dart `int Function(int)` is a subtype of `void Function(int)` because `int` is a subtype of `void`.

If you want to return something inferred as `void`, use `return;` without a value. 

`reflectType` takes an `Type` object and reflects its type. `void Function(int)` is not a valid expression, but `ss` is because it's a single identifier (which evaluates to the `Type` object for the type it denotes).

**Comment by Silentdoer** [comment]
Hi, thanks for your reply,
int is a subtype of void, but void test() {return 0;} is error,
interred as void, use return;  () {print(0);return;} currently is still () => Null, it's will be changed in future?

**Comment by lrhn** [comment]
A `void` returning function is implicitly stating that you should *not* use the value it returns.
Because of that, explicitly actually returning a value using `return e;` is unnecessary and probably a mistake. 
To protect the user, the language disallows that.

The current inference may choose to make the actual run-time type of a function expression be `Null Function()`. That's still a valid subtype of `void Function()`, and at run-time there is no good way to distinguish `void Function()` from `dynamic Function()` anyway, they behave the same wrt. subtyping. The `void` restrictions is mainly for static checking.
