### ISSUE TITLE
Allow to declare a variable with the same name as a function

### ISSUE THREAD

**Issue by danielgomezrico** [dart-lang/language#1186]
# Current
Currently if you have a builder function with a name and you try to use the same name on a variable there's a compilation error saying:

> Local variable 'function_name' can't be referenced before it is declared - line 4 

# Example

```dart
String name() => 'Juan';

main () {
  final name = name();
  print(name);
}
```

Error:
> Local variable 'function_name' can't be referenced before it is declared - line 4 

Here is a running example.
https://dartpad.dev/d0ea4ca5673aec3b065dd9946953f8c2

The problem with this is that you endup having to give a different name to your variables than your functions and this is sometimes cumbersome or you endup naming things like `aName`.

# Expected
There are no errors, the compiler understands that Im using a function that is declared instead of the same variable that I am just declaring.

I mean, this returns no errors.
```dart
String name() => 'Juan';

main () {
  final name = name();
  print(name);
}
```

**Comment by lrhn** [comment]
The issue here is that the name of the variable is in scope in its own declaration.
It's actually in scope for the entire block, you'll also get an error for:
```dart
String name() => "name";
main() {
  var somethingElse = name();
  var name = "other";
}
```
because the later `name` declaration shadows the outer `name` function, even before the declaration.

You are only allowed to *use* the variable after its's been declared, so there is no big advantage to the current design. It won't, say, allow you to declare mutually recursive functions inside another function.,

**Comment by munificent** [comment]
What would you expect this to do:

```dart
main () {
  String name() => 'Juan';
  final name = name();
  print(name);
}
```

Or:

```dart
String name() => 'Juan';

main () {
  final name = name;
  print(name());
}
```

Dart does not have separate namespaces for functions and variables. (It is a [Lisp-1](https://stackoverflow.com/questions/4578574/what-is-the-difference-between-lisp-1-and-lisp-2) in the obscure PL historical terminology.) This is really valuable because it makes working with closures easy. You can store a function in a variable and then invoke just like you invoke any other function. If we put functions and variables in different namespaces, then we'd need special syntax for getting a reference to a function and invoking a function stored in a variable.

**Comment by danielgomezrico** [comment]
- 1 case: it should fail compiling the second line (`final name =`) saying that you cant redefine name since its already defined in the name function.

- 2 case: it should create a shadow variable for this scope, so everyone that uses `name` inside of the main function would use the variable declared in this scope and if someone else outside of it calls name it uses the name function "normally".

This reference talks about it https://en.wikipedia.org/wiki/Variable_shadowing.

What is currently happening is that it fails compiling saying `Local variable 'name' can't be referenced before it is declared`, which is kind of a weird error to me since it does not make any sense to use the same variable that I am currently initializing in the "initializing code", it does not fail saying that there's already a function with that name and that I can not reuse it in my variable.

I feel this as a pain since on Kotlin it works like this but they do have a different syntax for using a function reference, personally I think that is a good thing to have a different syntax for that since you declare your intention of using a function reference and don't hide this as an implicit behaviour, but it's a matter of personal preference too.

**Comment by munificent** [comment]
> * 1 case: it should fail compiling the second line (`final name =`) saying that you cant redefine name since its already defined something with that name in this scope.

So the proposal is that you cannot declare both a function and a variable with the same name in the same scope, but when *calling* a function, it ignores any variables with that name in enclosing scopes and only looks for functions?

That could work, but I think it's fairly unusual. Also, this would be a large breaking change for Dart so isn't something we could feasibly do.

> What is currently happening is that it fails compiling saying `Local variable 'name' can't be referenced before it is declared`, which is kind of a weird error to me since it does not make any sense to use the same variable that I am currently initializing in the "initializing code", it does not fail saying that there's already a function with that name and that I can not reuse it in my variable.

Yeah, it is a somewhat weird error. There is an interesting corner case with scoping local declarations. Does the new variable come into scope before or after its own initializer? Whichever answer you pick can lead to pretty confusing, hard to read code. So Dart, like other languages, makes it essentially off-limits. It says the variable is in scope but you can't use it. That way you get an error instead of being left with valid code that likely does not do what you want.

C# does something similar by saying that two references to the same identifier in the same block must always refer to the same variable. Java simply disallows shadowing entirely.

I'm going to close this because name resolution is very fundamental and not something we have the luxury of changing since it would break lots of existing code. Sorry we can't do something that you like better here, but name resolution always involves trade-offs. There's no perfect solution.
