### ISSUE TITLE
Improving string interpolation mechanism

### ISSUE THREAD

**Issue by albertodev01** [dart-lang/language#1196]
So far I like how single objects are interpolated.

```dart
final age = 25;
print("I'm $age yr old");
```

However, I don't like how multiple values can be interpolated.

```dart
final age1 = 25;
final age2 = 36;
print("We're $age1 and $age2 yr old");
```

This is especially tedious when we try to access members of a class.

```dart
print("A = ${A.name} | B = ${B.name} | C = ${C.name}");
```

------

Could we have something like this instead (for multiple interpolations)?

```dart
print($"A = {A.name} | B = {B.name} | C = {C.name}");
```

Basically, the dollar sign at the beginning of the string just requires braces to interpolate values.

```dart
// Current
print("A = ${A.name} | B = ${B.name} | C = ${C.name}");

// Desired
print($"A = {A.name} | B = {B.name} | C = {C.name}");
```

**Comment by mateusfccp** [comment]
I don't see how this is better. You save `n - 1` characters such that `n` is the number of interpolations. Doesn't seem to be worthy the effort.

**Comment by lrhn** [comment]
The cost of using `$"a-{b}-c-{d}-e" is that you have to use braces even on simple identifiers. It would otherwise be the *shorter* `"a-$b-c-$d-e"`.

Switching between `$"a {foo} b {bar.baz} c"` and `"a $foo b ${bar.baz} c"` requires rewriting every single-identifier interpolation (because I don't expect most people to want to write extra braces like `"a-${foo}-b"` unnecessarily.
So, it's a feature with a migration cost when you move to or from the feature.
Currently each interpolation can be treated individually.

I can easily imagine that we'd end up with style guides saying to use `"a $foo c"` when possible, `"a ${foo.bar} c"` when necessary, and `$"a {foo.bar} {baz.qux} d"` only when you have multiple non-identifier interpolations in the same string, and no single-identifier interpolations. Then adding something to the string which changes the preference would require you to go over the entire string to switch interpolation representation.

I'm also not sure the advantage is worth the extra complexity. It's not a big advantage. It's a small complexity from a technical perspective, but a somewhat larger complexity for users needing to choose between the different options.
