### ISSUE TITLE
Types of interest differ for different loops, is that useful?

### ISSUE THREAD

**Issue by eernstg** [dart-lang/language#1203]
Consider the following program snippet:

```dart
main() {
  bool b = true;
  Object i = 42;
  ... // Insert loop here!
  i = 24; // Promote iff `int` is a type of interest.
  i.isEven; // Error unless `i` was promoted.
}
```

The missing statement is one of the following loops:

```dart
while (b) { // Does not make `int` a type of interest for `i`.
  if (i is int) print("");
}

do { // Does make `int` a type of interest.
  if (i is int) print("");
} while (b);

for (int j in []) { // Does make `int` a type of interest.
  if (i is int) print("");
}
```

Promotion occurs when we insert the do-while loop or the for loop into the example, but not if we insert the while loop.

There is no soundness issue because types of interest never force an unsound promotion, they just prevent some sound ones where the type is not 'of interest'. So the control flow differences can't justify the different treatment (also, the do-while loop is guaranteed to reach the type test, but the for loop and the while loop are not, so that shouldn't single out the while loop anyway).

Perhaps we should adjust the treatment of the while loop such that types of interest emerging in its body are included? Alternatively we could change the treatment of for loops to exclude them. The [flow-analysis spec](https://github.com/dart-lang/language/blob/master/resources/type-system/flow-analysis.md) seems to omit the types of interest from the body of a while loop (and doesn't include for loops), so we may need to make an adjustment.

@stereotype441, WDYT?

**Comment by munificent** [comment]
> Perhaps we should adjust the treatment of the while loop such that types of interest emerging in its body are included?

+1 from me, for what it's worth. :)

**Comment by lrhn** [comment]
Agree. There is a show of interest in the code, whether it's executed or not.

Even if we only care about executed tests, I'd have expected that `for` and `while` work the same (body not guaranteed to be run) and `do`/`while` could then be different (body guaranteed to run). The current behavior feels like a bug, no matter what consistent behavior we'd want.

**Comment by stereotype441** [comment]
Agreed, it's really surprising that different types of loops would interact with types of interest differently like this.  I'm not sure exactly what's going on.  I will look in more detail when I return from vacation on Wednesday.

**Comment by stereotype441** [comment]
I looked into this more deeply.  The reason it's happening is that currently, we only update types of interest forward when doing joins; we don't update them when doing conservative joins.  This means that if the flow control path from the body of the loop to the code after the loop goes through a backwards branch, then that's handled by a conservative join before we even see that the type became of interest in the first place, so the fact that the type is of interest is lost.  Whereas if the flow control path from the body of the loop to the code after the loop doesn't go through a backwards branch, then the type of interest information is preserved.  This is why `do` loops preserve types of interest whereas `while` and `for` loops do not: because `while` and `for` loops have to jump from the bottom of the loop body back to the top of the loop to evaluate the condition, whereas `do` loops evaluate the condition after the loop body, so there is a control flow path from the bottom of the loop body to the subsequent code that doesn't involve a backwards jump.

The weird exception is "for each" loops.  Flow analysis doesn't model them strictly according to their desugared representation.  It models them more like this:
```dart
T id1 = E;
var id2 = id1.iterator;
if (id2.moveNext()) {
  do {
    D id = id2.current;
    { S }
  } while (id2.moveNext());
}
```

I think the easiest fix is to add special logic to the handling of `while` and `for` loops that explicitly propagates the types of interest from the bottom of the loop body to the code that follows, in spite of the fact that there is no direct flow control path.

**Comment by stereotype441** [comment]
Implementation fix out for review: https://dart-review.googlesource.com/c/sdk/+/162483
