### ISSUE TITLE
Error on using inferred deferred type?

### ISSUE THREAD

**Issue by eernstg** [dart-lang/language#1209]
Thanks to @lrhn for inspiring this issue. Consider the following program:

```dart
// LIBRARY 'lib.dart'.
class Foo { int bar = 1; }
Foo foo() => Foo();

// LIBRARY 'main.dart'.
import 'lib.dart' deferred as p;

void main() async {
  await p.loadLibrary();
  var x = p.foo(); // Inferred type of `x` is `p.Foo`.
  var y = x.bar; // Confirmation: `x` has `p.Foo` members.
}
```

This program is accepted with no compile-time errors by `dartanalyzer`, `dart`, and `dart2js`, and executions by means of the latter two have no dynamic errors.

However, if we replace the inferred type `p.Foo` by an explicitly declared type `p.Foo x = p.foo()` then the required compile-time error is reported.

We could consider this to be a bug in all tools, and ask for an implementation of the missing errors.

We could also allow the use of deferred types as type annotations, and rely on the fact that it already seems to work for an inferred type to indicate that it might be supported already, we just need to stop reporting the error.

At a more principled level, it is a dynamic error if the deferred load turns out to load a different library than the one which was denoted by the deferred `import` clause at compile-time, and this means that it would not be possible to introduce unsoundness by analyzing one library _L1_ at compile time, and using the deferred types as type annotations or in type tests/checks, and then loading a different library _L2_ at run time and reinterpreting the meaning of those types.

For new usages of deferred types (say, `e is T`, which is currently a compile-time error which is enforced), this treatment would imply that more expressions could fail at run time because the deferred library has not yet been successfully loaded. There may be an implementation effort here, but even in this case there must already be support for a dynamic type check based on assignments like `x = e` where `e` has static type `dynamic`.

The change to allow deferred types would be non-breaking. The change to report the error for inferred deferred types would be breaking, and the breakage could be widespread. In any case, it is not obvious to me that the current situation can be justified conceptually, it just looks like an accidental inconsistency.

@lrhn, @leafpetersen, @munificent, @natebosch, @stereotype441, @jakemac53, WDYT?

**Comment by lrhn** [comment]
We need to rethink deferred loading for Dart 2.
The Dart 1 model of only loading the source at run-time is not viable in a statically checked language.

We need to know the imported library at compile-time in order to do static type checking.
Then it also makes sense to know the types statically and use them (like we already do through inference). Let's say that I can use `p.Foo` a type, even when `p` hasn't been `loadLibrary`'ed yet.

There is no "make a type partially available". We learned that with `void` - once it can occur as a type in one place, inference and type arguments can cause it to occur *anywhere*, so I won't try to restrict the type to only occurring as type annotations, or not in `is`/`as` checks, that's bound to fail anyway.

Then we either make it a run-time error to get into a situation where we need to check against the type (any subtype check, in either direction), or we make the type work prior to loading the rest. The latter would mean that we need *some* knowledge of the type available before the library has been loaded, at least the subtype relations of `p.Foo`.
```dart
dynamic x = ...;
print(x is p.Foo); // Needs to check something <: Foo
p.Foo? z = x;      // Needs to check something <: Foo?
p.Foo? getFoo() => null;
Function f = getFoo;
print(f is Bar Function()); // Needs to check p.Foo <: Bar.
```

So, we'll at least need some representation of the type `p.Foo` before `p` is loaded.
* If we make the type not work before being loaded, we need a placeholder type which causes any dynamic subtype check to throw (and then we'll fill in the placeholder when `p` is loaded.)
* Otherwise we need the subtype information (but not necessarily member information). Then we only load the code and data deferredly, the type hierarchy is known.

There is also `dart:mirrors`. When we can use the type as a type annotation, we can reach it through reflection, also before `p` has been loaded. I'd be fine with making `dart:mirrors` throw on any attempt to use (or even create) a `TypeMirror` of `p.Foo` before the `Foo` type has been loaded in any way. (Obviously, if the same type is imported both as deferred and non-deferred, it's always available to mirrors, and it might have been loaded through a different deferred library before `p` is loaded).


We'd still only allow the deferred type as a *type*. You can implement a deferred type, but you cannot extend a deferred class or mix in a deferred mixin. You cannot access deferred constants at compile-time.

-----

As for "loading a different library", I think we should simply not consider it possible.

The Dart program you compile is the Dart program you run. If you manage to split that executable into multiple parts and link them at run-time, good for you, but the code should work the same whether your deferred imports actually delay anything or not.
Loading a *different library* is simply not something we consider at the spec level, it's a bug if it happens, and we do not give any semantics to that. Preferably, it cannot happen. Maybe we put checksums in the deferred parts, and check them on load. Maybe we don't, but we recognize that if you are not loading the deferred part you compiled at the same time as the main program, you are no more following Dart semantics than if you write arbitrary bytes into the VM heap. It might do *something*, but you shouldn't look to the Dart spec for what that is.

**Comment by eernstg** [comment]
> So, we'll at least need some representation of the type `p.Foo` before `p` is loaded.

If we treat usages of the type `p.Foo` exactly like all other usages of entities provided by the deferred-loaded library, the type test and type check is a dynamic error until loading has completed successfully. I'm sure we can find a way to get that behavior, using a placeholder type or some other mechanism.

> As for "loading a different library"

Wouldn't it be reasonable for an implementation to raise a dynamic error if the program is compiled with a deferred import resolving to a given library, and the `loadLibrary` implementation encounters a 'No such file' error. Do you require the executable to contain all deferred-loaded libraries, such that this will never happen? Otherwise I think we need to specify just enough to allow for the possibility that something goes wrong at `loadLibrary` (such as: the library is gone, or it's a different library).

We may be able to say these things in a way that sounds very much like the library load doesn't actually occur at run time, but I don't think we should specify it in such a way that the library _cannot_ be loaded at run time.

**Comment by lrhn** [comment]
> If we treat usages of the type p.Foo exactly like ...

We have to define what "usage of the type" means.

I'm generally leaning towards any subtype/instance-of check involving the type.
Not sure we can prevent it being used as a type argument (or being part of a type argument). Once it's a type, a lot of type passing-around is static. We could perhaps prevent it from occurring in run-time type arguments (arguments to collection literals, constructors or generic functions), but not to type constructors.

Take:
```dart
const C<p.Foo>? x = null;
```
This would then be allowed, it's a type constructor, not an object constructor (so nobody gets access to the type variable).
```dart
const C<p.Foo>? x = C();
```
would be a compile-time error because it would be a run-time error to evaluate `C()` before calling `loadLibrary`, and it has an implicit type argument of `p.Foo`.

**Comment by leafpetersen** [comment]
See also https://github.com/dart-lang/sdk/issues/35311

cc @sigmundch @joshualitt who have been doing some thinking around this.  

dart2js can in principle split out the type from the class.  @sigmundch was going to check with the VM folks to see if a similar split might be possible on their end.

**Comment by eernstg** [comment]
The discussion in dart-lang/sdk#35311 seems to imply that, with a separate representation of classes and types the 'code-split' of the program that dart2js performs could make the types available during the entire program execution, and the VM may be able to do the same (if needed).

Deferred types can then be used (for all purposes, in particular as type annotations, as type arguments, and in type tests/checks) without throwing, even before the deferred load has been completed, and type tests/checks on deferred types will run just as fast as other type tests/checks. That would of course be convenient.

**Comment by eernstg** [comment]
Just discussed the issue with @mraleph.

It is a substantial implementation task to separate types and classes on some configurations of the VM (esp. AOT), and this means that it is not going to be easy to support a semantics where all usages of deferred types "just work". Other configurations of the VM basically treat deferred imports the same as immediate imports, so it just works.

Hence, the following kind of specification would fit very well for the VM: **It is an implementation specific choice** whether the need for a run-time representation of a deferred type is supported before a successful completion of `loadLibrary`.

This specification may be inconvenient for developers, though: They have to be really careful when developing code using tools where the early use of deferred types just works, and it may break as soon as they start running the code in a context where it is a dynamic error to use a deferred type until the deferred load has been completed. Even worse, those errors may occur in a large number of locations, and when it is concerned with a deferred type it may be hard to find.

**Comment by sigmundch** [comment]
See also https://github.com/dart-lang/language/issues/1149 - Should we merge this issue and that one?

One point I was discussing there is that we think allowing deferred types will be better UX overall: some developers find it limiting that they can't get much of type safety when using deferred types - they are either forced to use dynamic or they have to refactor the logic to defer not just the types but also any logic that may use them.

That bug also touches superficially on the VM challenges from my early conversations with @rmacnak-google. Today, because they only defer machine code, referring to types is not an issue yet. Later on they do plan to defer class types because method dictionaries are big. @rmacnak-google also mentioned that it would require some refactoring in the VM to split types from classes.

> (@sigmundch can dart2js generated code answer these queries on types without loading the deferred bundle containing C?)

Yes, dart2js now represents all subtyping relations in a separate table without references to the underlying class. So all subtyping checks are now supported.

**Comment by eernstg** [comment]
Issue #1149 covers the same area as this one, so let's take the discussion there. Closing.
