### ISSUE TITLE
Allow "implements" for generics bounds

### ISSUE THREAD

**Issue by feinstein** [dart-lang/language#1241]
I understand the problems of multiple inheritance by allowing multiple `extends`, but AFAIK `implements` doesn't suffer from this, as it's up to the developer to provide the correct implementation.

having something like:

```dart
class MyClass<T extends BaseClass implements MyInterface> {
...
}
```

Would be very good for improving the safe usage of `T`, without having to go to `dynamic`.

**Comment by lrhn** [comment]
The syntax is not the issue. We could allow multiple extends as well, `<T extends BaseClass extends MyInterface>`. 
I assume your `implements` would mean exactly the same thing as the `extends`, so it really should be another `extends`.

The actual problem is that by having multiple bounds, we introduce intersection types into the type system, something Dart doesn't currently have. Intersection types are usually coupled with union types, #1222, so that's the real issue to look at for this feature.

If we want union and intersection types, we need to add them throughout the type system, just allowing multiple bounds on a single type variable won't work.

**Comment by feinstein** [comment]
Well I am no language expert but I thought there was a difference between `extends` and `implements`.

Here's what I know: `extends` suffers from multiple-inheritance problems, like diamond inheritance, where the compiler has no idea from whom to get a specific implementation. But `implements` on the other hand is just a contract, it just says there's a signature there and the implementation is up to the class it self.

At the compiler level I really don't know if these differences are relevant or not for type bounds, maybe instead of `extends` or `implements` the language could have just `is` e.g.: `<T is BaseClass && MyInterface>`, since `is` signifies both inheritance and contract.

**Comment by eernstg** [comment]
The point is that `extends` when used to specify the bound of a type parameter has nothing to do with `extends` when used to specify the superclass of a class. The former is simply a subtype constraint, so `X extends num` is satisfied when the value of `X` is a subtype of `num`; but with `class C extends D ...`, the implementation of `C` can include methods that are inherited from `D` (possibly from some superclass of `D`). Multiple inheritance issues are only relevant for the use in a class.

So if we were to introduce support for `implements` in a type parameter bound it wouldn't have a new meaning, it would simply be yet another way to specify a subtype constraint. So for a type parameter `X`, `X extends A implements B` and `X extends A, B` and `X extends A && B` would all be exactly the same constraint on `X`, namely that it must be a subtype of `A` and it must be a subtype of `B`.

Having that means having intersection types; having intersection types anywhere in the type system generally means that it has to be taken into account everywhere in the type system; and that's a major addition to the language. Union and intersection types go together (again: if we have one then the other one is inevitable), and they might be added to Dart, but it doesn't make sense to try to add just a little bit of support for it so that's a rather large feature request. Cf. #83.

**Comment by feinstein** [comment]
@eernstg thank you for the thorough explanation, it was very insightful.
