### ISSUE TITLE
Least upper bound involving FutureOr has a soundness problem

### ISSUE THREAD

**Issue by eernstg** [dart-lang/language#1250]
The function [**UP**](https://github.com/dart-lang/language/blob/master/resources/type-system/upper-lower-bounds.md#upper-bounds) does not have any cases covering `FutureOr`.

I believe this implies that such examples as `UP(FutureOr<int?>, num)` does not match any rules.

In particular, the last rule about the 'least upper bound of two interfaces as in Dart 1' would treat `FutureOr<int?>` as an interface type, but such types are assumed to be subtypes of `Object`, and that is not true for `FutureOr<int?>`. So we can't just pretend that `FutureOr` has `Object` as a superinterface and proceed with the Dart 1 algorithm, because it is unsound to let `UP(FutureOr<int?>, num) == Object`.

The implementations do indeed fail to handle this today, e.g., with the following example:

```dart
import 'dart:async';

bool condition = true;

void main() {
  FutureOr<int?> x = null;
  num n = 1;
  var z = condition ? x : n;
  // Unsound: `z` has the type `Object` and the value null.
  Object o = z;
  print(o); // 'null'.
}
```

This crashes the front end and is accepted with no issues by the analyzer.

If we adjust 'Note that both types must be class types at this point' to 'Note that both types must be class types or `FutureOr<T>` for some `T` at this point' in the two subtype rules then they will handle some of these cases, e.g., `UP(FutureOr<int>, int) == FutureOr<int>`.

A set of sound rules could be expressed as follows (but we may not wish to use them directly because they use nested applications of **UP**, and they rely on least upper bound being commutative):

- **UP**(`FutureOr<T> `, `T2`) = **UP**(**UP**(`Future<T>`, `T2`), **UP**(`T`, `T2`)).
- **UP**(`T1`, `FutureOr<T> `) = **UP**(**UP**(`T1`, `Future<T>`), **UP**(`T1`, `T`)).
- **UP**(`Future<T>`, `T`) = `FutureOr<T>`.
- **UP**(`T`, `Future<T>`) = `FutureOr<T>`.

@leafpetersen, WDYT?

**Comment by leafpetersen** [comment]
@eernstg Interesting, good catch! Pre null-safety, essentially the rules that were implemented were as follows:

- **UP**(`FutureOr<T1> `, `FutureOr<T2>`) = `FutureOr<T3>` where `T3 = **UP**`(T1, T2)`
- **UP**(`T1`, `FutureOr<T> `) = `Object`
- **UP**(`FutureOr<T>`, `T2`) = `Object`

The last two rules were not handled explicitly, but I think that's what it worked out to be - I think `FutureOr<T>` is treated as having no super-interfaces except `Object`.  @scheglov does that match your understanding?

I'm inclined to just codify these directly, adjusted for null safety by making `Object` be `Object?`.  Or perhaps `Object` if both sides are non-nullable and `Object?` otherwise.

I don't see a lot of value in the first two rules - very few things are super-types of `Future<T>` and `T`.  The second two are reasonable, but in general we've been fairly conservative about inferring `FutureOr` from nothing, and I'd be inclined to keep it that way.

**Comment by lrhn** [comment]
It all depends on which results we want to achieve.

In general, the supertypes of `FutureOr<X>` are `FutureOr<Y>` where `X` &lt;: `Y`, or any top type.
(If `X` is a supertype or subtype of `Future<X>`, then the type collapses to a non-union type, so that might be the easy case.)
So there might be solutions other than `Object?`.

If **UP**(`double`, `FutureOr<int>`) or **UP**(`Future<double>`, `FutureOr<int>`) should yield `FutureOr<num>` (a valid supertype of both), then we need to be clever. More clever than Erik's first two rules.

If we're fine without that (as we have been so far?), then we can keep the existing behavior. I'm not sure we have time to be clever right now, so unless the new rules turn out to be "obvious", I don't think it's the time to be too ingenious.

**Comment by ds84182** [comment]
Actually just realized this is the same way the following is inferred:
```dart
void main() {
  Type f<T>(Future<T> a, T b, T c) => T;
  print(f(Future.value(3), 4, 5.0));
}
```

**Comment by leafpetersen** [comment]
If we want to be smarter, what we want is probably something like:

 * **UP**(`FutureOr<T1> `, `FutureOr<T2>`) = `FutureOr<T3>` where `T3 = **UP**`(T1, T2)`
 * **UP**(`Future<T1>`, `FutureOr<T2> `) = `FutureOr<T3>` where `T3 = **UP**`(T1, T2)`
 * **UP**(`FutureOr<T1>`, `Future<T2> `) = `FutureOr<T3>` where `T3 = **UP**`(T1, T2)`
 * **UP**(`T1`, `FutureOr<T2> `) = `FutureOr<T3>` where `T3 = **UP**`(T1, T2)`
 * **UP**(`FutureOr<T1>`, `T2`) = `FutureOr<T3>` where `T3 = **UP**`(T1, T2)`

**Comment by lrhn** [comment]
Nice rules there. They will handle a lot of cases (and probably all the cases written by sane developers, not mad testers).

How about **UP**(`FutureOr<int>`, `Future<Future<int>>`)?
I think that gives us `FutureOr<Object>` (aka `Object`), not the smaller supertype `FutureOr<FutureOr<int>>`.
Not sure how to get to there, though.

Do we have rules for introducing `FutureOr`? Something like:

* **UP**(`Future<T1>`, `Future<T2>`) = `Future<T3>` where `T3` = `**UP**(`T1`, `T2`).  // to prevent using the rules below.
* **UP**(`Future<T>`, `T`) = `FutureOr<T>`
* **UP**(`T`, `Future<T>`) = `FutureOr<T>`
* **UP**(`T1`, `Future<T2>`) = `FutureOr<T3>` where `T3` = `**UP**(`T1`, `T2`).
* **UP**(`Future<T1>`, `T2`) = `FutureOr<T3>` where `T3` = `**UP**(`T1`, `T2`).

**Comment by scheglov** [comment]
Yes, so far the analyzer has no special handling of `FutureOr` and is handled as any other interface type, direct subclass of `Object`.

**Comment by leafpetersen** [comment]
Yes, if we want to go ahead and introduce `FutureOr` as a result of upper bounds when neither input was a `FutureOr`, then the full rules would be:
 * **UP**(`FutureOr<T1> `, `FutureOr<T2>`) = `FutureOr<T3>` where `T3` = **UP**`(T1, T2)`
 * **UP**(`Future<T1>`, `FutureOr<T2> `) = `FutureOr<T3>` where `T3` = **UP**`(T1, T2)`
 * **UP**(`FutureOr<T1>`, `Future<T2> `) = `FutureOr<T3>` where `T3` = **UP**`(T1, T2)`
 * **UP**(`T1`, `FutureOr<T2> `) = `FutureOr<T3>` where `T3` = **UP**`(T1, T2)`
 * **UP**(`FutureOr<T1>`, `T2`) = `FutureOr<T3>` where `T3` = **UP**`(T1, T2)`
* **UP**(`Future<T1>`, `Future<T2>`) = `Future<T3>` where `T3` = **UP**`(T1, T2)`.
* **UP**(`T1`, `Future<T2>`) = `FutureOr<T3>` where `T3` = **UP**`(T1, T2)`.
* **UP**(`Future<T1>`, `T2`) = `FutureOr<T3>` where `T3` = **UP**`(T1, T2)`.

**Comment by lrhn** [comment]
Those rules still fail to recognize that  **UP**(`Future<int>`, `FutureOr<Future<int>>`) can be `FutureOr<Future<int>>`. The second line will make it `FutureOr(FutureOr<int>>`.

I think we really need to try with *both* parts of the `FutureOr` union, and then pick the best somehow, not just assume that a `Future<T1>` must be matched against the `Future` part of the union.

Would it make sense to write something like:
> **DOWN**(**UP**(`T1`, `Future<T2>`), **UP(`T1`, `T2`))

(or will there be cases with not useful lower bound?)

**Comment by eernstg** [comment]
I've created the PR https://github.com/dart-lang/language/pull/1254, proposing a non-aggressive set of rules for this: They do not attempt to handle `UP(Future<int>, FutureOr<Future<int>>)`, and they do not return `FutureOr` when none of the arguments is `FutureOr`.

**Comment by eernstg** [comment]
Decision: We will not synthesize a type of the form `FutureOr<...>` when none of the arguments is `FutureOr<...>`, and we do not add extra rules to handle the cases associated with types like `Future<Future<...>>`. Spec update landed as https://github.com/dart-lang/language/commit/ae340c7dcc62d375bd8df9fd4cb0d669d84478d2.

**Comment by eernstg** [comment]
Tests under review [here](https://dart-review.googlesource.com/c/sdk/+/166626).
