### ISSUE TITLE
Truncating multiplication operator, as in ~*

### ISSUE THREAD

**Issue by toysonlocation** [dart-lang/language#1263]
Please implement the sibling of ~/ for multiplication, ~*

I've found myself often having do to things such as

    int toW = (imgWidth * scale).toInt();

but the visual noise is high. I could do something kwazy such as

    int toW = imgWidth ~/ (1/scale);

BUT much nicer would be something such as

    int toW = imgWidth ~* scale;

How about adding a "Truncating multiplication operator" ?? Please;

**Comment by lrhn** [comment]
The operation would be on `num`, and be typed as `int Function(num)`.
We'd need to introduce a new user-definable operator because `int` already implements all of the existing ones.

We already have `toInt()`, along with `round()`, `floor()` and `ceil()` conversions which truncate or round in different ways, so the new operation won't introduce any new power, just convenience.

Maybe it's sufficient if you define:
```dart
extension IMul on num {
  int imul(num other) => 9this * other).toInt();
}
```
and then you can write `var toW = imgWidth.imul(scale);`

**Comment by toysonlocation** [comment]
+1 for user-definable operator

I appreciate the extension idea, but it's a bit opaque for anyone else. May as well go for the vanilla (n).toInt()

So, yes, the suggestion is for a language change. Isn't ~/ also "just convenience", or is it something else?

**Comment by lrhn** [comment]
The `~/` operator is a fully-fledged overridable operator in Dart, so you can defined it on any class.
On `num` it's a "convenience" in the sense that `a ~/ b` is mostly equivalent to `b == 0 ? throw ... : (a / b).toInt()`. It's a fundamental operation in that it and `.remainder` implements the div/mod integer division/remainder operation.
It's not completely equivalent because `a ~/ b` where both `a` and `b` are integers will do integer division, whereas `(a / b).toInt()` will first convert both to doubles and then do double division. That can lose precision for large integers.

**Comment by toysonlocation** [comment]
So, did you guys consider ~* when you conceived ~/ ? It seems to me that the use cases of overrides for ~/ would be similar to those of ~*.  I'm not a language designer, just a consumer, and perhaps a simple one at that, but certain things such as ~* would reduce my clutter and give symmetry to ~/ . Would an implementation basically be a copy of the effort for ~/ except for the num implementation? Are there tricky grammar checks for things that start with ~  ?

Maybe the topic gets too big, but I'm wondering why ~/ made it in and ~*, ~- and ~+ missed out?

BTW I very much appreciate your responses, and yes I'm still interested in seeing ~* added.

**Comment by lrhn** [comment]
There was never any intent to add anything like `~*` or `~+` (integer coercing multiplication or addition). 
If you add or multiply two integers, you get a new integer out. If one of the operands is a double, you get a double result. You can control the result type by controlling the operand types. If you do get a double, it's because you started with a dobule, and then you can just use `toInt` or any of the `round` functions at the point where it makes the most sense. That's how you are supposed to go from `double` to `int`.

The `~/` division is different. If you start with two integers, `/` can't just give you an integer back, because your integers might be statically typed as `num` and you might *want* `5/2` to give 2.5. Because of that, there was a need for an integer division, one which recognizes two integers as operands and gives an integer result back, one which can complement `remainder`, and one which won't  give infinity if you divide by zero.

So, because we wanted you to be able to write a single operand in order to do integer addition, subtraction, multiplication and division, we needed an operator for integer division. The other ones were covered by the general `+`, `-`, and `*` operators on `num`, but `/` could not be made to return an `int`.

**Comment by toysonlocation** [comment]
All makes sense from a from-the-engine room perspective, and would suggest I'm using the ~/ wrongly, since I'm ignoring the remainder and because I see a symmetric use (rather than mechanism) for ~* . That is, I am using ~/ for the int quotient, and am seeking similarly to use *~ for the int product, and from my perspective it seems like I'm riding a bike with a handle on only one side.

**Comment by tatumizer** [comment]
> The "just convenience" of ~/ invites a desire for the further convenience of ~*

This operator is not "just convenience". The expression `a~/b` is not always equivalent to `(a/b).toInt()` - e.g. if a, b are Bigint values, the results can be different. But this is not the whole story. For the whole story, you should go into the depths of time. 

Before dart 2, there was dart 1. The idea behind the dart project was to make dart a replacement for javascript. To facilitate the conversion of javascript programs (and programmers) into dart programs/programmers, dart tried to not break too far apart from javascript conventions. 3 facts important in the context of this discussion are: 
1) javascript is a dynamically typed language

2) in javascript, there's a single numeric type: double. All Int values are internally represented as double values.

3) As a consequence, all arithmetic operations are implemented as operations over double values, even if for the user the values look like ints. This works just fine in most practical cases: 2+2 is still 4, 2*2 is still 4, etc., but the division is special: 3/2 is not 1 like in most languages, but 1.5; to convert it to int, you need to explicitly call "truncate" or "round", or "ceil", or "floor" (the result is still internally represented as double, but the fractional part becomes 0).

Dart copied features 1) and 3) from javascript, but for 2), the language decided to do something clever: introduce a special int type and make it (automatically) scale to an arbitrary size. E.g. you could write:
```
factorial(n) {  
  var v=1;  
  for (var i=2; i<n; i++) v*=i;  
  return v;
}
print(factorial(100));
```
and it worked! 
(The feature was a bit unusual, but not unique to dart: the same is true in python and some other languages). 
However, the division of two int values was still performed via conversion to double values. So `3/2` was still 1.5. But what if you had to divide the values, one (or both) of which didn't fit into the precision of `double`? E.g. what if you have to compute `factorial(100)/3`? Standard division operator `/` is no good for that. That's where `~/` came in. It was not just a convenience. It was something you couldn't do otherwise.

In dart 2, ints were reworked: the language now supports only ints that fit into "double" (that is: limited to 53 bits that can be precisely represented in mantissa). To work with big numbers, you now have to explicitly use Bigint class. But even for BigInt class, the division via `/` produces a (potentially inaccurate!) double value. For a true Bignum integer division, you have to use `~/`.

The takeaway is this: operator `~/` was introduced because it was logically necessary for **int** values. Double values came as an afterthought: int and double are 2 different implementations of "num" abstract class, so they have to support the same operators, including `~/`. (If all we had were only double values, there would be no justification for the operator: after all, javascript doesn't have it).

Most often, while converting from double to int, I use rounding, not truncation. Having a special shortcut for doubles that favors truncation over rounding or floor or ceil would be rather odd IMO.

Disclaimer: I'm not associated with dart team in any way; my historical account might not be 100% accurate, but that's what I managed to dig up from my memory.

**Comment by lrhn** [comment]
> In dart 2, ints were reworked: the language now supports only ints that fit into "double" (that is: limited to 53 bits that can be precisely represented in mantissa)

That's actually not correct. Dart no longer has arbitrary precision integers, but the VM integers are 64-bit signed two's complement integers, not 53-bit "precise doubles". JavaScript compiled code uses JS numbers, which means doubles, but you can have integers above 2^53, just not *all* of them.

That's my only nitpick, the rest of the story is spot on.

**Comment by toysonlocation** [comment]
That's a very interesting history. BTW your quoting of my post is actually my referencing of Irhn's original reply...

> We already have `toInt()`, along with `round()`, `floor()` and `ceil()` conversions which truncate or round in different ways, so the new operation won't introduce any new power, just convenience.

A fair amount of my work includes bitmap and other `int` oriented data. Since I have to bridge between the `double` world of the UI and the `int` world of the data, using lots of `toInt()` and `toDouble()` feels tedious when teased with the convenience of `~/` for half of the story. I continue to highlight convenience because when you find a tool that suits the job, you use it. The background you outline for `~/` obviously has nothing to do with my adaptation of the operator, but the operator just so happens to be highly (visually) efficient for my purposes. Hence, the request for it's would-be sibling `~*`, or perhaps step-sister by your measure.

I see from both your and Irhn's commentary that it wasn't conceived for the purpose, but there is a class of `int` problems that `~/` makes more efficient to code, and I work with that kind of calculation frequently. So, I lament the lack of what it inadvertently suggests "ought" to exist.

**Comment by tatumizer** [comment]
@toysonlocation : you can use the expression `a*b~/1` as an equivalent of `(a*b).toInt()` - not exactly a step-sister, but it should work. :-)

**Comment by toysonlocation** [comment]
@tatumizer haha - yes, thanks for the suggestion, and in fact I have done that and it does work. But I'd like to make just a left instead of three rights to get the job done.

**Comment by toysonlocation** [comment]
To summarize, I use dart in the context of work, and my work involves UI related integer math. I would like to see a truncating multiplication operator `~*` as a companion to the truncating division operator, since a good part of my calculations involve fitting. I fully understand now that the purpose and history of `~/` is more complicated than just providing truncation. However, from the perspective of a user of the language, it is a very natural operator to use in the way its name states (Truncating Division Operator), and so despite the design history, I still request a real-world-usage addition of a counterpart, the Truncating Multiplication Operator `~*`.

```
int toW = imgWidth ~* scale;
```
vs
```
int toW = (imgWidth * scale).toInt();
int toW = imgWidth ~/ (1/scale);
int toW = imgWidth * scale ~/ 1;

```

Thanks for the consideration!

PS: This does bring up that dart doesn't have a strong image manipulation library, which is something else I'd like to see. I'll post that separately.

**Comment by tatumizer** [comment]
The issue of adding support for custom operators was raised on these pages on multiple occasions over the years, with no definitive result. The main stumbling block was, as far as I remember, the precedence of operators. Looking back, I realize that everybody missed a simple solution: instead of supporting arbitrary user-defined operators, allow only **predefined variants** of (some of) the existing operators. E.g. `~*` and `~+`, **having the same precedence** as `*` and `+` respectively.
The advantages of new operators:
- they don't conflict with any existing operators, so their implementation via extension methods will always work
- they are visually distinct from ordinary `*` and `+`. That's a good thing. When we read `x+y`, the impression is that we are adding numeric values, but when x and y are, say, matrices, the expression can be misleading; the form `x~+y` makes it clear that we deal with custom operators.
- very often, operations `*` and `+` are commutative. There's no way to define `x * matrix` for the numeric x via extension method. With new operators, we can define both `double * matrix` and `matrix * double`

**Comment by lrhn** [comment]
Adding only some finite number of predefined variants of existing operators is equivalent to just a adding more operators.

Adding an infinite, but structured, set of variants of existing operators (like what's matched by a regexp like `~*<infix-op>+`), allows you to introduce families of operators with the same precedence. It'll have to special case the ones we already have which are prefixes of each other, like `>`, `>>` and `>>>`, or `+` and `++` (if `++` is also infix, what is `x ++ -  y`?).

The precedence of an operator could be that of the longest currently defined suffix, so `~+` would use the precedence of `+` and `~~~~` would be a prefix operator and use the precedence of `~`. We'll probably have to special case `+++` to be infix and use `+`, not `++`, because `++` is not an *operator*, it's syntactic sugar for `+= 1`.
Or it could be the precedence of the leading infix operator in the `<infix-op>*` sequence, so `~+-` uses the precedence of `+` as infix operator. I think I like that better.

You can do `-+` or `+-+`. Maybe we should alllow `?` as well, just not at the beginning, for `(~?<infix-op>|~+<infix-op>)(?|<infix-op>)*`. 
We can allow the operators to be either infix or prefix, depending on the umber of arguments on the declaration (no suffix operators, sorry).

It will still make it nigh impossible to read code like `a +- b ~// c --- d` (whooops, `//` starts comment, not operator).

**Comment by tatumizer** [comment]
I think it would be more prudent to allow just a predefined subset of operators and then see what else the users want, and for what purpose. Otherwise, there's a good chance that someone defines an operation that dart will later want to reserve for itself, and not necessarily as an overridable operator. E.g. right away, somebody will define `|>` or `->`, leading to backward compatibility issues later on. Dart already has some operators not available for custom reuse - e.g. `||` and `&&`, and in the future, this list of disallowed symbols might grow.

> It will still make it nigh impossible to read code like `a +- b ~// c --- d`

This is another argument in favor of a more careful approach. There are not that many options for custom operators that make sense. Even for some operators that do make sense, users can expect different precedence rules - e.g. somebody will define `**` as a shortcut for `pow()`, and expect it to have a higher priority than `*`.

**Comment by tatumizer** [comment]
Here's a more general syntax idea.
Currently, the extension method does not get picked up if the class has a conflicting method defined. To disambiguate, we need to use expressions like `ExtensionName(obj).method()`, which looks a bit verbose and aesthetically displeasing. What if in addition to the above, we support a shorter form: `obj.~method()`, which will instruct the compiler to look only for an extension method. This can disambiguate the call unless there are 2 extensions defining the same method (in which case we still have to use the verbose form as a last resort).
This simple convention will automatically solve the problem of extensions for operators:
```
extension on double {
   double operator *(double arg) {...};
}
//...
var x = y~*z; // explicitly calling the extension operator.
```
Note that the **definition** of the operator does not contain `~` - it's just a "normal" multiplication.
@lrhn: WDYT?

**Comment by toysonlocation** [comment]
Custom operators, shelved again?

**Comment by lrhn** [comment]
Using `~operator` or `~method` to force using an extension over an interface member ... I don't think it's worth it.
It can't work for prefix operators because `~` already is a prefix operator, so `~-x` already means something.

I think it's doing *too little* for its syntactic cost. I'd rather put work into "extension types" where you introduce a new type alias, but where extensions defined on that type alias takes precedence over members of the underlying type. Then you can do anything you want. Say:
```dart
extension type forcedInt on int {
  forcedInt operator +(num n) => (this + n).toInt();
  forcedInt operator *(num n) => (this * n).toInt();
  ...
}
```
  forcedInt x = 4;
  double scale = ...;
  x *= scale;  // still an int.
```
That allows you to introduce more than one entirely new set of operators for a type, and not be restricted to just one set of extensions.

**Comment by tatumizer** [comment]
> I think it's doing too little for its syntactic cost

The syntactic cost is just one symbol, so we have an enormous ROI here!

> so ~-x already means something.

The single user who has ever written the combination like this (assuming such a person exists, which I'm not sure it does) can be bribed into inserting a pair of parentheses in his code: `~(-x)` (\*).  (BTW, the same objection could be made against `--x` operator, but it wasn't)

Not only `~op` is inexpensive, it allows extensions and class methods to coexist peacefully. In contrast, type extensions open the floodgates to the arms race between the two - the author of the extension, offended by the existence of conflicting definitions
of the method, may start methodically re-defining his extensions as type extensions - which will result in `2+2` being 5 with no indication as to why.

(\*) while `~-x` certainly means something, I have great difficulty figuring out what it is :-)

**Comment by lrhn** [comment]
(As a code golfer, I can tell you that `~-x` is the same as `x - 1`, but with a stronger binding operator. Similarly `-~x` is `x + 1`.)

**Comment by lrhn** [comment]
One of the reasons I think `~method` does too little is that it allows *one* extension to coexist with instance members, but cannot do anything for multiple extensions. That makes it a one-trick pony. You have to ensure that you import only one extension, then you can use `foo.~method()` instead of `Extension(foo).method()` (so nothing new that you can't do already, just shorter syntax), and if you need another extension as well, you have to fall back to `Extension(foo).method()` anyway.

That said, extension conflicts *are* rather rare, and *needing* to use two in the same library is probably even rarer.

**Comment by tatumizer** [comment]
> (As a code golfer, I can tell you that ~-x is the same as x - 1)

I had the same conjecture, but dartpad proved me wrong. `~0` evaluates to 4294967295. I thought maybe that's how the cookie crumbles these days, but no: on VM, ~0 is -1 as expected (just tested it a minute ago, hopefully, that stays :-).

**Comment by hacker1024** [comment]
In a `const` statement, `.toInt()` is unavailable, while `~/` is. It'd be great to have `~*` for this use case as well.

**Comment by lrhn** [comment]
The best/only way to convert a `double` to an `int` as a contant expression is indeed `dbl ~/ 1`. And it works.

It's easy to convert an `int` to a `double` because doubles are infectuous (if you do an operation using an integer and a fractional number, the result can be fractional). The `~/` exists because division is the only operation on `int` where combining two integers can give a a fractional result.

There is no plan to add a `~*`, an I doubt it'll ever happen.
