### ISSUE TITLE
Issue for discussion of super mixin type argument inference

### ISSUE THREAD

**Issue by leafpetersen** [dart-lang/language#13]
I've updated the Dart 2.0 super mixin type inference specification to use the syntax from this proposal [here](https://github.com/dart-lang/language/blob/master/working/0006.%20Super-invocations%20in%20mixins/0007.%20Mixin%20declarations/mixin-inference.md).  This issue is for any relevant discussion, comments, or feedback.

cc @lrhn @eernstg @munificent

**Comment by leafpetersen** [comment]
No new discusssion (unsurprising) I'll go ahead and close this out.

**Comment by yjbanov** [comment]
Somehow I missed this issue. There's one instance where Flutter has to ignore the `MIXIN_INFERENCE_INCONSISTENT_MATCHING_CLASSES` check. However, from what I can tell, the new proposal fixes the issue.

**Comment by leafpetersen** [comment]
Hmm, why does the proposal address this - it's just porting over what's already implemented for class based super-mixins?  Can you point me at what the inconsistent matching classes are?

**Comment by yjbanov** [comment]
https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/widgets/dismissible.dart#L190

The reason I believe that the proposal addresses the issue is in the first example given in the [Inference proceeds outwards](https://github.com/dart-lang/language/blob/master/working/0006.%20Super-invocations%20in%20mixins/0007.%20Mixin%20declarations/mixin-inference.md#inference-proceeds-outward) section, which seems to match Flutter's usage if you substitute `_DismissibleState` for `A`, `State<Dismissible>` for `M0<int>`, and `AutomaticKeepAliveClientMixin` for `M1`. The example states that "`M1` is inferred as `M1<int>`", which for Flutter should translate to "`AutomaticKeepAliveClientMixin` is inferred as `AutomaticKeepAliveClientMixin<Dismissible>`".

I did overlook the fact that Flutter's case contains not one but two mixins, which may be where things break down.

**Comment by leafpetersen** [comment]
You're right.  It's a bug that this isn't working already.

https://github.com/dart-lang/sdk/issues/34404
