### ISSUE TITLE
Records: Is identity required to be stable?

### ISSUE THREAD

**Issue by leafpetersen** [dart-lang/language#1303]
[This proposal](https://github.com/dart-lang/language/blob/master/working/0546-patterns/records-feature-specification.md) indicates that equal records may or may not compare identical.  Is identity required to be stable?  That is, is `identical(x, x)` required to be true for values `x`?  Does `identical(x, y)` imply `identical(x, y)`?

Note that these have implications for optimization, since if identity is stable, then a tuple may not be returned from a method unboxed unless it can be proven that the returned pointer is unique.

**Comment by eernstg** [comment]
I'd prefer promising as little as possible about `identical` on records/tuples, perhaps nothing at all. This allows for improved performance, because boxing/unboxing can take place anywhere, and it allows for a rule which is easy to remember: "When comparing records/tuples, always use `==` and never use `identical`".

**Comment by lrhn** [comment]
As written, there is no promise that any operation on tuples preserves identity.
Passing arguments to `identical` is an operation which might not preserve identity, so effectively nothing can be guaranteed.
(It says that *constant* tuples preserve identity, but that does not actually make sense because being a constant is a property of an expression, not a value. Other types can say that they canonicalize constants *because* their values keep their identity.)

In practice, users will likely find that some operation do preserve identity and other do not. Quite possibly, all operations on "boxed" tuples (which means any tuple stored at a static type which is not a tuple type, so `Record`, `Object`, `dynamic` or `DestructureX`) will keep their identity, and values passed through tuple types may or may not lose it (if they are unboxed).
We could say that that is actually the promised behavior:
* Storing a tuple in a variable whose static type is an interface type will ensure that it has an identity, and moving that value among such variables will preserve that identity. (We do not promise that the identity is different from other equivalent tuples, it may or may not be, but the identity is *stable* as long as it's not assigned to a tuple type or potential tuple type). This would allow general code which just uses `Object` to keep working.
* Storing a tuple in a variable whose static type is a tuple type may or may not lose its identity. No promises mad.
* Storing a tuple in a variable whose static type is a type variable may or may not lost its identity. (We reserve the right to specialize generic functions and classes for tuple types).

Or even, promise that tuples at tuple types do not have identity: "Non-constant expressions of tuple types are unboxed and not identical to anything, tuples at any other type is boxed and retains identity until unboxed by assigning to a tuple type, and constant tuple expressions are boxed to the same instance every time."

We can then say that the behavior of `identical(o1, o2)` depends on the types of `o1` and `o2`.
* If neither type is a tuple type, identical works like now, and boxed tuples are treated like any other reference.
* If one or both types are tuple types, then those tuples are boxed and then compared as above (which preserves identity of constants). Compilers may be able to special-case this to `false` if they recognize `identical` and one of the operands is a non-constant tuple expression.

This would ensure that `identical(a, b)` gives the same results as `var y = identical; ... y(a, b)` even when compilers can't tell that `y` is `identical`. The latter would box both tuples before sending them to an unknown

The biggest issue is type variables. Take:
```dart
T foo<T>(T value) {
  T tmp = value;
  if (tmp == null) throw "Nope!";
  return tmp;
]
```
It looks like it should preserve the identity of the value passed in, but we probably want to reserve the right to specialize the function for tuples (or even just for non-nullable types). In that case 
```dart
const (int, int) p = (0, 0);
var x = foo<(int, int)>(p);
```
might be calling a specialized version of `foo` like: 
```dart
(R, S) foo_t2<R,S>((R, S) value) { return value; }
```
which would pass the tuple through a non-constant tuple typed variable, and therefore change its identity.

That means that we can't promise that type variables preserve identity, even if the code looks completely generic over the type.

**Comment by lrhn** [comment]
Also "identity"/canonicalizaton might be needed for places in the language specification where we require "the same value".
For example, if an instance method parameter has a default value, a subclass overriding the method must have *the same* default value. We need to ensure that "the same" is well-defined. Since the default value is a constant, we should at least ensure that references to constants are considered "the same" if they are pointwise equal, even if written as tuple literals.

**Comment by tatumizer** [comment]
> If one or both types are tuple types, then those tuples are boxed and then compared as above (which preserves identity of constants). Compilers may be able to special-case this to false if they recognize identical and one of the operands is a non-constant tuple expression.

With a definition like this, `identical` for tuples becomes unpredictable and brittle.
Won't it be easier to just define it like this: if one or both are tuple types, the result is always false?

**Comment by ds84182** [comment]
Java's Project Valhalla offers some interesting insight, especially around [identity & equality](https://cr.openjdk.java.net/~briangoetz/valhalla/sov/02-object-model.html#equality).

For tuples where the static type is known at compilation time (e.g. unboxed representation), the compiler could generate a stub for identical that replaces the actual call. This allows for call-site inlining of identical.

For calls to identical where the types of the arguments are not known at compilation time (e.g. boxed representation), the runtime can virtually dispatch to a stub, after doing type checks.

Without a proper implementation of value identity for records, the definition of Dart's `identical()` falls apart. Value identity is already specified in Dart today, although those values are only ints and doubles. Opening up composite value types with strange rules around identity does not feel great. It isn't like developers will be writing `identical(x, y)`, but the libraries they depend on that use it may break in strange or hard to debug ways.

**Comment by lrhn** [comment]
Another thing to worry about is that the behavior of `identical` should not depend on the compiler recognizing the call as being to `identical`. It's a function and you can pass it around as a value and call it in places where it can't be recognized. At that point, the arguments *will* be boxed. So, the behavior of `identical` should be the same (or equally undefined) whether the call can be recognized or not.
```dart
const (int, int) x = (2, 2);
(int, int) y = x;
var id = identical;
print(identical(x, y));
print(id(x, y));
```
Whatever strategy we choose, it should treat this code in some consistent way.

Which means that `identical(a, b)` could just always box tuples and then do whatever it does for boxed tuples.

**Comment by munificent** [comment]
I've [updated the proposal](https://github.com/dart-lang/language/commit/487c4e047b546e943b4421304644152da42278ee) based on our design discussion this morning. The current plan is to take @mraleph's [suggested approach](https://github.com/dart-lang/language/issues/1289#issuecomment-722984356) and define identical structurally.
