### ISSUE TITLE
Records: Should `DestructureN<T0, ..., TN>` be allowed for all `N`?

### ISSUE THREAD

**Issue by leafpetersen** [dart-lang/language#1305]
[This proposal](https://github.com/dart-lang/language/blob/master/working/0546-patterns/records-feature-specification.md) for records specifies a fixed maximum width tuple for which destructuring is supported.  This seems arbitrary - why not simply allow any width?

**Comment by lrhn** [comment]
The destructuring is allowed for any width, but only a finite number of widths also have a non-tuple interface for the getters.
You can still write `var x = (0, ........, 9999); var y = x.field9999;`, but there won't be a `Destructure10000` interface which that tuple type implements.

So, I'll consider what it would mean to have "all the interfaces".

That would introduce an infinite number of names exported from (likely) `dart:core`.
We'd have to special-case resolution (more so if we don't reserve the names up-front), and we'd have to disallow finding them using reflection. (The `dart:mirrors` library can return a list of declarations for a library. Even using an iterable. which *can* be infinite, it would still likely risk people looping forever when they reflect on `dart:core`).

It also means that we have *arbitrarily long names*, not limited by the program source. (Obviously those types can be tree-shaken since the program doesn't use them, the types being used are limited by the program source, as long as we don't allow dynamically spreading tuples into new tuples - which we shouldn't allow!)

(I'm still not sure these interfaces are needed at all, and they are feel arbitrary and limited, both in width and in not supporting named elements. I would prefer not having them.)

**Comment by munificent** [comment]
What @lrhn said. :)

It's because there are corresponding named interfaces in dart:core for each arity and we don't want an unbounded number of those. Scala [has the same restriction](https://stackoverflow.com/questions/4152223/why-are-scala-functions-limited-to-22-parameters) (and uses 22 of all things for the limit). GHC [limits tuples to 64 fields](https://stackoverflow.com/questions/2978389/haskell-tuple-size-limit).

The proposal lets you make larger records, but you can't destructure them (which makes them not *super* useful unless you go through the loosely-typed reflection-y API).

If we eliminate the `Destructure` interfaces and use a different protocol for positional field destructuring, then the limit would probably go away too.

**Comment by leafpetersen** [comment]
> What @lrhn said. :)

I disagree with what @lrhn said.  :)

> That would introduce an infinite number of names exported from (likely) `dart:core`.
> We'd have to special-case resolution (more so if we don't reserve the names up-front), and we'd have to disallow finding them using reflection. (The `dart:mirrors` library can return a list of declarations for a library. Even using an iterable. which _can_ be infinite, it would still likely risk people looping forever when they reflect on `dart:core`).

Then don't treat them as names exported from `dart:core`?  I don't really understand why we need to treat all types as things corresponding to class definitions.  Concretely, this proposal is mixing structural and nominal types.  The proposal adds an in principle infinite number of structural types, but treats them as implementing a nominal de-structuring interface.  So just.... don't?  Make the de-structuring interface essentially structural.

> It also means that we have _arbitrarily long names_, not limited by the program source.

Given that the encoding is logarithmic, I don't think this is in any way a realistic concern.

> It's because there are corresponding named interfaces in dart:core for each arity and we don't want an unbounded number of those. Scala [has the same restriction](https://stackoverflow.com/questions/4152223/why-are-scala-functions-limited-to-22-parameters)

Scala has to compile to the JVM and hence is limited in lots of ways that we aren't.

> GHC [limits tuples to 64 fields](https://stackoverflow.com/questions/2978389/haskell-tuple-size-limit).

That's fine - we should be all mean be open to limiting the size of the tuples/records that we support to being some finite size so that we aren't committed to the GC supporting arbitrary sized headers - just as we limit the size of arrays to some finite max length so that the length doesn't need to be a bigint.  But that's not what this is about.  Instead, this proposal says that tuples can be any width, but we arbitrarily limit destructuring to 16.  That feels like saying "You can have any length List, but you can only iterate on Lists up to length 16".

**Comment by lrhn** [comment]
We can treat `DestructureN` as a magical type (we still have to resolve the name, but we can be magical about it and say that if an identifier of that form does *not* lexically resolve to anything, it means a tuple super-interface).
It's still a nominal type, not structural, since classes have to explicitly implement it (a class won't implement `Destructure2` just because it has a `field0` and a `field1` getter, you have to write it in the `implements` clause).

So, we can definitely consider the types "tree shaken" to only have the ones actually mentioned in the program.
We can even allow `DestructureN` <: `DestructureM` when `M` < `N` when both are mentioned by the program.
(Still, good luck with `class TupleMock implements Destructure999999 { noSuchMethod(i) => ...}`, although with null safety it's limited how useful that class can be).

> The proposal lets you make larger records, but you can't destructure them

Why can't you destructure them? A 12-tuple still has `field0`, ... `field11` getters, it just doesn't have a separate interface *just* for those. You can't abstract over the type (and abstract away the names entries), but you can still destructure at the tuple type without any problems. And that's the most important part, I don't see the need for destructuring when you don't actually know the type of the value precisely.

**Comment by leafpetersen** [comment]
A follow up comments about the concerns around resolving names:  why is this different from the `fieldn` getters that tuples induce?  They also require "magic" name resolution, and they also are theoretically unbounded in size.

**Comment by leafpetersen** [comment]
> > The proposal lets you make larger records, but you can't destructure them
> 
> Why can't you destructure them? A 12-tuple still has `field0`, ... `field11` getters, it just doesn't have a separate interface _just_ for those. You can't abstract over the type (and abstract away the names entries), but you can still destructure at the tuple type without any problems. And that's the most important part, I don't see the need for destructuring when you don't actually know the type of the value precisely.

I'm not sure what you're saying here.  The `Destructure` interfaces are being introduced for a reason that has not yet been described (presumably around allowing code to be written which abstracts over destructurable things).  Limiting this arbitrarily says that some records have this ability, but some don't.

**Comment by lrhn** [comment]
The underlying question here might be: What does "destructure" mean?
I take it to be the ability to extract individual values from a tuple (or, in general, from a composite value).
You can do that for tuples without the interfaces, a 99-tuples has a `field98` property even if it has no `DestructureX` interfae.

It might also/alternatively refer to an unspecified pattern matching operation.

The reason I for the `DestrucutureX` interfaces that I was inferring, was to allow *classes* to implement the interfaces too, and simulate tuples/be used interchangeably with a tuple value at the shared interface. To allow class instances to be used in places where we would otherwise only allow tuples, and (this is my main expected benefit from the interfaces) to be able to do *pattern matching* on class instances as if they were tuples.

So, the destructuring is not relying on the interfaces, we can do destructuring of tuples without those, but we can't do position-based pattern-matching/destructuring of class instances the same way without a common interface for tuples and class instances. Restricting the interfaces does not restrict destructuring of *tuples*.

I'm saying that we don't need that at all, and I don't particularly want it, so I see no inherent value in having those interfaces at all.

**Comment by leafpetersen** [comment]
Alternative approach to this suggested [here](https://github.com/dart-lang/language/issues/1310).

**Comment by munificent** [comment]
> It might also/alternatively refer to an unspecified pattern matching operation.

That's what I had in mind.

> The reason I for the `DestrucutureX` interfaces that I was inferring, was to allow _classes_ to implement the interfaces too, and simulate tuples/be used interchangeably with a tuple value at the shared interface.

Exactly right. Sorry, I realize it's hard to evaluate a design that has features that rely on as-yet-undesigned parts. Working on it. :)
