### ISSUE TITLE
The `get` keyword should be allowed before type specifier

### ISSUE THREAD

**Issue by TheKashe** [dart-lang/language#1306]
Currently, _final_ and _const_ come before type specifier, but _get_ is used after type specifier.

This breaks code alignment (in case one wants to use such coding style), as type and keyword switch places in the (perceived) columns.

```
final String foo = "foo";
const String bar = "bar";
var          baz = "baz";
String get   qux => foo;     
```

Proposed change:

allow _get_ to come _before_ type specifier:

```
final String foo = "foo";
const String bar = "bar";
var          baz = "baz";
get   String qux => foo;    
```

**Comment by lrhn** [comment]
Since `get` is a built-in identifier, it can't be a type. That doesn't mean that it's completely safe to twiddle with parsing order.

Example: `get async async => ...` can currently only be parsed as a getter named `async` which is an asynchronous function.
You can also write `async get async` which is a getter named `async` which returns the type `async` (it won't work because the getter shadows the `async` name, but the parser won't know that yet). Since `async` is not a built-in identifier, it *can* be a type name.
If we allow swapping the type and `get`, then both can be written as `get async async`, and that grammar is then ambiguous.
(I'm sure we can come up with a disambiguation which doesn't assume that `async` is a type).

We can also declare getters named `get`, but I don't think that leads to further issues than it already does.

**Comment by munificent** [comment]
This would be a very large breaking change for marginal benefit. I think it's infeasible for us to do this, so I'm going to go ahead and close it out.
