### ISSUE TITLE
Self-assignments inside loops invalidate null promotion

### ISSUE THREAD

**Issue by znjameswu** [dart-lang/language#1308]
The following behavior is strange. A self-assignment inside a loop makes promoted variable fall back to nullable.

This makes even incrementing a nullable variable hard.

```dart
void fun(int? a) {
  if (a == null) return;
  for (var i = 0; i < 30; i++) {
    int b = a; // OK
  }
  
  if (a == null) return;
  for (var i = 0; i < 30; i++) {
    a = a;
    int b = a; // Error
  }
  
  if (a == null) return;
  for (var i = 0; i < 30; i++) {
    a++; // Error
  }
}
```

Tested on DartPad (Dart SDK 2.11.0-240.0.dev)

**Comment by leafpetersen** [comment]
For better or for worse, we are committed to a design in which we do not iterate to a fixed point.  This allows us to do the analysis quickly, but means that in general we must conservatively approximate on back edges of loops, which we do by assuming that anything that is assigned to in the loop might be assigned something nullable.  While we agree that cases like your example are unfortunate, we still believe that this is the right tradeoff between precision and speed in the analysis.

**Comment by jamesderlin** [comment]
See https://github.com/dart-lang/language/issues/441 for the discussion.

**Comment by jamesderlin** [comment]
>  which we do by assuming that anything that is assigned to in the loop might be assigned something nullable. 

Would it not be sufficient to see that the assignment in the loop does not change the promoted type (i.e., its declared type is `int?`, promoted type in the loop body is `int`, and the assignment in the loop body preserve it at `int`)?  I don't see why cases like this should require multiple passes.

**Comment by leafpetersen** [comment]
> Would it not be sufficient to see that the assignment in the loop does not change the promoted type (i.e., its declared type is `int?`, promoted type in the loop body is `int`, and the assignment in the loop body preserves it at `int`)?

The key insight is that "the assignment in the loop body preserves it at `int`" depends on inference to know that it's true, which in turn is part of the flow analysis.  We need to know which variables to demote before we enter the loop, but we don't know the types of the things assigned to those variables until we've done flow analysis/inference on the body of the loop.  So if we allowed the types of the things assigned to `x` to influence whether `x` gets demoted, then we would need to iterate, since the first time around we wouldn't know whether to demote `x`, so we'd need to do inference, then once we knew the type of things assigned to it, we would need to change our demotion choices, which then in turn changes the result of inference, which might then change the choice of demotions.... so back to a fixed point calculation.
