### ISSUE TITLE
The "variableDeclaration" grammar rule does not appear to be used

### ISSUE THREAD

**Issue by munificent** [dart-lang/language#1316]
I'm digging through the spec's grammar around variable declarations to figure out how to weave patterns into them and I noticed that this rule doesn't appear to be referenced by anything else:

```
variableDeclaration ::= declaredIdentifier (',' identifier)*
```

The prose mentions it, but no other grammar rule does.

**Comment by eernstg** [comment]
Good catch again!

`<variableDeclaration>` used to be the last item in `<topLevelDeclaration>` (and wasn't used anywhere else), but was replaced by

```
  \alt \LATE{} \FINAL{} <type>? <initializedIdentifierList> `;'
  \alt \LATE{}? <varOrType> <initializedIdentifierList> `;'
```

This is a bug fix because `<variableDeclaration>` doesn't allow the variables to be initialized (so `final x;` and `final int x;` would be derivable, but they should be syntax errors as top-level variables).

This is also an improvement, because `<variableDeclaration>` starts with `'covariant'?`, and that's never allowed for a top-level variable. 

So `<variableDeclaration>` should simply be removed. Under review in #1320.
