### ISSUE TITLE
Calling methods of `Object` with a wider signature, but hitting `null`

### ISSUE THREAD

**Issue by lrhn** [dart-lang/language#1322]
This was brought up by @askeksa-google. It's not restricted to null safety.

In short, legacy mode is unsound, not just null-unsound:
Example:
```dart
class MyType implements Type {
  int doMagic() => 42;
}
class A {
  MyType get runtimeType => MyType();
}
void main() {
  MyType t = (null as A).runtimeType;
  print(t.runtimeType); // "Type", not "MyType".
  print(t.doMagic()); 
}
```
This can be either unsound null safe (UNS) semantics or legacy semantics, because the `(null as A)` succeeds as long as we're not in sound null-safe mode.

For getters/methods other than `runtimeType` and `noSuchMethod`, there is no way to introduce a non-`Never` subtype of their declared return types, and in null safe code, even unsound, we check for `Never`-typed expressions that do not throw.

Example:
```dart
class A {
  Symbol noSuchMethod(Object inv) => inv is Invocation ? inv.memberName : #unnamed;
}
void main() {
  dynamic i = Invocation.getter(#name);
  Symbol s = (null as A).noSuchMethod(i);
}
```

We are calling a method with static signature `dynamic Function(Object)` with an argument of type `dynamic`. In legacy mode that's a direct call, in UNS mode there is an implicit downcast to `Object` of `i` which succeeds.

Then we try to invoke a method with static type `Symbol Function(Object)` and actual signature `dynamic Function(Invocation)` with an argument with static type `Object` and actual type `Invocation`.

*Does this just work, or will/should we do an intermediate check and see that the method's run-time signature doesn't satisfy its static signature?*

Do we check that the function actually accepts an `Object`, or do we just do a dynamic invocation and check the run-time types? *Do* we check the run-time types? (If we changed `i` to `Object()`, where do we specify that it should throw?)

I'm guessing, without having checked thoroughly, that the language specification still specifies the run-time behavior of  invocations as if they were dynamic, doing all the type checks on arguments along the way, and being statically type-checked merely allows the compiler to omit some checks.
However, with the Dart 2.0 type system, we introduced some extra checks for unsound covariance. Do we need something like that here too? (And if not, is that just a lucky accident?)

This *only* affects members of `Object`/`Null` which has had their signature subtyped in a subclass. Those are the only methods that `null` actually has, but which won't necessarily accept the invocation allowed on the subclass.
It won't be much extra overhead to insert extra run-time checks on the return values of invocations of such methods where an interface has restricted the return type, and where null-unsoundness allows `null` to be a possible receiver.

Obviously all the problems go away in sound null safety, since you can't ignore a `null` value in the receiver type, and the member types of `Foo?` is the same as those of `Null`/`Object`.

Big example:
```dart
Invocation get dummyInvocation => Invocation.getter(#dummyInvocation);

class MyType implements Type {
  int doMagic() => 42;
}

class A {
  Symbol noSuchMethod(Object inv) => inv is Invocation ? inv.memberName : #unnamed;
  MyType get runtimeType => MyType(); 
  Null toString([int x]) => null; // or `Never ... => throw "bad';` in null-safe mode.
  Null get hashCode => null;
  Null operator==(Object other) => null;
}

void main() {
  dynamic i = dummyInvocation;
  Symbol s = (null as A).noSuchMethod(i);
  assert(s is Symbol);
  MyType t = (null as A).runtimeType;
  t.doMagic();
  Null x = (null as A).toString(42);
  x = (null as A).hashCode;
  x = (null as A) == 42;
}
```

So, my guess is that the specification treats all invocations as dynamic invocations at run-time and checks the arguments.
We have not specified that we check the returned value, and we probably should state that as well (and as usual allow compilers to do nothing if the result is statically guaranteed). This also subsumes our unsound-covariance checks for generic class member returns.

**Comment by askeksa-google** [comment]
See also https://github.com/dart-lang/sdk/issues/44140, which is an issue I filed for a related bug in the AOT compiler.

**Comment by leafpetersen** [comment]
I believe that this is the legacy version of [this issue](https://github.com/dart-lang/language/issues/551).  I think we observed at the time that this also applies to legacy code (since the union in legacy code is implicit).  It was fixed for null safety [here](https://github.com/dart-lang/language/blob/master/accepted/future-releases/nnbd/feature-specification.md#expression-typing).  We didn't plan any fixes for legacy code.  We could consider applying the same fix to legacy code.

**Comment by lrhn** [comment]
The issue applies both to legacy code and to null safe code in unsound mode, because both situations can end up with a `null` which cannot be seen from the type.

The fix in null safe code is to use the member signature from `Object` when invoking an `Object` member on a nullable type. That's perfectly reasonable union type behavior, and using the member signature from `A` for `A?` was really a bug.

That fix won't help here because there is no static type to help us.

We cannot change the type of `A a = ...; var t = a.runtimeType;` where `A` overrides `runtimeType` to return a subtype of Type`. 
Or I guess we can, but then it affects *all* uses of that overridden member, effectively making it impossible to override a member of `Object` to get a more specific type. That will be breaking (as if anyone ever does that override, except possibly `noSuchMethod(dynamic ...)` or something like `toString([int radix = 10])`).

I think it would be better to insert run-time checks whenever an overridden member of `Object` is being called on `null` (so first run-time check is: Is receiver `null`, if so, are the arguments count and types valid for the method on `null`, and if so, call and chec if the return value a valid return from the static type's member signature.

**Comment by eernstg** [comment]
I do think it is useful to fix a soundness issue even for legacy code. The typing situation is similar to a "contravariant member":

```dart
class C<X> {
  void Function(X) f = (X x) {};
}

void main() {
  C<num> c = C<int>();
  void Function(num) f = c.f; // Caller-side check, throws at evaluation of `c.f`.
}
```

With the `Object` and null issue, the statically known receiver type yields a certain member signature _s_, and we may dynamically encounter null as a receiver, yielding a member signature _s0_ which is not a subtype of _s_. The situations where this non-subtype relationship holds are known statically, so we would just need to check whether the receiver is null and throw.

This will fail somewhat more aggressively than if we check things like the actual return value vs. the statically known return type, but that may be an OK trade-off because it's considerably faster. After all, there will not be many call sites where this check is needed.

**Comment by lrhn** [comment]
The members of `Object` are:
```dart
Type get runtimeType;
int get hashCode;
bool operator==(Object);
dynamic noSuchMethod(Invocation);
String toString();
```
Of these, only `toString` and `noSuchMethod` can be torn off, and only those can have more (optional) members added.
The parameter type of the two methods and `==` can be specialized, and the the return type can be specialized for all members (although only to `Never`/`Null` for `hashCode`, `toString` and `==` because the declared return type is sealed).

Which means any semantics assuming those types match the declared type are unsafe and should be checked:
```dart
//@dart=2.7
class MyType implements Type {
  int get foo => 42;
}
abstract class A {
  MyType get runtimeType;
  Never get hashCode;
  Never operator==(dynamic arg); // No way to actually break this.
  int noSuchMethod([dynamic argument, dynamic extra]);   
  Never toString([int radix = 10]);
}
void main() {
  A a = null;
  
  MyType t = a.runtimeType; // unsound assignment.
  print("t: $t is MyType: ${t is MyType}");
  String  x = a.hashCode; // unsound assignment (possibly covered by Never checking)
  print("x: $x is String: ${x is String}");
  try {
    int i = a.noSuchMethod(Object()); // Invalid invocation, but will always throw.
  } catch (e) {
    try {
      print("noSuchMethod: $e");
    } catch (e) {
      print("noSuchMethod *Internal error*: $e");
    }
  }
  int Function([dynamic, dynamic]) fi = a.noSuchMethod; // unsound assignment.
  print("fi: ${fi.runtimeType} is int Function([dynamic, dynamic]):"
        " ${fi is int Function([dynamic, dynamic])}");
  try {
    fi(1, 2); // Invalid invocation.
  } catch (e) {
    print("fi: $e");
  }
  try {
    a.toString(42); // Invalid invocation.
  } catch (e) {
    print("toString: $e");
  }
  int s = a.toString();  // Unsound assignment (possibly covered by Never checking);
  print("s: $s is int: ${s is int}");
  Never Function([int]) fs = a.toString; // unsound assignment.
  print("fs: ${fs.runtimeType} is Never Function([int]):"
        " ${fs is Never Function([int])}");
}
```
This shows a number of soundness errors where a variable contains a value not matching the variable's static type.
I don't know what it can be used for, but it definitely makes some optimizations invalid.

**Comment by eernstg** [comment]
The caller-side checks I mentioned would be as follows: For an invocation of an `Object` member where the receiver can be null (legacy/unsoundness), when the statically known member signature _s_ is such that the signature _s0_ in `Object` is not a subtype of _s_, throw if the receiver is null.

If we do that then an exception is thrown in each case in [@lrhn's example](https://github.com/dart-lang/language/issues/1322#issuecomment-733631030) where a comment containing 'unsound' occurs.

The case where this is perhaps a bit too aggressive is when the invocation would actually succeed:

```dart
//@dart=2.7

class MyType implements Type {
  int get foo => 42;
}

abstract class A {
  int noSuchMethod([dynamic argument, dynamic extra]);   
  String toString([int radix = 10]);
}

void main() {
  A a = null;
  dynamic Function(Invocation) x = a.noSuchMethod; // Throws.
  var y = a.toString(); // Throws.
}
```

The evaluation of `a.noSuchMethod` throws because the resulting function object has a run-time type which is not a subtype of the statically known type, even though we would have assigned it to a variable whose type _does_ admit the given run-time type.

The evaluation of `a.toString()` throws for the same reason, even though the given invocation would have been type correct also with the signature of `toString` in the actual receiver type `Null`.

So it's a little bit too aggressive, but it is cheap and simple. And I don't think we will see this very often at all.

**Comment by lrhn** [comment]
Closing as no longer relevant.
Unsound null safety no longer exists. (And if it does, you can't use it. And if you can use it, don't make this mistake.m'kay.)
