### ISSUE TITLE
[NNBD] Is there a way to nest nullable types without boxing?

### ISSUE THREAD

**Issue by modulovalue** [dart-lang/language#1327]
Is there an equivalent for the following code snippet that uses the new nnbd language features without introducing any wrappers?
```dart
Option<Option<int>> a = Some(Some(0));
```

The following did not work:
```dart
int?? a = null;
(int?)? a = null;
((int?)?) a = null;
```

I was hoping to gain some memory and performance benefits from avoiding boxing completely in cases that can only be modeled by 'something that is nullable and it might or might not exist'

If not, can we expect that something like this will be possible leading up to the full release or are there no plans to add support for such use cases?

**Comment by lrhn** [comment]
No way to do that, and no plans to add it.

Dart nullability is effectively a union type, and union-ing with a type is an idempotent operation. The values that are either `int` or `Null` is exactly the same as those that are either `int`, `Null` or `Null`.

I'm not sure how you would get memory benefits from that unless the implementation keeps more than one `null` value, so it can store both `null-int` and `null-int?` in the same memory slot and distinguish them afterwards.

**Comment by modulovalue** [comment]
> I'm not sure how you would get memory benefits from that unless the implementation keeps more than one null value, so it can store both null-int and null-int? in the same memory slot and distinguish them afterwards.

I'm not too familiar with how the Dart VM implements things, but my reasoning for potential memory benefits was: wouldn't a hypothetical `int??`modelled by _a pointer, that can be the nullpointer, or point to another pointer that can be an integer or a nullpointer_, be more efficient than _a pointer, that can be the nullpointer or point to a struct that itself contains a pointer to the value or a nullpointer_ i.e. a `Wrapper<int?>?`.

In any case, thank you for the response. This resolves it for me.

**Comment by lrhn** [comment]
Object references are not pointers as such, and the implementation doesn't allow for "pointer to pointer".
A nullable integer variable contains either a reference to an integer (which is often optimized to storing a tagged integer directly in the "reference") or a reference to the `null` object.
Having to store a third value, to distinguish between no-integer and no-nullable-integer requires a third value. It would effectively be as if there were multiple `null` values, one for each level of `?` wrapping. That value would have to be user-visible because you'd need to check for it: `if (x != null?) ... x is int? ...`.
