### ISSUE TITLE
Null safety: erroneous check with object members

### ISSUE THREAD

**Issue by DenisGL** [dart-lang/language#1343]
Hello,
The issue is illustrated in this code snippet:

```
class Foo {
  String? _string;

  Foo() : _string = '';
  
  String doSomething() {
    return _string==null ? '' : _string; // => ERROR: A value of type String? cannot be returned...
  }
  
  String doSomething2(String? string) {
    return string==null ? '' : string;
  }
}
```
In doSomething(), the compiler issues an error: '**A value of type String? cannot be returned from method 'doSomething' because if has return type of String**.

I don't understand why, because I have handled nullity with the test.

In addition, the same example is working if I get the input String? as parameter, and do not use the member (see doSomething2())

I have Dart 2.12.0-29.10.beta.

**Comment by mnordine** [comment]
It's because flow analysis only works locally in functions, because the type system cannot guarantee fields will not change. This is covered here: https://dart.dev/null-safety/understanding-null-safety#working-with-nullable-fields

I recommend you read that entire article carefully as well.

There are some ideas to address your concerns here: https://github.com/dart-lang/language/issues/1201

**Comment by lrhn** [comment]
As @mnordine says, this is expected behavior. You do not get type promotion on fields, only on local variables.

We are aware that this can be highly confusing, but we have also not been able to find a solution within the current language which isn't either unsound or potentially more confusing (because it might only work some of the time anyway, and now you have a more complex job to figure out why).
