### ISSUE TITLE
Add typescript like Pick<Type, Keys> utility Type

### ISSUE THREAD

**Issue by lazylazyllama** [dart-lang/language#1351]
## Proposal

It would be nice, if dart has the ability to create new Types that contain of a Given type, but only with a subset of properties.
Typescript has something like this implemented via a utility Type called Pick<Type, Keys>:

Example:
```typescript
interface Todo {
  title: string;
  description: string;
  completed: boolean;
}

type TodoPreview = Pick<Todo, "title" | "completed">;

const todo: TodoPreview = {
  title: "Clean room",
  completed: false,
};

todo;
// ^ = const todo: Pick
```

## Use case
This would especially be handy when dealing with generated code for graphql. It would then be possible to just generate all the Graphql Schema types in their pure form, while every query will create its own type by using the base type and then picking only those types, that are required for this specific query.

**Comment by lrhn** [comment]
This seems like something that makes more sense in JavaScript. In Dart, classes are not defined by their properties, but by their interface (getters, setters and methods).
You would have to project a subset of those getters, setters and methods, which is obviously possible, but could get long-winded if there are many methods.

I guess we could do something like `abstract class Foo implements Bar show foo, bar, baz {}` to only implement a subset of `Bar`'s interface. 

It's also not clear whether there should be any subtype relation between the types. In practice, there likely isn't. We could make `Bar show foo, bar, baz` a supertype of `Bar`, but `Foo implements Bar show foo, bar, baz` won't have any relation. 

That probably makes it less useful in practice, you might as well declare the member signatures of `Foo` directly instead of borrowing them from `Bar` if there is no relation between the two anyway. It's just a *syntactic* shorthand, which makes it unlikely to be worth its own complexity.

**Comment by lazylazyllama** [comment]
So it would probably make sense to have something like this, in case `data classes` land.

Maybe it could then be implemented sth. like this:

```dart
class MyCElass {
  String name;
  DateTime launchDate;
  }
}
```

**Comment by lrhn** [comment]
Also sounds like a feature that was discussed for "records", to project a number of fields onto a new record.

**Comment by lazylazyllama** [comment]
Those record types sound very promising. Do you remember where this projection feature was discussed or what the result of the discussion was? :)

**Comment by lrhn** [comment]
I think the comment I was thinking of was https://github.com/dart-lang/language/issues/1319#issuecomment-728888487
It's generally spread over the different `label:patterns` issues.

**Comment by lazylazyllama** [comment]
Okay thank you, closing this for now
