### ISSUE TITLE
Type check failed with Map value

### ISSUE THREAD

**Issue by wliumelb** [dart-lang/language#1352]
Try this in DartPad with Null safety enabled:

```
void main() {
  final Map<String, dynamic> map = {'key1': 1, 'key2': '2'};
  final String val = map['key1'];
  print(val);
}
```

Type checker and compiler did not show any error. Only crash at run time.

**Comment by lrhn** [comment]
That's expected behavior.
The `dynamic` type means *turn off static type checking* (aka, "I know what I'm doing, so shut up, compiler!"), and all type checking instead happens at run-time (aka. dynamically instead of statically).

The expression `map['key1']` has static type `dynamic` because that's the value type of the map. The assignment to `String val` is then compiled as if it was `final String val = map['key1'] as String;`, with an implicit dynamic down-cast which can, and did, fail at run-time.

If you want to avoid the risk of assignments from `dynamic` failing at run-time, then you must, well, stop doing them. Either avoid using the `dynamic` type at all (instead use `Object?`, or `Object` for non-null safe code), or, if you want the `dynamic` for other reasons than assignment, or has it trust upon you by other libraries, enable a lint to warn you when you're doing the downcast:, by putting the following in your `analysis_options.yaml` file:
```yaml
analyzer:
  strong-mode:
    implicit-casts: false
```

**Comment by wliumelb** [comment]
Thank you very much for your detailed explanation and suggestions. It's very helpful.

So `dynamic` is not exactly a type that covers everything, but rather a keyword to disable type checking? 

I think most Flutter programmers (me included until today) that use `dynamic` are not aware of this danger. Maybe a warning in the linter telling them that they should use `Object` rather than `dynamic` could save a lot of apps from crashing down the road. :)

**Comment by lrhn** [comment]
The `dynamic` type allows any value to be assigned to it without error, so in some sense it covers everything. So does `Object?` and `void`, just with different behaviors.

The differences between the three is that if you have a value of type:
* `Object?` (`Object` pre null-safety), you can only call the few methods defined on `Object` on it, and (post null-safety) cannot assign it to a subtype without an explicit cast (pre null-safety, you had implicit downcasts from any type).
* `dynamic`, you can perform any method invocation on the value, and it's determined at run-time whether the method is there. You can assign it to any type, it's determined at run-time whether the value is actually a subtype of the type it's assigned to.
* `void`, you can't invoke *any* methods, and can't assign it to any type except `void` and `dynamic`.

So the types `void` (don't use at all) and `dynamic` (use however you want, checked at run-time) are special behaviors for the actual type `Object?`/`Object`, which is itself just a normal type.
