### ISSUE TITLE
Generic type inheritance

### ISSUE THREAD

**Issue by JanuszHain** [dart-lang/language#1364]
When I try to extend the class with generic type and don't define the generic in child class, then it is treated like dynamic (I think?). It doesn't work if I leave it without passing the generic type down to child, which is problem easy to miss in Dart. I have created [repo](https://github.com/JanuszHain/flutter_generic_function_error
) that showcases the problem.

Not working example:

```
class ManagementListNotWorking<T> extends StatefulWidget {
  final Widget Function(T item) someBuilder;
  final List<T> items;

  ManagementListNotWorking({
    @required this.items,
    @required this.someBuilder,
  });

  @override
  State<StatefulWidget> createState() => _ManagementListNotWorkingState();
}

class _ManagementListNotWorkingState extends State<ManagementListNotWorking> {
  @override
  Widget build(BuildContext context) {
    return Expanded(
      child: ListView.builder(
        itemCount: widget.items.length,
        itemBuilder: (context, index) {
          return widget.someBuilder(widget.items.first);
        },
      ),
    );
  }
}
```

Working example:

```
class ManagementList<T> extends StatefulWidget {
  final Widget Function(T item) someBuilder;
  final List<T> items;

  ManagementList({
    @required this.items,
    @required this.someBuilder,
  });

  @override
  State<StatefulWidget> createState() => _ManagementListState<T>();
}

class _ManagementListState<T> extends State<ManagementList<T>> {
  @override
  Widget build(BuildContext context) {
    return Expanded(
      child: ListView.builder(
        itemCount: widget.items.length,
        itemBuilder: (context, index) {
          return widget.someBuilder(widget.items.first);
        },
      ),
    );
  }
}
```

Warning would be enough so the developer knows that inheritance without passing the type is dangerous and can lead to bugs. Is there any chance to avoid passing type to the child class (now or in some language improvement)?

**Comment by eernstg** [comment]
We have the notion of a raw type, that is, a generic type denoted by an identifier `C` or a construct like `p.C` where `p` is an import prefix, where the actual type arguments are omitted.

It is true that a raw type will typically be a type where the actual type arguments are added implicitly and have the value `dynamic`. The precise rule is known as instantiation to bound, and it typically chooses `dynamic` when no bound is declared. Details are [here]().

You can use `--no-implicit-dynamic` on the analyzer in order to get a diagnostic message in a number of situations, including the one where a superinterface is a raw type.

**Comment by JanuszHain** [comment]
Thank you for the tip :)
