### ISSUE TITLE
Operator type ambiguity

### ISSUE THREAD

**Issue by duzenko** [dart-lang/language#1371]
Consider the code
```
void main() {
  Map map;
  final x = map['x'];
  // compile ok
  print(x + 1);
  print(x + '1');
  // compile errors
  print(1 + x);
  print('1' + 1);
}
```

I can't find what rule controls this in the docs.
What happens in runtime on the first two '+' invocations?
Is operator type supposed to be determined in compile-time or run-time?

**Comment by eernstg** [comment]
Maybe you could indicate in more detail what you expect?

I can see that this code does not use null safety (the declaration of `map` would be an error). So the behavior you get is a dynamic error at `map[...]` because `map` is null.

Assuming that's been fixed, `x` has type `dynamic` and the value of `x` is some object (possibly null).

Then `x + 1` and `x + '1'` will give rise to dynamic invocations of `operator +`. The given object may or may not have that member, and it may or may not accept an argument of type `int` respectively `String`. So the execution may will throw an exception at that point.

`print(1 + x)` is not a compile-time error (despite the comment), but it will include a dynamic type check on `x`: The `operator +` on `int` requires an argument of type `num`. Similarly, `1 + '1'` is a compile-time error because the static type of `'1'` is `String`, which is not a subtype of `num`.

You can find information about the details in the DartDoc info, e.g., [for `num.operator +`](https://api.dart.dev/stable/2.10.4/dart-core/num/operator_plus.html), and about the broader topics in the [Language Tour](https://dart.dev/guides/language/language-tour).

@duzenko, I'll close the issue because it does not seem to raise any issues in need of fixing, and it does not propose any new features. But you're of course very welcome to create a new issue if something in this one has not been covered appropriately.

**Comment by duzenko** [comment]
@eernstg 
Thank you

You say that 
> print(1 + x) is not a compile-time error 
but in my Flutter app it actually gives dart analyze errors

```
error: The argument type 'dynamic' can't be assigned to the parameter type 'num'. (argument_type_not_assignable at [pavement] lib\main.dart:14)
error: The argument type 'int' can't be assigned to the parameter type 'String'. (argument_type_not_assignable at [pavement] lib\main.dart:15)
```
Should I assume that the project should still compile and run despite that?

**Comment by eernstg** [comment]
Sounds like you are using more strict settings than the default for the analyzer, say, `--no-implicit-casts`? In that case you'll need to have an explicit cast, `1 + (x as num)`. For the `int`/`String` error you probably want to resolve the problem: Only null can have type `int` as well as `String` (and even that won't work when we switch to code with null safety).
