### ISSUE TITLE
Allow parameter mismatch in method overriding.

### ISSUE THREAD

**Issue by devongalat** [dart-lang/language#1383]
I am using Flutter to create an app and I am creating an abstraction layer for my widgets. One of the features of this abstraction is that I need to override `Widget build(BuildContext context)`. My implementation requires a function as such, with an additional argument: `Widget build(BuildContext context, Controller controller)`. I am currently unable to override the original method using this new implementation due to an `invalid_override`.

What I was forced to do is to create a new method to override, and instead make `Widget build(BuildContext context)` empty / not return anything and ignore the hint `missing_return`.

I should instead be able to override using an additional argument as such, without getting any errors:
```
@override
Widget build(BuildContext context, Controller controller);
```

**Comment by srawlins** [comment]
For now you can make the second parameter optional:

```dart
Widget build(BuildContext context, [Controller controller]) {
  assert(controller != null);
}
```

**Comment by mraleph** [comment]
@devongalat what you want to do violates the fundamental principle (often referred to as Liskov’s substitution principle) that an instance of a subclass can be used anywhere where base class is used. Practically it means that if you have a variable of type `Widget` you can call `build` method on it with a single parameter and this invocation succeeds because any value stored in such a variable is guaranteed to have a legal (that is compatible) override of `build`. However if you were to allow illegal overrides it would no longer be the case - eg in your case such invocation would throw an exception because an additional parameter is missing. That’s a very bad behavior (and a massive source of potential issues) and as such it will not be allowed.

**Comment by devongalat** [comment]
@mraleph Thank you for the reply. Could you consider therefore to add a suggestion to the user to instead implement an optional parameter when one tries to create an invalid override as srawlins wrote earlier?

**Comment by srawlins** [comment]
The optional parameter I suggested, and then asserting it is non-null, is very much a hack, and you're still violating the principles that @mraleph discusses. I don't think it is a suggestion our tooling should be making.

**Comment by devongalat** [comment]
What you consider a hack, I consider to be a great solution to ugly code which would perform the same task. ( Before you made your suggestion, I tried to do it by creating an additional function, and the code looked much less clean than it does now. )

**Comment by lrhn** [comment]
You should name your method with a different name.

Your method is not the `Widget.build` method. It cannot be used by other code which expects to call a `Widget`'s `build` method because they *will* call it with one argument. So, it shouldn't be overriding `Widget.build` and claim that it is one.
Just call it `buildWithController`. Any code which knows that it must call the method with two arguments *must* also know that it's an instance of your class, and therefore it can also just call `buildWithController` instead.

Dart doesn't have overloading like, say, Java or C#. If you have method with different, incompatible, signatures, you should give them different names.
