### ISSUE TITLE
Map matchers require "not equivalent" keys, which doesn't work for all maps.

### ISSUE THREAD

**Issue by lrhn** [dart-lang/language#1407]
See [pattern proposal](https://github.com/dart-lang/language/blob/master/working/0546-patterns/patterns-feature-specification.md#map-matcher).

Map matchers require the keys to be constant (which is somewhat reasonable) and distinct ("not equivalent", which I assume means not `==`).
However, maps may use non-default equalities for their keys, so it's possible to have a map (like an identity map, which is supported directly by the platform libraries) where two keys are `==`-equal.

Map matchers should be able to be handle these cases too.
I suggest only requiring that the keys are *non-identical*. If a map satisfies that it matches `{x1: var a, x2: var b}` by considering `x1` and `x2` both equal to *one* of its keys, then the match succeeds. That would be no different from a mock `Map` with `length` of 1 which returns `42` on every lookup and `true` on every `contains` (and a single key object which claims to be `==` to everything, if you check the keys).

**Comment by munificent** [comment]
I think the proposal more or less covers what you want here. It says that *if* some pair of keys both have primitive equality methods, then it's a compile-time error if they are not equal according to those methods. Otherwise, there is no compile-time checking for that pair being distinct. This lets you use types with user-defined `==` as keys in map patterns but also gives you some static checking for duplicates in cases where the compiler is able to.
