### ISSUE TITLE
Null safety feedback: return after Map containsKey test should be non-nullable

### ISSUE THREAD

**Issue by kaladron** [dart-lang/language#1416]
Given this:

```
  final Map<String, String> _specialWords = {
    "skis": "ski",
    "skies": "sky",
  };
```
This construct:

```    if (_specialWords.containsKey(_word)) return _specialWords[_word];```

should consider the return type to be acceptable as String rather than String?

```$ dart --version
Dart SDK version: 2.12.0-133.7.beta (beta) (Tue Jan 12 09:25:38 2021 +0100) on "linux_x64"```

**Comment by Cat-sushi** [comment]
You can also rewrite your code as:

```dart
if(_specialWord[_word].containsKey(_word)) return _specialWord[_word]!;
```

**Comment by kaladron** [comment]
I did the one with the exclamation in my code, but that's just casting away NULLness.  If I'm wrong (or the if check evolves) then the compiler can't catch my mistake.

**Comment by eernstg** [comment]
>  If I'm wrong (or the if check evolves) then the compiler can't catch my mistake.

I think that's the core of the issue here: As mentioned by @julemand101, the compiler can't assume that `operator []` of `_specialWords` satisfies any constraints beyond the ones that the type system can recognize. But if we were to change the static analysis such that the `!` can be omitted in this case then the compiler _still_ can't catch the "mistake" (of having a receiver whose `contains` may return true even in the situation where a subsequent `operator []` returns null). The compiler would then have to insert an implicit `!` in order to avoid the potential soundness violation&mdash;and presumably you wouldn't be much happier about casting away nullness implicitly than doing it explicitly.

A `@notNullIfTrue bool` return type could not be supported by static analysis unless we'd have a very restricted interpretation of its meaning: _Any_ method invocation between the occasion where `contains` is tested and the occasion where `operator []` is evaluated could run code that we cannot identify statically, and that code could modify the map. For instance, it would most likely be an error if `_specialWords` was changed such that evaluation invokes an explicitly written getter rather than a compiler-generated getter (that just reads the storage location of a variable). The static analysis of Dart does not have the notion of "no unknown code is invoked between event E1 and event E2" for any events E1 and E2, and we're not likely to ever get it, it is simply too fragile and non-modular to be practical.

**Comment by lrhn** [comment]
Generally, I recommend using `var other = _specialWords[word]; if (other != null) ... use(other) ...` for situations where your values are not going to be `null` (like @mraleph suggested above), and only using `containstKey` when a valid value *might* be `null` (in which case using `!` is also not correct).

Using `if (map.containsKey(key)) use(map[key]!);` is already inefficient for looking up the key twice.

There are lots of different deductions you can make from APIs that the compiler won't know about.
Say `if (list.isNotEmpty) list.firstOrNull.doSomething();` is always safe because `list.firstOrNull` will return a first element if the list is not empty. The compiler doesn't know this connection, and we won't make it. 
The same can be said for maps. There are *many* ways to ensure that a key is actually in a map prior to looking it up, like `for (var k in map.keys) use(map[key]);`. That's not visible in the *type system* or the *object model*, so the compiler cannot trust it.

Also, it cannot be trusted *exactly* because the language cannot prevent someone from making an implementation which doesn't follow the rules.

With null safety, we went with explicitness over implicitness. You don't get to silently do a `null` check, you have to write `!`. That way, it won't be any surprise to you if that check fails. That does mean that you can't omit the `!` even if it's painfully obvious that the API ensures the value won't be `null`. 
(What we do need is a getter on maps which throws if the key isn't there. It was too breaking a change to change the existing `[]` operator, sadly.
Maybe (but likely not):
```dart
extension MapGet<K, V extends Object> on Map<K, V> {
  V call(K key) => this[key] ?? throw StateError("no element");
} 
// ...
Map<int, int> map = ...;
int y = map(2);
```
That could work, and you would still have to use `map[key]` if the value type is potentially nullable.)

**Comment by kaladron** [comment]
It seems like the concern is people doing surprising things with implementations of functions.  I think I'm wishing for annotations on these functions so that it's not implicit, but is explicitly part of the contract that, say, ```operator[]``` doesn't have side effects, etc.  Rather than an "any function can do anything" model.  That way the optimizer could find more opportunities for things as well (caching results, etc).

This PR is probably closeable now.  Thank you!

**Comment by leafpetersen** [comment]
Ok, closing this out, thanks for the discussion!
