### ISSUE TITLE
Generic typedef is difficult to assign a value to

### ISSUE THREAD

**Issue by atreeon** [dart-lang/language#1418]
I have the following three typedefs
```
typedef fna = T Function<T>(int c, T d);
typedef fnb = T Function<T>(String c, T d);
typedef fnc = int Function<T>(String c, T d);
```

I can't seem to assign a function to two of them

The first one I can assign a value
`fna a = <String>(int c, String d) => "blah" as String;`

The next two look similar but I get a compile error using a similar syntax and if I use a cast that fails at runtime.

    fnb fny1 = <String>(String c, String d) => "blah" as String;
    fnc fnz = <String>(String c, String d) => 5 as int;

Am I doing something wrong here?

**Comment by lrhn** [comment]
Your first assignment is probably not doing what you think it's doing, so yes, you're likely doing something wrong. 
You write `<String>`, but that's a type *parameter* named `String`, not a type *argument*. It's the same as:
```dart
fna a = <S>(int c, S d) => "blah" as S;
```
just with a longer name for the type variable (one which looks confusingly like an actual type).

When you try the same thing with the other two, *you shadow the `String` type*, so the *first* parameter will have the type variable named `String` as type, and not the `String` from `dart:core` as required. That's why it won't work.
It's like writing:
```dart
fnb fny1 = <S>(S c, S d) => "blah" as S;
```
which means that the `c` parameter doesn't accept a real `String` as it should.

The valid assignments I'd do are:
```dart
fna a = <T>(int c, T d) => d;
fnb b = <T>(String c, T d) => d;
fnc c = <T>(String c, T d) => 42;
```
These satisfy the type constraints - the assigned function is a generic function, it takes the required parameters and returns something of the correct type. For the first two, the only available value of type `T` is `d`.

If this is not what you want, it's not completely clear what you do want.

**Comment by atreeon** [comment]
Thank you so much @lrhn ...yes, I think I'd got confused with the locations of type arguments and type parameters

Thank you for showing the generic version of the typedef too
