### ISSUE TITLE
Type inference not promulgated for subclass constructors?

### ISSUE THREAD

**Issue by samuellow** [dart-lang/language#1422]
I stumbled across a runtime error where parameters of a constructor did not match the expected types. I wrote the following snippet to verify the issue.

```dart
class A {
  String aa;
  
  A(this.aa);
  
  void abc(String d) {
  }
}

class B extends A {
  B(b) : super(b);

  void abc(d) {
    super.abc(d);
  }
}

void main() {
  A(true); <-- compilation error as expected
  B(true); <-- no compilation error, runtime error!
  var b = B('');
  b.abc(true); <!-- compilation error, inference works for non-constructor functions
}
```

Is this artifact already mentioned in the language specs? I'm a two-month Dart noob so please forgive my ignorance.

**Comment by leafpetersen** [comment]
There is no type inference happening in your program.  Dart does much more limited type inference than you may be used to if you come from languages like Haskell, ML, or perhaps Scala.  In particular, constructor parameter types are never inferred, and method parameter types are only "inferred" by copying them down from overridden methods (if any).  Closure parameters are subject to inference where possible.

In general, in Dart, constructor and method parameters with no specified type are given type `dynamic`, which means all static checking is suppressed.  For your example, `A(this.a)` is statically typed to take a `String`, since `this.a` is a field formal which has a defined type.  But `B(b)` doesn't specify a type for `b`, so the type is "inferred" as `dynamic`.  This means you can pass anything as a parameter to `B`.  The call to `super(b)` then has an implicit cast from `dynamic` to `String`, which fails at runtime.

Hope this helps.
