### ISSUE TITLE
Factory methods are not eligible for function assignment

### ISSUE THREAD

**Issue by pak3nuh** [dart-lang/language#1429]
I all,
I use functions a lot and I love the Dart deals with them, except for one minor issue.
I can assign static methods as function types for input parameters, but not named constructors or factory methods. I'm sure this is a design choice but it tickles my brain.

For instance, JSON deserialization forces me to expose static methods instead of factory methods, which makes more sense semantically.
```dart
typedef Functor<T, W> = W Function(T input);

class Person {
  final String name;
  final int age;

  Person(this.name, this.age);

  factory Person.deserialize(String json) {
    throw UnimplementedError();
  }

  Person.deserializeCtr(String json): name = "", age = 0;

  static Person deserializeStatic(String json) {
    throw UnimplementedError();
  }
}

// Functor<String, Person> personDeserializer = Person.deserialize;
// Functor<String, Person> personDeserializer2 = Person.deserializeCtr
Functor<String, Person> personDeserializer3 = Person.deserializeStatic;
```

Do you intend to allow this in the future or is there any major reason why you won't?

**Comment by lrhn** [comment]
We do hope to allow constructor tear-offs at some point, for all constructors, not just factories.

**Comment by pak3nuh** [comment]
That is good news :smiley: 

Do we have a rough timeline?

**Comment by lrhn** [comment]
No timeline whatsoever, sorry. It's not on the short list of things that we are currently actively planning for. I'd say ... maybe this year. Or maybe not. 🤞 

It's one of those features which isn't *very* important because there is a workaround ... it's just darn annoying every time you have to write `(x) => Foo.foo(x)` instead of just `Foo.foo`. I guess the only thing holding us back is opportunity cost. What would we *not* do instead? Currently that other thing seems more important.

**Comment by FMorschel** [comment]
I think this is solved already @lrhn

**Comment by lrhn** [comment]
It is indeed. Thanks.
