### ISSUE TITLE
Do we need a generic constraint for nullable only generics?

### ISSUE THREAD

**Issue by leafpetersen** [dart-lang/language#143]
The following class will be ill-formed when we move to non-nullable types:

```dart
class C<T> {
  T x;  // Error, since T may be non-nullable, and x is not initialized
  List<T> l = new List(10); // Error, since T may be non-nullable and the list is not initialized
}
```

One solution is to simply require the user to manually put a `?` on the type where required:

```dart
class C<T> {
  T? x;  
  List<T?> l = new List(10);
}
```

Another possibility is to allow the class to specify a constraint indicating that it may only be applied to nullable types:

```dart
class C<T?> {  // T is required to be nullable
  T x;   // Ok, required to be nullable
  List<T> l = new List(10); // Ok, required to be nullable
}
```

It's not clear how common this is.  Also, this is something that could probably be added later if we discover we really want it (though changing classes to use it would be a breaking library change).

cc @lrhn @munificent @eernstg

**Comment by munificent** [comment]
For the record, my position on this is and has been that I don't think this is needed or very useful. If we get evidence to the contrary, I'm definitely open to adding it. When I was prototyping NNBD a while back and converting over the core libraries, I don't recall running into cases where I wanted this.

**Comment by eernstg** [comment]
@leafpetersen wrote
> But this class is now not usable in a context where you have
> a type variable which is not known to be non-nullable.

If that other type variable, `X`, can genuinely be nullable (that is, if it can be a supertype of `Null`, which is true if its upper bound is a supertype of `Null`) then we would genuinely need to adjust its value before using it with `A`, but that could be specified as `A<X!>`, cf. [this comment](https://github.com/dart-lang/language/issues/142#issuecomment-455117211).

Otherwise, if that other type variable `X` should also be non-null, its declaration should be adjusted to `X extends Object`, in which case the problem becomes a migration issue (but `A<X!>` might be used during the migration, and a lint could later reveal cases where that `!` operator is used but not needed).

**Comment by leafpetersen** [comment]
@lrhn Where are you in your thinking on this?  I still think that I'm on the side of the fence that this is not needed, but open to discussion.

**Comment by lrhn** [comment]
I think I'm also hoping it won't be needed, but I want to keep the door open to being convinced otherwise.
So, maybe start out without the feature, but don't design ourselves into a corner where it cannot be added.

If we start seeing classes where the type variable is nullable-bounded (or unbounded) and all occurrences of the type variable has a `?`, then we probably needs the feature.

If we have `!` as a user-available operator on type variables, then I'm not as worried, then you can use a non-nullable bound and null all the type variable occurrences without getting into ambiguity where `C<int?>` isn't assignable to `C<int>`, even if they are really the same.

**Comment by leafpetersen** [comment]
I think we're converging towards holding off on this.  @lrhn is there discussion/thoughts you want to raise or just record here for posterity?

**Comment by lrhn** [comment]
I've become more convinced that not having this feature is a good thing.

If you actually care whether your the type of your type variable is nullable, you should just make it non-nullable and write the `?` as appropriate. If you inspect the value of a potentially nullable type variable, then you're probably doing something weird and fragile.

I'm actually close to requiring all actual bounds to be non-nullable, the only way to get non-nullable type variable is to use no bound and accept all types, because that means that you won't be able to expect anything from the object anyway, only passing it through uninspected. 

A generic type parameter like `F<X extends int?>` can be fulfilled by `int?`, `int`, `Null` and `bottom`. Here `int` and `Null` have *nothing* in common, so the bounds buy you nothing. If something has type `X`, you can't do anything to it without first checking that it's not `null`, then you know that it's `int` and can use that. Internally in the generic code. There is no difference from declaring it as `F<X extends int>` and writing `X?` as the type. The only reason to allow that would be to allow the client code to have either `F<int>` or `F<int?>` (or `F<Null>`) and knowing something about the values coming out of the code. This feels speculative.

I think allowing nullable type bounds is fine from a consistency standpoint, but I expect style guides to recommend against it unless the bound is `Object?` anyway.

**Comment by eernstg** [comment]
@leafpetersen, @lrhn, sounds like we can conclude that we will _not_ have a mechanism that allows a type variable declaration to require that the value must be a nullable type. "**Decision**" and close?

**Comment by leafpetersen** [comment]
Decided, no, we can always add this later if we find it's important.
