### ISSUE TITLE
Discussion issue for grammar ambiguities with non-nullable types

### ISSUE THREAD

**Issue by leafpetersen** [dart-lang/language#144]
This issue is to discuss and resolve any parsing ambiguities associated with non-nullable type syntax.

Known potential ambiguities:
  - `a is int ? - 3 : 3;`
    - this is valid pre-NNBD code, does it change meaning after NNBD?

cc @lrhn @munificent @eernstg @danrubel

**Comment by munificent** [comment]
This is a gnarly one. Let's say we take:

```dart
{ a as int ? - 3 : 3 }
```

and default to interpreting it as:

```dart
{ (a as int) ? -3 : 3}
```

If that's *not* what you want, how do you get the other interpretation where `?` is part of the type? We don't currently allow you to parenthesize a type annotation. So one option is to allow that, then require:

```dart
{ a as (int?) -3 : 3}
```

That feels a little weird to me because in typical formatting, the `?` already looks like it binds tighter as a type (no space before the `?`) than as a conditional operator.

The other option is to default the other way. Treat the `?` as part of the type. If you want it to not be, you have to explicitly parenthesize:

```dart
{ (a as int) ? -3 : 3}
```

I think we could probably do this by shuffling around the grammar so that a conditional expression's conditional prohibits a `testTest` or `testCast` expression. You'd have to get through it by going through `primary` and parenthesizing.

This is a breaking change and, unfortunately, I think a fairly common one.

**Comment by leafpetersen** [comment]
> This is a gnarly one. Let's say we take:
> 
> ```dart
> { a as int ? - 3 : 3 }
> ```
> 
> and default to interpreting it as:
> 
> ```dart
> { (a as int) ? -3 : 3}
> ```
> 
> If that's _not_ what you want, how do you get the other interpretation where `?` is part of the type?


Seems to me that asking whether `a is int?` is probably something you essentially never want to do.  We currently don't provide any way to do this (if you ask `a is int` in current Dart, it returns false for `null`).  

Perhaps we should just disallow `T?` in `is` checks, or else allow it but prefer the `(a is int) ? e1 : e2` parsing?  If you really want to do an `is` check on a nullable type then you can use a type alias (once we have general type aliases).

**Comment by yjbanov** [comment]
When would one want `A ?` to mean nullable `A`? I think `A?` (i.e. no space between `A` and `?`) is the only reasonable way to state it. The same goes for the conditional operator. There has to be whitespace preceding `?`.

**Comment by bwilkerson** [comment]
> This is a gnarly one. Let's say we take:
>
> `{ a as int ? - 3 : 3 }`
>
> and default to interpreting it as:
>
> `{ (a as int) ? -3 : 3}`
>
> If that's not what you want, how do you get the other interpretation where `?` is part of the type?

Assuming I needed to write that, I'd want to write it as `{ (a as int?) - 3 : 3}`.

**Comment by munificent** [comment]
> Seems to me that asking whether a is `int?` is probably something you essentially never want to do. 

I suppose so, but it feels weird to prevent a semantically meaningful operator for syntactic reasons. If we add other kinds of type annotations, we'll probably run into this problem again.

I can also imagine code that might want to do this. Consider some API that accepts `int`, `null`, or `String`, and forwards the first two to some other API that accepts `int?`.

> Assuming I needed to write that, I'd want to write it as `{ (a as int?) - 3 : 3}`.

Good point. :)

**Comment by leafpetersen** [comment]
Ok, so for the conditional expression ambiguity, it sounds like we can resolve by first trying to parse as a conditional expression, and so prefer the parse `(a is int) ? -3 : 3` over the parse `(a is int?) -3 : 3`.

**Comment by danrubel** [comment]
That is certainly my understanding of this situation. I'm making parser
mods to that end unless I hear otherwise.

**Comment by leafpetersen** [comment]
A note on grammar: the grammar for types will only allow a single `?`.  That is:

```
type' ::= functionType
          | qualified typeArguments? 

type ::= type' `?`?
```

So 
```dart
  int ? ? x = 3;
``` 

is a parse error.

Also, `int??String` parses as `(int) ?? (String)`.

**Comment by danrubel** [comment]
Agreed. That is the case and I've just [added parser tests](https://dart-review.googlesource.com/c/sdk/+/90800) to ensure as much.

**Comment by lrhn** [comment]
The grammar has now been defined, including the ambiguity introduced by null-aware index operators.
