### ISSUE TITLE
Is Dart type system sound?

### ISSUE THREAD

**Issue by mateusfccp** [dart-lang/language#1461]
I don't know if I understood this correctly, but accordingly to the [Dart online documentation](https://dart.dev/guides/language/type-system), the language's type system is sound.

However, both the [latest available specification](https://spec.dart.dev/DartLangSpecDraft.pdf) (page 200) and the [current formal specification](https://dart.dev/guides/language/specifications/DartLangSpec-v2.2.pdf) (page 175) clearly states:

> The type system is **unsound**, due to the covariance of generic classes. This is a deliberate choice (and undoubtedly controversial). Experience has shown that sound type rules for generics fly in the face of programmer intuition. It is easy for tools to provide a sound type analysis if they choose, which may be useful for tasks like refactoring.

Is one of them incorrect or does they refer to a different kind of soundness and I am messing up these things?

**Comment by eernstg** [comment]
The Dart type system maintains a sound heap (that is, a variable of type `T` will refer to an object of type `T`), but it does so by checking many things statically, and a few things dynamically.

The major example of a property which is checked dynamically is associated with contravariant occurrences of a type parameter: Dart class type parameters are treated as covariant (no matter how they are used), and this implies that some methods where a formal parameter type is a type variable, or contains a type variable in a covariant position may be invoked such that the type of the actual argument isn't a subtype of the declared type. In this case a dynamic error occurs.

```dart
void main() {
  List<num> xs = <int>[];
  xs.add(2.5); // Throws at run time.
}
```

**Comment by mateusfccp** [comment]
@eernstg Sorry, there was no template for "question", so I chose "bug in the spec" one, but I can't change labels by myself... My original intention was, indeed, to label it as a "question".

I think your answer clarifies the case for me, so I am closing this, thanks.

Looking forward to #524.

**Comment by leafpetersen** [comment]
> The terminology may differ, however, so some people might say that the dynamic checks imply that the type system is unsound, no further discussion needed.

They might, but.. they would be wrong.  Soundness has a well-defined meaning in the literature, and it is entirely consistent with dynamically checked properties.  While we have not proved soundness for the language, we do intend it to be sound (in the standard sense), and it does seem like a bug to me that we explicitly the contrary. I think this is leftover text from Dart 1, right?  Shouldn't we remove this?

**Comment by fweth** [comment]
> For anyone who wants to allow developers to write even more precise types and eliminate even more of the dynamic checks (like me ;-), we have features like declaration-site variance coming..

Will declaration-site variance ever make Dart statically sound, in the sense of no dynamic type checking, or will it be an optional thing?

**Comment by modulovalue** [comment]
I was confused by this as well. I think I understand now where any possible confusion might come from and I'd like to share what I've learned:

The [wikipedia entry](https://en.wikipedia.org/wiki/Soundness) for soundness refers to soundness as a property that must be considered relative to some logical system. If the assumptions are true and all inference rules in the logical system are sound, then all conclusions can be assumed to be true as well.

Compiler writers might refer to soundness of the static type system as the property that all static types need to "match" the dynamic types. See: [Alex Aikens Stanford Lecture on Compilers](https://www.youtube.com/watch?v=9p_s457RSQE&list=PLTsf9UeqkRebOYdw4uqSN0ugRShSmHrzH) (I don't remember the exact video/timestamp, but IIRC it is discussed there from that perspective) or see: [The Seven Sources of Unsoundness in TypeScript](https://effectivetypescript.com/2021/05/06/unsoundness/)

Static analysis researchers might refer to soundness as the property of static analyses to match the semantics of the programming language (or to be less precise in a way that does not violate the semantics). See: [Static Program Analysis by
Anders Møller and Michael I. Schwartzbach p. 176](https://cs.au.dk/~amoeller/spa/spa.pdf)

There's a paper that discusses the unsoundness of the old static type system of Dart. See: [Type Unsoundness in Practice: An Empirical Study of Dart](https://cs.au.dk/~amoeller/papers/undart/paper.pdf) (the 4th reference refers to "Why Dart types are optional and unsound." and if you click on the link, it redirects to a page that states "Dart has a sound type system" which is very confusing)

From the perspective of a user of Dart, the `covariant` keyword as well as casts using `as` could also be seen as sources of unsoundness because they allow one to escape the soundness guarantees of the type system.

Logicians might claim that their logical system is sound **and** complete. Mathematicians might say [that's impossible](https://en.wikipedia.org/wiki/Gödel%27s_incompleteness_theorems)

This inconsistency can be explained by [Rice's theorem](https://en.wikipedia.org/wiki/Rice%27s_theorem) i.e. the system that a logician might refer to is not [powerful enough which allows it to be sound and complete](https://youtu.be/k6xH47tIS_I?t=168)

I have also seen soundness and completeness be used as some "absolute/global properties" not relative to anything, to express that, in general, we can't be sound and complete at the same time. We can be always be sound by saying nothing. And we can always be complete by saying something.

Apart from theoretical concerns, there is some natural language related confusion as well. In German, soundness is known as [Korrektheit](https://de.wikipedia.org/wiki/Korrektheit_(Logik)) which means correctness, but the english correctness also translates to Korrektheit. In English, soundness can be used as a synonym for robustness i.e. "the state of being in good condition" and not at all refer to any formal notion of soundness. I suspect that other natural languages have similar issues.

I have concluded for myself that the concept of "soundness" is heavily overloaded and therefore highly ambiguous.

**Comment by eernstg** [comment]
Cf. https://github.com/dart-lang/language/pull/2883.

**Comment by mateusfccp** [comment]
I'm closing this, as I think the new redaction makes it more clear and is consistent with the online documentation aforementioned.
