### ISSUE TITLE
Default values for non-null primitives 

### ISSUE THREAD

**Issue by esDotDev** [dart-lang/language#1473]
With the addition of nnbd, it would be nice if non-null "primitives" could default to String.empty, false and 0 respectively as they do in C#, saving us a bunch of pointless typing.

**Comment by esDotDev** [comment]
I definitely don't understand all the ramifications from it, but as a developer, it's quite rare that I initialize non-static primitive fields to anything other than essentially their "0" value, be that false, 0, or "". 

It would just be nice to optimize for that primary use case.  

In C# I've always found quite nice that the compiler complains when you do `int i = 0;` asking you why you are assigning a default value to something that already has that default value. It makes the non-defaults stand out as well, when you do assign something, it means something, instead of just  a wall of false, "", 0's

In terms of num, I can't reason about that much as we really avoid using num at all in our actual code. Obviously in C# they have 0d and 0f, but not sure how relevant that is to this issue.

**Comment by Kavantix** [comment]
I have to disagree, having variables have default values has consequences that change some nice behaviors that were added because of nnbd
For instance you can now define a variable as non null, assign in a switch and get a compile time error if you missed a case and use the variable. With default values this would no longer be possible since it will always have a value already.

**Comment by esDotDev** [comment]
I don't really see how this would be a big issue with numbers, strings and ints. That sliver of a use case doesn't really seem worth all of the boilerplate imo. 

I don't really see these as mutually exclusive, like I would like both of these things to work. Are you disagreeing this has value at all, or jus that it's not worth the trade-offs?

I wonder if the the late keyword can help address that use case? This would indicate its non-null, but someone will assign it before it should be used:
```
late int id;
switch(0){
  case 1:
      id = 1;
}
print(id + 1) // compiler can detect issue here, no?
```

**Comment by tatumizer** [comment]
What happens if you simply forget to add "?" to your type declaration? NNBD is a new thing in dart, I'm still forgetting about "?" while writing my programming etudes. Fortunately, the compiler alerts me about the omission.
```
int x; 
print(x); // ERROR: the non-nullable local variable x ... blah blah
```
I intended x to be nullable, but instead of "int?" said "int". Or I'm overstressed and have no capacity to even think about nullability at all. Or I've never heard about this NNBD feature, to begin with. Or something. 

With the proposed change, no error message will be printed. This goes against the spirit of NNBD IMO.
