### ISSUE TITLE
Allow final fields to be set in the constructor body

### ISSUE THREAD

**Issue by cedvdb** [dart-lang/language#1508]
At the moment if you need to set a bunch of final fields you can use an initializer. As soon as you have some conditions in the initialization process, you have to use a static method in the class to keep the code readable.

This indirection shouldn't be here.

You can also use the late keyword to do the initialization in the constructor body, the problem with this is that it is not typechecked for null, ie if you forget to do the initialization at all, the variable will be null and this will be a runtime error.

```
void main () {
  final t = Test();
  print(t.b + t.a);
}

class Test {
  final int b;
  late final a;
  
  Test() : b = 3;
}
```

All in all, I think this design decision brings more shenaningans that need to be. 

 - late should be set on the same line eg:
 
```
   // should not be valid
   late final a;
  // valid
   late final a = b +1;
```

  - the constructor body should allow setting the final values.

**Comment by munificent** [comment]
In case you're curious, the language works this way deliberately. If you allow final fields to be initialized in constructor bodies, then it's very very hard to ensure that the field is initialized before it is read. Consider:

```dart
class C {
  final int x;

  C() {
    harmless();
    x = 123;
  }

  void harmless() {
    print('nothing going on here');
  }
}

class Nefarious extends C {
  void harmless() {
    print(x); // Oops!
  }
}
```

This is a real issue in Java and C#: It's possible to read final/readonly fields before they have been initialized. Because of the languages both specify that all fields are forcibly initialized to their default values before the constructor body begins. That initialization takes time and increases code size for almost no value. Also, it means there must be some notion of "default value" for all types. It's one of the reasons it would be much harder to make null safety sound in those languages.

In Dart, there is no concept of default value for a type at all. If you have a final variable or field, the language 100% guarantees that its initializer will have run before you can observe it. Constructor initializer lists are an important part of that because they ensure each final instance field is initialized *before* any code has access to `this` and is thus able to read the fields.

It *is* annoying to have to structure your code around this restriction. Long long ago, we talked about having a way to mark inside the constructor body when all fields are initialized and then only provide access to `this` after that point, but I don't think the original language team put much work into it.

I find factory constructors work pretty well for most cases where initializer lists are too restrictive.
