### ISSUE TITLE
Make Short, Long, Byte, Float, Char, ... as STANDARD types!

### ISSUE THREAD

**Issue by CXCubeHD** [dart-lang/language#1519]
Dart has a huge problems, and those are the missing types. I know that they aren't really missing, but they should be a default type, just like in C++ and C#.

We need to have both **SIGNED** and **UNSIGNED** types:
```
unsigned int ui = 0;
uint = 0; // Pls add this it is faster to write
```

We also need other types as "DEFAULT TYPES":
```cs
byte b; // unsigned byte
sbyte sb; // signed byte
signed byte sb2;
short s;
ushort us;
unsigned short us2;
long l;
ulong ul;
unsigned long ul2;
float f = 10f; // !
decimal d = 100000000000000000000000000000000; // Just like in C#
char c = c'F'; // add c as a prefix so it is clear that it is a char
```

String, Object also should be a standard type, so they should start with a lowercase letter:
```cs
object o;
string s = 'Hello World';
```

Adding this wouldn't be hard at all and that would make our lifes easier and more enjoyable.

Edit:
Object and String can have uppercase versions of them, just like in C#

**Comment by mateusfccp** [comment]
I don't see this as a huge problem, and don't think the team should spend resources on this anytime soon.

Do you have a  use-case with a specific limitation by not having these types?

**Comment by lrhn** [comment]
This is technically not a language request, but a library request.
The only thing that needs to change in the language is if the new types should implement `num`.

**Comment by CXCubeHD** [comment]
> I don't see this as a huge problem, and don't think the team should spend resources on this anytime soon.
> 
> Do you have a  use-case with a specific limitation by not having these types?

If you are working with native code for example. Also I think that this is a must have that every language should have. It allows the developer to make more efficient code, so for example you could use the unsigned int to gain more data as if you were using the signed int. Also adding this would be easy, as a developer I think it would take a maximum amount of 20 hours to fully implement it while having it stable, and I am only counting that for a single developer, so if many people would do that then it would be even faster. Also for ints it might be okay to not have an unsigned version, but stuff like bytes, shorts, longs and floats must be there! I don't want to rely on a third party libary that doesn't support null safety yet and that doesn't implement them really well.

**Comment by CXCubeHD** [comment]
> This is technically not a language request, but a library request.
> The only thing that needs to change in the language is if the new types should implement `num`.

I think this is a language request, because the compiler handles those native types, like C++ or C#. And that's why I think this reason is not valid at all

**Comment by mateusfccp** [comment]
> If you are working with native code for example. Also I think that this is a must have that every language should have. It allows the developer to make more efficient code, so for example you could use the unsigned int to gain more data as if you were using the signed int.

I highly disagree with you. Different languages have different approaches and different use-cases. Having absolute control over how memory is being used is a **must** in languages like C and C++ because of their lower-level nature. They are often used in resource-critical environments and embedded devices.

There are other languages that are focused on higher-level abstractions, like, for instance, Haskell. Having control over memory is really something that no one would like to have in Haskell by its own nature. It's also not a kind of language that you want to use in resource-critical environments.

I, particularly, don't think this is a **must** in Dart. It's not that it wouldn't be useful at all, but it's really not something that most people that use Dart miss.

> Also adding this would be easy, as a developer I think it would take a maximum amount of 20 hours to fully implement it while having it stable, and I am only counting that for a single developer, so if many people would do that then it would be even faster.

Well, as it's simple to you, you can make a contribution to the repositories. Although it's not currently a priority of the Dart team, I am sure that if you provide a reasonable implementation they may eventually merge it.

**Comment by CXCubeHD** [comment]
> Well, as it's simple to you, you can make a contribution to the repositories. Although it's not currently a priority of the Dart team, I am sure that if you provide a reasonable implementation they may eventually merge it.
> 
> 

I am not a main dev in this project, so I don't really know the project structure and where everything is. But I think that a main developer would be able to add that. Also high level languages like C# also have those types, so I don't think that this reason is very good.

**Comment by lrhn** [comment]
For the record, using a smaller type is not necessarily more *efficient*. 

Dart is an object based language where event integers are objects, and can be stored in a `List<Object>`. The optimization used to enable this somewhat efficiently is tagged "small integers", where some of the bits are used for the tag. 
If we have different *kinds* of integers, we will need more tag bits. If compiled to a 32-bit architecture, that might be costly.

Also, while 8-bit and 32-bit operations can be as fast as 64-bit operations, and potentially smaller, 16-bit "shorts" are likely to be less efficient on modern x64 architectures. Would that be a reason to not have shorts?

**Comment by CXCubeHD** [comment]
> For the record, using a smaller type is not necessarily more _efficient_.
> 
> Dart is an object based language where event integers are objects, and can be stored in a `List<Object>`. The optimization used to enable this somewhat efficiently is tagged "small integers", where some of the bits are used for the tag.
> If we have different _kinds_ of integers, we will need more tag bits. If compiled to a 32-bit architecture, that might be costly.
> 
> Also, while 8-bit and 32-bit operations can be as fast as 64-bit operations, and potentially smaller, 16-bit "shorts" are likely to be less efficient on modern x64 architectures. Would that be a reason to not have shorts?

I do not see this as a valid reason but rather as an excuse. A good example where you could use those types is if you want to make 100% percent sure that the number has a specific size. Doing that with if's is just stupid. And having an option is always better than having not an option. Also having unsigned types is a must, the same goes for the char type and byte type.

**Comment by vxern** [comment]
> Dart has a huge problems, and those are the missing types. I know that they aren't really missing, but they should be a default type, just like in C++ and C#.

Dart is not C or C++. Dart is Dart. Python is Python, JavaScript is JavaScript. The developers of these languages made conscious decisions as to what variable types there should and shouldn't be. Dart is not designed to be a sys-level language, it is not designed to combat C or C++ or even Rust, it is not designed to do low-level work. 

Adding two dozen other types to the language designed for `making the development process as comfortable and as fast as possible for developers`, ( which in my opinion it does really damn well ), is bound to create unnecessary clutter and tedious work. Let's not forget that Dart's focus right now is mainly Flutter, not penetrating hardware and editing singular bits.

> String, Object also should be a standard type, so they should start with a lowercase letter.

Why should they be a standard type if they can be objects? A string is a string of UTF-16 characters, an integer is a string of individual bits. A string *can* be an object, an integer *cannot*. This is also why there is no `Integer` object in C#.

> Doing that with normal ints and throwing exceptions when the number is negative just would be idiotic.

What happens if you try and pass in a negative integer into a uint? I'm very sure the SDK won't be happy. Whereas I'm also sure if you pass in a negative integer into an int, the SDK won't have anything against it, and your application will not be crashing.

> Also adding this would be easy, as a developer I think it would take a maximum amount of 20 hours to fully implement it while having it stable

Why exactly should I, along with thousands of other Dart programmers who have grown accustomed to the language, spend a maximum of 20 hours of my time adjusting my code to types *I do not need and never needed*?

> Object and String can have uppercase versions of them, just like in C#

C# abstracts several types away: `string` is an abstraction of `String`, `float` is an abstraction of `Single`, `double` is an abstraction of `Double` while `object` is an abstraction of `Object`. My question is: What is the point of doing the same for Dart when the uppercase, 'object' version of a string is entirely sufficient and does not cause any problems?

To conclude: Personally, I believe Dart's type system is entirely sufficient; it does its job very well, it doesn't cause any issues for me. Therefore, it is not an issue and should not be treated as such.

**Comment by lrhn** [comment]
> Also adding this would be easy, as a developer I think it would take a maximum amount of 20 hours to fully implement it while having it stable, and I am only counting that for a single developer, so if many people would do that then it would be even faster.

That'd be very impressive.

We'd spend more time than that just figuring out how to compile those types to JavaScript, whether they should implement `num`, or be subtypes of `int`, how they should be represented in memory when boxed, and, heck, just what to call them.

Should operations on these new integers be constant operations? (Because then the compiler's and the analyzer's constant evaluation logic needs to be updated too.) 
Can you add an `int16` to an `int32`? Can you add an `int64` to an `int32`? What are the result types?
Can you assign an `int16` to an `int32`? Would that be a coercion or a subtype relation? (Probably not subtype, but coercion would require language spec changes, so likely neither, you'd have to do `.toInt32()`. But then you can't assign `byteList[0]` to `int` any more, breaking backwards compatibility! Because `Uint8List.operator[]` would surely return `byte`.)
Should we have 32-bit `float`s too? How are you going to compile *those* to JavaScript?

The design alone would take weeks of discussion. Nothing here is a given, it's all *choices*, and for language design, it's better to get it right the first time, because it's nigh impossible to change things when they are already being used. That means thinking about all the options, how they interact with the existing type system and libraries, etc.

Should we have literals of different types? Something like `15u8` or `15b` being 15 as a `uint8`/`byte`?  That'll require parser changes.
Or will we use the context to convert plain integer literals to their expected type, like we do for doubles? That'll require more logic in the type inference step.

Then there is testing, more testing, documentation, maybe a blog post telling people about the new types.
Should the style guide be telling you when to use each kind of integer? (We'd at least have to discuss that).

I recommend getting acquainted with how the VM represents integers, and how dart2js/dev-compiler represents Dart integers and doubles. It's not even remotely trivial.
Maybe 20 weeks, if we really wanted it, and *not* for a single person. 😁

**Comment by tatumizer** [comment]
Over a weekend, I started experimenting with a new (for me) programming language called **zig**. My first etude was a [smashing success](https://github.com/dart-lang/sdk/issues/45153#issuecomment-798929436)! I put together a daring plan: automatically generate a boilerplate for dart to be able to call zig functions via ffi with no effort. I ran into some obstacles (or rather the obstacles ran into me), and now I'm in the process of negotiations with the zig team as to what went wrong. Will keep you posted.

The point is that for low-level programming, you need a language designed for low-level programming. Stuffing everything and kitchen sink into one language looks neither desirable nor realistic. Zig is a fast and SAFE language, dart+zig could be a match made in heaven. Zig compiles and cross-compiles for every imaginable platform, including WebAssembly. 
And the language itself is a charm: it has weird syntax many on this mailing list would welcome (based on some earlier requests).
What not to like here? :grin:

**Comment by EmreSURK** [comment]
I strongly disagree with that suggestion. 
Variable types are lean and clean at that time. Adding more and more stuff is not better always. There is no use-case for suggested types, and "every language has them" is not a valid reason. 

I believe you are searching for your needs in the wrong place. If you thinking variable sizes is important and that affects the performance of your programs, then you give up using object-oriented languages. 

That is how object-oriented programming works, everything is an object. 

Best.

**Comment by CXCubeHD** [comment]
> I strongly disagree with that suggestion. 
> Variable types are lean and clean at that time. Adding more and more stuff is not better always. There is no use-case for suggested types, and "every language has them" is not a valid reason. 
> 
> I believe you are searching for your needs in the wrong place. If you thinking variable sizes is important and that affects the performance of your programs, then you give up using object-oriented languages. 
> 
> That is how object-oriented programming works, everything is an object. 
> 
> Best. 
> 
> 

I halfly agree to you, but these types really must be standard types because that not only would allow people to interact with native code but also it would improve other stuff. Let's say for example that you want to store 255 keystates, it would me 4 times more efficient to store them in a byte array rather than in a int array. Also I don't think that an int can replace a char very well. This is because ints have int extension methods that aren't useful for text. And casting every time to a string would also be stupid. Also with those types you can garantee  certain type properties like in null safety. If you only want to have unsigned numbers then you are ALWAYS garanteed to have an unsigned type when using unsigned intergers. Also as the documentation says BigInts are a standard libary class and aren't optimized that well as normal ints. Also having types like floats could allow better communication between dart and native cpu code. I generally don't like your approach at killing must have features that could make the language very good 👎

**Comment by CXCubeHD** [comment]
@lrhn This can be answered easily. Just make it like in other languages like in C#. Generally the bigger types can cast to lower types easily:

byte -> short -> int -> long ...

Types that have are larger can have data loss. The compiler should warn the developer that this might could result a dataloss.

byte <- short <- int <- long ...

The same goes for casting signed to unsigned types or the other way around. Just take the approach from C#, because theirs is pretty good. 

And I do not think that your argument is good. Languages can do that easily without ANY problems and you are complaining like a little child. At least we developers want to have an OPTION for that. I do NOT like your approach at killing fundemental language features that would make working with native code much easier. 👎

**Comment by CXCubeHD** [comment]
> > Dart has a huge problems, and those are the missing types. I know that they aren't really missing, but they should be a default type, just like in C++ and C#.
> 
> Dart is not C or C++. Dart is Dart. Python is Python, JavaScript is JavaScript. The developers of these languages made conscious decisions as to what variable types there should and shouldn't be. Dart is not designed to be a sys-level language, it is not designed to combat C or C++ or even Rust, it is not designed to do low-level work. 
> 
> Adding two dozen other types to the language designed for `making the development process as comfortable and as fast as possible for developers`, ( which in my opinion it does really damn well ), is bound to create unnecessary clutter and tedious work. Let's not forget that Dart's focus right now is mainly Flutter, not penetrating hardware and editing singular bits.
> 
> > String, Object also should be a standard type, so they should start with a lowercase letter.
> 
> Why should they be a standard type if they can be objects? A string is a string of UTF-16 characters, an integer is a string of individual bits. A string *can* be an object, an integer *cannot*. This is also why there is no `Integer` object in C#.
> 
> > Doing that with normal ints and throwing exceptions when the number is negative just would be idiotic.
> 
> What happens if you try and pass in a negative integer into a uint? I'm very sure the SDK won't be happy. Whereas I'm also sure if you pass in a negative integer into an int, the SDK won't have anything against it, and your application will not be crashing.
> 
> > Also adding this would be easy, as a developer I think it would take a maximum amount of 20 hours to fully implement it while having it stable
> 
> Why exactly should I, along with thousands of other Dart programmers who have grown accustomed to the language, spend a maximum of 20 hours of my time adjusting my code to types *I do not need and never needed*?
> 
> > Object and String can have uppercase versions of them, just like in C#
> 
> C# abstracts several types away: `string` is an abstraction of `String`, `float` is an abstraction of `Single`, `double` is an abstraction of `Double` while `object` is an abstraction of `Object`. My question is: What is the point of doing the same for Dart when the uppercase, 'object' version of a string is entirely sufficient and does not cause any problems?
> 
> To conclude: Personally, I believe Dart's type system is entirely sufficient; it does its job very well, it doesn't cause any issues for me. Therefore, it is not an issue and should not be treated as such.

This argument is also bad because most of the default C# standard types are SEALED STRUCTS. They almost have the same properties like Objects they just are in place instead of being allocated everytime. Also as I mentioned before converting these types is really easy and is not a problem at all. I think because of people like you that have the same bad approach the language will habe it's big issues. Also having an OPTION is ALWAYS better then being stuck. This would allow to have better compatibility with native code. And that would be really good because as for now you can't really do more advanced stuff. People like you just kill a language that has so much potential. Also as a tip: Look what other languages handle stuff before saying that that won't work very well. I am a C# developer and I NEVER had problems like this before and I think this argumentation is really dumb.

**Comment by tatumizer** [comment]
@CXCubeHD: I can relate to your frustrations, but not to the form of their expression :-)

I'd like to point out that you slightly misunderstand the problem. Types like `byte`, `short` `unsinged long long` and friends are virtually useless by themselves. To take advantage of these types, you have to be able to form aggregates (arrays, structs) that include elements of these types. As soon as you have a struct, you also have an array of structs, structs containing arrays of structs and so on. And struct has better be a value type. And with value types, come pointers. And with the pointers, comes the unsafe mode. So as soon as you say: I need "byte" type, you also say you need all of those, and the Sun, and The Moon, and the stars... And C# really has it all (including the Sun and the Moon). 

A reasonable compromise would be to introduce a variant of the language specifically designed for low-level programming - call it dart-mini, or dartino, or something, which has these types, and where nothing is an object. In principle, this mini-language can interoperate over ffi with C hassle-free. And dart can interoperate with dartino seamlessly (with certain restrictions). This is a more realistic scenario, but right now I'm not sure there are enough use cases to justify the endeavor.

**Comment by CXCubeHD** [comment]
@tatumizer Thank you for the nice and polite comment. I don't really expect it coming now, but I really do wish that in future releases. But it also isn't that hard to implement. Basically you take the int, replace some stuff, replace assembly opcodes, add cast operators to other int types and that's it, it really isn't that hard. Also I was thinking of structures. Structures would be great because those could improve performance by 10x as shown in an comparison between classss and structures in C#. Structures are, as you said in place and are allocated on the stack with is much much faster. I could see this being implemented in Game / Renderengines. But I don't see this coming now and I don't really expect that because implementing that would cost much time and resources. That's why I wanted those native types that could improve comparability with native code and code itself. But I really DO think that we MUST have a char type. And implementing that would be even easier! Where you could use a byte for example is rgba color. If you want to make 100% sure that those numbers are in certain ranges without having to do that with if checks  would be great. I also do not expect pointers even though having them would be great. And another example for the ulong type would be if you try to make a program that manipulates memory of other programs. You need to store the address and because there aren't any unsigned 64 bit types you can not really do that well. This is the point where I think that I start thinking why? Why can't I make a number as high as 18446744073709551615 in dart? And using other ways would just show how dart just isn't really ready yet to use. I still can't understand the people that make big drama about things that all new developers from other languages expect. I see other dart features to be more "useless" than this. I am not saying that we shouldn't have those, but this has for me a much higher priority. I would wish that some guy of this dev team also had the same thoughts. I would rather say that this things are more important than extensions, because extensions just add a new way to do stuff that you could do before. But still nice to see that some people almost share the same thoughts.

**Comment by tatumizer** [comment]
> And another example for the ulong type would be if you try to make a program that manipulates memory of other programs. You need to store the address and because there aren't any unsigned 64 bit types you can not really do that well.

If it's somebody's address, you can store it in a signed 64-bit value, too: it's just an opaque value for you. Processor never knows whether a value is signed or unsigned: operations like +, -. |, & etc don't care about that (so you can even safely manipulate your addresses using addition/subtraction - result will be the same internally). Where the distinction between signed/unsigned really matters is in multiplication/division, but even if you want that, you can store only 64 bits of the result, which will still be the same).

Not sure whether you are familiar with typed_data: dart has Unit64List, Int64List and friends. Maybe for some of your use cases, those will do?

**Comment by CXCubeHD** [comment]
@tatumizer they might be some liberies that can add this, but I want it as a default language feature WITHOUT having to import liberies for that.

**Comment by leafpetersen** [comment]
> And I do not think that your argument is good. Languages can do that easily without ANY problems and you are complaining like a little child.

@CXCubeHD Please keep it civil and respectful here.  @lrhn is taking time to engage in good faith (and is probably the person most qualified to do so), and whether you agree with him or not, he deserves to be treated civilly.  If you are unwilling to do so, I will be deleting uncivil comments, and if necessary will ban you from this repository.  Please consider this a final warning.

I appreciate your detailed interest in the language, and your willingness to engage here, but I am *adamant* that discussion here will take place on mutually respectful terms.

**Comment by CXCubeHD** [comment]
@leafpetersen I want to apologize that it felt so disrespectful to you and other people, I of course didn't mean it like that, but I don't really think that those reasons where good.

**Comment by leafpetersen** [comment]
> @leafpetersen I want to apologize that it felt so disrespectful to you and other people,

Thank you.

> I of course didn't mean it like that, but I don't really think that those reasons where good.

I understand you may disagree.  Please do keep in mind though that @lrhn and others on here have been part of implementing and shipping many features in the Dart language (and in previous roles, other languages), and are keenly aware of the costs and tradeoffs involved. 

> I just find it very inconvenient to everytime write Uint8 u = 10 as Uint8; and I just want it to have as a standard language feature.

Understood.  We have this issue tracker, in part, as a way to take input and requests from our users, and we hear your request.  Please do understand though that we are a small team with a very large surface area to support, and with difficult tradeoffs to make.  We have a lot of users, and a lot of different constraints to satisfy.  Some of the things our users want (like this!) are hard to integrate with other things that other users want (like cross-platform!).  It is literally our full time job to think about these things.  That doesn't mean we have, or will, get everything right, but I would ask for a bit of benefit of the doubt - and I will insist, as I said above, on civility.

**Comment by konsultaner** [comment]
I think a very good reason for exanding the type system is this issue of mine: https://github.com/dart-lang/sdk/issues/45153#issuecomment-798929436

I think 99% of the times the current type system will do. But in some rare edge cases, it does indeed reduce performance. I don't know about the effort that needs to be done for expanding the type system, but making a language faster would be a good reason to put some time in it.

**Comment by lrhn** [comment]
Just because I've been thinking about this recently ...

A *minimal* implementation *could* be made "library only". 
No language changes, no new classes implementing `num`.
I'd put such classes, like `Uint16` and `Int32` into `dart:typed_data`. They'd effectively be immutable single-element typed-data lists.
Likely no subtyping between the types (an `Int32` is not an `Int64`),
You can have conversions to any other of those types (so they all have a `toUint16()` method).
Operators only work with the same type (so `Uint32 operator+(Uint32 other)` on `Uint32`).

The types would be sealed. We may want to fiddle with identity, like we do with `num` types, so we can safely unbox and rebox without it showing.

That would require no language design. It would allow platforms to optimize, but it *can* be implemented entirely in potentially inefficient library code (worst case, each `Float32` contains a `Float32List(1)` to store its value.)

It could potentially replace the `Uint64` from `package:fixnum` with something that's available everywhere, but we can't necessarily promise an efficient implementation, so it shouldn't be something you do for *performance*. Do it to ensure 
a specific numerical behavior instead.

**Comment by tatumizer** [comment]
Have you considered integrating dart with some simple high-performance language, e.g. lua?
Here's what they say:
"It is also easy to extend programs written in other languages with Lua. Lua has been used to extend programs written not only in C and C++, but also in Java, C#, Smalltalk, Fortran, Ada, Erlang, and even in other scripting languages, such as Perl and Ruby.".

**Comment by mraleph** [comment]
> The types would be sealed. We may want to fiddle with identity, like we do with num types, so we can safely unbox and rebox without it showing.

This requires some language design - I requested this capability before, e.g. I want a way to annotate a class which would allow compiler to forgo its identity (either by making identity unpredictable or defining identity in terms of deep identity of elements).

**Comment by konsultaner** [comment]
@CXCubeHD Why did you close it?

**Comment by konsultaner** [comment]
@CXCubeHD ok, please link the new issue. I would like to follow it!

**Comment by CXCubeHD** [comment]
#2100

**Comment by Levi-Lesches** [comment]
In the future, you might want to just edit the top comment (as long as you're not substantially changing the essence of the proposal). That way, the history and conversation of this issue isn't lost.

**Comment by annasajkh** [comment]
> I strongly disagree with that suggestion. Variable types are lean and clean at that time. Adding more and more stuff is not better always. There is no use-case for suggested types, and "every language has them" is not a valid reason.
> 
> I believe you are searching for your needs in the wrong place. If you thinking variable sizes is important and that affects the performance of your programs, then you give up using object-oriented languages.
> 
> That is how object-oriented programming works, everything is an object.
> 
> Best.

imagine every single pixel on an image editing app is an object
how laggy would that be? especially on mobile
this is why every serious image editing, video editing, etc is still written in c++
