### ISSUE TITLE
Ternaries with nullable class members trigger [dart: invalid_assignment] whereas local variables don't

### ISSUE THREAD

**Issue by btalb** [dart-lang/language#1521]
When using null-safety, I keep ending up in weird patterns that would easily be solved in other languages.

I think I've narrowed it down to this difference in handling between a local `int?` and `int?` as a class member:
```dart
class MyClass {
  final int? value;

  MyClass(this.value);
}

main() {
  final c = MyClass(5);
  final int? localInt = 5;
  final int i1 = (localInt == null) ? 0 : localInt;
  final int i2 = (c.value == null) ? 0 : c.value;
}
```

Our first int `i1` doesn't produce an error as expected, but the second int `i2` does:
```
main.dart:9:45: Error: Operator '+' cannot be called on 'int?' because it is potentially null.
```

I know there is the `??` operator, and both those lines can be replaced by `final int i = myNullableInt ?? 0`. But the discrepancy leads to weird issues if I want to do more complicated logic. For example, say I want `null` to be given the value of 0 and all other values to be given the value `value + 1`:
```dart
final i = (c.value == null) ? 0 : c.value + 1;
```

There's no easy way to do this, and I end up having to make a local copy of the `int?` just to use it in these ways. Is this a bug? Or is there a subtle reasoning I'm missing?

**Comment by natebosch** [comment]
See https://dart.dev/null-safety/understanding-null-safety#working-with-nullable-fields for a detailed explanation.

The short answer is that type promotion, including promotion to non-null, happens for _variables_ like `localInt`, but not _fields_ like `c.value` because it is possible to override a field with a getter, than may return non-null in `c.value == null` but, then return null the second time it is called in `: c.value`.

There are a few proposals floating around to add some syntax to make this situation nicer, such as https://github.com/dart-lang/language/issues/1201

**Comment by btalb** [comment]
Thanks @natebosch . Behaviour makes perfect sense with that explanation, and it's good to see the pain points being thought about with the proposal for 'if-variables'.

Apologies about the duplicate.

**Comment by eernstg** [comment]
@btalb, you may be interested in the whole topic of [field-promotion](https://github.com/dart-lang/language/issues?q=is%3Aissue+is%3Aopen+label%3Afield-promotion).
