### ISSUE TITLE
The argument type 'String' can't be assigned to the parameter type 'Uri'

### ISSUE THREAD

**Issue by MatthwFrost** [dart-lang/language#1530]
When i try use http.get i receive a this type of bug, 
```
The argument type 'String' can't be assigned to the parameter type 'Uri'.
```
I've tried to look for fixes but haven't come across one. I'm not sure whether is a bug with dart or my laptop because i know there are a few bugs for M1 silicon chips. I am also new to the language.

Here is the code that raises the error, I've tried different way but haven't found a fix.
```
import 'package:http/http.dart' as http;

class API_manager {
  void getNews() {
    var client = http.Client();

    client.get('http://newsapi.org/v2/everything?domains=wsj.com&apiKey=API_KEY');
  }
}
```

**Comment by mateusfccp** [comment]
You have first to parse your URL `String` into an `Uri` object. You can do it with `Uri.parse`. The resulting object may be passed to the `get` method.

---

Please, if you have any question refer to the documentation or ask it in StackOverflow or other communities (like Discord etc). This repository is dedicated to discussions about the language itself instead of general Dart support.

**Comment by MatthwFrost** [comment]
I apologise, have a good day!
