### ISSUE TITLE
Different analyzer result between spred operator and list.addAll()

### ISSUE THREAD

**Issue by giorgiofran** [dart-lang/language#1550]
Dart 2.12.2
I have a simple list like the following: 
```dart
 var t1 = <Object?>['foo'];
```

On both the following cases the analyzer complains that the list t1 cannot be assigned to the t2 or t3 ones.
```dart
 var t2 = <String?>[...t1];
 var t3 = <String>[]..addAll(t1);
```
If I define the list like follows:
```dart
var t1 = <dynamic>['foo'];
```
the analyzer complains only on the `addAll()` method.

**Comment by eernstg** [comment]
Assume you have a `t1` of type `List<dynamic>`.

For `t2`, the inferred element type of the spread element `...t1` is `dynamic`, and this is allowed in list literal with element type `String?` (or any other type), because `dynamic` is assignable to any other type. For `addAll`, we have a normal method invocation, and the requirement is that the actual argument type is assignable to the statically known formal parameter type; the former is `List<dynamic>` and the latter is `List<String>`, so that's an error.

It may seem inconsistent, but you could say that the elements of a list literal must be assignable to the element type of the list literal one by one (so an element type of `dynamic` is OK, even in the case where it's several elements coming from a spread element).

**Comment by mateusfccp** [comment]
This is not a bug in the static analysis or anything. You are explicitly determining that `t1` is of type `List<Object?>`. This means that `t1` can receive virtually any value (as, as far as I know, `Object?` is the top type). This also means that `List<String?>` cannot receive `t1`, as there's no static guarantee that all elements in `t1` are going to be `String?` or a subtype of `String?`.

If you want the static analysis to be able to infer the type for you, you may simply remove the explicit type.

```dart
final t1 = ['foo'];
final t2 = <String?>[...t1];
final t3 = <String>[]..addAll(t1);
```

**Comment by eernstg** [comment]
@giorgiofran, thanks for the input, don't hesitate to create more issues if you encounter things that look wrong! This issue can be closed, however, because the code is working as intended.
