### ISSUE TITLE
Nullable types are not assinable to a variable.

### ISSUE THREAD

**Issue by Reductions** [dart-lang/language#1553]
At the moment this is not posible:

```dart
void main() {
  Type t = int?; // I also tried to do: Type t = (int?);
  print(t);
}
```

Here is the error I get:

```
test_dart.dart:2:16: Error: Expected an identifier, but got ';'.
Try inserting an identifier before ';'.
  Type t = int?;
               ^
test_dart.dart:2:16: Error: Expected ':' before this.
  Type t = int?;
               ^
test_dart.dart:2:12: Error: A value of type 'Type' can't be assigned to a variable of type 'bool'.
 - 'Type' is from 'dart:core'.
  Type t = int?;
           ^
```

**Comment by eernstg** [comment]
Use this:

```dart
Type typeOf<X>() => X;

void main() {
  Type t = typeOf<int?>();
  print(t);
}
```

**Comment by Levi-Lesches** [comment]
Would the new `typedef`s help with this?

```dart
typedef MaybeInt = int?

void main() {
  Type t = MaybeInt;
  print(t);
}
```

**Comment by Reductions** [comment]
@Levi-Lesches You can not typedef anything but functional types.

**Comment by Levi-Lesches** [comment]
That's being changed in #65, and hopefully releasing soon. Hopefully that should fix this pattern.

**Comment by eernstg** [comment]
It is indeed possible to use the new and more general kind of type alias (currently needing `--enable-experiment=nonfunction-type-aliases`, soon to be enabled by default):

```dart
typedef MaybeInt = int?;
```

However, I'd still recommend using something like [`typeOf<int?>()`](https://github.com/dart-lang/language/issues/1553#issuecomment-809261322) when possible, because the type alias adds `MaybeInt` to the global namespace, and that would typically not be helpful.

**Comment by Reductions** [comment]
Glad to hear that typedef of nonfunctional types is coming to dart. @eernstg

**Comment by eernstg** [comment]
Thanks, @Reductions!

I'll close this issue: It may be seen as a proposal to allow `T?` as an expression when `T` is a type, but that's already on the agenda in https://github.com/dart-lang/language/issues/123#issuecomment-724072932, hence the 'state-duplicate' label.
