### ISSUE TITLE
Constructor tear off proposal needs to account for default values

### ISSUE THREAD

**Issue by leafpetersen** [dart-lang/language#1584]
The constructor [tear off proposal](https://github.com/dart-lang/language/blob/master/working/0216%20-%20constructor%20tearoffs/proposal.md) describes the semantics of tear offs in terms of an eta-expanded function which forwards the parameters to the constructor.  I don't think this is quite accurate because of default values, and this should be called out.

**Comment by lrhn** [comment]
It does say that *params* has the "same optional/required parameters with the same names, types and default values, ..." as the constructor. I'll see if I can emphasize this (since it's a tricky point). Preferably without going into as much details as we did for specifying constructor forwarders in mixin applications, even though that will likely be the end product when this feature becomes formally specified.
