### ISSUE TITLE
non-trivial noSuchMethod dynamic error example might be incorrect

### ISSUE THREAD

**Issue by moneer-muntazah** [dart-lang/language#1614]
Hi everyone,

I was reading through the spec. https://github.com/dart-lang/language/blob/master/specification/dartLangSpec.tex In line 2853 an example is given for a dynamic error during the invocation of `noSuchMethod`. In line 2860 `NoSuchMethod(covariant Null n) => n;` will not compile with null safety since `Null` is no longer the subtype of all types- the narrowing is not allowed.

**Comment by eernstg** [comment]
That's true, but the language specification does not yet include any of the rules that we have introduced as part of null safety (it's a "pre-null-safety" spec), so it's not a surprise that you can find examples that are pre-null-safety as well. Integrating the null safety rules and updating everything (including examples) as needed will be the next thing.

I'll close this, because the updates are planned, and the need to do it is known, and there are hundreds of locations where we will make adjustments so it won't be very helpful to start listing all of those in separate issues.
