### ISSUE TITLE
Question: Inferred types in null safety

### ISSUE THREAD

**Issue by moneer-muntazah** [dart-lang/language#1640]
Hi everyone, I'm not sure if this is the right place to ask questions, but I know it's the best place so I hope it's okay.

What is the difference between these two?

```dart
void main() {
  String y = x['value'];
}

const x = <String, dynamic>{
  'value': "ok"
};
```

```dart
void main() {
  String y = x['value'];
}

const x = {
  'value': "ok"
};
```

The second one does not compile. I thought maybe because the type is inferred as <String?, dynamic> but when add that as the type, the program runs. like so

```dart
void main() {
  String y = x['value'];
}

const x = <String?, dynamic>{
  'value': "ok"
};
```

The static analyzer states that a value of type `String?` cannot be assigned to a value of type `String` which I understand, but I'm wondering where the `String?` came from. Is it a return of `operator []` ? 
When I check the runtimeType I get `ConstantStringMap<String, String>` 

What's more puzzling to me is that this also won't compile

```dart
void main() {
  String y = x['value'];
}

const x = <String, String>{
  'value': "ok"
};
```

Stating the same message about wrong type even though I specified `<String, String>` Why does it have to be `<String, dynamic>`

Also whenever I add `dynamic?` I get a message that `?` is unnecessary because dynamic is nullable. 

But if that's the case shouldn't this be disallowed

```dart
void main() {
  String y = x['value'];
}

const x = <String, dynamic>{
  'value': "ok"
};
```

because `x['value']` can be null? 

Thank you sorry for the long post. I just really want to understand.

**Comment by lrhn** [comment]
The reason the first example works is that Dart allows you to assign something with static type `dynamic` to anything, with a run-time check.
For:
```dart
const x = <String, dynamic>{'value': "ok"};
void main() {
  String y = x['value'];
}
```
the `Map<K,V>.[]` operator has a return type of `V?`, and `dynamic?` is just `dynamic` (because `dynamic` already allows `null` as a value, as the compiler tells you if you try to write `dynamic?` directly), so you get an implicit downcast from `dynamic` to `String`, as if you had written `String y = x['value'] as String;`.

In the second example, `x` has type `Map<String, String>`. That means that `x['value']` has type `String?` which is not assignable to string due to null safety. You need to write `String y = x['value']!;` or `... as String`, or even `... ?? "defaultValue";`, to convince the compiler that it's never assigning `null` to `y`.

That goes for all the other examples too, if the *value* type of the map is `dynamic`, it compiles, otherwise it doesn't because the `[]` return type is nullable and `y` is not.
