### ISSUE TITLE
What is the cost of the bang (!) operator?

### ISSUE THREAD

**Issue by ramsestom** [dart-lang/language#1641]
I am currently converting a large Flutter app to null-safety and I have a lot of complex objects with nullable properties (and that have to remain nullable).
So I often have to bang cast these properties with the `!` operator but I am wondering, what is the cost of this bang operator in term of computational time at runtime?
The documentation on null-safety says that:

> Of course, like any cast, using ! comes with a loss of static safety. The cast must be checked at runtime to preserve soundness and it may fail and throw an exception. But you have control over where these casts are inserted, and you can always see them by looking through your code.

So what is really going under the hood when we bang a nullable variable? Is a non-nullable copy of this variable created at runtime? If so, in terms of performances, does it cost less to declare a locale copy of the variable in my code and to work with it rather than having to bang a nullable property possibly multiple times in the body of a function?
For example supose that I have:

```dart
class MyClass1 {
    MyClass2? prop;
}
```

What coding pattern would be the more efficient in term of performances:

```dart
MyClass1 c1 = new MyClass1();
if (c1.prop != null) {
   //even if I, as the developper, knows that the getter of prop would always return the same prop object so I can safely bang 
   //prop after testing it wasn't null, the compiler don't know that worcing me to bang c1.prop each time
   c1.prop!.someMyClass2Function();
   c1.prop!.someMyClass2OtherFunction();
}
```

or

```dart
MyClass1 c1 = new MyClass1();
if (c1.prop != null) {
   MyClass2 localnonnullc2 = c1.prop!;
   //I declared a local non-nullable copy of c1.propso that the compiler wouldn't requiere me to bang c1.prop in my if() body 
   localnonnullc2.someMyClass2Function();
   localnonnullc2.someMyClass2OtherFunction();
}
```

or

```dart
MyClass1 c1 = new MyClass1();
MyClass2? localc2 = c1.prop;
if (localc2  != null) {
   //localc2 beeing a local variable, the compiler knows for sure that localc2 would remain non null in my if() 
   localc2.someMyClass2Function();
   localc2.someMyClass2OtherFunction();
}
```
?

**Comment by ykmnkmi** [comment]
If you look at the JS compilation result, then "!" checks are omitted on the web, but "late" is checked every time a field is accessed.

**Comment by lrhn** [comment]
I wouldn't worry *too much* about `!` operators. They were always there anyway, if you did `foo.method()` before and `foo!.method()` now, the code always had to check that `foo` wasn't `null` before calling. It's just being explicit about it now.

If you make a lot of `!` checks, and can reduce that by moving the value into a local variable and checking once, I'd see that as a *saving* compared to pre-null-safety code.

Still, any operation you don't make is both safer and faster than the one you make. I personally prefer moving values into local variables and checking them there. I feel like I have more control that way, and it makes it obvious, both to the compiler and the reader, that the value won't change between uses. I very rarely use `!` in production code, and only when I know (somehow) that it will definitely succeed, otherwise I'd do a check and branch instead.  (I am less risk-averse about throw-away scripts.)

Also remember to use cascades if you need to call multiple methods on the same value, `c1.prop!..foo()..bar()` works, as does `c1.prop?..foo()..bar()`, which allows you to write the entire `if` block in one statement. For more complicated uses, the local variable is probably better.

**Comment by cedvdb** [comment]
>  I very rarely use `!` in production code, and only when I know (somehow) that it will definitely succeed, otherwise I'd do a check and branch instead. (I am less risk-averse about throw-away scripts.)

I often have to use ! for state that needs initialization. I'm curious how do you deal with that ? for example:

```
class DataState<T extends Entity> {
  final bool loading;
  final bool exists;
  final T? data;
}
```

Here data is nullable, and when it exists it not null, yet you still have to use !.

Another example, where a library needs to be initialized, returning a future for each property would be impractical:

```
abstract class MyAppInfo {
  static PackageInfo? _packageInfo;
  static const String title = 'Sent';
  static String get appName => _packageInfo!.appName;
  static String get packageName => _packageInfo!.packageName;
  static String get version => _packageInfo!.version;
  static String get buildNumber => _packageInfo!.buildNumber;

  static Future init() async {
    _packageInfo = await PackageInfo.fromPlatform();
  }
}
```

**Comment by tatumizer** [comment]
If I understand your use case correctly, `static late final PackageInfo _packageInfo;` may help :-)

**Comment by lrhn** [comment]
I would probably avoid that pattern entirely. It's inherently unsafe and depends on someone calling (and waiting for) `init` before the other getters can be used. (Also, static-only classes are discouraged by the style guide).

You can use `late`, but using `late` is like using `dynamic` - great when it really is solving a dynamic problem, but bad when used as a crutch to hide unsafe code from the compiler.

I'd do something like:
```dart
abstract class MyAppInfo {
  static MyAppInfo? _info;
  static Future<MyAppInfo>? _initFuture;

  final PackageInfo _packageInfo;
  MyAppInfo._(this._packageInfo);
  
  static MyAppInfo? get info => _info;

  static Future<MyAppInfo> init() async {
    var intiFuture = _initFuture;
    if (initFuture != null) return initFuture;
    return _initFuture = PackageInfo.fromPlatform().then((info) => _info = MyAppInfo(info));
  }

  String get appName => _packageInfo.appName;
  String get packageName => _packageInfo.packageName;
  String get version => _packageInfo.version;
  String get buildNumber => _packageInfo.buildNumber;
}
```
This will allow you to `await MyAppInfo.init()` and get the `MyAppInfo` from that, then store it whereever you want.
Or call `init()` and then later check `MyAppInfo.info` and see if it's non-null.

Simply assuming that it's going to be non-null, because it's not called until `init` has completed, is not something I'd design for.

**Comment by cedvdb** [comment]
Thanks. I believe something has to be said about practicality and balance between runtime errors and compile time.

 - Using late instead of ! in my case would resolve in the same scenario where if the value was not initialized the error would happen at runtime. So using late is not a fix here.
 
 - Using a future "static constructor" (whatever is the name for this pattern) can work, and it will in my case. However there are various scenarios I can think of where having this compile time check furnish a worst API than the runtime check (eg: You want to display the build version on every page,  so you use the static init at the start of the application, then you have to find a way to make that instance accessible, maybe by injection, you can't use a global var here ). Therefor I think it can be fine if the error happens at runtime and is just part of the documentation, if that's more practical. Custom errors can be thrown to make it clearer. 


For the `DataState` I could create subclasses,  `DataStateLoading`, `DataStateExist` and `DataStateNotExist` to force compile time check
