### ISSUE TITLE
[specification] Decide on treatment of cyclic dependencies during inference

### ISSUE THREAD

**Issue by eernstg** [dart-lang/language#1650]
Cf. https://github.com/dart-lang/co19/issues/1078#issuecomment-822866466:

```dart
int f(func) => 0;

class C {
  static var sVar = f(() => sVar);
}

void main() {
  String s = C.sVar;
  C.sVar.arglebargle;
}
```

Given that the return type of `f` is `int`, type inference could infer the declared type of `sVar` as `int`, but it could also report a compile-time error based on the fact that the initializing expression `f(() => sVar)` refers to `sVar` itself, that is, based on the cyclic dependency (even though it doesn't actually matter in this case).

Currently (as of commit 1d38c98b696687798604db64fd6a128b1967962c), the analyzer accepts the program and the CFE rejects it

```
n021.dart:8:16: Error: A value of type 'int' can't be assigned to a variable of type 'String'.
  String s = C.sVar;
               ^
n021.dart:9:10: Error: The getter 'arglebargle' isn't defined for the class 'int'.
Try correcting the name to the name of an existing getter, or defining a getter or field named 'arglebargle'.
  C.sVar.arglebargle;
         ^^^^^^^^^^^
```

Based on [section 'Top-level inference procedure'](https://github.com/dart-lang/language/blob/master/resources/type-system/inference.md#top-level-inference-procedure), I believe that the analyzer should encounter the error that `sVar` isn't available when local inference is performed on `f(() => sVar)`, but we do not get any compile-time errors (perhaps `sVar` gets the inferred type `dynamic`).

Similarly, the CFE should report the same error, but it does actually infer `sVar` to have type `int` and proceeds to report the errors where `sVar` is used in a way that conflicts with this typing.

So we have discrepancies in the implementations, and we might wish to take the opportunity to adjust the specified behavior in the specification, if that enables a less breaking change to the tools and an overall sound language design.

**Comment by Levi-Lesches** [comment]
Doesn't this fit in well with how functions are "lazy"? The closest analogy would be `late`, which also exhibits the same behavior here:  

```dart
late int temp = temp;

void main() {
  print("Hello");  // okay, Dart hasn't caught on yet
  print(temp);  // Uncaught RangeError: Maximum call stack size exceeded
                //   Error: RangeError: Maximum call stack size exceeded
  // BTW Dart gives both of these errors (and on the same line too!) which looks confusing
}
```

I have a feeling that if we allow Dart to inspect functions before they're ran for their _values_ (not just the types), then we can run into incorrect behavior when the value of a field changes before the function is actually executed (especially late/nullable values).

**Comment by eernstg** [comment]
We're actually never evaluating function invocations at compile-time (except for a special case where "the language knows" how it is implemented: `String.length`), so we can't rely on rules that need to consider the value returned by an invocation. However, we _can_ have a situation where the type of an invocation depends on the actual arguments, and that's the reason why we can't just ignore cyclic dependencies via function invocations:

```dart
X id<X>(X x) => x;
int intId(int i) => i;

void main() {
  var y = id(y); // Error: We use the type of `y` to choose `X` in order to type `id(y)`.
  var z = intId(z); // Error?
}
```

In the case of `intId` we _could_ say that the type of `intId(...)` is `int` no matter which arguments we're passing to it, and then we could determine that `z` has type `int`, and then the invocation of `intId(z)` is type correct. But we could also say that the inference of the type of `z` fails because the initializing expression `intId(z)` depends on `z`.

This issue is concerned with that decision: The second approach is safe and simple, but may cause errors for programs that we could have accepted. The first approach may give rise to tractability issues, e.g., because it might require fixed point iterations during inference.

**Comment by Levi-Lesches** [comment]
Well, currently, both are errors, so those cases are already handled. Are you saying that `intId(z)` maybe shouldn't be an error? 

Another example of this is the getter pattern: When converting a field to private field + getter/setter, if you forget to mark the getter with an underscore, you get a runtime error. While technically, a getter is really a function and thus this is a matter of infinite recursion instead of a cyclic declaration, the convention of using getters was enough to make this stand out to me. 

```dart
class A {
  int b = 0;
  
  bool _c = true;
  bool get c => c;  // TYPO: should be _c
  set c(bool value) => _c = value;
}

void main() {
  A obj = A();
  print(obj.b);  // 0
  print(obj.c);  // Uncaught RangeError: Maximum call stack size exceeded
                 //   Error: RangeError: Maximum call stack size exceeded
}
``` 

While I do see the cases where cyclic declarations can cause issues when not caught by the compiler/analyzer, in my experience Dart seems to be smart enough to catch nearly all instances, and in the few where it doesn't, a Stack Overflow error is enough to indicate that something's wrong (especially when line numbers are included in the traceback).

**Comment by eernstg** [comment]
> Well, currently, both are errors

Note that the example in the initial comment of this issue is accepted by the analyzer and rejected by the CFE. This issue is concerned with clarifying the situation with the implementations and the spec, such that we have a language design that we're happy about, and which is implementable.

And, yes, `var z = intId(z);` ..

>  maybe shouldn't be an error

**Comment by stereotype441** [comment]
I did some research (and had some conversations with @scheglov) about what is currently implemented in the analyzer and CFE.  Here's the current situation:

- The CFE currently implements a recursive algorithm for type inference of implicitly typed fields and top level variables: for each implicitly typed field or variable, it attempts to infer a type for it by performing type analysis of its initializer expression*.  If, in doing so, it encounters a reference to another implicitly typed field or variable, then it pauses type analysis of the former field/variable, and by making a recursive function call, starts inferring a type for the latter field/variable.  Once that completes, it uses the inferred type to resume type analysis of the former field/variable.  This recursion can happen to arbitrary nesting depth, but it can't lead to infinite recursion because if a field or variable is encountered whose type analysis is currently paused, that is reported as a cyclic dependency error.  To reduce how often users run into cyclic dependency errors, the type analysis of the initializer skips over subexpressions that, for various reasons, couldn't possibly influence the type of the full initializer expression (for example, in `var x = f(y);`, provided that `f` is a non-generic function, then the type of `x` is inferred without needing to visit `y`, and that means that the initializer for `y` can refer to `x` without causing a cyclic dependency error).  This approach is sound but it's complex, because the rules for which subexpressions are skipped are subtle and undocumented, and that means there's a danger of user confusion if the user makes a minor change to their code that causes a subexpression to stop being skipped, and that leads to a surprising cyclic dependency error.

- The analyzer currently implements a two-pass algorithm for type inference of implicitly typed fields and top level variables: first it locates all the implicitly typed fields and variables in a library cycle and constructs a dependency graph for them based on their references to one another.  (Unlike the CFE, it doesn't skip over any subexpressions when finding these dependencies).  Then, once the graph is constructed, it topologically sorts it, and assuming there are no cycles, infers the type of each field/variable after all of its dependencies are inferred.  This approach is nice and simple, but it's unsound, because the first pass can fail to notice dependencies on fields.  For example, in `var x = y.z;`, if `y` is an implicitly typed top level variable, and `z` is an implicitly typed instance field, the first pass will fail to see that the type of `x` depends on the type of `z` (because it hasn't worked out the type of `y` yet, and until it does that, it doesn't even know which class to look for `z` in).  That means that (a) the analyzer can fail to notice some cyclic dependency errors, and (b) the results of type inference can depend on the order in which the analyzer visits the various top level variables and fields.

(*Sometimes fields get their type inferred via inheritance rather than from an initializer expression; I'm ignoring that detail to simplify this description)

So, considering again the example from the top of the bug report:
```dart
int f(func) => 0;

class C {
  static var sVar = f(() => sVar);
}

void main() {
  String s = C.sVar;
  C.sVar.arglebargle;
}
```
The CFE tries to infer a type for `sVar` by performing type analysis of its initializer expression `f(() => sVar)`.  Since `f` is non-generic, it skips oves the subexpression `() => sVar`, so there's no circular dependency issue, and it infers a type of `int`; later, when analyzing `String s = C.sVar;` it reports an error, since `int` can't be assigned to `String`.  The analyzer, on the other hand, tries to draw a dependency graph for `sVar`, sees that it depends on itself, and reports a cyclic dependency error.  Then it does error recovery by assigning `sVar` a type of `dynamic`, so no further errors are reported.  (Note that this is different from what @eernstg described in the initial bug report; the analyzer behavior has changed since this issue was opened).

As I see it we have three possible directions to go from here:
1. Update the spec to match the CFE behavior, and change the analyzer behavior to match it.  This is totally possible, but I don't like it because of the complications of specifying exactly which subexpressions should be visited / not visited during inference.  There's also an implementation complication in that this would require the analyzer to type analyze initializer expressions twice (once to infer thet type and then again to analyze any subexpressions that were skipped); this is likely to lead to subtle bugs because the analyzer rewrites parts of the AST during type analysis.
2. Somehow tweak the analyzer behavior so that it's sound, and change the spec and CFE to match it.  I don't really like this option, partly because I'm not really sure what the best tweak would be, and partly because the current CFE algorithm was written as a response to user frustration with the analyzer behavior, so it seems like a step backward.
3. Update the spec to be similar to the CFE behavior, but simpler, and change the analyzer behavior to match it.  The simplification I have in mind is to eliminate the optimization that causes subexpressions to be skipped.  I've done an experimental test run through internal source code and found just a single line of code that would break, in a package that's not published externally; I think that's a small enough breakage to be worth the user annoyance.

So I'm currently favoring option 3.  Anyone else want to venture an opinion?

(Note that @scheglov has already filed https://github.com/dart-lang/sdk/issues/46579 to track the work necessary to implement recursive type inference in the analyzer; this would be a necessary part of either option 1 or 3).

**Comment by eernstg** [comment]
I think option 3 is a good way ahead:

If type inference fails for some variables (most likely: a very small set of variables), developers can declare the type. This failure is going to occur directly at the declaration of the variable, we don't rely on usages of the variable to trigger anything. So the breakage is not hard to detect, and not hard to handle.

I also think that a few extra declared types for these cyclic-dependency situations may be a step up in software quality: If the type is so hard to discern for an analyzer/compiler it is probably also hard for a human reader, so we may as well declare the type explicitly.

**Comment by eernstg** [comment]
@stereotype441 and @scheglov, the analyzer now reports a circularity error in the initial example of this issue. Did that option 3 [here](https://github.com/dart-lang/language/issues/1650#issuecomment-877370017) already get implemented?

If that is true then, presumably, we'd already have plenty of evidence that the change wasn't too breaking. The CFE behavior may still be slightly more user-friendly, but as soon as the developer provides the required declared type (such that the analyzer is happy), the analyzer should report the same errors that the CFE already reports by skipping the circularity.

The specification [already has](https://github.com/dart-lang/language/blob/master/resources/type-system/inference.md#top-level-inference-procedure) the following:

> If the inference process requires the type of an _unavailable_ variable in order to proceed, it is an error.

We may need to say that type inference on a term `e` (with some context type) will always 'require' the type of every identifier that occurs in `e`, but apart from that I believe that there's no need to change the spec.

In that case we could close this issue, and perhaps create an implementation issue on the CFE, requesting that the CFE uses the simpler approach where no subterms are skipped during the circularity check.

@leafpetersen, WDYT?

**Comment by johnniwinther** [comment]
I've created a [CL ](https://dart-review.googlesource.com/c/sdk/+/267061)that aligns the CFE top level inference with the analyzer. It was found that the underlying assumptions of the CFE approach doesn't match well with the horizontal inference and the change to report errors during top level inference.

**Comment by scheglov** [comment]
As I can see, [XXX](https://dart-review.googlesource.com/c/sdk/+/206421) (for the analyzer) is not landed yet.
So, this code does not report circularity errors for `a` and `c`.
```dart
class A {
  static final a = b.c;
  static final b = A();
  final c = a;
}
```

As I said in https://github.com/dart-lang/sdk/issues/46579, it is up to the language team to decide.
And I'm not sure I have seen the decision :-)
Correct me, if I'm wrong.

FWIW, I thought that the mentioned change is something what CFE does, and pulls types doing inference as necessary. I think it even was a simpler model.

**Comment by johnniwinther** [comment]
With the mentioned CFE CL that example above still results in a compile time error.

**Comment by eernstg** [comment]
@johnniwinther and I just discussed this issue. I think we need to decide on a particular approach and get it landed.

I'd recommend that the analysis uses the eager approach (where no subterms are skipped during the circularity check). You could say that this is an 'eager' approach, because it makes no attempt to prune the inference process anywhere, even in cases where it could be argued that the result is not needed in order to find the type which is being inferred right now.

This means that some programs will be rejected because of a circularity, in spite of the fact that a lazy analysis could actually complete the inference. The point is that such programs have subtle (and not very maintainable) dependencies, and it's presumably better for readers and maintainers of the code, if the types that would otherwise have been inferred are instead written explicitly.

This would be a breaking change, but as I understand the situation it is essentially non-breaking in practice. So we may or may not need to run a breaking change procedure.

@stereotype441, @leafpetersen, @lrhn, @munificent, @jakemac53, @kallentu, @natebosch, do you agree on the need to proceed with this decision, and do you agree on using the 'eager' approach mentioned above?

@scheglov, @johnniwinther, I know that there is a history of work done in this area already. Do you have any worries or further considerations about proceeding in this manner?

**Comment by johnniwinther** [comment]
The eager approach is the current state of the CFE as of https://dart-review.googlesource.com/c/sdk/+/267061. We have seen only two distinct internal errors from this - in both cases two subsequent fields that refer to each other in their initializers. The approach is preferable to the CFE - even compared with the old approach that skipped subterms.

**Comment by stereotype441** [comment]
I'm fine going ahead with the eager approach.  @johnniwinther did you go through the [breaking change process](https://github.com/dart-lang/sdk/blob/main/docs/process/breaking-changes.md) when you did https://dart-review.googlesource.com/c/sdk/+/267061?  (I don't see a change to the CHANGELOG in that CL so I'm guessing you didn't).  If not, we should probably go through the steps of that process ASAP, just so that customers get informed of the potential breakage.

**Comment by johnniwinther** [comment]
I didn't go through the process because I didn't realize that it was breaking - I thought the analyzer was doing the eager approach!

**Comment by eernstg** [comment]
@stereotype441, @leafpetersen, @lrhn, @munificent, @jakemac53, @kallentu, @natebosch, I created https://github.com/dart-lang/sdk/issues/50383 containing a breaking change request to do as described above.

If you have concerns about doing this then we can simply reject the request. Otherwise I think it would be helpful to get the process going.

**Comment by eernstg** [comment]
@stereotype441, @scheglov, I have not mentioned a need to change the analyzer in [the breaking change request](dart-lang/sdk#50383). However, I heard a few remarks implying that there could be a need to adjust the analyzer as well. WDYT?

**Comment by scheglov** [comment]
The current implementation in the analyzer is somewhat in the middle. It does not skip any parts of initializers while doing inference. But, as described in https://github.com/dart-lang/sdk/issues/46579, it misses some dependencies because of using `dynamic` for variables being inferred while gathering dependencies. So, yes, we need to make [changes](https://dart-review.googlesource.com/c/sdk/+/206421) to the analyzer.

**Comment by eernstg** [comment]
Has been implemented now (such that all cyclic dependencies are flagged as errors), cf. https://github.com/dart-lang/sdk/issues/50383.

**Comment by eernstg** [comment]
Closing a technical-debt issue: :tada:
