### ISSUE TITLE
"sealed" dependencies

### ISSUE THREAD

**Issue by giorgiofran** [dart-lang/language#1666]
I have a large project with a lot of dependencies. 
I'm facing a huge problem at present with the AngularDart update, but the problem is general and not limited to that.
The question is that if you have one of your dependencies with old references, you are in troubles.
If the project is small, you can fork it and try to update it, but if you have the dependency on a big project, that is difficult to do.
So, a suggestion that could not solve entirely the problem, but that could help in many cases.
I was thinking about a particular type of dependency (I called it "sealed" but it is obviously only a suggestion) that can be used in your code as a normal one, but that cannot be exported in any way. I mean no Object from this dependency can be used as public parameter or field.
Let's make an example: I have package A that uses package B and package C as dependency. Both B and C uses D  but in a different version. Today this means that I cannot even run pub update.
But, imagine that package B has declared D as "sealed". This means that it is using that package internally, and that does not expose any Object of it. This way, even package "A" is not aware that B is using D.
At this point, whichever is the version of D used by C gives no problems at all.

**Comment by Silentdoer** [comment]
This sounds like rust's dependency handling

**Comment by munificent** [comment]
What you're looking for is unshared dependencies. You're correct that Dart and pub do not support this. I wrote a little about them [here](https://dart.dev/tools/pub/versioning#unshared-libraries-the-npm-approach) in the initial pub docs.

Being able to have multiple different versions of the same package inside an application does help avoid version lock. However, there are a few downsides:

* If objects from one version of the package ever flow to a place that expects the other, they are not compatible. You will get *extremely* confusing error messages too like "Foo is not an instance of Foo". Static analysis ("cannot be exported in any way. I mean no Object from this dependency can be used as public parameter or field") is not enough to prevent this. Objects can always flow through upcasts and other places where the type checker loses track of it.

* It increases code size. For mostly server-side languages and frameworks like Node and Rust, that's not much of a problem. For a client-side application language like target, it's a major concern. App developers really don't five slightly-different version of the same package floating around in their app making it larger.

* It adds a lot of complexity to package management. When users depend on a package, they have to decide if that should be a shared or unshared dependency. If they guess wrong (for example make it unshared when objects from that dependency *do* leak out) they can end up breaking downstream consumers of their package. Our experience is that users overall don't want to spend a lot of mental effort reasoning around package management, so we try hard to keep the system as simple as we can.

Because of those, we've always made the trade-off that it's better to just not support unshared dependencies, even though it can make some upgrades painful.
