### ISSUE TITLE
Should we do bottom-up disambiguation of set/map literals with spreads?

### ISSUE THREAD

**Issue by munificent** [dart-lang/language#167]
This is syntactically ambiguous:

```dart
{...a}
```

It could be a map or set. Right now, the proposal follows the set literal proposal and says the context type can be used to disambiguate:

```dart
Set s = {...a}; // Set
Map m = {...}; // Map
```

It makes sense for the set literal proposal to only use the context type to disambiguate empty literals, because it's empty. What else could you use? But it seems weird for spreads:

```dart
var list = [1, 2, 3];
var set = {...list};
```

As it's proposed, this will generate a type error here. There is no context type, so the `{...list}` is inferred as a map literal. Then you get a type error trying to spread a list into a map literal.

This feels pretty bad to me. Should we also allow bottom-up inference if there isn't a context type? Would doing so cause any problems I'm not foreseeing? If not, I'm happy to update the proposal.

cc @lrhn @leafpetersen

**Comment by lrhn** [comment]
We knew the rules would have to be generalized for spreads/if/for elements.

For something that is syntactically indistinguishable, we should use types to determine the meaning. Then all following steps can use the static type of the expression to see what the choice was.

I would first use *context type* if available. 
If the basetype of the context type is a subtype of `Iterable<Object>` (and it's not also a map, as usual), then let `T` be the type of `Iterable` that it actually implements.
Then it's a set literal, all sub-parts are *elements* (not *entries*), and the context type of each element is `T`.

If not, it's a map literal and each sub-part is an *entry*. For map entries, we'll probably have to talk about "key context type" and "value context type" for the map entries. We'll need a new syntactic category for map entries, because we now have sub-entries in if/for constructs.


For a non-empty set-or-map literal and the context type is not available, I'd look at the type of the individual element-or-entry expressions, recursively, and give each of them a vote.

For `... p`, if `e` has a static type that is a subtype of `Iterable<Object>` and not a subtype of `Map<Object,Object>`, then it votes *set*.
Otherwise if `e` has a static type that is a subtype of `Map<Object, Object>`, then it votes *map*.
If neither, then it doesn't vote either way.

For `if (e1) p1`, analyze p1 and use its votes.
For `if (e1) p1 else p2` analyze p1 and p2 and use all their votes.
For `for (... in e1) p1`, analyze p1 and use its votes.
For `expression` vote *set*.
For `expression: expression` vote *map*.

If there is not at least one vote, or there are votes for both *set* and *map*, it's a compile-time error, otherwise pick the one that is voted for.


One thing to consider is whether to make `... {}` provide no vote. That would make
```dart
var s = {... {}, ...{1}};
```
successful and `{...{}}` fail. Which might be surprising since `{}` is normally a map.

**Comment by leafpetersen** [comment]
We decided to do this, specification for how it is done will be forthcoming shortly.
