### ISSUE TITLE
class Foo<T> {void test<T>(T t) {}} should be conflict by analyzer?

### ISSUE THREAD

**Issue by Silentdoer** [dart-lang/language#1670]
and why static method can not invoke by generic type like `Foo<int>.staticMethod()`?

`List.copyRange(arg);` is equals `List<dynamic>.copyRange(arg)`? because `List list`, list is `List<dynamic>` type

**Comment by srawlins** [comment]
@Silentdoer GitHub uses Markdown parsing for comments, and I believe your generic type annotations are being swallowed. You might want to edit your description and put all code in backticks (`) like

    `List<String>`

**Comment by Silentdoer** [comment]
> @Silentdoer GitHub uses Markdown parsing for comments, and I believe your generic type annotations are being swallowed. You might want to edit your description and put all code in backticks (`) like
> 
> ```
> `List<String>`
> ```

ok, thank you

**Comment by Silentdoer** [comment]
> > `class Foo<T> {void test<T>(T t) {}}` should be conflict by analyzer?
> 
> What conflict do you expect? Note that type variables can shadow each other. For example:
> 
> ```dart
> class C<T> {
>   // `T` below shadows `T` above; it is completely unrelated to `T` above.
>   T m<T>(T a) => a;
> }
> ```
> 
> > and why static method can not invoke by generic type like Foo.staticMethod()?
> 
> I imagine you want to write something like `Foo<String>.staticMethod()`. Is that correct? What would it mean to call a static method on a class, and simultaneously use a type argument? Can you provide an example of what you're trying to accomplish?

maybe `T m<T>(T a) => a;` should rename to other character?

**Comment by Silentdoer** [comment]
i just think List.copyFrom is ok, but `List<dynamic>.copyFrom` is error that not consistent with List a equals `List<dynamic> a`

**Comment by Silentdoer** [comment]
i close the issue, maybe it is not a problem need to dissus

**Comment by lrhn** [comment]
There is no plan to make shadowing type parameters an error in the language. If you want to protect yourself against doing it by accident, you can use the lint [`avoid_shadowing_type_parameters`](https://dart-lang.github.io/linter/lints/avoid_shadowing_type_parameters.html).

The current Dart type inference treats "raw types" (a *type* like `List`) as *specified*, and therefore not subject to inference. Since the type is generic, and there is no inference for it, it's instantiated to bounds, giving you `List<dynamic>`. 
One of the reasons for this choice is that that was the behavior in Dart 1, and it mad the Dart 2.0 migration easier to preserve the old behavior. There were also considerations about the inference algorithm needed to do something else.

You cannot invoke static methods on instantiated generic types because it *has no effect*. There was no reason to allow it, so the *syntax* doesn't allow you to write it.

You actually *can* invoke static methods on instantiated type aliases now:
```dart
typedef IntFoo = Foo<int>;
... IntList.staticMethodOnFoo(...) ...
```
It doesn't make any difference to the call, static methods cannot access type parameters of the class, only instance and constructors can (because the type parameters are treated as properties of *instances*, not the class declaration itself, and static methods are properties of the class *declaration*, the declaration being treated as a namespace).

So, it's not correct that `List.copyRange(...)` is equivalent to `List<dynamic>.copyRange(...)`. It really is treating the *`List` declaration* as a namespace, not as a *class*.

Allowing `List<int>.staticMethod` is confusing because it *really* would just mean the same thing as `List.staticMethod`. It's unnecessary and confusing, and therefore it's not allowed. There are no plans to allow it.
