### ISSUE TITLE
local variable int a; should be error?

### ISSUE THREAD

**Issue by Silentdoer** [dart-lang/language#1689]
void main (){
int a;  // no error
}

class Uu
{
int a;//error
}

**Comment by srawlins** [comment]
The first `a` is a local variable, as you note, and so is "implicitly late." It is allowed to be declared non-nullable _and_ be declared without an initializer as long as it is definitely assigned an `int` value before it is read (it never is read, in your case).

The second `a` is a field, and fields do not have such an "implicit late." You can explicitly mark the field `late`. Fields do not have "implicit late" because it is impossible to know whether a field is definitely assigned before it is read.

**Comment by leafpetersen** [comment]
> The first `a` is a local variable, as you note, and so is "implicitly late."

Just to be extra clear, this is entirely a static property, and not a runtime checked property the way that actual `late` variables are.  The static analysis guarantees that `a` is never used before it is initialized.   But yes, this is working as intended.  While this example may not seem useful, it is sometimes useful to have non-nullable variables which are not initialized on all paths (but are initialized before every use), e.g. where some control flow paths return early, or throw an error.

**Comment by Silentdoer** [comment]
>The first a is a local variable, as you note, and so is "implicitly late." 

but in following code:
```dart
int a;
await for(var m in receive) {
  a = m;
  break;
}
a = a + 1;  // will be error, but if use late int a; in above, thr code will be ok
```

**Comment by Levi-Lesches** [comment]
That's because it's possible for `receive` to be empty, and thus the for loop never runs. Because it _might_ be uninitalized, Dart stays safe and doesn't assume it will be. 

Explicitly marking it `late` is like telling the compiler "yes, I know it's possible this won't work, but trust me it will for my use case". Using late will only get rid of the compile-time error -- if `receive` really is empty, you'll get a runtime error that `a` isn't assigned.

**Comment by Silentdoer** [comment]
> That's because it's possible for `receive` to be empty, and thus the for loop never runs. Because it _might_ be uninitalized, Dart stays safe and doesn't assume it will be.
> 
> Explicitly marking it `late` is like telling the compiler "yes, I know it's possible this won't work, but trust me it will for my use case". Using late will only get rid of the compile-time error -- if `receive` really is empty, you'll get a runtime error that `a` isn't assigned.

oh, i get it
