### ISSUE TITLE
Constrained generic does not hint that method exists.

### ISSUE THREAD

**Issue by jepperaskdk** [dart-lang/language#1693]
Can you show me how to achieve the example below?
Why does `<T extends Serializable>` not guarantee that I can call `fromJson` on `T`?
There are a number of StackOverflow threads on this particular example, probably because of this flutter turtorial:
https://flutter.dev/docs/cookbook/networking/fetch-data

```
abstract class Serializable {
  Object fromJson(Map<String, dynamic> json);
}

class A implements Serializable {
  @override
  A fromJson(Map<String, dynamic> json) {
    throw UnimplementedError();
  }
}

class Utilities {
  static T fromJson<T extends Serializable>(Map<String, dynamic> json) {
    return T.fromJson(json);
    /**   ---^
     * The method 'fromJson' isn't defined for the type 'Type'.
       Try correcting the name to the name of an existing method, or defining a method named 'fromJson'.
     */
  }
}

var t = Utilities.fromJson<A>({});
```

Thank you in advance. :)

**Comment by lrhn** [comment]
You cannot call static methods on type variables at all. 

One reason it's a bad match for Dart is that Dart static members are not inherited by subclasses. Even if class `X` declares a static `foo` member, a subclass `Y extends X` does not have to have any static `foo` member, or it can have one with a completely different signature.
So, if you have `<T extends X>` then `T` can be bound to `Y`. Doing `T.foo` could be completely wrong.

At the point where you call` Utilities.fromJson<A>({})`, you need to call `A.fromJson` directly (or pass *that* to a helper function instead of just the type).
