### ISSUE TITLE
Does isolates in dart queue the values received on its port ?If yes , then how can I ensure that it works only on latest message?

### ISSUE THREAD

**Issue by radha1990kumari** [dart-lang/language#1699]
I will be passing camera image stream in an isolate for processing and I want that after processing current frame ,the isolate start processing the latest frame received .How can implement this in dart for flutter app.

**Comment by ds84182** [comment]
Isolates do queue values received on their ports. There are various ways to work on the latest value:

You can probably ensure it only works on the latest message by enqueuing an event to process incoming data from a ReceivePort. For example (untested, probably works):

```dart
late String latestMessage;
bool scheduledProcessingEvent = false;
RawReceivePort((String message) {
  latestMessage = message;
  if (!scheduledProcessingEvent) {
    scheduledProcessingEvent = true;
    Timer.run(() {
      scheduledProcessingEvent = false;
      processMessage(latestMessage);
    });
  }
});
```

This still buffers messages into the ReceivePort, so enqueuing a bunch of messages would result in higher memory usage. Since you're working with camera images, the messages might be quite large.

----

A different solution would involve bidirectional communication. Basically using a second SendPort in the processing isolate to indicate when its finished. Then you only send the latest camera image when the isolate finishes processing the current frame.

**Comment by radha1990kumari** [comment]
@ds84182 ,Thank you will try that.
