### ISSUE TITLE
Can function types be instantiated as type literals?

### ISSUE THREAD

**Issue by srawlins** [dart-lang/language#1700]
I have encountered a few questions that I don't think the [constructor tearoff spec](https://github.com/dart-lang/language/blob/master/accepted/future-releases/constructor-tearoffs/feature-specification.md) answers:

#### Can I instantiate function types directly?

E.g.

```dart
var t1 = void Function();
```

I think the answer is "no" but only from little hints, like "We can also use type aliases to define instantiated **interface types**, but we cannot do the same thing in-line" and "We will introduce syntax allowing you to explicitly instantiate [...] a type literal for a **generic class**" (emphasis mine). Am I correct in reading that function types cannot be instantiated? 

#### What about via a type alias?

```dart
typedef Fn<T> = void Function();
var t1 = Fn<int>;
```

The question here is: do we resolve `Fn` to its definition, and then if it resolves to a function type, we report an error? I don't think this is explicitly called out...

#### What about a type variable type alias?

```dart
typedef T<E> = E;
var t1 = T<int>;
var t2 = T<void Function()>;
```

Should `t1` resolve to a Type object for `int`? Again `t2` is an error?

**Comment by eernstg** [comment]
I think this is all determined by the grammar: `int` is an expression because expressions include `<identifier>`, but `void Function()` is not an expression, so `var t1 = void Function();` is an error. But `var t1 = Fn<int>;` is OK, and so is `var t1 = T<int>;` and `var t2 = T<void Function()>;`. The type alias `T` expands to a type variable, but that makes no difference here, because using a type literal as an expression is not a case where we are using the type alias as a class.

For this, I'm relying on the grammar I proposed here: https://dart-review.googlesource.com/c/sdk/+/197161.

**Comment by lrhn** [comment]
When Erik says `Fn<int>` is OK, it assumes the grammar extension we're planning for the future "constructor tearoffs" language feature. It's not currently OK.

**Comment by srawlins** [comment]
Excellent! Thanks for the responses! This can be closed unless someone thinks the proposal should be adjusted, or test cases should be added. I did not see any in [@lrhn's CL](https://dart-review.googlesource.com/c/sdk/+/197168) similar to my cases above, but I may have missed them.

**Comment by lrhn** [comment]
Explicitly instantiated type literals would be the test https://dart-review.googlesource.com/c/sdk/+/197168/7/tests/language/type_object/explicit_instantiated_type_literal_test.dart (and the similary named "error" test for using them badly).
