### ISSUE TITLE
Generic Closure TypeError when used in other scope

### ISSUE THREAD

**Issue by ltOgt** [dart-lang/language#1701]
Take the following setup:
```dart
class GenericBase {}

class GenericChild extends GenericBase {}

class FunctionOrigin<G extends GenericBase> {
  final void Function(G generic) func;

  FunctionOrigin(this.func);
}
```

Using `func` works without issue when called in the same scope as `origin` was defined in:
```dart
void main() {
  final origin = FunctionOrigin<GenericChild>((GenericChild child) {
    print("works");
  });

  final genericInstance = GenericChild();

  print("\n Calling from same scope");
  origin.func(genericInstance);
}
```
```out
 Calling from same scope
works
```

Doing exactly the same but passing `origin` and `genericInstance` to a method or global function will result in a `_TypeError`:
```dart
class FunctionUser {
  void useFuncClass(FunctionOrigin origin, GenericBase genericInstance) {
    origin.func(genericInstance);
  }
}

void useFuncGlobal(FunctionOrigin origin, GenericBase genericInstance) {
  origin.func(genericInstance);
}

void main() {
  final origin = FunctionOrigin<GenericChild>((GenericChild child) {
    print("works");
  });

  final genericInstance = GenericChild();

  print(" Calling from same scope");
  origin.func(genericInstance);

  try {
    print("\n Calling from within function inside class");
    FunctionUser().useFuncClass(origin, genericInstance);
  } catch (e) {
    print(e);
  }

  try {
    print("\n Calling from within function in global scope");
    useFuncGlobal(origin, genericInstance);
  } catch (e) {
    print(e);
  }
}
```
```out
 Calling from same scope
works

 Calling from within function inside class
type '(GenericChild) => void' is not a subtype of type '(GenericBase) => void'

 Calling from within function in global scope
type '(GenericChild) => void' is not a subtype of type '(GenericBase) => void'

```

________
When Replacing `GenericChild` with `GenericBase` everything works everywhere:
```dart
final origin2 = FunctionOrigin((GenericBase child) {
  print("works");
});

final genericInstance2 = GenericBase();

print("\n Calling from same scope");
origin2.func(genericInstance2);

try {
  print("\n Calling from within function inside class");
  FunctionUser().useFuncClass(origin2, genericInstance2);
} catch (e) {
  print(e);
}

try {
  print("\n Calling from within function in global scope");
  useFuncGlobal(origin2, genericInstance2);
} catch (e) {
  print(e);
}
```
```out
 Calling from same scope
works

 Calling from within function inside class
works

 Calling from within function in global scope
works
```
_____
<details>
<summary>Copy Paste the whole example from here</summary>
<p>

```dart
class GenericBase {}

class GenericChild extends GenericBase {}

class FunctionOrigin<G extends GenericBase> {
  final void Function(G generic) func;

  FunctionOrigin(this.func);
}

class FunctionUser {
  void useFuncClass(FunctionOrigin origin, GenericBase genericInstance) {
    origin.func(genericInstance);
  }
}

void useFuncGlobal(FunctionOrigin origin, GenericBase genericInstance) {
  origin.func(genericInstance);
}

void main() {
  final origin = FunctionOrigin<GenericChild>((GenericChild child) {
    print("works");
  });

  final genericInstance = GenericChild();

  print(" Calling from same scope");
  origin.func(genericInstance);

  try {
    print("\n Calling from within function inside class");
    FunctionUser().useFuncClass(origin, genericInstance);
  } catch (e) {
    print(e);
  }

  try {
    print("\n Calling from within function in global scope");
    useFuncGlobal(origin, genericInstance);
  } catch (e) {
    print(e);
  }

  try {
    print("\n Calling from within function inside class; WITH BASE");
    FunctionUser().useFuncClass(origin, GenericBase());
  } catch (e) {
    print(e);
  }

  //
  //
  //
  //

  final origin2 = FunctionOrigin((GenericBase child) {
    print("works");
  });

  final genericInstance2 = GenericBase();

  print("\n Calling from same scope");
  origin2.func(genericInstance2);

  try {
    print("\n Calling from within function inside class");
    FunctionUser().useFuncClass(origin2, genericInstance2);
  } catch (e) {
    print(e);
  }

  try {
    print("\n Calling from within function in global scope");
    useFuncGlobal(origin2, genericInstance2);
  } catch (e) {
    print(e);
  }
}

```

</p>
</details>

**Comment by lrhn** [comment]
Function parameters are *contra-variant*. That means that `void Function(num)` is a *subtype* of `void Function(int)`, even though `num` is a *supertype* of `int`. The way the subtype ordering changes (the variance) of the composite function type is opposite (contra to) the ordering of the part types that occur as parameters.

On the other hand, Dart *class generics* are co-variant (so `List<num>` is a supertype of `List<int>`, and the ordering changes along with (co-) the ordering of the part types occurring as type arguments).
That's not always sound, but it's what we have, and it's usually convenient.

That gives you a conflict when you use a class type parameter as the type of a function type's parameter type. The two work in opposite directions. 

Your `FunctionOrigin` is such a class:
```dart
class FunctionOrigin<G extends GenericBase> { // <- FunctionOrigin is covariant in G.
  final void Function(G generic) func;          // <- func is contravariant in G

  FunctionOrigin(this.func);
}
```
So, when you up-cast a `FunctionOrigin<GenericChild>` to `FunctionOrigin<GenericBase>`, it's varying in the wrong direction for `func`.

Your helper functions do that:
```dart
void useFuncGlobal(FunctionOrigin origin, GenericBase genericInstance) {
  origin.func(genericInstance);
}
```
Since you don't provide a type argument to `FunctionOrigin` here, it instantiates to bound and becomes `FunctionOrigin<GenericBase>`.

When you later call `useFuncGlobal(FunctionOrigin<GenericChild>(...), GenericChild())`, the parameters are accepted because they are *subtypes* of the declared type.

Then you try to read `origin.func`, which expects a `void Function(GenericBase)` , because the type of `origin` is `FunctionOrigin<GenericBase>`. It instead finds a `void Function(GenericChild)` *which is-not a `void Function(GenericBase)`*.
We know covariant class generics are unsound, so the compiler inserts extra checks in positions where that unsoundness might rear its head. This is one of those places, so when the `origin.func` finds a value which is not an instance of the expression's static type, it throws. Unsoundness detected, error!

What you can do instead is to declare `useFuncGlobal` as generic:
```dart
void useFuncGlobal<T extends OriginBase>(FunctionOrigin<T> origin, T genericInstance) {
  origin.func(genericInstance);
}
```
With that, it's still possible to make it throw, but if your call `useFuncGlobal(FunctionOrigin<GenericChild>(...), GenericChild())` correctly infers `T` to be `GenericChild`, or you write it explicitly, then the code will work correctly.

**Comment by ltOgt** [comment]
Thank you very much for the detailed answer and taking the time to write it.
Learned something new today
