### ISSUE TITLE
Typedef argument is not inferred

### ISSUE THREAD

**Issue by nt4f04uNd** [dart-lang/language#1702]
I'm not sure if that's a bug in SDK or this is by design, so opening issue here.

For some reason, the callback type in this case cannot be inferred and gives me `Object?`, unless I specifify the type for the argument explicitly.

So the error is
```
line 2 • The argument type 'Object?' can't be assigned to the parameter type 'Item'.
```

```dart
void main() {
  A((item) => function(item));
}

void function(Item item) {
  
}

class Item {}

class A<T extends Item> {
  A(this.callback);
  final Callback<T> callback;
}

typedef Callback<T> = void Function(T item);
```

**Comment by Levi-Lesches** [comment]
I think this is working as intended. The error seems to be, if I understand you correctly, that because `function` expects an `Item`, your closure (`(item) => function(item)`) should be inferred as `void Function(Item)`. But Dart doesn't inspect the inside of a function to infer what type the parameters are, so it won't look at your closure and say "oh well it passes `item` to `function`, so `item` must be an `Item`."

If you want to fix this, you can: 

1. Pass `function` to `A` directly, instead of creating a closure to do it (preferred): 

```dart
void main() {
  A(function);
}
```

2. Add a type to your closure: 
```dart
void main() {
  A( (Item item) => function(item) );
}
```

**Comment by munificent** [comment]
@Levi-Lesches is correct. This is working as intended. Type inference doesn't go into the bodies of lambdas. It's possible that a future version Dart *could* support that, but it gets pretty complex pretty fast and it is deliberate that we don't support it today.
