### ISSUE TITLE
why Function<T>(T a, T b) is same Function<bool>(dynamic a, dynamic b) ? 

### ISSUE THREAD

**Issue by jpoh281** [dart-lang/language#1710]
```
typedef TestFunction = int Function<T>(T a, T b);


void main() {
 TestFunction boolDynamicDynamic = testFunction;
 TestFunction boolBoolBool =  <bool>(bool a, bool b) => 2;
 TestFunction boolDynamicDynamic2 = <bool>(dynamic a, dynamic b) => 2;
  print(boolDynamicDynamic.runtimeType); // <T1>(dynamic, dynamic) => int
  print(boolBoolBool.runtimeType); // <T1>(T1, T1) => int
  
  print(boolDynamicDynamic.runtimeType == boolBoolBool.runtimeType); // false
  
  print(boolDynamicDynamic.runtimeType is TestFunction); // false
  print(boolBoolBool.runtimeType is TestFunction); // false
  
}


int testFunction<bool>(dynamic a, dynamic b){
  return 2;
} 
```

I can't understand Function<T>(T a, T b) ==  testFunction<bool>(bool a, bool b)

**Comment by lrhn** [comment]
Both `<bool>(bool a, bool b) => 2` and `int testFunction<bool>(dynamic a, dynamic b){ return 2; }` introduces a *type parameter* named `bool`. It could have been called `T` instead, it's just a name. It has no relation to the `bool` type from `dart:core`.
So, it's really just `<T>(T a, T b) => 2` and `int testFunction<T>(dynamic a, dynamic b){ return 2; }` with fancy names, the former has run-time type `int Function<T>(T, T)` (same type as declared by `TestFunction`), the latter has run-time type `int Function<T>(dynamic, dynamic)`, which is a proper subtype of `int Function<T>(T, T)`, and can therefore be assigned to `TestFunction`, but is not equal to it.

That's why `boolBoolBool.runtimeType` is `int Function<T1>(T1, T1)`

**Comment by jpoh281** [comment]
I have one more question.
```
typedef TestFunction<T> = T Function<T>(T a, T b); 

void main(){
  TestFunction <bool> bb = testFunction; // ok
  // TestFunction <bool> bb = testFunction<bool>; // error
  print(bb(1, 3));
}
T testFunction<T>(T a, T b) => a;
```

why working this?

**Comment by lrhn** [comment]
You can't write `testFunction<bool>` yet. That syntax does not exist in the grammar, but will be added as part of one of our next language enhancements.

Until then you can only do *implicit* instantiation, which is what 
```dart
 TestFunction <bool> bb = testFunction; // ok
```
does. It implicitly specialzies the `testFunction` tear-off to the `<bool>` type parameter.

**Comment by jpoh281** [comment]
Thanks to you, I got to know more about dart lang
