### ISSUE TITLE
Definite assignment does not work for switch case with enum-like classes

### ISSUE THREAD

**Issue by Giuspepe** [dart-lang/language#1730]
Definite assignment of variables with switch cases of enum-like classes does not work correctly, see the following examples:

The [`exhaustive_cases`](https://dart-lang.github.io/linter/lints/exhaustive_cases.html) lint works correctly in the following example:

```dart
class EnumLike {
  final int i;

  const EnumLike._(this.i);

  static const e = EnumLike._(1);
  static const f = EnumLike._(2);
  static const g = EnumLike._(3);
}


void exhaustiveCases(EnumLike e) {
  switch (e) {
    // analyzer: exhaustive_cases lint, because cases for EnumLike.f and EnumLike.g are missing
    case EnumLike.e:
      print("exhaustive_cases lint");
  }
}
```

Definite assignment works correctly with normal enums:

```dart
enum RealEnum { a, b, c }

void good(RealEnum e) {
  String data;
  switch (e) {
    case RealEnum.a:
      data = "a";
      break;
    case RealEnum.b:
      data = "b";
      break;
    case RealEnum.c:
      data = "c";
      break;
  }

  print(data); // data is definitely assigned -> no lint
}
```

However, definite assignment does not work with enum-like classes:

```dart
void bad(EnumLike e) {
  String data;
  switch (e) {
    // LINT
    case EnumLike.e:
      data = "e";
      break;
    case EnumLike.f:
      data = "f";
      break;
    case EnumLike.g:
      data = "g";
      break;
  }

  // data is definitely assigned too, but analyzer doesn't recognize this,
  // even though it knows that the switch of the enum-like class is exhaustive.
  // otherwise, it would have returned an exhaustive_cases lint.
  print(data); // analyzer lint: not_assigned_potentially_non_nullable_local_variable, because data is not definitely assigned
}
```

I expected definite assignment to work with enum-like classes as well, because the `exhaustive_cases` lint does work correctly with enum-like classes.

Is this issue correct for the `dart-lang/language` repo or should I file it in the `dart-lang/linter` repo?
Thanks for your help!

**Comment by Levi-Lesches** [comment]
Just because you only defined `e`, `f`, and `g`, it does not mean you cannot have other valid instances of `EnumLike`. What should happen if I wrote `bad(EnumLike._(4))`? That's what the error is trying to say. 

If you want exhaustiveness checking _and_ assigning a value to an enum, use `switch` to do both: 

```dart
enum MyTypes {e, f, g}

void good(MyTypes type) {
  switch(type) {
    case MyTypes.e: print("E, 1");
    case MyTypes.f: print("F, 2");
    case MyTypes.g: print("G, 3");
  }
}
```

**Comment by Giuspepe** [comment]
Thanks for your reply @Levi-Lesches. I'm a bit confused about this part now in combination with the lint `exhaustive_cases`:

> This is only true when switching on enums. In your case, you switch on a regular object, so it doesn't even try exhaustiveness checking, just like it wouldn't try for String and int.

In the example given for the lint `exhaustive_cases` https://dart-lang.github.io/linter/lints/exhaustive_cases.html the analyzer checks exhaustiveness, even though the switch is not on a regular enum.

**Comment by TimWhiting** [comment]
My understanding is that the `exhaustive_cases` check always triggers on non-enums unless there is a default case. In other words the default case covers the exhaustive options for the non-enum type.

**Comment by Giuspepe** [comment]
@TimWhiting this does not trigger the `exhaustive_cases` lint

from https://dart-lang.github.io/linter/lints/exhaustive_cases.html
```dart
class EnumLike {
  final int i;
  const E._(this.i);

  static const e = E._(1);
  static const f = E._(2);
  static const g = E._(3);
}

void ok(E e) {
  // All cases covered.
  switch(e) { // OK
    case E.e :
      print('e');
      break;
    case E.f :
      print('e');
      break;
    case E.g :
      print('e');
      break;
  }
}

**Comment by eernstg** [comment]
I'm afraid `exhaustive_cases` has a few rough edges, cf. https://github.com/dart-lang/linter/issues/2768.

**Comment by Levi-Lesches** [comment]
@Giuspepe, I think the issue is the difference between the `exhaustive_cases` lint and definite assignment. The lint just wants to make sure you didn't miss anything, but there's nothing wrong with not including every possible case. For example, you can easily switch over some numbers, without including every possible number. That's why the lint only pops up when you signal to it that you have a limited number of possible values, like an enum or an enum-like class. The linter is smart enough to understand that even though it's _possible_ to have `e == EnumLike._(4)`, your switch statement probably doesn't care about it, so it doesn't bother you. This is also why the following "edge case" happens: 
```dart
class EnumLike {
  final int i;
  const E._(this.i);

  static const e = E._(1);
  static const f = E._(2);
  static const g = E._(3);
}

void ok(E e) {
  // LINT: Missing case for E.g
  switch(e) { // OK
    case E.e :
      print('e');
      break;
    case E.f :
      print('e');
      break;
    case E._(3) :  // this is equal to E._(3), but the linter doesn't notice and errors anyway
      print('e');
      break;
  }
}
```
 
But a non-nullable variable _has_ to be assigned before it can be accessed. So if you don't cover _every possible_ case, then there's a way for it to be potentially unassigned. This is where `E._(4)` becomes an issue, and by not covering all possibilities, your code is unsafe. As another example, let's use strings: 

```dart
void printResponse(String message) {
  // no lint here, since 
  // 1. it's okay if we don't print a message 
  // 2. there aren't any obvious constants to choose from
  switch(message) {  
    case "Hello": print("World"); break;
    case "How are you?": print("Good"); break;
    case "Do you like Dart?": print("Yes"); break;
  }
}

String returnResponse(String message) {
  // Error: THe body might complete normally, causing null to be returned.
  switch(message) {  
    case "Hello": return "World";
    case "How are you?": return "Good";
    case "Do you like Dart?": return "Yes";
  }
}
```

Hope that clears it up

**Comment by Giuspepe** [comment]
Thanks for clarifying @Levi-Lesches, that makes sense :)
