### ISSUE TITLE
Add option to Completer to suppress StateError when calling complete() multiple times

### ISSUE THREAD

**Issue by enloc-port** [dart-lang/language#1731]
When calling `complete()` on a completed `Completer`, a `StateError` is thrown.

To avoid this, every potentially subsequent call to `complete()` has to be wrapped into a `if (completer.isCompleted) { ...`.

But in some scenarios, I just don't care whether the `Completer` is completed or not. For instance when a function has multiple async operations, each of which may or may not complete the `Completer`, but I only care which "completion" fires first, similar to a `Future.any()`.

In such cases, I want the `Completer` to simply ignore all subsequent calls to `complete()` when it has already been completed.

I am not sure on how to call this parameter and what its default value should be. So it's called `suggestedParameter` in the following example:

```Dart
Completer<bool> completerThrow = Completer<bool>(suggestedParameter: true);
completerThrow.complete(true);
completerThrow.complete(false); // should ignore this call

Completer<bool> completerIgnore = Completer<bool>();
completerIgnore.complete(true);
completerIgnore.complete(false); // should throw

**Comment by mateusfccp** [comment]
You can do it easily with extension methods (I couldn't come with a better name, tho):

```dart
extension TryCompleteCompleterExtension<T> on Completer<T> {
  bool tryComplete(T value) {
    if (isComplete) {
      return false;
    } else {
      complete(value);
      return true;
    }
  }
}
```

This way you can call it indiscriminately and it won't ever trow, but you will also be able to know if the completer was completed in a specific call through the returned `bool`.

**Comment by lrhn** [comment]
This is not something we'll put on the completer itself. It has all the necessary information, and most uses of a completer knows whether the completer is completed or not, and should be checking that before trying to complete anyway.
The cases where you don't know it, you usually could have set a boolean flag somewhere else, and you just didn't because `completer.isCompleted` is equivalent and sufficient.

So, not going to put a flag on `complete` to make it optionally do nothing. Not calling the method is the superior way to do nothing 😁 . (That, and changing the API is a breaking change, so it's not without cost to change it).

**Comment by enloc-port** [comment]
Writing a simple extension, as mentioned in one of the comments, is the better solution compared to the alternative.
