### ISSUE TITLE
Using the spread operator together with short conditional operators 

### ISSUE THREAD

**Issue by M123-dev** [dart-lang/language#1735]
You currently cannot add items to a collection using the spread operator together with short conditional operators.

``` dart
  List<int> list3 = <int>[
    isTrue ? ...list1 : ...list2,
    if(isTrue) ...list1 else ...list2,
  ];
```

The second line causes erros but the third line is fine, normal values (not via the spread operator ) can be inserted with the short variant.

```
info line 12 • The value of the local variable 'list2' isn't used. (view docs)
Try removing the variable or using it.

error line 15 • Expected an identifier.
error line 15 • Expected to find ':'.
error line 15 • Expected to find ']'.
```

[Dartpad example](https://dartpad.dev/?id=266456ddb7f8b3fc08be295cdd61638a&null_safety=true)

**Comment by Levi-Lesches** [comment]
Interestingly enough, removing the spread for `list1` in the ternary is enough to get the compiler to stop complaining. Of course, that's not desired here, but it's interesting that the compiler _can_ allow `list2` to start with `...`. 

Anyway, I think the problem is that the spread operator doesn't evaluate to an expression, but is rather a command to Dart. So using it with a ternary means there is no well-defined value coming out of that expression, and thus isn't allowed by the grammar. From [a similar question on Stack Overflow](https://stackoverflow.com/questions/65788284/flutter-dart-problem-using-the-spread-operator-after-the-else-clause-of-a-ter), it seems like the proper workaround is to (use if/else or) put the spread before the ternary, then use parenthesis, like so: 

```dart
  List<int> list3 = <int>[
    ...(isTrue ? list1 : list2),
  ];
```

**Comment by lrhn** [comment]
> but it's interesting that the compiler can allow `list2` to start with `...`

It shouldn't.
You can only use the `...` notation in an *element*, which is a slightly different syntactic category than *expression*. An element can only occur in a collection literal, and is either an expression, a spread, a collection-`if` containing two elements or a collection-`for` containing an element.
(And I can't see which compiler you are using, but neither Dartpad doesn't allow it, neither analyzer nor dart2js).

The conditional expression (`?`/`:`) cannot contain an element, only expressions, so it shouldn't be able to contain a spread.

**Comment by Levi-Lesches** [comment]
I did use DartPad, but in hindsight it was probably one of those times where DartPad doesn't report any errors, even when there are (it happens a lot).

**Comment by munificent** [comment]
As Lasse said, this is working as intended. Expressions and collection elements are different things (though there is a collection element that is merely a single expression). We don't allow collection elements to nest inside expressions. The only expression where that would even be meaningful is the conditional expression, and that isn't much of a value-add since we already have `if` elements. (Another way to think about is that the only reason `?:` even exists at all is because you can't use `if` in expressions.)
