### ISSUE TITLE
empty named constructor shoud use {} instead of ;?

### ISSUE THREAD

**Issue by Silentdoer** [dart-lang/language#1736]
```dart
class Foo {
  var prop1;
  var prop2 = 8;

  /// flag,  it seems like call a function
  /// if use Foo.name() {} will be more clear
  Foo.name();
  static instance = Foo.name();
}
```

**Comment by Levi-Lesches** [comment]
So to clarify, `;` means "end of statement", and `{ }` means "this is a body of code, but it's empty. The difference is very noticable in abstract classes: 

```dart
abstract class A {
  void function1();  // abstract function
  void function2() { }  // regular function, just does nothing
}

/// Because `function1` is abstract, we need to override that in `B`.
/// We don't need to override `function2` though. 
class B extends A { }
```

With constructors, there's a difference between a constructor with and without a body -- the most relevant one I can think of right now is that only non-body constructors can be `const`: 

```dart
class A { 
  const A.canBeConst();
  const A.notConst() { }   // error, const constructors cannot have a body
}
```
Dart doesn't bother to check if the body of the constructor is empty, because including the `{ }` is how you tell Dart you want it to have a body, and that's what's important. 

Also, syntax sugar makes code look nice! Consider constructors with lots of paramters: 
```dart
class Person {
  final String name, favoriteColor, bio;
  final int age, numSiblings;
  final bool isAwesome, isSmart;

  const Person({
    required this.name, 
    required this.favoriteColor, 
    required this.bio, 
    required this.age, 
    required this.numSiblings, 
    required this.isAwesome, 
    required this.isSmart,
  }) { }
```

The `{ }` just looks out of place, doesn't it? A semicolon accurately states that there is nothing left to do, the initializer list has done all the work. At least I think so, it's subjective. The technical part is above.

**Comment by Silentdoer** [comment]
> 
> 
> So to clarify, `;` means "end of statement", and `{ }` means "this is a body of code, but it's empty. The difference is very noticable in abstract classes:
> 
> ```dart
> abstract class A {
>   void function1();  // abstract function
>   void function2() { }  // regular function, just does nothing
> }
> 
> /// Because `function1` is abstract, we need to override that in `B`.
> /// We don't need to override `function2` though. 
> class B extends A { }
> ```
> 
> With constructors, there's a difference between a constructor with and without a body -- the most relevant one I can think of right now is that only non-body constructors can be `const`:
> 
> ```dart
> class A { 
>   const A.canBeConst();
>   const A.notConst() { }   // error, const constructors cannot have a body
> }
> ```
> 
> Dart doesn't bother to check if the body of the constructor is empty, because including the `{ }` is how you tell Dart you want it to have a body, and that's what's important.
> 
> Also, syntax sugar makes code look nice! Consider constructors with lots of paramters:
> 
> ```dart
> class Person {
>   final String name, favoriteColor, bio;
>   final int age, numSiblings;
>   final bool isAwesome, isSmart;
> 
>   const Person({
>     required this.name, 
>     required this.favoriteColor, 
>     required this.bio, 
>     required this.age, 
>     required this.numSiblings, 
>     required this.isAwesome, 
>     required this.isSmart,
>   }) { }
>   // vs
>   const Person({
>     required this.name, 
>     required this.favoriteColor, 
>     required this.bio, 
>     required this.age, 
>     required this.numSiblings, 
>     required this.isAwesome, 
>     required this.isSmart,
>   });
> ```
> 
> The `{ }` just looks out of place, doesn't it? A semicolon accurately states that there is nothing left to do, the initializer list has done all the work. And it kinda looks like the semicolon "hugs" the parentheses, which makes it less visually distracting. At least I think so, it's subjective. The technical part is above.

ok, thank you
