### ISSUE TITLE
please support if (type == GenericType<R>)

### ISSUE THREAD

**Issue by Silentdoer** [dart-lang/language#1738]
and also support if (T == void) ?, otherwise i need use the function:
```dart
bool isVoidType<T>() {
    var list = <T>[];
    var s = <void>[];
    if (list.runtimeType == s.runtimeType) {
      return true;
    } else {
      return false;
    }
  }
```

**Comment by Levi-Lesches** [comment]
Try comparing the object instead of the type, by using `is` instead of `==`: 

```dart
void typeCheck(Object obj) {
  if (obj is List<int>) print("This is a list of integers");
}

void main() {
  List<int> numbers = [1, 2, 3];
  typeCheck(numbers);  // "This is a list of integers"
}
```

Also, as far as I know, `void` isn't really a type -- it's an instruction, just like `dynamic`. It tells Dart "don't let this value be used". Which makes me wonder why (and even how) you're using it so often. Types work best when you set them correctly then leave them alone. If you're constantly worrying about which type you have, you may be going about it the wrong way, and it's probably better to try something else instead. If you need help, you can ask on StackOverflow.com or try me here.
