### ISSUE TITLE
type '(String) => int' is not a subtype of type '(dynamic) => dynamic'

### ISSUE THREAD

**Issue by Silentdoer** [dart-lang/language#1740]
I have two callable type, 
1. `typedef Callable<R> = R Function();`
2. `typedef CallableWithState<S, R> = R Function(S);`

my executor tasks contains the two callable, so in run task code, i need check task's type, such as:
```dart
class TaskWrapper<S, R> {
  CallableWithState<S, R> task;
  S state;
}

if (taskWrapper is TaskWrapper) {  /* it equals task is TaskWrapper<dynamic, dynamic>, task contains it's origin generic type, but i can not take out it;*/
  // throw type '(String) => int' is not a subtype of type '(dynamic) => dynamic'
  // dart should allow this invoke ?
  taskWrapper.task(taskWrapper.state);
}
```
```

**Comment by Silentdoer** [comment]
I use Function replace `CallableWithState<S, R>`, code is works

**Comment by eernstg** [comment]
The approach taking in `TaskWrapper` is actually tricky to handle well in Dart, so I'll comment on it in some detail.

Note that `task` in the class [here](https://github.com/dart-lang/language/issues/1740#issue-942890120) and also in the following class is a "contravariant" member:

```dart
class TaskWrapper<S, R> {
  R Function(S) task;
  S state;
  TaskWrapper(this.task, this.state);
}
```

A [contravariant class member](#297) takes covariant type parameters to the extreme, because you can get dynamic type errors even on a read operation:

```dart
void main() {
  TaskWrapper<num, num> taskWrapper = TaskWrapper<int, int>((i) => i, 3);
  taskWrapper.task; // Throws!
}
```

This is a consequence of the choice in Dart to use dynamically checked covariance for all class type parameters.

If and when we add [sound declaration-site variance](#524) to the language, you can make the critical type variable invariant. That makes the program statically typesafe (but it will break some working programs, because it eliminates some subtype relationships):

```dart
// Requires sound declaration-site variance!

class TaskWrapper<inout S, R> {
  R Function(S) task;
  S state;
  TaskWrapper(this.task, this.state);
}
```

Until then, I'd recommend against having contravariant members at all. It's quite often possible to get rid of contravariant members by using a function type as the type parameter, rather than building a function type in the body of the class:

```dart
class TaskWrapper<Task extends Object? Function(State), State> {
  final Task task;
  final State state;
  TaskWrapper(this.task, this.state);
}

void main() {
  task(num i) {
    print("Running main task!");
    return i + 0.1;
  }
  
  var tw = TaskWrapper(task, 3);
  print(tw.runtimeType); // 'TaskWrapper<(num) => double, int>'.
  TaskWrapper<double Function(int), int> tw2 = tw; // OK.
  tw.task; // No problem, `task` isn't contravariant.
  tw2.task; // Static type != dynamic type, still no problem.
  var d = tw.task(tw.state); // Typable, `d` has type `double`.
}
```

`task` and `state` don't have to be final, but that's yet another step you can take in order to eliminate the dynamic checks associated with covariance&mdash;worth considering, if it will fit into your software design.

**Comment by Levi-Lesches** [comment]
I'm not sure if this is relevant since the issue is closed now, but when I was trying to reproduce the issue I found that putting the generics on the left side of the equals (instead of the right) fixed the problem. Also, since the `task` and `state` are a part of `TaskWrapper`, you might as well make a method inside `TaskWrapper` that handles calling `task` with `state`. Here I demonstrated all three versions:
```dart
typedef CallableWithState<S, R> = R Function(S);

class TaskWrapper<S, R> {
  final CallableWithState<S, R> task;
  final S state;
  const TaskWrapper(this.task, this.state);
  
  /// [call] allows the class to be called as a function
  R call() => task(state);  
}

void main() {
  T func<T>(T i) => i;
  int result;

  // Method 1: Use generics on the left side
  TaskWrapper<int, int> wrapper1 = TaskWrapper(func, 3);
  result = wrapper1.task(wrapper1.state);  // okay
  print("Finished method 1: $result");
  
  // Method 2: Use a function that's part of TaskWrapper
  result = wrapper1();  // calls wrapper1.call()
  print("Finished method 2: $result");  // 3
  
  // Method 3: Use generics on the right side (fails)
  TaskWrapper wrapper2 = TaskWrapper<int, int>(func, 3);
  wrapper2.task(wrapper2.state);  // error
}
```

When you use generics on the left side, you're telling Dart that you want the wrapper to be treated as, say, a `TaskWrapper<int, int>`, regardless of what you actually assign to it. As pointed out above, if you used `<num, num`, you could assign an `<int, int>`, which would compile but could cause errors at runtime. So when you only used generics on the right, you were assigning an `<int, int>` to a `<dynamic, dynamic>`, which caused errors later.

**Comment by eernstg** [comment]
@Levi-Lesches, that `call` method is really interesting!

But first, note that the potential for run-time type errors on a mere read remains as long as we have a "contravariant" member. Here's a variant of your code with the same `CallableWithState` and `TaskWrapper`, but a slightly different `main`:

```dart
typedef CallableWithState<S, R> = R Function(S);

class TaskWrapper<S, R> {
  final CallableWithState<S, R> task; // A "contravariant member".
  final S state;
  const TaskWrapper(this.task, this.state);
  
  /// [call] allows the class to be called as a function
  R call() => task(state);  
}

void main() {
  T func<T>(T i) => i;

  TaskWrapper<num, int> wrapper1 = TaskWrapper<int, int>(func, 3);
  wrapper1.task(wrapper1.state); // Throws.
}
```

The evaluation of `wrapper1.task` throws (we don't even get to evaluate `wrapper1.state` or the invocation) because the value of `task` in wrapper1` has a value whose type is not a subtype of the statically known type `int Function(num)`.

This is also the reason why Method 3 throws: It's simply the same thing as

```
  ...
  TaskWrapper<dynamic, dynamic> wrapper2 = TaskWrapper<int, int>(func, 3);
   wrapper2.task(wrapper2.state); // Throws.
```

and `wrapper2.task` doesn't have the type `dynamic Function(dynamic)`, so it throws.

Returning to the `call` method, the approach where we make the class soundly covariant needs to be extended, because we can't decompose the function type `Task` inside the body of `TaskWrapper`. We need 3 type arguments:

```dart
class TaskWrapper<State, Result, Task extends Result Function(State)> {
  final Task task;
  final State state;
  const TaskWrapper(this.task, this.state);
  Result call() => task(state);
}

void main() {
  T func<T>(T i) => i;
  int result;

  // Method 1: Use generics on the left side
  TaskWrapper<int, int, int Function(int)> wrapper1 = TaskWrapper(func, 3);
  result = wrapper1.task(wrapper1.state);
  print("Finished method 1: $result");

  // Method 2: Use a function that's part of TaskWrapper
  result = wrapper1(); // calls wrapper1.call()
  print("Finished method 2: $result");

  // Method 3: Use generics on the right side (fails)
  var wrapper2 = TaskWrapper<int, int, int Function(int)>(func, 3);
  result = wrapper2.task(wrapper2.state);
  print("Finished method 3: $result");

  // Method 4: Provide arguments of the desired type.
  var wrapper3 = TaskWrapper(func<int>, 3);
  result = wrapper3.task(wrapper3.state);
  print("Finished method 4: $result");
}
```

This version of `TaskWrapper` is completely safe (it can be compiled with variance using `out` on all type parameters), and it maintains a sufficient amount of information to enable the `call` method.

As we can see in Method 1 and Method 3, this approach is unpleasantly verbose when we need/wish to pass the type arguments explicitly. But we can also see in Method 4 that it is sufficient to pass actual arguments to the constructor that have the right types (use use `var` to infer the variable type), then all those type arguments will be inferred bottom-up.

So it's a delicate trade-off (until we get support for sound variance, that is!), but we do have a sound alternative today.

**Comment by Levi-Lesches** [comment]
> But first, note that the potential for run-time type errors on a mere read remains as long as we have a "contravariant" member. Here's a variant of your code with the same `CallableWithState` and `TaskWrapper`, but a slightly different `main`:
> 
> ```dart
> typedef CallableWithState<S, R> = R Function(S);
> 
> class TaskWrapper<S, R> {
>   final CallableWithState<S, R> task; // A "contravariant member".
>   final S state;
>   const TaskWrapper(this.task, this.state);
>   
>   /// [call] allows the class to be called as a function
>   R call() => task(state);  
> }
> 
> void main() {
>   T func<T>(T i) => i;
> 
>   TaskWrapper<num, int> wrapper1 = TaskWrapper<int, int>(func, 3);
>   wrapper1.task(wrapper1.state); // Throws.
> }
> ```

Actually, while I do understand that contravariant generics can often cause errors, using `call` in this context _does_ work: 

```dart
typedef CallableWithState<S, R> = R Function(S);

class TaskWrapper<S, R> {
  final CallableWithState<S, R> task; // A "contravariant member".
  final S state;
  const TaskWrapper(this.task, this.state);
  
  /// [call] allows the class to be called as a function
  R call() => task(state);  
}

void main() {
  T func<T>(T i) => i;

  TaskWrapper<num, int> wrapper1 = TaskWrapper<int, int>(func, 3);
  wrapper1();  // <-- does not throw
  print("Made it here");
  wrapper1.task(wrapper1.state); // Throws.
}
```

I'm not sure why it works, but I can take a guess: 

> The evaluation of `wrapper1.task` throws (we don't even get to evaluate `wrapper1.state` or the invocation) because the value of `task` in `wrapper1` has a value whose type is not a subtype of the statically known type `int Function(num)`.

When we use `.call`, the types work out for `.call` itself, so the function is invoked without issue. Then, when the code reaches `=> task(state)`, it doesn't see an issue because it's working in the `TaskWrapper` context. In other words, Dart can't see that `<int, int>` is problematic with the static type `<num, int>`, because it's too distracted by `S` and `R` from inside `TaskWrapper` and "forgets" about `main`. 

I could be totally off, but that's what I'm thinking. It does feel a bit "magical" to have errors go away depending on the context of the function call, but I like to use the philosophy of "if this operation only uses variables intrinsic to this class, it should be its own method", which is why I thought of using `.call` in the first place. 

But yes, sound variance would be very nice, and I hope the team finds enough time to properly implement it as that would get rid of a lot of weird edge cases like this.

**Comment by eernstg** [comment]
`wrapper2()` does not throw because it calls a member of the receiver class. In the body of a member of the receiver class, the type arguments are in scope, and it is possible to denote the type arguments by name. Those names denote the actual (run-time) value of the type argument, and this means that variance is irrelevant: 

```dart
class A<in X, out Y> {
  // Variance puts constraints on the member signatures:
  // X get x => ...; would be an error: X occurs in a covariant position.
  // void m(Y y) {} would be an error: Y occurs in a contravariant position.

  void m2() {
    // But in the body of a member, `X` and `Y` are just types, and constraints
    // on type variables related to variance are irrelevant.
    X localFunction(Y y) => ...; // No problem!
  }
}
```

For `task(state)` we note that the type of `task` has type `R Function(S)` and the type of `state` is `S`, so it's OK (and safe!) to pass `state` as the actual argument to `task`.

So there's no confusion or magic, we're just relying on the fact that type variables are denotable types inside a generic class, but clients may have a static type of a receiver where the statically known type arguments are supertypes of the actual values, and this means that only some member signatures are safe (and sound variance is all about raising errors for the unsafe ones).
