### ISSUE TITLE
Allow to cast empty List<dynamic> to a list of any type we want

### ISSUE THREAD

**Issue by lirantzairi** [dart-lang/language#1750]
An empty List<dynamic> should be allowed to be casted to a list of any type we want (`List<int>`, `List<String>`, etc). Currently we can't do it unless we use `List<T>.map(...)` or `List<T>.from(...)`. This makes it hard to validate and decode responses of network calls because in these cases lists are usually of type `List<Map<String, dynamic>>` but an empty list will always start as `List<dynamic>`.

Small example:
```
import 'package:flutter/material.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  Future<void> _decode<EXPECTED_DATA_TYPE>(dynamic result) async {
    if (result is! EXPECTED_DATA_TYPE) {
      print('Unexpected data type');
      return;
    }
    print('Success');
  }

  Widget _buildTryEmptyButton() {
    return TextButton(
      child: Text('Try empty list'),
      onPressed: () {
        final result = []; // some network call returns empty list
        _decode<List<Map<String, dynamic>>>(result);
      },
    );
  }

  Widget _buildTryNonEmptyButton() {
    return TextButton(
      child: Text('Try non empty list'),
      onPressed: () {
        final result = [{'key': 'value'}]; // some network call returns non empty list
        _decode<List<Map<String, dynamic>>>(result);
      },
    );
  }

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        body: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: [
            _buildTryEmptyButton(),
            _buildTryNonEmptyButton(),
          ],
        ),
      ),
    );
  }
}

```

**Comment by jodinathan** [comment]
doesn't ```list.cast()``` work in this case?

**Comment by Levi-Lesches** [comment]
Yep. Changing
```dart
_decode<List<Map<String, dynamic>>>(result);
```
to
```dart
_decode<List<Map<String, dynamic>>>(result.cast<Map<String, dynamic>>());
```
fixes this. Also, you could just declare `result` as a `List<Map<String, dynamic>>`. In general, @lirantzairi, you shouldn't rely on `dynamic` to provide you with type safety -- it's entire purpose is to allow you to "disable" type safety. If you want to type an empty list, you can either do: 
```dart
final List<Map<String, dynamic>> result = [];
```
or
```dart
final result = <Map<String, dynamic>>[];
```
or, if it's a network call, like your comment suggests, explicitly mark the return type of the function to be `List<Map<String, dynamic>>`

**Comment by lirantzairi** [comment]
Thank you for your responses.

@Levi-Lesches my declaration `final result = []` is just to replace a possible server's response, and the fact it's dynamic actually shows my point, that it can be anything - `List<Map<String, dynamic>>` / `List<String>` / `Map<String, dynamic>` / `String` / etc. Using `cast<>()` requires to know in advance whether it's a list / map / non of them.

This is why I use `EXPECTED_DATA_TYPE` - it lets you validate whether the server's response type is as you expect. In almost all cases it works good. In particular, in case you expect it to be a list of some type and it's indeed a non empty list of that type then it works good. But if the response is actually an empty list, then the JsonDecoder makes it `List<dynamic>` and then it fails.

Logically, empty lists (`<dynamic>[]`) should be castable to lists of any type (same for maps btw). I can't think of a reason why not.

**Comment by Levi-Lesches** [comment]
Right, so you have a type argument, `EXPECTED_DATA_TYPE`, which means you know what type you want when you get the result. So you can do `result.cast<EXPECTED_DATA_TYPE>()` to get a correctly-typed list. And in both of your button callbacks, you know the type you want (`List<Map<String, dynamic>>`), so this works. 

> Using cast<>() requires to know in advance whether it's a list / map / non of them.

Well, the assumption is that at _some_ point you must know what type you have/want. Maybe it's when you parse the data, maybe it's when you render it as widgets, or anywhere in between. As soon as you know, you cast it to that. 

If you find that you _really_ don't know ahead of time what type of data will be returned to you, and what type you get changes what you do with that data, either 1) use a different API that tells you what type it returns, or 2) use a bunch of manual `if (result is X)` statements.

**Comment by lirantzairi** [comment]
I can't do `result.cast<EXPECTED_DATA_TYPE>()` in this case because `EXPECTED_DATA_TYPE` is `List<Map<String, dynamic>>`, not `Map<String, dynamic>`. I also can't assume that all lists are lists of maps because as I wrote they can be lists of other types. And it's not a matter of API (which obviously I can't just switch to a different one), it's  the way responses are decoded to jsons by JsonDecoder. As a workaround I can do one of the following:
1. Add a second generic type parameter, something like `_decode<EXPECTED_DATA_TYPE, SUBTYPE>(dynamic result)` so SUBTYPE can be used in `cast<SUBTYPE>()` in case EXPECTED_DATA_TYPE is a list.
2. Like you said, use a bunch of `if else`s.
3. Subclass JsonDecoder() and decode a string response in a way that lists will get a specific type, not `dynamic`

None of these solutions is very elegant and I don't see why they are better than allowing an empty list to simply be casted.

**Comment by Levi-Lesches** [comment]
If you can, maybe post some of your code? I can help you pick a good style. For myself, I only use `List` and `Map` when dealing with JSON (that is, implicitly `dynamic`) and use the right types in my for loops. So I might have something like this. 

```dart
Future<List<User>> getData() async {
  final List response = jsonDecode(await getServerResponse());
  return [
    for (final Map json in response) User.fromJson(json)
  ];
}
```

The logic is that `dynamic` involves a sort of "trust" from the compiler, so you may as well leverage that to write cleaner code. Of course, make sure to convert into a "safe" type as soon as possible, so that any type-related errors are very obvious and easy to debug. Otherwise, you may have a bunch of `dynamic`s flying through your otherwise-safe code.

**Comment by lrhn** [comment]
We can't just cast *any* empty list to another type because lists are mutable. If you could cast `var list = <dynamic>[];` to `List<int> intList = *castOperation* list;`, then someone could do `list.add("not an int")` and break type soundness.
So, it could only work for empty lists that are also immutable.
The result of JSON decoding is generally not immutable.

If you need to introduce an empty immutable list, then you can just use `const <Never>[]` and then you can cast it to any element type.

**Comment by lirantzairi** [comment]
@lrhn I understand your point, but the same problem would happen if you use `list.cast<>()` as a cast operation. It would pass the static checks and fail on runtime:
```
var list = <dynamic>[];
List<int> intList = list.cast<int>();
list.add("not an int");
print(intList);  // Will throw here
```

If I change `list.cast<int>()` to `list as List<int>` then thanks to type soundness I'll have to change `list.add("not an int")` to `list.add(1)` which is great but then it fails at runtime:
```
var list = <dynamic>[];
List<int> intList = list as List<int>;  // Will throw here
list.add(1);
print(intList);
```

I don't see why the cast in the first example should pass but the cast in the second example should fail.

**Comment by lrhn** [comment]
A `List<dynamic>` is-not-a `List<int>`. The request in this issue was to be allow to cast an *empty* `List<dynamic>` to any type of list.
When I say "cast", I mean `as List<int>`, not calling the `cast` method - you can always call the `cast` method, its up to you to not make it throw afterwards. The `list` method is *not casting the list*, it's introducing a wrapper which *cast the elements* when you access them. It's based on dynamic checks, which is why it fails at run-time. It's like using `dynamic` - you *claim* that something is true, and then later checks will throw if you were wrong. So, let's forget about the `cast` method.

I'm saying we can't allow you to *cast* even an empty `List<dynamic>` to `List<int>` in general because it's inherently unsafe.
The type system doesn't know whether lists are empty (or what it means to begin with, a `List` is just another interface), and even if the run-time check could check whether a list was empty, a list doesn't have to *stay* empty.

The only list where it's potentially safe to cast is an empty *immutable* list, because the new element type can never be disproved by any actual element. It's still not allowed because Dart generics reify the type parameter as part of the object. A `List<dynamic>` *knows* that it's a `List<dynamic>`. If you do `.toList()` on it, it will create a new *mutable* `List<dynamic>`.

The example given here was using an empty list as a default value. If they had used `const <Never>[]` as that default value, then it would be an empty immutable list which *can* be cast to any list type. So, just do that.
Casting an empty `List<dynamic>` to any subtype is very unlikely to happen.

**Comment by lirantzairi** [comment]
Ok, got it. Thanks for your reply and help :)

**Comment by munificent** [comment]
Closing because it seems like this is resolved now.
