### ISSUE TITLE
why  abstract class method  not analyze null-safety params

### ISSUE THREAD

**Issue by SakurasDuck** [dart-lang/language#1765]
`
abstract class A {
  void a({int param}); //?
}

class B extends A {
  @override
  void a({int? param}) {//it work
    //todo
  }
}
`

help!!! plz

**Comment by lrhn** [comment]
The abstract method `void a({int param});` is a valid function signature. It is possible to implement that method as, e.g.,
```dart
  void a({int param = 0}) { ... }
```

A *concrete* method needs to choose a strategy for dealing with omitted optional parameters, because it can access the parameter variables and needs to find a valid value. 
An abstract method doesn't need to do that. It can specify that it has an optional non-nullable parameter, and leave it up to the concrete implementation to decide how to satisfy that (which it can do either by adding a default value or by widening the parameter type to be nullable).
