### ISSUE TITLE
Should static-metaprogramming be allowed to add initializers to a contructor?

### ISSUE THREAD

**Issue by rrousselGit** [dart-lang/language#1769]
Related to data-classes and static-metaprogramming, in particular this comment: https://github.com/dart-lang/language/issues/314#issuecomment-888945152

## Use-case

I believe that for a reasonable data-class syntax, it is critical for users to define a constructor instead of the properties.

The idea is, instead of:

```dart
@data
class Person {
  final String name;
  final int age;
}
```

users would write:

```dart
@data
class Person {
  Person(
    final String name,
    final int age,
  );
}
```

The benefit of this approach is, users get access to all the constructor features, including:

- super constructors
- const constructors
- named constructors
- optional vs required parameters
- default values
- positional vs named parameters
- asserts

So an alternate example could be:

```dart
@data
class Person extends Mammal {
  const Person(
    final String name, {
    final int age = 0,
  }) :  assert(age >= 0),
         super(...);
}
```

## Problem 

The problem of this approach is, it works only if static-metaprogramming is allowed to modify a constructor.

So even if a macro generated the class properties, the constructor would not initialize them. 

## Proposal

Allow static-metaprogramming to modify a constructor by adding initializers.

In particular, this would involve transforming:

```dart
@data
class Person {
  Person(final String name);
}
```

into:

```dart
@data
class Person {
  Person(final String name): name = name;

  final String name;
  <add toString/==/copyWith methods>
}
```

My belief is that this is a benign change, because the constructor prototype is not altered in any way.

**Comment by Levi-Lesches** [comment]
If the user is going to specify the details of the constructor already, why not just format the fields nicely? So your example of: 
```dart
@data
class Person extends Mammal {
  const Person(
    final String name, {
    final int age = 0,
  }) :  assert(age >= 0),
         super(species: "Homo Sapiens");
}
```
would instead be 
```dart
@data
class Person extends Mammal {
  final String name;
  final int age;
  
  const Person(this.name, {this.age = 0}) : 
    assert(age >= 0),
    super(species: "Homo Sapiens");
}
```

I think that encourages much cleaner code for the price of writing just the `this.X` bits. The rest you would have had to write anyway.

**Comment by rrousselGit** [comment]
This causes a lot of duplication. One goal of data-classes is to remove duplicates.

**Comment by Levi-Lesches** [comment]
The only difference between the two code samples is the extra `this.X` parts -- everything else is written only once. Seeing as the `this.X` parts allow you to specify ordering, optionality, and names for named parameters, I'd say the extra few characters (less than one line of code) is a very small trade off for getting that much expressiveness.

**Comment by rrousselGit** [comment]
In what way is:

```dart
@data
class Person extends Mammal {
  final String name;
  final int age;
  
  const Person(this.name, {this.age = 0}) : 
    assert(age >= 0),
    super(species: "Homo Sapiens");
}
```

better than:

```dart
@data
class Person extends Mammal {
  const Person(
    final String name, {
    final int age = 0,
  }) :  assert(age >= 0),
         super(species: "Homo Sapiens");
}
```
?

**Comment by Levi-Lesches** [comment]
1. It allows you to incude non-field parameters in your constructor, and non-parameter fields: 

```dart
@data
class Product {
  String imageURL;  // not in the constructor
  List<Rating> ratings;  // also not in the constructor

  Product(final int id) :   // id isn't a field
    imageURL = "myWebsite.com/images/$id",
    ratings = MyAPI.getRatings(id);
}
```
If you tried that in your example, Dart would think that `id` is a field. In this example, that's not so bad, but the point is that _any parameter you define would also become a field_, which is not always desirable. Also, your syntax wouldn't allow you to assign to `imageURL`, since it wouldn't be included in the constructor and thus wouldn't be declared as a field. 

2. You can use the fields in other methods/getters: 
```dart
@data
class Product {
  final int id; 
  const Product(this.id);

  String get imageURL => "myWebsite.com/images/$id";
  
  List<Rating> getRatings() => [
    for (final Map json in MyAPI.getRatings(id)
      Rating.fromJson(json)
  ];
}
```

If you tried this in your example, the field `id` wouldn't actually exist until the macro's code is generated. That's fine if you want to work like that, but one of the design principles of macros is that they shouldn't affect code in any other way -- it should be like you hand-wrote the code yourself. If you decide you no longer want the `@data` macro, you may be surprised to find out that all your fields have disappeared too!

3. You can apply annotations to the fields
```dart
/// Collects properties that are used by the front-end
abstract class WebsiteEntity {
  String get imageURL;
}

@data
class Product extends WebsiteEntity {
  @excludeFromJson  // won't be included in .toJson()
  final int id; 

  const Product(this.id);

  @override
  String get imageURL => "myWebsite.com/images/$id";
  
  List<Rating> getRatings() => [
    for (final Map json in MyAPI.getRatings(id)
      Rating.fromJson(json)
  ];
}
```
  
3. Backwards compatibility/style. Your example has a totally different meaning in today's code than what you're suggesting. It also introduces two ways to create dataclasses, except using `@data` is slower and has the side-effects mentioned above. Not to mention veterans won't have to learn a whole new syntax for something they already do all the time. Being consistent on how to do things will keep the language concise and simple in the long run.

**Comment by danilofuchs** [comment]
Perhaps adding a keyword right before the constructor parameter to signal it should be interpreted as a class attribute?

Typescript has `public attr: Type` and `private attr: Type` shorthands.

I don't think public/private is the right thing with Dart, but still, this could solve the ambiguity issues

**Comment by rrousselGit** [comment]
> 1. It allows you to incude non-field parameters in your constructor, and non-parameter fields:


This is a very rare case. But you could do:


```dart
@data
class Product {
  Product._(
    final String imageURL,
    final List<Rating> ratings,
  );

  Product(int id)
    : this._(  // redirecting constructors are ignored
       imageURL: "myWebsite.com/images/$id",
       ratings: MyAPI.getRatings(id),
      );
}
```

> You can use the fields in other methods/getters:

What is the issue with getters/methods? [Freezed](https://pub.dev/packages/freezed) supports the following:

```dart
@freezed
class Person {
  factory Person(
    String firstName,
    String lastName,
  ) = _Person;

  String get fullName => '$firstName $lastName';
}
```

> If you decide you no longer want the @data macro, you may be surprised to find out that all your fields have disappeared too!

This is no different than if anything else. If you removed the `@data`, you would find out that your constructor is removed, and all the other methods like copyWith/toString/...

This is the nature of macros and is in not way specific to this approach.


> 3. You can apply annotations to the fields

You can apply annotations to parameters. This is how Freezed works today.

```dart
class Product {
  Product(
    @excludeFromJson int value,
  );
}
```

> Backwards compatibility/style. Your example has a totally different meaning in today's code than what you're suggesting.

I don't understand this point.
What has a different meaning?

> It also introduces two ways to create dataclasses, except using @data is slower and has the side-effects mentioned above. 

I don't understand this either. What are the two ways?

If anything, the current proposal is the one having this issue. See https://github.com/dart-lang/language/issues/314#issuecomment-890245982, clearly suggesting that we will need multiple annotations for macros

> Not to mention veterans won't have to learn a whole new syntax for something they already do all the time. Being consistent on how to do things will keep the language concise and simple in the long run.

The syntax I am suggesting is exactly how [Freezed](https://pub.dev/packages/freezed) works, which is used by many developer

On the other hand, what the current proposal suggests is a brand new syntax. It is not possible today to _not_ write a constructor, yet get named parameters & co.


On top of that, I would argue that my proposal is more consistent with the language. Because it reuse the syntax for named parameters, default values, asserts, super constructors, ...

Whereas the current proposal would require workaround to implement those. Meaning we would need either variants of `@data` or thing like `@positional` or @Assert(...)`, duplicating the language features.

**Comment by Levi-Lesches** [comment]
> If you removed the `@data`, you would find out that your constructor is removed, and all the other methods like `copyWith`/`toString`/...

Right, methods that are generated by the macro would obviously be removed, I was referring to the fields specifically, since it _looks_ like those are set manually, but really they are just specification for the code-gen to actually implement. In other words, when I see `final String name`, I'd be pretty surprised to find out my class doesn't actually have a field called `name`, with or without macros. 

> ```dart
> Product(int id)
>   : this._(  // redirecting constructors are ignored
> ```

My point here is that things like these seem too "magical". Maybe they fit a specific use-case, and that's why they're obvious to you, but it feels like the distinctions of what the macro is doing are unclear. That's specifically what macros are supposed to _avoid_. If they're going to have the tremendous power to overwrite hand-written code, they must set clear guidelines as to how they'll do it. Rules like "your fields aren't really fields" and "certain constructors are parsed but not others" aren't _obvious_, which they should be if they'll be implemented. 

Then again, like I said in #314, if you really do want to go down this road, you can -- just use a separate constructor: 
```dart
@dataFromConstructor
class Person {
  const Person._(  // is only used for code-gen purposes
    final String name, {
    final int age = 0;
  }): assert(age >= 0);
}

// generates: 
class Person {
  final String name;
  final int age;
  const Person(this.name, {this.age = 0}) : 
    assert(age >= 0);
}
```
That way, the _default_ isn't that macros will overwrite your code, but rather they are a tool to generate more code that fits the patterns you set for it.

**Comment by rrousselGit** [comment]
> Then again, like I said in #314, if you really do want to go down this road, you can -- just use a separate constructor:

Having to make all constructors private is a bit of a syntax downgrade though. And it would cause the analyzer to lint about dead code, since the constructor would never be referenced.

Say we want to define a private constructor, we'd need a mean to tell the generator to not remove the leading `_` somehow.

**Comment by bwilkerson** [comment]
> And it would cause the analyzer to lint about dead code, since the constructor would never be referenced.

I'm not arguing for one position or another, but I'll claim that we'll need to do something to make it possible for the analyzer to _not_ flag code as being dead when it's only used by a macro no matter how macros work.

**Comment by jakemac53** [comment]
Can we close this given https://github.com/dart-lang/language/blob/master/working/augmentation-libraries/feature-specification.md#augmenting-constructors? It is allowed for library augmentations and thus would be allowed for macros.

**Comment by rrousselGit** [comment]
Oh my~
Sure!
