### ISSUE TITLE
Macros and platform specific code?

### ISSUE THREAD

**Issue by jakemac53** [dart-lang/language#1791]
Should macros be able to generate platform specific code? How?

Existing code generators could generate platform specific imports, but that is the only real mechanism available. Should macros have a similar ability and what would that look like?

Should they be able to see the target platform and generate different code? How does that impact the IDE experience of viewing generated code?

**Comment by bwilkerson** [comment]
> Should they be able to see the target platform and generate different code? How does that impact the IDE experience of viewing generated code?

How is the target platform specified when analyzing in an IDE? (Do we even have that information available, and if so what would we need to watch for changes?)

**Comment by jakemac53** [comment]
> How is the target platform specified when analyzing in an IDE? (Do we even have that information available, and if so what would we need to watch for changes?)

Right this is a major concern I would have with allowing macros to generate code differently. The analyzer only analyzes the code once with some sort of an agnostic platform I think? It isn't clear how the user would indicate the platform to analyze and generate macros with.

**Comment by bwilkerson** [comment]
> The analyzer only analyzes the code once with some sort of an agnostic platform I think?

How do other platforms know the platform? Is it a "defined variable" (provided on the command-line using `--D=`)? If so, then yes, the analysis server currently has no way to specify that. (The command-line analyzer used to, but I think we might have lost that when we moved to `dart analyze`.) We could consider adding something to the analysis options file, but it isn't a great user experience to have to hand edit that file and then wait for everything to be re-analyzed before seeing the effect.

This is similar to the conditional imports support, and I had some other ideas at the time we added it, but they were all deemed to be too expensive to implement and so they weren't. Depending on how important a use case this is we might want to reconsider some of those ideas.

**Comment by jakemac53** [comment]
> How do other platforms know the platform?

It depends on the CLI you are using to compile - it is either implied by that (for flutter its known to be flutter), or its passed via some other config (typically a command line option `--target=<name>`).

**Comment by Levi-Lesches** [comment]
> Should they be able to see the target platform and generate different code? How does that impact the IDE experience of viewing generated code?

Focusing only on the user-side for a second, it seems like this will lead to scenarios where the code devs are seeing is not the code that's actually running. Even if the IDE can simulate different platforms, they'll either 1) recompile to see the effects or 2) forget to switch platforms and miss the new code, leading to frustration. The way conditional imports are done today is nice because it shows all possible paths in the code. If macros could bypass that by controlling what the code looks like, that could lead to trouble. 

Also, the whole point of source code is that it tells the humans what's going on. Devs need to know what will happen to their programs on _all_ platforms. If it's the _compiler_ that cares about just the target platform, this should be a language feature in general, that macros just happen to be able to use (but not made specifically for them).

**Comment by lrhn** [comment]
My initial hunch is that I'd prefer to allow macros to insert configuration specific imports, but not to generate different code depending on knowing the target.

However, just having configuration specific imports is already sufficient to do have different macros for different platforms.

```dart
import "my_macro_default.dart" 
  if (dart.library.ui) "my_macro_flutter.dart"
  if (dart.library.io) "my_macro_vm.dart"
  if (dart.library.js) "my_macro_js.dart";
  show MyMacro;

@MyMacro("doit")
class C {}
```

Here the compiler should choose the applicable import, then apply the macro imported from there. If you have different `MyMacro` definitions for different platforms, you can generate platform specific code.

That also requires the platform to be *known* and the "environment" variables to be available at macro execution time.

So, I see no harm in also allowing a single macro to generate different code depending on whatever information is available (it can check `const bool.fromEnvironment("dart.library.js")` directly if it wants to).


The only way I can see to prevent this is to disallow a macro annotation from depending on any configuration dependent import (so the library declaring the annotation class, and the libraries declaring the values of any annotation constructor arguments cannot transitively have any configuration dependent import). Not sure that's a restriction worth making, and you'd also have to block access to the `fromEnvironment` constructors. If we add too many restrictions to macro code, we're essentially introducing a *new* (sub-)language instead of actually using Dart.

**Comment by jakemac53** [comment]
> However, just having configuration specific imports is already sufficient to do have different macros for different platforms.

Interesting point! This actually gets pretty weird potentially though. When the macro is actually expanded, it is presumably running on the VM (or at least that is how we have discussed it in the past). So it will see _different_ conditional imports at that point. It likely also is going to not have some of the normal libraries available (dart:io, etc), so it won't even match exactly a normal VM context.

It seems like possibly the user code could use conditional imports to import a different macro, but the macro itself wouldn't be able to use conditional imports to generate different code. Unless we explicitly specify some other behavior at least.

> So, I see no harm in also allowing a single macro to generate different code depending on whatever information is available (it can check `const bool.fromEnvironment("dart.library.js")` directly if it wants to).

We still have all the usability concerns of a macro generating different code. In the analyzer today it will just choose the default import afaik, and always use that. So that means the generated code the user sees won't necessarily match the _actual_ code from the macro. This would also make debugging broken most likely, etc.

> The only way I can see to prevent this is to disallow a macro annotation from depending on any configuration dependent import (so the library declaring the annotation class, and the libraries declaring the values of any annotation constructor arguments cannot transitively have any configuration dependent import).

Well as I mentioned above another choice is to treat those imports based on the context in which the macro is running, and so they would always end up choosing the imports available to macros at runtime. They wouldn't be able to see the target platform.

> Not sure that's a restriction worth making, and you'd also have to block access to the `fromEnvironment` constructors. If we add too many restrictions to macro code, we're essentially introducing a _new_ (sub-)language instead of actually using Dart.

Ya, I realize now it is worrisome to expose _any configuration_ at all to macros, for the same reason of the generated code that we show the user not matching the generated code actually being ran. :/

**Comment by bwilkerson** [comment]
> In the analyzer today it will just choose the default import afaik ...

Correct. The analyzer support for conditional imports is very limited.

> Ya, I realize now it is worrisome to expose _any configuration_ at all to macros, for the same reason of the generated code that we show the user not matching the generated code actually being ran.

I agree. I don't know how we'd keep the analyzer's notion of platform consistent with what the user is running. I suspect that the analyzer  would need to generate for all possible platforms and then have some way to match up the executing platform dynamically. This definitely isn't supported today and would likely be a significant effort to support.

@devoncarew @scheglov for visibility.

**Comment by munificent** [comment]
I understand that doing it well is a hard problem, but I *do* think platform-specific or configuration-specific code of some kind should fall under the aegis of static metaprogramming. One of the use cases the Flutter team has repeatedly raised is the ability to write debug-only code that disappears in the released executable. That includes field declarations for storing debug state that are completely eliminated in release builds.

We don't necessarily have to solve that *with macros*, but I think we should have some ability to address that with the set of changes we're planning around static metaprogramming. Dart aims to be a multi-platform client-side language. The most successful language I know in that area is C++ and C++ does that in part because the preprocessor makes it pretty easy to write code that does one thing on one platform and something else on another.

**Comment by jakemac53** [comment]
Fwiw we could just support an equivalent of ifdef. That would not only allow macros to produce platform specific code all in a single file (eliminating some of these other concerns), but it would also allow users to do the same.

Is there any particular reason we want to stray away from that tried and true approach? Ya its kind of gross visually, but it works,  its clear what is going on, and you can set breakpoints that make sense in any configuration (they may never be _hit_ on some configurations, but the _locations_ make sense).

**Comment by munificent** [comment]
I'm definitely not morally opposed to supporting `ifdef`. (I vaguely recall bringing it up back in the early days of the discussions around conditional imports.) It still has all of the user-experience challenges of any kind of config-specific code. There's no longer a configuration-independent static view of the program. There are multiple programs that can vary in arbitrary ways between configurations. That's not necessarily a bad thing, just a UI challenge (that C++ IDEs have mostly solved).

For `ifdef` in particular, the main challenge is grammatical. I don't think we want something like the C preprocessor where you can't even *parse* a file until after the ifdefs have been applied. Fixing that would mean defining precisely where `ifdef` and `endif` slot into the grammar. Not intractable, but sort of an odd syntax design problem. Little known fact, but C# [has a few preprocessor directives](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/preprocessor-directives) that I think are more constrained than the C preprocessor, so there may be some prior art we can use.

**Comment by jakemac53** [comment]
I think we have pretty much decided not to try and address platform specific code with macros directly - instead this should be provided by some other feature which both macros and hand-authored code can use. Closing for now at least :).
