### ISSUE TITLE
Finally block not executed in synchronous generator

### ISSUE THREAD

**Issue by jobfeikens** [dart-lang/language#1792]
In the following example, the finally block doesn't get called. When I change "sync*" into "async*" however, the finally block does get called.

```
void main() {
  generate().first;
}

dynamic generate() sync* {

  try {
    for (var i = 0; i < 3; i++) {
      print('yield');
      yield i;
    }
  } finally {
    print("finally");
  }
}
```

**Comment by julemand101** [comment]
Not sure if it is even possible to detect that as things are right now? `sync*` returns a `Iterable` which does not have any concept of `close()` (compared to `async*` which returns a `Stream`). So the only way to "close" the `Iterable` right now would be to take all elements (if you instead of `.first` uses `.last`, then "finally" is printed). But that is a lot of wasted resources if `.first` needs to throw away all elements from the `Iterable` (which might not even be possible if the `Iterable` is endless).

You could implement `close()` on `Iterable` but I think that would be a major change.
