### ISSUE TITLE
HashMap duplicates

### ISSUE THREAD

**Issue by Jamminroot** [dart-lang/language#1793]
>Describe the problem you are trying to solve, why is it hard to solve today?

Adding keys\values to `HashMap<String, List<String>>` in my app causes duplicates to be added.

The problem seem to be somewhere within ContainsKey \ PutIfAbsent and similar methods - they behave as if key is not in the collection, even though it is.

Can't provide a repro as sample CLI application I made (adaptation of my case) does not show the issue.

Sample code of a repro would be something like this:

```dart
class BaseClass {
  HashMap<String, List<String>> values = HashMap.identity();
}

class TestClass extends BaseClass {
  TestClass.fromRWL() {
    Map<String, dynamic> map = {
      "params": {
        "paramName": ["value1", "value2"]
      }
    };
    HashMap<String, List<String>> values = HashMap.identity();

    (map['params'] as Map<String, dynamic>).forEach((key, value) {
      values.putIfAbsent(key, () => (value is List<dynamic> ? value.map((e) => e as String).toList() : List.generate(1, (i) => value)));
    });

    var vars = 0;
    for (var variant in values.values) vars = max(vars, variant.length);
    var args = ["paramName"];

    for (var arg in args) {
      if (!values.containsKey(arg)) {
        values.putIfAbsent(arg, () => List.generate(vars, (index) => ''));
      }
    }

    print(values);
  }
}
```

Note `values` being repeated. I thought that that might be the issue, but no, that's not it - and code above works just like one would expect it.
I do realize that `!values.containsKey(arg)` is not necessary as `putIfAbsent` _should_ handle it, but, well...

What I did to confirm the problem:

```dart
    for (var arg in args) {
      if (!values.containsKey(arg)) {
        print('Adding entries for $arg, ${arg.runtimeType} hash=${arg.hashCode}');
        print('Probing keys already in the map: ');
        for (var existingKey in values.keys) {
          print('Existing key: $existingKey ${existingKey.runtimeType} hash=${existingKey.hashCode}, equals to arg: ${existingKey == arg}');
        }
        values.putIfAbsent(arg, () => List.generate(vars, (index) => ''));
      }
    }
    print(values);
```

Sample console output:

```console
flutter: Adding entries for Solution, String hash=239232507
flutter: Probing keys already in the map: 
flutter: Existing key: Solution String hash=239232507, equals to arg: true
flutter: {Solution: [], Solution: [Cpp_RnD.sln]}
```

I can provide some pieces of code upon request though or share access to the app I'm messing around with - for now it's in private repo.

Original issue: https://github.com/flutter/flutter/issues/87810

**Comment by julemand101** [comment]
I am rather confused about what your actual problem is. But are you sure you really want to use `HashMap.identity()` to construct your `Map`? If you are using this, the equality of keys is only based around the exact same object instance and not the actual value inside each object.

For Strings, that is not necessary the case that two String objects containing the same String value points to the exact same object instance. The only case where this is kinda a guarantee if you are using the same String constant value multiple times in your code. But if you are getting the String from outside, this value is not necessary the same object instance as the String constants in your code.

You should really just use `Map()` or `HashMap()` to create your Map. Using `HashMap.identity()` can ends up making your program a lot more confusing. Especially when using `String` objects as key.

**Comment by Levi-Lesches** [comment]
To add on to @julemand101, try this: 
```dart
bool checkForKey<K, V>(HashMap<K, V> map, K key) {
  for (final K otherKey in map.keys) {
    if (identical(otherKey, key)) return true;
  }
  return false;
}
```
Basically, using `identical()` instead of `==`. I believe you'll get false in your examples.

**Comment by lrhn** [comment]
I concur. Using a `HashMap.identical` with `String` keys is asking for trouble. Just use a plain `HashMap`.
Printing the string's `hashCode` doesn't matter since the identity map uses `identityHashCode` instead.

We almost promise that string *literals* are canonicalized (but not really - #985), and we definitely don't promise anything about any other way to create strings (like, say, JSON parsing).

Can you say why you chose to use `HashMap.identical` to begin with?

**Comment by Jamminroot** [comment]
You are right. For some reason I thought that `HashMap.identity()` creates an empty growable HashMap similar to `List.empty(growable: true)`. Using regular constructor resolved the problem.
I'm closing the issue,  thanks for a quick reply!
