### ISSUE TITLE
Can a generic method be torn off of a dynamic expression if it declared in an extension of Object

### ISSUE THREAD

**Issue by srawlins** [dart-lang/language#1794]
The [constructor tearoff spec](https://github.com/dart-lang/language/blob/master/accepted/future-releases/constructor-tearoffs/feature-specification.md) says:

> We do not allow _dynamic_ explicit instantiation. If an expression _e_ has type `dynamic` (or `Never`), then `e.foo<int>` is a compile-time error for any name `foo`. (It'd be valid for a member of `Object` that was a generic function, but none of the `Object` members are generic functions). It's not possible to do implicit instantiation without knowing the member signature.

So, what if there exists a generic extension method on `Object`?

```dart
extension on Object? {
  void m<T> {}
}

f(dynamic d) {
  d.m<int>; // Could this be allowed?
}
```

The spec follows this rule with an alternative:

> (Possible alternative: Allow it, and handle it all at run-time, including any errors from having the wrong number or types of arguments, or there not being an instantiable `foo` member. We won't do this for now.)

**Comment by lrhn** [comment]
It's not allowed, and won't work with implicit tear-off either. 
The type `dynamic` is considered as having all members itself, so the extension method does not apply. It doesn't matter what the extension is defined on, because there *could be* an instance method on the object itself with the same name, and that one should win. So, you can never access extension members on something typed `dynamic`.
You'd get a run-time error for `void Function() f = d.m;` too because it doesn't implicitly instantiate the function tear-off, and then it attempts to assign a generic function value to a non-generic-function-typed variable.

*However*, if we choose to allow instantiation of function *values* (can't find an issue, might be just something we've discussed offline), *and* we further allow instantiating a value typed as `dynamic` at run-time, then it would make sense to also allow `d.m<int>` to work the same as `(d.m)<int>`. That's a lot of "if"s.

If you cast `d` to `Object?`, then it does work.

**Comment by eernstg** [comment]
@lrhn wrote:
> if we choose to allow instantiation of function _values_

We had a discussion in email, but it can also be seen as a revisit to https://github.com/dart-lang/language/issues/1604, plus the implicit case (where the context type is used).

**Comment by srawlins** [comment]
Ah good points. Thanks much!
