### ISSUE TITLE
should support a way than declare abstract async method?

### ISSUE THREAD

**Issue by Silentdoer** [dart-lang/language#1796]
such as:
```dart
abstract class A {
  void init() async;
}

**Comment by Silentdoer** [comment]
can use this : `FutureOr<void> init();`

**Comment by eernstg** [comment]
Note that you don't need an abstract `async` declaration: Just declare an abstract method and use `async` on any overriding declaration that needs to be `async`. (The modifier `async` changes the meaning of the body of a declaration, it doesn't change the method at all as seen from a caller.)

But you'd probably have this (because an `async` method returning `void` is a very special case: "fire and forget"):

```dart
abstract class A {
  Future<void> init();
}

class B implements A { // For example.
  Future<void> init() async { ... }
}
```
