### ISSUE TITLE
Do extension methods capture static type parameters or runtime type parameters (or both)

### ISSUE THREAD

**Issue by leafpetersen** [dart-lang/language#180]
The static extension method feature proposed in #41 likely allows extensions to reference the generic type parameter of the class (it's almost certainly not useful otherwise).  For Dart, which has reified generics, a key question is whether the type parameter which is captured is the static type parameter, or the runtime type parameter.  [In discussion](https://github.com/dart-lang/language/issues/41#issuecomment-447765602), it has been pointed out that the latter might be very useful.  This issue is to discuss the implications and mechanisms involved.

 Concretely, suppose I have the following:

```dart
class Ref<T> P
  T _value;
  Ref(this._value);
  T get value() => _value;
  set value (T x) => _value = x;
}
```

And suppose I defined an extension as follows:

```dart
extension CloneRef<T> on Ref<T> {
  Ref<T> clone() => Ref(this.value);
  Ref<T> cloneWith(T x) => Ref(x);
}
```

Now consider the following code:

```dart
  void test() {
    Ref<num> r1 = Ref<int>(3);
    Ref<num> r2 = r1.clone();
    r1 = r2 as Ref<int>; // (1)
    r2.value = 3.0; // (2)
    Ref<num> r3 = r1.cloneWith(3.0); // (3)
  }
``` 

If extension methods capture the static type of the receiver only, then the runtime (reified) type of `r2` and `r3` is `Ref<num>`, and:
   - line (1) will be a failed runtime cast
   - lines (2) and (3) will succeed.

If extension methods capture the dynamic type of the received, then the runtime (reified) type of `r2` and `r3` is `Ref<int>`, and:
  - line (1) will succeed
  - lines (2) and (3) must be arranged to fail for soundness.

The simple operational model of extension methods is to treat them as syntactic sugar for application of a static function.  For this example, we would have something like the following de sugaring:

```dart
class CloneRef {
  static Ref<T> clone<T>(Ref<T> this) => Ref(this.value);
  static Ref <T> cloneWith<T>(T x) => Ref(x);
}
```

If we treat extension methods as capturing the static type, then the following de-sugaring of the test code is valid:

```dart
  void test() {
    Ref<num> r1 = Ref<int>(3);
    Ref<num> r2 = CloneRef.clone<num>(r1);
    r1 = r2 as Ref<int>; // (1)
    r2.value = 3.0; // (2)
    Ref<num> r3 = CloneRef.cloneWith<num>(r1, 3.0); // (3)
  }
``` 

If we wish to treat extension methods as capturing the runtime type, then we need some additional mechanism, akin to the runtime checks that are required for checked covariant generics.  It's plausible (but I don't think entirely clear to me yet) that this can be done entirely via caller side checking, using something like an "open type" mechanism which captures the runtime generic type parameter.  In that case, we can use the same de-sugaring of the extensions themselves, but the code which uses them must be de-sugared into code which opens the object and potentially performs runtime checks.

```dart
  void test() {
    Ref<num> r1 = Ref<int>(3);
    Ref<num> r2 = 
     open r1 as Ref<T> rt in CloneRef.clone<T>(rt);
    r1 = r2 as Ref<int>; // (1)
    r2.value = 3.0; // (2)
    Ref<num> r3 = 
      open r1 as Ref<T> rt in CloneRef.cloneWith<T>(rt, 3.0 as T); // (3)
  }
``` 

Notice the additional runtime cast required on the argument to `cloneWith`.  In some cases, a similar runtime cast might be required on returned values as well.

It's plausible that these checks could be done on the callee side as well, I'll have to think through what the encoding would be.

**Comment by leafpetersen** [comment]
cc @lrhn @munificent @eernstg

**Comment by eernstg** [comment]
I'd actually expect the very last occurrence of `num` need to be `T` (`CloneRef.cloneWith<T>(rt, 3.0 as T)`), because, in the original expression `r1.cloneWith(3.0)`, `cloneWith` is not a generic method, it gets the value of `T` from the dynamic type of the receiver. Would that be compatible with your thinking?

**Comment by eernstg** [comment]
Here's a reason for wanting the type argument passed to `cloneWith` to be `T` rather than `num` (even though the usual preference given to the context type might dictate the latter), namely the perspective where the extension methods are handled by a companion object:

```dart
// Desugared extension.
class CloneRef<T> {
  static Ref<T> clone(Ref<T> this) => Ref(this.value);
  static Ref <T> cloneWith(T x) => Ref(x);
}

 void test() {
    Ref<num> r1 = Ref<int>(3);
    CloneRef<num> cr1 = ...; // Compiler-generated, yields a `CloneRef<int>`.
    Ref<num> r2 = cr1.clone(r1);
    r1 = r2 as Ref<int>; // (1)
    r2.value = 3.0; // (2)
    // `r1` not modified, can reuse `cr1`.
    Ref<num> r3 = cr1.cloneWith(r1, 3.0); // (3)
  }
```

**Comment by eernstg** [comment]
Note that there is a proposal for how to deal with type patterns (#170), and in particular that it ensures that if a pattern _P_ matches a type _T_ and _S <: T_, then _P_ matches _S_, and it will bind type variables introduced by _P_ to values which have the expected relationship to the bindings resulting from a match with _T_, and which also has the soundness property that the matched type (here: _T_ or _S_) is a subtype of the matching type (that is, the type _[U<sub>1</sub>/X<sub>1</sub> .. U<sub>s</sub>/X<sub>s</sub>]P_, where `X<sub>j</sub>`, 1 <= j <= _s_ are the type variables introduced by _P_ and _U<sub>j</sub>_ the corresponding binding produced by the match). I believe that these properties are highly relevant to the discussion about the soundness of the resulting language mechanism.

**Comment by leafpetersen** [comment]
It would be worth looking into whether this comes up in C#, and if so how they deal with it.

**Comment by lrhn** [comment]
If we match partial function types, then it's possible that the actual type is a supertype of the static type.
```dart
extension Unary<R, T> on R Function(T) {
  void before(T function(T) intercept) => (T value) => super(intercept(value));
  void after(R function(R) intercept) => (T value) => intercept(super(value));
}
```
So:
```dart
int foo(Object o) => o.hashCode;
num Function(num) f = foo;
f.before((x) => x); /// static inference would type x as num Function(num)
f.after((x) => x); /// static inference would type x as num Function(num)
```
Here we pass a `num Function(num)` to something expecting `Object Function(Object)` or an `int Function(int)`. That will blow up in either case. So, we must recognize that calling the `before` and `after` functions are not safe. 

This is not new for `after`, it's a classical covariant type argument, and we get the same effect for classes.

For `before`, our type variable is contravariant (and still used invariantly). I don't know if we have anything like it already.

So, we can definitely do unsafe things. The big question is whether we can predict where the unsafeness occurs and insert checks statically, or whether we'll have to check everywhere.

**Comment by eernstg** [comment]
> extension Unary<R, T> on R Function(T) ...

This has a structure which is similar to the one that we have outlawed (where a superinterface in a class declaration uses a type argument in a contravariant or invariant position, https://github.com/dart-lang/language/issues/39), so we should certainly not aim at enforcing the usual discipline on class types where a static typing situation involving `Unary<R0, T0>` is assumed to be associated with a dynamic environment where the corresponding type variable values `R` and `T` are subtypes (`R <: R0` and `T <: T0`).

But we already have a similar situation with a type alias: The type parameter `T` "is contravariant", and such a type parameter could also "be invariant", and at run time we would have `R <: R0` and `T :> T0`. 

This means that the _parameter_ type `T` of `intercept` in `before` is an example of using a contravariant type parameter in a covariant position (which is unsafe), and similarly for the _return_ type `R` of `intercept` in `after`.

So we shouldn't have any particular problems detecting the unsafe cases, and doing whatever we want about them.

The situation where inference comes up with a result that will cause a dynamic error if there is any non-trivial subsumption is also something we have looked at earlier (https://github.com/dart-lang/linter/issues/1133). I think we ought to be able to flag such situations (maybe always, maybe just as a lint), and offer some sort of invariance support such that developers can take away the variance that causes the problem.

(We haven't discussed having the ability to declare that a function has a type like `num Function(exactly num)`, but we could allow that, if we insist that these unsafe constructs must be allowed, and it should be possible to make them statically safe).

**Comment by lrhn** [comment]
Yes, the point of the examples were to show that a naïve approach would introduce type-unsoundness that had to be detected and guarded against.

I think Erik's approach of disallowing contravariant cheating like this is likely simpler. 

Another option is to fail early if the captured type parameter is actually used invariantly, and the run-time type doesn't match the static type. That would mean failing immediately when calling the extension method that requires a run-time type that is both a supertype and a subtype of the static type.

Just using the static type is an option, but not a particularly good one (and we still need to introduce open-type functionality anyway).

**Comment by natebosch** [comment]
Some of this discussion is a bit over my head. I have a concrete example that may be impacted by this decision. Handling types with `StreamTransformer` has traditionally given headaches since one of it's generics is for an argument type, and the other a return type.

Here is an extension I'd like to be able to write. Will the decision made in this issue have an impact on my ability to write it?

```dart
extension WhereType<T> on Stream<T> {
  Stream<R> whereType<R>() => super.transform(
          StreamTransformer<T, R>.fromHandlers(handleData: (e, sink) {
        if (e is R) sink.add(e);
      }));
}
```

When I attempt to write this today as a method returning a `StreamTransformer` I'm pushed into a worse API:

```dart
StreamTransformer<T, R> whereType<T, R>() =>
    fromHandlers(handleData: (v, sink) {
      if (v is R) sink.add(v);
    });

// usage
numbers.transform(whereType<num, int>());
```

What I would like is:

```dart
numbers.transform(whereType<int>());
```

However I can't get that. If I return a `StreamTransformer<dynamic, int>` I get a static error because `StreamTransformer<dynamic, int>` is not a `StreamTransformer<num, int>`, and if I return a `StreamTransformer<Null, int>` I get a runtime error because a `Stream<num>` is not a `Stream<Null>` in the call to `bind()`.

**Comment by lrhn** [comment]
The problem with stream transformers is precisely what I was talking about, and I think my solution works:
```dart
StreamTransformer<Null, T> whereType<T>() => _WhereTypeTransformer<T>();

class _WhereTypeTransformer<T> extends StreamTransformerBase<Null, T> {
  Stream<T> bind(Stream<Object> stream) async* {
    await for (var value in stream) if (value is T) yield value;
  }
}
```

You can test the code in [DartPad](https://dartpad.dartlang.org/71b4ac4f930b5e4ec8da22d0c8d5146e).

This hack, a `Null` generic type and an `Object` method parameter type, only really works when the transformer works for *all* objects. It's not possible to put any upper bounds on the source stream type that are statically detected.

**Comment by lrhn** [comment]
This is exactly one of the cases where a method on the object can do things that an external method cannot, because the instance method has access to the *concrete* type argument. It can create something that has the "exact type" needed for invariant constraints. Any external function cannot. If we want extension methods to be able to do everything instance methods can, then they need access to the actual type parameters too.

**Comment by munificent** [comment]
For what it's worth, here is my current take on this:

1. I do think it is important to have functionality to crack open an object and extract its runtime type argument. During the 2.0 migration, we had to add a hacky dart_internal library to expose this for Iterable<T> and Map<K, V> precisely because we had very compelling use cases. Obviously, to get rid of that hack, we need a real language (or maybe library) mechanism to do this.

2. I think you should be able to access the above mechanism within the body of a method. In other words, you shouldn't have to define a special method whose parameter signature is where the magic happens.

3. My limited understanding is that exposing type patterns in the signature of an extension method doesn't add any expressiveness compared to using the type pattern inside the body of the extension method.

    That's probably not clear. By analogy, let's talk about union types. If you want a function that accepts either a number or a string, you can today do:

    ```dart
    function(Object numberOrString) {
      if (numberOrString is num) {
        print("number");
      } else if (numberOrString is String) {
        print("string");
      } else {
        throw ArgumentError();
      }
    }
    ```

    This has the desired runtime behavior. But the static experience isn't
    great:

    ```dart
    function(true); // Not a number or a string.
    ```

    There's no static error here. So even though we can write code inside the body of the method to do what we want, the fact that it's not visible in the signature compromises the experience.

    As far as I know, disallowing type patterns in extension methods does not have this problem. Because it's all about grabbing the *runtime* type argument, the static shape is the same either way.

4.  I expect *not* supporting extracting the runtime type in extension methods to lead to a strictly simpler and more shippable feature.

1 and 2 imply that even if extension methods *can* grab runtime type parameters, we'll need *another* feature to let us do the same inside the body of a method. 3 implies that using that latter feature inside extension methods is just as good as direct support for it in extension methods. 4 implies that doing both has a cost.

All of those imply to me then that supporting grabbing the runtime type argument in extension methods isn't worth the cost. Instead, I think it makes more sense to keep it a relatively simple purely static feature, and rely on some sort of type pattern system at the statement level for the rare cases where you need it.

**Comment by natebosch** [comment]
> rely on some sort of type pattern system at the statement level for the rare cases where you need it. 

Can you give a straw man for what that might look like and how it solves the `whereType` use case?

**Comment by munificent** [comment]
This syntax is totally made up, but something along the lines of:

```dart
extension WhereType<T> on Stream<T> {
  Stream<R> whereType<R>() {
    match (this) {
      case Stream<var S>:
        return transform(
            StreamTransformer<S, R>.fromHandlers(handleData: (e, sink) {
          if (e is R) sink.add(e);
        }));
      default:
        throw "Unreachable";
    }
  }
}
```

**Comment by eernstg** [comment]
@munificent wrote:
> type patterns in the signature of an extension method doesn't
> add any expressiveness compared to using the type pattern
> inside the body of the extension method

That is not quite true. When the actual type arguments are in scope for the extension as a whole (rather than in a scope nested inside the body of each extension method), it is possible to use those type arguments in the signature of the extension method. I'll use type patterns as specified in #170 to illustrate this.

An example where that makes a difference is when we have an exact type, and we are constructing an entity (here: a function) whose type has non-trivial variances (the argument type is contravariant):

```dart
class Pair<X, Y> {
  final X x;
  final Y y;
  Pair(this.x, this.y);
}

extension Pairing on var X {
  Pair<X, X> Function(X) pairWithMe() => (X other) => Pair(other, this);
}

main() {
  Pair<String, String> Function(String) f = "Hello".pairWithMe();
}
```

In this example, we can safely assign the returned function to a variable whose signature is exactly the statically known signature from the extension method. This gives us a "tight" typing, and we know that both static and dynamic checks will help us using that function only with string arguments.

Currently this only arises with exact types, but we might very well get support for some kind of invariance (for instance, #229), and this allows us to achieve similar benefits for type arguments:

```dart
extension Adding on List<var X> {
  void Function(X) addToMe() => add;
}

void Function(X) foo<X>(List<invariant X> xs) => xs.addToMe();

main() {
  List<invariant num> xs = [];
  void Function(num) f = foo(xs);
  f(3.25);
}
```

In this code there are no dynamic type checks. In contrast, if we only match statically in `Adding` then the attempt to return the tear-off of `add` would fail whenever `addToMe` is added and the dynamic type argument of the list is actually a subtype of the statically known one (so that would mean that we can _only_ call `addToMe` when we have obtained an `invariant` type on the list).

Alternatively, we could allow invocations on receivers of type `List<T>` for some type `T` (rather than `List<invariant T>`) by using the return type `void Function(Null)`. But that function type is not handled well in Dart (an over-eager static check is applied, so we basically only get to call it if we cast the function to `dynamic` and then perform a dynamic invocation).

In other words, the distinction between being able or unable to refer to the actual type arguments in the signature of extension methods makes a difference as soon as we consider

- code where a receiver uses covariance and hence some dynamic checks are inserted, along with
- code where invariance or similar devices are used to achieve full static safety.

I think that's a relevant consideration for Dart, certainly when features like invariance are new (and lots of code hasn't yet been adapted to use it), but also in the long run, because some objects may be used in a mostly read-only fashion, in which case it may be a perfectly meaningful trade-off to use covariance and accept a dynamic check in a couple of situations (and those situations could of course also be made statically safe with dynamic checks like `if (x is List<var X extends Whatever>) ...`).

**Comment by eernstg** [comment]
Here's a more compact example with direct emphasis on a contravariantly typed member (such that we don't need to consider things like tear-offs and parameters that are covariant-by-class):

```dart
class C<X> {
  void Function(X) f;
  C(this.x);
}

extension Foo on C<var X> {
  void Function(X) foo() => f;
}
```

If we match the type pattern statically then an invocation `c.foo()` where the statically known receiver type is `C<num>` and the dynamic receiver type is `C<int>` will have static type `void Function(num)`, and the dynamic type will be `void Function(int)`, so we have a soundness hole or we add a caller side check, which will throw in case there is any difference between the statically known type argument of `C` and the dynamic one. This is based on a static choice of the value of `X`, and there is really no way to make that safe because `X` is detached from the list.

Alternatively, if we match the type argument dynamically then the receiver type is `C<num>` which actually means `exists X <: num. C<X>` in Dart, and this means that the type of the invocation `c.foo()` will be `exists X <: num. void Function(X)`. This type can be approximated soundly by `void Function(Null)`, and that would allow us to, say, assign the returned value to a variable of type `Function` (no checks needed), or assign it to a variable of type `void Function(int)` (with a dynamic check, which would succeed in this case).

So the static matching essentially forces us to forget the existential properties of the type, and this means that we cannot soundly select an upper bound of the type of any expression involving a "member with a contravariant type". With the dynamic matching we preserve the static knowledge that the receiver and the extension method signature are connected, and that allows us to preserve more precise typings.

**Comment by tatumizer** [comment]
@eernstg : could you please illustrate the last `C<X>` example with the code (including the soundness hole part)? That is, the example of the caller code where potential problem manifests itself, allowing to break type constraints, and how having "var X" solves this problem.

**Comment by eernstg** [comment]
@tatumizer wrote:
> please illustrate the last `C<X>` example with the code

It's all about the treatment of the invocation `c.foo()`, so there isn't much additional code:

```dart
class C<X> {
  void Function(X) f;
  C(this.x);
}

C<num> c = C<int>((int i) {});

extension Foo on C<var X> {
  void Function(X) foo() => f;
}

var x = c.foo();
```

However, the point is that we may have different choices for specifying what that invocation of `foo` _means_.

If we use static type pattern matching then the extension amounts to a thin layer of syntactic sugar. In this case the meaning of an extension is a set of top-level functions, and call sites will just move the receiver from being in front (like `e.f(...)`) to the first parameter position (like `f(e, ...)`). Type parameters of the extension will be type parameters of each of the top-level functions, and they will be chosen by type pattern matching on the static type of the receiver. So we get the following desugared code (skipping class `C` and variable `c`, which are the same each time):

```dart
void Function(X) Foo_foo<X>() => f;
var cf = Foo_foo<num>(c);
```

With this design, the type returned by the extension method is `void Function(num)`. This means that the body of the method will throw (because it tries to return a value of type `void Function(int)`, which is not a subtype of the return type.

What I'm pointing out here is that the semantics of the program is not correctly represented by the static analysis, because it got lost along the way that the receiver has type `exists T <: num. C<invariant T>`, but it was taken to have the type `C<invariant num>` (we need to use invariance because the whole point is that this `T` is _precisely_ the type argument of the dynamic type of `c`).

It is not a soundness problem that the program throws, but it indicates that we get a lower quality of service. ;-)

When I mentioned the soundness problem I was referring to the hypothetical solution where we allow that `Foo_foo` invocation to return a `void Function(int)`.

But we do not have to tolerate this quality-of-service problem. It's a little bit like saying "Let's sign a contract. You promise that `x < 100`, and I'll build a house for you". Then at run-time we have `x == 99`, and then the contractor turns on us and says "Oh, but I assumed `x == 100`, so now I won't build the house". That's unfair. ;-)

With dynamic type pattern matching we will have the following semantics. We can still desugar each extension method to a top-level function, and the type variables introduced in the type pattern of the extension are type parameters of that function (followed by the user-declared ones, in case the extension method is generic). But the dynamic matching of the type pattern must be expressed explicitly, and that's not a feature that Dart has currently.

```dart
void Function(X) Foo_foo<X>() => f;
var cf = let v = c in Foo_foo<v@C.X>(v);
```

You might think of `v@C.X` as a path dependent type. Of course, Dart does not have path dependent types (introduced [here](https://dl.acm.org/citation.cfm?id=680013), formalized [here](https://dl.acm.org/citation.cfm?id=1111062) and in the development of [Scala](http://lampwww.epfl.ch/~amin/dot/fpdt.pdf)), but we can just think of type variables as final members of objects and then looking up the actual value of the type argument `X` of an instance of `C` could be written as `v@C.X`. We have to say which class we want to use because we could have things like `class B<X> extends A<List<X>> {}`, and then we could have a `b` with type `B`, and `b@B.X` could be `num` whereas `b@A.X` could be `List<num>`.

This means that the statically known return type of the invocation would be `void Function(v@C.X)`. But given that we don't want to allow deep excursions into dependent types we will make a sound approximation to that type and never allow the dependent types to exist beyond each single step of the type analysis. The static knowledge we have is that `v@C.X <: num`, but this means that the best sound approximation (supertype) is `void Function(Null)`. So that's the inferred type of `cf`.

With that, we get a successful extension method execution, and we preserve soundness. The resulting function could then be invoked:

```dart
void bar(void Function(int) g) => g(42);

main() {
  bar(cf); // Downcast `void Function(Null)` to `void Function(int)`: succeeds.
}
```

So my point is that we can preserve a more precise static analysis by using dynamic type pattern matching _and_ running a static analysis which takes this fact into account, and the alternative (static type pattern matching) leaves the programmer with something that basically corresponds to broken promises.

**Comment by tatumizer** [comment]
@eernstg : I think I understand it now. Whether I fully understand or only partially understand is not quite clear at that point - most likely, the latter :-)

Let's forget for a second about extensions, invariant types etc, and consider a simple example.
```
class Bird {
}
class Duck extends Bird {
}
class C<X> {
  X Function(X) f = (X x)=>x;
}
main() {
  var c_of_duck = C<Duck>();
  C<Bird> c_of_bird = c_of_duck;
  print(c_of_bird.f(new Duck()));
}  
```
An attempt to run it ends badly: 
```
Uncaught exception:
TypeError: Closure 'C_closure': type '(Duck) => Duck' is not a subtype of type '(Bird) => Bird'
```

My question is: why do we have an error only in runtime here? It looks like the compiler has enough information to flag the invocation statically. Moreover, an argument can be made that the expression `c_as_bird.f` should be statically flagged with the error message `The method 'f' isn't defined for the class 'C<Bird>'.` 

In other words, when we upcast c_as_duck to c_as_bird, the method "f" should "disappear". Why? Because there's not much difference between *that* upcast and *this* upcast:
```
class Bird {
  void fly() {}  
}
class Duck extends Bird {
  void quack() {}
}
main() {
  Bird bird = new Duck();
  bird.quack(); // Error: The method 'quack' isn't defined for the class 'Bird'.
}
```

The user is not surprised to see the method "quack" disappear after the upcast. In fact, the contrary would be surprising. In case of "c_as_bird", same reasoning applies - what is the point to provide access to "f" is the call cannot be successful? (Same for the upcast from `List<int>` to `List<num>`: operator `[]=` should disappear, too).

If this is true, then the motivating example for "var X" above seems to be addressing the problem that (arguably) shouldn't exist  (the upcast from C<int> to C<num> will make "f" disappear)

Probably, I'm still missing something. Maybe your "invariant X" proposal addresses the problem, but I couldn't figure out (based on your write-up) whether the mechanism leads to disappearing methods or not.

Disclaimer: I didn't get to your reasoning about Null b/c I hit the wall earlier, and the above is the description of that wall :-)

**Comment by eernstg** [comment]
As a follow-up on [this comment](https://github.com/dart-lang/language/issues/180#issuecomment-479440787), I've written a rough first proposal for how to directly compute the resulting Dart type in a situation where we would otherwise take a detour via path dependent types: #296. The output from that algorithm is the kind of type we are using here.

@tatumizer wrote:
> explain .. a much simpler example:

The object `c_of_duck` variable refers to an instance of `C<Duck>` typed as such, and `c_of_bird` refers to the same instance, but typed as `C<Bird>`. This is not a violation of the heap invariant, because `C<Duck> <: C<Bird>`.

However, it is _incorrect_ to assume that `c_of_bird.f` has type `Bird Function(Bird)`. What we actually know is that there is some type `T` such that `T <: Bird`, and `c_of_bird` has a type `S` such that `C<invariant T>` is a superinterface of `S` (directly or indirectly). Based on that, we can conclude that `c_of_bird.f` has type `T Function(T)`.

But we do _not_ have `T Function(T) <: Bird Function(Bird)` for all `T <: Bird`, and that's the reason why the assumption above is incorrect.

We could then assign a sound type to the expression `c_of_bird.f` (the best one would be `Bird Function(Null)`), and check `c_of_bird.f(new Duck())` accordingly. This would succeed when implicit downcasts are supported, and code generation will then have to proceed in such a way that it is statically known that there will be a check (btw, that check will succeed at run-time in this case).

However, we do not do that currently, we actually assign the type `Bird Function(Bird)` to the expression `c_of_bird.f`, and then we generate a dynamic check to insist that this is what we get (a caller-side check). Of course, given that `c_of_bird` can be a `C<Duck>` there is no reason to expect this to hold, but it is true that we will enforce that the program incurs a dynamic error except in some situations where it is indeed safe to proceed. Indeed, it would work in some situations with exactly these static types, namely the situations where we are effectively using an invariant type; it's just not possible (yet) to specify that the receiver has type `C<invariant Bird>` (and, of course, that dynamic check would fail in the current situation, but we can adjust the program to make it succeed).

I'm arguing that we should use a sound typing in the first place. This makes it harder to call `c_of_bird.f`, but it will be based on information which is actually known to hold, and we will succeed in actually obtaining that function object (rather than throwing at a caller-side check).

**Comment by tatumizer** [comment]
@eernstg : I forgot to mention that `c_of_bird.f(new Bird())` fails, too. It's not surprising, given the circumstances, but the error message is a bit cryptic:
```
Uncaught exception:
TypeError: Closure 'C_closure': type '(dynamic) => dynamic' is not a subtype of type '(Bird) => Bird'
```
`dynamic`, of all things???
Compare it with an attempt to pass `new Duck()`:
```
Uncaught exception:
TypeError: Closure 'C_closure': type '(Duck) => Duck' is not a subtype of type '(Bird) => Bird'
```
I tried many other variants out of curiosity. What if we pass an instance of `ScroogeMcDuck extends Duck`? What if we pass null? Turns out, we never get anything new: scrooge triggers the same message as plain Duck (`...Duck is not a subtype...`),  null - the same as Bird (`...dynamic is not a subtype...`).

So it seems that no matter what we pass as an argument to `c_of_bird.f(arg)`, the program fails in runtime. Perhaps the compiler, by thinking a bit harder that it does now, could figure out that the fate of method "f" is already sealed at the moment when we upcast from c_of_duck to c_of_bird? Logically, there are 3 possibilities for the compiler:
- statically reject the attempt to call method `c_of_bird.f`, effectively making the method disappear (similarly to what compiler does when we upcast `Duck` to `Bird` and then call `bird.quack()` - compiler simply complains that the bird doesn't know how to quack). Unfortunately, the idea of making "f" disappear is not tenable, because an upcast to c_of_bird followed by downcast back to c_of_duck ideally should bring f back, but it wouldn't 

- statically reject the upcast from c_to_duck to c_of_bird right away (thus precluding possible runtime error on "f" call) . This is harsh, but might be a good choice otherwise. I have a theory that "invariant X" proposal leads to this kind of behavior, but I'm not sure.

- do nothing and let it fail in runtime (current behavior)

I'm writing it all down because it appears that understanding of these effects and choices is necessary to fully appreciate "var X" proposal. 
Or not? :-)

**Comment by tatumizer** [comment]
Here's the challenge. Can we write an extension on `Map<X,Y>` such that whenever we have `Map<X,Y>` and `Map<Y,Z>`, we can use operation `*` such that it produces `Map<X,Z>`?
```
Map<int, String> map1 = ...
Map<String, double> map2 = ...
Map<int,double> map3 = map1 * map2;
```
Can `var X` help here?

**Comment by eernstg** [comment]
@tatumizer wrote:
> `c_of_bird.f(new Bird())` fails ..

The original example (with `c_of_bird.f(new Duck())`) fails because of the caller-side check at the evaluation of the getter `f`, so we never proceed far enough to even try to call that function. So changing the actual argument to something else should not make a difference. I still get the same error message, and I don't understand how you'd get an error referring to `(dynamic) => dynamic`.

> So it seems that no matter what we pass .. the program fails

Right, because it's a caller-side check on the value of `f` that fails. It would also fail on `dynamic d = c_of_bird.f;`.

I hope we can get rid of caller-side checks entirely, we should just use a sound typing of `f`.

> Logically, there are 3 possibilities for the compiler:

My proposal is to give `c_of_bird.f` a sound type (cf. #296 for details), such that there is no need to perform a caller-side check. The best sound type is `Bird Function(Null)` (or `Bird Function(Never)` when we get that).

With a sound typing, the evaluation of `c_of_bird.f` would never fail, but further usage of its value might now involve a downcast (the sound type is a proper supertype of the type that we currently give to `c_of_bird.f`).

> "var X" idea .. provides the way to avoid an error in runtime

Right, everything concerned with `var X` is part of an effort to push for features that would allow developers to obtain statically safe typing of code using existential types. All these issues with "contravariant fields" are just examples of that kind of situation.

> we succeed in obtaining the function, but still fail while trying to call it

That's exactly one of the possible scenarios:

```dart
class Bird {}
class Duck extends Bird {}

class C<X> {
  X Function(X) f = (X x)=>x;
}

main() {
  var c_of_duck = C<Duck>();
  C<Bird> c_of_bird = c_of_duck;

  // Assuming the typing of #296 (and hence no need for caller-side checks)
  // the following does not include a downcast, and there is no error at run time.
  Bird Function(Null) f = c_of_bird.f;

  // Assuming #295 (checking the actual argument against the actual
  // requirement for functions with types like that of `f`), the following
  // invocation does include a dynamic check, which succeeds at run time.
  print(c_of_bird.f(new Duck()));
  // This one is similar, but fails at the check on the actual argument.
  print(c_of_bird.f(new Bird()));

  // With an 'existential open' operation we can check and make it safe.
  if (f is Bird Function(var X)) {
    Bird b = new Duck();
    if (b is X) b = f(b); // Statically safe.
  }
}
```

The last few lines show that we can indeed use `var X` to reconstruct static knowledge about the types involved in this situation, and then we can also write statically safe code for dealing with it.

**Comment by tatumizer** [comment]
> I still get the same error message, and I don't understand how you'd get an error referring to (dynamic) => dynamic.

I get this strange message (dynamic -> dynamic ) on dartpad, which is based on ver 2.2.0. On desktop, I have an earlier version (2.1.1-dev.3.2), which never mentions dynamic.

**Comment by eernstg** [comment]
@munificent, @leafpetersen, @lrhn, please confirm that we have decided to use the **static type** of the receiver when we bind the values of type arguments in an extension (and, consequently, in each extension method).

Although this approach does not have the same amount of expressive power as the dynamic binding, we get performance characteristics that are easier to understand, and we can use a very sophisticated, well-tested, and well-understood device to compute the value of such type arguments statically, namely type inference.

**Comment by eernstg** [comment]
@tatumizer wrote:
> why Duck=>Duck is not a subtype of Bird=>Bird

This is a [standard property of function type subtyping](https://stackoverflow.com/questions/1150372/confused-about-function-subtyping): You can't tolerate a function accepting a `Duck` if you statically expect a function accepting a `Bird` (because your perfectly nice `Ostrich` will be rejected when it meets the test `is Duck`), so `... Function(Duck)` is not a subtype of `... Function(Bird)`.

**Comment by eernstg** [comment]
@munificent, @leafpetersen, @lrhn, please confirm that we have decided to use the **static type** of the receiver when we bind the values of type arguments in an extension (and, consequently, in each extension method).

Although this approach does not have the same amount of expressive power as the dynamic binding, we get performance characteristics that are easier to understand, and we can use a very sophisticated, well-tested, and well-understood device to compute the value of such type arguments statically, namely type inference.

**Comment by leafpetersen** [comment]
> @munificent, @leafpetersen, @lrhn, please confirm that we have decided to use the **static type** of the receiver when we bind the values of type arguments in an static extension methods declaration.

LGTM

**Comment by tatumizer** [comment]
@eernstg : the answers in stackoverflow are verbose and just add to confusion.
Your own answer is short, but I don't understand it :)
So I had to resort to rediscovering the answer myself, as usual, which took enormous amount of effort, but it was worth it :). Here's my answer.

All the "strangeness" of functional types can be seen in this example: 
```
main() {
  void f(Duck duck) {}
  print(f is void Function(Bird)); // false!!! WHY???
}
```
To explain what's going on, let's ask one question: why do we need functional types at all?
One trivial use case is: we have some function foo, which accepts a **functional parameter** of type
`void Function(Bird)`. Compiler has to verify that whatever we pass as an actual parameter matches the definition of this functional type. For example:

```
//expecting a bird handler
foo(void Function(Bird) birdHandler) => birdHandler(new Bird());
// passing a function that knows only how to handle Duck
foo((Duck duck)=>duck.quack());
```
The function `foo` therefore assumes that it can call our function passing **any** bird.
But our duck-specific handler is not capable of handling an arbitrary bird. Compiler is right to reject it because of type mismatch.
So one-sentence answer is:  think of what happens when we pass a function as a parameter. (The rest is obvious).

**Comment by leafpetersen** [comment]
This was decided in favor of the static type.
