### ISSUE TITLE
Null-safety: null check not working with type Function

### ISSUE THREAD

**Issue by esotericpig** [dart-lang/language#1828]
I couldn't find an issue about this, but maybe it has already been mentioned.

The below code doesn't compile:

```dart
class Tester {
  void Function()? myFunc;
  
  Tester(this.myFunc);
  
  void test() {
    if(myFunc != null) {
      // ERROR: The function can't be unconditionally invoked because it can be 'null'.
      myFunc();
    }
  }
}
```

The workaround of course:

```dart
myFunc!();
```

It seems like the null-check if-statement should resolve it, just like when using a variable of any other type, but it doesn't work with type Function, but works with other types:

```dart
class Tester2 {
  String? name;
  
  void test() {
    if(name != null) {
      // Compiles fine.
      print(name);
    }
  }
}
```

Thanks

**Comment by Levi-Lesches** [comment]
This isn't because it's a function, it's because `myFunc` is a field. Local variables can be promoted, but fields cannot. 

Your `name` example works because you _can_ pass `null` to `print`. `name` isn't being promoted, but `print` doesn't care. If you tried to access a _property_ of `name`, or pass it to a function that expects a non-nullable, you'd get an error.

Some examples:

```dart
/// Fields do not promote...
class Temp {
  Function? func;
  String? string;
  
  void test() {
    if (func != null) func();  // error
    if (string != null) print(string.length);  // error
    print(string);  // always fine
  }
}

/// ...but local variables do
void main() {
  Function? func;
  String? string;
  if (func != null) func();  // OK
  if (string != null) print(string.length);  // OK
  print(string);  // always fine
}
```

**Comment by esotericpig** [comment]
Oh okay, I see. Thanks.

That's quite confusing. I thought fields/properties were okay with null-check. I didn't know that it's only for args/locals. So then it works with args:

```dart
  void test(void Function()? myFunc) {
    if(myFunc != null) {
      myFunc();
    }
  }
```

Well, hopefully it gets added to instance vars as well one day.

**Comment by Levi-Lesches** [comment]
The reason fields don't promote is because fields are actually getters under the hood, and getters are just functions that can return any value. Specifically, they can return a _different_ value every time they're called. Even `final` variables aren't safe, because `final` simply means "this has a getter, but no setter". Subclasses can override the getter with their own logic. The following is hopefully never used in production, but technically could be: 

```dart 
import "dart:math";

class User {
  /// This is null half the time, and non-null the other half.
  String? get username => Random().nextBool() ? "JohnSmith42" : null;
  
  void greet() {
    if (username != null)  // Just because it's non-null here...
      print(username.length);  // ...doesn't mean it's non-null here!
  }
}
```

Obviously, this is convoluted, but with actual logic like "is the user logged in?", this could happen. And even if _you're_ classes don't do this, someone can extend it and do it themselves. 

If you really want promotion without the `!`, you'd make a local variable that reflects the value of the field, and promote _that_:

```dart
class Temp {
  Function? func;
  String? string;
  
  void test() {
    if (func != null) func();  // error
    final String? string = this.string;
    if (string != null) print(string.length);  // OK
    print(string);  // always fine
  }
}
```
----
There are a couple of alternatives being discussed: 

- #1518: A stronger `final` that means the field will _never_ change (or at least without explicitly setting it)
```dart
class User {
  final String? username;  // once declared, never changes
  const User(this.username);

  /// null if [username] is null, but won't change
  final String? get email => username == null ? null : "$username@gmail.com";
   
  void test() {
    if (username != null) print(username.length);  // OK, because it hasn't changed
  }
}
```
- #1514: A local variable that redirects to a field, so it can be promoted:
```dart
void test() {
  shadow string;  // actually refers to this.string
  if (string != null) print(string.length);  // OK
  print(string);  // always fine
}
```
- #1201: A quick way to make a local variable that holds the value of a field. Today, you would do: 
```dart
void test() {
  if (var string != null) print(string.length);  // quickly defines a local variable
  print(string);  // always fine
}
```
