### ISSUE TITLE
Expose WeakRef and finalization tracking APIs in Dart

### ISSUE THREAD

**Issue by jacob314** [dart-lang/language#1847]
### Admin comment by @mit-mit:

This request is being tracked as a feature via issue https://github.com/dart-lang/sdk/issues/47772.

For details, see the working proposal feature specification:
https://github.com/dart-lang/language/blob/master/accepted/future-releases/1847%20-%20FinalizationRegistry/proposal.md

----

### Original feature request by @jacob314:

The C API for Dart has always exposed this functionality but it was not exposed in the Dart core libraries because it could not be implemented in JavaScript.
The WeakRef proposal has now landed in JavaScript so WeakRef and finalization tracking could now supported in debug Dart builds on all platforms.
Support is available in all major browsers but Safari so the feature would need to be prohibited in release builds until that changes.
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/FinalizationRegistry
https://github.com/tc39/proposal-weakrefs

Providing this APIs would allow Dart memory leak detection tools to work on both the Dart VM and JavaScript and would simplify integration of leak detection tools into unittests on the VM. For example, without this API, the VMService must be used to detect leaked objects with some performance overhead to find all instances of the LeakedObject class.

The apis could reasonably be exposed in `dart:core`, `dart:collection` (as an iterable WeakMap), or `dart:developer`.
It could make sense to expose this in `dart:developer` as that would make it less surprising if the APIs work in debug environments but not production environments.

**Comment by mraleph** [comment]
I am preparing a proposal which will be posted as a PR on a language repo once it is ready.

**Comment by mraleph** [comment]
The proposal is up here for review: https://github.com/dart-lang/language/pull/1853

**Comment by stereotype441** [comment]
I just read @mraleph's proposal, and although I don't have the expertise to comment on it in great detail, in general I like it.

One question (and I apologize if this has been addressed earlier; I'm just getting up to speed and haven't read all 67 previous comments): the proposed spec appears to make no guarantees whatsoever that any callback passed to `FinalizationRegistry` will ever be called.  In other words, an implementation in which `register` and `unregister` have no effect would, strictly speaking, conform to the spec.  I understand that we can't guarantee that any finalizer will be called if the program shuts down first (e.g. because the user has closed the web page containing the program).  And I understand that in theory, the amount of time between an object becoming unreachable and its finalizer being called may be unbounded.  But isn't there some guarantee we can make to at least clarify the intent (even if it might be impossible for a program to observe whether the guarantee was met)?  Like, for example, could we say, "after the garbage collector performs a full collection, the finalizers associated with any objects that are no longer reachable are scheduled to execute, and will execute prior to the event loop becoming idle"?  Or if even that's too strong, perhaps we could at least say "although there is no guarantee that the finalizer will ever execute, the implementation intent is that it be executed reasonably soon after the first full garbage collection in which the associated object is determined to be unreachable"?

Also, I didn't see any clarification of when `FinalizationRegistry` finalizers run relative to the event loop.  Are they guaranteed to be executed in their own microtask, or might they be executed concurrently with other microtasks?  If a program never returns to the event loop, will its finalizers ever run?  What if the program returns to the event loop regularly, but there is always a microtask waiting to execute?  What if the program regularly runs out of microtasks but there is always one non-microtask waiting to execute?

Thanks!

**Comment by blaugold** [comment]
Is there going to be a guarantee that Dart finalizers are not just triggered by GC being performed because of memory pressure, but also when the event loop runs out of tasks? 

I'm thinking of the case where a finalizer is closing something like a `ReceivePort`, which left open keeps an isolate running. If the object that the finalizer has been registered for has become unreachable, but there is not enough memory pressure to cause a GC, the isolate never exits, even though it potentially could.

**Comment by dnfield** [comment]
GC can be caused by memory pressure notifications but are normally caused by new allocations.

ReceivePorts that are open won't be GCed anyway though, because they're still live. But the weak ref api could still be used to notify users about uncollected ReceivePorts.

**Comment by mraleph** [comment]
> Is there going to be a guarantee that Dart finalizers are not just triggered by GC being performed because of memory pressure, but also when the event loop runs out of tasks?

No. We are not going to guarantee that GC ever runs. The only thing we can guarantee is that if GC runs and if GC discovers that the object is unreachable then it will eventually invoke the finaliser.

If developer want guaranteed prompt finalisation, then developer should structure their code to explicitly destroy objects.

**Comment by dvc94ch** [comment]
> If developer want guaranteed prompt finalisation, then developer should structure their code to explicitly destroy objects.

in the context of hot reloading in flutter, can't that lead to double frees?

**Comment by dnfield** [comment]
If you have a resource that might not otherwise get re-created in hot reload, you can make sure you respond to `reassemble` (on e.g. `State` or some binding class or whatever else might be appropriate) to recreate that resource.

IOW, if you called some kind of `dispose` method on an object which makes it unusable, you need to create a new instance of that object when you hot reload.

**Comment by mraleph** [comment]
Proposal has been accepted. Implementation tracking issues have been filed: https://github.com/dart-lang/sdk/issues/47772

**Comment by qssq** [comment]
```
======= Exception caught by scheduler library =====================================================
The following assertion was thrown during a scheduler callback:
Assertion failed: org-dartlang-sdk:///flutter_web_sdk/lib/_engine/engine/canvaskit/skia_object_cache.dart:248:12
!browserSupportsFinalizationRegistry
is not true

When the exception was thrown, this was the stack: 
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 251:49  throw_
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 29:3    assertFailed
C:/b/s/w/ir/cache/builder/src/out/host_debug/flutter_web_sdk/lib/_engine/engine/canvaskit/skia_object_cache.dart 248:13    [_doResurrect]
C:/b/s/w/ir/cache/builder/src/out/host_debug/flutter_web_sdk/lib/_engine/engine/canvaskit/skia_object_cache.dart 245:40    get skiaObject
C:/b/s/w/ir/cache/builder/src/out/host_debug/flutter_web_sdk/lib/_engine/engine/canvaskit/canvas.dart 210:33               drawPicture
C:/b/s/w/ir/cache/builder/src/out/host_debug/flutter_web_sdk/lib/_engine/engine/canvaskit/layer.dart 467:17                paint
C:/b/s/w/ir/cache/builder/src/out/host_debug/flutter_web_sdk/lib/_engine/engine/canvaskit/layer.dart 141:14                paintChildren
C:/b/s/w/ir/cache/builder/src/out/host_debug/flutter_web_sdk/lib/_engine/engine/canvaskit/layer.dart 337:5                 paint
C:/b/s/w/ir/cache/builder/src/out/host_debug/flutter_web_sdk/lib/_engine/engine/canvaskit/layer.dart 141:14                paintChildren
C:/b/s/w/ir/cache/builder/src/out/host_debug/flutter_web_sdk/lib/_engine/engine/canvaskit/layer.dart 368:5                 paint
C:/b/s/w/ir/cache/builder/src/out/host_debug/flutter_web_sdk/lib/_engine/engine/canvaskit/layer.dart 141:14                paintChildren
C:/b/s/w/ir/cache/builder/src/out/host_debug/flutter_web_sdk/lib/_engine/engine/canvaskit/layer.dart 368:5                 paint
C:/b/s/w/ir/cache/builder/src/out/host_debug/flutter_web_sdk/lib/_engine/engine/canvaskit/layer.dart 141:14                paintChildren
C:/b/s/w/ir/cache/builder/src/out/host_debug/flutter_web_sdk/lib/_engine/engine/canvaskit/layer.dart 368:5                 paint
C:/b/s/w/ir/cache/builder/src/out/host_debug/flutter_web_sdk/lib/_engine/engine/canvaskit/layer.dart 141:14                paintChildren
C:/b/s/w/ir/cache/builder/src/out/host_debug/flutter_web_sdk/lib/_engine/engine/canvaskit/layer.dart 537:5                 paint
C:/b/s/w/ir/cache/builder/src/out/host_debug/flutter_web_sdk/lib/_engine/engine/canvaskit/layer.dart 141:14                paintChildren
C:/b/s/w/ir/cache/builder/src/out/host_debug/flutter_web_sdk/lib/_engine/engine/canvaskit/layer.dart 368:5                 paint
C:/b/s/w/ir/cache/builder/src/out/host_debug/flutter_web_sdk/lib/_engine/engine/canvaskit/layer.dart 141:14                paintChildren
C:/b/s/w/ir/cache/builder/src/out/host_debug/flutter_web_sdk/lib/_engine/engine/canvaskit/layer.dart 368:5                 paint
C:/b/s/w/ir/cache/builder/src/out/host_debug/flutter_web_sdk/lib/_engine/engine/canvaskit/layer.dart 141:14                paintChildren
C:/b/s/w/ir/cache/builder/src/out/host_debug/flutter_web_sdk/lib/_engine/engine/canvaskit/layer.dart 368:5                 paint
C:/b/s/w/ir/cache/builder/src/out/host_debug/flutter_web_sdk/lib/_engine/engine/canvaskit/layer.dart 141:14                paintChildren
C:/b/s/w/ir/cache/builder/src/out/host_debug/flutter_web_sdk/lib/_engine/engine/canvaskit/layer.dart 368:5                 paint
C:/b/s/w/ir/cache/builder/src/out/host_debug/flutter_web_sdk/lib/_engine/engine/canvaskit/layer.dart 141:14                paintChildren
C:/b/s/w/ir/cache/builder/src/out/host_debug/flutter_web_sdk/lib/_engine/engine/canvaskit/layer.dart 154:5                 paint
C:/b/s/w/ir/cache/builder/src/out/host_debug/flutter_web_sdk/lib/_engine/engine/canvaskit/layer_tree.dart 56:17            paint
C:/b/s/w/ir/cache/builder/src/out/host_debug/flutter_web_sdk/lib/_engine/engine/canvaskit/layer_tree.dart 99:16            <fn>
C:/b/s/w/ir/cache/builder/src/out/host_debug/flutter_web_sdk/lib/_engine/engine/profiler.dart 37:18    


```

**Comment by fzyzcjy** [comment]
Hi, I wonder when will Dart finalizers be available (stable)? This is quite helpful for, for example, https://github.com/fzyzcjy/flutter_rust_bridge/issues/243. Thanks!

**Comment by dvc94ch** [comment]
I'd checkout https://GitHub.com/cloudpeers/ffi-gen, which handles this for you.

**Comment by fzyzcjy** [comment]
@dvc94ch Interesting. Sounds like similar to https://github.com/fzyzcjy/flutter_rust_bridge/ ;)

**Comment by dnfield** [comment]
I would strongly discourage anyone from using GC to manage non-Dart objects. If you want to manage native object lifetimes, have an explicit method like close or dispose to release native resources.  GC might not ever run, or run too late.

**Comment by dnfield** [comment]
However, using this to assert that appropriate cleanup methods were called before GC is good

**Comment by fzyzcjy** [comment]
@dnfield Thanks for the interesting remark!

> have an explicit method like close or dispose to release native resources

Then there are all problems of manual memory management... For example, accidentally forget to call dispose, or call dispose when still using it.

> GC might not ever run, or run too late.

I will tell Dart VM about the real (native) memory usage of the pointer. Then, if real memory usage is high, will Dart immediately trigger a GC (to also free up those native memory)?

/cc possible related @raphaelrobert, @Desdaemon, https://github.com/fzyzcjy/flutter_rust_bridge/issues/243

**Comment by dnfield** [comment]
The VM can be aware of external object size, but GC pressure comes from new allocations. It's really not that hard to get into a scenario where you have an external object that takes up very close to a ceiling of memory you want to use, but not enough to trigger a GC. Then, new allocations happen quickly and kick off a GC, but you then run out of memory (or file handles, or some other native limited resource) before the GC can finish. 

Flutter had this problem with images for example - we were relying on the GC to clean them up, which works pretty often but does not work so well when you try to load larger images in memory constrained environments. The more we tried to make the GC clean this up for us, the worse it got - the GC sometimes couldn't work fast enough (so new images could get allocated before the GC-able ones got cleaned up, leading to OOMs), and we also were artificially running the GC too often (Because it saw these huge objects it thought it was responsible for cleaning up). So now we explicitly and eagerly dispose images/graphics resources, and you can't get into that race anymore (and we don't need as many GCs, which are pretty resource intensive to run).

**Comment by fzyzcjy** [comment]
@dnfield Thank you so much for the insights!

**Comment by mit-mit** [comment]
Enabled in language version 2.17 and above
