### ISSUE TITLE
[Control flow collections] boolean as key values for constant maps

### ISSUE THREAD

**Issue by sgrekhov** [dart-lang/language#188]
Please see [Control flow collections feature specification](https://github.com/dart-lang/language/blob/master/accepted/future-releases/control-flow-collections/feature-specification.md#const-collections)

> As is already the case in Dart, it is a compile-time error if the key is an instance of a class that implements the operator == unless the key is a string, an integer, a literal symbol or the result of invoking a constant constructor of class Symbol. It is a compile-time error if the type arguments of a constant map literal include a type parameter

What about boolean? The following code works
```dart
var v = const {true: 1};

**Comment by eernstg** [comment]
The text here is not completely precise (we'd have to say 'an instance of a class that has an implementation of operator == different from the one in class `Object`', as we currently do in the language specification, [here](https://github.com/dart-lang/sdk/blob/ba07724b196a8b282456898a0fb6332c59efce85/docs/language/dartLangSpec.tex#L6642)).

With that, `bool` is actually already covered, because `class bool` does not have a concrete implementation of operator == different from the one in class `Object`. However, the spec does not explicitly state this as a fact, so in that sense it is currently just a consequence of an implementation decision.

I'll use this issue to get this topic clarified in the spec.

**Comment by eernstg** [comment]
Clarification done in [this CL](https://dart-review.googlesource.com/c/sdk/+/90462).

**Comment by munificent** [comment]
I clarified this in the "Control Flow Collections" proposal too.
