### ISSUE TITLE
Can Code objects be introspected?

### ISSUE THREAD

**Issue by munificent** [dart-lang/language#1933]
We've discussed whether there is any API to let you destructure a Code object and introspect over its syntactic subcomponents. For example, given a Code object for `a + b`, is there a way to determine that it's a `+` expression and what the two operands are?

**Comment by munificent** [comment]
> Do we have use cases for making them introspectable outside of statement/expression level macros?

The only one I know offhand is the request to hunt through the body of a function to find dependencies for observability. I'm OK with kicking this down the road.

**Comment by rrousselGit** [comment]
What does "kicking this down the road" means? As I'll definitely need this for dependency tracking.

Considering we can do that using build_runner today, it'd be a bit unexpected IMO to no-longer be able to,

**Comment by munificent** [comment]
> What does "kicking this down the road" means?

Basically just deciding on this later when we are further along with more fundamental design questions and implementation feasibility studies. I think we can decide whether or not the feature needs to support this after making other decisions since the overall design doesn't hinge on it.

**Comment by rrousselGit** [comment]
Coming back to this, another use-case I have is making some runtime errors compile errors instead

In particular, one case I have is, users may define the following:

```dart
@Macro(flag: true)
void a(Class class) {}

@Macro()
void b(Class class) {
  class.doSomething(a);
}
```



And I would like the line:

```
  class.doSomething(a);
```

to fail to compile because `b` did not pass the flag, such that folks have to either write:

```dart
@Macro()
void a(Class class) {}

@Macro()
void b(Class class) {
  class.doSomething(a);
}
```

or:

```dart
@Macro(flag: true)
void a(Class class) {}

@Macro(flag: true)
void b(Class class) {
  class.doSomething(a);
}
```



There are some workarounds to achieve this using the type system (by having a `Class` vs `ClassWithFlag` type). But this comes with an enormous amount of complexity and involves really bad error messages.


Riverpod managed to do this without macros, but it caused Riverpod to have 50+ public classes instead of ~20 (see its API reference https://pub.dev/documentation/riverpod/latest/riverpod/riverpod-library.html). That's significant pollution of the public API just for a single compilation error.

And the error message is fairly unclear too with no way of customizing it. It currently is something among the lines of:

```
The argument type 'ClassBase' can't be assigned to the parameter type 'ClassWithFlagBase'
```

It's a fairly obscure error with no way of clarifying it. No beginner seeing this compilation error will naturally guess what the fix to this error it


If Code objects could be introspected, then Riverpod's public API could be cut in half and the error message could become something much more human-friendly, such as:

```
`b` tried to doSomething on `a`, yet `a` has `flag: true` but `b` doesn't.

To fix, either remove `flag: true` from `a` or add `flag: true` to `b`.
```

**Comment by davidmorgan** [comment]
It looks like we will do some introspection on expressions for macro metadata

https://github.com/dart-lang/language/issues/3847

for any more than that it's a feature request / extension:

https://github.com/dart-lang/language/issues/2185
