### ISSUE TITLE
Allow mixins in "extends" clauses

### ISSUE THREAD

**Issue by munificent** [dart-lang/language#1942]
We would like to deprecate and eventually stop supporting using `class` declarations as mixins. There are a couple of proposals out for how to do that: #1529 and #1643. The main sticking point for simply making it a warning or error to mix in a class is Flutter.

Flutter has a number of class declarations that are widely used as both mixins (in `with` clauses) and as superclasses (in `extends` clauses). Flutter can't change those class declarations to be explicit `mixin` declarations because it would break every `extends` use of the classes in the wild today.

We could potentially have a deprecation period where we encourage Flutter users to change all of those `extends ___` to `extends Object with ___`, but it's not clear that that's actually a desirable ecosystem change. Most Dart users seem to be unaware of mixins so forcing them to learn about `with` before they can use common functionality like ChangeNotifier might be punishing for little benefit.

Here is a simpler proposal:

1. Allow using `extends ___` on mixins and treat it as syntactic sugar for `extends Object with ___`. Unlike the previous proposals, we don't make this a temporary language feature. Instead, we simply allow that sugar henceforth and forever.

    With this, Flutter classes like `ChangeNotifier` can immediately be changed to `mixin` instead of `class` without breaking or effecting any users.

2. After Flutter and other key packages have migrated their mixin-in-able classes to use `mixin`, add a linter rule that warns when users mixin a type declared using `class`. Eventually promote that to a warning.

3. In Dart 3.0, remove support for mixing in classes. Continue to allow mixins to appear in `extends` clauses.

**Comment by Hixie** [comment]
`ChangeNotifier` is two steps down an inheritance hierarchy. I don't think it makes sense for it to be a mixin.

**Comment by Hixie** [comment]
(I also don't really understand the benefit of allowing `class Foo extends Mixin` instead of `class Foo with Mixin`. It just seems to muddle things further. The migration path for the latter seems straightforward with `dart fix`.)

**Comment by bwilkerson** [comment]
We don't currently have a fix for that, but we certainly could.

**Comment by munificent** [comment]
> `ChangeNotifier` is two steps down an inheritance hierarchy. I don't think it makes sense for it to be a mixin.

I'm a little confused. The [docs](https://api.flutter.dev/flutter/foundation/ChangeNotifier-class.html) don't show it having any superclass other than `Object`. I see lots `with ChangeNotifier` in a corpus of packages, so it is definitely being used as a mixin.

What am I missing here?

**Comment by Hixie** [comment]
Sorry I was thinking ValueNotifier, ChangeNotifier is just one step down. The inheritance hierarchy is:

    Listenable
       |
    ChangeNotifier 
      |
    ValueNotifier

(The top link is done via `implements` rather than `extends`, in practice, because Listenable is just an interface.)

I don't really understand what problem we're trying to solve here, though. As far as I can tell, everything works fine today. The only issue is that `prefer_mixin` can't be silenced when a class is _intended_ to be used as a mixin as well as a superclass.

**Comment by munificent** [comment]
> Sorry I was thinking ValueNotifier, ChangeNotifier is just one step down. The inheritance hierarchy is:
> 
> ```
> Listenable
>    |
> ChangeNotifier 
>   |
> ValueNotifier
> ```
> 
> (The top link is done via `implements` rather than `extends`, in practice, because Listenable is just an interface.)

That distinction matters here. If ChangeNotifier *extended* Listenable, then users wouldn't be able to use it as a mixin (unless they manually implemented the Listenable interface themselves).
 
> I don't really understand what problem we're trying to solve here, though.

1. It's a source of confusion for library consumers and a maintenance burden for library authors that *any* class can be used a mixin if it happens to meet certain restrictions, even if the class author doesn't *intend* it to be used as one. We'd like to change the language so that you can *only* mix in types *declared* to support that by using `mixin` instead of `class`. We would change the language to make it an error to mix in a type declared using `class`. Anything you mixin would have to be declared using `mixin`.

2. That language change would be breaking to Flutter and others because there are types like ChangeNotifier that are intended to be used as mixins but are written using `class`.

3. Changing ChangeNotifier and friends to use `mixin` instead of `class` would be breaking to Flutter *users* since there are many existing uses of `extends ChangeNotifier` in their code.

To fix 3, we can simply allow mixins in `extends` clauses. (It's harmless sugar for `extends Object with ___`.) Doing this unblocks 2 so that ChangeNotifier and friends can be changed from `class` to `mixin`. That unblocks 1 so we can make it an error to mix in classes. The end result is a simpler language where it's easier for type authors and consumers to know how the type should be used.

> when a class is _intended_ to be used as a mixin as well as a superclass.

There's no material benefit to allowing a type to be used as both a mixin and superclass. They both result in a new subclass whose superclass is the mixin/class thing. The only capability you get is being able to use it in an `extends` clause, which we can just allow directly for mixins. Then it's clear to anyone looking at the type that it *is* a mixin and that it must continue to fit within the restrictions of being a mixin.

**Comment by Hixie** [comment]
> 1. It's a source of confusion for library consumers and a maintenance burden for library authors that _any_ class can be used a mixin if it happens to meet certain restrictions, even if the class author doesn't _intend_ it to be used as one.

Is it? It doesn't seem like that much of a burden. Do we have data supporting this?

This really does not seem like a high priority change to the language. There are far bigger fires for us to deal with, IMHO.

**Comment by Levi-Lesches** [comment]
> The only capability you get is being able to use it in an extends clause, which we can just allow directly for mixins.

I've been wondering about this: Can you make a mixin that shares functionality with another mixin? The closest I could get to this was: 

```dart
mixin A { void a() => print("a"); }
/// Trying to implement `B extends A`, such that `A` is an implementation detail
mixin B on A { void b() => a(); }

/// But A is not an implementation detail, C has to explicitly mix it in
class C with A, B { }  

void main() => C().b();  // "a"
```

**Comment by munificent** [comment]
> > 1. It's a source of confusion for library consumers and a maintenance burden for library authors that _any_ class can be used a mixin if it happens to meet certain restrictions, even if the class author doesn't _intend_ it to be used as one.
> 
> Is it? It doesn't seem like that much of a burden. Do we have data supporting this?

I don't know if we have numeric data, but we've heard from API maintainers over the years that Dart's flexibility around how classes can be used makes it harder to evolve APIs without breaking them.

> This really does not seem like a high priority change to the language. 

Sure, but it's also a tiny change.

**Comment by leafpetersen** [comment]
> Is it? It doesn't seem like that much of a burden. Do we have data supporting this?

@Hixie  It is absolutely a burden for library maintainers, and we have data to support it in the form of extensive experience *as* library maintainers.  The current best practice in numerous Dart team maintained libraries is to document classes in with comments indicating that a class is not intended to be mixed in.  [Example](https://github.com/dart-lang/sdk/blob/main/pkg/analyzer/lib/dart/element/element.dart#L59).  But the problem with comments is that if someone ignores them, then making a change that breaks a use as mixin still breaks the downstream customer, and so we are still on the hook to either fix the issue on a roll (internally) or to deal with the breakage (externally).

**Comment by lrhn** [comment]
@munificent 
> That distinction matters here. If ChangeNotifier *extended* Listenable, then users wouldn't be able to use it as a mixin (unless they manually implemented the Listenable interface themselves).

Not, not at all. You can't use a class as a mixin if it has a superclass other than `Object`.

So, if your class has an `extends ` not followed by `Object`, or a `with`, then you cannot derive a mixin from it.

**Comment by lrhn** [comment]
The problem we are trying to fix is that you can mix in classes that are not intended to be mixed in.

Allowing that is a problem. If *anyone* uses the class as a mixin, it becomes a breaking change to add a constructor or a superclass. Obviously, you can just say "I don't care" and add a supertype or constructor anyway. Even our own breaking-change policy does not consider programs doing mixin application of classes not intended as mixins as valid programs. (We're a little too lenient for my taste: "must not mixin a class clearly documented as not intended to be used as a mixin", where it really should be "not clearly documented as intended to be used as a mixin").

In practice, it would be better to not allow you to mix in those classes at all, instead of allowing the foot-gun.

So, we need to either introduce new syntax to declare classes that *can* be used as mixins, and disallow mixing in any other class, or to just disallow mixing in classes entirely, and have a migration path for the classes which are currently being used as mixins, so they can be come mixins.

The former would be a declaration like `mixin class Foo { ... }` which can't have superclasses, `on`-types or generative constructors (all the restrictions of `class` *and* `mixin` declarations). That's a lot of work for not a lot of benefit (there aren't that many mixin-classes), but it's consistent. As with other breaking language changes, we'd have cross-version compatibility which allows old code to mix in new mixin-classes, and new code to mix in old classes, but new code can only mix in new mixins and mixin-classes.

The latter would just make it an error to mix in a class. Whoever wrote the class that was intended as a mixin would have to change it to a `mixin` declaration.
That's much simpler, and what we are proposing to do.
The problem is that it breaks existing code which *extends* that declaration, which makes it harder to push through a change. Not impossible. Again, language versioning can work: We can allow old code to extend new mixins, and new code must change that `extends` to `with` to be valid. 
Or we can just allow `extends Mixin`, and not require any code to be migrated except the declaration. That makes migration easier, and if that's what it takes to get there, I'm fine.

So, different proposals: In a new language version:
1. Allow declaring `mixin class` which is like the current `class` that can be mixed in, but disallow mixing in any other new-code class. You can still mix in old-code classes, old code cannot mix in new-code plain classes.
2. Disallow mixing in a `class`. You can change the `class` declaration to a `mixin` declaration to keep mixin-ability, but then you can't extend it (you have to use `with`). You can still mix old-code classes. Old code classes can extend new-code `mixin` declarations if they allow `Object` as supertype.
3. Disallow mixing in a `class`. You can change the `class` declaration to a `mixin` declaration to keep mixin-ability. You can still mix old-code classes. Any class can extend new-code `mixin` declarations if they allow `Object` as supertype.

Assume we choose one of these, and do it in 2.16, which one would you prefer?

(In either case, you'd have to change `ChangeNotifier` to be a `mixin` to keep the ability to mix it in.)

**Comment by Levi-Lesches** [comment]
It seems like one of the questions we circle back to (and if I'm reading it right, the difference between options 2 and 3), is whether you should be allowed to extend a mixin, barring migration conveniences.

Using the example of Flutter's `ChangeNotifier`, users should be using `with`, but the question is what would another _type_ of `ChangeNotifier`, like `ValueNotifier`, use? There's an overlap here between wanting to include the functionality of a mixin by using `with`, and wanting to offer similar functionality of a class using `extends`.

**Comment by munificent** [comment]
> but the question is what would another _type_ of `ChangeNotifier`, like `ValueNotifier`, use?

Since `ValueNotifier` doesn't extend `Object` (it extends `ChangeNotifier`), it can't be used as a mixin and can only be used as a superclass.

**Comment by Levi-Lesches** [comment]
Right, my comment was addressing the earlier question of whether `ValueNotifier` should be using `with ChangeNotifier` or `extends ChangeNotifier`, and why.

**Comment by lrhn** [comment]
Seems to be handled by the language-versioned switch in Dart 3.0 to needing `mixin class` for declarations that can be both extended and mixed in.

We could still allow `extends Mixin`, meaning `extends Object with Mixin`, instead of having to write `with Mixin`, but I don't think there is any real benefit left. If anything, it'll just be confusing that you `extends Mixin`, but it doesn't have a generative constructor.

**Comment by munificent** [comment]
Yeah, I'm going to go ahead and close this because I think the language is more or less where we want it to be now with `mixin class`.
