### ISSUE TITLE
Will hand-written Enum imitation work as enum?

### ISSUE THREAD

**Issue by tatumizer** [dart-lang/language#1947]
The proposal says:

**This enum declaration above is therefore defined to behave equivalently to the corresponding class declaration:**
```dart
class Name<T extends Object?> extends Enum with Mixin1, Mixin2 
    implements Interface1, Interface2 {
  static const id1 = Name<int>._$(0, "id1", args1);
  static const id2 = Name<String>._$(1, "id2", args2);
  static const id3 = Name<bool>._$(2, "id3", args3);
  static const List<Name> values = [id1, id2, id3];

  final int index;
  final String _$name;

  Name._$(this.index, this._$name, params) : initList;

  memberDeclarations*

  String toString() => "Name.${_$name}"; // Unless defined by memberDeclarations.
}
```

**Q:** what if I write this declaration by hand, without relying on the sugar defined in the Enum proposal?
Will the compiler still treat it as enum?

Assuming the answer is yes, can I implement the same thing as a macro?
Simple example: instead of writing
```dart
enum SpecialValue {
  foo(3), bar(5), baz(42)
  final int value;
  const SpecialValue(this.value);
}
```
I write 
```dart
@Enum
class SpecialValue {
   static foo=SpecialValue(3), bar=SpecialValue(5), baz=SpecialValue(42);
   final int value;
   const SpecialValue(this.value);
}
```
and let the macro generate an equivalent definition, as above? I can see a significant upside in doing so (instead of defining an enhanced enum as a language feature). What is the downside?

**Comment by munificent** [comment]
A hand-generated enum-like class (whether using macros to desugar some of it or not) will behave *mostly* built-in enum syntax, but not entirely:

1. Real enums get exhaustiveness checking in switch statements. A hand-built enum-like class does not. (For pattern matching, I intend to explore letting user-defined classes opt in to exhaustiveness checking, but it's not there now.)

2. As you can see in your examples, enums get special nice syntax for defining the list of values. Hand-written classes and classes using macros don't get that. (We don't intend to use macros to let users add new syntax to the language.)

> What is the downside?

There's always a trade-off question in the language with syntactic sugar for whether it carries its weight in complexity or not. For enums (and enhanced enums), I think they do. This is primarily because many users coming from Java and other language already expect Dart enums to work this way. We don't spend the cost of teaching them *new* syntactic sugar, we just have to make the syntactic sugar that's already in their head do what they expect.

**Comment by tatumizer** [comment]
> This is primarily because many users coming from Java and other languages

I am not sure what language, other than java, supports java-style enums. I double-checked some languages (C#, typescript, python, scala), and in each of those, the enum values are defined using `val=expr` assignment, no attempt is made to emulate java enums. Anyway, it's not a criticism of the proposal - I was just curious about the rationale. (To tell the truth, I don't like java enum syntax and find the initialization without '=' weird and kludgy, especially when ported to dart - but this is subjective).

**Comment by Levi-Lesches** [comment]
> 1. Real enums get exhaustiveness checking in switch statements. A hand-built enum-like class does not. (For pattern matching, I intend to explore letting user-defined classes opt in to exhaustiveness checking, but it's not there now.)

From [`exhaustive_cases`](https://dart-lang.github.io/linter/lints/exhaustive_cases.html): 

> Switching on instances of enum-like classes should be exhaustive.
> 
> Enum-like classes are defined as concrete (non-abstract) classes that have:
> 
> - only private non-factory constructors
> - two or more static const fields whose type is the enclosing class and
> - no subclasses of the class in the defining library
