### ISSUE TITLE
How does async work with augment keyword?

### ISSUE THREAD

**Issue by mnordine** [dart-lang/language#1953]
In the [library augmentation proposal](https://github.com/dart-lang/language/blob/master/working/augmentation-libraries/feature-specification.md), the `augment` keyword is proposed, along with some examples. If we need to `await`, how does that look?
```dart
// Wrap the original function in profiling:
// `augment` always first in function declaration?
augment Future<int> slowCalculation(int a, int b) async {
  var watch = Stopwatch()..start();

  // await first
  var result = await augment super(a, b);
  
  // augment first
  var result = augment await super(a, b);
  
  print(watch.elapsedMilliseconds);
  return result;
}
```

Former seems more readable to me.

**Comment by stereotype441** [comment]
+1.  Also from the standpoint of the language grammar and semantics, I think `await augment super(a, b)` makes sense because it can be parsed as `await (augment super(a, b))` (in other words, call the original implementation, obtaining a future, then await that future).

**Comment by tatumizer** [comment]
Or just rename "augment super" to "augmentee". One word! :-)

**Comment by lrhn** [comment]
Or just make it `await super.slowCalculation(a, b)` and, for instance methods, don't allow skipping the augmented function on the way to the superclass implementation.

**Comment by tatumizer** [comment]
"super.foo" is ambiguous because it can refer to the "augmentee" OR to the foo inherited from the base class of the class being augmented.

**Comment by lrhn** [comment]
It's not actually ambiguous if it's the *same thing*.

Consider if we say that every function has (or can have) a super-implementation chain.
When you augment a function, you add an implementation to that chain, the augmented function becomes the next one up in the chain.
When you extend a class, the super-chain of your methods are linked to hose of the superclass, in one long chain.

Using `super` is going up that chain. Writing `super.foo` always means "the next `foo` up the chain" from where it's written.
(There are details, but I'm sure I can make this be consistent).

That is, it is as if an augmentation adds layers on top of the existing declaration, and you can ask for the most recent layer below yourself, and class extension also adds layers to the class declaration, and it's treated like *the same thing* and therefore, unambiguously, uses the same syntax.

**Comment by tatumizer** [comment]
I entertained this idea for a moment before asking but convinced myself that it contradicts the meaning of the verb "augment" ("make larger", accodring to Webster). If you interpret augmentation as creating a chain of C<sub>1</sub>, C<sub>2</sub>, etc where each of C<sub>n+1</sub> effectively extends C<sub>n</sub> then you are making super.foo, as seen from C<sub>0</sub>, inaccessible in the augmentations, which is counterintuitive. Had you used the verb "upgrade" instead of "augment", such an interpretation would become an easier sell. :-)

(\*) I'm not a native English speaker, so please take my linguistic propositions with a grain of salt.

**Comment by bwilkerson** [comment]
> Consider if we say that every function has (or can have) a super-implementation chain.

That's an interesting way to think about it, though not my initial mental model.

That model seems to be consistent with the `mustCallSuper` annotation. If it's critical that every implementation of a method invokes the super-implementation (so that some base implementation is always invoked), then that would also hold true for augmentations. I can't think of a valid counter example.

I like that that means that we could drop `augment` from `super` invocations.

**Comment by tatumizer** [comment]
> If it's critical that every implementation of a method invokes the super-implementation... I can't think of a valid counter example.

Suppose one augmentation adds a field and augments `hashCode` getter to compute a hash of all fields so far.
Another augemntation adds another field and augments hashCode getter (similarly).
It's not required for the second augmentation to utilize hashCode generated by the previous one (in fact, AFAIK, that wouldn't even be a good idea to do so).

But there's a bigger problem, which relates to the ordering of augmentation imports vs the order of macro invocations.
I don't want to diverge to it in this thread (will think how to verbalize it and open a separate issue), but the gist is that an augmentation library doesn't generally know whether `foo` was already defined in some C<sub>i</sub> down the stack or not.

**Comment by munificent** [comment]
I'm leaning towards changing the `augment super` syntax because I *don't* think we should model it in terms of overriding. It's a different operation.

Say you have a simple widget class hierarchy like:

```dart
class Widget {
  final Rect bounds;

  void draw() {
    // By default, fill with a solid background color.
    fill(bounds);
  }
}

class Frame extends Widget {
  void draw() {
    // *Don't* call super. We don't want to fill the background.
    stroke(bounds);
  }
}
```

The Widget base class has a default `draw()` behavior that fills with a color. The Frame class is a transparent widget that *doesn't* fill and draws an outline instead. Now consider some augmentations on Frame.

One valid augmentation is "I want to both fill *and* draw the outline":

```dart
augment class Frame {
  void draw() {
    super.draw();
    augment super.draw();
  }
}
```

In other words, the purpose of this augmentation is to reintroduce the `super.draw()` that the original declaration of `Frame.draw()` omits.

Another is "I do want to fill, but want do something else instead of drawing the frame":

```dart
augment class Frame {
  void draw() {
    super.draw();
    setLineWidth(4);
    stroke(bounds);
  }
}
```

Or "I want to do what Frame does but some other stuff too":

```dart
augment class Frame {
  void draw() {
    setColor(red);
    super augment.draw();
  }
}
```

All of these are valid. In particular, I think macros should have the ability to express these. That means that calling the superclass method and calling the original method are orthogonal axes.

I don't see much practical value in combining them. It leads to behavior that is strictly less expressive and it doesn't provide much simplicity in return. We already have to define what it means to augment top-level functions and static methods where `super()` isn't meaningful. So I'd rather just define that behavior directly and use the same behavior for instance members too.

**Comment by Levi-Lesches** [comment]
> Another is "I do want to fill, but want do something else instead of drawing the frame":

If you're going to allow the augmentation to completely replace the original implementation, isn't that more akin to subclassing? I don't see how it would be useful to write code and completely overwrite the implementation in an augmentation, versus just extending it and providing different behavior. 

>  We already have to define what it means to augment top-level functions and static methods where `super()` isn't meaningful.

In that case, why are we using `super`? Having `super augment.draw()` implies that `super` is a keyword and that there is an in-scope identifier named `augment` with a `draw` method, neither of which is true. It also implies that `super augment.doSomething()` is also valid, but that doesn't sound right. In other words, once I read `super`, the words `augment.draw()` hold no information since it's implicit. Why not borrow the current usage of `super` as an in-scope function representing the currently-augmented function. The word `super` is a natural choice, but if you feel it's really a separate idea, then another word like @tatumizer's `augmentee` would work too. Thus you reduce `super augment.draw()` into `augmentee()`, with the semantics of "I'm calling the augmented function".

**Comment by tatumizer** [comment]
Another syntax candidate:
```dart
augment int slowCalculation(int a, int b) as _slowCalculation {
  var watch = Stopwatch()..start();
  var result = _slowCalculation(a, b);
  print(watch.elapsedMilliseconds);
  return result;
}
```

**Comment by jakemac53** [comment]
It works like `await augment super(a, b);`.

I am soon going to be changing the syntax so it is more intuitive, from `augment super` to just `augmented`. This makes it more clear that it is different from regular `super` and also looks less weird.
