### ISSUE TITLE
augmentation libraries: the order of imports might be inconsistent with the order of macro invocations

### ISSUE THREAD

**Issue by tatumizer** [dart-lang/language#1965]
The lack of support for fully qualified names makes it necessary to use explicit import statements in generated files. Each macro generator uses its own imports. Consequently, we cannot concatenate the results of all macro generators in the same file (the imports will collide). Therefore, we have to generate many augmentation libraries for one main library, each with its own imports (which is bad enough). Then, these libraries have to be explicitly imported into the main library, but no one knows how many of them are there and in which order they have to be imported.

Either I totally misunderstand how augmentation libraries are going to be utilized in macros (which is quite possible), or there's something wrong with the design.

My gut feeling is there's no way around using fully qualified names of external classes in the generated code (\*). Using fully qualified names instead of imports in generated code is a common practice in other languages. But dart doesn't provide such a feature, e.g. I can't write
```dart
print(my_package:my_library:MyClass());
```
(Related: #1941)

(\*) the alternative: localized import:
```dart
augment foo() {
   import "src/bar" show baz; // accessible only within the block
   baz();
}
```

**Comment by jakemac53** [comment]
> Each macro generator uses its own imports.

They don't explicitly do this. The system does it, and should generate unique prefixes etc (when emitting resolved identifiers).

**Comment by jakemac53** [comment]
> Either I totally misunderstand how augmentation libraries are going to be utilized in macros (which is quite possible), or there's something wrong with the design.

There isn't a design sent out for this yet, I would wait before making assumptions about how it will work.

**Comment by tatumizer** [comment]
> The system does it, and should generate unique prefixes etc 

I think it makes it more complicated than it could be, and also breaks a fundamental scoping principle ("Always prefer local over global"), with many complications arising from this.  Maybe it's indeed too early to discuss this now, except that it can affect the design of imports. Please feel free to close the issue if you consider it redundant.

**Comment by munificent** [comment]
Scoping is always hard with macros, but I think we have a (still to be written down) plan for this. It's essentially:

* When a macro generates code, it does so by interpolating Identifier objects that know the top-level scope (i.e. library) that they are supposed to be resolved to. Think of them as a first-class resolved name.
* When the macro engine compiles macros to a library augmentation, it synthesizes imports for each unique library that is referenced by Identifier objects. Each import gets a unique prefix that is not shadowed by any local identifier.
* Then Identifiers are serialized to prefixed identifiers using those unique prefixes.

This should ensure that we can compile code generated from a number of macros into a single library augmentation without any scope collision.

**Comment by tatumizer** [comment]
I've already figured that out, but my point is that 1) it's rather complicated and roundabout 2) macros have to declare imports to be used only in the generated code (e.g `import dart.io` just to be able to generate the code that opens a file) 3) such imports are normally marked as unused (the macro itself won't use dart.io), but here the warnings have to be suppressed 4) and this is just a start :-)
I admit that the idea is fascinating, but this doesn't automatically make it a good idea  :-)

**Comment by jakemac53** [comment]
> 1) it's rather complicated and roundabout

I disagree with this. It follows an existing pattern we already have and use in package:code_builder. The apis will be different but the concept is the same, and it isn't overly complicated or confusing imo.

It is a lot less complicated for macro authors than manually trying to get the imports right (and especially avoid collisions with other macros).

> 2) macros have to declare imports to be used only in the generated code (e.g `import dart.io` just to be able to generate the code that opens a file)

It is important that macros can't add references to things that aren't imported by either the main library or the macro itself. Otherwise you get in a much weirder situation where users have to add their own dependencies on libraries they don't even use. They can be broken by a macro adding a reference to some new thing, etc.

It also would mean you can't just parse a file to understand what its dependencies are, which is an important feature (we need to do library cycle detection and generally create an import graph before running or resolving any dart code such as macros).

> such imports are normally marked as unused (the macro itself won't use dart.io), but here the warnings have to be suppressed

They will be used,  you will have to pass the identifier to a function in the macro in order to create a reference to it, for instance this api https://github.com/dart-lang/language/blob/39bfd1f385470686d0f1b25d14289a6e7747d606/working/macros/api/builders.dart#L74.

**Comment by tatumizer** [comment]
Oh, I see. The idea is obvious in retrospect, but difficult to come up with. Cute.
BTW, your new API is much simpler. Good job! :-)
