### ISSUE TITLE
generic constraints check

### ISSUE THREAD

**Issue by agrapine** [dart-lang/language#1971]
Due to the fact it isn't enough to check if generic type T satisfies the constraints, we're forced to create branches in code for each set of constrains for T.

Could we make it so the following example is not illegal?
```dart
abstract class Constraint {}

void foo<T>(T arg) {
  if(T is Constraint) {
    barConstrained(arg); // Illegal 😢 
  } else {
    barUnconstrained(arg);
  }
}

void barUnconstrained<T>(T arg) {...}
void barConstrained<T extends Constraint>(T arg) {...}
```

**Comment by Levi-Lesches** [comment]
By the way, using `T` in these tests doesn't work. To see why, try this: 

```dart
class Foo { }
void test<T>() => print(T is Foo);
void main() => test<Foo>();  // false
```

That's because `T` is a `Type` object. You want to use the actual object, `arg`, instead. So your new example can be: 
```dart
class Constraint { }
void barConstrained<T extends Constraint>(T arg) {}
void foo<T2>(T2 arg) {
  if(arg is Constraint) {
    barConstrained(arg); // Illegal 😢 
  }
}
```

**Comment by eernstg** [comment]
`T is Constraint` will be false no matter which type is the value of `T`, because you're testing whether the reified type (which is an instance of `Type`) has type `Constraint`, and that's never true.

What you surely want is to test whether the value of `T` is a subtype of `Constraint`. There is no operator in Dart which will do this directly, but you can express this test indirectly:

```dart
abstract class Constraint {}

void foo<T>(T arg) {
  if(<T>[] is List<Constraint>) {
    barConstrained(arg as Constraint);
  } else {
    barUnconstrained(arg);
  }
}

void barUnconstrained<T>(T arg) {...}
void barConstrained<T extends Constraint>(T arg) {...}
```

However, in this case it looks like you really want a simpler thing:

```dart
void foo<T>(T arg) {
  if(arg is Constraint) {
    barConstrained(arg);
  } else {
    barUnconstrained(arg);
  }
}
```

**Comment by agrapine** [comment]
@eernstg thank you for the reply. 

`T is Contraint` doesn't always return false. and yes I could run it with `as` : 
```
abstract class Constraint {}

void foo<T>(T arg) {
  if(T is Constraint) {
    barConstrained(arg as Constraint); // Not legal 😢 but T is lost...
  } else {
    barUnconstrained(arg);
  }
}

void barUnconstrained<T>(T arg) {...}
void barConstrained<T extends Constraint>(T arg) {...}
```

I need the T passed to barConstrained to be the extended class and not `Constraint`

here's a more specific example:

here I want to have some sort of protocol in extracting out the dependency on Provider but without adding a second closure/argument to the service registration (eg: `store.addLazy(()=> Counter(), provider: (instance) => ListenableProvider.value(value: value))`.

```dart

/// Caller

class Counter extends ChangeNotifier {
  int count;
  void increment() {
    count++;
    notifyListeners();
  }
}

Widget providerDelegate<T>(T value) {
  if(T is Listenable) {
     // desired
    return ListenableProvider.value(value: value); // illegal
    // with as & T
   return ListenableProvider<T>.value(value: value as Listenable); // illegal, T doesn't meet the constraints
    // with only as
   return ListenableProvider.value(value: value as Listenable); // now it can build a provider but for T == Listenable 😢 
  } else {
    return Provider.value(value: value);
  }
}

/// somewhere in bootstrap
final store = Store(providerDelegate)..addLazy(()=> Counter());
///
MultiProvider(
  providers: store.buildProviders(),
  child: child...
)

/// Store
class Store {
  Store(this.providerDelegate);
  
  final Widget Function<T>(T instance) providerDelegate;
  Map<Type, dynamic> registry = {};

  addLazy<T>(T Function() create) {
    registry[T] = LazyFactory<T>(create, providerDelegate);
  }

  List<Widget> buildProviders() => registry.values.map((e) => e.buildProvider()).toList();
}

class LazyFactory<T> { 
  LazyFactory(this.create, this.providerDelegate);
  final T Function() create;
  final Widget Function<T> providerDelegate;
  T? _instance; 
  T get instance => _instance ??= create();
  Widget buildProvider() => providerDelegate(instance);
}
```

**Comment by eernstg** [comment]
@agrapine wrote:
> yes I could run it with `as`:

But that still won't work: `if (T is Constraint) ...` is the same thing as `if (false) ...`, and that's probably not what you want.

The set membership relation and the subset relation can be used to illustrate the situation: You wish to test `T ⊆ Constraint`, but you're actually testing `T ∈ Constraint` (because that's how the `is` operator works: it tests type _membership_), and that's never true.

But you could do the following:

```dart
abstract class Constraint {}

void foo<T>(T arg) {
  if (<T>[] is List<Constraint>) {
    (barConstrained as dynamic)<T>(arg); // OK.
  } else {
    barUnconstrained(arg);
  }
}

void barUnconstrained<T>(T arg) {...}
void barConstrained<T extends Constraint>(T arg) {...}
```

You cannot use a run-time test in Dart to establish that `T` is a subtype of `Constraint` (we have had [proposals](https://github.com/dart-lang/language/issues/459) about type variable tests similar to the existing `is` tests, and it would not at all be impossible, we just don't have them). But you can verify indirectly that this subtype relation exists (`<T>[] is List<Constraint>` is an example of a test which will be true exactly in the cases where `T` is a subtype of `Constraint`), and then you have to perform the invocation itself dynamically, because the type system won't trust us that `T` can be used as a type argument to `barConstrained`.

This is statically safe (even though the type system doesn't know that ;-), but it will be slower than a statically checked invocation. So it may or may not be suitable for your purpose. It is also dynamically safe (in the sense that everything which is not statically proven by the type system will be checked at run time, in particular: it will be checked that the given type argument `T` is indeed a subtype of `Constraint` when `barConstrained` is called, but this check is guaranteed to succeed because we just tested the same thing).

**Comment by Levi-Lesches** [comment]
@eernstg, But doesn't casting `barConstrained` to `dynamic` kinda defeat the purpose of using bounded generics in the first place? Not to mention the return type and any other parameters. 

Despite the usage of `(T is Constraint)` instead of `(arg is Constraint)`, I interpreted this as a request to promote `T`. 

```dart
class Constraint { int get temp => 0; }
void barConstrained<T extends Constraint>(T arg) {}
void foo<T2>(T2 arg) {
  if(arg is Constraint) {
    print(arg.temp);  /// valid, since `arg` is promoted to `Constraint`
    barConstrained<T2>(arg);  /// error, since `T2` is NOT promoted to `T2 extends Constraint`
  }
}
```

**Comment by agrapine** [comment]
@eernstg you're the man. the dynamic invocation was the missing piece to overcome this.

`(barConstrained as dynamic)<T>(arg)` // just enough magic to get it over the line 👍

**Comment by eernstg** [comment]
@Levi-Lesches wrote:
> But doesn't casting `barConstrained` to `dynamic` kinda defeat the
> purpose of using bounded generics in the first place?

I don't think so. The point is that we're maintaining exactly the same kind of constraints that the static type analysis enforces, but in this particular case the static analysis cannot _express_ the desired property: A promotion of the type variable that makes it known that it is a subtype of `Constraint`.

So we use the test `<T>[] is List<Constraint>` to determine that `T <: Constraint` and then we use a dynamic invocation of `barConstrained` with the type argument `T` and the actual argument `a`, knowing that `T <: Constraint` and `a is T`, and that is exactly what is needed in order to accept the invocation as type safe. (We don't use the returned value&mdash;because it has type `void`, so we know we should ignore it&mdash;otherwise we would have had to take care of the type safety of that, too). The only missing bit is that we can't _tell_ the type checker that `T <: Constraint`, and hence we have to say "just for this function call, I've inlined the missing parts of the type checker into my program, so trust me, it will work!".

I tend to consider this to be the most important role played by dynamic constructs: They allow us to take the responsibility for ensuring the type correctness of constructs that are beyond the capabilities of the given static analysis. Of course, `dynamic` can also be used to introduce arbitrary sloppyness, but I wouldn't recommend that. ;-)

**Comment by Levi-Lesches** [comment]
> The only missing bit is that we can't _tell_ the type checker that `T <: Constraint`, and hence we have to say "just for this function call, I've inlined the missing parts of the type checker into my program, so trust me, it will work!".

Right, I get that. But wouldn't it be useful if we _could_? Let's say `barConstrained` was an actually useful function that took parameters and returned a value, like in a real codebase. By casting the function to `dynamic`, you lose all that info, and like you said, have to do Dart's work yourself. If the compiler could promote `T2` to be `T2 extends Constraint` (because it already promoted `arg`), this wouldn't be a problem. 

Is there a technical reason this isn't done already, or has it just not been that much of an issue?

**Comment by eernstg** [comment]
> But wouldn't it be useful if we _could_?

Yes! That's been proposed several times, and we have https://github.com/dart-lang/language/issues/459 to keep track of it.

However, I don't think we can expect a type checker to understand complex software fully. Some people are perfectly happy about writing certified programs using Coq and similar systems (like https://compcert.org/), and this goes very far in the direction of establishing a complete, machine-checked proof of correctness of the given program (relative to a spec, of course, and we all know that they never have any faults ;-). However, anyone who has tried using Coq will know that it can take hours to get over a seemingly trivial hurdle ("Here's a tiny function, Coq!", "Coq: Nope, that is not a function, how do I know it is guaranteed to terminate?", "...proveproveproveprove...", "Coq: Nope, doesn't type check yet.", ......), and I believe it's appropriate to choose a level which is significantly lower than "we must prove everything".

In this particular case it might not even be very hard, but there are always a lot of things to get right whenever the language is extended. Some of the worries are mentioned in https://github.com/dart-lang/language/issues/459, but I think that it doesn't even go much into the syntax, and surely there will be more if we look into the details.

Until then, and for any other extension which is reasonable and implementable and just not done yet, and also for extensions which are impossible to implement (because of decidability or complexity issues), I think it's important that we have escape hatches like dynamic invocations.

When we escape, we have to accept responsibility for the work which is otherwise done by the static analysis (or we might accept that dynamic errors could occur at that point, because we just don't care enough to avoid it). In this case it isn't hard to establish all the required guarantees, and it also wouldn't be hard if the function had had an "interesting" return type. We just have to do it manually, and that means that it must be treated very carefully during maintenance.

So we could add a language feature to handle this particular problem, but I don't think we can expect to have all the language features that we might want, and then it's important that we're not completely stuck.
