### ISSUE TITLE
Safe/unsafe concept (like Rust) for compile time safety

### ISSUE THREAD

**Issue by bernaferrari** [dart-lang/language#1981]
I always have trouble when I call a method that can throw an exception, like `array.first`/`array.find` or `await http.get`. It is totally unclear when implementing that they can explode later, often when running, and try/catch doesn't feel like a good (or even intuitive) scenario, as sometimes you don't even realize that `first` doesn't return null by default (I know about firstOrNull in the collections library, but the user may unconsciously add a code that can be a problem later).

I propose a `safe` function and an `unsafe` keyword/annotation, so all Dart code could be checked at compile time:

```dart
await http.get(); // Error, this is unsafe.
safe(await http.get(), onException: (exception) {}); // Proposed.

dynamic getData() => http.get(); // Error, this is unsafe.
unsafe dynamic getData() => http.get(); // Proposed.
```

Rust uses `!` for getting into possibly dangerous code, but Dart already uses it for null-safety. Rust has the `unsafe` concept where it can be a block `unsafe {}` or a function keyword for allowing dangerous things. We could have something like that in Dart, where `ctrl+f` would return every method that is potentially unsafe at runtime.

With Algebraic Data Types (and/or Unions), http.get could return `Success(data) | Error (exception)`, therefore limiting the user's exposure to dangerous code. The safe/unsafe concept could be useful as a mid-way until then, as a way to enforce people to make safer code and to prevent runtime errors.

I'm not sure how/where this could be used inside Flutter, in the worst case, `buildWidget` could be explicit about the errors it receives (and pass to ZoneGuard as it already does today).

**Comment by tatumizer** [comment]
Dart does not have a notion of "checked exceptions". Therefore, the compiler has no reason for raising an error here:
`await http.get();` - it simply doesn't know that the call might throw; such information is not present in the signature of `http.get`.

**Comment by bernaferrari** [comment]
Dart could have forbid `throw Exception` without a try/catch or unsafe keyword (through a version flag). So `http.get()` wouldn't compile without the unsafe keyword, and the code that uses it would then know what is happening.

**Comment by tatumizer** [comment]
In other words, you propose to introduce checked exceptions. 
This idea was ruled out right from the start of dart 1.0. By that time, checked exceptions (popularized by java) were already recognized as one of the biggest mistakes of its design. That's why you don't see them in newer languages.
Please refer to this article (among many others) for the background.
https://literatejava.com/exceptions/checked-exceptions-javas-biggest-mistake/

(See also https://stackoverflow.com/questions/1037575/why-arent-exceptions-in-c-checked-by-the-compiler)

Please note also that the patterns of error handling from rust are not applicable to dart (Rust doesn't have exceptions at all).

**Comment by bernaferrari** [comment]
Swift now has checked exceptions: https://docs.swift.org/swift-book/documentation/the-swift-programming-language/errorhandling/#Specifying-the-Error-Type
