### ISSUE TITLE
Stricter tagged string templates?

### ISSUE THREAD

**Issue by jakemac53** [dart-lang/language#1984]
Looking at the [JavaScript page](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals#tagged_templates), they have some examples which instead of taking the expressions as a list, accept a specific number of arguments. In Dart these could each have their own type as well, consider this (copied essentially from their example):

```dart
String myStrictTemplate(List<String> strings, String name, int age);

// Used like
myStrictTemplate'$name is $age years old!';
```

This would allow for stronger typing where you want exactly 2 arguments, with specific types.

One immediate issue you run into is how to distinguish between a "strict template" that takes a single List argument and the form of template that accepts an arbitrary number of "thunks" though.

Possibly if we had Tuples, this could be solved in the future that way, we could allow tagged templates to have a 2nd argument of type List or Tuple.

**Comment by munificent** [comment]
I considered this briefly. I couldn't think of any use cases, so I left it out to keep things simple. (I fear use of this would likely be anti-patterns that are using a string literal to try to reinvent their own weird invocation syntax.)

JS has a nice solution which is that the string templates always the expressions as separate arguments. But JS *also* supports rest params, so if you want to allow an arbitrary list of them instead of a fixed number of parameters, you just declare a rest param to gather them up. If we had rest params, I'd suggest something similar.

**Comment by jakemac53** [comment]
Ya I think I agree the use cases are contrived, and also we could probably tack this feature on later if we got sufficiently compelling use cases.
