### ISSUE TITLE
Enhanced enums `index` declaration

### ISSUE THREAD

**Issue by lrhn** [dart-lang/language#1995]
The [current proposal](https://github.com/dart-lang/language/blob/master/accepted/future-releases/enhanced-enums/feature-specification.md) for enhanced enums allows you to add mixins to the enum class.

Those mixins are applied on top of the `Enum` superclass, below the declarations of the `enum` declaration itself.

The `Enum` class declares `int get index;`, but does not provide an implementation.
The current specification states that an `int get index => ...` implementation is added to the `enum` class *itself*, which means it may override `index` declarations from mixins.

That also doesn't match the current *implementation*, where all `enum` classes share an internal `_Enum` superclass which implements `int get index`.

Should we do something else? The options include:
1. Say that `int get index` is provided by an unknown anonymous superclass which implements `Enum`, and which mixins are applied to. That allows mixins to freely override `int get index` and call `super.index`.
2. Say that if there is any concrete implementation of `int get index` declared in the `enum` class itself or introduced by mixins into a superclass, then the default `int get index` implementation is omitted. (That makes the internal `index` value unreachable, and it can potentially be completely tree-shaken, unless we use it for something else like optimizing switches). Since the class still implements `Enum`, the implementation will be compatible with `int get index`.
3. Say that it's a *compile-time error* if `int get index` is declared as a concrete member in the `enum` declaration itself, or its signature is overridden in a super-interface or mixin such that `in get index => ...` is not a valid override of the resulting signature. (We must introduce the getter, you can't add something which prevents that).
4. Say that it's a *compile-time error* if `int get index` is declared as a concrete member in the `enum` declaration itself, or in any of the mixins, or its signature is overridden in a super-interface or mixin such that `in get index => ...` is not a valid override of the resulting signature. (We must introduce the getter, you can't add something which prevents that, and you can't introduce a concrete implementation, so you can't tell whether the implementation actually comes from the current class or is inherited from a superclass ... we'd prevent a mixin from doing `super.index` too, pretending that there is no inherited implementation.)

Number 4 is the one which provides most flexibility to the implementation of enums.
Number 2 is the one that provides most flexibility to the enum class author.
Number 1 and 3 seems to add restrictions, enough to get in the way, but not enough to actually help either the implementation or the enum author.

**Comment by tatumizer** [comment]
@lrhn: what is the rationale for having "index" in the first place? Enum is normally considered an unordered set, but "index" implies some order. People may start externalizing this index, which will lead to an otherwise unnecessary breakage of old code whenever a new value is added. And it seems even conceptually questionable: after all, in a normal set, the elements are not supposed to have any index. What gives?

**Comment by munificent** [comment]
> 1. Say that `int get index` is provided by an unknown anonymous superclass which implements `Enum`, and which mixins are applied to. That allows mixins to freely override `int get index` and call `super.index`.

Is this morally equivalent to say that `Enum` itself both declares `int get index` and provides an implementation? If so, I like this one. I think this is the mental model users have, allows overriding and `super` calls, and has a minimum of magic.

**Comment by Levi-Lesches** [comment]
I agree with @munificent that allowing the user to override `index` as any other member can be useful. Given that, shouldn't 

> Number 2 is the one that provides most flexibility to the enum class author.

be option 1 instead? What benefit to the author does option 2 have over option 1?

**Comment by lrhn** [comment]
@tatumizer 

The rationale for having `index` was, probably (I wasn't there) that it allows a more efficient way to operate on the values. Java has an implicit index ([`ordinal`](https://www.tutorialspoint.com/java/lang/enum_ordinal.htm)), and apparently they were happy with it and uses it to implement enum switches and `EnumSet`. Dart chose to make it too, and name it `index`.
We just didn't have any way to abstract over enums, and no shared interface that contained that `index`, not until very recently.

The enum classes also needed *some* property that differed between enum values, to avoid the enum values all being canonicalized to one object by `const` evaluation - if we consider `enum` values as desugaring to normal `const` object creations, which the spec did. (We could also just have say that they were not canonicalized, so this was more of an extra convenience from already having `index`, and therefore not needing to say anything special about canonicalization.)

Since  `value.index` is equivalent to `EnumType.values.indexcOf(value)`, it's not a strictly necessary property, but again, it's more efficient to have the value directly.

Adding a value to an enum is always a breaking change, order notwithstanding.

@munificent 

We could definitely say that the `Enum` class itself provides the implementation of `int get index`, and that also explains why all enum classes have to extend `Enum`.
(Which they don't currently, they extend `_Enum` which implements `Enum`. We'd have to add an actual implementation of `get index` on `Enum`, and a `const` `Enum` constructor to make it look like it's actually extensible. We can then keep lying and extend `_Enum` instead.)

Another thing we could do is to make `index` an *extension member* on enum classes, like `name` is, instead of a real member. That would clear out the namespace and allow you to declare your own `index` members, but if you don't, `enumValue.index` keeps working, and you can always do the `EnumIndex(enumValue).index` override if you really need the real index value.
That would be consistent with `name`. Any code that is generic over enums will call it on `Enum` or `T extends Enum`, where it works.
You can't call `super.index` in mixins, but you can call `this.index` if the mixin is `on Enum` (which is the same case as where it could have called `super.index`). 

It would be a "breaking change" that can't actually break any code not using `dart:mirrors`, or code not importing `dart:core` and therefore not seeing the extension, or if someone introduces another `index` getter on `Enum` which would now not be shadowed by the instance member.

@Levi-Lesches True, option 1 is more powerful for enum authors because they *can* call `super.index`, and in both cases they can override it as they see fit. Option 1 is slightly more restrictive for the enum implementation, because it locks in the position of the `enum` getter implementation. So: in order of flexibility to users vs. implementors, we have something like (users horizontally, implementors vertically, option 5 being making `index` an extension getter, which loses user flexibility because they can't override it):

|  | - |   | + |
|:-:|:-:|:-:|:-:|
|-| 3 |   | 1  |
| |   |   | 2  |
|+| 4 | 5 |   |

(very roughly, and definitely open to discussion!)

**Comment by Levi-Lesches** [comment]
> Option 1 is slightly more restrictive for the enum implementation, because it locks in the position of the enum getter implementation.

If the idea of an `index` is intrinsic to all enum declarations, then wouldn't defining it on `Enum` be the most ideal? I'm just not sure what you mean by "locks in". The proposal talks in terms of a parent class `Enum`, and barring any magic/simplifications regarding `_Enum`, that would seems like the best place to put any enum-related member.

**Comment by lrhn** [comment]
The `index` getter is *declared* in `Enum`, but as an abstract getter.

Actually having the implementation being in the `Enum` class prevents us from other implementations, like having the field stored on the actual `enum` subclass, which may or may not be an advantage. 
If we can see that a specific subclass doesn't use the field at all, we might be able to tree-shake the field if it's not shared. (In practice, we currently share the field by having it in a shared superclass, we just don't *promise* to do so.)

So, any specification which defines where the value is stored prevents implementations which store it somewhere else.
The *less* we specify, the more flexibility we give implementors, but the less promises we can make to `enum` authors.

Tradeoffs. You just can't win! :wink:

**Comment by eernstg** [comment]
I think the **extension method** approach looks very promising! :smile:

We would remove the declaration of `int get index` from `Enum`, in order to avoid having an instance member that shadows the `index` extension getter. We would then add an extension `EnumIndex on Enum` with an `int get index => ...;` that might dispatch on different kinds of enums (selecting a suitable implementation), and some more specialized `_EnumIndex1 on _ThisKindOfEnum` where the index is known to be stored on the instance as a private field and `_EnumIndex2 on _ThatKindOfEnum` where the instances of an enum type are stored sequentially and the index is computed by subtracting addresses and dividing by the size, etc. Code generation could dispatch to `EnumIndex.index` as a fallback, and use the others (using suitable privacy violation magic) to generate code for enum types where there is more precise knowledge about the representation.

We get a lot of nice properties:

- Statically typed invocations of `index` continue to work, and look familiar.
- There is no OO override because this is an extension method, and this means that `EnumIndex(e).index` is guaranteed to yield the system-provided semantics, and `e.index` will provide this semantics by default.
- Anyone who _wants_ a different semantics can introduce an instance member named `index` in their `enum` declaration, and that allows them to customize the meaning of `e.index` in whatever way they want, and they have access to the system-provided semantics whenever needed, as opposed to the situation where we can't get to it because it isn't the nearest overridden implementation, so `super` won't work.

Conversely:

- The fact that developers can use `EnumIndex(e).index` to force the use of the system-provided semantics could be seen as a violation of abstraction.
- It may seem confusing/messy that the system-provided semantics is an extension method, and a custom semantics may be an instance method (though it _could_ also be an extension method).
- Invocations of `index` on a receiver of type `dynamic` will only work if the author of the enum added a instance getter with that name, which may again be seen as confusing/messy.

**Comment by lrhn** [comment]
Ah, yes. Making `index` an extension member is breaking because it doesn't work on `dynamic`.
And since we didn't have a super-interface of enum classes until recently, there might be code that works generically over enum types that uses dynamic invocations of `index`. So, harder migration than it immediately seemed. Damn dynamic!

**Comment by munificent** [comment]
> Actually having the implementation being in the `Enum` class prevents us from other implementations, like having the field stored on the actual `enum` subclass, which may or may not be an advantage.

I don't follow this. The `Enum` class could have *an* implementation of `index`. That implementation may be a getter or a field. That's an implementation detail that Dart very carefully encapsulates.

An actual `enum` subclass may choose to override that getter with another getter, or a field. Either should work fine. If both `Enum` and the subclass define `index` *fields* then you are theoretically getting some redundant state. But in this case, both classes are fully by the compiler so it seems fairly straightforward for the to eliminate the duplicate field if not needed.

Am I missing something?

**Comment by lrhn** [comment]
@munificent You are missing that mixins go between `Enum` and the `enum` class, and they can do `super.index` if we say that `Enum` provides the implementation of `index`.

So, if we say that, then the `enum` class cannot override `index` with the correct implementation.

We can certainly let `Enum` have an `int get index => _index;` and let the `enum` class actually provide `_index`, and let any internal code that needs direct access to the index go to `_index`. So, saying that `Enum` provides the implementation of `index` is definitely something we can get away with pretending, no matter where we actually store the value.

**Comment by munificent** [comment]
> @munificent You are missing that mixins go between `Enum` and the `enum` class, and they can do `super.index` if we say that `Enum` provides the implementation of `index`.

Ah, good point.

> We can certainly let `Enum` have an `int get index => _index;` and let the `enum` class actually provide `_index`, and let any internal code that needs direct access to the index go to `_index`.

Yes, that works. Basically what I'm suggesting is that `Enum` both declares and implements `int get index`. But *how* it implements it is completely an implementation detail. We don't need to say that there's a `_index` field on the `enum` class that the `Enum.index` getter can access. The implementation is just unspecified magic.

> So, saying that `Enum` provides the implementation of `index` is definitely something we can get away with pretending, no matter where we actually store the value.

+1.

**Comment by tatumizer** [comment]
If Enum class provides this magic, then it has to provide it [here](https://pub.dev/documentation/extension/latest/enum/Enum-class.html), too. 
That is, if I declare 
```dart
class Meter<int> extends Enum<int> {

 const Meter(int val) : super (val);

 static const Meter HIGH = const Meter(100);
 static const Meter MIDDLE = const Meter(50);
 static const Meter LOW = const Meter(10);
}
```
then I will get all the magic automatically.

Why do you need an extra level of sugar then? The entire proposal is mostly about an *extra* level of [unnecessary,  ad-hoc] sugar. To me, it looks almost comical: first, there are "native" enums; somewhere on the side, there's this `Enum<T>` java simulator. And then, there's an extra layer of sugar. If Enum provides the same functionality with no sugar, then the sugar doesn't do much except create more confusion. But if it doesn't provide this functionality, the whole logic just falls apart: we can't even say Enum implements some magic - no, it's the sugar that somehow injects this functionality into the otherwise dumb Enum. 
I admit I'm more confused than usual :-)

**Comment by lrhn** [comment]
That link is not related to Dart enums, it's just a third-party class named `Enum` from a some package.

Dart *language* enums are special. They are the only ones getting exhaustiveness checking in switches because it's the only types where we can *guarantee* that no other instances exist. There is a fixed number of known constant instances, that's what makes it an enum.

Currently there are lots of restrictions on what you can do with an `enum` class, other than declare the enumerated instances (basically, you can't do anything). 
Those restrictions are mostly unnecessary, they don't help with upholding the "fixed number of known constant instances" property, which is the reason for `enum`s to exist. 
This is not a proposal to add sugar, it's a proposal to remove restrictions on enum classes, compared to non-enum classes, which are not necessitated by being an enum.

That means declaring any other members on the enum class, including fields and having constructors to initialize those fields. It means implementing interfaces. It even means sharing implementation using mixins.

The one thing we require is that all the classes extend `Enum`, and that no other objects have a class that implements `Enum`. We ensure that by saying that it's a compile-time error if any non-abstract non-`enum` class implements `Enum`.

**Comment by lrhn** [comment]
I think putting the implementation of `index` in the `Enum` superclass will give the most flexibility to `enum` class (and `Enum `mixin`) authors, and the implementation issues are manageable.

That means that the class `Enum` will have an `external int get index;`/`external final int index;` member instead of an abstract `int get index;`/`abstract final int index;`.
We may even move the functionality of `_Enum` into `Enum` directly.

**Comment by tatumizer** [comment]
> Dart language enums are special. They are the only classes getting exhaustiveness checking in switches because it's the only types where we can guarantee that no other instances exist. 

I don't understand that. Exhaustiveness checking is already there for Enum-like classes - see [exhaustive_cases](https://dart-lang.github.io/linter/lints/exhaustive_cases.html) in linter. Quote:

> Switching on instances of enum-like classes should be exhaustive.
>
> Enum-like classes are defined as concrete (non-abstract) classes that have:
>
> - only private non-factory constructors
> - two or more static const fields whose type is the enclosing class and
> - no subclasses of the class in the defining library

I was sure you are building your proposal ON TOP of that.
It would be quite logical: you would have to add just a couple of fields (by the same magic as discussed above). This leaves us with the only problem: impose a restriction that makes it impossible to create MORE instances. This can be done exactly like in your proposal (disallow references to the constructor), with the only exception: you can still call this constructor in the declarations of enum constants. (This would remove the restriction on constructor being private: it can be public, but due to restrictions, it can't be accessed anyway).  No new syntax is necessary.

**Comment by lrhn** [comment]
Linter-powered exhaustiveness checks can tell you if you forgot a value. They cannot affect flow analysis and detect that when you do switch and do something on every value, there is no other path through the switch. That affects promotion and reachability analysis. Dart enums are truly part of the *language* in a way no user-written class can be.

Enum-like classes are just classes. The follow a pattern, but it's not a compiler enforced pattern that the compiler can otherwise rely on. They can do things that true Dart `enum` classes can't, like have members, which is why you'd want to use them anyway.

That's the gap we're trying to patch here, making Dart `enum` classes able to do all the things that enum-like classes can, so you can use proper `enum` classes for everything, instead of having to use non-`enum` classes which don't have the full language support.

**Comment by tatumizer** [comment]
> The language doesn't even know lints exists.

I understand that.

I thought the language uses lint as a testing ground for the new enum feature, and all you have to do now is to move the (already implemented) logic into the compiler. I thought these were all different stages of one clever, well-thought-out plan.
Like chess combination. Now I see where my mistake was: I was trying to rationalize things. A simpler explanation would be: all those various versions of Enums are emerging spontaneously. They are popping up here and there like mushrooms, in and out of existence. There's no grand plan. Things just *happen*.
FWIW, I find the *concept* of Enums currently supported by lint quite satisfactory. It could be incorporated into the compiler with minimal changes (change "class" to "enum" and add magic methods in Enum). Somebody apparently uses this concept already. This small change can be perceived as a natural step in a Grand Plan strategy (we can pretend such a plan existed all along).

**Comment by eernstg** [comment]
This has been settled: It is an error to override `index`, https://github.com/dart-lang/language/pull/2080.
