### ISSUE TITLE
Provide the ability for final or non-nullable fields to be defined in constructor bodies.

### ISSUE THREAD

**Issue by MichaelFenwick** [dart-lang/language#1999]
Currently, for classes with final fields or non-nullable fields which aren't instantiated at declaration, all constructors must directly set the values of these fields via `this.foo` arguments in the constructor signature. I find this to be troublesome in a number of circumstances, but primarily in the following cases:

- Cases where the field's value needs to potentially be changed from what the caller is passing in (such as to clamp a numerical input to within a specific range, or to set the field to a particular value in a Map, given by using what the caller passes as the key).
- Cases where the constructor is a translator between types (think of constructors which would be named things like `Foo.fromJson()` and the like). In this case, the caller is only going to be able to pass the original data structure into constructor, not the value(s) the class instance is ultimately going to store.
- For fields set via an optional parameter, cases where it's desirable to set the default value to something with is not a compile-time constant (which is currently a constraint that exists for default values of optional parameters but does not exist for assignments in the body). This is especially common when you want a 'DateTime' field to default to 'DateTime.now()'.
- Cases where the field in question does not need to be specified by the caller. This is often encountered in named constructors, like `Color.black();` and can often (but not always) be worked around with a forwarding constructor, such as (`Color.black(): Color(0, 0, 0);`).

Currently, some work arounds I have found (some more reasonable than others) include:

- Making the fields in question no longer final, and additionally making them private with the appropriate getters so they can be accessed outside the class, but can't be changed. (This, is rather ugly though, and it would still be possible to alter the value of the fields within the class itself).
- Keep the fields final, but replace the offending constructors with either factory constructors or static methods which ultimately call the base constructor and return that. I find this to be the best usually, but it's still messy and goes against what you would typically expect out of a factory constructor or static method.
- In the case of non-nullable fields, marking them as late (and thus losing some static analysis capabilities for it).
- Just giving up on immutability or non-nullability for the fields so that you don't have to worry about whether they are defined in the constructor's parameters.

In the end, the result of all this is a lot of frustration in the coding process, awkward looking code as a result of these workarounds, and excessive boilerplate.

My suggestion would be to allow for the static analysis to look in a constructor's body to see if a class's final or non-nullable fields are assigned an appropriate value, and only raise an error if it is not assigned in either the body or one of the currently existing allowed options.

**Comment by munificent** [comment]
Have you looked at [factory constructors](https://dart.dev/guides/language/language-tour#factory-constructors)? Those are the canonical solution to this problem today.

**Comment by Levi-Lesches** [comment]
Also, initializer lists? 

```dart
class Vector {
  final int magnitude;
  Vector(int vector) : magnitude = vector.abs();
}
```

**Comment by munificent** [comment]
That too. To your original point, @MichaelFenwick :

> My suggestion would be to allow for the static analysis to look in a constructor's body to see if a class's final or non-nullable fields are assigned an appropriate value, and only raise an error if it is not assigned in either the body or one of the currently existing allowed options.

We have discussed going this kind of definite assignment analysis inside constructor bodies many times. I agree that having to use a factory constructor or initializer list can be cumbersome sometimes. However, doing this analysis soundly is quite hard. You have to ensure not just that every field is definitely assigned inside the body but *that `this` is not accessed (implicitly or explicitly) before that happens*. Otherwise, `this` can escape, which means that code can access one of these fields before the end of the constructor body and before the language can be certain that the field has a value.

Java and C# work this way, and the result is unsoundness. In both languages, it *is* possible to observe a field—even a final/readonly one—before it has been initialized. In Dart, we wanted field initialization to be fully sound. It is completely impossible to read a (non-`late`) field in Dart before it has been initialized.

We could possibly still do this while allowing fields to be initialized inside the constructor body. But that would require prohibiting access to `this` until after all fields are initialized. Our thinking is that the errors users would get if they did that wrong would be very hard for many to understand. You couldn't, for example, call an instance method inside the constructor body.

To avoid that complexity and confusion, we instead force users to use factory constructors or initializer lists. Those can be a little more tedious to use, but they are easier to understand and still fully sound.

**Comment by MichaelFenwick** [comment]
Your point about it being confusing that you might not be able to use `this` in the constructor body is a good one @munificent. Perhaps a reasonable alternative would be to offer a new syntax for constructors? Something like `late Foo(this.bar) { baz = bar + 1; }` to tell the compiler that you're promising that after the constructor has run that all fields will have been initialized to an appropriate value, but without having to make all instances of the field `late`. I feel that even this would do a lot to remove some pain points I frequently run into, while also allowing the "lateness" to be limited to only the scope of the constructor (rather than that of the entire class), and thus less worrisome to use when needed. Ultimately I guess it's not really that different from a factory constructor, so maybe isn't worth doing for that reason, but to me it'd read cleaner since unlike with factory constructors, I'd know immediately what type the constructor is returning from the signature alone, and wouldn't have to manually call a separate constructor in the body itself.

**Comment by Levi-Lesches** [comment]
Do initializer lists not work for you?
