### ISSUE TITLE
Implementation issue for Int-to-Double-conversion

### ISSUE THREAD

**Issue by JekCharlsonYu** [dart-lang/language#20]
This issue is for tracking implementation of Int-to-Double-conversion:

- Request issue: https://github.com/dart-lang/language/issues/3
- Feature issue: https://github.com/dart-lang/language/issues/4
- Feature specification: 
https://github.com/dart-lang/language/blob/master/accepted/2.1/int-literal-as-double-value/feature-specification.md
 - Implementation plan: N/A

**What:** Issue for implementation for Int to Double Conversion

**ETA:** 10/15 in Dart Repo.

**Comment by lrhn** [comment]
Issues filed as https://github.com/dart-lang/sdk/issues/34355

**Comment by grandpa-guru** [comment]
@mit-mit I have one thing that bothers me while developing Flutter applications. Are there any reasons why 

> Error: A value of type 'int' can't be assigned to a variable of type 'double'.

when assinging variable value instead of literal value?

Not working:
>   int integerValue = 3;
>   double doubleValue = integerValue;

Working:
>   double doubleValue = 3;

**Comment by lrhn** [comment]
Yes, there is a reason.

Dart does not have implicit conversions between class instances. A value which is an `int` is not also a `double`, and there is no implicit way to convert it to a `double`, and so `double doubleValue = integerValue;` is an error. It's even a compile-time error because there is no way to assign something of type `int` to a `double` variable.

What Dart *does* have is the ability to treat integer *literals* (like `3`) as a double literal (like `3.0`) when the integer literal occurs in a place where a `double` is required. It *only* works for literals. There is no implicit conversion in that case, there was never any `int` object created. So `double doubleValue = 3;` is completely equivalent to `double doubleValue = 3.0;`, we just allow you to omit the `.0` when you know that the numeral will be used as a double anyway.

**Comment by ParvinderjitSF** [comment]
Why dart is lacking basic features like implicit conversions ? My app getting crashed due to this basic feature

**Comment by mateusfccp** [comment]
@ParvinderjitSF Can you give a concrete example of what is happening? Preferably a MRE.

**Comment by talski** [comment]
> @ParvinderjitSF Can you give a concrete example of what is happening? Preferably a MRE.

```dart
double? doubleValue;
dynamic integerValue = 1;

doubleValue = integerValue;
```

On flutter windows I get `type 'int' is not a subtype of type 'double?'`.
On flutter web I got no errors.

Flutter @ master
Dart SDK version: 2.14.0-383.0.dev on "windows_x64"

**Comment by mateusfccp** [comment]
@talski I can reproduce it on `Dart SDK version: 2.13.4 (stable) (Wed Jun 23 13:08:41 2021 +0200) on "macos_x64"`.

It seems that the web and VM behave differently in this case, which is undesirable.

**Comment by mit-mit** [comment]
This is a several years old historical issue. For new issues, kindly file a new issue
