### ISSUE TITLE
Surprising inference failure on nested future

### ISSUE THREAD

**Issue by eernstg** [dart-lang/language#2001]
Consider the following program:

```dart
import 'dart:async';

void main() {
  Future<Future<String>> v = Future.value(Future.value(''));
}
```

This program is rejected by both the CFE and the analyzer (version 2.9.0-11.0.dev as well as a fresh 2eaac80e1a968b0219793df296e38003f97ede7d):

```
n021.dart:4:56: Error: The argument type 'String' can't be assigned to the parameter type 'FutureOr<Future<String>>'.
 - 'FutureOr' is from 'dart:async'.
 - 'Future' is from 'dart:async'.
  Future<Future<String>> v = Future.value(Future.value(''));
```

and

```
ERROR|STATIC_WARNING|ARGUMENT_TYPE_NOT_ASSIGNABLE|/usr/local/google/home/eernst/lang/dart/scratch/202005/n021.dart|4|56|2|The argument type 'String' can't be assigned to the parameter type 'FutureOr<Future<String>>'.
```

The following variant is accepted:

```dart
import 'dart:async';

void main() {
  Future<Future<String>> v = Future.value(Future<String>.value(''));
}
```

It looks like the type inference commits to a choice for the two branches of `FutureOr` a bit too early. Is that intended, or should it search more exhaustively?

**Comment by eernstg** [comment]
Here's a simple example, and a connection to the inference ruleset which seems to illustrate that it is working as intended:

```dart
import 'dart:async';

void main() {
  FutureOr<Future<String>> v2 = Future.value('');
}
```

Inference on `Future.value('')` would seek a value for `X` such that
`Future<X> <# FutureOr<Future<String>> [X] -> ...`.
We have the following items in the [rule](https://github.com/dart-lang/language/blob/master/resources/type-system/inference.md#rules) for `FutureOr` on the right hand side:

> If `Q` is `FutureOr<Q0>` the match holds under constraint set `C`:
> - If `P` is `FutureOr<P0>` and `P0` is a subtype match for `Q0` under constraint set `C`.
> - Or if `P` is a subtype match for `Future<Q0>` under non-empty constraint set `C`
> - Or if `P` is a subtype match for `Q0` under constraint set `C`
> - Or if `P` is a subtype match for Future<Q0> under empty constraint set `C`

In this case, I believe that "subtype match for `Future<Q0>`" is applicable, yielding the constraint `_ <: X <: Future<String>`, and "subtype match for `Q0`" is applicable, yielding the constraint `_ <: X <: String`, and we commit to the former because that rule occurs first, and then the actual argument `''` is not assignable.

@leafpetersen, do you agree that this is how we get the error? Should we reconsider the ordering of the rules or is there a compelling reason to choose the current ordering?

**Comment by leafpetersen** [comment]
> @leafpetersen, do you agree that this is how we get the error? Should we reconsider the ordering of the rules or is there a compelling reason to keep the current ordering?

Yes, I believe we should keep the current ordering here.  Our inference is essentially one pass, so we don't get the opportunity to do arbitrary backtracking between successful matches.  At branch points from union types we have to heuristically choose which match to prefer when two local solutions exist (even if one of the local solutions later turns out to not result in a global solution).  This specific case is deliberate, I believe.  In general, when matching `FutureOr<T>` against `Future<S>`, there are two things to try: matching `Future<T>` against `Future<S>` and matching `T` against `Future<S>`.  If at most one applies, we're fine.  If both applies, the question is which is more likely to be the useful solution?  And the answer is that usually we are better off choosing to match `Future<T>` against `Future<S>` - nested Futures are rare and usually not what you want.  Consider for example:

```
void foo<T>(FutureOr<T> x) {}
void test() {
  foo(Future<int>.value(3));
}
```

By preferring the `Future<T>` branch, we get the solution of `int` for `T`.  If we were to prefer the `T` branch of the `FutureOr`, we would get the solution `Future<int>` for `T`, which is probably not what the user expected.

**Comment by eernstg** [comment]
Thanks, that makes sense! Closing.

PS: A more general notion of union types in Dart would then presumably clash with (non-backtracking) type inference in ways that are even more difficult to handle.
