### ISSUE TITLE
Problem with Dart Type Inference

### ISSUE THREAD

**Issue by icnahom** [dart-lang/language#2010]
I'm having a type inference problem when specifying a Type using a Generic Class. The Type defaults itself to the upper bound of the generic type parameter, but when using a super class as a Type it works fine.

[Here's ](https://dartpad.dev/?id=6f6d168be3bf85a56737013b21ff95ec)a simple example;
```dart
class Parent{}

class Foo<T extends Object> extends Parent{
  Foo(this.value);
  final T? value;
}

class Bar {}

void main() {
  final Parent a = Foo(Bar()); // Works
  final Foo b = Foo(Bar()); // Doesn't work!

  // Manually specifying works
  final Foo<Bar> d = Foo(Bar());
  final Foo c = Foo<Bar>(Bar());

  print(a.runtimeType);
  print(b.runtimeType);
  print(c.runtimeType);
  print(d.runtimeType);
}
```

**Comment by eernstg** [comment]
In `final Foo b = Foo(Bar());` you're specifying that the type of `b` is `Foo<Object>` (a raw type like `Foo` denotes the type which is obtained by [instantiation to bound](https://github.com/dart-lang/language/blob/6f69a38993b5674b06891092a40f915791a9206b/specification/dartLangSpec.tex#L7332)). The instance creation `Foo(Bar())` has the context type `Foo<Object>`, so you type inference yields `Foo<Object>(Bar())`.

So the important point here is that a raw type does _not_ mean "Please use inference to find the best possible type arguments" it means "use the declared bounds". If you don't want that, don't use a raw type.

```dart
class Parent{}

class Foo<T extends Object> extends Parent{
  Foo(this.value);
  final T? value;
}

class Bar {}

void main() {
  final Parent a = Foo(Bar()); // Yields a `Foo<Bar>`.
  final b = Foo(Bar()); // Yields a `Foo<Bar>`, declared type is `Foo<Bar>`.
  final Foo<Bar> d = Foo(Bar()); // Yields a `Foo<Bar>`, declared type `Foo<Bar>`.
  final Foo c = Foo<Bar>(Bar()); // Yields a `Foo<Bar>`, declared type `Foo<Object>`.
  ...
}
```

**Comment by icnahom** [comment]
It's alright 👍 I wanted `b` to work so that I can specify a type to be of an exact custom widget in flutter. Because writing the type like `c` makes it long and tedious. Anyways for now I will keep it to be of a type 'Widget' because everyone likes type inference.

**Comment by eernstg** [comment]
I think you should be able to obtain the desired typing by omitting the declared type and relying on the type of the initializing expression, and then perhaps adding a bit more type information to that initializing expression.

```dart
// Just a stand-in for an expression that depends heavily on type inference.
X foo<X>() => throw 0;

void main() {
  List<Map<int, String>> xs = [{1: foo()}]; // Declarative, require a specific type as the end result.
  var ys = [{1: foo<String>()}]; // Choosing the input to the type inference.
}
```

When the type information is provided in the declarative style it is necessary to write the desired type in full (although you might use `typedef`s to make some verbose types more concise), but when the type information is provided in the "forward" direction (by adding type information to subexpressions of the initializing expression) then you would typically be able to use simpler types.

The trade off is, of course, that the declarative style is declarative, that is, the type inference does more work and the result is documented explicitly. However, in many cases it works just fine to provide the necessary information in the initializing expression, because the type of the variable is reasonably easy to compute in the head when reading the code.
