### ISSUE TITLE
Macro argument scopes (specifically, Code objects), and augmentation libraries

### ISSUE THREAD

**Issue by jakemac53** [dart-lang/language#2012]
We want to be able to model the Macro output in terms of an augmentation library, and in general we want the code output by macros to not have special powers.

At the same time, we allow `Code` arguments to macro constructors, and we want the _scope_ of that code to be essentially the same scope as the macro annotation. However, we also possibly want to be able to refer to _local variables_ within those expressions.

Example:

```dart
abstract class Thing {
  int get x;
  int get y;
  
  @MemoizedVar(x + y) // `x` and `y` here are local variables. 
  int get z;
}
```

But what if `z` is a function, and it has parameters named `x` or `y`? We need to clarify whether the macro arguments scope is that of the _body_ of the declaration it annotates, or the class, or something else more custom.

Some factors to be taken into consideration:

- It might be useful for a macro arguments to be able to access the arguments to a function.
- A macro on `z` can emit code for declarations outside the scope of the body of `z` (for instance it can add fields and methods to the surrounding class and/or library, or add whole new classes).
- Macros may annotate static methods/fields on classes.

There are a few possible solutions I have been considering to this:

## Solution 1: No access to local variables or params in macro argument expressions

The scope is the lexical scope of the body of the class, static members of the class are visible (possibly without being qualified by `ClassName.`?), but no local variables.

This could be modeled by generating a static getter next to the original annotated declaration:

```dart
library augment 'original.dart';

augment class Thing {
  static  get _$someGeneratedName => x + y;
}
```

### Pros

- Easiest to define.
- Valid anywhere in the library (may need some munging to add the qualified `ClassName.` in front, or just require it).

### Cons

- Very limiting, can't access parameters or local variables.

## Solution 2: Its own lexical scope, as if the expression was inside the body of a new declaration

We could model this in the same way as Solution 1, except the getter wouldn't always be static - it would only be static if the annotated declaration was static.

### Pros

- I think this mostly behaves how users would expect, the scope is essentially the same as the annotated declaration.
- Allows access to local variables.

### Cons

- Possibly a bit magical, might be unexpected that expressions in macro annotations on static fields have a different scope.
- These expressions cannot be used in parent scopes (unless the annotated declaration was static).

## Solution 3: The scope is the same as the scope at the top of the body of the annotated declaration.

We could again model this in essentially same way, except with a local function at the top of the body of the annotated declaration.

```dart
library augment 'original.dart';

augment class Thing {
  int get z {
    // Note that the `Code` object in this case would have to be a function invocation not a reference to a getter.
    _$someGeneratedName() => x + y;
    // Rest of the generated code here (should contain an `augment super`).
  }
}
```

### Pros

- Has access to parameters as well as local variables, could be useful.

### Cons

- Breaks lexical scoping, the expression looks like normal code and lives outside the body of the declaration, so it likely isn't intuitive that the parameters are available.
- The expression is only usable within the annotated declaration (can't be used even on other declarations in the class).

**Comment by jakemac53** [comment]
My personal opinion at this time is to go with solution 2. I think its the least surprising, pretty easy to define and model in terms of augmentation libraries, and still provides a good amount of functionality.

**Comment by munificent** [comment]
Do we only support macro arguments that are used *as expressions*? I can imagine a macro like:

```dart
@addIntField(foo)
class C {
}
```

Which expands to:

```dart
class C {
  int foo;
}
```

In this case, the macro argument isn't treat as an expression, it's treated as an identifier that *binds* a name. That suggests another potential solution:

### Solution 3: Macro arguments are unresolved

They are treated as pure syntax. It is only the resulting code where they are interpolated that gets resolved. In fact, the same macro argument could be interpolated into multiple different points in the generated code such that each resolves in different ways.

I don't know if this is the *best* solution, but I think it's a fairly simple one that's implementable.

**Comment by jakemac53** [comment]
We could make them unresolved too, but I think its a really nice affordance to have them be resolved. It means you can get code completion and everything else within those expressions.

> In this case, the macro argument isn't treat as an expression, it's treated as an identifier that _binds_ a name. That suggests another potential solution:

I think for this case I would probably just ask for a String that is the name? Most of the interesting cases will be more complex expressions, where code completion and error checking etc would be nice.

**Comment by munificent** [comment]
> I think for this case I would probably just ask for a String that is the name?

We could, but that feels weird to me. The macro argument is already lived from being an expression to being a metaexpression that represents an identifier. Why the should macro user have to manually double lift the identifier into a string? If the macro needs an identifier which it will then use to declare something, isn't the natural syntax for that argument... an identifier?

**Comment by Levi-Lesches** [comment]
I'd argue that by passing an identifier into a macro, I'd expect the identifier to resolve and pass the _value_ instead to the macro. This would make using and writing macros that take parameters more intuitive, since that's how constructors already work. If I wanted to pass in a literal name, it would be pretty obvious to me that I should be using a String, just like I would when passing literal text to a UI framework.

**Comment by tatumizer** [comment]
I don't understand this:
```dart
 @MemoizedVar(x + y) // `x` and `y` here are local variables. 
  int get z;
```
Parameters of annotations are normally constant expressions, but here, `x + y` is not a constant, but something else. (I don't even understand what this macro is trying to achieve and why it should call "augment super" but ... never mind)

If we need a NEW kind of "constant" encapsulating an expression, then tagged literal looks like a no-brainer here:
`@MemoizedVar(expr 'x + y')`.

**Comment by jakemac53** [comment]
@Levi-Lesches ya that is basically my intuition. If I wanted to pass a variable definition as Dart code I would probably expect it to be an entire declaration anyways (`final int foo` or `var foo`) etc.

We had discussed only supporting expressions, which I still think is the right choice, but i don't see that codified in the spec yet so I will send a PR for that as well.

@tatumizer please read https://github.com/dart-lang/language/blob/master/working/macros/feature-specification.md#arguments

**Comment by tatumizer** [comment]
@jakemac53 : I still think this syntax will be less confusing: `@MemoizedVar(expr 'x + y').`, no?

**Comment by jakemac53** [comment]
@tatumizer The issue is those wouldn't be resolved expressions (its back to strings) instead of actual Dart code. I get where you are coming from with it being a bit confusing - there is something to learn there. But that isn't in any case what this issue is about.

We also don't want to leak the macro apis (including the `Code` api) into app code.

**Comment by tatumizer** [comment]
Whether they are resolved or not depends on whether the compiler resolves them or not, no matter what syntax. :-)
My point is that these expressions have better be somehow syntactically distinct.
E.g., dart for a long time delayed introducing back quotes into the language  - assuming that in the future, there might be a better application for them. This "better application" so far failed to materialize, maybe the time is now?
``@MemoizedVar(`x + y`)``.

**Comment by TimWhiting** [comment]
Personally I think both unresolved and resolved syntax are useful. I appreciate the code-completion of the latter and the flexibility of the former.

Example:
```dart
macro MyMacro implements ... {
  MyMacro(LexedTokens tokens, {required Expression initializer});

  /// Implementation uses the resolved expression to get the type parameter for the field
  /// but uses an unresolved identifier for the first parameter.
}


/// Usage

late int x;
late int y;

@addLateField(foo, initializer: x + y);
class C {
}

/// expands to 
augment class C {
  late int foo = x + y;
}
```

The tokens for unresolved code cannot include a comma notably.

It encourages macro authors to use resolved subclasses of Code for the most part (because of being able to resolve types and have code completion for users), while allowing for simple usage for example of unresolved identifiers.

It is up to the author of the macro to return / throw an error if the first argument is not a simple identifier. But this way you don't have to worry about resolving identifiers in scope when they aren't intended to be in scope to begin with.

**Comment by Levi-Lesches** [comment]
I'd actually agree with @jakemac53 again here, that passing in `x + y` as a _parameter_ feels wrong when there's a class definition right there you can put it into:

> If I wanted to pass a variable definition as Dart code I would probably expect it to be an entire declaration anyways (`final int foo` or `var foo`) etc.

My logic is that since the macro does not know what the expression is, it can't do anything useful with it that you can't do by annotating the field. In other words, instead of: 

```dart
late int x, y;

@MemoizedVar(x + y, "z")  // syntax here doesn't matter right now
class MyClass { }

// expands to: 
augment class MyClass {
  int? _z;
  int get z => _z ??= x + y;
}
```

I'd much rather see: 

```dart
late int x, y;

class MyClass {
  @memoize
  final int z = x + y;
}

// expands to: 
augment class MyClass {
  final int? _z;

  @override
  int get z => _z ??= augment super;
}
```

Again, the macro's job isn't to introduce a field called `z`, initialize it with `x + y`, and cache it -- the macro's job is just to memoize _any_ field. A line like `@MemoizedVar(x + y)` or `@addLateField(foo, initializer: x + y)` contains so much information that could easily just be in Dart syntax. I believe it would be better to just have the `late final foo = x + y` line and annotate that with whatever generic macro functionality you need.

**Comment by jakemac53** [comment]
The `@MemoizedVar` example was definitely not a very useful real world example, I agree for that case I would rather see a macro on a field.

I actually was just struggling to come up with examples that _were_ useful, so it might be better to start from those? Do we actually need this feature at all?

**Comment by Levi-Lesches** [comment]
Given that a parameter in the macro's constructor means "I need to operate on this expression but I don't know what it is", I think, generally speaking, it should always be possible to write that expression out as regular Dart code and apply the macro to that directly. Between `external`, abstract classes, `get`/`set`, `late`, and nullables, I have a hard time imagining a declaration that _needs_ to have its definition in the same place.

**Comment by tatumizer** [comment]
I am not sure if this is on topic or not, but anyway...
Consider an example:
```dart
@addLateField(foo, initializer: x + y);
class C {
}
```
Suppose I'm a "smart" user, I don't want to hardcode the parameters at the call site: I prefer to declare constants instead, placing them conveniently at the top of my file, and then refer to them by name. So I rewrite the code as
```dart
const parameterName = "foo";
@addLateField(parameterName, initializer: x + y);
class C {
}
```
Since there's no way to distinguish syntactically between values and expressions, the macro goes ahead and generates the field, but the field is not called "foo" - it's called "parameterName" instead.
This is quite unexpected. Had we had a different syntax for values vs expressions, the macro, at least in theory, could call some method from the Context: "give me the actual value of parameterName" (such a mechanism is not currently envisioned, which is another problem) .

But let's forget about this case for now - very often, the macro can be implemented without evaluating parameter value at compile time (it will just generate the code that uses the parameter transparently). My argument is: in all cases like this, the parameter should be treated as "passed as expression", not as "passed as a literal value".
Example:
```dart
@insertLogMessage(message: "foo called")
void foo() {
}
```
To cover the case when the user passes a constant instead of a literal, the macro has to accept the parameter as "expression". Then, it will work even if called like this:
```dart
const message = "foo called";
@insertLogMessage(message: message)
void foo() {
}
```
Again, if the macro interprets the parameter as a "value", it will insert `log("message")`; if it treats it as an expression, it generates `log(message)`, which is the expected output.

**Comment by lrhn** [comment]
A problem here is that `@SomeMacro(x + y)` looks like a normal annotation, which creates a constant value.
The macro is instead using the *expression* as argument. (It can't do anything else, only constant values exists at compile-time, everything else is at most syntax.)

There is precedence for generating AST nodes from syntax in [C#](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/concepts/expression-trees/).
For example the LINQ `SELECT` operation desugars to calling the `Select` method on the underlying collection, but if the compiler statically determines whether that `Select` method expects an `Expression<Func<T, bool>>` instead of a `Func<T, bool>`,  then it builds an AST of the expression instead. 
It works everywhere. If the context type of an expression is `Expression<T>` then the expression has context type `T`, but it's compiled into an expression creating an AST of the expression, instead of into code evaluating the expression.
C# expressions might be grammatically simpler than Dart expression (not sure anymore, they've added a lot since then).

That might be way to do things in Dart too. If a macro annotation needs an expression, it can be typed as needing the expression, and then you can *also* pass values to the macro.

**Comment by tatumizer** [comment]
> If a macro annotation needs an expression

My point is that there's no "if" here - at least not with the current design. All macro parameters have to be treated as expressions. Do you have an example where the parameter can be *expected* to be passed as a value? In every situation like this, the user might try to pass the constant expression and then wonder why the compiler cannot even compute 2+2.

**Comment by TimWhiting** [comment]
The current API lets a macro take a Code expression (or subclass of Code) which is treated as unevaluated syntax, which can be resolved and inserted into the generated code. However, it also lets you take in normal parameters such as Strings. Whether a string is evaluated as a literal String or a Code expression depends on the parameters of the macro constructor, not the arguments. I can see how that might be confusing to users, but I believe it is up to the macro documentation to tell users how to use the macro.

```dart
macro MyMacro ... {
   MyMacro(Code identifier);
}

macro MyMacro ... {
   MyMacro(String name);
}
```


Looking at your example it might be confusing for it to generate a field called parameterName instead of foo. 
```
const parameterName = "foo";
@addLateField(parameterName, initializer: x + y);
class C {
}
```
But the macro never took in a String to that parameter. So it would also look weird to a regular user of the package why you are 'trying to pass as string instead of an unresolved identifier'. And a new user who has not read the documentation might try this (I don't know if I would ever recommend someone using a package without glancing at the readme / docs), but then when there are analysis errors after trying to use a field called 'foo' they will be able to look at the augmentation file and figure out what is happening, and if still confused will look up the package documentation / stack overflow answers for the package to figure things out. But for most regular users of the package who have read the documentation or used the package before they will understand immediately.

**Comment by jakemac53** [comment]
Hi all, this issue got very derailed, so I have hidden a bunch of comments (including my own :D ) that aren't related to the _scope_ of expressions passed to macros as code.

See #1989 for some discussion around other syntax ideas for these code block arguments, or file new issues if you want to discuss their general usefulness or other topics related to that, thanks!

**Comment by jakemac53** [comment]
We discussed essentially this again recently, I think we are going to stick with Option #1. Essentially macro applications should behave exactly like annotations do, they will not have a special scope.

It just gets really weird to look at otherwise, and we have enough other questions to answer regarding scoping/identifiers in macros as it is. Further complicating the matter doesn't seem worthwhile (plus the suggestions here would break the expected and intuitive lexical scoping that most dart users love).
