### ISSUE TITLE
`(Native)Finalizer.detach` `detachKey` specification

### ISSUE THREAD

**Issue by dcharkes** [dart-lang/language#2015]
[1847 - FinalizationRegistry/proposal.md](https://github.com/dart-lang/language/blob/d5fd4997c8fd6344852856ae4d0cd73529fd4f87/accepted/future-releases/1847%20-%20FinalizationRegistry/proposal.md)

```dart
  /// Detaches the finalizer from any objects that used [detachKey] when
  /// attaching the finalizer to them.
  ///
  /// If the finalizer was attached multiple times to the same object with different
  /// detachment keys, only those attachments which used [detachKey] are
  /// removed.
  ///
  /// After detaching, an attachment won't cause any callbacks to happen if the
  /// object become inaccessible.
  void detach(Object detachKey);
```

The specification of `detachKey`  is incomplete.

1. It is not specified whether `detachKey` in `detach` should be `identical` _or_ `equal` to the one passed in in `attach`.
2. It is not specified whether `detachKey` is scoped by the `Finalizer` and `NativeFinalizer` instances. I presume it is. (Detach should be a static method if it wasn't scoped by the instance.)

cc @mraleph @lrhn

**Comment by dcharkes** [comment]
RE: 1. It's `identical` because we want the `detachKey`s to be usable in `Expando`s I believe?

**Comment by lrhn** [comment]
The `detachKey` must be identical. It's not because we want to use them in expandos, just that they have the same requirements as expandos.

We should probably introduce a new concept of "non-trivial identity", and disallow anything having no-trivial identity. In practice it's not so much about identity as it is about life-time and being literals. Anything where we can introduce something later which must have the same identity, even after the existing object was GC'ed, can't be trusted as being managed by GC, so no expandos, finalizer keys or weak-references to something where we can re-create something with the same identity.

The `detachKey` is only scoped to the current finalizer. Finalizers are entirely separate and knows nothing of each other.

Maybe changing "the finalizer" to "this finalizer" is enough.
