### ISSUE TITLE
Add a @debuggerHidden annotation and use it in dart:core library to hide properties that are not useful for debugging

### ISSUE THREAD

**Issue by jacob314** [dart-lang/language#202]
Add a `@debuggerHidden` annotation and use it in dart:core library to hide properties that are not useful for debugging. `@debuggerHidden` is a placeholder name. I am equally fine with another name matching the same or similar concept.

Related flutter issue for motivation:
https://github.com/flutter/flutter/issues/27377

 I would want to update the dart:sdk core library to use this annotations so debuggers in IntelliJ and VSCode can show a terser views of dart:core classes in general and collection classes in particular. For example, for the `Iterable` class it could make sense to only show the length, isEmpty, and first properties by default as many of the other properties are redundant and just badly clutter the debugger. For example if you know the value of `isEmpty` you know the value of `isNotEmpty` so no need to show it as well.
```dart

abstract class Iterable<E> {

  @debuggerHidden Iterator<E> get iterator;

  Iterable<E> followedBy(Iterable<E> other);
  Iterable<T> map<T>(T f(E e)) => new MappedIterable<E, T>(this, f);
  // ...

  int get length;
  bool get isEmpty => !iterator.moveNext();

  @debuggerHidden bool get isNotEmpty => !isEmpty;

  E get first;

  // Hidden by default as it is slow to compute and if a user is interested in last they 
  // probably really wanted to see all the elements.
  @debuggerHidden E get last;

  // No need to include this if you have first and length.
  @debuggerHidden E get single;
}
```

**Comment by lrhn** [comment]
This is a *very* usage specific annotation. Not only is it only intended for tools showing object layouts (or class layouts?), it's carefully tailored to one specific idea about what to show. It's basically a curating of APIs for one particular use-case.

We don't want to overload the SDK source with platform or use-case specific annotations. The source is for everyone, and the more crud we put in there, the less useful it becomes for everybody.
There is no way the library team can maintain these annotations, since they are based on a third-party judgement about what is applicable to a particular tool. We also don't want every other team to have to edit platform SDK sources in order to make their tool work better.

What I would recommend is that we build a secondary metadata functionality that tools can integrate with, so an IDE or debugger can parameterize, say, the analysis server or common front-end, with structured use-case specific metadata for the SDK (or any library), and then get that information back when it applies. Basically a kind of "annotation injection". Since annotations have no effect on the Dart static or dynamic semantics, it's a safe approach. I think that will actually *scale* to multiple tools.

(I'm already starting to regret the `pragma` annotation, because it *really* has no use for anyone except the tool itself, and editing it suffers from the same issues as mentioned above. That too can be handled by metadata injection instead, because the annotations are only relevant to the particular tool who is requesting the source to be parsed.

So, my (long term) suggestion is to work towards making our tools, the ones used by other programs, allow annotation injection in some form, and possibly combine that with code generation.

Just adding annotations to the SDK source code for each particular use-case does not scale. I'd prefer to not go there at all (there shouldn't need to be any annotations in the SDK except `@deprecated`).

**Comment by jacob314** [comment]
Thanks. We'll solve a more restricted set of problems directly in package:flutter instead using clever  lints to eliminate almost al  cases where the error is required.
