### ISSUE TITLE
[Feature Request] Add single if statement tearoff (syntactic sugar)

### ISSUE THREAD

**Issue by Agondev** [dart-lang/language#2038]
Would be great to be able to do something like:

```dart
Navigator.canPop(context) ?> Navigator.pop()
```

instead of:

```dart
if (Navigator.canPop(context)) {
  Navigator.pop();
}
```

Honestly not a must, nor a priority. Just a personal preference, and might benefit many others like me.

Per my comments below, this is to be an optional operator. As in, both of the above can be used interchangeably. The suggested new operator is not a replacement of the standard if statement, but rather like a ternary in its purpose.

**Comment by tatumizer** [comment]
Good idea, but `Navigator.canPop(context) ?> Navigator.pop()`  looks like an expression, and if this is an expression, it has to return something.
Maybe it can return Never though.
Would be especially handy if we could also use `continue`, `break`, `return` after `?>`

**Comment by Agondev** [comment]
> Good idea, but `Navigator.canPop(context) ?> Navigator.pop()` looks like an expression, and if this is an expression, it has to return something. Maybe it can return Never though. Would be especially handy if we could also use `continue`, `break`, `return` after `?>` Looks "mathy" - quite a good fit for dart IMO.

My choice of ```?>``` is arbitrary, I simply combined ```??``` and ```=>```. Anything else will do, really; as long as it's short and simple.

**Comment by tatumizer** [comment]
I like it the way you proposed. It also provides a good syntax for conditional passing of optional parameters (instead of "if") - see [this comment](https://github.com/dart-lang/language/issues/1311#issuecomment-998366835):
`foo( x == 1 ?> 42)` - but here, the return type is VoidOr<int>.
Maybe it should always return this type, even when used as an independent "expression".

**Comment by Levi-Lesches** [comment]
Keep in mind, you can already do this in one line: 

```dart
if (Navigator.canPop(context)) Navigator.pop();
```

I don't really think an expression form is needed, since this is inherently a statement with control flow.

**Comment by tatumizer** [comment]
Indeed, the braceless form exists, but it's ugly. I don't like it, and I don't know anyone who does.
Many style guides [frown upon this form](http://www.fredosaurus.com/notes-java/flow/if/30if-braces.html#:~:text=Braces%20%7B%20%7D%20not%20required%20for%20one,guides%20recommend%20always%20using%20them.)
In dart, "if" is not always a statement. In collection literals, single-expression "if" without "else" is the most common use case: 
```dart
var list = [
  if (x != null) x,
  // etc.
];
```
Even with a statement form, whenever you have complex logic, things become unreadable very quickly:
```dart
if (cond) {
  if (cond1) expr; // you'd better you braces here
  if (cond2) expr1;
} else {
  // something similar  
}
```
"Control flow" argument is not very convincing: this is a kind of micro-control-flow, but for micro-control-flow, we have a number of other operators, `??`, `?:`, `&&`, `?.` etc., which also could be written as if-else.

**Comment by Agondev** [comment]
> Keep in mind, you can already do this in one line:
> 
> ```dart
> if (Navigator.canPop(context)) Navigator.pop();
> ```
> 
> I don't really think an expression form is needed, since this is inherently a statement with control flow.

1. Doesn't always work. Don't remember if it's a linter error or warning but either way, it leads to the (2) below.
2. Auto formatter can randomly choose to move the second part into a new line. Methinks it mostly depends on the amount of characters (80) in line, but it it's inconsistent, so I don't like it.
3. I prefer ?> over if(). Personal preference. Doesn't mean the other option should go away, much like one isn't forced to use ternaries.

**Comment by lrhn** [comment]
The *language* allows unbraced `if` branches. The official language style guide allows it if it stays on one line, and the formatter respects that when possible.

> Indeed, the braceless form of "if" exists, but it's ugly. I don't like it, and I don't know anyone who does.

And I like it 😁.

Some project specific style guides goes further and disallows unbraced `if` statements, for whichever reason makes sense to them (want control flow to be more visible, want consistency without exceptions, something third I don't know of).

I'd wager that the same style guides would also disallow such a `?>` operator for all the same reasons, which makes adding another way to have a one-line conditional statement not really seem valuable.

**Comment by tatumizer** [comment]
The reason you like it might have something to do with the absence of alternatives. As soon as dart introduces `?>`, the temptation to use it will become irresistible, and you will remember 1-line `ifs` only as a misguided practice of the past :-)

The fact is: dart supports 3-part "if" expression `?:` and a whole zoo of other conditional expressions. IMO, 2-part "if" would be a valuable addition to the zoo. It should be considered as another micro-tool among the existing micro-tools (rather than an isolated ad-hoc case). In some contexts, ternary `?:` looks good; in others - not so much. It's the responsibility of the programmer to choose the right tool for the right task.  In principle, you can always rewrite `?:` as if-else, but it's not always the best idea. Similarly, you may choose 1-line `if` or `?>` depending on the context.

Observation: Some style guides frown upon braceless forms of `if`, `while`, `for` etc. But if these forms are disallowed, the parentheses around the condition become redundant. E.g.
```dart
if (a > 1 && b > 1) {
   //...
}
```
With the mandatory braces, this could be written without `()`:
```dart
if a > 1 && b > 1 {
   //...
}
```
Most newer languages do it this way. Maybe some future dart 5 decides to take this route, too? Then `?>` will come in quite handy!

> The language allows unbraced if branches. The official language style guide allows it

Style guides often contradict each other. Flutter style guide [doesn't like 1-line ifs](https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#separate-the-if-expression-from-its-statement).

**Comment by Agondev** [comment]
I should also note that my OCD wants to shave off those extra 4 or 6 characters, ```i```, ```f```, ```(```, ```)```, ```{```, ```}```.

And sorrounding those brackets around and including ```if``` is _slightly_ more work then just skipping the them entirely and appending a ```?>``` after the conditional.

The brackets, also, in themselves are redundant (optional for our purposes), and a relic of dino conventions. Keep them for onboarding new devs for familiarities' sake, but make them optional for special snowflakes like myself. Hence the introduction of ```?>```.

**Comment by munificent** [comment]
I'm going to close this because I don't think it adds any significant value over current syntax. If we want to give users multiple ways of accomplishing the same goal, the new ways should either be noticeably better, or should at least be clearly better in some specific circumstances that the previous syntax doesn't handle well. I don't think either of those apply here, so it's unlikely we'd do this. Having two equally appealing ways to do the same thing just makes them spend mental effort making a choice without giving them anything of value in return.
