### ISSUE TITLE
Void arguments should not be required to be explicitly defined

### ISSUE THREAD

**Issue by cedvdb** [dart-lang/language#2040]
Use case:

```dart
void main() {
  final a = Thang();
  final b = Thung();
  a.start(input: null);
  // this should be allowed without the need for an explicit override
  // a.start();
  final b = Thung();
  b.start();
}

class Thung extends Thing<void> {
  @override
  start({void input}) {  }
}

class Thang extends Thing<void> {}

abstract class Thing<T>  {
  start({required T input}) {}
}
```

**Comment by Levi-Lesches** [comment]
First of all, I don't think you're using `void` right. It's rare to see `void` used as an input, so let's talk about it as an output first. When you return `void` from a function, you're not saying that the function doesn't return anything, rather that whatever value is returned should be ignored by the caller. Every function that doesn't have an explicit `return` statement implicitly returns `null`, but `void` says that we should never even check that in the first place. To demonstrate: 

```dart
void number() => 3;
void nothing() {}
dynamic maybeNothing() {}  // not void

void main() {
  final void value1 = number();  // ok
  print(value1);  // error: This expression is 'void', so it can't be used

  final void value2 = nothing();  // ok
  print(value2);  // error: This expression is 'void', so it can't be used

  final value3 = maybeNothing();  // ok
  print(value3);  // ok, prints "null"
}
```

As you can see, all three functions do return something, but by marking it `void`, the caller can never use that value. With that in mind, let's think about `void` as an input. 

`void` doesn't mean the parameter is optional, it means that whatever object is passed through should be ignored by the constructor. So you still need an object as an argument, but it can be a string, number, null, or whatever. As you can see, it doesn't make much sense to declare a `void` parameter -- if you really don't care about the type, `Object?` or `dynamic` works better -- but it still is possible: 

```dart
void print1(dynamic obj) => print(obj);  // ok, can be anything
void print2(Object? obj) => print(obj);  // ok, can be null
void print3(Object obj)  => print(obj);  // ok, can't be null
void print4(void obj)    => print(obj);  // error, cannot use obj
```

----

Anyway, back to your example, hopefully you can see why overriding with `T = void` doesn't really fix your problem. Instead, the issue is that `a` is a `Thing`, whose `.start` method declares a `required` parameter. So to rephrase your question, you're asking "why is omitting a `void` parameter sometimes okay if passing `null` instead is always ok?". 

I think it makes sense if you think about it closely: 
- class `A` (`Thing`) declares a required parameter -- type can be anything
- class `B` (`Thang`) extends from `A`, so it too declares a required parameter -- the type can still be anything
- class `C` (`Thung`) extends from `A` but _overrides the `required`_. So it not only accepts `null`, but also allows omitting the parameter entirely to get null, which is still allowed because the type is marked `void`, which is inherently nullable. This would be more obvious had you used a different type: if you had `Object`, it wouldn't work, and if you had `Object?`, it would.

Hopefully this code is a little clearer: 

```dart
class A<T> {
  void start({required T input}) { }
}

class B extends A<void> {
  //implicitly inherited: 
  void start({required void input}) { }
}

class C extends A<void> {
  //explicitly overriden: 
  @override
  void start({void input}) { }
}

void main() {
  final b = B();
  final c = C();
  
  // B.start declares a required parameter of type void
  b.start();             // error, 'input' is required
  b.start(input: null);  // ok
  b.start(input: 42);    // ok, but lint "don't assign to void"
  
  // C.start declares an optional parameter of type void
  c.start();             // ok
  c.start(input: null);  // ok
  c.start(input: 42);    // ok, but lint "don't assign to void"
}
```

**Comment by cedvdb** [comment]
The use case where you insist on the user passing null (instead of providing a default) `required T? property` makes sens.

On the other hand I don't see the use here to have to set a property that is not going to be used.

**Comment by Levi-Lesches** [comment]
So from what I can tell it seems you have a superclass `abstract class Task<Input, Output>`, and `Task.start` declares `input` to be required. Then you seem to have something like `class SubTask<Output> extends Task<void, Output>`, and you're wondering why you still have to pass in `input` when it shouldn't actually be used. 

I suppose the answer is your choice of making `Task.start` force `input` to be required. In that case, you're essentially saying "all uses of this class will need to care about the input", which isn't actually true in some cases, where `input` is actually completely irrelevant and shouldn't even be passed in at all. Seems like you _should_ go the other way, ie, making `input` optional and only force it to be required in some circumstances where you know you'll need it. 

I'd need to see more about your class layout to figure out how to optimize it, but so long as you're declaring `required` on a superclass, it's not a bug for Dart to enforce it, nor should it have a choice. It'd be pretty weird if `required` actually meant "optional" in some cases.

**Comment by cedvdb** [comment]
you are onto something here. I'll be closing this issue then as I'm not really sure anymore of what's going on.

I actually lied in my last comment, the input is used. Well I didn't lie but after checking the code again the input is used and your first comment was relevant too:

```dart
  Future<void> start({required I input}) {
    if (state.status == Status.ready) {
      _setState(
        TaskRunning(input: input, isLoading: true),
      );
      return execute(input);
    }
    return Future.value();
  }
```

The issue I had was that I did not want Tasks that did have an input to have to do null checks everywhere..

**Comment by tatumizer** [comment]
@Levi-Lesches:  your understanding of `void` is incorrect, which can be seen in the following passage
> As you can see, all three functions do return something, but by marking it void, the caller can never use that value. .

That is not true.
```
void foo()=>1;
main() {
  print(foo() as int); // prints 1
}  
```
If the variable has a type "void", it can be used, but only after type cast.
The rest of the explanation also suffers from a general misunderstanding of what `void` is.
The strangeness of `void` type can be explained by historical reasons (dart 1 was a dynamically typed language), but at this point this is immaterial.

**Comment by cedvdb** [comment]
Just a question though. In your mind was the use of `void` wrong in the above snippet and `Null` should be used instead ? This gives a lint message to use void instead.

**Comment by cedvdb** [comment]
I'm quite confused as if Null or void should be used in this case now. Null gives a lint warning.

**Comment by Levi-Lesches** [comment]
@tatumizer, by casting the value from `void` to something else, it's no longer `void` -- it's something else. I made it clear that `void` doesn't get rid of a value, and the object can still be passed around and stored, but so long as that value is marked `void`, it's unusable. 

@cedvdb, if your problem is that you keep passing `input` into `execute` even though it's not always used, I'd say that's probably not really much of a problem, assuming that it sometimes _is_ used. By having it set up that `execute` accepts the parameter, you can call it the exact same way whether `execute` actually needs that parameter or not.

**Comment by tatumizer** [comment]
@cedvdb: please read my comment above.
"void" is basically the same as "dynamic", with the difference that to use `dynamic`, you don't have to do a type cast; for "void", you have to. It doesn't matter whether `void` is passed as input or returned as output or declared as a variable.

**Comment by cedvdb** [comment]
Both dynamic and void are incorrect in this case though. I'll have to modify my data model.

**Comment by Levi-Lesches** [comment]
Perhaps if you abstract some of your class hierarchy and how it's used, I can try to reccomend an alternative. Note that you should be avoiding `dynamic` and `void` when representing a safe value. `Object`, `Object?` and `Never` are some good alternatives, but I personally hardly use `Never`.
