### ISSUE TITLE
[Spec, Grammar Grammar] Some minor syntactic inconsistencies.

### ISSUE THREAD

**Issue by modulovalue** [dart-lang/language#2049]
I have written a parser that extracts all grammar rules and parses them into a DSL. These are possibly some very minor inconsistencies:

* There are no productions for the ref 'typeIdentifier' in production 'constructorName'.
* There are no productions for the ref 'typeIdentifier' in production 'constructorDesignation'.
* There are no productions for the ref 'typeIdentifier' in production 'qualifiedName'.
* There are no productions for the ref 'typeIdentifier' in production 'qualifiedName'.
* There are no productions for the ref 'typeIdentifier' in production 'qualifiedName'.
* There are no productions for the ref 'typeIdentifier' in production 'typeName'.
* There are no productions for the ref 'typeIdentifier' in production 'typeName'.
* There are no productions for the ref 'typeIdentifier' in production 'typeAlias'.

They were probably meant to be `typedIdentifier`?

* The `<assertion>` production has an extra space between the last <expression> and the right parens. (This is the only place, it's consistent everywhere else, so I thought I'd mention it)
```
<assertion> ::= \ASSERT{} `(' <expression> (`,' <expression> )? `,'? `)'
                                                            ^
```

* There are no productions for the ref 'EOF' in production 'libraryDeclaration'.
* There are no productions for the ref 'EOF' in production 'partDeclaration'.

EOF is not a declared production, and it isn't mentioned anywhere else. While it's obvious what it means, wouldn't it be more correct if it would be a special symbol the way `.*?` is and not a reference to a production?

* I was surprised by `.*?`, but there's a section that explains it. 

However the Notation section doesn't mention it.

* I was surprised by the leading pipe and thought it was a typo ...

... but it wasn't, see: https://github.com/dart-lang/language/pull/2048. I think the meaning of the leading pipe isn't mentioned anywhere in the spec.

**Comment by eernstg** [comment]
Have you considered using the [specification grammar](https://github.com/dart-lang/sdk/blob/main/tools/spec_parser/Dart.g) as your starting point, rather than extracting grammar rules from the LaTeX source of the language specification?

The specification grammar is an ANTLER v4 specification, and it is used internally for several purposes: For instance, it conveniently supports experiments with the syntax of new language constructs, and it allows us to continually check that Dart as it is expressed in our test suite has syntax errors in locations where the Dart tools also raise an error, and only in such locations. The specification grammar is maintained along with the language specification, and the two are kept in sync.

One property which is not expressed formally in the language specification grammar (it is mentioned in the associated text, using natural language) and which is not a context free property is that string literals must have balanced usages of the non-terminals that enable string interpolation. This is handled using general purpose coding (Java code, in this case), pushing and popping some special tokens on a stack during parsing.

Similarly, we use general purpose coding to handle the fact that `yield` and `await` are treated as reserved words when they occur in a function body that has the modifier `sync*`, `async`, or `async*`, and as plain identifiers otherwise. We could have expressed this property in a context free manner by duplicating all grammar rules associated with expressions and statements and adjusting one copy to treat `yield` and `await` as reserved words, and the other copy to treat them as identifiers, and then used the relevant copy for parsing each function body. We did not do that, because of the amount of redundancy involved. (We could of course also have used various notions of parser generator 'states', but we preferred to make this non-context-free element of the syntax explicit and simple.)

It should be noted that the Dart grammar has always relied on disambiguation based on the ordering of the derivation rules (similarly to PEGs), which is conveniently compatible with the top-down parsing strategy (an extended version of recursive descent) that the Dart tools have always used.

In general, this means that the Dart grammar isn't completely context free (which is of course a property that is shared by many practical languages), so any strategy which is based on mechanically extracting the grammar rules from the language specification and using those rules as input to a parser generator for context free languages will fail. For instance, an LR parser generator will report a lot of shift/reduce or reduce/reduce errors.

It seems likely that it is a more productive approach to use the ANTLR v4 specification which is already working (that is, the specification grammar), or at least to use an approach which has this rule-order-based disambiguation mechanism.

For the more detailed comments:

> There are no productions for the ref 'typeIdentifier'

This non-terminal is defined in the associated text, [here](https://github.com/dart-lang/language/blob/bdbef03e26047a1f59152f97d23663cf93a7108e/specification/dartLangSpec.tex#L19977). In the specification grammar it is defined bottom-up. This form is more verbose, which is the reason why it is not used in the language specification, but it is simple to understand and parse, which is the reason why it is used in the specification grammar. Basically, a `<typeIdentifier>` is an identifier which is not a built-in identifier, and a built-in identifier is a member of an explicitly defined list of tokens.

> They were probably meant to be `typedIdentifier`?

No, a `<typedIdentifier>` is `<type> <identifier>`, and it is used to declare variables and parameters.

> The `<assertion>` production has an extra space

Thanks, that's not intended! It makes no difference formally, because the whitespace around meta-syntax never matters (in this case we have a meta-parenthesis around a sentential form, <code>(`,' <expression>)</code>, and we could have written that as <code>(`,'<expression>)</code> or <code>( `,'  <expression>  )</code> without changing the meaning, but it's more readable when we're using whitespace in a specific and consistent manner).

> There are no productions for the ref 'EOF'
> .. while it's obvious [it should be explained]

Agreed!

> I was surprised by the leading pipe

There is nothing special about that pipe: It just happens to separate two alternatives where the first one is empty. We could introduce a special notation (e.g., `\varepsilon`, 𝜀) for "the empty sequence of lexical tokens", and lots of grammar related textbooks would do that, but I don't think it's unreasonable to represent the empty sequence of tokens by nothing (other than whitespace).

Thanks for the input, I included the fix to the `<assertion>` whitespace and a sentence that defines `EOF` in an upcoming PR on the language specification.

**Comment by modulovalue** [comment]
For now, I just wanted to visualize the Dart grammar, and have that visualization stay up to date with little effort.

Everything went fine and if you ever wanted to know, here's what the Dart grammar looks like laid out via graphviz:

* generated from the antlr spec:
[dart_antlr_graph_in_progress.pdf](https://github.com/dart-lang/language/files/7822066/dart_antlr_graph_in_progress.pdf)

* generated from the latex spec:
[dart_spec_graph_obsolete.pdf](https://github.com/dart-lang/language/files/7822064/dart_spec_graph_obsolete.pdf)

I do plan to eventually generate a parser and your comments will be very helpful.
Thank you for your help!
