### ISSUE TITLE
Scoping issue with super parameters

### ISSUE THREAD

**Issue by eernstg** [dart-lang/language#2056]
Consider the following program:

```dart
class A {
  bool b;
  A({this.b = false});
}

class B extends A {
  final bool b2;
  B({super.b}): b2 = b {
    b = !b;
  }
}

void main() {}
```

This program is accepted by the CFE with `--enable-experiment=super-parameters` (in particular, `dart` from 05b19a2218a72d59ed2c826e362fb00774ba46f8), but rejected by the analyzer (same commit), with the following error message:

```
ERROR|COMPILE_TIME_ERROR|ASSIGNMENT_TO_FINAL_LOCAL|/usr/local/google/home/eernst/lang/dart/scratch/202201/n004.dart|10|5|1|The final variable 'b' can only be set once.
```

This implies that the super-parameter declaration `super.b` causes the name `b` to be entered into the initializer list scope of the `B` constructor as a reference to the parameter (because both platforms allow for the use of `b` as an expression in the initializer list). This is fine, and it is consistent with the [feature specification](https://github.com/dart-lang/language/blob/master/working/1855%20-%20super%20parameters/proposal.md#introduced-names-in-initializer-list).

However, when it comes to the body scope of the constructor, the CFE and the analyzer disagree: The CFE does _not_ enter the name `b` into the body scope as a reference to the parameter, which means that `b` in the constructor body refers to the instance variable, and this allows for expressions like `b = !b` without error. The analyzer _does_ enter the name, so `b = !b` would be an assignment to the parameter (the instance variable is shadowed), and this is rejected because a super parameter is always final.

The "obvious" remedy would be to say that the analyzer should behave in the way that the CFE currently behaves, because we want to be able to access the instance variable in the constructor body, exactly like we do with initializing formals.

However, this introduces an anomaly, because there is no guarantee that the name of the super parameter is also the name of an instance variable:

```dart
class A {
  bool x;
  A(int i): x = i != 42;
}

class B extends A {
  int j;
  B(super.x): j = x { // `x` is an `int` parameter.
    print(!x); // `x` is a bool instance variable.
  }
}

void main() {}
```

This could easily be taken as a strong hint that we should follow the analyzer, such that `x` refers to the parameter, both in the initializer list and in the constructor body.

However, that does still create a confusing discrepancy in the first example above, because this makes `this.` and `super.` behave differently with respect to the scoping.

I tend to recommend that we follow the CFE, but then also that we _hint_ the situation where a super parameter "shadows" an instance variable (both when that instance variable is declared in an enclosing scope and when it is inherited), but the super parameter is _not_ associated (in one or more superclass steps) with an initializing formal with the same name.

@natebosch, @munificent, @lrhn, @leafpetersen, @stereotype441, @jakemac53, WDYT?

[Edit: Changed the constructor body from `=>` to `{}`, that's a separate topic.]

**Comment by jakemac53** [comment]
My intuition is that it should behave exactly like the expected desugaring, so a new parameter is declared with the same name as the super parameter, and the parameter is in scope in both the constructor body and initializer list.

To access the instance getter you must use `this.`.

+1 for hinting in this situation though as it may be confusing.

**Comment by lrhn** [comment]
About `B({super.b}): b2 = b => b = !b;`... can you have arrow bodies in generative constructors? (Please say no! If yes, like, why? And like, don't!)

The `this.x` initializer list variable `x` is only in scope in the parameter list. It's not in scope in the body. We made that design deliberately when we introduced the variable. It is *not* something you can just desugar to a normal parameter of the same name (it *is* something you can desugar to a parameter with a fresh name, and alpha-renaming of all accesses to the variable).
I can see that super-initializers differ in that even if you have a `super.x`, there might not be any instance variable named `x` at all (it forwards `x` to the super constructor, the super-constructor parameter `x` doesn't have to be an initializing formal).

My first intuition is still that I want the super parameters to work in exactly the same way as initializing formals: Only introducing a variable in the initializer list, not in the body.

If it's initializing a super-field, you have a way to access the variable in the body (`super.x`, like it said in the parameter list), and in *most* cases also just `x`. In those cases, making `x` instead access the final variable is likely to be wrong. (OK, likely to be completely unnoticed, but when not, then it's probably wrong.)

It's slightly annoying that the value is only available in the initializer list, not in the body. For `this.x`, we are guaranteed that the field holds that value and is easily accessible in the body. For super, we don't know that, it might be impossible to get the value out of the `super` API again.
So, if you need the value again in the body, you'll have to rewrite to not use `super.x`, which is annoying. But probably not very common.

**Comment by jakemac53** [comment]
> The `this.x` initializer list variable `x` is only in scope in the parameter list. It's not in scope in the body.

I am curious what the observable difference is here, given that you can't define another parameter with that name?

**Comment by eernstg** [comment]
@jakemac53 wrote:
> My intuition is that it should behave exactly like the expected desugaring

Thinking about it some more I tend to agree: We do not in general have a situation where a super parameter named `n` is associated with an instance variable named `n`, and we'd have to have several things lined up before the super parameter does have such an association.

This means that a super parameter is less like an initializing formal than I thought at first, and in that situation it seems most consistent to treat it like a regular parameter, not like an initializing formal.

This would mean that we follow the analyzer, and the CFE would need to change.

@lrhn wrote:
> can you have arrow bodies in generative constructors?

The grammar allows it, but it implies that something is returned, so I agree that we should introduce a rule to make it an error. The specification gets close to saying that it is an error to have a function body of the form `=> e` in the case where `{ return e; }` would be an error, but as far as I can see it doesn't actually say that.

I adjusted the initial issue to use a block body, to avoid mixing the topic of this issue with the constructor body topic.

> My first intuition is still that I want the super parameters to work in exactly the same way as initializing formals

This is the point that I do not agree with any more, I think the super parameters are semantically too different from initializing formals to make that work well.

**Comment by eernstg** [comment]
The constructor `=>` error is added in https://github.com/dart-lang/language/pull/2064.

**Comment by lrhn** [comment]
The problem here is that while `super.x` does not necessarily correspond to an instance getter named `x` (like `this.x` definitely does), it *can* correspond to such a getter.

If the `this.x` initializing formal keeps out of the body scope, so you can use `x` to refer to the instance variable `this.x`, not the introduced final variable `x`, it might be confusing to users that it *doesn't* work for `super.x` when `x` would refer to that instance variable.

I think we should be *consistent* in the scoping between the two special formals, even if they are not completely analogue, because otherwise we are *inconsistent* in the cases where they *are* similar.

I'm fine with allowing `this.x` and `super.x` to introduce a variable that is *also* in scope in the body. (I originally argued for this when we introduced the variable, because then we could explain `this.x` as a simple desugaring. We did not do that because of worries that people would mistakenly assume `x` would refer to the instance member in the body (and because it would be breaking for existing code, and we didn't have language versioning back then).

I'd also be fine with both `this.x` and `super.x` introducing a final local variable that is only in scope in the initializer list, like we do for `this.x` now. This is safe. Anyone writing `x` to access the value will get an error if it's not there.

I'm also somewhat fine with not letting `super.x` introduce a local variable at all. I just expect we'll get requests for it, like we did for `this.x`.

I'm not fine with treating the two similar constructs differently, so that `this.x` is not accessible in the body, but `super.x` is, even when `x` would refer to the actual instance variable initialized by the super argument. I think people would expect that to work.

**Comment by eernstg** [comment]
@lrhn wrote:
> I'm not fine with treating the two similar constructs differently

Isn't overemphasizing the syntactic similarity of two constructs whose semantics is really different?

**Comment by lrhn** [comment]
@eernstg Every argument here sounds like it applies equally to an initializing formal, so should we let the variable of an initializing formal cover the body too?

**Comment by eernstg** [comment]
> should we let the variable of an initializing formal cover the body too?

My first reaction is that this would cause a non-trivial amount of breakage (even though a fix could be performed mechanically), so we probably don't want to pay the transition cost. Similarly, there would be a breaking-change cost associated with adjustments of the brain of every developer who's gotten used to the current rule.

Apart from that, I think it would be OK to let initializing formals be in scope in the constructor body, because developers have `this.` available when they need to access the instance variable. But I still think that it's a little bit better to keep the current rules for initializing formals than it is to put them into the body scope as well.

There is a third option that I did not mention (because I thought that it would be universally shunned), and that is to put a super parameter which is associated with an initializing formal with the same name into the initializer scope alone, and all other super parameters in both scopes. This would allow the super parameters that work similarly to an initializing formal to behave like those, and all other super parameters to work like any other parameter. (Hiding, awaiting loud frowns ;-)

**Comment by munificent** [comment]
> I do think an initializing formal should also introduce a variable that is available to the body, and if we could make that change I would do it.

I don't.

> > The `this.x` initializer list variable `x` is only in scope in the parameter list. It's not in scope in the body.
> 
> I am curious what the observable difference is here, given that you can't define another parameter with that name?

The problem is that it means a closure in the constructor would capture the field and not the parameter:

```dart
class C {
  String field;
  late void Function() callback;
  C(this.field) {
    callback = () { print(field); };
  }
}

main() {
  var c = C('before');
  c.field = 'changed';
  c.callback();
}
```

This prints "changed", which is (probably) what users want. If we kept the parameter in scope in the body, it wouldn't. It's very common to wire up callbacks and event handlers inside constructor bodies. (You can't do so in the initializer list because you don't have access to `this` yet.) In those closures, I am pretty certain users want to close over the instance's fields and not any parameters that happen to have initialized those fields. I think we made the right call with initializing formals.

When I was looking at constructors in the wild, I can't recall a single one that actually accessed the super-initializing parameter in the body too. Like 99% of the time, the only thing the parameter is used for is to forward to the superclass. I think we can leave it not in scope in the subclass constructor body without users even noticing. So I think we could not have it in scope in the body without many users noticing.

In the cases where they *would* notice... I don't have a good intuition as to whether they *intend* to access the parameter or access a field/getter on the superclass. Even if the author has a certain intention, it's not clear if other readers of the code will. It's probably safest to leave it not in scope in the body and have users make their intention clear by *not* using `super.` if they want to access the parameter in the body.

That also makes it consistent with `this.`, which is probably a good thing. These are two rare edge cases that users are unlikely to learn. So if they *do* learn one, it's probably good if they can carry that knowledge over to the other.

**Comment by cedvdb** [comment]
I'm surprised positionality is strictly respected here

```dart
class A {
  int x;
  int y;
  A(this.x, this.y);
}

class B {
   B(super.y, super.x); // probably a bug
}
```

My first intuition was that either the names had to match and dart would have done some magic behind the scene, either the name and position had to match.

Making this less of an issue :

```dart
class A {
  bool x;
  A(int i): x = i != 42;
}

// invalid (posted in the referenced issue) will not compile because super constructor only has i
class B extends A {
  int j;
  B(super.x): j = x { // `x` is an `int` parameter.
    print(!x); // `x` is a bool instance variable.
  }
}

// valid
class C extends A {
  int j;
  B(super.i): j = i {
    print(!x); // `x` is a bool instance variable.
  }
}
```

**Comment by leafpetersen** [comment]
> I think we should be _consistent_ in the scoping between the two special formals, even if they are not completely analogue, because otherwise we are _inconsistent_ in the cases where they _are_ similar.

+1 to this.

**Comment by leafpetersen** [comment]
We discussed this in the meeting this morning.  Notes:
  - There is agreement that putting the variables in scope in the body is the wrong thing to do, because of issues like the closure capture issue described above.
  - @munificent is going to do some corpus analysis to see whether having them in scope in the initializer list is in practice useful.
  - **For now, implementations should assume that the scope is limited to (but includes) the initializer list, just as with `this.` parameters**.  If we choose to restrict it further we will pro-actively communicate that as a change to the feature.

**Comment by pq** [comment]
> @pq, what do you think about linting this?

💯 

I'm in favor.  This is a potentially pretty confusing.

Tracked in https://github.com/dart-lang/linter/issues/3107 (cheers @eernstg! 🍻)

**Comment by cedvdb** [comment]
> SomeClass(super, super, super) {} and that would work basically just as well. But it's useful to require the names there for readability purposes.

> I don't think we want to change the feature to allow reordering positional parameters based on their name because that would break an important encapsulation property of positional names.

In essence, isn't it still breaking encapsulation when you bring in a lint rule ? Callers will still have to rename to obey the rule.

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/227901

**Comment by munificent** [comment]
> > We probably should consider a lint that warns if the super. parameter names don't match
> 
> In essence, isn't it still breaking encapsulation when you bring in a lint rule ? Callers will still have to rename to obey the rule, so to me it does. So does the encapsulation argument holds for reordering (quote 2)?

In general, no, we don't consider API changes that cause lints to fail to be breaking changes. In fact, probably the key distinction between a lint/hint/warning and a compile error is that the former are things an API maintainer should be allowed to cause to appear in downstream code without it being considered a breaking change.

If that wasn't the case, then no one would *ever* be able to use the `@deprecated` annotation because the entire *intent* of it is to make a hint appear in user code. You can think of lints/hints/warnings as a mechanism that specifically exists to allow API authors to apply some gentle backpressure onto their users to guide them without actually breaking their code, since they can always simply ignore the lint/hint/warning.

> I find that, given the arguments you have given above, a lint rule is inadequate.

What would you suggest instead?

**Comment by cedvdb** [comment]
> If that wasn't the case, then no one would ever be able to use the @deprecated

I'm referring to encapsulation in the widest sense, as privacy. Currently positional parameters are fully encapsulated. The difference with  `@deprecated` is that deprecated is used on public api which are not stricly encapsulated, if you change their name, the rest of the code does not compile, if you change positional parameters name, the rest of the code works just fine, no warning, no error. Privacy being the highest form of encapsulation.

 > What would you suggest instead?
 
I originally suggesting reordering positional parameters but it does break encapsulation which seems to be something that is not going to happen. My second argument was that if a lint rule is needed, which to me still breaks encapsulation, then reordering could be reconsidered. 

If breaking encapsulation is not going to happen then I don't think the lint rule is a good fit or the rule should be widened to all use cases. This seems quite in the same vein: 

```dart
class A {
  int x;
  int y;
  A(this.x, this.y);
}
void main() {
  int x = 3;
  int y = 4;
  final a = A(y, x);
}
```

More generally any method or constructor which are called with an **argument** at position `i` which has the same name signature as a **parameter** at a position that is not `i`, is either a bug or is really bad design.

**Comment by cedvdb** [comment]
> Unless it's deliberate.

The same can be said about the proposed lint rule

```dart
class A {
  int x;
  int y;
  A(this.x, this.y);
}

class ASwapped {
   B(super.y, super.x); 
 }
```

**Comment by munificent** [comment]
> Alternatively, I'd suggest either no lint rule at all or that the lint rule could be widened to all use cases.

A similar case where this comes up is method overrides and we already do have a lint if an overriding method uses different parameter names than the method it overrides.

**Comment by lrhn** [comment]
We could also choose to allow `super` as an entire positional parameter. It wouldn't introduce any local variable, and therefore it doesn't matter what its name is. It would, effectively, have a "fresh" name, only used to refer back to it in the super-invocation at the end of the initializer list.

The only place where the name of such a `super` parameter might matter is in DartDoc, but they can, heuristically, show the name of the parameter it forwards to. That might not be stable over time, because the super-class parameter might change name, but it doesn't matter since no-one will ever need to *write* the name in code.

**Comment by cedvdb** [comment]
> The only place where the name of such a `super` parameter might matter is in DartDoc, but they can, heuristically, show the name of the parameter it forwards to. That might not be stable over time, because the super-class parameter might change name, but it doesn't matter since no-one will ever need to _write_ the name in code.

Have you think about what is going to happen when the parameters name do differ ? Will the documentation just not be forwarded (would make sens given the lint rule). Something that also could work is forwarding the documentation and replacing the name with the child class name. However I feel like this will be quite brittle, the smallest typos will make the documentation confusing. That's one of the reason (as I mentioned above) that I'm worried about different names. I hope this is considered to not have this (hopefully) future doc feature broken.

**Comment by eernstg** [comment]
> what is going to happen when the parameters name do differ ?

Cf. https://github.com/dart-lang/linter/issues/3107.

**Comment by lrhn** [comment]
>  I think it would make sense to treat it as equivalent to super.n where n is the name of the associated parameter in the superconstructor.

Except that that makes the name of the positional super-parameter matter, and makes it a breaking change to change the name, in case someone was using the initializer list variable.
By giving `super` a fresh name, we avoid the possibility of depending on a positional parameter name from another class.

**Comment by eernstg** [comment]
> Except that that makes the name of the positional super-parameter matter

I should have restricted the meaning of that 'equivalent to'. The idea would be that it stops the complaint from the lint, not that it would add `n` to any scopes or otherwise make `n` available to code in general around that occurrence of `super`.

**Comment by munificent** [comment]
I analyzed a big corpus of code to see how often constructor parameters that could use `super.` are also referenced inside constructor initializers or the constructor body. The results are [here](https://github.com/dart-lang/language/blob/master/working/1855%20-%20super%20parameters/package_evaluation.md#super-parameter-scope). The summary is:

```
-- Use (69140 total) --
  66661 ( 96.415%): not used outside of super()  ==============================
   1426 (  2.062%): other initializer            =
   1023 (  1.480%): body                         =
     30 (  0.043%): other initializer and body   =
```

They are very rarely referenced except to be passed to the superclass constructor, so it shouldn't impact many uses if we don't put the `super.` parameters in scope in the body.

**Comment by munificent** [comment]
> Arguably, not allowing the name in the initializer list wouldn't hurt that many cases either, but I think consistency with `this.x` makes it worth the effort. (Also, you cannot access `this.x` in the initializer list.)

Yeah, I think it's generally a net win to require the name even if it's technically redundant. Names are nice for helping readers stay oriented.

**Comment by eernstg** [comment]
The language team decided that a super parameter should be added to the initializer list scope and not to the body scope of the constructor. In other words, the scoping properties of a super parameter are the same as those of an initializing formal parameter.
