### ISSUE TITLE
Question: Augmentation class access to generics

### ISSUE THREAD

**Issue by srawlins** [dart-lang/language#2058]
https://github.com/dart-lang/language/blob/master/working/augmentation-libraries/feature-specification.md

> A class, mixin, or extension declaration can be marked with an augment modifier:
> ```
> augment class SomeClass {
> ```

How do generics work here? Can the augmentation class blindly access `T`? Should the declaration be forced to declare all of the same type parameters? With the same names? And declare bounds?

**Comment by jakemac53** [comment]
I think the intention is you don't re-declare any of that stuff, but do have access to it. You can call members on mixins applied in the original declaration or the super class from the original declaration, etc. And so you would also have access to the type arguments. But you only specify the name of the type you are augmenting, all the rest would essentially just be boilerplate.

Granted, when augmenting a function you have to duplicate the parameters and return type, so that does seem a bit inconsistent.

**Comment by tatumizer** [comment]
The intention is (probably) to allow just adding "stuff". But some "stuff" changes the meaning. Can you add a generic parameter? Can you rename generic parameters?
Can you add "static" modifier? Can you make a variable that was not final in the original class final in the augmentation library?
If you make it final, will it still inherit the setter from the original declaration?
For every modifier/keyword, there will be a question of whether it's allowed to be added/modified or not.

**Comment by jakemac53** [comment]
> The intention is (probably) to allow just adding "stuff". But some "stuff" changes the meaning. Can you add a generic parameter? Can you rename generic parameters?

This is already spelled out:

> A class augmentation may specify implements and with clauses. When those appear, the specified superinterfaces and mixins are appended to the main class's superinterface and mixin lists, respectively.

**Comment by tatumizer** [comment]
The problem with the way how it's spelled out is that it never says what you are allowed to *repeat*.
E.g. can you say `augment class Foo<K extends Bar>` if the original definition says `class Foo<T extends Bar>` ?
Maybe the spec can say something like: if you repeat the stuff, it should be an exact copy of the original or something?
Or just disallow repeating anything but `class Foo`?

**Comment by jakemac53** [comment]
Sure we can/should add something that more explicitly says the _only_ clauses you are allowed to use are `implements` and `with`. That is the intention afaik with the existing text, its just only saying it in the affirmative but not clarifying that anything else is not allowed.

cc @munificent can clarify though if that is indeed for sure the intention, its at least how I interpreted it :).

**Comment by munificent** [comment]
> Can the augmentation class blindly access `T`? Should the declaration be forced to declare all of the same type parameters? With the same names? And declare bounds?

Yes, the augmentation can access `T` just like it can access instance and static members of the class that are declared in the main library. It cannot add new type parameters or change bounds on existing parameters.

@leafpetersen and I talked about this a while back. His suggestion was that an augmenting class should be required to exactly replicate the type parameters of the class it's augmenting. This doesn't accomplish anything technically—it's redundant information—but it makes the augmentation class look less weird because when you see uses of the type parameter in the body, you can see what they refer to. It's analogous to how an augmenting function is obliged to replicate the original function's parameter list.

One minor concern with this is that it does also force the augmenting library to import any types that are used in type parameter bounds, even though the import doesn't really *do* anything. But this is also true for having to import any parameter types when replicating a function's parameter list, so I suppose that's reasonable.

> Granted, when augmenting a function you have to duplicate the parameters and return type, so that does seem a bit inconsistent.

Yeah, but I think there's a distinction. When you inherit from a class or apply a mixin, it makes new members available inside the body of the class, but those members aren't *lexically scoped*. You don't actually see their names at the point where you have the extends clause.

But with function parameters and type parameters, those parameter names *are* lexically scoped so it would be weird to be able to access them without being able to see where they are declared in the augmentation library.

> Sure we can/should add something that more explicitly says the _only_ clauses you are allowed to use are `implements` and `with`.

The proposal later says:

```
It is a compile-time error if:

*   The augmenting type declares ... an `extends` clause.
    Only the main declaration can specify those.
```

So I think that's fairly clear.
