### ISSUE TITLE
enable to use generics in classes with const raw types

### ISSUE THREAD

**Issue by jodinathan** [dart-lang/language#2071]
Considering that is not allowed to extend `num` or any other raw type:

```dart
// this works OK:

void foo<T extends num>(T arg) {
  print(arg);
}

foo(5); // OK

// this doesn't: 

class Foo<T extends num> {
  void foo(T blah) {
    print(blah);
  }
  void bar() {
    foo(5); // int 5 is not T
  }
}
```

**Comment by lrhn** [comment]
Since `T` can be both `double` and `Never`, using `5` as a `T` value isn't safe.

Even if we ignored `Never` as an option, `5` is not a `double`. If we have a `double` context, then we can statically convert the decimal literal `5` to the double literal `5.0`, but we don't here. We only know whether `T` is `double` or `int` at runtime, and at that point `5` has already been compiled as an `int` value.

The reason `foo(5)` works is that we infer the type argument, so it's doing really `foo<int>(5)`, which is fine.
Inside `Foo<T>`, the `foo(5)` call does not infer anything, `T` is known before we do the call, and `5` might not be a `T`.

**Comment by jodinathan** [comment]
but shouldn't it be allowed since 5 can be set in any subtype of `num` and we can't extend `num`?  
IIRC there is no variant of `T  = 5`, being `T` extension of `num`, that could be an error

**Comment by lrhn** [comment]
The `5` in the source is not a value, it's a literal. It evaluates either to the `int` with value 5 or the `double` with value 5.0 (if *statically* in a double context, it's a source conversion, not a value conversion).

Since the `int` value 5, the value of the literal `5` in a non-`double` context, is not assignable to `double` or to `Never` (which is a completely valid subtype of `num`), we cannot assume that it can be assigned to `T`. If `T` is `Never`, it can't.
If `T` is double, the *integer* 5 still cannot be assigned to `T`. The language does not have any affordance for converting a run-time integer to double implicitly. If it's not known *at compile-time* that a decimal literal should be a `double`, then it's not.

**Comment by jodinathan** [comment]
I guess it is a WAI then. Closing.
