### ISSUE TITLE
Thoughts on the macro api for instantiating types 

### ISSUE THREAD

**Issue by jakemac53** [dart-lang/language#2072]
We currently have this api on `TypeDeclaration`:

```dart
  /// Create a static type representing this type with [typeArguments].
  ///
  /// If [isNullable] is `true`, then this type will behave as if it has a
  /// trailing `?`.
  ///
  /// Throws an exception if the type could not be instantiated, typically due
  /// to one of the type arguments not matching the bounds of the corresponding
  /// type parameter.
  Future<StaticType> instantiate(
      {required List<StaticType> typeArguments, required bool isNullable});
```

I want to move this api off of the Declaration object for a couple reasons:

- These should all be simple wrapper objects, and not things that have to deal with sending RPCs.
- You should be able to "instantiate" arbitrary types in any phase after the first one - but you can't get to a `TypeDeclaration` from an arbitrary type annotation today until the final definition phase.

At first glance it seems like it makes sense to move the API to either the `TypeResolver` or `StaticType` interfaces (but `StaticType` might make the most sense). Both of these are only available in phase two and beyond.

However, there is one downside to this move, as well as the general move to dealing with `StaticType`s for this interface (from `TypeAnnotation`s). When declaring a new class, which extends an existing (macro annotated) class, how should you write the `extends` clause? Ideally this would be done through a type annotation.

Concretely, lets look at a theoretical builder pattern macro applied to a private class:

```dart
@generateBuilder
class _MyClass {
  final int myField;
  
  _MyClass._(this.myField);
}

// Generated
class MyClassBuilder implements Builder<_MyClass> {
  // ... actual implementation bits
  _MyClass build();
}
```

This presents two problems:

1. How should the `generateBuilder` macro write out the `_MyClass` annotation? They shouldn't just write the raw string of the name because that likely won't be in scope of the augmentation by default (this is a bit up in the air though).
  - We could say that `TypeDeclaration` has a `TypeAnnotation type` field, but that doesn't handle the case where we want to write a version of the type with some specific generic type arguments.
2. How should the `Builder<_MyClass>` type be instantiated? We have plans for an api to get a type annotation (or maybe static type) for some type known to the macro, but you still need to be able to instantiate that type with some generic type arguments.

## Proposal

One possible solution to these issues is the following:

- Add some api to get a `TypeAnnotation` for a type known to the macro itself (this is handwavy for now, specifics can be ironed out)
- Add a `TypeAnnotation type;` field to `TypeDeclaration`.
- Add a new interface `TypeInstantiator` which is available in phase 1. It has an `instantiate` method like above except that it is built in terms of `TypeAnnotation`s instead of `StaticType`s.

The main potential issue with this is it means we need to be able to create arbitrary type annotations, which point to types that may not actually exist yet, or are not yet resolved. Essentially the macro would look something like this:

```dart
import 'package:builder/builder.dart' reflected as builderPkg; // Borrowing some ideas from the reflected import proposal

class GenerateBuilderMacro implements ClassTypesMacro {
  Future<void> buildTypesForClass(ClassDeclaration clazz, TypeBuilder typeBuilder) async {
    builder.declareType(DeclarationCode.fromParts([
      'class ${clazz.name}Builder implements ',
      // The new `instantiate` api, returns a `TypeAnnotation` with some type arguments and
      // nullability suffix 
      await typeBuilder.instantiate(
          // A TypeAnnotation for the Builder class from the reflected import
          builderPkg.Builder,
          typeArguments: [clazz.type],
          isNullable: false), 
      ' {\n',
      // The new `type` field on `ClassDeclaration`.
      clazz.type,
      ' build();', // fill in actual implementation of this later probably
    ]));
  }
}
```

Thoughts on this general idea?

**Comment by scheglov** [comment]
I think we should try to stick to converting semantic `StaticType`s into code, with all necessary imports added, prefixes as necessary. So, we should be able to ask for `TypeDeclaration`s. For known types this is not an issue - here `Builder` must be linked before the macro generator is run. For `_MyClass` this is also not an issue - we cannot introspect it, but we can create a `TypeDeclaration` (and type parameters) for it - just cannot ask what are its super-type, interfaces.

It is a service - write a `StaticType`. If the macro author does not want to use it, and prefers to write just random strings as types - sure, but it might be not compilable code.

**Comment by jakemac53** [comment]
> I think we should try to stick to converting semantic `StaticType`s into code, with all necessary imports added, prefixes as necessary.

Just to make sure I understand you are saying basically that we shouldn't allow the `TypeAnnotation` instances in `Code` objects - but instead only allow `StaticType` instances?

That makes a lot of sense to me, and I think has the following other implications:

- We should add a `StaticType staticType` getter to `ClassDeclaration` (same as above proposal basically but a `StaticType`.
- We should put the `instantiate` api on `StaticType`, the type arguments would also be static types.
- Types from reflected imports (or whatever feature we end up with) should be `StaticType` instances, not `TypeAnnotation`s.

We probably also need a way to ask what the type parameters are for a `StaticType` then, so that you can know how many type parameters exist and what their bounds are. But that gets a bit tricky since in phase one you would be able to get a `StaticType` for a `ClassDeclaration`, but we can't actually tell you anything about the bounds on the type parameters yet. We could make the bounds be a `List<TypeAnnotation>` but that feels weird.

**Comment by scheglov** [comment]
We might have a different terminology here, but right now it does not sound correct to me.

In the analyzer we have `AstNode`, `Element` and `DartType`. So, `AstNode` can be unresolved, `Element` is created without many properties set but eventually is linked and has everything set, and `DartType` is exposed as properties of `Element` - implemented interfaces, return types, etc.

What you instantiate is an `Element`, usually a `ClassElement`. In macros we should get elements from reflected imports, to support references to functions for example. Can we generate code like `items.map(math.cos)`?

And `DartType` is a reference to the `Element` plus other `DartType`s as type arguments. And when we generate code, we write the `Element` reference - which might be local, or imported, with or without a prefix.

Type parameters of a type is nonsense, I spent quite a time getting rid of it in the analyzer. Please don't repeat the same mistake. An element, such as `ClassElement` has type parameters, but `DartType` is something already instantiated, with type arguments provided for every type parameter. There is no such thing as "raw" or un-instantiated `DartType`.

**Comment by munificent** [comment]
I think we're conflating two different operations:

1. When a macro is generating code, producing a type annotation that is an instantiation of a generic type.

2. When a macro is working with semantic types, producing an introspection object that represents an instantiation of some generic type. For example, if a macro wants to tell if some given type is a subtype of `List<int>`, it needs to create a static type object representing `List` instantiated with `int`.

As a *convenience*, we may also allow you to stick the object produced by 2 into generated code and get a valid type annotation inserted. But they are conceptually separate operations that produce different things. In particular, we may need to do 1 at a point in type where the types being instantiated aren't accessible or don't even exist yet.

> 1. How should the `generateBuilder` macro write out the `_MyClass` annotation? They shouldn't just write the raw string of the name because that likely won't be in scope of the augmentation by default (this is a bit up in the air though).

They shouldn't use the raw string, but all they need is an `Identifier`, not an actual `StaticType`. So the answer can be something like:

```dart
import 'package:builder/builder.dart' reflected as builderPkg;

class GenerateBuilderMacro implements ClassTypesMacro {
  Future<void> buildTypesForClass(ClassDeclaration clazz, TypeBuilder typeBuilder) async {
    builder.declareType(DeclarationCode.fromParts([
      'class ${clazz.name}Builder implements ${builderPkg.Builder}<${clazz.identifier}>' {\n',
      // The new `type` field on `ClassDeclaration`.
      clazz.type,
      ' build();', // fill in actual implementation of this later probably
    ]));
  }
}
```

Here, `clazz.identifier` is a proposed API on `Declaration` that returns a resolved `Identifier` for that declaration.

Then, for use cases where you need an actual `StaticType` that is an instantiation of a generic type for use in introspection and type tests, we can put an `instantiate()` method on maybe `TypeBuilder`. Possibly even on `StaticType` itself if we want a more natural object-oriented API.

Does that sound about right? I don't think we need to overcomplicate generic instantiations in generated code. It's just Dart syntax. The only part we have to worry about is identifiers in the type annotation, and `Identifier` should handle that.

**Comment by jakemac53** [comment]
Adding an `Identifier` interface seems like a good idea to help separate some of these concerns, should that actually be a subtype of `Code`? But not one that users can create themselves, it can only be provided by the system.

The current api uses `TypeAnnotation` for this purpose - but it's weird because those aren't necessarily resolved, and it would be nice to keep them more similar to just an AST node. But we do I think we would ideally have a way to go from a `TypeAnnotation` to a piece of Code, in any phase. For instance needing to copy the bounds of some type parameter on a class over to a newly generated class.  If augmentations have everything in scope that was in scope for the original library, you could just copy it over verbatim and not worry about what it resolves to.

**Comment by scheglov** [comment]
I think it is fine for macro generators to produce code just from strings, after all some method names can come from nowhere - just literals, and similarly it is fine to reference an identifier that the macro author knows is available because the use wrote it, or append something, like `class ${clazz.name}Builder ...`. Or a macro that annotates a class, but actually iterates over (unresolved) methods, and generates a new class for each method, using method names.

So, `Identifier` to access just names seems useful for the type phase. But being a `Code` - I don't understand why. If you need a name, ask the `String get name`. You don't have to use it as is, cut and splice it as you wish.

And `TypeAnnotation` is still with us, after all the return type of a method is not `Identifier`, it is a `TypeAnnotation`. On the types phase it is unresolved, all we have is names like `List<String>`. But still might be useful, if someone wants to generate `class ListOfStringBuilder ...` - why not?

On the next phase (declaration?) where types are resolved, could continue adding data to `Identifier` and `TypeAnnotation`, maybe in form of a subclass `ResolvedIdentifier` that also has `Element get element`, and `ResolvedTypeAnnotation` that has `StaticType get type`. But this way we would not get types that are not written, such as inherited from a superclass, or implicit `dynamic`. OTOH, we already discussed that some types, like inferred for fields, we are not going to provide. So, maybe just explicit types might be fine, and so adding resolution to AST nodes will work.

In the analyzer we link actual ASTs, so this will work for the analyzer. But I don't know for CFE.


And then there is a separate question of writing an arbitrary `StaticType`.

Reflected imports have an import prefix in the macro declaration library, but what would be the import prefix in the generated augmentation library? If it is the same, then the macro knows how to write a class from a reflected library just as a string; but if not - we need a way to ask such prefix, or a higher level API to get a string for a class reference.

And there are just random `StaticType`s from `ResolvedTypeAnnotation`s - these can reference elements from random libraries imported by the macro annotated class, or its superclass, etc. Or we don't allow looked at superclasses?

**Comment by tatumizer** [comment]
We have:
- Type
- StaticType
- TypeAnnotation
- DartType
- ResolvedTypeAnnotation
- Identifier (which can point to a type?)
- ResolvedIdentifier
- Code (not sure if it can directly wrap type identifier or not)

> We might have a different terminology here,...

Quite a bit of different terminology :-)
Could you find a way to simplify it somehow? (E.g. using the pattern from mirrors: `reflect(type)` could provide access to meta information. Or something?).

**Comment by jakemac53** [comment]
> So, `Identifier` to access just names seems useful for the type phase. But being a `Code` - I don't understand why. If you need a name, ask the `String get name`. You don't have to use it as is, cut and splice it as you wish.

The issue I am trying to resolve here is when you actually need to emit the same identifier that exists in the code you are introspecting over. Simply copying over the string representation isn't viable if augmentation files don't have all the same identifiers in scope. We could change it so they do have all those identifiers in scope, and maybe we should.

I agree there are plenty of use cases for just emitting strings.

**Comment by tatumizer** [comment]
I realized that I lost my faith in dart.
The direction the language is taking right now will soon destroy all remaining elements of style.
Without the style, it's just an eclectic collection of "features". What's the point of language design then? Just copy as many features you can from as many languages you can, and then wonder why people don't appreciate the language.
Sorry folks. If no one cares - I don't care either. 
I'm marking the comment as off-topic, will delete it next week (unless it gets deleted by someone sooner)

**Comment by Levi-Lesches** [comment]
> The issue I am trying to resolve here is when you actually need to emit the same identifier that exists in the code you are introspecting over. Simply copying over the string representation isn't viable if augmentation files don't have all the same identifiers in scope.

Sorry, can you elaborate? Is there ever an instance where a macro can't generate code that refers to an identifier in its applied library? Would the following then not work? 

```dart
@defaultConstructor();
class A { final int b; }

// generates an augmentation file: 
augment class A { 
  const A({required this.b});  // copied the indentifier `b` from A's code
}
```

**Comment by TimWhiting** [comment]
Why not have augmentation libraries "inherit" (or copy) the imports in the library being augmented, and recommend augmentation libraries import any "new" imports by prefixes to avoid clashing with the library being augmented. If the library is supposed to augment, I don't see why it shouldn't be able to reference things just like the library being augmented, rather than having to deal with knowing exactly where everything is coming from.

**Comment by jakemac53** [comment]
> Why not have augmentation libraries "inherit" (or copy) the imports in the library being augmented, and recommend augmentation libraries import any "new" imports by prefixes to avoid clashing with the library being augmented.

I think it's largely because they _can_ have their own imports, so it might be weird if you _also_ had implicit imports. But this is something we can change if we decide it's needed.

As far as usability for hand written augmentations goes I also think explicit imports are better - for instance one reason part files are bad dev experience is because you can't see (or modify) the imports directly, you have to go to the library being augmented.

It would also increase the likelyhood of conflicts between imports in the augmentation library and the original. These can be resolved with prefixed imports, but its still pretty weird if one of the imports is implicit.

**Comment by srawlins** [comment]
I definitely agree with this stance where imports are not inherited. I think it is much cleaner for an augmentation to not rely on the import namespace of the main library; no worries about import prefix conflicts (with its own imports); not even a question about deferred imports or conditional imports. Instead, we provide a nice API, a bit like code_builder has, to refer to identifiers, which are resolved with proper imports and import prefixes.

I don't think we foresee any strong difficulties in such an API (we're working through unresolved identifiers), but if they arise, or the API is seen as very cumbersome, we can revisit. I think this is very pragmatic.

**Comment by TimWhiting** [comment]
I agree that from a hygienic standpoint it is better to have it's own namespace / imports. However, from a macro debugging perspective, a user brought to the augmentation library might be confused to see all of the namespaced identifiers. (i.e. it won't look like an augmentation of their code and more of an obfuscation of an augmentation of their code). I don't know how to balance those tradeoffs, but I prefer making it a nice experience for users. Maybe there is another solution (i.e. if the import is in the augmentee's imports, then don't prefix the import as long as the set of identifiers exposed by the currently imported libraries don't conflict).

**Comment by jakemac53** [comment]
> However, from a macro debugging perspective, a user brought to the augmentation library while debugging their code might be confused to see all of the namespaced identifiers. (i.e. it won't look like an augmentation of their code and more of an obfuscation of an augmentation of their code).

I think the way it works now is a net win for users - looking at the augmentation file alone gives you all the context you need to understand the entire file. Everything in scope is immediately imported in that file.

You may see more prefixes than you would expect to (although in theory we could try to _not_ always use prefixes using various rules, sort of like the one you suggested). But overall I don't think it will hurt the readability too much even if everything is prefixed, and you will not have to go back and forth between the original file and the augmentation as much.

**Comment by scheglov** [comment]
@jakemac53 It seems to me that we still need only a way to reference a top-level element, such as a class while generating an augmentation library. All the rest either can be referenced with just a name, because the generated code know that this name is prefixed with a target expression, or it does not make sense (you cannot just randomly reference any method, you should go through a target expression to get it). And for top-level elements we have a mechanism get a reference to one - reflected imports, or get from a `StaticType`. Some method in a service object provided to every macro generation, like `writeElementReference(Element)`, which will add necessary imports, and use prefix if required.

Or are there other elements that I forget about?

I also like separate sets of imports for augmentation libraries. It might be convenient to inherit when you need something, but it becomes an inconvenience when you would rather not because of a conflict.

As for whether to import with prefixed or not, we can optimize it, first adding without a prefix, and track is there would be a conflict with a new import, and add a prefix for this new import; or give the generator to choose - maybe always import with prefix, or even the prefix itself.

**Comment by jakemac53** [comment]
> And for top-level elements we have a mechanism get a reference to one - reflected imports, or get from a `StaticType`.

The problem is the 2nd part of this - you can only get a `StaticType` after the first phase. But when declaring new types, you may need to reference existing ones.

**Comment by scheglov** [comment]
If we know where a name is declared, the URI of the library, such as the library where the macro annotation was used, then it is the same as reflected imports.

If we don't know, because the name was not resolved, then we cannot know which library to import. We cannot postpone code generation until we can resolve, because we resolve against potentially generated types. One option would be to resolve anyway, in many cases we will resolve against imported libraries, not macro-generated in this library cycle. We probably have to make it an explicit operation `resolveNameInLibraryScope()` and track if there is any macro that generated this name later, making it a failure.

In your example with `_MyClass` and generated `MyClassBuilder` we do know the location of `_MyClass`. Do you have an example in mind for the case when we don't?

**Comment by jakemac53** [comment]
> In your example with `_MyClass` and generated `MyClassBuilder` we do know the location of `_MyClass`. Do you have an example in mind for the case when we don't?

Yes - consider if `_MyClass` is a generic class with some bounds on the parameter (`_MyClass<T extends SomeTypeInAnotherLibrary>`). Now how do I generate the bounds for the `MyClassBuilder` class (it should have an identical type parameter)?

**Comment by scheglov** [comment]
OK, I see. We don't resolve, and so we don't know the location of elements. And we don't resolve because we may generate new types. So, maybe the macro generator should first state, which types it is going to generate, so we will able to resolve references to classes, and in the next pass fill the details about the generated types?

**Comment by jakemac53** [comment]
> So, maybe the macro generator should first state, which types it is going to generate, so we will able to resolve references to classes, and in the next pass fill the details about the generated types?

That would essentially amount to adding a 4th phase, which I would really like to avoid if possible.

Another idea is to allow you to emit a type annotation that is actually just a pointer to another type annotation. Basically it would mean "resolve this to the same identifier this other type annotation resolves to". The main issue I see with that, is it doesn't allow us to actually write out a valid library augmentation file in Phase one - we don't know what imports to add. The question I guess is whether or not we actually _need_ to create a valid augmentation after phase one, or if we can wait until after all phases are complete.

**Comment by munificent** [comment]
> Adding an `Identifier` interface seems like a good idea to help separate some of these concerns, should that actually be a subtype of `Code`?

Yeah, I think it should. An identifier conceptually is a well-formed syntactic Dart element: it's a valid kind of expression and identifiers appear in lots of other places in the grammar. So if you have an `Identifier`, then it should be a thing you can directly insert into some larger piece of code you are generating.

We could say that `Identifier` is only a subtype of `Fragment`. But since Dart has identifier expressions, I think it should be a subtype of `Code`. You could imagine a macro wanting to generate a field initializer that is literally just the value of some constant. In that case, the entire field initializer *is* just the identifier. If we make `Identifer` subtype `Code` then macro authors can use it directly as generated code.

If this ends up making the API too weird, though, I think it's reasonable to have `Identifier` *not* subtype `Code` and require users to "codify" it somehow if they want to create an identifier expression `Code` object.

> But not one that users can create themselves, it can only be provided by the system.

Yup. It may be that we don't give them an API to create `Identifier` instances from scratch. Instead, they can get them from declarations they have introspection access to. That will give them an `Identifier` that reliably resolves to that particular declaration.

If we do reflected imports, those can expose `Identifier`s for each top level declaration. And `NamedTypeAnnotation` could probably have an `Identifier` instead of a bare `String` for `name`.

> The current api uses `TypeAnnotation` for this purpose - but it's weird because those aren't necessarily resolved, and it would be nice to keep them more similar to just an AST node. But we do I think we would ideally have a way to go from a `TypeAnnotation` to a piece of Code, in any phase. For instance needing to copy the bounds of some type parameter on a class over to a newly generated class. If augmentations have everything in scope that was in scope for the original library, you could just copy it over verbatim and not worry about what it resolves to.

I think `TypeAnnotation` could *probably* be a subtype of `Code` too? It is basically a syntactic element.

**Comment by munificent** [comment]
As far as how to handle type annotations referring to declarations that don't exist yet, I'll try to summarize what we talked about today:

An `Identifier` is a string name that should be resolved in the context a given library's namespace. That doesn't mean the name resolves to a declaration *in* that library. It may resolve to a declaration imported by the library. It means that the name is resolved in that library's namespace.

Because top-level declarations may be added to libraries during macro execution, we can't necessarily resolve an `Identifier` when the object is first created. For example, imagine an `Identifier` associated with the type annotation in the `extends` clause here:

```dart
import 'a.dart';
import 'b.dart';

@someMacro
class Foo extends Bar {}
```

In phase 1, `@someMacro` can get a `TypeAnnotation` for the `extends` clause that contains `Identifier` for "Bar". But until the phase 1 macros in "a.dart" and "b.dart" have run, we don't know what it will resolve to.

Can we say that `Identifier`s are lazily resolved? As long as the implementation doesn't *need* to generate Dart syntax for the `Identifier` until after all phase 1 macros have run, we can probably say that resolution gets deferred. This implies that a `Code` object that was composed from some `Identifier` also needs to defer being compiled to Dart syntax.

Does this work?

I could imagine it being a prboelm if a phase 1 macro B needs to introspect on declaration produced by phase 1 macro A. That would presumably require the `Code` object returned by A to actually be compiled, which means any `Identifier`s it contains need to be resolvable by then. But as far as I can tell, the introspection API in phase 1 isn't powerful enough to let you do this, is it?

**Comment by jakemac53** [comment]
I have a proposed resolution to this out here https://dart-review.googlesource.com/c/sdk/+/230180.

Basically it:

- Adds an `Identifier` class, the only public member is `String get name`, but implementations should tie these back to the original AST nodes they came from. These can't be created by users, only given to them.
- Replaces most `name` getters with `Identifier identifier` getters.
- Updates many apis to take an `Identifier` instead of a `TypeAnnotation`. This definitely cleans things up some as TypeAnnotation was weird for a lot of these apis that don't care about type arguments etc, only the name of the type.
- Replaces the `instantiate` API on `TypeDeclaration` with two new apis on `TypeResolver`:
  - `Future<StaticType> instantiateType(TypeAnnotation typeAnnotation);`
  - `Future<StaticType> instantiateCode(ExpressionCode code);`
    - This one might be a bit weird, but it allows for a fairly intuitive way of constructing any arbitrary type (like function types with required params, etc).
- Removes the ability to pass `TypeAnnotation`s to `Code` objects, now you can pass `Identifier`s instead. You can however call the convenience `Code get code` getter on `TypeAnnotation`, and pass that to a `Code` object. We could implicitly invoke this if wanted to, and allow passing `TypeAnnotation`s directly again, 🤷‍♂️ .
- Removes the `IdentifierCode` class, it is confusing to have both. We already have `ExpressionCode` which can be used instead.
- We no longer expect setters to have a trailing `=` on the name - since names are no longer used to disambiguate, it is OK for two identifiers to have the same name they can be disambiguated by the AST node the originated from.
