### ISSUE TITLE
Should enhanced enums be able to define or mix in "values" or "index" members?

### ISSUE THREAD

**Issue by munificent** [dart-lang/language#2073]
@johnniwinther joined us in the language meeting today to talk about enhanced enums supporting user-defined `values` and `index` members. He wanted to get a sense for whether allowing that carries its weight. The concerns (from him and arising from our discussion) are:

1. It's not clear what the motivating use case is. Is this a thing actual users want to do to solve real problems? If not, is it something where most uses will actually be inadvertent *mis*uses? If it's a feature that is almost always used wrong, we'll likely end up with a lint discouraging users from touching it. At that point... why support it at all?

1. Allowing this will add complexity to the compilers. Currently, they can and do assume that they can access the `index` field and reliably get an integer back which they can then use when compiling switch statements or other operations on enums. Likewise, they assume they can use the `values` property to reliably get the list of all enum values for things like exhaustiveness checking. And they assume that the positions of the enum values in the `values` list reliably corresponds to the values returned by `index`.

    Allowing users to provide those members breaks all of that. The compilers will have implement another mechanism to determine the "real" enum value indexes. This is tractable, but it's non-zero engineering work.

1. It becomes a leaky abstraction. The for-in statement desugars to calling the user's own implementation of `iterate` and `Iterator`, whatever those implementations are. The semantics *are* the protocol. But we don't intend for switch to work that way. Even if a user does define their own `values` or `index` members, a switch statement on that enum type will not use them. (For example, if two different enum values return the same number for `index`, we don't intend for you to get a "duplicate case" error if you have a case for both of those.)

    This means that users implementing those members aren't implementing an "enum protocol". Instead, they're hijacking those names to refer to some new unrelated API. Meanwhile, the enum still retains its original but now hidden "real" enum protocol that things like switch and exhaustiveness checks use.

Given all this, it seems like the safest option might be to simply *forbid* an enum type from implementing (or mixing in) members named `values` or `index`. Essentially treat `index` as non-virtual and `values` as being already defined on the enum's class. This would allow the compilers to keep their simple implementations today and give us the freedom to come up with a different solution in the future if more insight comes to light by replacing the error with some provably useful behavior.

See also: #1939, #1947, #1994, #1995

Thoughts, @lrhn @leafpetersen @eernstg @natebosch @jakemac53 @stereotype441?

**Comment by stereotype441** [comment]
My personal opinion is to forbid it for now.  We can always change our minds later, after the rollout of the feature, if a clear use case arises that justifies the engineering expense and the risk of misuse and confusion.  But I think for now we haven't seen any sign of such a use case.

**Comment by lrhn** [comment]
Ad 1.
The argument for not forcing the existing enum notion of `values` on any new `enum` is that it would prevent implementing an interface with a member names `values`. (Because you can't declare a static member with the same name as an *inherited* member, for no real good reason.)

Most likely most people won't have a member named `values`, but for those would want to, making the existence of such a member preclude introducing the automatic static `values` constant, will make that possible.

I don't expect the use-case to be that you want to create your own "compatible" `values` constant.

The `index` getter is different. That's an instance getter and required by the `Enum` interface, so there's not a lot of wiggle-room for overriding.
I saw no reason to prevent you from overriding it, because no language feature is defined in terms of `index` so overriding is at best self-defeating, and we allow you to override `toString` (which is defined for enum values) and `==`/`hashCode`.
Disallowing overriding `index` would be an exception.

Ad 2.
Compilers using the `values` constant field seems wrong. The `values` getter exists at runtime, so compilers can't *call* it (although they might pretend to during `const` evaluation). If the compilers use the constant evaluation subsystem to get a list of "values" (not the same as the run-time values, because that program isn't running yet), then I'm sure there are lots of other ways for them to get access to the same list of constant values. If it's just making assumptions about the structure of internal compiler data structures for `enum` declarations, then again, there should be plenty of ways to do the same thing (like introducing a private static constant declaration with the same value and using that).

For `index`, it's again different because it's actually useful. That said, nothing prevents the compiler from accessing the field on `Enum` (or whichever superclass we use) directly instead of doing a virtual getter invocation on `index`, or just split `index` into a private field and a public getter, and then access the private field instead of the public getter.

Sure, it's easier to keep doing what we are already doing, but it shouldn't be *hard* to change.
(I can change `_Enum` to have a private `_index` and a public `int get index => _index` today, if that'll help.)

Ad 3.
We never claimed that switch cases were based on `index`, we always maintained that they were based on `==`.
Overriding `index`, for whichever reason, should not affect switches, and no user should expect them to.
There never was an abstraction, the `index` getter is completely unused by the language specification.
The language shouldn't care if you break it.

Also, if you override `operator==`, then `switch` cases *will* stop working (the class no longer has primitive equality), 
*even* if the switch really uses `index`. Equality is the abstraction we use for switches, not `index`.


I don't think people will override `index` (or implement their own `values`) in order to pretend to be a different `enum`.
(And if they do, it won't work anyway, so that ought to stop them.)
If they change the behavior, it's because they want a different behavior for that class for some *other* reason.
I see no good reason to stop them, other than it making our implementation task slightly easier.

**Comment by jakemac53** [comment]
> I don't think people will override `index` (or implement their own `values`) in order to pretend to be a different `enum`.
> (And if they do, it won't work anyway, so that ought to stop them.)

This is the reason for just blocking it entirely though. If a user _does_ either of these things, it's almost certainly an error, and will lead to confusion for users of that enum. Serialization libraries for example often rely on `index` and `values` for serializing enums, and they _will_ be broken by enums doing this.

Personally I think it's better to just block entirely, to avoid such confusion. It is OK if enums have some special constraints around these members, to maintain backwards compatibility with existing enums.

**Comment by mnordine** [comment]
> It's not clear what the motivating use case is

It isn't clear to me, either. Did any use cases come up during the discussion? Maybe I lack imagination...

**Comment by tatumizer** [comment]
Java's equivalent of `index` is `ordinal`.
Here's what java has to say about it:

>public final int ordinal()
Returns the ordinal of this enumeration constant (its position in its enum declaration, where the initial constant is assigned an ordinal of zero). Most programmers will have no use for this method. It is designed for use by sophisticated enum-based data structures, such as EnumSet and EnumMap.

It's quite plausible that dart will need it too, for the same purpose. If `index` can be overridden, the justification for such a field becomes problematic.

**Comment by lrhn** [comment]
I still think allowing you to have an interface member named `values` is valuable, even if it disables the default `values` static constant.
Arguments like being usable by an `EnumSet` doesn't apply because it's a static declaration, so you can't abstract over it.
(Although serialization through *code-gen* is probably an exception.)

I'm ready to disallow overriding `index`. I don't think it's *necessary*, so we are adding an extra complexity in disallowing it. We might get that back by not having to change our `switch` implementation (no matter how trivial the change).

What if we added accessors for the original `index` and `values` on `Enum`, say:
```dart
external static int get indexOf(Enum value);
external static List<T> valuesOf<T extends Enum>();
```
Then you can still get the values if you need them, but we don't need to restrict the interface in the same way.
(We should have done that from the start, though. Harder to make that change today.)

**Comment by leafpetersen** [comment]
> The argument for not forcing the existing enum notion of `values` on any new `enum` is that it would prevent implementing an interface with a member names `values`. (Because you can't declare a static member with the same name as an _inherited_ member, for no real good reason.)
> 
> Most likely most people won't have a member named `values`, but for those would want to, making the existence of such a member preclude introducing the automatic static `values` constant, will make that possible.
> 
> I don't expect the use-case to be that you want to create your own "compatible" `values` constant.

We could just... not emit that error for the synthetic values member, at least for inherited members.

> I'm ready to disallow overriding `index`. I don't think it's _necessary_, so we are adding an extra complexity in disallowing it. We might get that back by not having to change our `switch` implementation (no matter how trivial the change).

My sense is that if we had non-virtual members, we would make this non-virtual.  This suggest to me that we should probably just make it ad hoc non-virtual here.

**Comment by lrhn** [comment]
I'm beginning to see non-virtual instance members as a solution for more problems (promotable fields for example, it's one way to guarantee no overrides), so maybe that's something we should work on more.

The big question is what "non virtual" means. 
I'm guessing that here it's really "final virtual"/"sealed" that is meant: Cannot be overridden.

For a full non-virtual member feature (like C#, or even Beta), I'd expect you to be allowed to add same-named members in subclasses, which are not overriding and can have completely different signatures.
Accessing the name at type `Enum` would get the `index` `int` getter, but if `enum Foo` has `Bar index(int by) =>....`, accessing `index` at type `Foo` would get the function instead.

So, if we tentatively pretend to introduce sealed instance members, it would mean:
* Subclass cannot add concrete member with that name, one where the implementation would be overridden.
* Subclass probably can add an abstract member/implement an interface with the same name, as long as the new signature is compatible with the implementation.
* Can the interface be *implemented*, or is it sealed too? (In this case, the `Enum` interface itself is not sealed, you can implement it, but it's only useful to do so in interfaces and `mixin`s that will be applied to `Enum`, and then you won't be allowed to override the `index` implementation anyway.) Probably,  or at least, as here, disallow a *concrete* class from implementing the interface which has a sealed member, if it doesn't also extend the class. (So we get no-implement classes too.)

**Comment by johnniwinther** [comment]
cc @chloestefantsova

**Comment by munificent** [comment]
> What if we added accessors for the original `index` and `values` on `Enum`, say:
> 
> ```dart
> external static int get indexOf(Enum value);
> external static List<T> valuesOf<T extends Enum>();
> ```
> 
> Then you can still get the values if you need them, but we don't need to restrict the interface in the same way. (We should have done that from the start, though. Harder to make that change today.)

Yup, I brought up a very similar point in the language meeting. I think we made it an instance member mostly because it looks nice that way, but not because we actually *want* it to be polymorphic. (See also: `Object.runtimeType` which you should never ever override.)

> I'm beginning to see non-virtual instance members as a solution for more problems (promotable fields for example, it's one way to guarantee no overrides), so maybe that's something we should work on more.

Agreed 100%. It's something I started working on when I was working on modifiers on types, but I didn't get to it yet. I think it's really valuable.

> For a full non-virtual member feature (like C#, or even Beta), I'd expect you to be allowed to add same-named members in subclasses, which are not overriding and can have completely different signatures.

This gets into overloading territory which adds a lot of complexity. I'm not aware of any languages that have nonvirtual methods that *don't* allow some form of overloading, though, so maybe that complexity is essential for supporting non-brittle class hierarchies.


> So, if we tentatively pretend to introduce sealed instance members, it would mean:
> 
> * Subclass cannot add concrete member with that name, one where the implementation would be overridden.

+1.

> * Subclass probably can add an abstract member/implement an interface with the same name, as long as the new signature is compatible with the implementation.

+1.

> * Can the interface be _implemented_, or is it sealed too? (In this case, the `Enum` interface itself is not sealed, you can implement it, but it's only useful to do so in interfaces and `mixin`s that will be applied to `Enum`, and then you won't be allowed to override the `index` implementation anyway.) Probably,  or at least, as here, disallow a _concrete_ class from implementing the interface which has a sealed member, if it doesn't also extend the class. (So we get no-implement classes too.)

This one I need to think about more.

My tentative thought is that non-virtual is essentially saying something about the method *body*. It means "a call to a method that matches my signature on an instance of this class (or any subclass) must reach *this body*."

Say you have a class with a nonvirtual method and the class also exposes an implicit interface. I think it's fine for another class to implement that interface and provide its own implementation of that method. Because then you're not *replacing* that actual method body with your own. You're in a totally different class.

In other words classes that care about nonvirtual methods case because they have some other concrete code (likely in the same class) that is calling that method and they want to ensure that calls to the method reach the actual implementation they care about. Once you're implementing that class's interface, none of that applies and you can do whatever you like because you're also not reusing any of the code that *calls* that nonvirtual method.

In cases where you want to ensure that a call to some method on *any* instance of the surrounding class's type goes to that one particular implementation, then it means you want the method to be nonvirtual *and* you want the class itself to be non-interface so that there are no subtypes of the class floating around that don't use the original method's implementation.

> Would probably be the right time to add `override` as a language feature too.

+1.

**Comment by eernstg** [comment]
This has been settled: #2080.
