### ISSUE TITLE
A piece of code in Dart Language specification gets difference in real machine

### ISSUE THREAD

**Issue by horo99** [dart-lang/language#2082]
In <Dart Programming Language Specification 5th edition Version 2.10>, page 85, there is the piece of code such below

![image](https://user-images.githubusercontent.com/22970981/151699111-04fb8f66-19a0-4d0b-b85b-ccbb77872d35.png)

the code means instantiation to bound will get the error, but I use the code in my machine, the result as below

![image](https://user-images.githubusercontent.com/22970981/151699162-cfbef69a-5d8f-4326-aeeb-602787e53ff2.png)

I don't get the error of F<C>.(In order to avoid the null check, I add the value of f).
My Dart SDK version: 2.15.1 (stable) (Tue Dec 14 13:32:21 2021 +0100) on "macos_x64".
I can't finger what's wrong

**Comment by eernstg** [comment]
The rule about how to check that a given type is super-bounded have changed slightly in the version of the language that includes null safety:

> top types in invariant positions and in positions that have no variance
> (unused type parameters in a type alias) are given the same treatment
> as top types in covariant positions

As a result, the example you mentioned is no longer an error. In particular, `F<C<dynamic>>` is transformed into `F<C<Never>>`, which is a regular-bounded type, so `F<C<dynamic>>` is a super-bounded type. This means that certain raw types are accepted that used to be compile-time errors; there is nothing unsound about those types, it's just that they are _not_ supertypes of all the possible regular-bounded types to which the given generic type can be instantiated.

The example has been updated in the upcoming version of the language specification where the null safety specification has been integrated (which illustrates that there do still exist some type declarations whose raw form is an error):

```dart
class C<X> {}

typedef F<X extends C<X>, Y extends C<Y>> = X Function(Y);

F f; // Compile-time error.
```

There are many situations where the 2.10 language specification differs from the language with null safety, so it is in general necessary to keep an eye on the newest language specification as well as the specifications of novel features in https://github.com/dart-lang/language/tree/master/accepted.

I'll close this issue because the required specification update is known, and in the pipeline.

**Comment by horo99** [comment]
> The rule about how to check that a given type is super-bounded have changed slightly in the version of the language that includes null safety:
> 
> > top types in invariant positions and in positions that have no variance
> > (unused type parameters in a type alias) are given the same treatment
> > as top types in covariant positions
> 
> As a result, the example you mentioned is no longer an error. In particular, `F<C<dynamic>>` is transformed into `F<C<Never>>`, which is a regular-bounded type, so `F<C<dynamic>>` is a super-bounded type. This means that certain raw types are accepted that used to be compile-time errors; there is nothing unsound about those types, it's just that they are _not_ supertypes of all the possible regular-bounded types to which the given generic type can be instantiated.
> 
> The example has been updated in the upcoming version of the language specification where the null safety specification has been integrated (which illustrates that there do still exist some type declarations whose raw form is an error):
> 
> ```dart
> class C<X> {}
> 
> typedef F<X extends C<X>, Y extends C<Y>> = X Function(Y);
> 
> F f; // Compile-time error.
> ```
> 
> There are many situations where the 2.10 language specification differs from the language with null safety, so it is in general necessary to keep an eye on the newest language specification as well as the specifications of novel features in https://github.com/dart-lang/language/tree/master/accepted.
> 
> I'll close this issue because the required specification update is known, and in the pipeline.

Thank you for your reply. The doubt in my mind has disappeared totally. I thought I can use latest DartLangSpecDraft 2.15 (although it is a draft) to learn about dart, and continue to observe the changes in docs.
Thank you  again.

**Comment by eernstg** [comment]
Thanks! Using the newest dartLangSpec draft is a good starting point, but for any novel features it will be specified in a feature specification in https://github.com/dart-lang/language/tree/master/accepted for some time.

However, the rather substantial discrepancy between the language specification and the most recent language that arose because of the null safety feature bundle was a special case. When we've landed the version of the language specification that includes null safety, those discrepancies will most likely be considerably smaller.
