### ISSUE TITLE
Allow `with` and/or `implements` key-words for `extension`

### ISSUE THREAD

**Issue by ValentinVignal** [dart-lang/language#2083]
Would it bring issues to allow `with` and/or `implements` with extensions?

```dart
class A {}
class B {}
class C {}

extension D on A with B implements C {} 
```

In that way, an object `A` could be considered as a `B` and/or a `C`.

Motivation:

It would be very useful when working with generated code or classes from a library we don't have the hand on:

```dart
import 'package:square/square.dart' show Square;

abstract class Object2D {
  double get area;
}

extension on Square implements Object2D {
  @override
  double get area => edge * edge;
}

someGenericMethodOn2DObject(Square());
```

I guess an issue would be the `@override` decorator that could bring confusion.

**Comment by lrhn** [comment]
That's basically Rust traits. 
It requires a way to let an `A` object *be* a `B`/`C` object at runtime, to have a representation (or be convertible into a representation) which will fit in where a `B`/`C` object is expected. What Rust does is (effectively) to create an implicit `B` and `C` wrapper for `A` objects, and wrap the object when you assign an `A` to `B`, and unwrap again if you cast it back to `A`. (In practice, they inline/unbox the wrapper object as a "fat pointer".)

That is more complicated than the static extension methods that Dart has today, where all you get is a way to call static methods "on" an `A` object. That has no affect on the runtime representation of `A`.

It also require a way to make this functionality scoped. Since you can add conflicting extensions on the same object, you want to be able to control which ones apply at any point. I guess the current "extension is imported into the current library" approach can work.

**Comment by eernstg** [comment]
We're considering a mechanism which has been called _extension types_ and more recently [_views_](https://github.com/dart-lang/language/blob/master/working/1426-extension-types/feature-specification-views.md). That mechanism has a lot of semantic overlaps with the extension mechanism that we have today, but they differ in ways that are relevant here.

```dart
class A {...}
class B {...}
class C {...}

view D on A implements B, C {
  ... // Implement the interfaces of `B` and `C` using the interface of `A`.
}

void main() {
  A a = A();
  D d = a;
  // We can use `d` as a `B` or as a `C` statically.
  d.someCMethod();
  // If we wish to have polymorphic or dynamic usages, we must box it.
  B b = d.box;
  b.someBMethod();
  (b as dynamic).someCMethod();
}
```

So you can require that the view declares and implements methods such that it satisfies the same interface as an instance of `B` and an instance of `C` (unless they have conflicts, e.g., `B.m` is a getter and `C.m` is a method). As long as there is no need for polymorphic access (that is, as long as the compiler can know that we're actually working on an instance of `A`), we can use those interfaces transparently without allocating a wrapper object.

However, if we wish to pass the `A` to a receiver who expects a `B` or a `C` then we must box the `A` instance. From that point it is actually a wrapper object, and all the normal mechanisms will work as usual. For instance, methods will be invoked based on OO dispatch (that is, they are "virtual methods").

This mechanism is still under consideration, so there are no promises about any of the details at this point.

Also note that there is no particular support for using a mixin in order to obtain certain method implementations, but there is support for extending other views. For instance, an existing view `AasB` that implements the interface of `B` using the interface of `A` could provide an implementation of all the `B` methods using `view D extends AasB on A implements C {...}`.

**Comment by ValentinVignal** [comment]
Thanks for the feedbacks and explanations. What should I do with this issue then? Do you prefer me to close it or to leave it open?

**Comment by eernstg** [comment]
Perhaps close it and comment on related issues, and create new ones as needed if your proposal develops into a more detailed form?
