### ISSUE TITLE
Unexpected error when down-casting a List

### ISSUE THREAD

**Issue by esDotDev** [dart-lang/language#2087]
This code will throw the error:
_Uncaught Error: TypeError: Instance of 'Bar': type 'Bar' is not a subtype of type 'Foo'_
```dart
void main() {
  List<Foo> fl= [Foo()];
  List<Mixin> l = fl.cast<Mixin>();
  l.add(Bar()); // this is the line that throws
}

class Foo with Mixin {}

class Bar with Mixin {}

mixin Mixin {}
```

If you rewrite it as this, it works as expected:
```dart
  List<Mixin> l = [Foo()];
  ...
```
If you replace the `cast` (or `toList()`) with a `map().toList()`, it will also work as expected:
```dart
List<Foo> fl= [Foo()];
List<Mixin> l = fl.toList(); // causes runtime error when bar is added later
List<Mixin> l = fl.map((i) => i as Mixin).toList() // works as expected
l.add(Bar());
```
This is not specific to mixins, class + extends has identical behavior.

**Comment by Levi-Lesches** [comment]
From the documentation for [`List<E>.cast<R>`](https://api.dart.dev/stable/2.7.2/dart-core/List/cast.html):

> Elements added to the list (e.g., by using `add` or `addAll`) must be instances of `R` to be valid arguments to the adding function, and they must also be instances of `E` as well to be accepted by this list as well.

Seems like the docs covered this already, noting that even if you cast your list from `Foo` to `Mixin`, all new elements still need to be of type `Foo`. 

Some discussion on this repo seems to indicate that the reason this happens is that `.cast` is actually a runtime check, and the list is still fundamentally a `List<Foo>`, just with a wrapper that makes sure all instances are also `Mixin`s as well. So if you want to change the static type of the list from `Foo` to `Mixin`, you should use `List.of` instead (note I used simpler names here):

```dart
class A { }
class B extends A { }
class C extends A { }

void main() {
  List<B> b = [B()];
  List<A> a1 = b.cast<A>();
  List<A> a2 = List.of(b);
  a1.add(C());  // runtime error
  a2.add(C());  // okay
}
```

**Comment by esDotDev** [comment]
Hmm, ok. That's really odd, I would expect the error to happen when the cast happens then, not sometime later when something is added. 

But what about in the  case of a toList()? I guess that is just doing an implicit cast as well? Very sneaky :( 
```
List<Foo> fl= [Foo()];
List<Mixin> l = fl.toList();
l.add(Bar()); // error here, 
```

**Comment by lrhn** [comment]
The `toList` method returns a list of the same type as the original list. Since the original list is a `List<Foo>`, the `.toList()` is also a `List<Foo>`, which can be assigned (unsafely) to `List<Mixin>`.

What you might want is `var l = fl.cast<Mixin>().toList();` which creates a new `List<Mixin>` with the same (`Foo`) elements as `fl`. Or just `var l = <Mixin>[...fl];`

**Comment by esDotDev** [comment]
Ah, ok, so it basically comes down to the fact the compiler is allowing this:
```
List<Foo> fl= [Foo()];
List<Mixin> l = fl; // This is not really a List<Mixin>
```
Is there a linter rule to have the compiler call this out for me?

**Comment by Levi-Lesches** [comment]
> Is there a linter rule to have the compiler call this out for me?

My understanding is that this will be a language feature when static variance is introduced. Specifically, this looks like a case of use-site variance, #753. 

> Why is `E` not `Mixin` here? It looks like the return type should be establishing the generic.

Notice the usage of `E` here vs `E` in `List.of`. In the latter case, we're using a constructor, so the `E` comes from whatever generic you pass to it, or whatever is inferred: 
```dart
List<Mixin> l = List.of<Mixin>(fl);  // okay, E is Mixin
```

However, when you use `fl.toList()`, you already _have_ a list, and that list already _has_ an `E` -- `Foo`. 

```dart
List<Mixin> l = fl.toList<Mixin>();  // toList is declared with 0 type parameters
```

So `fl.toList()` is returning `List<Foo>.of(fl)`, and doesn't care about `Mixin` at all. Note that your workaround with `.map` _does_ work because you're essentially doing the following: 

```dart  
List<Mixin> l = fl.map<Mixin>((i) => i as Mixin).toList();
```
Now, `.toList()` is being called on an `Iterable<Mixin>`, which happily returns a `List<Mixin>`.

**Comment by esDotDev** [comment]
Ok, ty all for the time!
