### ISSUE TITLE
In "Dart Programming Language Specification 6th edition draft Version 2.15-dev" page 35

### ISSUE THREAD

**Issue by horo99** [dart-lang/language#2097]
<img width="507" alt="image" src="https://user-images.githubusercontent.com/22970981/152717542-42012aa5-7001-4fd4-8b54-027c9bcd8a4a.png">
before is the code in specification, below is the fact in my ide
<img width="1051" alt="image" src="https://user-images.githubusercontent.com/22970981/152717823-baab923c-4320-4018-af7a-6085879958a6.png">

My dart version shows as below, 
Dart SDK version: 2.15.1 (stable) (Tue Dec 14 13:32:21 2021 +0100) on "macos_x64"

**Comment by horo99** [comment]
I know the specification I'm learning is a dev version, and I don't know it is right to commit a bug with the dev version specification like this way.

**Comment by eernstg** [comment]
@horo99 wrote:
> specification I'm learning is a dev version

Reporting a specification bug in this repo is fine!

However, the current version of the specification does not include null safety, and the example is correct for pre-null-safety Dart.

Parts of a new version of the language specification that introduces null safety are under review. This new version includes a fix for this example (and for a few thousand other things ;-). The corrected program looks like this:

```dart
class A {
  noSuchMethod(covariant Never n) => n;
}

void main() {
  dynamic d = A();
  d.foo(42); // Dynamic type error when invoking noSuchMethod.
}
```

It may seem silly to have a formal parameter whose type is `Never` (because it's never possible to successfully pass any actual argument to that parameter), but the point is still the same: We get a dynamic error because the given argument does not satisfy the typing requirement associated with the formal parameter, we don't get an infinite loop where each invocation of `noSuchMethod` directly causes another invocation of `noSuchMethod`.

Parts of the null-safety update is under review in https://github.com/dart-lang/language/pull/2023 and https://github.com/dart-lang/language/pull/2052, but the null-safety update consists of several additional parts, so it will take a while before everything has been landed (and this particular change is neither part of 2023 nor part of 2052).

Until then, please take the [null safety specification](https://github.com/dart-lang/language/blob/master/accepted/2.12/nnbd/feature-specification.md) into account as well as the language specification, in order to see how the language with null safety is defined.

**Comment by horo99** [comment]
Thanks!
Your reply is very helpful for me.
I forgot the type 'Never' before. I will firstly go to make a more totally understanding about null-safety via [null safety specification](https://github.com/dart-lang/language/blob/master/accepted/2.12/nnbd/feature-specification.md) before learning the specification. Thank you again!
