### ISSUE TITLE
Why print(0 == '') is not a compilation error?

### ISSUE THREAD

**Issue by SteveCruise** [dart-lang/language#2098]
Why this is not a compilation error?
```dart
print(0 == '') // always false
```
Sometimes we may compare enum type with int type like this:

```dart
enum AppId { assist, approval, report }

int id = 1;
if (id == AppId.approval) {
  // never true
} 
```
The compiler should tell us this is a bug!

**Comment by ykmnkmi** [comment]
```dart
abstract class num {
  bool operator ==(Object other);
}

class Object {
  external bool operator ==(Object other);
}
```
Also analyzer warns with `Equality operator '==' invocation with references of unrelated types.`

**Comment by lrhn** [comment]
It's not a compile-time error because it doesn't have to be. The `==` operator is perfectly capable of handling the operands, and the result is going to be `false`.

The compiler is not expected to know what the `==` operator of every type will return, which is one reason the language doesn't try to make rules about using or misusing `==`.

It does know for a few select types, though, those that can be used in constant evaluation. It still doesn't enforce any rules about using it "correctly", it just does the computation at compile-time.

This expression is not in a constant context, so the compiler doesn't have to do the computation as a constant. The compiler may simply not know whether `0 == ''` at compile-time (it doesn't need to memorize rules like "integers cannot be equal to strings", it either does the computation as constant evaluation, or it doesn't.)

It's also occasionally useful to do equality checks that are known at compile-time. 
* Doing `assert`s that should not be able to fail.
* Checking whether running on the web (`1 == 1.0`).
* Using conditional imports and having a value which is constant on some platforms, like `os_detect.operatingSystem == "browser"` (which will definitely be true when compiling for the web).

That said, the analyzer could probably give hints for comparisons that are *likely* a mistake. Comparing an enum value to an integer is known to be false (as long as the enum doesn't override `operator==`, which it will soon be able to).

**Comment by SteveCruise** [comment]
Thanks a lot for so mush words. I'm just a flutter new user.
