### ISSUE TITLE
Make `hashCode` part of primitive equality?

### ISSUE THREAD

**Issue by eernstg** [dart-lang/language#2108]
Cf. https://github.com/dart-lang/language/pull/2106, which is a spec PR that spells out the details.

We currently have the concept of a 'primitive operator `==`'. An instance or class that is involved in various parts of constant expression evaluation must have a primitive operator `==`, which basically means that "the language knows" how that operator is implemented, so it is permissible to execute it during constant evaluation. In particular, being an element in a constant set, being a key of a constant map, and being used as a case expression in a switch statement requires a primitive operator `==`. (Constant expressions of the form `e1 == e2` have their own rule, but we should probably switch to require a primitive `==` there, too, cf. https://github.com/dart-lang/language/issues/1811).

Until now we haven't had a similar notion of a "primitive `hashCode` getter".

This implies that there can be user-written classes where the operator `==` implementation is inherited from `Object` (so it's primitive), but `hashCode` is implemented by a user-written override.

We have a lint, [`hash_and_equals`](https://dart-lang.github.io/linter/lints/hash_and_equals.html), whose purpose is to ensure that an overriding declaration of operator `==` is accompanied by an overriding declaration of `hashCode`, and vice versa, and the above situation is inherently a violation of this lint. Shouldn't we consider that a strong hint that the code has a bad smell?

This issue is a proposal to eliminate this possibility by constraining `hashCode` in the same way as operator `==` (and naming the concept 'primitive equality' rather than 'primitive operator `==`'). This would allow implementations to use `hashCode` during constant evaluation to the same extent as it is currently able to use operator `==`, and it would support the particular coding discipline that is the target of `hash_and_equals`.

This topic was on the agenda of this week's language team meeting, but we didn't have the time. @stereotype441, @leafpetersen, @lrhn, @natebosch, @jakemac53, @munificent, WDYT?

**Comment by stereotype441** [comment]
sgtm!

**Comment by lrhn** [comment]
The use-case I see for overriding `hashCode` and not `==` is that `identityHashCode` is not that efficient.
If you don't override `==`, so it's `identical`, overriding `hashCode` cannot be *wrong* (any value satisfies the `a == b` =\> `a.hashCode == b.hashCodwe` since `a==b` only if `identical(a, b)`).

It might make sense to return some unique internal ID as `hashCode` instead of relying on `identityHashCode`.
I believe either the front-end or dart2js already does that.

(I never really liked the `hash_and_equals` lint because it goes both ways. If it just said "if you override `==`, you should override `hashCode`" then I'd be happier about it. Otherwise it risks false postives.)

With this change, such objects will no longer be usable in switches.
They won't be usable in set/maps either, but that's more reasonable, and I think we already promised the VM they could reject constant map/sets with objects overriding `hashCode` (@dcharkes).

So, my proposal is to introduce the twin notions of "primitive equality" (doesn't override `Object.==`) and "primitive hash-equality" (overrides neither `Object.==` nor `Object.hashCode`).
Then it's an error to use an object without primitive hash-equality as a constant map key or constant set element,
and it's an error to use an object without primitive equality as a switch case value.

(I'm slightly expecting our new enhanced enums to make this an issue, with people doing something like `int get hashCode => index;` for performance, and still expecting to get exhaustive switches.)

**Comment by lrhn** [comment]
Maybe the VM `identityHashCode` is more efficient now than it used to be (it used to use an `Expando`), so it's no longer an issue.
The JS version still sets the value as a property on the object, which risks polymorhism (https://github.com/dart-lang/sdk/blob/f9d59cfc24e540244dd30e46a36c3e9be4c21558/sdk/lib/_internal/js_runtime/lib/js_helper.dart#L267), so I'd definitely consider doing something more efficient there.

**Comment by munificent** [comment]
I went ahead and analyzed some code. Looking at a corpus of open source Flutter apps (1,028,560 lines in 7,238 files), it's:

```
-- Classes (14068 total) --
  13175 ( 93.652%): Defines neither               =============================
    687 (  4.883%): Defines both hashCode and ==  ==
    202 (  1.436%): Defines only hashCode         =
      4 (  0.028%): Defines only ==               =
```

All 202 of the "defines only hashCode" cases are from a single package, invoiceninja-flutter-mobile, and look like:

```dart
@override
@memoized
int get hashCode;
```

Filtering those out, we get:

```
-- Classes (11007 total) --
  10519 ( 95.566%): Defines neither               =============================
    484 (  4.397%): Defines both hashCode and ==  ==
      4 (  0.036%): Defines only ==               =
```

Looking at the repos on itsallwidgets.com (3,220,102 lines in 24,201 files):

```
-- Classes (39456 total) --
  38204 ( 96.827%): Defines neither               ==============================
   1042 (  2.641%): Defines both hashCode and ==  =
    203 (  0.514%): Defines only hashCode         =
      7 (  0.018%): Defines only ==               =
```

Again invoiceninja is an outlier. Filtering that out:

```
-- Classes (36395 total) --
  35548 ( 97.673%): Defines neither               ==============================
    839 (  2.305%): Defines both hashCode and ==  =
      7 (  0.019%): Defines only ==               =
      1 (  0.003%): Defines only hashCode         =
```

And looking at 1,000 recent pub packages (7,116,622 lines in 51,038 files):

```
-- Classes (70913 total) --
  68487 ( 96.579%): Defines neither               =============================
   2272 (  3.204%): Defines both hashCode and ==  =
    133 (  0.188%): Defines only ==               =
     21 (  0.030%): Defines only hashCode         =
```

Note that this only looks directly at one class declaration, so doesn't catch cases where a class ends up inheriting `==` or `hashCode` or both. I think those cases are likely pretty rare.

Given how tiny the number of cases where a class implements one but not the other, I don't know if it makes much sense to make a distinction between "primitive equals" and "primitive hashCode". 

Also, unfortunately, it looks like most classes that only implement one implement the *wrong* one and they end up with objects that may return `true` for `==` but have different hashcodes. :(

**Comment by eernstg** [comment]
Numbers, great! Those 'only ==' entries might be fine, but they might also be bugs in need of `hash_and_equals`. :smile:

Is it fair to claim that there is no need to cache `hashCode`? It seems to be unnecessary on the VM, but the situation might be different on JavaScript platforms. In that case there are very few well-justified cases where only `hashCode` is overridden.

It would be interesting if anyone could come up with an example of a situation where `hashCode` is overridden, and operator `==` is not, and this is exactly how it should be done.

**Comment by munificent** [comment]
> Numbers, great! Those 'only ==' entries might be fine, but they might also be bugs in need of `hash_and_equals`. 😄

Yeah. In theory, if it's your own type and you *know* that it will never be placed in a HashMap, then it's harmless to override `==` and not `hashCode`, but it's definitely breaking the contract between those two members.

> Is it fair to claim that there is no need to cache `hashCode`?

I would let the implementations make that choice since they know what's best.

> It would be interesting if anyone could come up with an example of a situation where `hashCode` is overridden, and operator `==` is not, and this is exactly how it should be done.

The formatter has a class:

```dart
/// A mixin for classes with identity equality that need to be frequently
/// hashed.
abstract class FastHash {
  static int _nextId = 0;

  /// A semi-unique numeric identifier for the object.
  ///
  /// This is useful for debugging and also speeds up using the object in hash
  /// sets. Ids are *semi*-unique because they may wrap around in long running
  /// processes. Since objects are equal based on their identity, this is
  /// innocuous and prevents ids from growing without bound.
  final int id = _nextId = (_nextId + 1) & 0x0fffffff;

  @override
  // ignore: hash_and_equals
  int get hashCode => id;
}
```

This is inherited by a couple of classes that are used in very performance-intensive code that also uses HashMaps. Adding this custom `hashCode` implementation was a significant performance improvement at the time. Today, it looks like it only makes about a ~3% difference on my benchmark.

**Comment by munificent** [comment]
We discussed this at the language meeting today. We do intend to unify the notion of primitive `==` and `hashCode` so that a class that implements *either* of those no longer has "primitive equality/hashCode". That in turn means that a class that implements `hashCode` cannot be used in a switch or constant map key or set. The VM already prohibits a class with an overridden `hashCode` from being used in a constant set or map key, so we think the restriction is reasonable.

However, we don't want to force the implementation teams to churn and implement this new restriction and error reporting right now since the benefit is so marginal. Instead, we intend to bundle this change with the larger pattern matching feature, since that feature will revamp a lot of things around switch statements anyway.

**Comment by munificent** [comment]
@eernstg, the plan is to ship this at the same time as patterns, but do you know who on the language team is planning to drive this? Is it you?

**Comment by eernstg** [comment]
> who on the language team is planning to drive this? Is it you?

Yep.

**Comment by munificent** [comment]
Awesome, thanks!

**Comment by eernstg** [comment]
The spec update https://github.com/dart-lang/language/pull/2106 has been revived.

**Comment by eernstg** [comment]
The spec update #2106 has been landed.

**Comment by eernstg** [comment]
Tests being added by https://dart-review.googlesource.com/c/sdk/+/279165.

**Comment by eernstg** [comment]
Closing. This is now handled in https://github.com/dart-lang/sdk/issues/51045.
