### ISSUE TITLE
Why extension is not a type?

### ISSUE THREAD

**Issue by Silentdoer** [dart-lang/language#2112]
```dart
class Stud {
  int sss = 9;
}

extension ExtensionStud on Stud {
  int getM() {
    return 9;
  }
  static int staMethod() {
    return 10;
  }
}

void main(List<String> arguments) {
  print(ExtensionStud.staMethod());  // ok
  // error, ExtensionStud has a static method, so why it is not a Type? Is this inconsistent at the conceptual level?
  Type type = ExtensionStud;
  Type type2 = Stud; // ok
}
```

**Comment by eernstg** [comment]
A declaration of an extension does not introduce a type into the top-level scope because it cannot be used as a type. For instance, you can't use `ExtensionStud` as the type of a variable, as a return type, as a type argument, etc. So the fact that it also can't be evaluated as a type literal is just one more situation where it can be detected that `ExtensionStud` does not denote a type.

There are many elements in the language design trade-offs associated with this design choice. The [_views_](https://github.com/dart-lang/language/blob/master/working/1426-extension-types/feature-specification-views.md) proposal unfolds a different trade-off where a similar mechanism _does_ introduce a type, so you might want to take a look at that to see a different trade-off.

**Comment by lrhn** [comment]
Having a static member, but not being a type, is not conceptually inconsistent.

A `class` declaration introduces a number of things: A class (has implementations and can be inherited), an interface (has member signatures), a type (has subtype relations) and a namespace (contains static members).
An `extension` declaration introduces extension methods (`on` type plus static members) and a namespace (contains static members).

Both introduce a namespace for static members (as does `mixin` declarations), and the way to access the static members is the same, "NameOfDeclarationOfNamespace.staticMember".

The namespace is completely separate from the rest of the declaration. That's why a generic class, `class C<T>`, is instantiated when we talk about it as a class, interface or type - there is no "raw type", it's always instantiated implicitly or explicitly, but there is no instantiation when accessing static members. It's just a name which refers to the *declaration*, not to its type.

We could potentially introduce a `namespace` declaration that has nothing but static members. That too would be consistent.
