### ISSUE TITLE
Can augmentations declare, prepend, append, override documentation comments?

### ISSUE THREAD

**Issue by srawlins** [dart-lang/language#2131]
A few questions here: given the basic notion of (for example) a class:

```
class C {}
```

and an augmentation:

```
augment class C {}
```

(All of the following questions hold for augmenting a function as well.)

Q1: Can the developer write a doc comment above `augment class C {}`? I think this is something we should strongly consider supporting, in some form.

To back up a bit, what does a doc comment do, beyond a simple comment? Primarily two things:

* Provide comment text for generated documentation, hosted for example at api.dart.dev and at pub.dev, which is attached to an element.
* Support cross-linking in bracketed "doc references", like `returns a [String]`. This can be seen in IDEs, generated documentation, and potentially in HTML views of code repositories (Code Search, GitHub).

An augmentation may wish to add a sentence to an existing doc comment, or refer to elements that the class author may not want to hand-write. Perhaps an augmentation function which HTML-escapes its wrappee looks like this:

```dart
/// Gets text from somewhere.
@htmlEscaped
String getText() { ... }

// augmentation:

import 'dart:convert' show htmlEscape;

/// Returned text is HTML-escaped with [htmlEscape].
augment String getText() {
  return htmlEscape(augment super());
}
```

If the answer to Q1 above is "No." you can stop reading. 😄 

Q2. What does a doc comment on an augmentation (of a class, of a function) do? Here are some scenarios:

1. If the class does not have a doc comment, does a doc comment on the augmentation "set" the doc comment for the class? Or would it be meaningful to document augmentations separately and display augmentations and their doc comments in generated docs?
2. What if there is a doc comment on the class, and another on the augmentation? If an augmentation can "set" a doc comment on a class, then do we replace the existing one? Append to it? If an augmentation is documented separately, the question is moot.

**Comment by Levi-Lesches** [comment]
If I can weigh in: 

I use dartdocs to learn how I'm supposed to use a class and its members. This includes parameters and return types but also a textual description of what is happening inside the function. That involves details on the values coming and going out as well as any side effects. If an augmentation can change either of those, then the answer to Q1 should be yes. 

One of dartdoc's many smart features is overriding doc comments when a member is overridden and provides its own doc comments. Even though the overridden member's documentation may be relevant, if the member itself is being replaced, its documentation should be as well. For the sake of consistency, since the member itself is being augmented, its documentation should be too. Especially because augmentation can and probably will be used to fill in the implementation entirely from just a signature.

I'm not really up to speed on how/whether augmentations will be imported separately or included by the library itself. If they can be imported separately, then it makes sense to document separately like extensions. If an augmentation is included in the library its augmenting, then its docs should be included with the original library. As for prepending vs appending, I think appending makes more sense because understanding how the augmentation modifies the member has to come after understanding how the original member works/is supposed to work. 

For your example, I'd expect to see: 
### getText function

[String]() getText()

Gets text from somewhere. 

Returned text is HTML-escaped with [htmlEscape]().


Here's another example: 
```dart
/// Represents a user in our system.
@JsonSerialize()
class User { 
  /// This user's age.
  int age;

  /// The user's password
  @jsonProperty(serialize: false)
  String password;
}

// generates: 

/// Can be converted to a JSON value.
augment class A {
  /// Is not included in the JSON output.  
  String password;
 
  /// Converts this object to JSON.
  Map<String, dynamic> toJson() => {"number": number};
}
```

Documentation: 
### User class

Represents a user in our system.

### age property

[int]() age

This user's age

### password property

[String]() password

This user's password.

Is not included in the JSON output. 

### toJson method

[Map]()<[String](), dynamic> toJson()

Converts this object to JSON.

**Comment by cedvdb** [comment]
That'd be pretty cool. I think it should be clear in the doc that it was added though as to not mess with the original doc.

**Comment by Levi-Lesches** [comment]
> That'd be pretty cool. I think it should be clear in the doc that it was added

But if the augmentation is invisible to users of the library, then it's really an implementation detail and should remain invisible. So including it in the docs is like saying "there's something going on here but you'll never know what or where it's defined", which may be more confusing than necessary. 

However, it _can_ be useful to document augmentations for users reading docs for their _own_ libraries, or more advanced users looking to understand the _implementation_, not just the usage. I'm not quite sure which use case is better to optimize for, but I agree it might be good to have some part of the docs like: `Added by augmentation: These are the augmentation docs`.

**Comment by lrhn** [comment]
The way augmentation libraries are currently defined, as super-charged part files, they can add members to the library that are not just implementation details. Those members can definitely be documented in the augmentation.

Overriding the documentation should be possible if you override the functionality.

Maybe just make augmentations replace the existing documentation entirely. Then code generation based on meta-programming should get access the original documentation as a string, so it can modify it as needed.
That's more powerful than providing only a limited set of combinators (like before/after/around/replace). You can still provide those options as helper functions.

**Comment by jakemac53** [comment]
I do generally agree there should be an affordance for adding doc comments. This should already be supported in a sense today when adding any _new_ declarations (you can just include comments as a part of the code string). But when augmenting functions in particular you just provide a body, so we would need to add a separate mechanism for adding in the doc comments.

**Comment by munificent** [comment]
> Q1: Can the developer write a doc comment above `augment class C {}`? I think this is something we should strongly consider supporting, in some form.

Yes, I think that should be supported. Also, I think identifier references in doc comments should be resolved *after* augmentations are merged in. This way, a doc comment on the primary declaration of a class can refer to members coming from augmentations.

**Comment by jakemac53** [comment]
Personally I don't think we should specify exactly how the comments are presented to the user in the spec, and the tools should just be free to do whatever they think is best. This is probably an analyzer/dartdoc question primarily.

And then we just need to ensure there is a way in the macro apis to add these comments, I filed https://github.com/dart-lang/language/issues/3047 to capture that part specifically.

**Comment by jakemac53** [comment]
I sent out https://github.com/dart-lang/language/pull/3048 just to clarify this behavior and I did make one decision there which is that doc comments on augmentations should be specific to the augmentation, and not completely override the doc comment for the original declaration.

Tools may decide to merge the comments etc as they see best fit.
