### ISSUE TITLE
The `newtype` idiom

### ISSUE THREAD

**Issue by fzyzcjy** [dart-lang/language#2132]
Many languages, such as Rust, has such an idiom - https://doc.rust-lang.org/rust-by-example/generics/new_types.html.

Usage example:

```
newtype PostId(int);
newtype CommentId(int);

Map<PostId, Post> posts;
Map<CommentId, Comment> comments;
```

Then, if I have an `id` of type `PostId` at hand, I will never make an mistake like:

```
// id is of type PostId
comments[id]; // compile ERROR!
```

On the other hand, if I use type aliases like `typedef PostId = int; typedef CommentId = int;`, then I can do `comments[postId]` without any warnings or errors.

With newtype, I can even do more things such as:

```
extension PostIdX on PostId { Post get object => posts[this]; }
extension CommentIdX on CommentId { Comment get object => comments[this]; }
```

which is also not possible with type alias.

Currently I can write down things like `class PostId {final int id;}`. But that comes with performance penalty. On one hand, it takes much more memory - you know, the `class` needs lots of bytes to store metadata. On the other hand, it is also slower since `operator==` and things like that will grow from a few machine instruction to dozens of.

**Comment by eernstg** [comment]
Note that this is covered by the [views](https://github.com/dart-lang/language/blob/master/working/1426-extension-types/feature-specification-views.md) mechanism (as currently proposed, which may still change in various ways):

```dart
view PostId on int {}
view CommentId on int {}

Map<PostId, Post> posts;
Map<CommentId, Comment> comments;

void foo(PostId id) {
  posts[id]; // OK.
  comments[id]; // Compile-time error.
}
```

A view on an `int` is does not carry a performance cost, it is still represented as a plain `int` at run time.

**Comment by fzyzcjy** [comment]
@eernstg Sounds interesting, thanks!

Btw I wonder when (roughly) will it be implemented? I see the draft init at 2021.05 but seems no update currently?

**Comment by eernstg** [comment]
Can't promise any timing, but I do think it is likely to happen.

**Comment by fzyzcjy** [comment]
Thank you!

**Comment by eernstg** [comment]
If you don't want to have any subtype relationship from a view type to the underlying representation (known as the 'on-type' of the view) then you would simply use a closed view:

```dart
closed view Email on String {
  factory Email(String s) {
    ... // Validate that `s` is a proper email address, otherwise throw.
    return s;
  }
  ... // Additional methods needed on an `Email`.
}

void main() {
  var email = Email("someone@gmail.com"); // OK.
  var otherEmail = Email("(@*&  #*"); // Fails to validate, throws.
  String s = email; // Compile-time error, `Email` and `String` are unrelated types.
  email = "A plain string"; // Compile-time error, unrelated types.
}
```

The mechanism will not provide any firm guarantees about the validation. In particular, all variants of this proposal have included support for a run-time cast, which means that we can write `'A plain string' as Email` and thus obtain a `String` typed as `Email`, without running the validation code.

It is definitely possible to be more strict, but we do tend to provide at least a small loophole when it comes to constraints that do not have any soundness implications.

In any case, the run-time representation of a view type is the underlying on-type, there is no wrapper object, and this implies that the run-time cast _will_ succeed if we do things like this:

```dart
void main() {
  Email email = ...;
  Object? o = email; // Upcast, OK.
  String s = o as String; // Yes, it is a string!
}
```

We could consider putting view types completely outside the subtype relationship (like `int` in Java), but that would imply that we can't have `List<V>` where `V` is a view type, and a lot of other "normal" things would no longer be possible. So that's not very likely to happen either.

**Comment by fzyzcjy** [comment]
I have one more usage for this idiom: Units like `m`/`km`/`cm`, or coordinate systems like `my-global-coordinate / my-scaled-coordinate / ...`.

For example, I hope I can have a type `Meter` and another type `Kilometer`, such that I will never be confused "what does this integer mean - meter or km?".

Rust has a newtype idiom (`struct Duration(i64);`), and golang also has similar things (e.g. for `type Duration int64`).

**Comment by fzyzcjy** [comment]
> @eernstg Note that this is covered by the [views](https://github.com/dart-lang/language/blob/master/working/1426-extension-types/feature-specification-views.md) mechanism

I wonder what is the current status? And can I contribute and where should I find out non-finished works?

**Comment by eernstg** [comment]
It's even more likely to happen, but some specification details are still being debated.

**Comment by eernstg** [comment]
> I would like to contribute

Thanks! I love the spirit of open source communities, and it works very well for things that are somewhat stand-alone parts of the overall project. When the language team has agreed to a proposal and implementation work proceeds, one area where contributions would be helpful is language tests. They are quite interesting to write as well, because they always bring up questions about the actual language semantics in cases where a design decision turns out to be suboptimal, or even where it hasn't been specified 100% unambiguously. ;-)

**Comment by eernstg** [comment]
Oh, I can't promise to keep a list of ping TODOs, but here's a way to keep an eye on the progress: When anything non-trivial is getting implemented, there will be an issue with the label `implementation` on the SDK repo, [like these](https://github.com/dart-lang/sdk/issues?q=is%3Aopen+is%3Aissue+label%3Aimplementation). That issue will contain a (usually long) list of subtasks, and they'll get a check mark when that subtask is done. Each subtask is usually handled in its own issue, so you can see who is working on what, and communicate via the issue.

**Comment by fzyzcjy** [comment]
Btw I see updates https://github.com/dart-lang/language/commits/master/working/1426-extension-types/feature-specification-views.md done a few days ago. Looks exciting :)

**Comment by fzyzcjy** [comment]
@eernstg I would like to introduce one more use case of newtype/view-type:

In my app, there are several coordinate spaces, like widget coord, object coord, shard coord etc. Thus, if I simply use Offset/Size/Rect/..., the code will soon be buggy because I sometimes misunderstands the coordinate of an Offset/Size/Rect/...

My current workaround (with overhead - not zero overhead!) is:

```dart
class OffsetT<Coord> {
  final Offset inner;
  OffsetT<Coord> operator+(OffsetT<Coord> other) => OffsetT(inner + other.inner);
// etc
}
```

In other words, I add a new class with `<Coord>` generics, and each coord space will have one such marker class. Then, I can never misuse points in different coordinate spaces. For example, adding a point in global coord with another point in object coord will get runtime error.

But this is not zero overhead. That's why I am looking forward to the `view`!

**Comment by Levi-Lesches** [comment]
If you're curious, you _can_ do this today with regular extensions (but you can't override the original methods):
```dart
/// Original [Offset] class, in some other package
class Offset {
  final double x, y;
  Offset(this.x, this.y);
  
  Offset operator+(Offset other) => Offset(x + other.x, y + other.y);
}

abstract class CoordinateType { } 
abstract class Rectangle extends CoordinateType { }
abstract class Polar extends CoordinateType { }

class MyOffset<T extends CoordinateType> extends Offset {
  MyOffset(super.x, super.y);
}

extension AddRectangle<T extends CoordinateType> on MyOffset<T> {
  /// Can't use [+], since [Offset.+] will always be used instead.
  MyOffset<T> add(MyOffset<T> other) => MyOffset(x + other.x, y + other.y);
}

void main() {
  MyOffset result = MyOffset<Rectangle>(0, 0).add(MyOffset<Polar>(0, 0));  // error
  print(result.x);
}
```

**Comment by eernstg** [comment]
@fzyzcjy, about the coordinate spaces: This is actually a somewhat tricky case. I think the core of it is the ability to have members (let's just focus on `operator +`) that are shared among several types, reusing code, and still keeping the different members with the same name separate (such that it is a compile-time error to mix two different types).

We can do this today with a wrapper object that uses an F-bounded type parameter (that is, a type parameter whose bound contains the type parameter itself). In the example, the classes `D1` and `D2` have different "representations" (one has a field of type `int`, the other a `String`), but they could just as well have used representations with exactly the same type: The `+` operators of `D1` and `D2` are still distinct according to the type system, so you won't mix them up by accident. Here's the example:

```dart
abstract class C<X extends C<X>> {
  // We can have reusable code here, e.g., methods calling `+`.
  X operator +(X other);
}

class D1 extends C<D1> {
  final int i; // One specific representation.
  D1(this.i);
  
  @override
  D1 operator +(D1 other) => D1(i + other.i); // One specific implementation of `+`.

  @override
  String toString() => 'D1($i)';
}

class D2 extends C<D2> {
  final String s; // .. and another.
  D2(this.s);

  @override
  D2 operator +(D2 other) => D2('$s${other.s}'); // .. and another.

  @override
  String toString() => 'D2($s)';
}

// A function that works safely and generically using `+`.
X add<X extends C<X>>(X x1, X x2) {
  return x1 + x2;
}

void main() {
  // `+` is available on each subtype of `C`.
  print(D1(2) + D1(3));
  print(D2('**') + D2('***'));
  
  // The `+` operators have incompatible types.
  D1(2) + D2('***'); // Compile-time error.
  D2('**') + D1(3); // Compile-time error.
  
  // Generic code can work on both, safely.
  print(add<D1>(D1(2), D1(3)));
  print(add<D2>(D2('##'), D2('###')));
}
```

Here's a simpler approach with no type parameter on the most general class `C`, and as you can see it is less type safe:

```dart
abstract class C {
  C operator +(C other);
}

class D1 extends C {
  final int i;
  D1(this.i);
  
  @override
  D1 operator +(covariant D1 other) => D1(i + other.i);

  @override
  String toString() => 'D1($i)';
}

class D2 extends C {
  final String s;
  D2(this.s);

  @override
  D2 operator +(covariant D2 other) => D2('$s${other.s}');

  @override
  String toString() => 'D2($s)';
}

// For `x1` we only know that its `+` returns a `C`, so the signature is much less precise.
C add(C x1, C x2) {
  return x1 + x2;
}

void main() {
  // `+` is available on each subtype of `C`.
  print(D1(2) + D1(3));
  print(D2('**') + D2('***'));
  
  // The `+` operators have separate types as long as we know the exact receiver type.
  // D1(2) + D2('***'); // Compile-time error.
  // D2('**') + D1(3); // Compile-time error.
  
  // Generic code can work on both, but not safely: It throws if we mix types.
  print(add(D1(2), D1(3)));
  print(add(D2('##'), D2('###')));
  try { add(D1(2), D2('###')); } catch (_) { print('Throws!'); }
  try { add(D2('##'), D1(3)); } catch (_) { print('Throws!'); }
}
```

So if you're willing to invest a bit of typing (on the keyboard) in order to get a better typing (in the Dart type system), then you can use the approach that uses an F-bounded type variable `X extends C<X>` to specify that the different `+` operators are unrelated.

These approaches rely on object-oriented dispatch: The generic code (like `add`) will not work unless it is able to call two different implementations of the member (here: `+`) when it's executed with arguments of type `D1` respectively `D2`.

The same ideas do _not_ work with views. In particular, a view method is never subject to object-oriented dispatch. It is always resolved statically, and this implies that there is no hope that we can invoke different implementations of `+` (or anything), based on the run-time type of the receiver.

However, if you give up on the ability to write generic code (so we won't have a type `C`, only the subtypes) then it's rather easy (except that we haven't quite resolved how to deal with overrides on members of `Object`, so I'm introducing a new method `toString2` to avoid using `toString`):

```dart
view D1(int i) {
  D1 operator +(D1 other) => D1(i + other.i);
  String toString2() => 'D1($i)';
}

view D2(String s) {
  D2 operator +(D2 other) => D2('$s${other.s}');
  String toString2() => 'D2($s)';
}

// No generic code, so we get code duplication.
D1 add1(D1 x, D1 y) => x + y;
D2 add2(D2 x, D2 y) => x + y;

void main() {
  // `+` is available on each type.
  print((D1(2) + D1(3)).toString2());
  print((D2('**') + D2('***')).toString2());
  
  // The `+` operators have incompatible types.
  D1(2) + D2('***'); // Compile-time error.
  D2('**') + D1(3); // Compile-time error.

  // Indirect invocation of `+` works, but it is not generic.
  print(add1(D1(2), D1(3)).toString2());
  print(add2(D2('**'), D2('***')).toString2());
  // ... and any D1/D2 add1/add2 mixture is a compile-time error.
}
```

**Comment by fzyzcjy** [comment]
@Levi-Lesches @eernstg Thanks for all the explanations and suggestions!

By the way, to make my use case complete, the coord system is most useful when we have Matrix and so on:

```dart

class Matrix4T<CoordA, CoordB> {
  final Matrix4 inner;
  OffsetT<CoordB> transformOffset(OffsetT<CoordA> offset);
}

// code I have shown yesterday
class OffsetT<Coord> {
  final Offset inner;
  OffsetT<Coord> operator+(OffsetT<Coord> other) => OffsetT(inner + other.inner);
}

// usage
void main() {
  final a = OffsetT<GlobalCoord>(Offset(1,2));
  final mat = Matrix4T<GlobalCoord, LocalCoord>(...);
  final b = mat.transformOffset(a); // it auto gets type "OffsetT<LocalCoord>"!
}
```

**Comment by mrcnski** [comment]
I see in the [above link about Views](https://github.com/dart-lang/language/blob/master/working/1426-extension-types/feature-specification-views.md?rgh-link-date=2022-02-25T15%3A52%3A49Z) that the feature is now called "extension types". Will that feature work with `String`, which is `abstract final`? 🤔 In the meantime, I guess it is not possible to extend or subtype `String`, which is really unfortunate.

**Comment by Levi-Lesches** [comment]
This compiles fine on DartPad's 3.3.0 beta channel:
```dart
extension type MyString(String s) {
  MyString operator +(MyString other) =>
    MyString(s + other.s);
}

void main() {
  final s1 = MyString("Hello, ");
  final s2 = MyString("World");
  final MyString s3 = s1 + s2;
  print(s3);
}
```

**Comment by munificent** [comment]
I think you can close this one as "completed" now, right @eernstg? I'll give you the honors. :)

**Comment by eernstg** [comment]
Very good, closing!

As mentioned in the link to 'views' above, the final name is 'extension types' and they were part of Dart 3.3.
