### ISSUE TITLE
Allow trailing comma in if statements

### ISSUE THREAD

**Issue by noga-dev** [dart-lang/language#2134]
instead of nesting a bunch of if statements like so:
```dart
if (someRatherSadlyLongCondition1) {
    if (someRatherSadlyLongCondition2) {
      if (someRatherSadlyLongCondition3) {
        if (someRatherSadlyLongCondition4) {
        }
      }
    }
  }
```

OR having an unesthetic formatting by writing this:
```dart
if (someRatherSadlyLongCondition1 && someRatherSadlyLongCondition2 && someRatherSadlyLongCondition3 && someRatherSadlyLongCondition4) {}
```

Would be nice to be able to write this:
```dart
if (someRatherSadlyLongCondition1 && someRatherSadlyLongCondition2 && someRatherSadlyLongCondition3 && someRatherSadlyLongCondition4,) {}
```

So that it would get auto formatted into this:
```dart
if (someRatherSadlyLongCondition1 && 
      someRatherSadlyLongCondition2 &&
      someRatherSadlyLongCondition3 &&
      someRatherSadlyLongCondition4,
      ) {}
```

Or this:
```dart
if (someRatherSadlyLongCondition1
    && someRatherSadlyLongCondition2
    && someRatherSadlyLongCondition3
    && someRatherSadlyLongCondition4,
    ) {}
```

**Comment by mateusfccp** [comment]
I use a workaround for this.

```dart
if (someRatherSadlyLongCondition1 &&  //
      someRatherSadlyLongCondition2 &&
      someRatherSadlyLongCondition3 &&
      someRatherSadlyLongCondition4) {}
```

By using `//`, the formatter is forced to break the line, and consequently will align the remaining conditions

**Comment by munificent** [comment]
Is the concern just that you don't like the formatting putting the `&&` at the end of the previous line and would prefer it at the beginning of the next line?

**Comment by noga-dev** [comment]
> Is the concern just that you don't like the formatting putting the `&&` at the end of the previous line and would prefer it at the beginning of the next line?

I don't like that I'm not allowed to place a trailing comma before the closing bracket of an if statement as I would be able to for any other closing bracket (ctor, func, etc.). I like consistency. The pretty auto formatting also helps with the OCD.

**Comment by cedvdb** [comment]
in constructor, array, functions, etc, it's an exhaustive list of arguments whereas `if` only has one boolean. So to me the comma makes little sens.

**Comment by munificent** [comment]
> I don't like that I'm not allowed to place a trailing comma before the closing bracket of an if statement as I would be able to for any other closing bracket (ctor, func, etc.).

Dart supports trailing commas in places where an unbounded comma-separated list of items is allowed, as in:

```dart
function(
  one,
  two,
  three,
  four,
  five,
);

var list = [
  one,
];
```

The primary motivation is that putting a trailing comma after every item, including the last, gives you an easy consistent way to comment out items by commenting the entire line:

```dart
function(
  one,
//  two,
  three,
  four,
//  five,
);

var list = [
//  one,
];
```

That wouldn't work for if, while, or do-while conditions because you must have one and exactly one expression in there. I can't see us allowing a trailing comma in a context where no *non*-trailing comma could appear, so I'm going to close this.

(The fact that the trailing comma also changes the formatting is a weird piece of historical inconsistency that I hope to reconcile at some point.)
