### ISSUE TITLE
double.parse issue!

### ISSUE THREAD

**Issue by Ali-Fadaei** [dart-lang/language#2135]
hi! I'm using double.parse for create custom text input formatter and i faced anormal behaviour of parsing!

`var example1  = '999,999,999,999,999';`
`double.parse(exmple1.replaceAll(',' ,  ''))` => 999999999999999.0

it seems correct but when add one extra 9:

`var example2  = '9,999,999,999,999,999';`
`double.parse(exmple1.replaceAll(',' ,  ''))` => 10000000000000000.0

if it is not an issue, please help me for realize why it happen.

**Comment by jakemac53** [comment]
This is working as designed, see https://dart.dev/guides/language/numbers (specifically the representation section): ` double maps to a 64-bit IEEE floating-point representation that matches the underlying processor.`.

It is notable that on the web, this is also the representation used for integers, since that is the representation that JavaScript uses for all numbers.

This [precision](https://dart.dev/guides/language/numbers#precision) section illustrates some of the visible effects of using that representation.

This is not a problem specific to Dart, you can google "floating point precision" or similar to research the topic.

**Comment by mateusfccp** [comment]
You can try to use the [`decimal`](https://pub.dev/packages/decimal) package:

```dart
import 'package:decimal/decimal.dart';

// ...

final example2 = '9,999,999,999,999,999';
Decimal.parse(example2.replaceAll(',' , ''))
```

**Comment by Ali-Fadaei** [comment]
@jakemac53  @mateusfccp thanks a lot!
