### ISSUE TITLE
Proposal: Elvis operator; a simplified ternary operator

### ISSUE THREAD

**Issue by erf** [dart-lang/language#2146]
I'd like to propose the [elvis operator](https://en.wikipedia.org/wiki/Elvis_operator) ( `?:` ) for the Dart lang, a shorthand for the ternary operator.

So you could replace:

```Dart
bool A = true;
bool B = false;
bool result = A ? A : B;
// true
```
With:
```Dart
bool A = true;
bool B = false;
bool result = A ?: B;
// true
```

Or using a method call:
```Dart
bool result = isBool() ?: false;
```
Or boolean expression:
```Dart
bool result = 3 > 0 ?: false;
```

Which would set `result` to `true` if the left hand is true, else use the right term ( which could be `true` or `false` .. or some other type than bool (?) giving either a bool or dynamic result ).

It is similar to the null-aware operator `??` but for non `null` boolean values or expressions.

I don't have strong opinion on the symbols to use, but it seem `?:` is often used.

**Comment by mraleph** [comment]
`A ? A : B` is the same as `A || B`. No need for special operators.

**Comment by erf** [comment]
Oh, that's true! I wonder why they have that operator in c++ as you also could also use the or operator.

**Comment by erf** [comment]
Ok, i see. It would not make sense to treat an `int` as a boolean value in Dart as its not part of the language, but in C/C++ it is.

but in C++:
```C
	int x = 2;
	int y = 2;
	int z = x || y;
	printf("%d", z);
	// yields 1
```
whilst:
```C
	int x = 2;
	int y = 2;
	int z = x ?: y;
	printf("%d", z);
	// yields 2
```

**Comment by Levi-Lesches** [comment]
I believe that's because of the casting to/from bool. In the first example, it converts 2 to a boolean, which is `true` because it's non-zero. Then it converts it back to an int, which is 1.

In the second example, it does another cast to bool in the Elvis operator, but instead of saving the boolean result as an integer, it selects the integer value 2. That's because whereas `||` is a boolean operator, the Elvis operator is a normal ternary and can be used on integers too.
