### ISSUE TITLE
Macros: Specify the ordering of members during introspection

### ISSUE THREAD

**Issue by jakemac53** [dart-lang/language#2157]
We need to specify the order in which members appear during introspection, in order to ensure the stability of generated code as well as consistency across the various tools that might be running macros. The same input code should always result in the same output code.

**Comment by munificent** [comment]
Yeah, I think we have basically two options here:

1. Specify an ordering. Probably just textual order.
2. Restrict the class introspection API that members have access to so that they can't see whether macros on other members have run or not.

The second option might be annoying and limiting in practice. Right now, member macros have access to the full introspection API for the surrounding class, don't they? If so, it's probably easiest just to specify that members are run in a certain order.

**Comment by jakemac53** [comment]
> * Specify an ordering. Probably just textual order.

Textual ordering might be fine, but there could be situations where re-ordering members becomes a breaking change then.

> Restrict the class introspection API that members have access to so that they can't see whether macros on other members have run or not.

This is already in place :).

> Right now, member macros have access to the full introspection API for the surrounding class, don't they?

They actually do not, until phase 3. They only get an `Identifier` for the surrounding class, because of exactly this ordering concern. They can get to the actual class in phase 3, when they can resolve identifiers to declarations.

> If so, it's probably easiest just to specify that members are run in a certain order.

We don't need to do this because we restrict the access but we could remove that restriction if we did. But I think it would make the issue around breaking changes due to re-ordering worse, and may also encourage macros that don't work well together. The existing api just doesn't allow writing a macro that could be broken by other macros running on other members.
