### ISSUE TITLE
Can we eliminate case labels with pattern matching?

### ISSUE THREAD

**Issue by munificent** [dart-lang/language#2196]
The pattern matching proposal makes some changes to existing switch statements: allowing patterns (obviously), but also removing the need for pointless `break` statements.

Another vestigial feature we could consider eliminating is labels on switch cases. Dart currently allows:

```dart
switch (v) {
  case 0:
    print('zero');
    continue another;
  another: case 1:
    print('one');
    break;
}
```

This won't work with patterns that bind variables since it would be possible to enter a case's body without having actually matched the value and bound the variables. We could disallow labels on only cases with patterns, or on only cases with patterns that bind variables, but... this is an almost-never used feature that has a famously high implementation burden.

Perhaps we could remove support for labels and continue to label inside switches *completely*. This is technically a breaking change. I analyzed 20,475,802 lines in 96,324 including the Dart SDK, Flutter SDK, ~2,000 Pub packages, and two large collections of open source Flutter applications. I found:

```
-- Switches (19957 total) --
  19946 ( 99.945%): no labels   ================================================
     11 (  0.055%): has labels  =
```

I didn't see any in there that felt particularly critical or compelling. Most could be trivially refactored to not use continue to label.

@rakudrama

**Comment by Wdestroier** [comment]
These switch cases with labels can be refactored to single responsability functions too 

```dart
var v = 1;

main() {
  switch (v) {
    case 0:
      printZeroOne();
      break;
    case 1:
      printOne();
      break;
  }
}

printZero() => print('zero');

printOne() => print('one');

printZeroOne() {
  printZero();
  printOne();
}
```

**Comment by lrhn** [comment]
I like the ability to use `switch` as a state machine as much as the next geek, but ... I have never actually used it.

That said, labels are not the real problem for pattern matching cases. They're just part of the bigger problem of allowing multiple `case`s to apply to the same block. You'd have the same problem with:
```dart
switch (value) { 
  case "":
  case 0:
  case List(length: 0) list: 
    // can't access `list` here
}
```

We need to ensure that multiple case patterns for the same code block introduce exactly the same variables (if we allow it at all).

A `case constantValue:`, `default:` or `label:` are all case entries which bind zero variables, and can therefore not be combined with a pattern which binds variables.
Or, probably better, they can be combined, but only the intersection of the variables are accessible. Then you can bind variables locally in the pattern, for:
```dart
  case 0:
  case List(length: var len) if len <= 0: 
     // can't see `len` here, but could in guard.
```

So, I see no *need* to remove labels, they fit right in with `case value:`.

We can still consider removing them if we actually want to get rid of the unstructured gotos. That should be for our implementors sake, and since it's already implemented, and (I presume), doesn't cost anything if you don't use the feature, I'm not sure it's really worth doing.

**Comment by munificent** [comment]
> I like the ability to use `switch` as a state machine as much as the next geek, but ... I have never actually used it.

Same. I just wrap the `switch` in a loop and explicitly reify the state.

> That said, labels are not the real problem for pattern matching cases. They're just part of the bigger problem of allowing multiple `case`s to apply to the same block. You'd have the same problem with:
> 
> ```dart
> switch (value) { 
>   case "":
>   case 0:
>   case List(length: 0) list: 
>     // can't access `list` here
> }
> ```
> 
> We need to ensure that multiple case patterns for the same code block introduce exactly the same variables (if we allow it at all).

The proposal [does cover that](https://github.com/dart-lang/language/blob/master/working/0546-patterns/patterns-feature-specification.md#variables-and-scope):

> Multiple switch case patterns may share the same variable scope if their case bodies are empty:
> 
> ```dart
> switch (obj) {
>   case [int a, int b]:
>   case {"a": int a, "b": int b}:
>     print(a + b); // OK.
> 
>   case [int a]:
>   case (String a): // Error.
>     break;
> }
> ```
>
> This would normally be a name collision, but we make an exception to allow this. However, **it is a compile-time error if all switch case patterns that share a body do not all define the exact same variables with the exact same types.**

We could possibly extend that rule to cover labeled cases too, but then we have to look inside the body of the cases to see which other labels they might jump to and it starts to get *really* fishy.

**Comment by Jetz72** [comment]
Perhaps you could extend the `continue` statement when moving to a variable-binding case to include a parameter list for that case's variables?

```dart
switch(obj) {
  case [int a]:
    print(a + 3);
    continue label(b: a.toString());
  label: case (String b):
    print(b + "three");
}
```

**Comment by munificent** [comment]
We could do that, but that's a lot of new mechanism for what is an almost completely unused feature. If we want tail call elimination (which is what this sort of is), we should probably just do tail call elimination. (But in practice, I don't think tail call elimination is that valuable in a language like Dart.)

**Comment by lrhn** [comment]
> We could possibly extend that rule to cover labeled cases too, but then we have to look inside the body of the cases to see which other labels they might jump to and it starts to get really fishy.

I don't see how why you'd need to look at the jumps. If a case has a label, that counts as an entry-point which binds no variables. So, no other case pattern for that case-block can bind variables either.

(I do think we should allow binding variables locally in the pattern, but only exposing the intersection of all the variables of the case patters of that case block. Then:
```dart
  switch (obj) {
     case a: ... continue b;
     label b:
     case List(length: var t) if (t > 2 && t < 5): ...
  }
```
would be valid, but `t` is not visible inside the case block, because it's lost in the intersection with the `label b:` entry which binds no variables.

That would be fine.

Now, a much more interesting approach is to allow continue *with arguments*:
```dart
switch (obj) {
  case Set<T> s: continue b(s.toList());

  label b(List<T> o):
  case List<T> o:
    // o is List<T>!
}
```
Just a thought :)

**Comment by munificent** [comment]
Closing this. We will keep supporting labels in switch statements. Switch expressions don't support labels.

**Comment by lrhn** [comment]
(And nor will element switches, since `continue` is not a valid element. Unless we want it to be.)

**Comment by munificent** [comment]
> And nor will element switches, since `continue` is not a valid element.

Well, more to the point, we don't have switch elements yet: https://github.com/dart-lang/language/issues/2124 :)

> Unless we want it to be.

Noooo.
