### ISSUE TITLE
Field of type `Future<void>` incorrectly makred as not assigned.

### ISSUE THREAD

**Issue by m93a** [dart-lang/language#2224]
If I define a field with type `Future<void>` and assign to it in the constructor, Dart incorrectly tells me that the field is uninitialized.

```dart
class Foo {
  Future<void> foo;
  
  Foo() { // error: Non-nullable instance field 'foo' must be initialized.
    foo = bar();
  }
  
  bar() async {
    await Future.microtask((){});
  }
}
```
This issue was encountered by others too, see this [SO question](https://stackoverflow.com/q/70864232/1137334).

## Expected behavior
The code should compile just fine because the field is initialized and the code is null-safe.

## Actual behavior
_Non-nullable instance field 'foo' must be initialized._
_Try adding an initializer expression, or add a field initializer in this constructor, or mark it 'late'_

**Comment by jakemac53** [comment]
Initializing the variable in the constructor body does not count here, because it could be accessed earlier in the constructor body (as well as in other initializers).

You could mark the field as `late` here, or nullable, or make it final and use a field initializer `final Future<void> foo = bar()`, etc.
