### ISSUE TITLE
A nullable variable can't be accessed inline even after performing null check.

### ISSUE THREAD

**Issue by Biplab-Dutta** [dart-lang/language#2229]
```dart
if (state.users != null && state.users.isEmpty) {}
```
The above line shouldn't be showing any error according to the dart docs screenshot that I have shared below.

But, it actually shows an error saying
```
The property 'isEmpty' can't be unconditionally accessed because the receiver can be 'null'.
Try making the access conditional (using '?.') or adding a null check to the target ('!').
```
To resolve the issue, bang operator is to be inserted.
```dart
if (state.users != null && state.users!.isEmpty) {}
```
Why do we need to use bang operator if `state.users != null` which is not what the dart docs suggest?

![image](https://user-images.githubusercontent.com/63902683/167294384-c23b16d5-8e61-4d55-bbc3-b74e15086b2c.png)

**Comment by lrhn** [comment]
This is intended behavior.
Dart can only promote *local variables*. The example image shows the local variable `s` being promoted from `String?` to `String` by an `s != null` check.

The code in question here is not testing a local variable, but a property of an object, `state.users`. The compiler cannot promote that to non-null because it cannot be certain (based on the static types) that the earlier check guarantees that the later use is actually non-null. (Because the object might be an instance of a subtype with a `users` getter which returns different values each time you call. It probably isn't, but the compiler needs the code to definitely be safe and sound, not just probably so.)

What you can do, and what is usually recommended, is to read value into a local variable which can be promoted. That also avoids reading the same value twice:
```dart
var users = state.users;
if (users != null && users.isEmpty) {}
```
