### ISSUE TITLE
[Macros] Concerns about static analyzability of Dart.

### ISSUE THREAD

**Issue by modulovalue** [dart-lang/language#2240]
@jakemac53 [wrote](https://github.com/dart-lang/language/issues/1482#issuecomment-1115128779):

> They produce a new file on the side, identical to one that could have been hand written [...] (but it will require an IDE to navigate to it or see it at all, as the file is not actually written to disk in your project).

This seems to have huge implications on how amenable Dart is to static analysis.

It seems to me that the current proposal implies the following:

__A Dart compiler has to be invoked to make it possible to reason about any piece of Dart code.__ 

Sound and efficient static analysis techniques that are possible (in theory) today (e.g the subfield of interprocedural analysis i.e. analysis that involves multiple declarations) for any dart library will only be possible for libraries whose transitive dependencies do not include `dart:macro`. Which in practice will mean that efficient interprocedural analysis won't be possible at all since most code will use macros.

By 'possible' I mean that interprocedural analysis will have to depend on the ability to execute Dart code, which is one of the reasons that makes it so hard to provide a good developer experience for javascript. The current proposal effectively is proposing to add javascripts `eval()` to Dart when looked at from a static analysis perspective.

This isn't a problem for compilers since they have different requirements and the freedom to work on all of the code at the same time, but one of the key selling points of Dart, its static analyzer, will be blocked from providing improvements that have the ability to clearly set Dart apart from the competition.

Dart isn't just JS with types. Dart provides properties that make it clearly better than TypeScript. I am worried that macros will take some of them away and make it *just* another language.

**Comment by lrhn** [comment]
>  Dart compiler has to be invoked to make it possible to reason about any piece of Dart code.

It least, a Dart macro processor must be invoked. The information passed to that processor, and the analyzing of its artifacts, are all well within the range of what the analyzer already does.
So, you need at least a Dart analyzer to analyzer Dart code.

It does prevent using naive text/regexp-based processors on Dart code, at least if it has to affect generated code as well.

(Would it be possoble to have an option to actually write the generated files to disk, once and for all, perhaps with names ending in `.g.dart` so they are easy to find and delete again? Or is that impossible because the dependency from the original source to the generated augmentations is not in the original source?)

**Comment by modulovalue** [comment]
lrhn wrote:
> [...] a Dart macro processor must be invoked.

Quote from the specification:
> [...] The macro is a full-featured Dart program with complete access to the entire Dart language. Macros are Turing-complete.

Therefore, any macro processor has to be a Dart compiler.

lrhn wrote:
> The information passed to that processor, and the analyzing of its artifacts, are all well within the range of what the analyzer already does. 

It seems to me that the dart analyzer does not depend on a Dart compiler to produce the information that it does? (of course, it depends on the artifacts that a Dart compiler needs to compile Dart code, but not an actual compiler?)

lrhn wrote:
> are all well within the range of what the analyzer already does

Given the statements above, I don't see how that is true.

**Comment by jakemac53** [comment]
Yes, all of this is essentially true, it is the cost that will be paid for having macros built into the language.

The fact that macros are Dart code in particular, means that you need a full Dart implementation in order to run them. We could have chosen a different (simpler?) language for writing macros, but we want them to be very expressive, and you would still have to have an implementation of whatever language you end up writing them in. The things we want to enable are not something you can really accomplish with a basic template language, so it wouldn't end up being significantly less complicated.

Yes, the analyzer will now require a Dart language implementation in order to analyze code.

> Sound and efficient static analysis techniques that are possible (in theory) today (e.g the subfield of interprocedural analysis i.e. analysis that involves multiple declarations) for any dart library will only be possible for libraries whose transitive dependencies do not include `dart:macro`. Which in practice will mean that efficient interprocedural analysis won't be possible at all since most code will use macros.

There seems to be an assumption here that macros cannot be efficiently compiled and run. This feature _will not ship_ if that ends up being the case, but we have been doing a lot of validation as we go along to measure the impacts, and have no reason to believe so far that the impact will be unacceptable. It also won't be zero.

Probably the largest risk here is the actual compilation time of the macros themselves. But as long as we are intelligent about doing incremental re-compilation, pre-compilation where possible (for example for pub deps), as well as shared compilation of dependencies, this should be an acceptable cost. A relatively simple macro can be compiled in around 100ms. In general we do not expect macros to have large dependency trees.

**Comment by modulovalue** [comment]
jakemac53 wrote:
> And it will be a major win for users of codegen today, as well as the overall dev experience (fix things like json serialization, data classes, ORM, lots of other use cases).

I fully agree that the use-cases that Macros are trying to solve will benefit the whole Dart ecosystem. However, it should be noted that these features are already implementable using build_runner without sacrificing the future of static analysis within Dart.
Why is build_runner not as popular as it should be?
1. Startup latency (which is a known problem, frontend related, and solvable, but for whatever reason not seen as a priority, *the common argument is 'Dart 2 introduced types -> Parsing in now inefficient', which I don't think is true.*)
2. Lack of integration with the dart analyser.

Jacob, you have worked on build_runner, would you agree?

---

> here seems to be an assumption here that macros cannot be efficiently compiled and run.

Please allow me to clarify what I was referring to.

I'm not talking about the performance of macros, but the fact that it seems to me that the current proposal will make it impossable to efficiently implement certain static analysis techniques that are currently possible (although not being used by any of the publicly available tools).
To set some context: if we look at the history of programming languages, we can observe the following notable events:
* Going from Machine code to Assembly added relative addressing.
* Removing Gotos by going from Assembly to C made the notion of basic blocks useful and non trivial.
* Going from C to Java added memory safety.

Each of those steps are notable partially because they restricted a programming language (without sacrificing performance too much) for the possibility of **significantly improved static analysis**

dart:mirrors is being deprecated because it makes static analysis less efficient. Sealed classes and modules are being proposed because they allow for better static analysis. I hope the pattern here is obvious.

Turing complete macros would be a step backwards if it means that they would restrict Dart with respect to static analysis.

### How would they do that?

Consider the following snippet:

```dart
// [...] directives that don't include dart:macro

class MyModel {
  final List<int> list = List<int>.generate(6, (final a) => a);
}
```

We can capture many useful constraints:
 * There's only one way to instantiate `MyModel`.
 * After the construction of `MyModel`, the list will definitely only have 6 elements. (inheritance is a problem, hard to model, but I have no evidence to assume that it would invalidate this argument.)
 * By modelling the semantics of List.generate and a subset of function literals we could also safely say what elements that list will contain.

The key point is that there are useful constraints to be collected and these constraints can be efficiently and dynamically maintained, stored and indexed without having to visit the whole repo in the worst case.
These sets of constraints can be combined by an associative operation. We can use Augmented Maps to maintain intermediate results and guarantee that all queries will always be logarithmic in time with respect to the amount of constraints.

Not Javascript, not Python, Kotlin or Java offer that much static analysis expressivity. Dart does.

Here's is the same example using a macro:
```dart
import 'package:my_macro/my_macro.dart';

@someAnnotation
class MyModel {
  final List<int> list = List<int>.generate(6, (final a) => a);
}
```

We can barely know anything about `list` here without having to potentially analyse the whole library graph. 

If something shouldn't make sense, please say so, I'll try to elaborate.

---

> It is also worth mentioning that we already have a (restricted) form of this happening today, the Const Evaluator

I have seen this argument come up before and I have to fully disagree that that is in any way related to turing complete macros.
 * First of all, I don't see how const evaluation in dart can be turing complete. _(this argument feels to me like saying we should add a standard library to regex because regex is almost as powerful as c++, which doesn't make any sense)_.
 * The reduced computational power of regular expression make them very efficient to implement for every case. The reduced computational power of constants in dart make them amenable to sound dynamic evaluation. (by dynamic in this case, I'm talking about the ability to maintain the resulting value of constant expressions in sub linear time even while subexpressions are being updated, and by sound I'm referring to having that property hold for all cases. (There are some detials missing here, but the point still holds.))

---

I'd be happy to be wrong.


I would appreciate a comment from
@eernstg & @leafpetersen

**Comment by jakemac53** [comment]
> Why is build_runner not as popular as it should be?
> 
> 1. Startup latency (which is a known problem, frontend related, and solvable, but for whatever reason not seen as a priority, _the common argument is 'Dart 2 introduced types -> Parsing in now inefficient', which I don't think is true._)
> 2. Lack of integration with the dart analyser.

Those are _part_ of the problem, but not the entire problem.

- Using a code generator also requires a lot of boilerplate, including often explicit references to weird looking generated symbols. We could fix some of that with just augmentation libraries.
- build_runner is not tightly integrated into really any tools. Integrating it into the analyzer wouldn't solve this, that is just one piece of the puzzle. Not everybody uses the analyzer (and we do want to support those people).
- build_runner is slow, especially for big apps. It doesn't scale linearly with app size, largely because of the way the analyzer is used within it.
- it uses the `analyzer` model for introspection. It lives on the side, and is not deeply integrated with the compiler itself.
- build_runner itself is pretty fundamentally unsound in a lot of subtle ways that would not be acceptable for the SDK.
- build_runner can only write to `source` or `cache` but our most popular tools don't understand `cache`, and `source` is really not what you want for a lot of things.

The main goal here is to make something with most of the power of build_runner (and actually more in some ways), which is also directly integrated into the compiler/analysis pipeline.

> * First of all, I don't see how const evaluation in dart can be turing complete. _(this argument feels to me like saying we should add a standard library to regex because regex is almost as powerful as c++, which doesn't make any sense)_.

Sure but we have explored making it so, and even landed experiments in the SDK to make it so, and it could someday be so. It isn't a crazy stretch.

> The key point is that there are useful constraints to be collected and these constraints can be efficiently and dynamically maintained, stored and indexed without having to visit the whole repo in the worst case.

This is just generally not true of most Dart code. Sure there are small things you can do with mostly only syntactic knowledge, but you don't even know what `List` is in this case without looking in your imported libraries. You can make assumptions but they are not provable in the general case.

Either way, we don't have any tools doing this type of thing. I doubt we will remove the requirement that all transitive dependencies are available.

In order to statically analyze any Dart file today, you must have access to _all transitive dependencies_ of that file. There is no way around that, and macros don't change that.

**Comment by modulovalue** [comment]
> Sure but we have explored making it so, and even landed experiments in the SDK to make it so, and it could someday be so. It isn't a crazy stretch.

Fair enough, could be, but even if constant evaluation was turing complete, my argument should still hold.

---

> Not everybody uses the analyzer (and we do want to support those people)

Why can't they include build_runner into their pipeline?

> build_runner is slow, especially for big apps. It doesn't scale linearly with app size, largely because of the way the analyzer is used within it.

I think this is an engineering problem?

> build_runner itself is pretty fundamentally unsound in a lot of subtle ways that would not be acceptable for the SDK.

Unsound with respect to what properties? Is the fundamental approach unsound or is this an engineering problem?

> build_runner can only write to source or cache but our most popular tools don't understand cache, and source is really not what you want for a lot of things.

Why can't it write to a different place?


> The main goal here is to make something with most of the power of build_runner (and actually more in some ways), which is also directly integrated into the compiler/analysis pipeline.

An important point that you have left out is that the macro system will be less powerful than build_runner because no custom files can be written to disk.

---

> This is just generally not true of most Dart code. Sure there are small things you can do with mostly only syntactic knowledge, but you don't even know what List is in this case without looking in your imported libraries. 

You don't need to definitely know that X is Y to infer valuable information about X. That's the whole point of static analysis. That's what lattice theory is for. You join two propositions and the wrong one can be rejected as you gain new information. If you don't have valuable information to join, or if most of the valuable information is only available offline, at the end, then this doesn't work anymore.

---

I feel like you are shooting down my arguments by providing examples that highlight very good points where the analyzer and build_runner could be improved while my point is that there are theoretical limits that the current proposal could impose on Dart and that this will remove properties that make Dart stand out compared to other programming languages with respect to static analysis.

**Comment by jakemac53** [comment]
> there are theoretical limits that the current proposal could impose on Dart and that this will remove properties that make Dart stand out compared to other programming languages with respect to static analysis.

I am still not understanding how/why this would be the case? The compilers/analyzer will be running the macros. They can see what augmentations exist, and analyze it pretty much just like normal code. Yes, it's true that any other tool that wants to do meaningful analysis will likely also need to run macros. But that doesn't mean they _can't do that analysis_.

> An important point that you have left out is that the macro system will be less powerful than build_runner because no custom files can be written to disk.

Fwiw, I do see build_runner as continuing to exist. It does indeed do much more than just generate code. It is for instance a decent target for generating documentation, processing images, other examples I have here. There may also be some code generation tasks that still make sense to do in build_runner (generating code from a proto or other IDL for instance may make more sense with build_runner still).

**Comment by modulovalue** [comment]
> I am still not understanding how/why this would be the case?
I will try to formulate a more concrete example tomorrow that will hopefully make that clearer.

**Comment by modulovalue** [comment]
_Update: I strongly believe that expanded macros should be written to disk and committed to source control. I provide an important reason for that [in this comment](https://github.com/dart-lang/language/issues/2239#issuecomment-1126700767)_.

_I will need to reevaluate the statements that I made in this issue should it be decided that expanded macros are written to disk._

**Comment by modulovalue** [comment]
As promised, here is a summary of the issues that I've raised:

My concerns can be put into two categories: 
* (1) about the macro proposal itself, and 
* (2) about how the macro proposal itself affects Dart.

---

### 1) The macro proposal itself: 

* Jake and Bob have convinced me that it would be best to not allow users to write arbitrary files to disk from within a macro. It was pointed out to me that macros are not meant to replace build_runner, so it is probably acceptable to redirect users who have more advanced requirements (_e.g. producing source maps_) to build_runner.

* I thought that writing the output of a macro to disk would mitigate all of the issues that I saw with (2), but Bob pointed out to me that that would end up being just a cache. I agree with that and I no longer think that writing macros to disk would solve the issues that I've raised with respect to (2). (_To be clear: writing macro output to disk might still be necessary for the UX within IntelliJ/VS Code, I'm not making any statements about that._)

**I'd like to conclude my concerns about (1) with the following: I don't see any major issues with the macro proposal itself (excluding any effects that it might have on Dart).**

---

### 2) How the macro proposal interacts with Dart:

_I wasn't able to summarise all the issues that I've raised with respect to (2) because they require significant context and I wanted to keep this summary short. In this comment, I'd like to point out the most severe one which has the biggest consequences for Dart as a language. If the consequences are not clear, I'd like to redirect the reader to the issues linked below._

By introducing the requirement that turing complete macros need to be executed to compile or statically analyze any given program, we lose the guarantees that static analysis or even compilation can ever be guaranteed to terminate for all Dart programs. This is not only important in theory, but a similar [issue has already caused huge problems inside of Google](https://youtu.be/rHIkrotSwcc?t=871). It seems to me that, even if Dart is less expressive with respect to certain abstractions, Dart has significantly better worst-case guarantees than for example C++. That would no longer be the case with an additional turing complete build step.


I go more into detail about (2) in: 
 * [the first part of my response to leaf](https://github.com/dart-lang/language/issues/2243#issuecomment-1133201639)
 * https://github.com/dart-lang/language/issues/2239
 * https://github.com/dart-lang/language/issues/2240
 * I have also challenged the notion that augmentation libraries are necessary to provide ergonomic code generation here: https://github.com/google/json_serializable.dart/issues/1149

--- 

I might not have all the necessary data or insight that would allow me to make the best decision, so I'm going to trust the Dart Team that the decision that they end up making is holistically the best one for Dart and its future.

cc: @munificent @jakemac53 @leafpetersen
