### ISSUE TITLE
The property type is not checked when I use ?? operator to set a value

### ISSUE THREAD

**Issue by lucas404x** [dart-lang/language#2257]
![code](https://user-images.githubusercontent.com/42918677/170079677-f8f34182-63dd-4a07-9da1-39311572cee3.png)

Hello guys! I don't know if it's a intentional behavior, but for me it's so strange that I think that's a bug.
Basically the property "total" is a double, but in the fromMap method I'm able to set a empty string if map['total'] is null. This probably works at compile-time because the "map" has dynamic subtypes, but since I'm using the null checker I think the right behavior is the compiler doesn't allow the string be defined in case of the value being null.
And yes, at runtime it's breaks.

**Comment by lucas404x** [comment]
Thanks for answer @jakemac53 !

I didn't knew the 'strict-casts' option. It's really cool! 😁
But in this way I'll need make a cast explicitly every time I try get a value from a map. The point it's for me is strange I see the attribute asking a type of value and the ?? operator doesn't check the value on the right to check if it's ok in case the left value be null.

I think would be a nice feature because It's really common see the people use this pattern around the projects. But it's just a suggestion anyway 🙂

**Comment by jakemac53** [comment]
> The point it's for me is strange I see the attribute asking a type of value and the ?? operator doesn't check the value on the right to check if it's ok in case the left value be null.

Yeah, I definitely see how that is confusing. Afaik the reason this isn't caught is because it is only the type of the entire expression that is checked against the LHS. That type is the least upper bound of `dynamic` and `String`, which is just `dynamic`. Then we check if `dynamic` is assignable to `double` which it is (without strict_casts enabled, but _not_ without). So it is allowed.

I think to catch this type of problem would require pushing that expected type "down" into the expression which would presumably be a large change to how the type system works today (and it probably isn't done that way for other, good reasons?). But maybe somebody else can chime in to that effect, I am not a type system guy haha.

`dynamic` is handy, but it really should be avoided wherever possible, imo. It causes all kinds of problems like this. I would remove it from the language entirely if I had the choice 😁.
