### ISSUE TITLE
"Promoting" variables bound in patterns based on previous cases?

### ISSUE THREAD

**Issue by munificent** [dart-lang/language#2264]
Consider:

```dart
int? maybeInt() => ...
switch (maybeInt()) {
  case null: print('no int');
  case var n: print('yes int');
}
```

What should the inferred type of `n` be here? According to the current proposal, it is simply `int?`, the static type of the matched value. However, the only way this case can be reached is if the other case failed to match. That implies that `n` will never be `null` and we know that statically. It would be sound to give it type `int`.

This potential behavior isn't quite promotion because it's not changing the type of an existing variable. (In the example here, there is no local variable holding the matched value.) It's a question of the *inferred* type of the *new* variable `n`. Should we take previous cases into account and infer a more specific type?

This can obviously get more complex when destructuring comes into play:

```dart
int? maybeInt() => ...
bool b = ...

switch ((maybeInt(), b)) {
  case (null, true): ...
  case (var a, _): ...
}

switch ((maybeInt(), b)) {
  case (null, true): ...
  case (null, false): ...
  case (var a, _): ...
}
```

In the first switch, we can't promote `a` to `int` because we could reach the second case with `null` in the first field if the second field is `false`. In the second switch statement, we could give `a` type `int` because the previous two cases exhaustively cover all values for the second field.

**Comment by lrhn** [comment]
YES! (If possible).

I'd be very sorry if
```dart
switch (nullableint) {
  case null:  ...
  case var n: ...
}
```
was less useful than:
```dart
if (nullableint == nul) {
  ...
} else {
 var n = nullableint;
 ...
}
```

We should treat `switch` as if its expression is a final variable. We know, for certain, that all `case` clauses refer to the same value, even if it's not a *named* value. The reason we promote variables is that we know they refer to the same value over time (and we drop promotion when they might have changed). It's not because variables are otherwise magical.
That's why a check in one place can affect the static type in another - it's the same value. A `switch` expression value satisfies that too. So, we should promote the switch value the same way we do local variables. (Now, if the switch value *is* a local variable, the question is whether we should promote it too, and we probably should, but be wary that it may change if patterns can have side effects.)

The complicated steps are complicated. We may have to recognize that `(null, true)` and `(null, false)` is exhaustive for the `(Null, bool)` part of `(int?, bool)`, leaving only the `(int, bool)` part. Which is obvious when you look at it, but probably not that easy to derive in full generality.

It also means that you must check switch cases in lexical order. Which is fine, I think we already say that.

**Comment by munificent** [comment]
> The reason we promote variables is that we know they refer to the same value over time (and we drop promotion when they might have changed). It's not because variables are otherwise magical. That's why a check in one place can affect the static type in another - it's the same value.

Ah, that's a smart way to look at it.

> A `switch` expression value satisfies that too. So, we should promote the switch value the same way we do local variables. 

Makes sense. We could probably even specify this by saying that the switch expression is stored if a fresh `final` local variable and that each case is checked against the promoted type of that variable.

> (Now, if the switch value _is_ a local variable, the question is whether we should promote it too, and we probably should, but be wary that it may change if patterns can have side effects.)

Yeah, I think we probably should. In general, the principle we seem to follow is that the language promotes as much as it soundly can.

Patterns can have side effects (because they can call arbitrary user-defined getters), but those side effects could only affect promotion if the local variable was assigned in a closure, which would turn off promotion so it should be fine.

> The complicated steps are complicated. We may have to recognize that `(null, true)` and `(null, false)` is exhaustive for the `(Null, bool)` part of `(int?, bool)`, leaving only the `(int, bool)` part. Which is obvious when you look at it, but probably not that easy to derive in full generality.

Yes, this is the hard part. If we want to go here, then I think we'll need to define exhaustiveness checking in such a way that it provides these properties. I believe the "spaces" approach I proposed does give this: after a series of cases, it yields a space that defines all of the *remaining* possible values. I'm not sure if @eernstg's predicate approach would.

> It also means that you must check switch cases in lexical order. Which is fine, I think we already say that.

Yeah, we already do and we must because cases can be non-disjoint:

```dart
switch (o) {
  case int x: print('int');
  case num n: print('num');
  case Object o: print('obj');
}
```

**Comment by eernstg** [comment]
About the ability to perform promotion on the result of pattern matching using predicates: I think that would actually fall out of the natural desugaring (yes, I know, we might not want to use that as the specification, but it could still serve as a framework for the understanding and correctness checks along the way). So here's the sugared code:

```dart
int? maybeInt() => 1;
bool b = true;

// Things to do in each case.
void c1() {}
void c2() {}
void c3(int i) {}

void main() {
  switch ((maybeInt(), b)) {
    case (null, true): c1(); break;
    case (null, false): c2(); break;
    case (var a, _): c3();
  }
}
```

Here is the desugaring that ensures one-time-only evaluation of each path in the pattern sequence:

```dart
int? maybeInt() => 1;
bool b = true;

// Things to do in each case.
void c1() {}
void c2() {}
void c3(int i) {}

void main() {
  late var maybeInt$ptn = maybeInt();
  late var b$ptn = b;
  if (identical(maybeInt$ptn, null) && identical(b, true)) c1();
  else if (identical(maybeInt$ptn, null) && identical(b, false)) c2();
  else if (true) {
    if (identical(maybeInt$ptn, null)) return; // Pretend!
    var a = maybeInt$ptn;
    c3(a); // Confirm that the type of `a` is `int`.
  }
}
```

To determine the appropriate promotions when running the body of the 2nd case, we'd rely on the knowledge that we are in the false continuation of `identical(maybeInt$ptn, null) && identical(b, true)` and the false continuation of `identical(maybeInt$ptn, null) && identical(b, false)`, and we would have the rule about boolean and enum values that allows us to conclude that we can reduce as follows:

```dart
!(identical(maybeInt$ptn, null) && identical(b, true)) && !(identical(maybeInt$ptn, null) && identical(b, false)) ===
(!identical(maybeInt$ptn, null) || !identical(b, true)) && (!identical(maybeInt$ptn, null) || !identical(b, false)) ===
(!identical(maybeInt$ptn, null) && !identical(maybeInt$ptn, null)) && ... /*3 other cases*/
```

But this is enough to know, in particular, that `!identical(maybeInt$ptn, null)`.

So we'd need to handle the knowledge that `!identical(maybeInt$ptn, null)` promotes `maybeInt$ptn` to `int`, but this occurs already with the desugared code.

So the only missing bit is that we don't currently perform this compile-time reduction whereby a finite type (bool, enum, bool?, enum?) is known to be exhausted by a finite set of object comparisons. I added the statement marked `Pretend!` above to get the same effect.

**Comment by eernstg** [comment]
Ah, one more thing: `continue Label` will break these promotions. ;-)

**Comment by lrhn** [comment]
A `continue label` is already very problematic when we have binding patterns. We may just have to disallow it entirely.
But if not, and it's labeling a `case` with a pattern with no bindings at all, then yes, it will be able to skip past other checks and therefore break promotion.

(I'd be more interested in allowing `continue: value` which restarts the switch with a new value.)

**Comment by munificent** [comment]
> Btw, how would the spaces approach handle this?

The algorithm defines subtraction on spaces so at each case, you can calculate the space for the value, subtract the spaces for the previous cases, and you're left with a space that defines the set of values that can flow into that case.

On poking at it a little, though, it may not work out as naturally as a predicate based approach like you suggest.

For example, according to the current prototype:

```dart
switch ((maybeInt(), b)) {
  // Remaining space is: (a: int?, b: bool)
  case (null, true): c1(); break;
  // Remaining space is: (a: int, b: bool)|(a: int?, b: false)
  case (null, false): c2(); break;
  // Remaining space is: (a: int, b: bool)|(b: false, a: int)
  case (var a, _): c3(a); // Confirm that `a` has type `int`.
}
```

So, with some inspection of the unions in the space, we can see that in each branch `a` has type `int`, so it should be safe to promote to that type.

I'm not sure if the algorithm generalizes well to larger more deeply nested destructuring, though.

**Comment by eernstg** [comment]
It is certainly promising that the spaces approach seems to allow us to go through every space in the union and gather the current knowledge about the type of a given path, and promoting that path to the ["least" upper bound](https://github.com/dart-lang/language/blob/master/resources/type-system/upper-lower-bounds.md#upper-bounds) of them all. (By the way, I think we'd need another space in the union after `(null, false)`, shown below.)

```dart
switch ((maybeInt(), b)) {
  // Remaining space is: (a: int?, b: bool)
  case (null, true): c1(); break;
  // Remaining space is: (a: int, b: bool)|(a: int?, b: false)
  case (null, false): c2(); break;
  // Remaining space is: (a: int, b: bool)|(a: int, b: true)|(a: int, b: false) <-- Add one case.
  case (var a, _): c3(a); // Confirm that `a` has type `int`.
}
```

We would presumably need to combine or split operands of unions:

```dart
switch class A { int? i; A(this.i); }
class B extends A {}
class C extends A {}

void f(A a) {
  switch (a) {
    // Initial space: A
    case B(i: null): ...
    // Remaining space: B(i: int _) | C
    case C(i: null): ...
    // Remaining space: B(i: int _) | C(i: int _)
    // Combine the operands to get A(i: int _).
    case A(i: var j): ... // Infer type `int` for `j`.
  }
}
```

However, the space simplification needs to include checks that shared member names are actually inherited:

```dart
switch class A {}
class B extends A { int? i; B(this.i); }
class C extends A { int? i; C(this.i); }

void f(A a) {
  switch (a) {
    // Initial space: A
    case B(i: null): ...
    // Remaining space: B(i: int _) | C
    case C(i: null): ...
    // Remaining space: B(i: int _) | C(i: int _)
    // A(i: int _) does not make sense, so we can't simplify this space to `A(i: int _)`,
    // but simplifying it to `A` is imprecise, we forget everything we're detected.
    // So we'd need to keep the remaining space unchanged.
    ...
  }
}
```

Also, we'd need to consider covariant return types (NB: there's no connection to the modifier `covariant`, this is simply about the sound variance that is available for return types):

```dart
switch class A { A? get next; } // Note that a switch class is abstract.
class B extends A { final B? next; B(this.next); }
class C extends A { final C? next; C(this.next); }

void f(A a) {
  switch (a) {
    // Initial space: A
    case B(next: null): ...
    // Remaining space: B(next: B _) | C
    case C(next: null): ...
    // Remaining space: B(next: B _) | C(next: C _)
    // We can reduce this to A(next: A _), but we'd need to be careful about the rules for how to do it.
    case A(next: var a1): ... // Infer type `A` for `a1`.
  }
}
```

Here are the three examples, in the same order, expressed as a potential desugaring where we use boolean expression processing (for brevity, I omit the late local variables and assume that we can promote expressions of the form `<receiver> ('.' <selector>)*`, e.g., `a.i` or `a?.next?.next`):

```dart
switch class A { int? i; A(this.i); }
class B extends A {}
class C extends A {}

void f(A a) {
  if (a is B && identical(a.i, null)) ...
  else if (a is C && identical(a.i, null)) ...
  else if (true) { // The pattern `A(i: var j)` is irrefutable, hence `true`.
    var j = a.i;
    ...
  }
}
```

As usual, in order to infer that `a.i` can be promoted to the corresponding non-nullable type, we'd consider the known-true expression at the third branch `if (true)`, and insert `true` for `identical(a.i, null)`, and show that this cannot possibly hold because the known-true expression would then be false:

```dart
!(a is B && identical(a.i, null)) && !(a is C && identical(a.i, null)) ===
(a is! B || false) && (a is! C || false) ===
a is! B && a is! C ===
false // Because `B` and `C` exhaust `A`, which is the static type of `a`.
```

We would need to be able to recognize that a finite set of types `T1..Tk` can exhaust a `switch` class `T` which is their immediate supertype, so we can reduce `a is T1 || .. || a is Tk` to `a is T`, and similarly for the negation `a is! T1 && .. && a is! Tk` reduces to `a is! T`. Otherwise we do not need any extra magic.

When the shared member names are actually not inherited:

```dart
switch class A {}
class B extends A { int? i; B(this.i); }
class C extends A { int? i; C(this.i); }

void f(A a) {
  if (a is B && identical(a.i, null)) ...
  else if (a is C && identical(a.i, null)) ...
  else ... // Additional cases.
}
```

In this case we'd again know the following:

```dart
!(a is B && identical(a.i, null)) && !(a is C && identical(a.i, null)) ===
(a is! B || !identical(a.i, null)) && (a is! C || !identical(a.i, null))
```

However, we couldn't simplify this in the same manner, because the first and the second occurrence of `a.i` do not resolve to the same declaration, and there is no shared declaration in `A` that they both override, so there's no hope that we can combine the two occurrences of `identical(a.i, null)` and prove anything.

For the covariant return types, we'd proceed as follows:

```dart
switch class A { A? get next; } // Note that a switch class is abstract.
class B extends A { final B? next; B(this.next); }
class C extends A { final C? next; C(this.next); }

void f(A a) {
  if (a is B && identical(a.next, null)) ...
  else if (a is C && identical(a.next, null)) ...
  else if (true) { // The pattern `A(next: var a1)` is irrefutable, hence `true`.
    var a1 = a.next;
    ...
  }
}
```

In this case we have the following known-true expression, where the declaration referred by `a.i` in both cases _do_ have a common overridden declaration in a`A`, so we try to set `identical(a.i, null)` to true and prove a contradiction:

```dart
!(a is B && identical(a.i, null)) && !(a is C && identical(a.i, null)) ===
(a is! B || false) && (a is! C || false) ===
a is! B && a is! C ===
false // In this case it is also true that `B` and `C` exhaust `A`.
```

Given that we don't actually compute anything like the remaining space here, we actually avoid the complications associated with the covariant return types.
