### ISSUE TITLE
extension method declared for class with nullable generic type invokable on object which doesn't match 

### ISSUE THREAD

**Issue by wheeOs** [dart-lang/language#2273]
```dart
extension Ext<T> on List<T?> {
  void foo() {
    add(null);
  }
}

void main() {
  final List<int> list = [3, 42];
  //this call should neither be possible in compile time nor suggested in code completion
  list.foo(); 
}

```

**Comment by lrhn** [comment]
It's possible. The problem is that a `List<int>` is-a `List<int?>`, and it's possible to up-cast to `List<int?>`.

You are effectively seeing the same result as the code:
```dart
final List<int> list = [3, 32];
List<int?> $this = list;
$this.add(null);
```
That's valid Dart code and it throws at runtime because `List.add` is inherently unsafe.

Because the `on`-type match of an extension is subtype based, there is no way to restrict it to only matching lists with nullable element types, because `List<int>` will always match where `List<int?>` does.
