### ISSUE TITLE
[Spec] The grammar does not have rules for dynamic types

### ISSUE THREAD

**Issue by kaby76** [dart-lang/language#2276]
I am testing the Spec. I programmatically scrape the [Spec](https://github.com/dart-lang/language/blob/master/specification/dartLangSpec.tex) for the rules of the grammar and generate an Antlr4 grammar. The grammar is then refactored via my Trash tool kit to fix various problems. Finally, the grammar is tested against the [sdk](https://github.com/dart-lang/sdk) library. The scraped grammar is better than the [grammar written by the Dart Language Team](https://github.com/dart-lang/sdk/blob/main/tools/spec_parser/Dart.g), but it is only as good as the Spec, which seems incomplete.

I am noticing missing rules in the [Spec](https://github.com/dart-lang/language/blob/8fb9f0ad4e8e5eabb1ec83abcd53f2f587d111fb/specification/dartLangSpec.tex) for dynamic types. For example, I cannot parse [dynamic methods](https://github.com/dart-lang/sdk/blob/09967d8c255e6d996bbc419fe3a2148aaff5e9e4/sdk/lib/_internal/wasm/lib/object_patch.dart#L43).

**Comment by lrhn** [comment]
The word `dynamic` is not a reserved word, just a built-in identifier. That means that it *is* an `<identifier>`, just with rules against using it in particular places (and even those rules are loosened for `dynamic` and `Function`).
I think you are right and the grammar doesn't include that exception:
```ebnf
<typeIdentifier> ::= <IDENTIFIER>
  \alt <OTHER\_IDENTIFIER>
```
should probably be
```ebnf
<typeIdentifier> ::= <IDENTIFIER>
  \alt <OTHER\_IDENTIFIER>
  \alt \DYNAMIC{}
  \alt \FUNCTION{}
```

We should be a little careful since we use have
```dart
<qualifiedName> ::= <typeIdentifier> `.' <identifier>
  \alt <typeIdentifier> `.' <typeIdentifier> `.' <identifier>
```
and `dynamic` and `Function` are only allowed as *types*, not as *prefix names*. 
Still, even if the grammar allows it, there won't ever be a prefix names `dynamic`.

@eernstg

**Comment by kaby76** [comment]
Thanks. I'll update my code to refactor the generated grammar for now.

**Comment by kaby76** [comment]
Exploring some of the permutations:

1) "dynamic" as a field => compiles.
```
class Expression {
  String dynamic = '+';
  bool isPlusOrMinus(Expression expression) {
    if (expression.dynamic == '+') return true;
    if (expression.dynamic == '-') return true;
    return false;
  }
}
```

2) "dynamic" as a type => compiles.
```
class Expression {
  dynamic String = '+';
  bool isPlusOrMinus(Expression expression) {
    if (expression.String == '+') return true;
    if (expression.String == '-') return true;
    return false;
  }
}
```

3) "dynamic" as a field and type => does not compile.
```
class Expression {
  dynamic dynamic = '+';
  bool isPlusOrMinus(Expression expression) {
    if (expression.dynamic == '+') return true;
    if (expression.dynamic == '-') return true;
    return false;
  }
}
```
```
$ dart t5.in
t5.in:2:3: Error: 'dynamic' isn't a type.
  dynamic dynamic = '+';
  ^^^^^^^
t5.in:2:11: Context: This isn't a type.
  dynamic dynamic = '+';
          ^^^^^^^
```

**Comment by lrhn** [comment]
Those permutations look correct.
The word `dynamic` can be used as a type reference (referring to the name exported by `dart:core`), and it can be used a member name (because all built-in identifiers can).

It can't be used as a type declaration `typedef dynamic = ...`, `class dynamic {}`, etc, or as an import prefix.

If you declare `dynamic dynamic = ...` then the declaration is in its own scope, and therefore the "type" `dynamic` refers to the variable declaration `dynamic`, which is not a type.

**Comment by eernstg** [comment]
I believe it makes no difference whether `dynamic` is added to `OTHER_IDENTIFIER` or it's added to `typeIdentifier`. But the workaround would just go away now, so it shouldn't matter at all. ;-)

But it would be great to hear if you notice

> some other things
