### ISSUE TITLE
Future catchError not work well.

### ISSUE THREAD

**Issue by Stitch-Taotao** [dart-lang/language#2300]
Reproduce Code
```
import 'dart:async';

void main(List<String> args) {
  runZonedGuarded(() {
    Future((() {
      return '3';
    })).then((value) {
      print(value);
      throw ("error!!!!!");
    }).catchError((Object error) {
      print('catchError:$error');
    });
  }, ((error, stack) {
    print('unhandle error:$error');
  }));
}
```
You can run it direct in [DartPad : Reproduce Code](https://dartpad.dev/?id=183ab30e1ff4209438f37af0dcb4d011)

I think the unhandle error should be exposed in complile time ，some like `catchError function take a wrong type onError parameter` . Otherwise , catchError make no sense and was confusing!

**Comment by ykmnkmi** [comment]
Dart don't support overloading. From docs:
```dart
/// The `Function` below stands for one of two types:
/// - (dynamic) -> FutureOr<T>
/// - (dynamic, StackTrace) -> FutureOr<T>
```

**Comment by lrhn** [comment]
This is a known issue. As @ykmnkmi says, Dart doesn't have overloading, so if a method must be able to accept both a `T Function(Object)` and a `T Function(Object, StackTrace)`, it will be written to accept the nearest common supertype, which happens to be `Function`. That's not particularly useful for type checking or inference, and it shows that the API was designed for Dart 1.0, which had a much more lenient type system.
It's a big regret that we didn't make every error handler require `Function(Object, StackTrace)` in the Dart 2.0 migration. Alas, there was quite enough other things to migrate too.

Today, what you can do is use `onError` instead of `catchError`. It's an extension method with better type checking, and (arguably) a better API, which falls back on calling `catchError` under the hood.

The other thing you can do is to change the `.then(...)` to `.then<void>(...)`. That avoids inferring `.then<Never>(...)` which is hard for the `catchError` to follow.

No current plans to change the APIs. It's breaking, and quite a lot of third-party classes implement `Future`. Really quite a lot!
We don't have a good way to do API migration, like we do language versioning. If we get one, this fix will be high on the list.
Until then it's, sadly, a known issue with no fix planned.
