### ISSUE TITLE
How to disambiguate a record type with ommitted parentheses

### ISSUE THREAD

**Issue by srawlins** [dart-lang/language#2302]
https://github.com/dart-lang/language/blob/df9574472a7a84aa518b88794c5ec9ff6349f170/working/0546-patterns/records-feature-specification.md

> If there are only named fields, you are allowed to omit the surrounding parentheses:
>
> `{int n, String s} pair;`

How do we disambiguate between a record-with-only-named-fields, and named fields of a record (or named parameters of a function type)? For example, the previous line:

> `(bool, num, {int n, String s}) quad;`

Is this a record with three positional fields (the last one being a record with two named fields), or a record with two named fields and two positional fields? It seems that you just choose the latter (disambiguate to "not a record itself"). Here are two more examples:

```dart
{int n, String s} pair;
```

Well yes, it's the same as the first example, but I might ask the question: is this a record with two named fields, or is it a record with one positional field which is typed as a record with one positional field which is typed as a record with two named fields (more formally, `((({int n, String s})))`)?

And how about:

```dart
typedef F = void Function(int, {int n, String s});
```

Does this define a type alias for a function which accepts two positional parameters, or one positional and two named? Again, the 'disambiguate to "not a record itself"' rule would lend itself here, preventing a breaking change to existing syntax.

**Comment by munificent** [comment]
> How do we disambiguate between a record-with-only-named-fields, and named fields of a record (or named parameters of a function type)? For example, the previous line:
> 
> > `(bool, num, {int n, String s}) quad;`
> 
> Is this a record with three positional fields (the last one being a record with two named fields), or a record with two named fields and two positional fields? It seems that you just choose the latter (disambiguate to "not a record itself").

Ah, that's a good point! We probably could just pick like you suggest here. But this does seem like a readability trap even if we can make it *technically* not ambiguous. If a user writes:

```dart
Function({int i, String s})
```

Can we really be certain whether they *intend* this to be a function type that takes two named parameters and not a function type that takes a single record?

> I might ask the question: is this a record with two named fields, or is it a record with one positional field which is typed as a record with one positional field which is typed as a record with two named fields (more formally, `((({int n, String s})))`)?

This one is at least easy because in the current proposal there is no such thing as a record with only a single positional field. :)

Thanks for raising this issue! I'm going to sit on it for now so we can mull it over. There is an obvious easy fix which is to eliminate the shorthand and always require the parentheses so I'm not worried about coming up with some other better solution right now. But it might be nice to try to come up with a syntax that doesn't require double brackets for named-only records but also avoids this ambiguity.

**Comment by munificent** [comment]
I went ahead and decided to remove the shorthand syntax. Simple and consistent is best. We can always refine the feature with a little syntactic sugar later if necessary.
