### ISSUE TITLE
Define the semantics of `augment super` for operators

### ISSUE THREAD

**Issue by jakemac53** [dart-lang/language#2325]
From @johnniwinther: "What does augment super[0] mean? Is it the call to the operator [] that is currently being augmented (like in augment int operator[](int index) => augment super[index];) or a call to operator [] on the value of the currently augmented getter (like in augment List<int> get property => [augment super[0]];, or both depending on context?"

I would say that inside of an augmented `operator []` method it calls the `operator []` method that is being augmented. In all other cases it would only be valid if augmenting a getter, and it would call `operator []` on the return value of the augmented getter. This does make it context dependent, but also I think makes it read most intuitively.

I also think combining `augment super` into a single keyword like `augmented` would help readability here.

**Comment by jakemac53** [comment]
My 2 cents - it calls the index operator `[]` on the currently augmented declaration.

In other words `augment super` gives a reference to the augmented declaration, and you can then invoke any methods you like on that (including `[]`).

Essentially `augment super` is always wrapped in parenthesis :).

**Comment by jakemac53** [comment]
This might be more obvious if we had a single reserved word which always referred to the augmented declaration - it mostly looks weird because it is two separate words but is really just a reference to a single thing.

**Comment by lrhn** [comment]
I'm very much not sold on the `augment super` syntax. We should find something better, and more ... readable.

(What's better than `super`? Maybe `ultra`?!)

**Comment by scheglov** [comment]
`augmented`

**Comment by jakemac53** [comment]
I do personally like `augmented`, the push back on that has been not wanting to create more reserved words, but this would only be reserved in the scope of an augmentation and might be ok imo.

**Comment by munificent** [comment]
I definitely don't love `augment super`. I'm also not particularly fond of `import augment` or `library augment`. I do think `augment` as a modifier on declarations works fairly well.

This was a part of the proposal that I sort of made up a semi-placeholder syntax for and never really revisited since I was mostly focused on the semantics. I picked `augment super` at the time because the syntax was fairly close to `super` calls. But that's no longer the case as I understand it.

With `super`, you can invoke any member from the superclass from any member:

```dart
class C extends B {
  void foo() {
    super.bar();
    //    ^^^ Not foo().
  }
}
```

But we don't support that for augmentations (for good reason). So there's no `.` or identifier after the `super` in `augment super`. So we're not getting much user value out of reusing `super` for this. It suggests a syntax that doesn't actually work.

On the other hand, since `super` is a reserved word, it does mean that you can unambiguously use `augment super` calls even in members named `augment()`. If we make a contextual keyword for this, whatever keyword we pick becomes an identifier where if you use it to name a member, you can never touch it with a macro. :)

I toyed with the idea of letting the augmentation *choose* a name for the super call:

```dart
augment(orig) void foo() {
  //    ^^^^ Whatever identifier you want.
  orig();
}
```

But that seems like more flexibility and mechanism than is worth having.

Maybe we could say that `super` *without* a `.` and identifier after it as treated as the way to call the augmented member?

```dart
augment void foo() {
  super(); // Calls original foo().
}
```

This syntax is already in use for implicit `call` invocations. `super(123)` is sugar for `super.call(123)`. But no one on Earth cares about that. We could either make a breaking change and remove that syntax or say that that sugar is not available inside the bodies of augmenting members.
