### ISSUE TITLE
Invalid assert in const constructor should not be allowed

### ISSUE THREAD

**Issue by cedvdb** [dart-lang/language#2335]
The following won't compile as `MyIntList` is unusable as a const constructor.  I believe this should not be allowed in the same vein as `assert(base.isNotEmpty)` is not allowed.

```dart
import 'package:collection/collection.dart';

void main() {
  const myIntList = MyIntList([1,2]); // throws here
}

class MyIntList extends DelegatingList<int> {
  const MyIntList(super.base) : assert(base.length > 0);
}

class MyOtherIntList extends DelegatingList<int> {
  const MyOtherIntList(super.base) : assert(base.isNotEmpty); // thows here
}
```

**Comment by eernstg** [comment]
I think this is covered by [this proposal about extending the set of constant expressions](https://github.com/dart-lang/language/issues/2219) and [this proposal about checking the types of potentially constant expressions](https://github.com/dart-lang/language/issues/1296).

As you mention, `base.isNotEmpty` is rejected. It not a constant expression (this is known based on the syntax alone), and DartPad (Based on Flutter 3.0.4 Dart SDK 2.17.5) does report a compile-time error on the constructor of `MyOtherIntList`.

The first proposal mentioned above would make `base.isNotEmpty` a potentially constant expression, and it would be a constant expression when the receiver is a constant list, so constant invocations of the constructor would just work.

`base.length` is accepted as a potentially constant expression, because (1) potentially constant expression checking does not have access to types, and (2) `length` is allowed in a constant expression when the receiver is a `String`.

With the second proposal mentioned above, potentially constant expressions would take the types of some subexpressions into account, and it would then be able to mark `base.length` as a compile-time error (with today's constant expression) or it could detect that `List.length` can be a constant expression (if we extend the set of constant expressions).

**Comment by cedvdb** [comment]
Alternative
