### ISSUE TITLE
Can records be const?

### ISSUE THREAD

**Issue by srawlins** [dart-lang/language#2337]
The records spec does not currently use the word 'const' or 'constant'. Can a record be const? Something like

```dart
const x = 'one';
const y = 'two';

const r = (x, y);

// Separate, for patterns, which has an open TODO on const evaluation of destructuring.
const (d, e) = r;
```

**Comment by lrhn** [comment]
I'd say yes. 

That only matters for whether the record can be used in a `const` expression, because records are already immutable and auto-canonicalizing (the way `identical` is defined on them). Any record which contains constant element expressions is automatically indistinguishable from being constant.
So let's also say that we allow them in const expressions.

**Comment by munificent** [comment]
Yeah, I don't see any reason to disallow const records. I'll leave this open as a reminder to update the proposal to include it.

**Comment by leafpetersen** [comment]
This should probably get added in soon.

**Comment by mit-mit** [comment]
@munificent kind reminder to get this into the spec.

**Comment by eernstg** [comment]
> My personal opinion is that I'd prefer to steer users away from doing `identical` on records

Certainly! I would expect the implicitly induced operator `==` on record types to use `identical` to provide good performance based on pointer equality in the case where the receiver is boxed (and the compiler would presumably inline `==` as several separate tests, in the case where the receiver is an unboxed record).

Hopefully this would allow us to lint against `identical(e1, e2)` in all cases where the type of `e1` or `e2` is a record type, and it would then only occur in the implicitly induced `==` implementations.

We could treat structs / value classes the same, and get the same effect.

The other reason why I'm arguing that we might want to allow records to be explicitly const is

> to document that the expressions are expected to be constant

that is: to document the intention and to get a compile-time error if its components aren't actually constant.

If we do not ensure any kind of record canonicalization explicitly then I suspect that we'll have it implicitly: How would backends otherwise be able to canonicalize objects with instance variables whose value is a record?

```dart
class C {
  final (int, int) pair;
  const C(int i1, int i2): pair = (i1, i2);
}

class D {
  final (C, C) pair;
  const D(C c1, C c2): pair = (c1, c2);
}
```

If constant expressions yielding an instance of `C` will have different representations of `pair` just because records are not canonicalized, then the decision about whether to canonicalize instances of `D` gets more complex than simply checking pointer identity of each instance variable. So I expect that we will have canonicalized records, because the backends need them.

Another thing is that if we do support `const <recordLiteral>` in constructor initializer lists, and include the case where some components of the record are only potentially constant (and check each constructor invocation), then we could also support `const <listLiteral>` and `const <setOrMapLiteral>`  in constructor initializer lists:

```dart
class E {
  final List<int> xs;
  final int j;
  const E(int i, this.j): xs = const [1, i]; // OK.
}

void main() {
  C(42, 43); // OK.
  var i = 42;
  C(i, 43); // OK.
  C(42, i + 1); // Compile-time error.
}
```

This has been requested, e.g., recently in https://github.com/dart-lang/language/issues/823#issuecomment-1204415563, and it would probably be a quite useful feature if we allow collection literals to be "constant after actual argument substitution".

> Should destructuring be constant?

That would be nice, and it fits nicely into https://github.com/dart-lang/language/issues/2219.

**Comment by lrhn** [comment]
> I would expect the implicitly induced `operator ==` on record types to use identical to provide good performance based on pointer equality in the case where the receiver is boxed

As pointed out elsewhere (last language-team meeting I think), that's not actually a valid optimization. There are objects which are identical, but not `==` to themselves.
Well, there is an object (singular): NaN.

Still, it means that `(1, double.nan)` must be un-equal to itself. If it tries to use `identical` checks to avoid that, it will give a wrong answer in the fast case. (Not what "fail fast" means!)

> How would backends otherwise be able to canonicalize objects with instance variables whose value is a record?

Ouch. That *is* a good question, and a reason why we should perhaps canonicalize records.
Or, alternatively, we introduce the notion of *structurally equivalent* as:

> Values *a* and *b* are structurally equivalent iff:
> * Both are reference values and it's the same reference (`identical(a, b)`), or
> * Both are records, they have the same shape, and for each pair of corresponding fields of *a* and *b*, those fields' values are structurally equivalent.

Then we say that we canonicalize objects to the same instance if the values of their instance variables are structurally equivalent. That's something we're willing to check at compile-time, even if we don't do it at runtime.
We don't have to make a constant `identical(record1, record2)` use structural equivalence.

Basically, we introduce the "recursive identical" functionality in the specification, but do not use it for the `identical` function (other than as specification that `identical(r1, r2)` may return true if `r1` and `r2` are structurally equivalent records).

That's the equivalence we really *care* about, we just don't want to make `identical` have to implement it.
We don't talk about *canonicalization* of records, because we don't canonicalize, but we still have a notion of being indistinguishable which does not include identity.

We *could* expose that relation, as a static `Record.identical(r1, r2)` which checks structural equivalence. Then you have to opt in to the more expensive version.


I would not allow `const (1, i)` in a constructor initializer list. That's not a constant. Also wouldn't allow `const [1, i]`.
We could allow `auto [1, i]` which is constant in a constant invocation, and not in a non-constant invocation, but I'm wary about having the same code generate different kinds of objects depending on invocation mode.
