### ISSUE TITLE
Is the record pattern shorthand syntax recursive?

### ISSUE THREAD

**Issue by leafpetersen** [dart-lang/language#2382]
The patterns proposal [here](https://github.com/dart-lang/language/blob/91f921525ec295cbaf5e21bb418a3dfa1dab9018/working/0546-patterns/patterns-feature-specification.md#record-pattern) introduces a shorthand syntax, e.g. `field : field as int` may be abbreviated as `:field as int`.  Is this name inference recursive?  That is, can I write `:field? as int` as shorthand for `field : field? as int`?

**Comment by munificent** [comment]
> Is this name inference recursive?

It could be in theory, but the grammar is restricted such that there isn't anything recursive you could actually write. The relevant sentence is: "The subpattern must be a variable pattern or cast pattern, which may be wrapped in any number of null-check or null-assert patterns."

(I should fix that to not say "any number of".)

The LHS of a cast pattern isn't an arbitrary pattern but only an identifier. We *could* generalize that to take an arbitrary pattern but I think it gets really confusing if you were to try to do, I don't know:

```dart
var [a, b] as SomeCustomList = ...
```

Think of cast patterns less like null-check and null-assert patterns which do a type test and contain a subpattern and more like a variant of variable patterns where the type annotation is asserted instead of tested and then binds a variable.

And null-check and null-assert patterns take a `primaryPattern` as their subpattern not a `unaryPattern`, so you can't nest them (since doing so is pointless).

**Comment by leafpetersen** [comment]
> so you can't nest them (since doing so is pointless).

Not entirely pointless, right?  e.g. `(x as T)?` casts `x` to `T` and then checks if it is null?

But agreed that the uses are fairly niche.

**Comment by munificent** [comment]
> Not entirely pointless, right? e.g. `(x as T)?` casts `x` to `T` and then checks if it is null?

Hmm, I suppose that's true. (Note that it would check for `null` first since `?` is the outer pattern than then cast it to `T` since patterns are "evaluated" outside-in.

The current proposal doesn't let you use parentheses in the field shorthand syntax, so that specific example isn't allowed. We could allow it since `(subpattern)` is also a unary pattern. I don't have a strong opinion one way or the other. Thoughts?

**Comment by leafpetersen** [comment]
> I don't have a strong opinion one way or the other. Thoughts?

Not really.  It's pretty niche.

**Comment by munificent** [comment]
OK, let's leave it as-is then. This way, you can use the field name shorthand in the cases that matter and compose it with `?`, `!`, and `as` (which are all patently useful) but you can't bury the name arbitrarily deeply.
