### ISSUE TITLE
Do we want to allow patterns in "variable-like" declarations?

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/language#2403]
The patterns spec proposal says:

> Places in the language where a local variable can be declared are extended to
> allow a pattern, like:
>
> ```dart
> var (a, [b, c]) = ("str", [1, 2]);
> ```

There are other places where we could in principle allow patterns.  Do we want to?  For example:
```dart
// Top level variable declaration:
final (a, b) = ...;

// Field
class C {
  late (a, b) = ...;
}

// Function or method parameter:
foo((int a, int b), int c) { ... }
```

CC @leafpetersen @munificent @eernstg @lrhn @mit-mit @natebosch @jacob314 @scheglov @srawlins @bwilkerson

**Comment by lrhn** [comment]
I'd require any pattern binding to have an immediate expression being pattern-matched. 
It does not make sense to do:
```dart
var (int x, int y);
```
and not do a pattern match immediately, because an assignment cannot assign to the *pattern*, only to the variables.
So, all pattern-based declarations must have an initializer expression (or be a parameter, which gets a value when it's instantiated too).

I'd probably avoid the `late` pattern binding as well.
If it's final, it can make all the pattern variables `late` and initialize them all at the same time (on read of any of them).
If the declaration is *not* final, then introducing multiple late variables at the same time gets iffy.
What would happen if you assign to *one* of the variables of `late var (a, b) = pair;`, and then read the other?

So, no late pattern matches either, the pattern match *must* happen when the variables are introduced.
Which does rule out top-level and static declarations, at least if they're not final. We could allow final ones.

Other than that, I'd allow patterns everywhere a value can flow into something.

I'd even consider allowing patters in:
* `const` declarations: `const (a, b) = someConstantPair;`. (Slightly worrisome, we don't usually allow constant destructuring or projection.)
* `catch`/`on` clauses: `on CastFailure<var S, var T>`, `catch (ArgumentError{:var invalidValue, :var message}, StackTrace)`. (Is `(e, s)` itself a pair-record pattern?|)
* extension `on` types (if we get type patterns): `on Future<var T>` to capture runtime type.
* maybe even initializer list entry LHSs: `C(List<int> args) : [this.first, this.second] = args;`

**Comment by stereotype441** [comment]
In terms of usefulness, I feel like I could make a good case for patterns in late final fields with an initializer, as a way of caching the output of an expensive computation that produces multiple outputs, e.g.:
```dart
class C {
  late final (int a, String b) = _expensiveComputation();
}
```
Where the intended semantics are, "the first time either `a` or `b` is read, the expensive computation is performed and the result is stored in both `a` and `b`."  A similar argument goes for patterns in final static fields with an initializer, or patterns in final top level variables with an initializer.

But it starts to feel iffy when I try to tease apart the intended semantics in the case where it's `late` but not `final`.  If someone writes to `a` and then reads from `b`, should the expensive computation still be performed?  If so, should `a` be updated to reflect the returned value, or just `b`?  Nothing seems like the obvious "right" answer here.  We could dodge the issue by saying that you can't use a pattern in a non-final field declaration, but that just feels like a weird and unnecessary coupling between the features.

And it would take back-end work to support this sort of thing, so maybe it's not worth it.  After all, the user could always do:
```dart
class C {
  late final (int, String) _x = _expensiveComputation();
  int a => _x.field0;
  Stirng b => _x.field1;
}
```

Maybe that workaround is easy enough that it's not worth the effort to support late final fields with an initializer after all.

**Comment by munificent** [comment]
*Eventually* I could see us supporting patterns in `late` variables, top-level variables, and static fields (which are all similar because all are lazy). The semantics are weird, but I'm sure we can hash out something reasonable. But I think that design work will take some real time and the value is somewhat marginal, so I'd rather focus on a simple core proposal and leave those to a future language extension.

Likewise, I think patterns could be useful for initializing instance fields. But they interact with initializer lists in some ways that will require a decent amount of design effort to untangle, so I think it's best left for later.

Also, extending patterns to these kinds of variables in a later release will give us better data on how users are actually working with patterns and what kinds of need they have for extending them around `late`, fields, etc.

**Comment by lrhn** [comment]
Places that are *eagerly* initialized at the time they are introduced into the scope should be fair game.
That includes parameters and catch clauses.

I'd love to extend extension `on` clauses to be binding, mainly for type patterns, but also for something like `on (int x, int y)` for extensions on patterns. Those variables should probably be final. Even if not, they'll be bound anew on every method entry, so they can be mutable.

Maybe allow naming `this` as `extension on String base { ... base.length... }` which would also work for extension types/extension structs/views where `this` should probably have the view type.

**Comment by munificent** [comment]
> Places that are _eagerly_ initialized at the time they are introduced into the scope should be fair game.

Agreed!

> That includes parameters and catch clauses.

Parameters are hard because we've already jammed so much syntax in there. List patterns collide with optional parameters. Extractor patterns probably collide with function-typed formals. Retconning patterns into a language that wasn't initially designed around them is *really* hard. And Dart has already stuffed a lot of odd bespoke syntax into the parameter list grammar.

Catch `on` clauses are doable, but not particularly high value either.

> I'd love to extend extension `on` clauses to be binding, mainly for type patterns, but also for something like `on (int x, int y)` for extensions on patterns. Those variables should probably be final. Even if not, they'll be bound anew on every method entry, so they can be mutable.

Yeah, type patterns would be very useful there. I'm not sure if other kinds of patterns are really that useful. You can always just access the field directly instead of destructuring in the on clause if you want to define an extension on a record type.

Using list patterns in extension `on` clauses would be problematic. Would it only call the extension if the receiver list had the right number of elements? :-O

**Comment by lrhn** [comment]
> Would it only call the extension if the receiver list had the right number of elements? :-O

Could be potentially surprising, yes. It's really a combination of a pattern defining a type, which is checked statically when resolving extensions, and an irrefutable binding pattern destructuring the runtime value.
That's pretty unique to extension declarations, so maybe we should wait a little with specializing here.

(For structs, where `this` refers to the struct itself, it would be nice to be able to give the matched object a name, like
```dart
struct Foo<T> on List<T> self {
  void method() { self.clear(); }
}
```
Doing other destructuring and binding there as well could be convenient, better than having to destructure `self` as the first thing of every method.)
```

**Comment by munificent** [comment]
OK, I'm going to go ahead and close this because there's no plans to extend patterns to other kinds of variable declarations, at least not in the initial release.

**Comment by nank1ro** [comment]
Are there any updates on the possibility of allowing patterns as late variables?
I would like to do this:
```dart
class _CounterPageState extends State<CounterPage> {
   late final (count, setCount) = createSignal(0);
   ...
}
```

**Comment by munificent** [comment]
No, no plans to support destructuring in `late` variable declarations. We could possibly add this in a future release, but the initial release of patterns in Dart 3.0 won't support this. It's not intractable, but the semantics are pretty unclear and we felt it was best to keep things simple.

**Comment by nank1ro** [comment]
> No, no plans to support destructuring in `late` variable declarations. We could possibly add this in a future release, but the initial release of patterns in Dart 3.0 won't support this. It's not intractable, but the semantics are pretty unclear and we felt it was best to keep things simple.

Hope you're going to add it soon in the next releases, really need this 🙏🏼
