### ISSUE TITLE
Should extension getters defeat field promotion?

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/language#2404]
In the revised plan for field promotion (https://github.com/dart-lang/language/issues/2020#issuecomment-1190546861), we say that:

> ...an instance field is promotable only if (a) it is private, (b) it is final, and (c) all other concrete instance getters with the same name in the same library are also final fields.

When we say "all other concrete instance getters", do we wish to include extension getters?  In other words, what happens here?
```dart
class C {
  final int? _x;
  C(this._x);
}
foo(C c) {
  if (c._x != null) {
    print(c._x + 1); // Has `c._x` been promoted to `int` here?
  }
}
class D {}
extension on D {
  int? get _x => randomBool() ? null : 0;
}
```
There's no soundness problem if we allow promotion here, because extensions are resolved statically, so there's no danger of `c._x` accidentally resolving to the extension getter at runtime.  So we can choose whether or not we want promotion to succeed.

Argument why promotion should succeed: Promotion is useful to the user and there's no soundness problem.
Argument against: users sometimes move code between a class and an extension as part of refactoring.  It might be quite surprising if such a move changed the promotability of other (possibly unrelated) fields in the same file.

I think I lean slightly in the direction that we disallow promotion in this case, but I could be convinced otherwise if anyone feels strongly.

@lrhn @leafpetersen @mit-mit @natebosch @jacob314 @munificent @eernstg

**Comment by eernstg** [comment]
I think we should ignore extension getters: There is no soundness issue, and the rule "all other concrete instance getters with the same name in the same library are also final fields" work fine as it is.

If we wish to have an error based on an extension getter, we'd just replace an already simple rule by another rule which isn't simpler, and we'd gratuitously outlaw some programs. I don't see the benefit.

I'm not so worried about the change-extension-member-to-instance-member scenario: This kind of change could also break some other usages, e.g., name clashes with declarations in subtypes, identities of tear-offs, and the behavior of the method itself (when it uses type variables of the class). So developers would have to be careful around that kind of transformation anyway, and and with respect to the particular case about promotion of `_x` they have the option to rename private names as needed.

(OK, I know the spec uses the phrase 'extension instance getter' rather than just 'extension getter', because it must be possible to distinguish it from an 'extension static getter', but we already use 'instance getter' to denote a declaration in a class or mixin, so we do not implicitly include 'extension instance getters' when we talk about 'instance getters'. So that's also not a reason to include extension getters. ;-)

**Comment by lrhn** [comment]
Agree.

The extension spec uses "extension instance getter" to distinguish it from a *static getter* declared in the extension.
It's a syntactic notion. The resulting getter is just an extension getter. We should probably call it that, and consider out options if we implement #723 and get static extensions.

**Comment by stereotype441** [comment]
Ok, I'm convinced by those arguments.  I'll leave this issue open for a few days in case there are more comments, but I'll proceed with development assuming that extension getters *don't* defeat field promotion.  Thanks!

**Comment by munificent** [comment]
I agree with @eernstg too. Extension getters really are different from instance getters. Users do sometimes refactor from one to the other, but that always requires some level of care (dynamic calls, overriding, etc.)

**Comment by stereotype441** [comment]
Ok, resolved that extension getters will *not* defeat field promotion.
