### ISSUE TITLE
Record types and generic function invocation vs argument list disambiguation

### ISSUE THREAD

**Issue by jensjoha** [dart-lang/language#2407]
The parser generally "parses" types in two goes:
* It computes the type, then (if it decides to actually use it), it
* parses the type.

It can compute the type for the same code many times (but generally only parses it once), and thus the compute part should generally be fast. For instance when computing the type looking at the code `Function(however much code in here)` we will look at the `Function`, we will look at the `(` and then jump to the `endGroup` of `(` (i.e. jump to `)`).

When computing the record type my approach was the same: We see the `(` and we jump to the `)`.
This seems to work fine, except for this test:

```dart
void f(bool b1, bool b2) {
  print('b1=$b1, b2=$b2');
}

g(int x, int y, Object o, Object p) {
  f(x < y, (o as int) > (p as int));
}

main() {
  g(0, 1, 2, 3);
}
```

which currently parses as a function call with 2 parameters, but if computing `(o as int)` as a record type it will instead parse as a function call with 1 argument (and when actually parsing the "record type" it will complain that it's not a valid record type because it's missing a comma and only contains one element).

```
void g(int x, int y, Object o, Object p) async {
  f(x < y, (await o) > (p as int));
}
```

is the same, but here it only complains because the record type only contains one element.

Making it look more at it in the "compute" mode would make parsing slower, introduce more duplicate code in the parser and  probably also have implications on recovery.

Any thoughts on this?

/cc @lrhn @munificent @eernstg @bwilkerson

**Comment by lrhn** [comment]
So currently you can scan through a "potential type" like `x < y, (await o)>`, and when you see the first `(` you know it's not a type (because types can only contain `(` after `Function`).

If you had seen `x< y, await o >`, you would also have balked at the `await`, since it's a reserved word and cannot start a type.

You *don't* skip directly from `<` to `>` because what's inside may not be valid types, and the result *might* be valid even if it's not a valid type.

You'll probably have to treat parenthesized tokens the same way as `<....>` delimited tokens: You need to check if they *can* be types, before accepting them as either.  


So, seeing `f(x<y, (o as int) > (p as int))`, the parser will give up on parsing `<y, ...>` as type arguments when seeing that `o as int` is not valid type syntax.

It can still be valid as both types and non-types, and we'll have to choose then.
If you see `f(x<y, (a, b) > (c, d))`, which can be both a valid two-type-arguments, two arguments invocation of `x` *and* two separate arguments to `f`, one of which is an (extension) operator `>` invocation on a tuple.
(We should probably disambiguate the same way we currently do for `f(x<y,z>(w))`.)
