### ISSUE TITLE
Should variable patterns in switches be treated as "final"?

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/language#2416]
The current [pattern spec](https://github.com/dart-lang/language/blob/master/working/0546-patterns/patterns-feature-specification.md#variables-and-scope) says that:

> The variables a patterns binds depend on what kind of pattern it is:
>
> ...
>
> *   **Variable** or **cast**: May contain type argument patterns. Introduces a variable whose name is the pattern's identifier. The variable is final if the surrounding pattern variable declaration has a `final` modifier.

How should this be interpreted in the circumstance where there is no surrounding pattern variable declaration, because the pattern appears inside a switch statement?  E.g.:

```dart
f(int i) {
  switch(i) {
    case (int j):
      j = 0; // Is this allowed, or is `j` implicitly final?
  }
}
```

Side note: in current Dart (prior to the introduction of pattens), there is a subtle difference between final and non-final variables in how they are affected by type promotion at the type of initialization.  For example:
```dart
f(int i) {
  int? j = i; // `j` is promoted to `int` at the time of initialization
  final int? k = i; // No promotion
}
```

(IIRC, the rationale for this was as follows: In the case of `int? j = i;`, we presume that the user used the explicit type `int?` so that they can assign `null` later in the control flow; so it makes sense to promote `j` to `int` until they do so.  Whereas in the case of `final int? k = i;`, it's impossible for the user to assign `null` later; so presumably the only reason they wanted the explicit type of `int?` was so that in the code that follows, `j` would be treated as an `int?`.  Kinda dubious reasoning, I suppose.  But it's what we implemented and I'm pretty sure that's how we justified it).

Anyway, whatever decision we make about whether variable patterns in switches should be treated as "final", I think the corresponding promotion behavior should be consistent with this decision.  So for example, if we decide that variable patterns in switches are final, then:
```dart
f(int i) {
  switch(i) {
    case (int? j):
      print(j.isEven); // Error: `j` has type `int?`.
  }
}
```
Whereas if we decide that variable patterns in switches are not final, then:
```dart
f(int i) {
  switch(i) {
    case (int? j):
      print(j.isEven); // No error; `j` is promoted to `int`.
      j = null; // No error; this assignment demotes `j` to `int?`.
  }
}
```

**Comment by stereotype441** [comment]
CC @munificent @lrhn @leafpetersen @eernstg @natebosch @jakemac53 @kallentu @mit-mit

**Comment by eernstg** [comment]
For code comprehensibility reasons, I'd prefer to have a bias towards immutability for all variables initialized during pattern matching.

In particular, the "headline" `case (int j):` is very visible, and it seems to promise that `j` is the scrutinee, and I think it's helpful for readers of this kind of code if we can "trust the pattern" to describe the situation at hand:

```dart
f(num n) { // Was `int`, but I don't think that was used to make a point.
  switch(n) {
    case (int j):
      ... // Lots of stuff going on!
      j = 0; // Error!
      ... // More stuff, where we must remember that `j` is just another variable.
  }
}
```

For the related case:

```dart
f(num? n) { // Was `int`, but let's just consider the typical situation where we're type casing.
  switch(n) {
    case (int? j):
      print(j.isEven); // Error: `j` has type `int?`.
      if (j is int) { // But we can certainly still promote `j`.
       print(j.isEven); // OK.
      }
  }
}
```

For completeness, we could try to find syntax to declare the variable mutable. However, it would be a non-breaking change to add new syntax for that in the future, so I'd recommend that we just look into that later, if it turns out to be very useful.

**Comment by munificent** [comment]
The proposal could be clearer about this, but the intent is that variables declared by patterns are *not* final by default and are only final if the variable pattern has `final` or if the pattern occurs inside a pattern variable declaration statement marked `final`.

I prefer immutability too. But Dart doesn't: local variables, function parameters, and even fields and top-level variables all default to mutable unless marked `final`. I might wish that weren't so, but it is. Given that, I think it would cause pain and confusion if variable patterns behaved differently. I think it's better for the language to be consistent, especially because variable patterns are so closely tied syntactically and semantically to variable and parameter declarations.

If we could design Dart from scratch again, I'd have *all* variable bindings default to immutable, but in the absence of that, I think the language works better if it's at least internally consistent. Honestly, defaulting to mutable doesn't seem to cause too many problems for local variables with limited scope in practice, and pattern variables are that.

**Comment by eernstg** [comment]
We do have a bit of prior art: An initializing formal parameter is implicitly final. We decided to do it that way, because it would be highly error-prone and confusing if the parameter itself were modified (and the instance variable would just stay the same).

In more detail, the situation is as follows: `this.x` is associated with the corresponding instance variable (named `x`), but it is also considered to be a formal parameter in the usual sense, that is, it introduces a local variable named `x`. That local variable is implicitly `final`.

```dart
class C {
  int i, j;
  C(this.i): j = ++i; // Error! - can't assign to `i`.
}

void main() {
  print(C(0).i); // If `++i` above hadn't been an error, this would print `0`.
}
```

If it had not been an error then we would have allowed the local variable `i` to be incremented, and the instance variable `i` would still keep the initial value passed as an argument to the constructor, but the local variable `i` would be incremented (and the new value is never used, and can't be found anywhere afterwards).

So the reasoning would be (1) we want immutability in this particular situation (pattern-defined variables) because it's confusing if those variables are modified, and (2) an implicit `final` is not confusing, it stops developers who are just about to do something that they probably shouldn't do anyway.

In particular, I've _never_ encountered any complaints about those initializing formals being final. ;-)

**Comment by munificent** [comment]
Yeah, initializing formals are an interesting edge case. You're right that they're modeled as implicitly-final variables. But I strongly suspect that from the user's perspective, what they think is happening is that they are reading *the field itself* and don't realize that must not be the case since `this` isn't available yet. Making the variable final allows them to maintain that fiction (and not get horribly burned if they think assigning to the parameter actually assigns to the field).
