### ISSUE TITLE
Do names of positional fields of a record type conflict?

### ISSUE THREAD

**Issue by eernstg** [dart-lang/language#2428]
Named fields of a record type are obviously significant, so we must flag name clashes as an error. But when it comes to the names of positional fields we could ignore them completely (they are just comments), or we could insist that they are distinct, from each other and/or from named fields.

```dart
typedef R1 = (int a, int a); // OK?
typedef R2 = (int a, {String a}); // OK?
```

**Comment by eernstg** [comment]
Similarly, is it an error for the name of a positional field to be a member of `Object`?:

```dart
typedef R3 = (int, int toString); // OK?
```

**Comment by lrhn** [comment]
I'd make name clashes an error. Just because we don't use the positional names yet, doesn't mean that we never will.
If we do, it's safer if we don't allow name clashes to begin with, and the cost is ... users not writing a name that is going to be confusing anyway.

I'd allow member-of-`Object` names as named parameters. Those will *not* provide a direct getter, and can only be accessed using record destructuring:
```dart
var silly = (hashCode: 4, toString: () => "Gotcha");
print(silly.toString()); // Calls instance member, gives `(hashCode: 4, toString: [Instance of Function])` (or whatever)
print(silly.hashCode); // Probably not 4.
var (:hashCode, :toString) = silly;
print(hashCode); // 4;
print(toString()); // "Gotcha"
```

That also encourages me to push on the idea that the field getters of records are more like extension members than instance members. Then it's not a problem to coexist with `Object` members, you just can't access them.
(But I guess it'll also just work to say that records don't get a getter at all or `Object`-property-named fields.)

**Comment by eernstg** [comment]
If getters of concrete record types are similar to extension members then we'll have the following:

- The selection of the implementation occurs at compile time, just like extension methods.
- A receiver of type `dynamic` will not be able to invoke them.

If we do the opposite and treat these getters _exactly_ like other instance getters then we have the following:

- The selection of the implementation can occur at compile-time, because concrete record types have no non-bottom subtypes.
- A receiver of type `dynamic` _can_ invoke them.

So we're just taking away features and giving nothing back&mdash;or is there a benefit?

**Comment by munificent** [comment]
I agree that it should be conflict too. In fact, the proposal already mandates this by saying that it's an error if two fields in a record type have the same name without distinguishing positional versus named fields. Added some verbiage to clarify that.
