### ISSUE TITLE
Implementation of `Record` superclass of records.

### ISSUE THREAD

**Issue by lrhn** [dart-lang/language#2442]
We want a `Record` type as a superclass of all record types.
That `Record` type cannot be extended, implemented, mixed-in or instantiated.

We still need to define what it is.
* Is it a class, like `Function`.
* Is it a magical entity like `void` or `Never`.

Inquiring minds want to know (because they're going to implement it).

I propose that we make `Record` a normal class declaration in `dart:core`, like `Function`, and make it *be* a class (unlike `FutureOr`).
We also gate access to the class on the language feature/experiment flag for records, so nobody can access the type, even if we put it into the platform library source prior to releasing the feature.

This way, if we ever want to put static methods on `Record`, we can.
And we can put abstract `==` and `hashCode` members on `Record` and document them.

An alternative is to make it a `struct` instead, when we get structs. If it makes any difference.

WDYT?
@munificent @leafpetersen @eernstg @jakemac53 @natebosch @stereotype441 @chloestefantsova

**Comment by eernstg** [comment]
Sounds good! Can we keep open the option to make it a struct later? It seems appropriate to use this relationship to indicate that the lack of guaranteed identity applies to exactly every object `o` such that `o is Struct`, rather than having two roots for that. Maybe we could have `Record <: Struct <: Object` now, where `Struct` is yet another class with special constraints like `Function`.

**Comment by chloestefantsova** [comment]
I have a related comment. I'm currently workin on a CL that adds the `Record` class into the core library: https://dart-review.googlesource.com/c/sdk/+/257066.

One detail that I want to explain is the static constant `Record.empty` described in the spec: https://github.com/dart-lang/language/blob/master/working/0546-patterns/records-feature-specification.md#record-expressions.

> There is no syntax for a zero-field record expression. Instead, there is a static constant empty on Record that returns the empty record.

Firstly, the spec says there is no syntax for records with no fields, and the `Records.empty` is a way to access such constant. But that means that by definition we can't describe that constant in the source of the core library, so I had to make it `external`.

Secondly, we don't have `external` constants AFAIK, so I had to make it a getter instead of `static const`.

Finally, the `records` experiment isn't enabled by default yet, so we can't compile the core library with the experiment enabled. It means that I can't describe the type of the `Record.empty` getter properly, as `()`. As a way to bootstrap the process, I declared the type as `Record`. It breaks some tests that expect `Record.empty` being assignable to variables of type `()`. We can fix that when we'll enable the experiment.

Please let me know if you have a better idea for bootstrapping `Record.empty`.

**Comment by stereotype441** [comment]
> > There is no syntax for a zero-field record expression. Instead, there is a static constant empty on Record that returns the empty record.
> 
> Firstly, the spec says there is no syntax for records with no fields, and the `Records.empty` is a way to access such constant. But that means that by definition we can't describe that constant in the source of the core library, so I had to make it `external`.

This seems fine to me.

> Secondly, we don't have `external` constants AFAIK, so I had to make it a getter instead of `static const`.

This seems like a problem to me.  I think we want people to be able to refer to `Record.empty` in constant evaluation, e.g. it should be possible to make a const map that has `Record.empty` as a key or value.

Should we consider some kind of hack that just works for `Record.empty`?  Like maybe put this in the SDK:

```dart
class Record {
  static const empty = empty;
}
```

But then maybe the constant evaluator recognizes that `Record.empty` is special, so that rather than report this as a compile-time error it just substitutes in the correct constant?

(Obviously, having full support for `external` constants would be cleaner, but I don't want us to have to go to a bunch of extra work just for this one special constant).

> Finally, the `records` experiment isn't enabled by default yet, so we can't compile the core library with the experiment enabled. It means that I can't describe the type of the `Record.empty` getter properly, as `()`. As a way to bootstrap the process, I declared the type as `Record`. It breaks some tests that expect `Record.empty` being assignable to variables of type `()`. We can fix that when we'll enable the experiment.

This seems a little unfortunate to me too.  We're going to want people to be able to turn on the feature flag for experimentation purposes, and get the same behaviour they will see once the feature is released.

Could we maybe have special case logic in the front end that force-enables the feature when compiling the core library?

**Comment by munificent** [comment]
> Firstly, the spec says there is no syntax for records with no fields, and the `Records.empty` is a way to access such constant. But that means that by definition we can't describe that constant in the source of the core library, so I had to make it `external`.

Ah, that's a good point!

If it helps, we could consider having an empty record literal syntax. I think `()` is *probably unambiguous, but I wouldn't consider it very clear or intuitive. Maybe `(,)`. Ugh, that's not great either. Could we do:

```dart
class Record {
  static const empty = Record._empty() as ();

  external const Record._empty();
}
```

?

**Comment by chloestefantsova** [comment]
Thanks for the feedback, @stereotype441 and @munificent!

> > Secondly, we don't have external constants AFAIK, so I had to make it a getter instead of static const.
> 
> This seems like a problem to me. I think we want people to be able to refer to Record.empty in constant evaluation, e.g. it should be possible to make a const map that has Record.empty as a key or value.

I see how it can be an issue. I think the suggestion by @munificent, with the external const constructor, can be implemented relatively easy.

> This seems a little unfortunate to me too. We're going to want people to be able to turn on the feature flag for experimentation purposes, and get the same behaviour they will see once the feature is released.
>
> Could we maybe have special case logic in the front end that force-enables the feature when compiling the core library?

It seems that we can! The blocker here is that we need to have the support in the backends for the record types and record constants first, so they don't panic when they read the platform files with them inside. I think we can approach it in two steps, like @johnniwinther suggested:

Step 1. Land the empty `Record` class first. The support from the backends is not needed, and we can build some of the Analyzer and the CFE with that.

Step 2. After the backends will start having some minimal support for record types and constants, add the `Record.empty` constant, as suggested above, using the external const constructors.

WDYT?
