### ISSUE TITLE
[Patterns] Refutability and assignability

### ISSUE THREAD

**Issue by leafpetersen** [dart-lang/language#2450]
The patterns proposal says:

> *   **Null-check**, **variable**, **list**, **map**, **record**, or
    **extractor**: Irrefutable if `v` is assignable to the static type of `p`.
    *If `p` is a variable pattern with no type annotation, the type is inferred
    from `v`, so it is never refutable.*

I don't understand why this is specified this way.  It seems to me that in a refutable context, you don't care (these are refutable, I think), and in an irrefutable context they are considered as irrefutable.  Separately, we should then say that it is an error if `v` is not assignable to the type associated with `p`, but that's not about refutability, that's about typing, right?  

Or is there something I'm missing here?  Either way, some explanation would help.

**Comment by munificent** [comment]
I think [this long comment](https://github.com/dart-lang/language/issues/2383#issuecomment-1207033358) has all of the background for this. If you have an intuition for patterns coming from languages without subtyping, it seems strange. But once subtyping gets involved, I believe it makes sense. We want to cover all of these cases:

```dart
Object obj = ...;
List<Object> list = ...;

// 1. OK: List pattern is irrefutable when value is List.
var [a, b] = list;

// 2. Compile-time error: Can't use list pattern when value might not be List.
var [a, b] = obj;

switch (list) {
  // 3. OK:
  case [a, b]: ...
}

switch (obj) {
  // 4. Also OK: Now it *tests* if value is list and matches if it is.
  case [a, b]: ...
}
```

Because of 4, we can't blanket say it's a compile-time error if the matched value type is not assignable to the pattern's type: in refutable contexts, the whole point is to allow that statically and do the type test at runtime.

Because of 1, we can't blanket say that list patterns are refutable. You're allowed to use a list pattern in a declaration when the value is known to be a List.

So what we do is base the refutability of the list pattern on the matched value type. Then the existing error to use a refutable pattern in an irrefutable context also makes 2 an error like we want while allowing 1, 2, and 3.

**Comment by leafpetersen** [comment]
> Because of 4, we can't blanket say it's a compile-time error if the matched value type is not assignable to the pattern's type: in refutable contexts, the whole point is to allow that statically and do the type test at runtime.
> 

This doesn't feel convincing. I wouldn't propose to do so for switches, etc (any more than we treat switches the same as assignment now).  That is:
  - We currently require assignability on assignment
  - We *do not* currently require assignability on a switch

If we just keep doing the same, what goes wrong?
