### ISSUE TITLE
Should null-check `?` patterns be prefix instead of postfix?

### ISSUE THREAD

**Issue by munificent** [dart-lang/language#2452]
The patterns proposal defines a null-check pattern. It has a subpattern followed by a postfix `?`. The pattern matches if the value is not null and then matches the non-nullable result against its inner subpattern. Given:

```dart
class Pet {
  final String name;

  /// Might not have a term of endearment.
  final String? endearment;

  ...
}

Pet getPet() => ...
(Pet?, Pet) getPets() => ...
Pet? tryGetPet() => ...
List<Pet>? tryGetPetList() => ...
```

Here are some examples:

```dart
switch (tryGetPet()) {
  // Simple use in switch case:
  case pet?: print('Got pet $pet');
}

// Simple use in pattern-if:
if (var pet? = tryGetPet()) ...

switch (getPet()) {
  // Explicit field in extractor:
  case Pet(endearment: short?):
    print("Aren't you just the cutest $short?");

  // With field shorthand in extractor:
  case Pet(:endearment?):
    print("Aren't you just the cutest $endearment?");
}

// With interesting subpattern:
if (var [pet1, pet2, pet3]? = tryGetPetList()) ...
```

Swift has a similar feature with similar syntax. It's good in that its terse, which is important since I think it will often be used in cases where you want to copy a nullable value into a non-nullable variable after checking for null.

But the syntax doesn't seem great. Is it better if we make the `?` prefix instead? That would look like:

```dart
switch (tryGetPet()) {
  // Simple use in switch case:
  case ?pet: print('Got pet $pet');
}

// Simple use in pattern-if:
if (var ?pet = tryGetPet()) ...

switch (getPet()) {
  // Explicit field in extractor:
  case Pet(endearment: ?short):
    print("Aren't you just the cutest $short?");

  // With field shorthand in extractor:
  case Pet(:?endearment):
    print("Aren't you just the cutest $endearment?");
}

// With interesting subpattern:
if (var ?[pet1, pet2, pet3] = tryGetPetList()) ...
```

This reads better left to right, since the null check happens before recursing into the subpattern. It also looks less like a nullable type, which could arguably be a good thing.

On the other hand, it's inconsistent with `!` null-assert patters, which are postfix. (And should remain postfix because otherwise they look like negations.)

**Comment by lrhn** [comment]
The prefix `?` works incredibly badly with the `if (?var pet = ...)` syntax. I can see you moved it in to get `if (var ?pet = ...)`, which is an improvement. (That probably won't work if we switch to requiring `var` on every binding variable.)

I think it works fairly well with the alternative/original syntax `if (... case ?var pet)` because value flow goes from left to right, and goes through the `?` first.

That's at the outer level. Inside a nested pattern, it's `var (?x, ? y)` or `(?var x, ?var y)`, or for an extractor `Foo(bar:? var x). That's, I guess, reasonable.

(What if the prefix syntax was `?.`, and `!.` for assertions? `var (?.x, ?.y)`. Nope, looks *too much* like a member access.)

**Comment by munificent** [comment]
> The prefix `?` works incredibly badly with the `if (?var pet = ...)` syntax. I can see you moved it in to get `if (var ?pet = ...)`, which is an improvement.

I didn't move it in, this is the syntax you would get with a prefix `?` according to the current proposal. The `if (var` is all part of the pattern-if statement form, and the pattern starts after `var`.

**Comment by lrhn** [comment]
Having worked more with the grammar, I think `?` at the end is quite possibly the least bad way to do it.

It fits with the `!` and `as type` coercions, and if we use `if (expr case pattern)` instead of `if (pattern = expr)`, then the position is fine.
(There is an ambiguity in `p as int?` since it can be `(p as int?)` or a cast to `int?`. Those modifiers probably don't need to nest, and if we don't allow them to do so directly, you'll have to use parentheses to get `(p as int)?`.)

**Comment by munificent** [comment]
I agree. I don't love it there, but I like it there better than anything else we've tried.
