### ISSUE TITLE
[Patterns] Do relational patterns do a downcast?

### ISSUE THREAD

**Issue by leafpetersen** [dart-lang/language#2461]
The dynamic semantics of relational patterns in the pattern proposal says:

```
Relational:

Evaluate the right-hand constant expression to c.

A == c pattern matches if v == c evaluates to true. This takes into account the built-in semantics that null is only equal to null.

A != c pattern matches if v == e evaluates to false. This takes into account the built-in semantics that null is not equal to anything but null.

For any other operator, the pattern matches if calling the operator method of the same name on the matched value, with c as the argument returns true.
```

I believe that this implies that if calling the method in a relational pattern returns a non-boolean (which can happen, I think, if the return type is `dynamic`), then it is simply a failed match (rather than a runtime error).  Is this the intended semantics?  This is not consistent with how conditionals currently behave, just as a point of comparison.

```dart
class A {
  dynamic operator <(int other) => "hello";
}

void main() {
  A a = A();
  if (a < 3) {} // Throws a runtime cast error
  switch (a) {
    case < 3: print("hello"; // Does this throw a cast error, or just fail to match this case?
    default: print("world");
  
}
```

**Comment by lrhn** [comment]
I'd make it a run-time error if `<` or its siblings return a non-`bool` value.

It's a compile-time error if the static return type of a relational pattern operator is not assignable to `bool`.
It's a run-time error if the value is not a `bool`, which can only happen if the static type was `dynamic`, or if we have unsafe null-safety (which we will/won't at the time patterns are released?)
The run-time error happens when the comparison is evaluated for truth, as if it was a normal implicit downcast from `dynamic`. The `< 3` here is evaluated as if it was `($scrutinee < 3) as bool`.
