### ISSUE TITLE
Promoting methodd

### ISSUE THREAD

**Issue by cedvdb** [dart-lang/language#2463]
I'm interested in having the following compile, only the second `if` is promoting currently:

```

void main() async {

}

void doSomething(TaskStatus status) {
  if (status.isCompleted()) {
    print(status.output);
  }

  // vs 
  if (status is TaskCompleted) {
    print(status.output);
  }
}



abstract class TaskStatus {
  
  bool isCompleted() => this is TaskCompleted;
  // does not work either
  static bool isCompleted2(TaskStatus status) =>  status is TaskCompleted;
}

class TaskLoading extends TaskStatus {}

class TaskCompleted extends TaskStatus {
  final int output;
  TaskCompleted(this.output);
}

```

Use cases:

- The main use case is discovery, it's easier to find the different status above if there was a promoting method on the base class
- Another use case is name collision
- It is kind of a way around null safety in most cases, without null safety, there wouldn't need to be different state implementation of the class.

**Comment by lrhn** [comment]
That's working as intended. Calling an interface method like `isCompleted` cannot depend on the particular implementation of that interface method. The compiler doesn't know, in general, whether someone, somewhere, overrides `isCompleted` to do something else. (It can know if it sees the entire program, but that precludes doing modular compilation.)

That means that `status.isCompleted()` is known to return a `bool`, but that's *all* the caller knows. It cannot derive any other conclusions from that value being `true` or `false` because the interface doesn't, and cannot, say what the values mean.

What I'd do is 
```dart
TaskCompleted? asCompleted(TaskStatus status) => status is TaskCompleted ? status : null;
```
and then:
```dart
  var completed = asCompleted();
  if (completed != null) { 
    print(completed.output);
  }
```
This reduces the type check + type promotion to something you only need a nullability check for.

**Comment by mateusfccp** [comment]
I think a possible solution to this is #2253. Being able to define that a method promotes a type at language-level. Don't know how feasible this is, however.

**Comment by cedvdb** [comment]
> That's working as intended. Calling an interface method like `isCompleted` cannot depend on the particular implementation of that interface method. The compiler doesn't know, in general, whether someone, somewhere, overrides `isCompleted` to do something else.

Right, but what about the static version though ? It does not solve my issue but I was surprised it did not work either
