### ISSUE TITLE
Support for `MapEntry` literals inside `List` and `Set` literals

### ISSUE THREAD

**Issue by rasitayaz** [dart-lang/language#2468]
To explain it simply with an example, the idea is to take the following code,
```dart
Set<dynamic> dynamicSet = {
  'string',
  5,
  const MapEntry('k', 'v'),
};
```

and simplify it as follows,
```dart
Set<dynamic> dynamicSet = {
  'string',
  5,
  'k': 'v',
};
```

This could provide simplicity for structures combined with lists, sets and maps.

For example, a prototype object like following can be defined with this feature:
```dart
final userPrototype = {
  'name',
  'age',
  'company': {
    'title',
    'website',
    'country': {
      'code',
      'name',
    },
  },
};
```

**Comment by lrhn** [comment]
Dart is a typed language. What you have here is completely untypable. Helping you write untypable code is not a goal.

It's also unparsable, since we decide whether something is a set or map depending on whether it has keys or not.
```dart
var v1 = {'a', 'b': 'c'} //  set with a map entry element?
var v2 = {'b': 'c'}; // a map?
```
So, that idea won't fly.

I'd wait for records and write it as:
```dart
final userPrototyper = {
  'name',
  'age',
  (company, {
    'title',
    'website',
    ('country', {
      'code',
      'name'
    })})};
```
That's no more or less useful than what you have, but it's shorter. The `MapEntry` class isn't special in any way, it's not intended to be generally useful for anything except describing entries in maps.
