### ISSUE TITLE
Adding a {k,v} pair to the first map in a list of empty maps, adds the pair to every single map in the list

### ISSUE THREAD

**Issue by Xyrtur** [dart-lang/language#2472]
Steps:

1. Create a non-growable list of empty maps
2. Add a {k,v} pair to the first map in the list
Expected:  `[{3: aaaaa}, {}, {}, {}]`
Actual: `[{3: aaaaa}, {3: aaaaa}, {3: aaaaa}, {3: aaaaa}]`

Code:
`var orderLines = List.filled(4,<int, String>{}); // creates an empty List<Map>`
`orderLines[0][3] = "aaaaa";`  
`print(orderLines);`

Console:
`[{3: aaaaa}, {3: aaaaa}, {3: aaaaa}, {3: aaaaa}]`

I found this while using Dart 2.18 and 2.19. I don't think it should work this way but if it should, please explain how this works.

**Comment by Jetz72** [comment]
That's creating a list where all four entries are the same instance of your empty map. What you want is to create a new map for each index of the map. For that, use [`List.generate`](https://api.dart.dev/stable/2.18.0/dart-core/List/List.generate.html), with a function that generates each item individually instead of a single object that gets inserted into every index:

```dart
var orderLines = List.generate(4, (index) => <int, String>{});
orderLines[0][3] = "aaaaa";
print(orderLines);
```

**Comment by Xyrtur** [comment]
Understood! Thank you so much for such a quick and helpful response
