### ISSUE TITLE
`factory` with return type

### ISSUE THREAD

**Issue by FMorschel** [dart-lang/language#2480]
As mentioned [here](https://github.com/dart-lang/language/issues/782#issuecomment-575547881) and the issue mentioned on #782 by @lrhn as well, would also solve #23115:

> There is also the option of allowing you to write return types on constructors.
> 
> If that is allowed, then it might also be possible to write a `Future<X>` return type which makes it very clear that the constructor does not return an `X`.

I would like to point out that if this feature is allowed, a new constructor concept could be a `List<X>` or even `Future<List<X>>`. This would be more clear than `static Future<List<X>> Function(...)` for server requests or even DB requests.

PS: I'm not sure if this should be said here or on #782, so any suggestion will be taken.

**Comment by lrhn** [comment]
The counter-argument is that you don't *need* it to be a constructor, it can just be a static method. 
The only case where you really need a constructor is where you create a single new instance of the class, which means calling a non-redirecting generative constructor. 
The async constructor can match that, it's like any other generative constructor except that it can contain `await` operators in the initializer list.

For creating a list of things, you need to invoke a constructor more than once anyway, and return something which doesn't implement the constructed type. It'll be a factory constructor if it is a constructor, and then it might as well be a static factory method.

The one difference is where the type argument goes, is it
```dart
  List<T> foos = Foo.createList<T>();
```
or
```dart
  List<T> foos = Foo<T>.createList();
```
The latter does read a little better, but we can solve that by allowing static *methods* (not getters/setters/fields) to access the type parameter of the surrounding class, and let you invoke them as `TheClass<X, Y>.staticMethod()`.
With that, constructors lose one more of the things that made them special, which is good, because we're making everyone special! (And we can allow constructors type parameters too, so everyone can do `Foo<X>.sloop<Y>()`, whether constructor or not.)

(In fact, with that, non-redirecting factory constructors no longer need to exist, it's just a way to get an implicit return type of `OuterClass<X,Y,Z>` without writing it. Only the generative constructors are special, and only because you need to call them from subclasses.)
