### ISSUE TITLE
Allow both "final" and a type in pattern variables

### ISSUE THREAD

**Issue by munificent** [dart-lang/language#2486]
Elsewhere in the language, in variable declarations you can specify both `final` and a type annotation if you want the variable to have a specific type and not be mutable. The patterns proposal currently treats `final` and the type annotation is mutually exclusive. I don't think there's any strong reason for that and we should probably allow:

```dart
if (foo case final int x) ...
```

**Comment by lrhn** [comment]
That should just be allowed. It's an oversight that I haven't noticed it.

It should be something like:
```abnf
variablePattern ::= 
     'var' identifier
   | 'final' identifier
   | 'final'? type identifier
   | ...
```
(I made it `'final'? type identifier` instead of `'final' type? identifier` because the type is what makes it refutable, so this way there is one production which is always refutable, and the others are always irrefutable.)
