### ISSUE TITLE
Why does Dart change my original object sometimes?

### ISSUE THREAD

**Issue by bhanuka96** [dart-lang/language#2499]
I created two objects called `myStuff1` and `myStuff2`. Inside `doStuff1` function, created another new object and assign `myStuff1` value to the newly created object and modified the newly created object. But the Original value is also changed when I print my original object (myStuff1) value. How is this work?

And I did the same thing to the `myStuff2` object. But this time original value is not changed. Why is that?

I am very confusing this. I want to learn about this. Please tell me why and how does this work?

**Full Code**

```
void main() {
  Thing myStuff1 = Thing();
  
  myStuff1.stuff = 'start';
  
  ThingWrap wrapper = ThingWrap();
  
  wrapper.thing = myStuff1;
  
  doStuff1(wrapper);
  
  print(wrapper.thing.stuff);
  
  Thing myStuff2 = Thing();
  
  print(myStuff2.stuff);
}

void doStuff1(ThingWrap theStuff) {
 ThingWrap _theStuff = theStuff;
 var newStuff = Thing();
 newStuff.stuff = 'test';
  
  _theStuff.thing = newStuff;
}


void doStuff2(Thing thing) {
 var newStuff = thing;
 newStuff.stuff = 'test2';
}

class Thing {
 String stuff = 'empty';
}

class ThingWrap {
  Thing thing = Thing();
}
```

**Comment by Levi-Lesches** [comment]
In the future, please try to use more descriptive variable names, like `value` and `wrapper` instead of `things` and `stuff`. I redid your `doStuff1` using clearer names so I'll go through it line by line: 
```dart
class Data { String value = "empty"; }
class Wrapper { Data data = Data(); }

void test1(Wrapper wrapper) {
  Wrapper newWrapper = wrapper;
  Data newData = Data();
  newData.value = "test";
  newWrapper.data = newData;
}
```
> ```dart
>  Wrapper newWrapper = wrapper;
> ```
Here you're creating a new variable `newWrapper` that still refers to the old variable, `wrapper`. So `newWrapper` and `wrapper` are just two different names for the same object. Keep that in mind.

> ```dart
> Data newData = Data();
> newData.value = "test";
> ```
Here we create a new instance of `Data` and assign `newData.value = "test"`. This is actually a new object, not referring to any existing object. 

> ```dart
>  newWrapper.data = newData;
> ```
Now you're assigning `newWrapper.data` to `newData`. Remember that `newWrapper` is just another name for the same object stored in `wrapper`, so this modification applies to the original object as well. 

`doStuff2` would have the same effect... but you don't call it from `main` and so it never runs. 

----

Also, this issue tracker is for issues with Dart as a language (as in, a bug report or feature request). If you want help from others with learning or understanding Dart, check out the links at https://dart.dev/community.

**Comment by lrhn** [comment]
As described, Dart variables contain object references, and two variables can point to the same object. Changing the object through either reference will still change the same single object.
