### ISSUE TITLE
Scoping of cases that share a body is still weird

### ISSUE THREAD

**Issue by munificent** [dart-lang/language#2553]
I recently [landed a change](https://github.com/dart-lang/language/commit/05e110b3b80d9a9f9b9b1e05165eb86a993cbc45) that tries to clarify how scoping works around patterns and also loosens some restrictions on variables declared in switch case patterns that share a body.

Previously, this was an error:

```dart
switch (obj) {
  case [int i] when i > 0:
  case [String s] when s.isNotEmpty:
    print('matched');
}
```

The old rules were that since those two cases share a body but don't define the exact same set of variables, it's an error. But there's nothing actually problematic about this example because the variables each case declares are only used in their respective guards and not in the body.

The latest update allows this. Basically, it says that when a set of cases share a body, *only the variables used in the body* must be declared by every case and have the same type. That allows the above example, and also this:

```dart
switch (obj) {
  case [int sameName] when sameName > 0:
  case [String sameName] when sameName.isNotEmpty:
    print('matched');
}
```

Both cases declare a variable named `sameName`, but whose type is different in each case. That's fine because the variable isn't used in the body, so the inconsistency doesn't matter.

However, actually specifying this in a coherent way gets pretty complex, especially when you consider that guard expressions can *capture variables in closures*. Consider this gnarly example:

```dart
final callbacks = <Function()>[];

bool capture2(void Function() callback, bool result) {
  callbacks.add(callback);
  return result;
}

switch(['']) {
  case [var s] when capture(() => s += 'guard1', false):
  case [var s] when capture(() => s += 'guard2', true):
    callbacks[0]();
    callbacks[1]();
    print(s);
}
```

Does this print "", "guard2", or "guard1guard2"? The proposal currently says "guard2". This means that *at runtime*, the body runs in a scope where the enclosing scope is *only* the one case that matched. In theory, if "go to definition" was a meaningful thing at runtime, then go to definition on the `s` in `print(s)` would take you to the `var s` in the second case. There is only one `s` and it's only defined by one case.

But that gets very confusing for static analysis, which doesn't know which case will match and must analyze the body in the context of all of the cases. The proposal tries to handle that by analyzing the body in a scope that is the conservative intersection of only the things that are true coming from all cases.

It's *sort of* as if the code sees the above example like:

```dart
String s;
switch(['']) {
  case [s] when capture(() => s += 'guard1', false):
  case [s] when capture(() => s += 'guard2', true):
    callbacks[0]();
    callbacks[1]();
    print(s);
}
```

Statically, there is a single scope where all of the variables shared across the pattern are declared. And then each case just initializes that one variable. But the runtime semantics don't follow that because this would imply that the program prints "guard1guard2".

The core weirdness is that statically, a variable used in the body appears to have *multiple declarations*. But at runtime, it only has one. Having a variable in a body that can statically resolve to multiple possible declarations is a very weird concept for our implementations. The analyzer assumes every variable reference resolves to a single Element, and CFE assumes every variable reference resolves to a single variable declaration AST node.

Implementing flow analysis and type promotion correctly for this is likely possible, but probably a lot of work since it breaks the assumption that every variable is declared at one point.

### Hoisting only shared variables

One option would be to say that when a set of cases share a body, whenever multiple cases declare a variable with the same name, you get *one* variable shared across all of the cases.

In other words, we decide that, yes, the above program prints "guard1guard2". I think this is a *little* surprising because syntactically the two cases do look like they're declaring separate variables. But the distinction is only visible when a guard captures the variable in a closure and that will likely be extremely rare.

The other problem with this model is code like the `sameName` example:

```dart
switch (obj) {
  case [int sameName] when sameName > 0:
  case [String sameName] when sameName.isNotEmpty:
    print('matched');
}
```

The current proposal allows this. If we hoist all variables declared by a set of shared cases up, how do we create a single declaration that represents `sameName`? What is its type?

We could say that we *only* hoist variables that are used in the case body. So if a variable is only mentioned in the guard expression, it gets declared right in its one case pattern and can have its own type independent of other cases.

But that leads to a chicken-and-end problem: We don't know which variables are used in the body until we analyze and resolve it. But we can't analyze it until we've defined the enclosing scopes. And we don't know which variables go into the hoisted shared scope and which are per case until we know which ones the body uses.

This is conceptually tractable. We could just do what the proposal says and eagerly synthesize a scope that contains the union of all variables in all cases and marks the ones with conflicting types as unusable. Then we analyze the body in that scope.

But then we would have to go *back* and re-resolve all of the guard expressions. Because whether or not a variable gets hoisted and shared across cases is user-visible when closures capture variables in guards. Currently, our implementations only do a single analysis pass over the code, and it would be a lot of work to have to do multiple passes.

### Hoisting all variables

A simpler solution is to say that *all* variables declared by a set of cases sharing a body get hoisted. We treat them as all being declared above the first case (or perhaps the first case where a variable with that name appears). Then in each case, we treat the variable pattern as *initializing* the variable and making it available for use. This lets you read every variable a case pattern declares in its own guard clause.

The case body is treated as a join point for flow analysis and definite assignment analysis. A variable is only usable in the body if *all* cases match that variable and mark it initialized. The desired behavior that you can only use a variable in the body if all cases define it falls out naturally from definite assignment analysis.

There are two problems, one minor and one less minor. The minor one: It may be surprising that the above example prints "guard1guard2" because it syntactically looks like two unrelated variable declarations. I think almost no users will ever observe this and if they do, we can explain it.

The larger problem is determining what type the hoisted variable should have. In the `sameName` example, the two patterns declare it with different types. To merge that to a single hoisted declaration, we need a single type. We could try something like `Object?` and then treat each pattern as *promoting* the variable to its matched type, but I think that feels pretty weird. The difference between a declared type and promoted type is user visible. I think it would be surprising, for example, if you could do:

```dart
switch (obj) {
  case [int sameName] when sameName > 0:
  case [String sameName] when sameName.isNotEmpty:
    // Assign a bool, allowed since declared type is Object?:
    sameName = true;
}
```

The only other option I can think of is that when multiple cases declare a variable with the same name, it *must* have the same type in all cases *even if the variable is never used in the body*.

That's a restriction from the current proposal, and could be annoying in examples like:

```dart
switch (obj) {
  case SomeClass(:int someProp) when someProp > 1:
  case OtherClass(:String someProp) when someProp.isNotEmpty:
    print('Not using someProp here.');
}
```

You wouldn't be able to use the field shorthand and instead have to do:

```dart
switch (obj) {
  case SomeClass(someProp: int intProp) when intProp > 1:
  case OtherClass(someProp: String stringProp) when someProp.isNotEmpty:
    print('Not using someProp here.');
}
```

It feels like the previous example should just work, but the language won't let you.

I think I'm OK with that restriction because a simpler model around flow analysis is generally a good thing for users too. There's maybe an argument that if you have cases sharing a body, you really *shouldn't* have variables with the same name with different types just because it's kind of confusing to read.

Thoughts?

**Comment by munificent** [comment]
> Not sure if this is helpful, but another way of thinking about this (and one that I find fairly appealing) is more like the following:
> 
> ```dart
>  void body(String s) { 
>      callbacks[0]();
>      callbacks[1]();
>      print(s);
> }
>  switch(['']) {
>    case [String s] when capture(() => s += 'guard1', false): body(s);
>    case [String s] when capture(() => s += 'guard2', true): body(s);
>  }
> ```
> 
> The semantics then would be to print the empty string. This is analogous to the Dart treatment of for loop variables, which allocate a "fresh" variable for every iteration. Here, we essentially are saying we allocate a "fresh" variable for the case body.

Ah, yes, good idea. We talked about that briefly too but I forgot to mention it here.

> It may be surprising that side effects on captured variables don't show up in the body, but honestly, anything we do here is going to be surprising, I think. I actually wonder whether we should just say that it's an error to assign to a pattern variable in the guard?

That's not a bad idea. Essentially the variables declared in the pattern are always implicitly final (and those are the variables that the guard sees). Then when you enter a body, those values get copied to new variables that might be final or not based on the variable is specified in the pattern.

> > A simpler solution is to say that _all_ variables declared by a set of cases sharing a body get hoisted. We treat them as all being declared above the first case (or perhaps the first case where a variable with that name appears).
> 
> I don't really understand how this solves the issue you started with, which is that the CFE and the analyzer want to have a single location to treat as the canonical declaration. Semantically, you may have a single location, but you still have two declaration sites, and go to declaration still has to choose one. So I feel like I'm maybe missing something? But I wonder whether my suggestion above might not give a cleaner model?

It's less about how go to declaration behaves (which will always be a little arbitrary inside the body) and more about the underlying implementation. In the current implementation as I understand it, flow analysis assumes there is a single variable declaration that flows the analysis. If we tried to say that each guard sees a unique variable per case, but the body sees some magical unification of those, then figuring out how to implement that unifying gets weird.

> > The desired behavior that you can only use a variable in the body if all cases define it falls out naturally from definite assignment analysis.
> 
> As usual, I would caution against relying on this, since without specifying something extra, definite assignment would allow me to assign to the variable. I don't think you want the following to be legal:
> 
> ```dart
>   switch ([true]) {
>      case _ when b = false:
>      case [bool b]:
>           print(b);
>    }
> ```

Haha, good point! I like your suggested modeling and restriction. Really, if you're assigning to a pattern variable in a guard, you are already bringing confusion upon yourself. Let's see what @stereotype441 thinks.

**Comment by lrhn** [comment]
(I wrote this and went away before finishing it up, then Leaf wrote what I think is the same thing. So, I'll post it anyway, just take it as a concurring opinion.)

> One option would be to say that when a set of cases share a body, whenever multiple cases declare a variable with the same name, you get one variable shared across all of the cases.

Cannot possibly work for `final` variables.
Each `when` clause must see the values of variables bound by its pattern. If those variables are final, the same variable cannot assume two different values, like:
```dart
T seq<T>(void _, T value) => value;
switch (("a", "b")) {
  case (final s, "b") when seq(print(s), false): 
  case ("a", final s) when seq(print(s), true): 
    print(s);
}
```
Even without capturing any variable, the final `s` variables have already been seen with two different values, so they cannot possibly be the same variable.

> A simpler solution is to say that all variables declared by a set of cases sharing a body get hoisted. 

Same issue.

There really *has* to be two different final variables, one visible to each `when` clause.

So, alternative:

## Introduce multiple variables
We say that the variables visible in the `when` clauses are not the same variables that are visible in the body.
One declaration, two different variables.

We introduce one scope per `when` clause and one scope for the body, each defining a variable at most once.
The matched values are then bound to both the variables when applicable.

I'd even make the variable in the `when` clause always be final (like the synthetic variable of a `this.x` initializing formal in the initializer list). That'll stop a lot of shenanigans which complicate our life as compiler writes, but doesn't actually help any reasonable programmer.

So, for a case-head pattern, *every* identifier declaration in the pattern introduces a *final* variable in the `when` clause, bound to the matched value.

For one or more cases with the same body, every identifier declared in any pattern introduces a variable in the body scope.
If the pattern declarations do not have the same ontology, finality and type in *every* case (with labels and `default:` having no declarations), the variable is conflicted, and any reference to it is an error (like we do for import conflicts).
Otherwise the variable in the body scope has that type and finality, and is bound to the matched value of whichever pattern actually matched.

This way, a successful case pattern match only needs to provide the values for the shared variables, a set which is statically known after inferring types for the cases, but before looking at the body. That vector of values, identical for every participating case, is then used to initialize the new variables introduced in the body.

**Comment by stereotype441** [comment]
Well, shoot.  I was really hoping that for an example like:

```dart
switch (e) {
  case (int x, int y) where x > y:
  case (int y, int x):
    print('the larger one is $x');
}
```

we could treat it as though all the `x`s refer to the same variable.  Because that's how I've been thinking of it and how I would want to desugar it:

```dart
if (e is (int, int)) {
  int x = e.$0;
  int y = e.$1;
  if (x <= y) {
    y = e.$0;
    x = e.$1;
  }
  print('the larger one is $x');
}
```

But @lrhn's point about `final` has convinced me that this approach just won't generalize.  We need the invariant that every read from a final variable returns the same value, not just because that's what the user expects, but also because flow analysis relies on that for soundness*.

(*Technically, all flow analysis cares about is whether the variable is written to after its declaration, but the effect on this issue is the same.  We don't want flow analysis treating a variable as "written to after its declaration" just because it appears in multiple case heads that share a body, and consequently disabling some promotions).

So where does that leave us?

I definitely want the set of variable bindings, and their scopes, to be consistent regardless of whether the variables are final or not, and regardless of whether there are guard clauses or not.  So I have to plan for the worst case.  That means final variables with guard clauses.  For example:

```dart
switch (e) {
  case (final int x, final int y) where x > y: // (1)
  case (final int y, final int x) where x > y: // (2)
    print(x); // (3)
}
```

To satisfy the invariant, the final `x` on line (1) *can't* refer to the same variable as the final `x` on line (2) (because in the case where `e.$0 < e.$1`, both of those `x`s are seen by the user's program and have different values).  By similar reasoning, the `x` on line (3) *can't* refer to the same variable as the final `x` on line (1).  I guess it *could* refer to the same variable as the final `x` on line (2), but that seems like madness.  So I think the approach @lrhn outlined under the heading "Introduce multiple variables" is our only reasonable option.  In other words, each case head declares a fresh set of variables, and then there's a separate set of synthetic variables implicitly declared at the "join point" at the top of the case body.

I like the idea that the variables that are in scope in the `when` clauses are all implicitly `final`.  It prevents most of the shenanigans that we are fussing over in this issue, and I can't think of any use real-world use cases that it gets in the way of.

And I like the fact that it allows the same variable name to have different types in different case heads as long as you don't use it in the body.  That's a nice feature.

For consistency, I think we should create these extra synthetic variables in switch expressions and if-case as well.  So for example:
```dart
late void Function() later;
bool defer(void Function() callback) {
  later = callback;
  return true;
}
print(switch (e) {
  case int x where (defer(() { print(x); })) => x++ }); // prints `0`
later(); // prints `0`, because the `x` that was captured is different from the `x` that was incremented.
```

I'm sad about all this because I suspect it means extra implementation work.  The analyzer and CFE now have to have a notion of synthetic local variables that get declared at the join point (or after the `when` clause for switch expressions and if-case).  Flow analysis needs to have hooks to allow the analyzer and CFE to tell it about the relationship between all these variables.  And the analyzer (or maybe the analysis server) probably needs extra logic to link those variables together to make rename refactorings work the way the user expects.  But I don't really see any other way.

So I guess what I'm saying is, LGTM to @lrhn's "Introduce multiple variables" suggestion, and an apology in advance to @scheglov and @chloestefantsova for the extra implementation work it requires of them 😄.

**Comment by scheglov** [comment]
I also like "Introduce multiple variables" proposal, with implicit finality, and join points. I don't anticipate issues in the analyzer with creating a new synthetic join element that will track on which elements for variable patterns it is based.

One doubt that I have is about requiring that variable elements in each case should have the same type. Why not LUB? This might cause breakages when we have an extractor pattern in a multi-case body, and this getter changes to a more specific type, and then this body has an error.

**Comment by lrhn** [comment]
Just saying, Leaf posted the idea first! :)

It does mean that two different variables refer to the same declaration, which I guess still beats one variable coming from two different declarations.

We have another case of different variable scopes flowing into the same body, in C-style `for` loops where we introduce new variables for each loop iteration. At least one of the variables is entirely synthetic, so we can always point to the non-synthetic declaration in error messages. You could say that the same declaration is used to declare multiple variables, like we'd do here, but then those different variables still merge together into the same body.
(Is that also an implementation issue - or is it only a real problem if someone actually captures the variable in the increment or test expressions? Would we'd want to redesign it, to something simpler? I know I can't remember how it actually works right now.)

**Comment by lrhn** [comment]
One more thing to consider is *promoted* type of matched variables.
```dart
switch (object as Object) {
  case var x when x is int && x > 5:
  case var x when x is int && x < 3:
    // Is x promoted to `int` here? I hope so.
```
Here the result of each match is that the declared type of `var x` is `Object`, and the promoted type of `x` is `int` at the end of *every* successful `when` clause. **It would be nice** if we could make the type of the `Object x` variable in the body be pre-promoted to `int` as well.

If it's not the same variable across `when` and body, we probably need to do something extra to propagate the promotion information, say capture the promoted type of every shared variable (every variable, until we know which ones are shared), and possibly every type-of-interest as well, and apply them to the join-point and variable initialization. Then the implicit `Object x = (matched value known to be int);` would promote `x` to `int` immediately, because `int` is a type of interest in at least one case.
In effect, the *values* going into the body declarations are not taken directly from the match, but take from the corresponding `when`-clause variable's state at then end of the `true` branch of the boolean expression. (When that variable is final, things just get easier.)

It's probably not *that* easy.

**Comment by stereotype441** [comment]
> One more thing to consider is _promoted_ type of matched variables.
> 
> ```dart
> switch (object as Object) {
>   case var x when x is int && x > 5:
>   case var x when x is int && x < 3:
>     // Is x promoted to `int` here? I hope so.
> ```
> 
> Here the result of each match is that the declared type of `var x` is `Object`, and the promoted type of `x` is `int` at the end of _every_ successful `when` clause. **It would be nice** if we could make the type of the `Object x` variable in the body be pre-promoted to `int` as well.

Agreed.  Flow analysis is not fully specified, so we might need to be a little loose in how we specify this because we just don't have the terminology in the spec to reflect all the things flow analysis tracks.  I don't think it will be too difficult, but there are a lot of i's to be dotted and t's to be crossed.  For the record, flow analysis currently tracks, for each variable:
- a possibly empty list of increasingly specific promoted types,
- an unordered list of "types of interest" that the variable's type has been tested against but not necessarily promoted to,
- a boolean indicating whether the variable is definitely assigned,
- a boolean indicating whether the variable is definitely unassigned,
- an "SSA node" capturing information about the value of the variable (this allows the result of an `is` or `== null` check to be stored in a variable and then used for promotion in an `if` statement at a later time),
- conceptually, a boolean indicating whether the variable has been write captured (this is actually implemented by using `null` for the "SSA node", but spec-wise it makes sense to think of it as a separate boolean),
- a list of promotions the user has attempted, which have been rejected by flow analysis, so that we can produce better diagnostics (probably we don't need to spec this),
- and a set of similar information about the variable's fields (for field promotion).

We will want to carry nearly all of this information from the variables in the individual case heads to the variables in the case body.

Fun times 😃

**Comment by munificent** [comment]
> So I think the approach @lrhn outlined under the heading "Introduce multiple variables" is our only reasonable option. In other words, each case head declares a fresh set of variables, and then there's a separate set of synthetic variables implicitly declared at the "join point" at the top of the case body.

I agree. I've beat my head against this for a while but no inspiration has struck, so I think this is probably the best we can do.

> I like the idea that the variables that are in scope in the `when` clauses are all implicitly `final`. It prevents most of the shenanigans that we are fussing over in this issue, and I can't think of any use real-world use cases that it gets in the way of.

This seems reasonable to me too.

> And I like the fact that it allows the same variable name to have different types in different case heads as long as you don't use it in the body. That's a nice feature.

Yes, this one is, I think, practically useful.

> For consistency, I think we should create these extra synthetic variables in switch expressions and if-case as well. So for example:
> 
> ```dart
> late void Function() later;
> bool defer(void Function() callback) {
>   later = callback;
>   return true;
> }
> print(switch (e) {
>   case int x when (defer(() { print(x); })) => x++ }); // prints `0`
> later(); // prints `0`, because the `x` that was captured is different from the `x` that was incremented.
> ```

I'm not sure about this. While it will be rare for users to get tripped up by this, I think it's pretty surprising that you get a new `x` here even though there's no *reason* for it aside from consistency. Intuitively this code looks like there's a single variable `x` and there is no problem modeling it that way either. It's *only* when you have multiple cases sharing a body that you need all of the copy-to-a-new-variable shenanigans.

Is it a crazy idea to disallow *closing over* pattern variables in a guard clause? If you can't assign to it and you can't even wrap it in a closure, then it should be completely user-invisible whether or not the variable gets copied to a new one, right?

> One doubt that I have is about requiring that variable elements in each case should have the same type. Why not LUB? 

I hint at that in this example:

```dart
switch (obj) {
  case [int sameName] when sameName > 0:
  case [String sameName] when sameName.isNotEmpty:
    // Assign a bool, allowed since declared type is Object?:
    sameName = true;
}
```

If we took the LUB, then it would allow, I think, pretty surprising assignments. I can't imagine much practical good coming out of this flexibility.

> This might cause breakages when we have an extractor pattern in a multi-case body, and this getter changes to a more specific type, and then this body has an error.

Ah, that's a good insight. You're right that it makes some code more brittle. However, I think that problem already exists elsewhere in the language:

```dart
var x = Foo().bar;
x = Baz().bar;
```

If the type of the `Foo.bar` getter is changed to a more precise type, this will break the later assignment. While in theory it should be non-breaking to tighten a return type, in practice because of type inference, tear-offs, etc., it technically can still break things.

**Comment by stereotype441** [comment]
> > For consistency, I think we should create these extra synthetic variables in switch expressions and if-case as well. So for example:
> > ```dart
> > late void Function() later;
> > bool defer(void Function() callback) {
> >   later = callback;
> >   return true;
> > }
> > print(switch (e) {
> >   case int x when (defer(() { print(x); })) => x++ }); // prints `0`
> > later(); // prints `0`, because the `x` that was captured is different from the `x` that was incremented.
> > ```
> 
> I'm not sure about this. While it will be rare for users to get tripped up by this, I think it's pretty surprising that you get a new `x` here even though there's no _reason_ for it aside from consistency. Intuitively this code looks like there's a single variable `x` and there is no problem modeling it that way either. It's _only_ when you have multiple cases sharing a body that you need all of the copy-to-a-new-variable shenanigans.

Fair point.  I guess my follow-up question, then, is: what should we do if we're in a switch *statement* but the body corresponds to just a single case?  Do we make a synthetic extra variable in order to be consistent with bodies that have multiple cases?  Or do we do it only when it's strictly necessary?

Concretely:

```dart
late void Function() later;
bool defer(void Function() callback) {
  later = callback;
  return true;
}
multipleCasesWithASingleBody() {
  int e = 0;
  switch (e) {
    case int x when x == 5:
    case int x when (defer(() { print(x); })):
      print(x++); // prints `0`
  }
  later(); // prints `0` because we had to make a synthetic extra variable
}
singleCaseWithASingleBody() {
  int e = 0;
  switch (e) {
    case int x when (defer(() { print(x); })):
      print(x++); // prints `0`
  }
  later(); // what does this print?
}
```

😬 
```

**Comment by lrhn** [comment]
If someone does side-effects in their `when` clause, I don't care that their code doesn't work like they expect.
Just do that in the body instead.

If the variable in the `when` clause is final, we prevent most of the possible side effects.
We can't prevent capturing. We also can't prevent that for the initializing formal variables in initializer lists, and we have lived with that.

I think it's fine. If it really affects someone, they should consider that a learning experience.
