### ISSUE TITLE
How are "inheritance" conflicts in views handled?

### ISSUE THREAD

**Issue by eernstg** [dart-lang/language#2557]
When a view has more than one superview, it is possible to have multiple declarations with the same name. How is this conflict handled?

Even in the case where the member signatures are compatible (say, using the same approach as that of computing a 'combined interface' of the superinterfaces of a class), this is a conflict: There are two implementations of this signature, and we need to select one of them (or report the situation as an error). On top of this, it is also possible for the member signatures to be incompatible. For example:

```dart
view class V1(num it) {
  void foo() {}
}

view class V2(int it) {
  int get foo => 2;
}

view class Va(int it) implements V1, V2 {
  int foo(String s) {} // (a)
}

view class Vb(int it) implements V1, V2 {} // (b)

void main() {
  Vb().foo(); // (c)
}
```

One situation to consider is (a): `Va` declares a member named `foo` that redeclares the conflicted name. I would expect this case to be uncontroversial: There is no error, because the conflict has been resolved explicitly by the author of `Va`. It is not an error that there is no 'correct override' relation between `Va.foo` and `V1.foo` because we do not require that relation to hold (same for `Va.foo` and `V2.foo`).

Situation (b): `Vb` does nothing to resolve the conflict on the name `foo`. We could then do at least the following:
1. Resolve the conflict automatically by a rule specifying a priority on the superviews. For instance, we could say that `V2` is more specific than `V1` because it occurs textually after `V1` in the `implements` clause. Or we could specify some other priority system (e.g., methods are more specific than getters, plus various other rules as needed).
2. Report the conflict as a compile-time error (which essentially means that the developer must write an overriding declaration).
3. A variant of the previous approach: Use a priority system to select the "most specific" declaration, and report a compile-time error if none of the declarations is most specific.
4. Accept the declaration of `Vb` with no errors, and report an error at each invocation, e.g., at (c).

The [current proposal](https://github.com/dart-lang/language/blob/23131b61bb1b787f748df25ae182c1416ffab4e5/working/1426-extension-types/feature-specification-views.md?plain=1#L785) accepts (a) with no errors or warnings, but for (b) it reports a compile-time error (that is, it uses approach (2)). The rationale is that it is error-prone to silently resolve the conflict. Also, accepting the conflict and reporting an error at each call site (4) seems dangerous, because the author of `Vb` does not get a heads-up, and there may be many call sites.

An alternative (different from [the current proposal](https://github.com/dart-lang/language/blob/master/working/1426-extension-types/feature-specification-views.md)) could be to use `extends ... with ...`, where both `extends` and `with` would accept a list of superviews. It would then be an error to have conflicts between `V1` and `V2` in case we use `extends V1, V2`, but if we use `extends V1 with V2` or just `with V1, V2` then the conflict would be resolved silently by giving priority to declarations in superviews that occur later textually. This will allow developers to choose to treat conflicts as errors, respectively using linearization to resolve them automatically, based on what's best for their use case.

@lrhn, @natebosch, @leafpetersen, @kallentu, @jakemac53, @stereotype441, @munificent, WDYT? Do we prefer the automatic conflict resolution because it "just works", or do we prioritize reporting an error because these conflicts might give rise to misunderstandings and bugs?

**Comment by lrhn** [comment]
After more thought and discussion over lunch ... I'm starting to wonder whether one of the issues here is the choice to make view methods act like extension methods, or *inherited* non-virtual methods.

A non-virtual method is, as we use it, attached to a type. However, it's not a given that the method is also available on/inherited by a subtype. That's a property of how we defined extension types, because we *wanted* them to mimic instance methods and be "inherited" by subtypes.

What if we instead defined views as follows:

A declaration of
```dart
view class V<T> extends VS with VM1, VM2 implements VI1, VI2 {
  members;
}
```
(all of the super-clauses are optional, extends allows only one super-view) introduces a new view type `V` (possibly generic).

The type `V` is a proper subtype of the type of the view types `VS`, `VM1`, `VM2`, `VI1`, and `VI2` (all of which must be view types, and of `Object` if the representation type is non-nullable, of `Object?` if the representation is potentially nullable.
(No cycles allowed as usual).

The type `V` has a set of instance view member implementations, which can be invoked as members on expressions of type `V`. It's computer as follows:

Define **updateWith**: Set\<declaration\> &times Set\<declaration\> &mapsto; Set\<declaration\> as so that **updateWith**(*S*, *M*) is found by:
* Let *R* = *S*.
* For member declaration *x* in *M*:
    * If *x* is a getter, let *R* be {*z* &in; *R* | basename(*z*) &ne; basename(*x*) &vee; isSetter(*z* } &cup; { *x* }
    * If *x* is a setter, let *R* be {*z* &in; *R* | basename(*z*) &ne; basename(*x*) &vee; isGetter(*z*)} &cup; { *x* }
    * If *x* is a method, let *R* be {*z* in *R* | basename(*z*) &ne; basename(*x*) } &cup; { *x* }.
* The result of **updateWith**(*S*, *M*) is then *R*

Then, 
Let *S* be the set of member implementations of `VS` (declared or inherited). If `extends VS` is omitted, let *S* it be the empty set.
Let *M1* be the instance member declarations declared by `VM1` (not inherited).
Let *M2* be the instance member declarations declared by `VM2` (not inherited).
Let *M* be the instance member declarations of `members`.

The view implementation members of *V* is then:  **updateWith**(**updateWith**(**updateWith**(*S*, *M1*), *M2*), *M*)

The members of *V* that are not declared by *V* are considered *inherited* members.

Further, it's a compile-time error if `VM`, `VM2`, `VI1` or `VI2` has a member with base name *x* and `V` does not have a member implementation (declared or inherited) with base name *x*. 
(This is optional, we can choose to not make this an error if we don't want to.)

That is: We treat views exactly(-ish) like classes. Member implementation is inherited only along `extends` and `with` (and `with` only gets the top "mixin", or we can restrict it to views with no super-view). Conflicts in implementation is handled by linearization.
Further, we treat views in `implements`, or above the bottom level of "mixins", as interfaces whose base names must be implemented, but which do not carry implementation.


This model breaks with the idea that view methods are extension methods, which automatically apply to subtypes. A view type has the members it chooses to inherit, and nothing more. The "must implement interfaces" requirement does ensure that a view-subtype has *some* member with the same base-name as the interface. 
Again, that requirement is optional, there is nothing fundamentally problematic about allowing a subtype to have a completely different set of methods. It's just likely to be surprising to users who are using a class-like mental model.

(Underlying question: What is the goal of view subtyping? To have *assignability* to the supertype (so an `Element` can be added to a `List<Node>`), and implementation inheritance/reuse. Having an extension-method-like member inheritance by default is not necessary, explicit inheritance control of which members a view has might just be better.

**Comment by eernstg** [comment]
I'd like to repeat the question, because the response so far has been focused on more detailed questions, leaving this fundamental choice unanswered:

@lrhn, @natebosch, @leafpetersen, @kallentu, @jakemac53, @stereotype441, @munificent, in the case where a view "inherits" multiple distinct implementations of the same member name, ..

- do we prefer to have an automatic conflict resolution (like linearization) because it "just works", or
- do we prefer to require an explicit resolution of every conflict, because each conflict might give rise to misunderstandings and bugs?

I'd prefer to report every conflict, and have it resolved explicitly by the developer. (We may introduce syntax to do this very concisely, e.g., using a general forwarding mechanism, but they main point is that the conflict is handled explicitly.)

**Comment by lrhn** [comment]
To me, whether to be parallel or linear depends very much on the word used.
If we use `extends` or `with`, it should be linear. If we use `implements`, it should not.
I currently recommend `is`, which I also wouldn't make linear.

The next question is what happens in case of parallel conflicts.
I'd make it a late error, only if someone accesses the member name. 

Making it an early error, so the class with a conflict, and no declaration shadowing it, would be a compile-time error, has the advantage that the class author is forced to be aware of the conflict, so they can "fix" it. But if they don't want to fix it, they are still forced to do so, which can be annoying.
It's more consistent with what we do elsewhere to make errors early, forcing a type to have a single consistent API. It probably depends on how we see the layering - is the view a class like unit of API, or is it just a layer on top of something else, and if that something else is inconsistent, that's no more a problem than having conflicting imports.

**Comment by jakemac53** [comment]
While I see how we could support these types of conflicting declarations with views, I am not sure that it is actually a good idea to do so? I think I would prefer it to be an error in all cases (basically, it should behave exactly like normal classes). I might even be more strict and not allow any conflicting declarations, even where the types are compatible.

The reason I feel that way, is that I want views to feel as much like classes as possible. At the usage sites in particular, you can't tell the difference between a view and a class (without navigating to the type). For the most part, they do behave the same (as far as the user is concerned), except if we silently hide these conflicts. Then, if you can up-cast a view, and views are allowed inherit other views which declare the same members, then it actually changes the behavior of the object to upcast it.

**Comment by lrhn** [comment]
Upcasting changes behavior of statically dispatched methods. That's what being statically dispatched means.
It's already true for extension methods, which we *try* to make look like instance methods.

It will be true for views too, if we allow any sort of "sub-view" relation with "member inheritance", and the ability to declare something with the same name as what you inherited. At that point, up-casting to the super-view type will make that name resolve to a different method.
The only way to avoid that is to not allow sub-views to override/shadow an inherited member. I think that's far too restrictive.
(I'd start doing those methods as extension methods on the view types then, and get the same effect anyway.)

I think we should allow sub-view'ing APIs which have members of the same name.
The only question, to me, is whether such a conflict should be:
* Resolved automatically by linearizing the super-views,
* Made into a compile-time error in the sub-view, unless it declares a member with the same name,
* Made into a compile-time error if a conflicted member is invoked.

**Comment by eernstg** [comment]
> The only way to avoid that is to not allow sub-views to override/shadow an
> inherited member. I think that's far too restrictive

The views proposal used to have that restriction, and it was removed. The main argument, as I saw it, was that it is possible to inspect exactly which piece of code is getting invoked at each view method call site, exactly because it is statically resolved. This is also true in the case where the static type of the receiver changes from, say, `SubView` to `SuperView`, in which case the implementation that we're actually calling could change from `SubView.m` to `SuperView.m`.

The only missing part is that IDEs ought to show every static invocation with a pale blue background color, and every method call with a pale yellow background color, and every dynamic invocation with a blinking red background color. Developers would then know that the blue ones are resolved at compile-time and no dispatch will occur, and they can reason about the code based on that knowledge.

**Comment by leafpetersen** [comment]
I'm somewhat torn here.  

I mildly prefer linearization, using the `with` syntax.  My second preference is to use `implements`, and make it an error at the declaration site to have an unresolved conflict.

I do not like using `extends` - the semantics are too different.  For example, I would expect to have to call a super constructor when I `extend` a view.  I *especially* do not like the idea of having `extends` with a list of multiple super views.

The complexity of the mixin semantics concerns me.  I am more and more convinced that simply using `implements` here is the right choice, because it automatically gives the right semantics.  That implies no linearization.

**Comment by eernstg** [comment]
Here's one reason why we might want to use explicit conflict resolution, at least in some cases:

```dart
view class V1(...) { int get m => 1; }
view class V2(...) { void m() {}}
view class V with V1, V2 {} // OK!
```

Is it really plausible that we want to silently resolve the conflict between declarations that are so different?

It differs from a normal override relationship (where we're happy to let `with` linearize several different implementations of a given member name) in that there is no justification for the assumption that "those two versions of `m` have the same purpose". It is almost guaranteed that this will occur in a situation where the author of one `m` knew nothing about the existence of the other `m`, and hence it's a source of confusion to see `with V1`, and hence assume that we have `V1.m` available, and not know that `V2` has a completely different `m`.

We could declare a conflict, say, at least in the cases where we cannot compute a combined member signature (which is one well-known way to define "the declarations are too different" precisely), or in the case where the linearization gives rise to a shadowing relation which isn't a 'correct override'.

However, there is no semantic justification for this kind of requirement, because no call sites will make a dynamic choice between one or the other declaration.

So my preference is still to report every conflict.

**Comment by munificent** [comment]
I think we should follow as closely as feasible to how extension methods behave today. As I understand it, that means reporting a conflict if two supertypes define a member with the same name unless the subtype defines a more specific one:

```dart
class A {}
class B {}
class C implements A, B {}

extension on A {
  void foo() { print('A.foo()'); }
  void bar() { print('A.bar()'); }
}

extension on B {
  void foo() { print('B.foo()'); }
  void bar() { print('B.bar()'); }
}

extension on C {
  void foo() { print('C.foo()'); }
}

main() {
  C c = C();
  c.foo();
  c.bar();
}
```

This reports an error on the call to `bar()` but not `foo()`. For views, then, I would suggest the same behavior if you were to write:

```dart
view class A {
  void foo() { print('A.foo()'); }
  void bar() { print('A.bar()'); }
}

view class B {
  void foo() { print('B.foo()'); }
  void bar() { print('B.bar()'); }
}

view class C <whatever keyword> A, B {
  void foo() { print('C.foo()'); }
}

main() {
  C c = C();
  c.foo();
  c.bar();
}
```

That seems like it gives us the least new mechanism and the easiest path to explaining the behavior for users.

**Comment by lrhn** [comment]
> I think we should follow as closely as feasible to how extension methods behave today. As I understand it, that means reporting a conflict if two supertypes define a member with the same name unless the subtype defines a more specific one:

That's only an error if someone tries to call the method. If nobody does, there is no conflict.

We can do either: If you'd "inherit" conflicting declarations, and doesn't override them, either it's just a compile-time error, or it's an error only if someone tries to invoke that name (and that can be either because we remember the conflict explicitly, a "conflicted member", or because we just don't inherit anything in case of conflict, "no member of that name".)

I'm leaning towards the last one. No conflict, also no member. It's fragile if someone adds something to a super-view, but no more fragile than any of the other solutions. The only difference is where you need to fix it. In the late error case, you can fix it either in the sub-view (introduce a member) or at the call site (cast to the correct super-view first).
In the early error case, your program won't compile until the subview is changed.

**Comment by eernstg** [comment]
One more reason to report the conflict early, based on imports/exports:

Note that we allow conflicts with overlapping namespaces in imports (only usages are flagged as errors), but they are reported as errors in exports:

```dart
import 'a.dart'; // Defines 'int a = 1'.
import 'b.dart'; // Also defines 'int a = 2'.

void main() {
  // Currently no errors; compile-time error if the next line is uncommented:
  // a = 0;
}
```

```dart
// Compile-time error: Both libraries export the name 'a'.
export 'a.dart';
export 'b.dart';
```

The import conflict is reported late because the conflict is created by local code (i.e., code in the same library), and if the conflict arises then the imports can be edited. There is no violation of encapsulation because this library "knows" that it imports 'a.dart' and 'b.dart'.

The export conflict is reported early because it would otherwise cause errors in different libraries. Maintainers of those libraries could resolve the conflict by importing 'a.dart' or 'b.dart' themselves, but that's at best inconvenient, and it seems to violate the encapsulation that we depend on getting the conflicted names by that specific export by another library.

Similarly, we could report the conflict early with inline classes (that is, at the declaration of the class that creates the conflict), because we don't want to silently deliver that conflict to clients using this type. Also, it may be considered as a violation of encapsulation if those clients need to know the exact superinterface structure in order to resolve the conflict themselves.

**Comment by lrhn** [comment]
There is indeed similar amount of implicitness in exports and view-subtyping-with-inheritance.

If an exported library or an inherited superview type *adds* a new member, it is immediately exported. 
Unless you export with a `show` clause, which you always should for *precisely* that reason.
Exporting another entire library, at least one that you are not in *complete* control over (so from the same package), should never be done, because you then cannot control your API.

In the view case, the subview declaring a member with the same name shadows the conflict. In libraries, that's another source of conflict, because the library declarations do not shadow exports.

When a second library or superview adds a member with the same name, there is a *conflict*.
In the library case, that's an immediate compile-time error, and has to be resolved, by using a `show` or `hide` (or it shouldn't happen if you used a `show` already).

But libraries are not objects. They are much more "pick and choose" collections of individual members, not a coherent API.
If a subview exposes a superview API, it will usually want to expose the entire API. If not, it's really not the same API, and it might as well rename all the members (so, do manual forwarding).
If it exposes two superview APIs, and those two have a conflict, it's already a conceptual problem. It may not be possible to combine the two APIs. (Overloading sure would make things quite a lot easier here).
One of those two APIs is going to be incomplete.

So, OK, it might be reasonable to make it a compile-time error when that happens. It means you need a new version of the library declaring the subview, but when that library is updated (presumably to expose the same super-view API as before, and hiding the newly conflicting one), client code will keep working.

I guess that's no less inconvenient than any other conflict that a new member of something introduces.
I'm convinced. Early conflict error!

**Comment by munificent** [comment]
Early errors on conflicts sound good to me too.

**Comment by eernstg** [comment]
Sounds good, thanks!

I'll **conclude** that conflicts among "inherited" declarations must be handled explicitly, and this can be done by providing a redeclaration of the conflicted name. The construct has been renamed to 'inline class', and the introduction of primary constructors has been postponed, so the example now looks like this:

```dart
inline class V1 {
  final num it;
  void foo() {}
}

inline class V2 {
  final int it;
  int get foo => 2;
}

inline class Va implements V1, V2 {
  final int it;
  int foo(String s) {} // Redeclaration resolves the conflict; no errors.
}

// Compile-time error: conflict on `foo`:
inline class Vb implements V1, V2 {
  final int it;
}
```
