### ISSUE TITLE
[Records] Type literal

### ISSUE THREAD

**Issue by Cat-sushi** [dart-lang/language#2572]
[The specification of records](https://github.com/dart-lang/language/blob/master/accepted/future-releases/records/records-feature-specification.md#no-record-type-literals "language/records-feature-specification.md at master · dart-lang/language") says that there is no type literal for records.
I understand that records are anonymous shaped value type, but sometimes type name is useful for self documenting and shorter typing.
Of course, classes can be a solution, but I expect records without wrapping objects are cheaper than instances of classes, because records are subset of pattern matching.
Another future cheap solution named views  have type name, but they cant have multiple fields.

Could we have type literal for records?
The following example is feasible?

```dart
typedef point = Record<(int x, int y, int z)>;
```

**Comment by Cat-sushi** [comment]
I found a future solution combining records and views.
I'll wait for both of them.
```dart
view class Point {
  final (int, int) coordinates;
  const Point.from(this.coordinates);
  const Point(int x, int y) : coordinates = (x, y);
  int get x => coordinates.$0;
  int get y => coordinates.$0; 
}
```

**Comment by munificent** [comment]
> Could we have type literal for records?

Type literals are different from type names. If you want to give a name to a record type, you can use a typedef:

```dart
typedef Point = (int, int);
```

Type *literals* is the weird corner of the language where you can use a type name *as an expression* to get a reified runtime object that represents the type. For example:

```dart
var x = int;
print(x);
```

Here, `int` is a type literal that evaluates to a runtime type object for the integer type. It's not a very common feature. We don't support record type literals because they are ambiguous with records *of* type literals:

```dart
var x = (int, int);
```

Is this a type literal of the record type `(int, int)`, or is it a record *value* whose two fields are type literals for the `int` type? To avoid that ambiguity, we don't support record type literals and the answer is the latter.
