### ISSUE TITLE
[Patterns] Record pattern and extension getters

### ISSUE THREAD

**Issue by scheglov** [dart-lang/language#2579]
When we match a record pattern, the specification says "is a record type with a corresponding field". So, it sounds to me that we don't allow matching of extension getters, in contrast to extractor patterns. Is this intentional?

I mean strange code like this:

```dart
extension E on ({int foo}) {
  int get bar => 2;
}

void f(({int foo}) x) {
  if (x case (foo: var y, bar: 2)) {}
}

typedef A = ({int foo});

void f2(({int foo}) x) {
if (x case A(foo: var y, bar: 2)) {}
}
```
My understanding is that `f2` is supposed to work, but `f`, with the specification written as it is now - not.

**Comment by stereotype441** [comment]
CC @leafp @lrhn @natebosch @eernstg @kallentu @jakemac53 @mit-mit @munificent

**Comment by lrhn** [comment]
I agree with that, and I think it's what we want.

A record pattern match is not an an extractor/object pattern match. It attempts to, and must, match the *record shape*.
If not, we cannot extract members from the record to begin with.

If you *want* to use an extractor pattern on a record, you can get that as:
```dart
typedef Typeof<T> = T;

...
  if (x case Typeof<({int foo})>(foo: var u, bar: 2)) { ... }
```

In fact, you can think of a record pattern of `(p1, p2, x1: p3, x2: p4)` as desugaring to an extractor pattern of:
```dart
Typeof<(Object?, Object?, {Object? x1, Object? x2)>($1: p1, $2: p2, x1: p3, x2: p4)
```
The pattern shape test is implicit, and after that pattern shape has matched, a shape which was derived from the pattern fields, it's impossible that an extension can apply to those field patterns.

**Comment by munificent** [comment]
The destructuring patterns (records, list, map, object) all essentially do two things:

1. Test the matched value against some type.
2. If it has that type, do further destructuring on the value as that type.

With a record pattern, we use the shape of the pattern to determine *both* 1 and 2. If some of those destructured fields could be extension getters, it becomes impossible to tell what the intended shape of the matched record should be if we don't already know, as in:

```dart
extension on (int, int) {
  int get sum => $0 + $1;
}

main() {
  // Upcast to Object:
  Object obj = (1, 2);

  switch (obj) {
    case (var x, var y, sum: var s): ...
  }
}
```

So, no, I don't think we should support extension getters in record patterns. We can and do in object patterns, because there is a separate named before the destructured fields that is used to determine what type to test. With record patterns, we don't have that luxury.
