### ISSUE TITLE
null safety strange behavior

### ISSUE THREAD

**Issue by pskink** [dart-lang/language#2584]
with the following code:
```
int? i;
i = 0;
final i2 = i;

List.filled(1, i.sign); // ok
List.filled(1, i2.sign); // ok

List.generate(1, (_) => i.sign); // error: The property 'sign' can't be unconditionally accessed because the receiver can be 'null'.
List.generate(1, (_) => i2.sign); // ok
List.generate(1, (_) => i!.sign); // ok
```

i am not sure if its a bug or expected feature that `List.generate(1, (_) => i.sign);` reports an error while all other cases are ok

**Comment by ykmnkmi** [comment]
Everything works as expected, since this is a closure, there is no guarantee that when it is called, the variable `i` will still have a value.

**Comment by ykmnkmi** [comment]
For such cases, it would be nice to have a modifier that means that the passed function or method will be called synchronously and immediately.

**Comment by lrhn** [comment]
The closure is indeed what makes the difference.
The type promotion is usually clever, but around closures, it really assumes worst-case. There exists a time where `i` is not an `int`, and you never know when a closure will be called, so it assumes that it might see a `null` in `i`.
(Even if the closure is created after a point where the variable is promoted, and will never be demoted again. Probably because the type inference step which does the type promotion, hasn't visited the rest of the function yet, and seen that the variable isn't assigned `null` again.)

**Comment by pskink** [comment]
thanks a lot for clarifying!

**Comment by pskink** [comment]
however if we change `final i2 = i;` to `int? i2 = i;` then I don't really see any difference between `i` and `i2` - they are both `int?` so why closure with `i2` is ok?

**Comment by Levi-Lesches** [comment]
@pskink The reason `i2` is okay is that it captures the value fo `i` at the time it is evaluated -- and at that time, `i != null`, so `i2` is _non-nullable_. That's why it breaks when you switch it to `int? i2 = i`: because you used `final`, Dart is guessing which type you want, and it guessed `int`, not `int?`. 

This steps around the question of passing data to closures in the future: if Dart can't be sure whether `i` will be null or not when the closure is called, you can always make your own variable, `i2`, which has exactly the value you want, `0`, mark it non-nullable, and use that in your closures instead.

**Comment by pskink** [comment]
@Levi-Lesches it is still strange: if I do `int? i2 = i;` i can use `i2` (promoted to `int`) inside a closure but if I add another line `i2 = 99;` (anywhere) I cannot since there is compilation error in the closure
