### ISSUE TITLE
[Patterns] Duplicate names of record pattern fields

### ISSUE THREAD

**Issue by scheglov** [dart-lang/language#2610]
Is it an error to repeat them in a record pattern?
```dart
void f(Object x) {
  if (x case (foo: var a, foo: var b)) {}
}
```
Here we have to build the required record type, and with duplicate names it is not valid.

Is it an error to repeat them in an object pattern?
Given that we can invoke any getter, including getters from extensions, the getter can return new values.
So, it is not necessary invalid and completely useless.
```dart
void f(Object x) {
  if (x case X(foo: var a, foo: var b)) {}
}

class X {
  int _foo = 0;
  int get foo => _foo++;
}
```

**Comment by munificent** [comment]
> Is it an error to repeat them in a record pattern?

It doesn't *have* to be. It's harmless to destructure the same named field multiple times.

> Given that we can invoke any getter, including getters from extensions, the getter can return new values.

The proposal does say that all invocations are cached, though, so if you destructure the same getter multiple times, you'll get the same value every time.

It doesn't need to be an error, but I agree that it's completely useless. Anything you could do by destructuring the same field multiple times, you could also do by destructuring once with an `|` subpattern. If a user does repeat a field name, it's most likely a mistake and it's probably helpful to point out the error.

I think I'll make this an error. If for some reason it turns out that people *do* want to do this, it's a non-breaking change to remove the error in a future release.
