### ISSUE TITLE
Definition for assignable expression needs clarification

### ISSUE THREAD

**Issue by jmewes** [dart-lang/language#2611]
## Observed

In section "17.36 Assignable Expressions" of [DartLangSpecDraft.pdf](https://spec.dart.dev/DartLangSpecDraft.pdf) it is written that:

> Assignable expressions are expressions that can appear on the left hand side of an assignment.

Further, it is mentioned that an _assignable expression_ can be:

> An invocation (possibly conditional) of a getter (10.3) or list access operator on an expression e.

I understand the term "on the left hand side of an assignment" as left to the assignment operator:

```
<expression> ::= <assignableExpression> <assignmentOperator> <expression>
  | ...
```

Here is a code snippet that tries to provide an example for the definitions above:

```dart
class Qux {
  int _q = 0;
  
  int get quux => _q;
}

void main() {
   var qux = Qux();
  
   qux.quux = 42; // Error: The setter 'quux' isn't defined for the class 'Qux'.
// ^      ^
// |------|-------  invocation of a getter, used as an assignable expression, as defined above
}
```

(https://dartpad.dev/?id=7c25b19d3197a554b382cf50263b4c2a)

I understand `qux.quux` as an invocation of a getter that - according to the quotes above - should be usable on the left hand side of an assignment. However, the code fails to compile since a setter is expected instead of the invocation of a getter.

## Expected

~For me, section "17.36 Assignable Expressions" would make sense if it would mention "setter" instead of "getter". The updated definition would then look like this:~

> ~An assignable expression is either: (...) An invocation (possibly conditional) of a **setter** or list access operator on an expression e. (...)~

Here is a code snippet that tries to provide an example for this updated definition:

```dart
class Qux {
  int _q = 0;
  
  set quux(int i) {
    _q = i;
  }
}

void main() {
   var qux = Qux();
  
   qux.quux = 42;
// ^      ^
// |------|-------  invocation of a setter, used as an assignable expression, as defined above
  
   print(qux._q); // 42
}

```

(https://dartpad.dev/?id=c0a1bd1036ad850e4d456ab1378f4561)

## Steps to reproduce

See https://github.com/dart-lang/language/blob/6727010/specification/dartLangSpec.tex#L16282-L16283

## References

- Also see the following discussion in the `#language` channel of [The Unofficial Dart Community Discord](https://discord.gg/Qt6DgfAWWx): https://discord.com/channels/823048554532700191/870318216747024414/1038373764674633780
- Section 17.23 of [DartLangSpecDraft.pdf](https://spec.dart.dev/DartLangSpecDraft.pdf): "An assignment changes the value associated with a mutable variable, or
invokes a setter."

**Comment by lrhn** [comment]
*Grammatically*, `qux._q` looks like an invocation of a getter, but it isn't. I agree the phrasing is confusing.

**Comment by eernstg** [comment]
The main words here are

> This section describes how to evaluate these expressions when
> they do not constitute the complete left hand side of an assignment.

In other words, for `qux.quux = 42`, this section describes how to evaluate `qux`, and for `myList[15].qux += e`, it describes how to evaluate `myList[15]`.

As you can see, the section basically just says that every available form is evaluated as the corresponding expression.

The semantics of assignments (including forms like `variable = expression` and `e.name += expression` where `e` is such that `e.name` is an `<assignableExpression>`) is specified elsewhere, e.g., https://github.com/dart-lang/language/blob/67270109be694bdf2997ea751d9266cbccc906b4/specification/dartLangSpec.tex#L15086.

The situation where `e.name` is an `<assignableExpression>` only includes situations where `e` can also be parsed as an expression (only some expressions will do, e.g., `a + b` won't). So the specification of the semantics of `e1.v = e2` describes `e1` as an "expression" (and it doesn't go into detail about the fact that only some expressions are possible, because we have already mentioned that `e1.v = e2` is an expression, which implies that `e1.v` is an assignable expression).

I agree that the treatment as a whole can be confusing, but I think this illustrates that it's not arbitrary. In particular, the text in 'Assignable Expressions' would _not_ be more correct or informative if we changed 'getter' to 'setter' as suggested.

Do you have any ideas about how the treatment of this topic could be made less confusing?

**Comment by jmewes** [comment]
The English term "assignable expression" consists of two words: the [adjective](https://www.merriam-webster.com/dictionary/adjective) "[assignable](https://www.merriam-webster.com/dictionary/assign)" and the noun "expression". So, it implies that the expression can be transfered to another.

However, my naive understanding of the definition for an `<expression>` is that it can receive a value from another:

```
<expression> ::= <assignableExpression> <assignmentOperator> <expression>
| <conditionalExpression>
| <cascade>
| <throwExpression>
```

That understanding is supported by the first sentence of section "17.36 Assignable Expressions".

I suggest to consider a naming that doesn't allow this ambiguity.

And to narrow down "An assignable expression is either: (...) An invocation (possibly conditional) of a setter or list access operator on an expression e. (...)" to something that also doesn't allow this ambiguity.

Further, the main points of a section would be better suited for first sentence than the second sentence.

**Comment by jmewes** [comment]
What is wrong with those conclusions?

```dart
class Qux {
  int _q = 0;
  
  int get quux => _q;
}

void main() {
   var qux = Qux();
  
   qux.quux = 42; // Error: The setter 'quux' isn't defined for the class 'Qux'
}
```

1. `qux.quux` is the invocation of a getter.
2. As defined by https://github.com/dart-lang/language/blob/6727010/specification/dartLangSpec.tex#L16279-L16283 , the invocation of a getter is an `<assignableExpression>`
3. The number 42 is an expression.
4. `=` is an `<assignmentOperator>`
5. An `<expression>` can be formed from: `<assignableExpression> <assignmentOperator> <expression>`
6. So, `qux.quux = 42` should be a valid expression, but it fails to compile.

**Comment by eernstg** [comment]
Good catch, that section is actually quite confusing! ;-)

> an `<expression>` ... can receive a value from another:

Agreed, except that I guess it should have been 'an `<assignableExpression>` ... can receive a value'.

For example, we don't support `1 + 1 = newValue;`, so the left hand side of an assignment cannot in general be an `<expression>`, it needs to be an `<assignableExpression>`.

Those two non-terminals are independent, that is, none of them is able to derive the other. In contrast, e.g., `<expression>` can derive `<primary>`, so a primary is a kind of expression, but an assignable expression isn't a kind of expression (nor vice versa).

> That understanding is supported by the first sentence of section "17.36 Assignable Expressions".

Here's the text:

> Assignable expressions are expressions that can appear on the left hand side
> of an assignment. This section describes how to evaluate these expressions when
> they do not constitute the complete left hand side of an assignment.

The first sentence would have been more precise if it had been 'Assignable expressions are terms', because it is not syntactically accurate that they are `<expression>`s. Nevertheless, if we have a sequence of tokens that can be derived from `<assignableExpression>` then they could also be derived from `<expression>`. In other words, we can always _reinterpret_ a given assignable expression as an expression, if that is justified by the given context.

I think the really confusing part is this line:

> An _assignable expression_ is either:

At this point the text definitely ought to say that we have the syntax (which is described quite directly by the following lines), and then we also have the special case where we consider incomplete assignable expressions. That is, an assignable expression `e` and a term `t` such that `e` can be derived from `t <assignableSelector>`. The rest of the section is then specifying how to evaluate `t`. The entire assignment is specified elsewhere, but it relies on the description in this section to handle "the `t` part of the assignment" in this sense.

I'll create a PR to clarify the text.

> What is wrong with those conclusions? [about `qux.quux = 42`]

You're using spec language which is applicable to an _incomplete_ left hand side of an assignment to the term `qux.quux`, but `qux.quux` is the _complete_ left hand side of the given assignment.

But the section still needs to be clarified. ;-)

**Comment by lrhn** [comment]
The big problem here is that assignable expressions, the grammatical category, is really *potentially* assignable expressions. The same syntax can denote both a local variable and a final local variable, a getter and setter, or a getter without a setter. Or an `operator[]` without an `operator[]=`.

The grammar does not distinguish those cases. If it was named "potentially assignable expression", then it might be easier to say things like "if the variable or property denoted by the potentially assignable expression is not actually assignable" without sounding ridiculous :grin:.

**Comment by jmewes** [comment]
Thanks for the explanations and addressing the feedback. I am glad that my understanding was at least not completely wrong.

**Comment by eernstg** [comment]
Thanks again! I'll close this issue: The work is handled via #2615 now.
