### ISSUE TITLE
Use private like super keyword 

### ISSUE THREAD

**Issue by marcoNonvanilla** [dart-lang/language#2614]
The recently added super keyword is great to eliminate unnecessary boilerplate. I think the same could easily be done for private:

```dart
class ClassName {
   final int _myNum;
   final int _myPubNum;

  ClassName({required private.myNum, required this.myPubNum});
}
```

**Comment by eernstg** [comment]
I think this is covered by https://github.com/dart-lang/language/issues/2509 (search for 'super'). If you wish to recommend that we use a different syntax (such as `private.myNum` rather than `_myNum`, `this._myNum`, `super._myNum`) then it's probably better to comment on that issue than it is to create this new one.
