### ISSUE TITLE
Apply a mixin to a class that implements the class for which the mixin is

### ISSUE THREAD

**Issue by InAnadea** [dart-lang/language#2617]
I'm trying to apply mixin to the class that already extends other class and I want to implement some other functionality. Also I have mixins for this other functionality and my class needs it.

Code sample

```dart
abstract class Animal {
  bool get hasTooth;
  bool get hasLegs;
}

mixin Bitable on Animal {
  bool bite() => hasTooth;
}

mixin Runnable on Animal {
  bool run() => hasLegs;
}

class Dog extends Comparable implements Animal /*with Runnable, Bitable*/ { // here is problem
  @override
  int compareTo(other) {
    return 1;
  }

  @override
  bool get hasLegs => true;

  @override
  bool get hasTooth => true;
}

class Shark extends Comparable implements Animal /*with Runnable, Bitable*/ { // here is problem
  @override
  int compareTo(other) {
    return 1;
  }

  @override
  bool get hasLegs => false;

  @override
  bool get hasTooth => true;
}
```

Maybe I don't understand mixins? Thanks!

**Comment by eernstg** [comment]
A couple of comments:

You probably don't want to have `Comparable` as a superinterface (that is, anywhere in the `extends`, `with`, or `implements` clauses), because this means `Comparable<dynamic>`, which in turn implies that the parameter type of `compareTo` is `dynamic`. So let's make it `Comparable<Animal>`.

Next, the `with` clause is used to create a superclass, and hence it's part of the superclass clause (which is also known as the `extends` clause). So we're moving them back a bit.

Next, you probably don't want to have `Comparable` as a superclass (because there's nothing to inherit), so I'll swap `Animal` and `Comparable`.

Finally, you _can_ use `on Animal` in the mixins, but it is an unnecessary restriction: If you use `implements Animal` rather than `on Animal` then you get exactly the same kind of support for calling methods of `Animal` in the body of the mixin. The difference is that `on Animal` requires the _superclass_ to be a class that implements `Animal`, but that's only important if you want to call `super.m` where `m` is a member of `Animal`. In short, it is never useful to have an `on` clause in a mixin that doesn't call any `super` members, just use `implements` instead.

Here's the resulting code:

```dart
abstract class Animal {
  bool get hasTooth;
  bool get hasLegs;
}

mixin Bitable implements Animal {
  bool bite() => hasTooth;
}

mixin Runnable implements Animal {
  bool run() => hasLegs;
}

class Dog extends Animal with Runnable, Bitable implements Comparable<Animal> {
  // here is problem
  @override
  int compareTo(other) {
    return 1;
  }

  @override
  bool get hasLegs => true;

  @override
  bool get hasTooth => true;
}

class Shark extends Animal with Runnable, Bitable implements Comparable<Animal> {
  // here is problem
  @override
  int compareTo(other) {
    return 1;
  }

  @override
  bool get hasLegs => false;

  @override
  bool get hasTooth => true;
}
```

**Comment by InAnadea** [comment]
Thanks, @eernstg! But, if I need to extend, for example, the `Equatable` class, implement `Animal` with these mixins?

**Comment by eernstg** [comment]
If you need to extend a specific class then you can certainly use a mixin that requires `this` to implement some other class:

```dart
abstract class A { void m(); }
class B { void m2() {} } // Must be superclass, implementation needed.
mixin M implements A { void m3() { m(); }} // Needs to call `A` members, but not `super`.

class C extends B with M implements A {
  @override
  void m() {} // Any of these classes can provide the actual implementation of `m`.
}
```

**Comment by eernstg** [comment]
> need to use `on` for mixins only when I need to use `super` in mixin

Exactly: If the interface of `A` contains `m` and you need to call `super.m()` in the body of a mixin `M` then `mixin M on A ...` is needed. If you do not need to call `super.m()` (because a plain `m()` will do the right thing anyway) then you also do not need `on`. In that situation `mixin M implements A ...` will do, and it is much more flexible.

**Comment by eernstg** [comment]
I think we should close this issue because it doesn't report anything which should be changed. We can still add comments as needed.
