### ISSUE TITLE
[Patterns] what should the user experience be if a record match is guaranteed to fail due to shape mismatch?

### ISSUE THREAD

**Issue by stereotype441** [dart-lang/language#2632]
Consider this code:
```dart
f((int, String) x) {
  switch (x) {
    case (a, b, c):
      print('impossible'); // (1)
  }
}
```
As currently specified, the line at (1) can't be reached, because the intersection between the matched value type (`(int, String)`) and the required type of the pattern (`(Object?, Object?, Object?)`) is empty.  But there's no compile-time error or warning specified.  This seems bad--we should let the user know that the match is guaranteed to fail.  Ideally the error message (or warning/hint/lint message) should give some insight about *why* the match is guaranteed to fail (in this case because the pattern has the wrong number of unnamed fields).

A more subtle way this sort of scenario could arise is from a sub-pattern, e.g.:
```dart
abstract class C {
  (int, int) get coordinates;
}
f(C c) {
  switch (c) {
    case C(coordinates: (x, y, z)):
      print('impossible');
  }
}
```

How do we want to handle this?
- Make it a compile time error?
- Make it a warning?
- Have flow analysis mark the code as unreachable (which leads to an analyzer hint)?
- Make a lint or hint to detect this case?

And do we want to do similar things for other circumstances where the pattern can be proven not to match based on the matched value type?  For example, we could conceivably detect all these scenarios:
- A record pattern is guaranteed not to match because the matched value type is a record with a different shape.
- A record pattern is guaranteed not to match because the matched value type isn't a record type and isn't a supertype of `Record`.
- A constant pattern is guaranteed not to match because the constant's type is a type that can't be subclassed (e.g. `int` or an enum) and the matched value type isn't a supertype of it.
- A null check pattern is guaranteed not to match because the matched value type is `Null`.
- A list or map pattern is guaranteed not to match because the matched value type is a type that can't be subclassed.
- An object or variable pattern is guaranteed not to match because the matched value type is a record type, and the required type is neither a record type nor a supertype of `Record`.

**Comment by stereotype441** [comment]
CC @munificent @leafpetersen @jakemac53 @lrhn @mit-mit @natebosch @eernstg @kallentu

**Comment by eernstg** [comment]
Previously only a few kinds of types had significant constraints on the possible subtypes (function types have only other function types and bottom types, `enum` types have only bottom types, `num` has only a few platform classes, none of them related to `String`, and so on).

I think we're about to get more of those (`final` classes have only bottom subtypes, record types with different shapes can't intersect).

We should probably introduce the notion of disjoint types (types whose intersection is empty), and then we can use this property to guide detection of unreachable code, patterns that won't ever match a given scrutiny, and so on.

**Comment by leafpetersen** [comment]
I think there is a whole category of errors/warnings that are currently somewhat underspecified because they depend on exactly what we can wring out of the exhaustiveness checking, and I wonder if this is one of them.  The minimum that we require is some notion of "this switch is/is not exhaustive", but I think it's likely we can also pull out of the data structures redundancy information (this case will never be reached because all possible matches are covered by previous cases).  It's possible that we can also pull out irrelevancy information (this case can never match) from the same process, and if so, I believe we should surface that to the user in some way.  For the last two, I don't have strong feelings about whether we make these specified errors or just tooling diagnostics.  It feels like making them ignorable is useful (i.e. diagnostics), since it makes code evolution easier (the unreachable/redundant cases may signal a logic error, but they are not in and of themselves problematic).

For your first example, I think there is a specified exhaustiveness error, since all of the types involved are sealed, but for your second example I think not.

In the absence of this falling out of exhaustiveness checking, I'd personally be in favor of there being some type driven diagnostic when a case definitively cannot match because of the sealed nature of the types involved.

**Comment by munificent** [comment]
> The minimum that we require is some notion of "this switch is/is not exhaustive", but I think it's likely we can also pull out of the data structures redundancy information (this case will never be reached because all possible matches are covered by previous cases).

Yes, the algorithm I proposed explicitly detects unreachable cases (as other pattern matching exhaustiveness algorithms I've seen do).

> It's possible that we can also pull out irrelevancy information (this case can never match) from the same process, and if so, I believe we should surface that to the user in some way.

I'd like to do this too. As Eric says, we haven't done this before because up until now most types in Dart were open to subtyping, so any pair of types unrelated types may not actually be disjoint because there could be a third type somewhere that implements both.

Now that we have record types (which are implicitly closed to subtyping) and are also working towards letting user defined classes prohibit being subtyped, there are plenty of cases where the language will be able to tell that two types are actually disjoint. Given that, I think it's worth showing that to the user.

My general preference is to use warnings for code that is harmless but pointless. Things like unreachable code in a block after a return statement, `?.` on non-nullable types, etc. It's basically all some flavor of unreachable code. I would put this into that same bucket.

We can do this just within refutable patterns if we want. We may also want to consider performing similar checks on `is` and `as` expressions which can also be provably useless:

```dart
String s = 'definitely not a number';
if (s is int) print('this will never be reached');

s as int; // This will always throw.
```

(This is perhaps even an argument *for* supporting final classes because it gives users an ability to opt into these smarter checks for types they don't intend to be subtyped.)

**Comment by lrhn** [comment]
With "this cannot happen" scenarios, we need to decide at which level we trust it. We had the problem with nullability, where we decided that a branch was unreachable, even if it actually wasn't because of unsound null safety. What happens on that branch should have affected promotion.

We have the same issue here. We can decide to issue a warning or not, but we do need to decide how it affects flow-based analysis.
```dart
String? s = "a string"; // s promoted to `String`
if (s == null) {
  s = null;
}
// s still promoted to `String`? (Yes.)
```
This is not new, as this example shows by not using patterns, and we have made a choice to assume that any condition *can* go both ways, even if it really cannot. It's the *soundest* thing to do (if anything else breaks, we don't worsen the unsoundness), and if the user doesn't like the result, they can stop having dead code.

We only make flow based decisions based on actual flow control operations (`break`, `return`, etc.), branches are assumed to be live.
The only places we don't do that is for exhaustiveness (and that's where we need a backup throwing default case for unsound null safe mode).

What I'm hopefully getting to soon, is that we should be very clear on where exhaustiveness applies, because it's very important to our flow analysis. It's better to use it less, than to use it unpredictably.

I'd be fine with checking for exhaustiveness only in `switch` cases. Mainly because it's the only place we cache properties between tests. Also I don't particularly want to specify whether or when an `if`/`else if` chain is exhaustive. Or nested `if`-trees.

I'm sure it's *possible* to generalize, each flow path carrying a "what have I exhausted so far from each relevant exhaustive domain" analysis. 
I just worry that it leads to weird cases like:
```dart
int i = 42;
if (i is int) {
  ...
} else {
  // what is i here? (int & !int), is that Never?
  i = i;
}
```
(Assuming each type can be used for exhaustiveness on its own, an exhaustive choice between `is X` and `is! X`.)

Or users getting confused why 
```dart
int fooForRealness(Foo x) {
  if (x case Foo(isForReal: true, realness: var r)) { 
    return r;
  } else if (x case Foo(isForReal: false, realness: var r)) { 
    return -r;
  }
  // unreachable, right?
}
```
doesn't work, because the `if` chain is not exhaustive, because we don't know that `Foo.isForReal` is stable.

**Comment by munificent** [comment]
> because we don't know that `Foo.isForReal` is stable.

This is a very very good point. We definitely won't take the caching behavior that we do within a switch statement/expression/element and extend it across a chain of `if-case` statements. That strongly suggests to me that exhaustiveness checking and promotion based on it is confined to within switches as well.

At the same time, independent of promotion, I think it will likely be reasonable to emit warnings on pointless `is` and `as` expressions when we know the type can never match. We probably shouldn't have type promotion treat `if (foo is Disjoint)` to be equivalent to `if (false)`, but we should still warn on it.

**Comment by eernstg** [comment]
https://github.com/dart-lang/sdk/issues/50483 brings up yet another impossible match: `case double.nan:` (see also https://github.com/dart-lang/language/issues/2587).

We could consider dealing with the very simple cases separately:

- `case ... double.nan ...:` is always an impossible match when `double.nan` occurs such that it must be equal to anything. 
- `case Never():` is an impossible match.
- `case T():` is an impossible match when the scrutinee has a sufficiently restricted type `S` (it is `final`, or it is some type like `int`/`double`/`bool`/... that has a known set of subtypes), such that we can conclude that `T` and `S` have an empty intersection. Record types with a different shape is a good example here.

The point is that this kind of situation can be detected and reported for each case in isolation, which means that it could be useful to address it independently of the general exhaustiveness check.

**Comment by lrhn** [comment]
We could, and probably should, say that we always cache with a single pattern too, so:
```dart
if (e case (int x, _) & (> 4, var y)) ...
```
only reads `.$0` once. 

We have defined the functionality for switches, so that it should cache for a single-case switch. 
I don't think the `if`-`case` should work *differently* from a single-case switch.

It might even make sense in irrefutable contexts, when it's possible to read the same property more than once:
```dart
var Foo(x: var x1, x: var x2, ...) = foo;
```
Not really useful (just do `x: var x1 & var x2`), but also not (I think) disallowed. 
There is no reason to *not* cache, since we have already defined the functionality.

In a single, irrefutable pattern, I'm certain we can inline all the caching, and not use late variables.
We should also optimize our late variables for switch cases, to avoid unnecessary overhead, but I guess that'll be a back-end concern.

**Comment by munificent** [comment]
> We could, and probably should, say that we always cache within a single pattern too, so:

We can and do. :)

> I don't think the `if`-`case` should work _differently_ from a single-case switch.

It doesn't. It will cache within that one pattern. But we don't cache across a *chain* of `if-case` statements. In principle we *could* but, like, just use a switch statement if that's what you want.

**Comment by lrhn** [comment]
I don't think I want chaining across different `if`s. While convenient in the trivial case, I fear that it's going to get complicated the moment any variable in the patterns *might* change. 

The `switch` is safe because all the patterns work on the same *value*. The moment you have
```dart
if (x case p when e) { 

} else if (x case p2 when e2) {

}
```
we need to be absolutely sure that no change has come to the variable `x` between those two reads. Since `e` can call arbitrary code, that gets complicated fast, for anything that is not a local variable. I'd rather not try to specify when we *can* safely chain patterns, because they run on (some of) the same values.

**Comment by munificent** [comment]
Closing this in favor of the more general #2894.

**Comment by eernstg** [comment]
Hmmmm, I think we should keep this one open after all: #2894 is concerned with cases where `c == e` is guaranteed to evaluate to false, based on the static type of `e` and on the knowledge that `c` is constant (so we know the exact type). In particular, #2894 allows the case in `switch (e) { case c: ... }` to be flagged as unreachable.

This issue is different in several ways. For example, it includes cases where a record scrutinee and a record pattern have a different shape (it can be used to flag the case in `switch ((1, 2)) { case (_, _, _): ... }` as unreachable).

This issue also mentions the situation where it is known that the intersection of two types is empty, and that's yet another case (which can be used to flag the case in `switch (a) { case B(...): ...}` as unreachable, given that `a` has static type `A`, and given that the intersection of the types `A` and `B` is known to be empty).

**Comment by munificent** [comment]
Yeah, there are other cases too:

```dart
switch (123) { // int
  case [var x]: print('wat'); // No instance of int will ever implement List!
}
```

Likewise map patterns and object patterns on unrelated sealed types. Basically any pattern that does a type test and where we can tell it's not possible for there to be a subtype of the matched value and the tested type.
