### ISSUE TITLE
Why top types satisfy an `Object` type bound?

### ISSUE THREAD

**Issue by shilangyu** [dart-lang/language#2644]
I tried to find an explanation in the [dart spec](https://spec.dart.dev/DartLangSpecDraft.pdf) as to why the following is happening, but I found nothing. By a top type I mean `Object`, `dynamic`, `void`, etc, as defined in section _15.2 Super-Bounded Types_ of the spec (all supertypes of `Object`).

Let `O` be some class with a type argument with a bound `Object`:

```dart
class O<T extends Object> {}
```

Now, obviously, I cannot construct an instance with `T=dynamic`, since `dynamic` can for example represent a nullable type and the type bound disallows that:

```dart
final o = O<dynamic>(); // does not work, good
```

But, I am able to use `T=dynamic` if I am using `O` as a type:

```dart
void func(O<dynamic> o) {} // works
Type a = O<dynamic>; // works
```

Since we can never construct an instance with such a bound, this system seems sound. But what is the motivation of this behavior? Providing a supertype of `Object` gives no advantage since it is only broadens the bound which cannot be satisfied anyways.

I speculated that maybe types are just contravariant, but this does not work for user defined ones, only for `Object`:

```dart
class A {}
class B extends A {}
class C<T extends B> {}

void main() {
  final b = C<A>; // fails
}
```

**Comment by lrhn** [comment]
What you see is a "super-bounded type".

The class `O<T extends Object>{}` does not allow any instances to be created with a type argument which is not a subtype of `Object` (so, only non-nullable types). That's because all the member implementations of `O` can, and do, rely on `T` being non-nullable. Allowing a non-nullable type argument would be *unsound*.

The type, on the other hand, has no implementations to worry about. The type `O<dynamic>` *works* as a type. It's a supertype of `O<int>`. Any actual instance of `O` will be a subtype of `O<dynamic>`, and that's OK.

Dart doesn't allow just *any* type argument for a super-bounded type. There are rules for which types count as proper super-bounded types, but using `dynamic` as a replacement generally works.
In the last example, `final b = C<dynamic>;` would work.

The reason for having super-bounded types in that language is that not all class types would otherwise have a shared super-type.
Example:
```dart
class C<T extends C<T>> {}
```
If you just write `C x;`, which you otherwise can, the language needs to find some instantiation of `C` to make the declaration valid. There is nothing here you can safely instantiate `C` with, so that's a problem.
The solution was to allow `C<dynamic> x;` to be valid. It's a supertype of all `C` instantiations. It's a valid type. You can't possibly create an *object* of that type, but that's only a problem when you create objects, which you don't here.

So, super-bounded types exist to allow the language to handle un-instantiated generic types, even if they have no concrete and expressible bound.

**Comment by shilangyu** [comment]
Thank you for this thorough answer. Indeed, looks like the chapter I pointed to exactly explained this reasoning and motivation :sweat_smile: . I failed to extract this information. Thank you for clearing this up!
