### ISSUE TITLE
Abstract interface type not promoted, requires `as`  typecast

### ISSUE THREAD

**Issue by jmagman** [dart-lang/language#2666]
In this example, class `Bar` implements two abstract classes, `Foo` and `Baz`.  `Foo` defines a property.  A conditional checking `bar is Foo` does not promote `bar` to a `Foo`, and there is a `undefined_method` compilation error when the `Foo` property is accessed.

```dart
abstract class Foo {
  String get name;
}

abstract class Baz {
}

class Bar implements Foo, Baz {
  @override
  String get name => 'Bar';
}

void test() {
  final Baz bar = Bar();
  // works
  if (bar is Foo && (bar as Foo).name != null) {
  }
  // error: The getter 'name' isn't defined for the type 'Baz'.
  if (bar is Foo && bar.name != null) {
  }
}
```

**Comment by lrhn** [comment]
Dart promotion can only *promote* to a subtype of the original type. The type `Foo` is not a subtype of `Baz`, so the `bar is Foo` check gives `true`, but it doesn't promote the `bar` variable. To make that variable have type `Foo`, it needs to forget that it has type `Baz`, because it can't just be both. The promotion won't look for some subclass which is both, it will only promote to the type being checked for, and here it can't.

If you do `bar is Bar`, it will work.
