### ISSUE TITLE
Invocation key of list subpatterns regarding rest potential mistake

### ISSUE THREAD

**Issue by Michael35699** [dart-lang/language#2669]
Link:
https://github.com/dart-lang/language/blob/master/accepted/future-releases/0546-patterns/feature-specification.md

> Let `e` be `i : ("tail[]", [index])` where `index` is the zero-based index of this element subpattern.
> 
> *Note the "tail" in the invocation key name. This is to distinguish elements after a rest element at some position from elements at the same position but not following a rest element, as in:*
> 
> ````dart
> switch (list) {
>   case [var a, ..., var c]: ...
>   case [var a, _,   var d]: ...
> }
> ````
> *Here, `c` and `d` may have different values and `d` should not use the previously cached value of `c` even though they are both the third element of the same list. So we use an invocation key of "[]" for `c` and "tail[]" for `d`*.

If I understand this correctly, then shouldn't the last sentence be reversed? Since `c` proceeds a rest, it should have "tail[]" and `d` be the regular "[]"?

**Comment by lrhn** [comment]
It's interesting that the read of `d` *could* use the read of `c`.

Because it comes after a check of `list.length == 3`, we know that `list[2]` and `list[list.length - 1]` is the same value,
so the `var d` could use the same late variable as `var c`.
The only problem is that if the second pattern fails anyway, perhaps because of a `when` clause, any later read of `list[2]` in a later pattern might not see the value as already read, because it cannot assume that the length is `3`.

Maybe, after any successful exact length check, we can conflate positive and negative-from-end indexing caches, use whichever is already available, and *fill in the other*, so that all future reads of the same field will be already cached.

It's somewhat harder to define, probably impossible to desugar with just `late` variables.

Consider:
```dart
switch (l) {
  case [_, 2, ..., var v1] when false: ...
  case [1, _, var v2, ...] when false: ...
  case [_ ,_ var v3] when maybe(): ...
  case [..., var v4]: ...
}
```
When reaching the third case, and recognizing that we have a list of length 3, we may have read either `list[2]` into `v1` or `v2` or both or neither, depending on the first two values of the list.

If we could turn getting the value for `v3` into:
```dart
  late _cacheV1 = _list[_list.length - 1];
  late _cacheV2 = _list[2];
  late _cacheV3 = (){
    assert(list.length == 3);
    var result;
    if (?_cacheV1) {  // is _cacheV1 initialized
      result = _cacheV1;
      if (!?_cacheV2) _cacheV2 = result;
    } else {
      result = _cacheV1 = _cacheV2; // Initialie _cacheV2 if needed
   }
   return result;
  }();
```
(A shorter way to do it would be nice, let's say we introduce an operator `=?=` which takes two late variables, and makes sure they both gets initialized to the same value, using the value of the first if both or neither is already initialized, then it's just `late _cacheV3 = _cacheV2 =?= _cacheV1;`.)

It might not be worth it, but it should be technically possible.
(Defining the rules for when to combine would be a lot of "fun" too. )

An alternative could be to define the variables as:
```dart
late _cacheV1 = _list.length == 3 ? _cacheV2 : _list[_list.length - 1];
late _cacheV2 = (_list.length == 3 && ?_cacheV1) ? _cacheV2 : _list[2];
```
We'd probably have to check for every possible exact length that occurs in the switch, if we wanted all the optimizations.

Another option is to cache list elements in a list with the same length as the original. That might be wasteful if most elements aren't checked.

**Comment by lrhn** [comment]
Chatted with Johnni, and if the caching is partially dynamic (which it might have to be if lowering happens before `fromEnvironment` constants are available), then `list[2]` and `list[list.length-1]` could end up both checking the `list[2]` cache.

That's assuming an implementation, but so is assuming that they *cannot* share a cache.

It comes back to whether we want to ensure one specific behavior, or we want to allow implementations to optimize away reads that they can definitely detect as unnecessary.

Defining something that's really smart gets tricky, but not necessarily impossible.

Take:
```dart
late T list_2_cache = /* only ever gets here after checking length > 2, so list_length must have been read */
    list_length == 3 ? (has_list_negative_1_cache ? list_negative_1_cache : (list_negative_1_cache = list[2]))
           : // other relevant lengths that we have negative matches for  ... else
               list[2] /* and update _has_list_2 */;
```
Very wordy, but maybe a smart compiler can compile into, say, a binary decision diagram implementation that carries all known-so-far information along the edges, and unifies when it definitely knows something more.
