### ISSUE TITLE
[Patterns] Exhaustiveness definitions for spaces for Null-assert and and cast-binder are incorrect?

### ISSUE THREAD

**Issue by leafpetersen** [dart-lang/language#2681]
The definition of [how to lift patterns to spaces](https://github.com/dart-lang/language/blob/master/accepted/future-releases/0546-patterns/exhaustiveness.md#lifting-types-and-patterns-to-spaces) says the following:

```
*   **Null-assert or cast binder:** An object space of type `top`.
```

This seems wrong to me, because it doesn't account for the sub-pattern.  That is, I think "An object space of type `top`" implies that the case matches all objects, but that's not necessarily the case.  For example:

```dart
    Card? card;
    switch (card) {
      case Jack(oneEyed: true)!: ...
    }
```

The code above matches `null`, or a one eyed Jack, but not any other card.

For null check matcher patterns, the corresponding example above:

    ```dart
    Card? card;
    switch (card) {
      case Jack(oneEyed: true)?: ...
    }
    ```

is specified to yield:

```
    Card(this: Jack(oneEyed: true))
```

I'm not sure I understand yet the motivation for the extra indirection through `Card`.  It seems to me that this can be modeled as just `Jack(oneEyed: true)`, but I'm not sure.

In either case, it seems to me that perhaps what we want for the null-assert case is something like:

```
*   **Null-assert** The union of the space for the constant `null` and the space of the lifted sub-pattern.
```

For cast patterns, I'm not sure what to say.  It may just be best to leave this as top.  Technically, it seems like it should be something like the union of the lifted sub-pattern and `top - type` where `type` is the lifted sub-pattern of the target type of the cast?

cc @munificent @eernstg @lrhn @kallentu @stereotype441 @jakemac53 @natebosch

**Comment by munificent** [comment]
> The definition of [how to lift patterns to spaces](https://github.com/dart-lang/language/blob/master/accepted/future-releases/0546-patterns/exhaustiveness.md#lifting-types-and-patterns-to-spaces) says the following:

### Null-assert

> 
> ```
> *   **Null-assert or cast binder:** An object space of type `top`.
> ```
> 
> This seems wrong to me, because it doesn't account for the sub-pattern. That is, I think "An object space of type `top`" implies that the case matches all objects, but that's not necessarily the case.

Yeah, I think this is just outdated. If I remember right, at the time I wrote this, cast patterns only contained an identifier to bind and not an arbitrary subpattern. I'm not sure about null-asserts but it may be something similar, or maybe I just got that wrong.

> `The union of the space for the constant `null` and the space of the lifted sub-pattern.`

That sounds right to me.

### Cast

> like it should be something like the union of the lifted sub-pattern and `top - type` where `type` is the lifted sub-pattern of the target type of the cast?

OK, it took me a while to wrap my head around this. I think we want:

```
(lift(matchedValueType) - list(castType)) | lift(subpattern)
```

This is weird because in other cases when lifting a pattern to a space, we don't care about any static type context. But consider:

```dart
sealed class Card {}

class Pip extends Card {}
sealed class Face extends Card {}

class Jack extends Face {}
class Queen extends Face {}
class King extends Face {}

Card card = ...
switch (card) {
  case (Queen _) as Face: ...
  case Jack _: ...
  case King _: ...
}
```

If we do `top - Face | Queen`, we get:

```
top - Face = top  // Since top isn't sealed.
top | Queen = top // Top covers everything.
```

That would show the second two cases as unreachable. But that's not true. If the card is a non-Queen face card, they will be reached. Instead, we want:

```
Card - Face | Queen = Pip | Queen
```

Then when we union that with the other two cases, we get:

```
Pip | Queen | Jack | King
```

Which covers all the sealed subtypes and is exhaustive.

### Null-check

> I'm not sure I understand yet the motivation for the extra indirection through `Card`. It seems to me that this can be modeled as just `Jack(oneEyed: true)`, but I'm not sure.

In that case, yes, but we can't always discard the outer non-nullable type. Consider:

```dart
Card? card;
switch (card) {
  case (Jack? _)?: ...
}
```

Here, if we just do `(Jack? _)`, we've lost the null check. I think what we really want is the intersection of the lifted space for the non-nullable matched value type and the space for the subpattern.

The weird object-space-with-this-inside is a way to model that. I think at one point, the algorithm did support calculating the intersection of two spaces and we could rely on that. But it was only used to see if the intersection was empty, so I simplified it down to just a predicate.

We could probably define that. Or at least define the limited thing we need here which is just the intersection of a space *for just a type (i.e. no fields)* with some other space (which may or may not have fields).

**Comment by leafpetersen** [comment]
> ### Null-check
> > I'm not sure I understand yet the motivation for the extra indirection through `Card`. It seems to me that this can be modeled as just `Jack(oneEyed: true)`, but I'm not sure.
> 
> In that case, yes, but we can't always discard the outer non-nullable type. Consider:
> 
> ```dart
> Card? card;
> switch (card) {
>   case (Jack? _)?: ...
> }
> ```
> 
> Here, if we just do `(Jack? _)`, we've lost the null check. I think what we really want is the intersection of the lifted space for the non-nullable matched value type and the space for the subpattern.

I think maybe this reflects a missing piece around types, but I'm not sure.  As specified right now, the lifting of types to spaces is: 

```
Static type: An object space with that type and no fields.
```

Which suggests that we have `object` spaces for things like `Card?`.  That seems odd to me, but...maybe?  Is that the intent?  It seems to me that maybe what we want is to say something like:

```
Nullable type `T?`: The union of the space for the constant `null` and the object space for `T`.
```

```dart
 Card? card;
 switch (card) {
   case (Jack? _)?: ...
 }
```

I think now that makes your example work out, because the inner pattern space becomes `Jack() | null` and the interpretation of `p?` becomes `lift(p) - null`, which is `Jack()`, which is what you want?  I'm not 100% sure about this, I'm still wrapping my head around this.  But it feels like:

```dart
Card? card;
  switch(card) {
     case Jack():
}
```
and

```dart
Card? card;
  switch(card) {
     case Jack()?:
}
```

are doing exactly the same test, so why would they take different paths?

Also, I'm not 100% sure where the `this` parameter gets accounted for.  Subtraction doesn't account for it.

**Comment by munificent** [comment]
I've completely rewritten the spec, so I *think* this is no longer valid.
