### ISSUE TITLE
Please document, the function argument evaluation sequence, of dart

### ISSUE THREAD

**Issue by gintominto5329** [dart-lang/language#2683]
Hello,

Currently, im writing, a somewhat low-level library, in dart,
I have a few questions, which i think only insiders can know,

### 1. The sequence of evaluation, of function arguments, in dart, like 
```
  print ( int  i ) {  print( i );  }

  func ( prnt(1),  prnt(2),  prnt(3) );
```
Among the above arguments which would be evaluated(here printed) first, and which, at last,
In c/cpp, this is undefined generally, javascript does [left-to-right](https://stackoverflow.com/questions/8405989/what-is-the-order-of-evaluation-for-function-arguments-in-javascript),

### 2. During an assignment, which side is evaluated first, like:
```
  list [ i++ ] = lst [ i ];
  list [ i++ ] = lst [ j++ ] = ls [ j ];
```
Is this possible,

### 3. Is there any way, to declare and define, a list of non-null objects, without using `add`, nor `generate`, nor `filled`, someting like `late`, currently i practice a very bad and lengthy approach, i cannot use `generate`, as it would lead to a lot of if-else conditions:
```
const int length = 9;

  final List<classObject> list;
  {
    final List<classObject?> _list = List<classObject?>.filled(length, null, growable: false);

    int i = 0;

    _list[i++] = // ...

    _list[i++] = // ...

    while (i < length) {
      _list[i++] = // ...
    }

    list = List<classObject>.generate(
      length,
      (final int index) {
        return _list[index]!;
      },
      growable: false,
    );
  }
```

### 4. Does `GrowableList` has better performance than `FixedSizeList`, if i never use `add`,

Please provide answers, applicable for both dart-runtime and dart-to-javascript ( dart2js ), hence **definitive**,

thanking you,

**Comment by lrhn** [comment]
I am fairly sure the evaluation order is defined by the language specification.

## 1. Function arguments

Evaluated in source order (earlier in source means evaluated earlier). 
That's left-to-right on the same line, top-to-bottom if using multiple lines, etc. So "source order" is the shortest way to say it.

For method invocations, the receiver is evaluated before the arguments, so `e1.foo(e2, e3)` evaluates `e1`, `e2` and `e3` in source order.

This also applies to operators, so `e1 + e2` evaluates `e1` first to the receiver object, then `e2` as the only argument to
the `operator+` method.

Same for `e1[e2]` which is just treated as `e1.operator[](e2)`.

The only user-defined ternary operator is `operator[]=`, and `e1[e2] = e3` is also evaluated in source order, `e1` first to a receiver, then the arguments `e2` and `e3` in source order, then `e1`'s `operator[]=` is called with those arguments.

The only discrepancy from source-order evaluation is that an expression of the form `e1.foo(e2)` where `foo` is a getter (returning a function), will evaluate `e1`, then `e2`, and only then the `<value of e1>.foo` getter (and then call the function).
(I don't remember the reason for this it off-hand, but probably for consistency and to allow more efficient implementations).

## 2. Assignment

Source order too. Some details depends on the complexity of the left-hand-side, like caching of of subexpressions which are used more than once in a composite assignment like `e1[e2] += e3`.

A composite assignment (read + operator + write) like that is expanded into something like `e1[e2] = e1[e2] + e3`, and evaluated left-to-right, but the values of `e1` and `e2` are cached so the second occurrence reuse the first ones' values. 
Like: `var tmp1, tmp2; ... `(tmp1 = e2)[tmp2 = e2]  = tmp1[tmp2] + e3` (just properly typed).

For a plain assignment like `e1.foo = e2` it's plain source order, `e1` first then `e2`, then invoke the `<value of e1>.foo` setter.

## 3. No default lazy list builder.

There is no provided and easy way to lazily fill in a list of non-nullable values.

The recommended approach to creating a non-nullable list is having the values before creating the list, either a literal, `List.filled` or `List.generated`, or building it in a `List<T?>` and then either use `List.cast` or `List.from` to wrap or create a new list with the non-nullable type.

It's possible to create something like a `ListBuilder<T>` which starts out empty, and lets you assign to it, and then it builds the `List<T>` for you when it's all filled out, but it's going to be just a wrapper around calling `List.from` or `List.cast` anyway.

(It's possible that the platform libraries could create such a builder that doesn't copy at the end, but just changes the type on the backing store directly, and removes it from the builder. We don't currently have such functionality.)

## 4. Performance, it's is impossible to say. 

Whether a growable list is as efficient as a fixed length list, whether added to or not, is not not something we make promises about.
It might differ between platforms, and might change on each platform as we add optimizations. And we might optimize different code in the same code in different ways, so it's not even guaranteed to have the same answer within the same program.

Asking which has the best performance prompts the return question: How are you using it?

There might also be differences between JIT native and AoT native, as well as between native and web.
And on WASM, when we get there.

I don't actually know the answers for *any* platform, not for sure. 
I can guess, but the only real answer is a benchmark which matches the behavior of your actual program, because the truest answer is "it depends".

In general terms

**On the web**, both are represented by a JavaScript `Array`. The fixed length list one has an extra property set, to mark it as fixed length. I don't know if that affects performance by risking polymorphism. 
Have to ask a Dart2JS developer to be sure. @rakudrama?

**On JIT native**, a growable list wraps a fixed-length list (the "backing store") which can have more space than the actual elements.
So, it definitely costs a little more *space*. I'm sure member access on growable lists is suitably optimized, so the extra layer of indirection won't be noticeable when doing real work as well. That may only work if the access is monomorphic, so you might want to be careful to not mix fixed-length and growable lists. (Although the VM has been known to optimized list polymorphism in some places, like for typed data lists. It might do so for normal lists, either today or in the future. Only the VM engineers know for sure.) @mkustermann?

**On AoT native**... I really have no idea. I'm guessing it uses the same wrapped fixed-length list implementation, but I don't know which optimizations might be applied by the compiler if it can see that a growable list isn't added to and doesn't escape. (Escape analysis can be hard, so I'd probably assume that we don't do it, and program accordingly.)

**All in all**, my educated guess is that a fixed list is probably not slower than a growable list on any native platform, but that mixing them _might_ make both slower due to polymorphism.

**Comment by gintominto5329** [comment]
Thanking you, 
For such a high value answer, 

As expected from the team behind the mighty flutter.dart engine
