### ISSUE TITLE
Add a officially denoted way to yield the control to other asynchronous code.

### ISSUE THREAD

**Issue by Cat-sushi** [dart-lang/language#2689]
[The specification](https://spec.dart.dev/DartLangSpecDraft.pdf#Await%20Expressions) doesn't say that `await` always introduces a new microtask or a new event.

The specification says that `await null` is a syntax suger of `await Future.value(null)`, so I checked the [API document](https://api.dart.dev/stable/2.18.1/dart-async/Future/Future.value.html), then. 
But, the API document also doesn't say that it does.

On the other hand, [a news letter](https://github.com/dart-lang/language/blob/master/archive/newsletter/20170915.md#migration) pointed from a note of the [Language tour #Handling Futures](https://dart.dev/guides/language/language-tour#handling-futures "Language tour | Dart") suggested that `await null` introduces a new microtask.

It is important to know a confident way to yield control to other asynchronous code, in some context such as developing `Mutex`.

**Comment by eernstg** [comment]
> The specification says that `await null` is a syntax suger of `await Future.value(null)`

That's not entirely true, it says that `await null` is evaluated by evaluating null (yielding null), checking whether it's an instance of `Future<Null>` (it isn't), creating the future `Future<Null>.value(null)`, and then suspending the execution until some point in time where that future has been completed.

The specification never talks about the implementation of scheduling (for example, it never mentions microtasks), but there must be some mechanism that enables suspension of the current execution to take place, and also restarting that execution later. The way these things are done in detail is an implementation specific part of the language.

> It is important to know a confident way to yield control to other asynchronous
> code, in some context such as developing `Mutex`.

The fact that the current execution is suspended at the time mentioned above should suffice. You _can_ rely on `await null` to cause a suspension.

Of course, the level of detail in the specification could have been different. For instance, it could have mentioned the scheduler and the notion of microtasks (and whatever else we might use in an implementation), it could have specified that there must be separate stacks for separate asynchronous computations, or it could specify the opposite (e.g., that the asynchronous control flow must be achieved by lowering the body of `async` functions to a specific kind of code that never uses `await` or `yield`), etc.etc.

However, the more detail we add to the specification, the less freedom we have to use different implementation techniques (possibly varying over time, when someone comes up with a brilliant way to do things, or varying between configurations, e.g., doing it differently with the VM and on the web). Hence, it isn't necessarily always an improvement to specify something in more detail.

I hope you can write the code you need to write, relying on the properties that we have actually specified at this point.

**Comment by Cat-sushi** [comment]
Do you mean that the newsletter says that `await null` is the migration method, at the same time we must not trust that?

**Comment by eernstg** [comment]
The newsletter is from 2017, it is an informal document, and the [section you mentioned](https://github.com/dart-lang/language/blob/master/archive/newsletter/20170915.md#migration) is about a different change to the language semantics. So it isn't the current source of truth about the language semantics, and certainly not the semantics of `await` expressions, but it may still be interesting as a source of information about the evolution of the language at that time.

The section is about a change where the execution of an async function body does not immediately suspend. The previous semantics was that an async body would always suspend immediately; the new semantics was that the execution would proceed synchronously from the start of the function body, and it would only suspend when (and if) it reached an `await` expression.

The recommended migration is to simply add `await null;` at the very beginning of each async function body. In real life this means each async function body which is considered vulnerable to this change&mdash;if your application runs perfectly fine after the change then there's no need to do anything. However, if it suddenly has bugs that seem to be caused by a new and unexpected scheduling of asynchronous execution then adding `await null;` to some or all async function bodies would reestablish the old semantics. The reason why you should add `await null;` is exactly that this will force a suspension to occur. 'Will', not 'may'.

> Do you mean that the newsletter says that `await null` is the migration method,
> at the same time we must not trust that?

The newsletter doesn't use the word 'trust', but I think you are referring to [this section](https://github.com/dart-lang/language/blob/master/archive/newsletter/20170915.md#relying-on-async) where they explain that you can no longer rely on async function bodies to return immediately (they can now run an arbitrary amount of computations synchronously before they encounter the first `await`). So that's one thing you can't trust: Your invocation of a function whose body is `async` is not guaranteed to return immediately.

(But it doesn't sound like that was the crucial property for you, anyway.)

They do mention one more thing: In the _old_ semantics you couldn't rely on getting the first statement(s) of the async function body executed before it returned (because it would return immediately). That was a source of bugs, so the new semantics was motivated by the ability to avoid many instances of that kind of bug.

So this is not something that you can't trust in the new semantics, this was something that developer would at times assume about the _old_ semantics even though it wasn't true; but it is indeed true with the new semantics (vaguely, it's not really a guarantee of anything: you can still have the kind of bug that they describe if the thing you think has already happened when the function with the async body returns comes after the first `await` expression).

So you shouldn't have to worry about anything they say in that newsletter. It doesn't in any way contradict the statement that evaluation of an await expression will suspend, every time.

**Comment by Cat-sushi** [comment]
> The newsletter is from 2017, it is an informal document,

Why does the formal document, the language tuer, reffrer the newsletter?

>the [section you mentioned](https://github.com/dart-lang/language/blob/master/archive/newsletter/20170915.md#migration) is about a different change to the language semantics.

Where is the latest specification?

>  (they can now run an arbitrary amount of computations synchronously before they encounter the first await). So that's one thing you can't trust: Your invocation of a function whose body is async is not guaranteed to return immediately.

Yes, I knew.

> In the old semantics you couldn't rely on getting the first statement(s) of the async function body executed before it returned (because it would return immediately).

Now, what should we rely on?

**Comment by eernstg** [comment]
The language tour is an informal document, too. But it sounds like there's a need to update the language tour: I can't imagine that a reference to that newsletter (and that language semantics change) is helpful today.

> Where is the latest specification?

The [language specification](https://dart.dev/guides/language/spec) is the location where the entire language is specified. However, the language is updated frequently, and the newest features are specified in so-called feature specification documents, [here](https://github.com/dart-lang/language/tree/master/accepted). So the newest ruleset is obtained by starting with the language specification, and then taking all the accepted feature specifications into account.

The most typical situation is that you're looking for rules about a specific topic. If the language specification does not say anything about this topic (because it's a new feature, typically) then check out the feature specifications. Of course, the feature specifications depend on a very large number of details about the language that are specified in the language specification, so you may need to look up stuff in the language specification even in the case where you are reading about a new feature in a feature specification.

It would have been nice if we had had the time to integrate all feature specifications into the language specification immediately when they are released, but there's a lot of emphasis on getting new features specified and implemented. So, unfortunately, you do have to consider the language specification plus a bunch of feature specifications in order to find the most recent answer to any given question about the language.

> Now, what should we rely on?

An invocation of a function whose body is `async` will proceed synchronously until it encounters the first `await` expression (which could be in the body of some other async function that this one called).

Also, await expression evaluation _will_ suspend.

**Comment by Cat-sushi** [comment]
> So, unfortunately, you do have to consider the language specification plus a bunch of feature specifications in order to find the most recent answer to any given question about the language.

Yes, I knew.

> An invocation of a function whose body is async will proceed synchronously until it encounters the first await expression (which could be in the body of some other async function that this one called).

As I said, I knew.

> However, the language is updated frequently, and the newest features are specified in so-called feature specification documents, [here](https://github.com/dart-lang/language/tree/master/accepted). So the newest ruleset is obtained by starting with the language specification, and then taking all the accepted feature specifications into account.

I can't find the current semantics for yielding the control to other asynchronous code, [there](https://github.com/dart-lang/language/tree/master/accepted).

**Comment by eernstg** [comment]
> Yes, I knew.

Sure, but 'Now, what should we rely on?' sounded like something wasn't clear..

> I can't find the current semantics for yielding the control to other asynchronous code

That's true, and you can't find the semantics of looking up URIs denoting imported or exported libraries, or the actual representations of objects of type `int` (including the fact that we may have 3-4 different kinds in the same program execution), or the details about when garbage collection occurs, or how/when/how-much memory your program execution will allocate and deallocate, etc.etc.

Practical programming language specification will have to stop at some point, and, as I mentioned, it is not simply the case that "more detail is better".

But what is it that you need to know which isn't already covered by the fact that you _do_ know on which occasions the execution will be suspended?

**Comment by Cat-sushi** [comment]
> Practical programming language specification will have to stop at some point, and, as I mentioned, it is not simply the case that "more detail is better".

I knew.

> But what is it that you need to know which isn't already covered by the fact that you do know on which occasions the execution will be suspended?

How can I make [my code](https://pub.dev/documentation/simple_mutex/latest/simple_mutex/Mutex/lock.html) trusted?

**Comment by eernstg** [comment]
> How can I make [my code](https://pub.dev/documentation/simple_mutex/latest/simple_mutex/Mutex/lock.html) trusted?

That's always difficult. For instance, it needs to be bug free to some extent, and that means that there is a set of expectations about the behavior (docs), and they are satisfied (to that extent, whatever it is).

However, I don't know how your lock method can be made more trustworthy by knowing and depending on anything about Dart asynchronous execution which goes beyond knowing what is already specified, in particular: in which situations the execution is suspended.

If you need to say 'microtask' or 'scheduler' then you're not gaining anything other than a buggy dependency, because we don't promise that the next platform running Dart (or the next version of any tool) will have microtasks, nor that the scheduler will work in any particular way.

**Comment by Cat-sushi** [comment]
OK,
My understanding is that,

- Nothing are promised. Even the specification would introduce breaking change.
- The specification is a formal document, but not complete.
  - language/accepted is another source of formal documents.
  - Specifications always stop at some point.
- The language tour is official but not formal.
- Scheduling is always implementation detail.
  - The newsletter is implementation detail.
  - Currently, we can rely on `await null` to suspend asynchronous cord, but it is not in spec, trusted, or promised.

**Comment by eernstg** [comment]
> My understanding is that,

That's a good summary!

I do maintain, though, that _lots_ of things are promised.

> Currently, we can rely on `await null` to suspend asynchronous cord, but it is not in spec, trusted, or promised.

In particular, this fact is actually in the language specification, [here](https://github.com/dart-lang/language/blob/b60b46caad839106e449e61c3673303af6f0fae9/specification/dartLangSpec.tex#L16003), it is trusted (meaning: any violation is a bug), and I don't know how it could be promised to a higher degree than it already is.

That said&mdash;it would be very nice to have a single language specification which includes everything and is 100% up to date. We'll probably get there when (and if) Dart gets really boring. ;-)

> denoted at same level of `scheduleMicrotask`?

You could say that library documentation is "one step less formal" than the language specification. It is not easy to change any of those, especially for platform libraries like 'dart:async' and 'dart:core', but breaking language changes are yet harder to carry out than changes to libraries.

Hence, libraries commit to a large amount of detail that the language as such does not. For example, the distinction between microtasks and other asynchronous events is made in the scheduleMicrotask documentation. However, I doubt that it would help you achieving any correctness properties that you could not have achieved without those concepts.

In particular, this documentation indicates that every computation scheduled using `scheduleMicrotask` is executed in order and before any `Timer` events, but given that you don't know which other things are executed via `scheduleMicrotask` (or in which order, except for the ones that are known to have been scheduled using code that guarantees some ordering) it is hardly possible to obtain any _relevant_ guarantees. How is your `lock` method going to be correct if you have this kind of guarantee, but it might be buggy if you didn't have it?

**Comment by Cat-sushi** [comment]
> In particular, this fact is actually in the language specification, [here](https://github.com/dart-lang/language/blob/b60b46caad839106e449e61c3673303af6f0fae9/specification/dartLangSpec.tex#L16003), it is trusted (meaning: any violation is a bug), and I don't know how it could be promised to a higher degree than it already is.

In case of `await null`, the `Future` is completed from the beginning. isn't it?

**Comment by eernstg** [comment]
> the `Future` is completed from the beginning. isn't it?

That's true, but the suspension occurs unconditionally anyway.

You could say that an implementation could be conforming to the specification, and it could still choose to schedule the current computation again, every time, whenever it evaluates `await null` (or: any expression of the form `await Future<T>.value(someExpressionOfTypeT)`). This would make it work essentially in the same way as an execution where there is no suspension at this point. However, even though it might look like a useful rule if we say "at suspension of a computation _c_, the scheduler must choose to resume a computation which is different from _c_, if any". But I doubt it is going to make any particular correctness property of a program easier to prove.

You could also say that a conforming implementation of Dart could emulate a CPU to run some translated instructions, and it could run that virtual CPU with the clock frequency 0 Hz. Bad, but not likely to happen. It is also somewhat hard to protect oneself against this kind of problem: we can't possibly come up with all those useless approaches that a conforming implementation _could_ employ. This is also part of "stopping at some point" when something is being specified.

**Comment by Cat-sushi** [comment]
Do you mean that there is no way to suspend current code denoted at same level of `scheduleMicrotask`?

**Comment by rrousselGit** [comment]
Personally I've been doing `await Future<void>.value()` instead of `await null`.

Is there a reason why `await null` would be preferrable?

**Comment by Cat-sushi** [comment]
@rrousselGit 
I don't stick to `await null`, but `await null` is almost equivalent to `await Future<Null>.value(null)`, and `await Future<void>.value()` doesn't solve the problem, does it?

**Comment by rrousselGit** [comment]
Ignore me, I misunderstood the discussion.

**Comment by Cat-sushi** [comment]
> I'm afraid I'll have to say that I can't contribute anything further in this discussion.

I'm sorry, I think I'm incapacious.
I just want a official document other than this thread.

**Comment by lrhn** [comment]
If you want to be absolutely sure that you delay until after a later microtask, then:
```dart
await Future<void>.microtask((){});
```
That's the one future constructor which explicitly promises to use microtasks.

**Comment by Cat-sushi** [comment]
@lrhn 
That makes sense.
Thank you very much.
