### ISSUE TITLE
Let a list pattern match an `Iterable`?

### ISSUE THREAD

**Issue by eernstg** [dart-lang/language#2699]
Section [Type checking and pattern required type](https://github.com/dart-lang/language/blob/master/accepted/future-releases/0546-patterns/feature-specification.md#type-checking-and-pattern-required-type) again: in the rule about list patterns, we have the rule 'Else if `M` implements `List<T>` for some `T` then `E` is `T`'. Is there any particular reason why it isn't sufficient to require that `M` implements `Iterable<T>`? This seems to allow us to dig into an iterable in a situation where that should be well defined and possibly useful.

```dart
void main() {
  Iterable<int> it = ...;
  switch (it) {
    case []: print('Empty!');
    case [1, 2, 3]: print('123!');
  }
}
```

The matching process could start by invoking `toList()` and then proceeding as with a list.

**Comment by munificent** [comment]
> The matching process could start by invoking `toList()` and then proceeding as with a list.

I would rather the user call `toList()` themselves so that they *know* it's happening. Places where you have an object or type `Iterable` but *not* `List` are often places where the sequence is lazy, or the iteration has side effects. Given that the destructuring and caching behavior is already fairly subtle, I think it would just add more user confusion if we allowed `Iterable`s to flow into there (and silently copied them to a list). If we were to do this, I'm certain we'd get a flurry of follow up bugs about:

1. Does it call `toList()` if its matched by a wildcard or variable pattern that doesn't need to copy it?
2. If a variable or wildcard matches on the iterable, what is the resulting type? `Iterable` or `List`? If the latter, it means we're forced to always call `toList()`.
3. Does a `[...]` pattern need to call `toList()` at all? Should it?

I think we'd just end up regretting the extra complexity. Conceptually, matching works best when it operates on data structures that feel fixed and immutable. `Iterable`s to me feel like "live" objects that compute their elements.
