### ISSUE TITLE
A 'rest element' in a map pattern could be matching

### ISSUE THREAD

**Issue by eernstg** [dart-lang/language#2700]
In section [Rest elements](https://github.com/dart-lang/language/blob/master/accepted/future-releases/0546-patterns/feature-specification.md#rest-elements-1), it is stated that

> [there's no well-defined notion of a map "minus" some set of matched entries](https://github.com/dart-lang/language/blob/master/accepted/future-releases/0546-patterns/feature-specification.md#:~:text=there%27s%20no%20well%2Ddefined%20notion%20of%20a%20map%20%22minus%22%20some%20set%20of%20matched%20entries)

However, if we agree on what it means for a map to be "well behaved" then we might actually be able to compute the "rest" map: Create a copy of the given map using `Map.from`, then `remove` each key in the map entry patterns. That map would then be matched against the pattern of the rest element.

This might be slow, but presumably not slower than doing the same thing manually. So I guess the question is whether it would be useful.

**Comment by munificent** [comment]
That's not a bad idea. It's a little weird because list patterns deliberately use `sublist()` to copy the rest element from the original list in order to preserve the reified type argument. Using `Map.from()` would lose the original map's runtime type.

It's not clear to me that this is particularly valuable and we can always add it later, so moving it to `patterns-later`.

**Comment by lrhn** [comment]
> That's not a bad idea.

It is actually bad idea, mainly because `Map` provides no way to create a copy. It's not (just) about the runtime type, but about the underlying equality relation.

Lists can be copied into a standard platform list with the same elements, and it should behave basically the same. There is no relation between the elements, they just sit in their own individual cells.

Maps have an underlying equality relation. It can be *anything*. You cannot determine it from the outside, and the `Map` interface does not provide any way to create an "equivalent" map. There is no `Map<K, V> toMap()` method.
Using `Map.from` may give a map with a different equality relation (always `==`). It's no longer the same map. Some source keys may collapse into a single entry. Some source keys may no longer be equal to the pattern keys used to match them.

Until we get a `Map.clone`/`Map.toMap` which promises to have the *same* equality behavior, there is nothing we can do which will work reasonably for all maps. And we can't tell from the outside whether it will work for a map at all.

**Comment by munificent** [comment]
That's a good point. For example, if the map you're matching on is an `IdentityMap` or some `CaseInsensitiveStringKeyMap`, then calling `Map.from()` will drop that policy on the floor. I'm going to go ahead and close this, but it was a useful discussion to have.
