### ISSUE TITLE
Exhaustiveness on list patterns with negative lengths

### ISSUE THREAD

**Issue by munificent** [dart-lang/language#2701]
@stereotype441 mentioned this in a meeting and I wanted to file an issue so we don't lose track. This appears like it should be an exhaustive switch:

```dart
String test(List<int> list) => switch (list) {
  [] => 'empty',
  [_, ...] => 'not empty'
};
```

However, it's possible for neither case to match if you pass it a misbehaving implementation of `List` that returns a *negative* number for `length`.

Exhaustiveness needs to be sound. At the same time, I don't want users to have to write clearly pointless default cases when switching on lists just to handle misbehaving list implementations that will never actually reach their code. I can think of a couple of ways to handle this:

* When a list pattern calls `length` on a list, if a negative number is returned, throw a "bad list protocol" exception.
* Treat any length of 0 or less as equivalent to zero. That means an empty list pattern, or a list pattern containing only a rest element, will match a list of length 0 or less.

I lean slightly towards the first option because I like letting users known when something fishy is going on. But I could be convinced to do the latter if it's more efficient or has other desirable properties. In practice, almost no users will ever hit this case.

Thoughts?

**Comment by leafpetersen** [comment]
> I lean slightly towards the first option because I like letting users known when something fishy is going on. But I could be convinced to do the latter if it's more efficient or has other desirable properties. In practice, almost no users will ever hit this case.

I think I'd lean towards the latter.  From a code size perspective, I think that having to have code there to throw the error (or a call out to something which checks and throws) will be a small but persistent tax, and I see little actual benefit here in practice to throwing.

**Comment by lrhn** [comment]
Leaning towards the latter for me too.

The extra code to do the check won't be big. It'll be something like

```dart
late int listLength = $internal$getLength(list);
```
with 
```dart
int $internal$getLength(List<Object?> list) {
  var length = list.length;
  if (length >= 0) return length;
  throw VeryBadError("List length is negative", list);
}
```
It will only be run once per list in a pattern, because we cache the length.
Still, it's overhead with no benefit, because no real list will ever return a negative length. 
If that happens, you have bigger issues than whether an empty-list pattern matches.

If we don't throw, and just read (and cache) the negative length, we have to make sure all our patterns behave as desired when seeing a negative value for `length`.

Any pattern requiring a length greater than zero still works and rejects the list.

An `[]` pattern must check `length <= 0` instead of `length == 0`. Then we truly do cover all integers if we cover all list lengths.

A pattern of `[... p]` will not check length at all (it never needed to, but it still doesn't). 
A trailing spread pattern's `.sublist` call should be `.sublist(0)`, with no end given, so we don't have to use the negative length at all (or ever read it, if the only pattern is `[...]`).


(Same issue applies to map patterns too. We don't need the length for anything other than `==` or `>=` comparisons for maps, since we can't address maps from the back. There is no `sublist` call.)
