### ISSUE TITLE
Union types, like in typescript

### ISSUE THREAD

**Issue by topperspal** [dart-lang/language#2711]
Dart is great, and it is also **statically typed** (sometimes not convenient). For example, why enums are not always good for a simple list of options like
```dart
Toast.show("Boring enums everywhere! 😕", length: ToastLength.long);

// Here we created an enum class only for two options [short, long].
enum ToastLength { short, long }

// But this is verbose and also clutter auto-completition list in code editor.
// Can this be implemented simply like typescript typedef

typedef _ToastLength = "short" | "long";

class Toast {
  static void show(String message, {_ToastLength length = "short"}) {
    ...
  }
}

// Or bind prefered options directly in the method like this

class Toast {
  static void show(String message, {"short"|"long" length}) { ... }
}

// So we can write the method without and clutter like this

Toast.show("Now dart looks cool! 😎", length: "long");

```

This will also help library developers to reduce the types, so they don't conflict with types in other libraries.

**Comment by lrhn** [comment]
If we generalize this feature a little, it would seem that it is a way to define a "subset type":
* It introduces a (finite) type which contains only known _constant_ values of some larger shared super-type. Here the larger type is `String`, but there is no need to restrict to just that. I'd allow any container super-type and any constants  of that type with primitive equality. (Including a super-type of `Object?` and arbitrary primitive-`==` constants.)
* Allows only constant expressions with one of those values to be assigned to the type, or existing expressions of the type.

## Subtyping

The subset type is probably going to be a subtype of `Object?`. Maybe of `Object` if all the constants are non-`null`. Types don't really work in `Dart` if they are not, because generics assume an implicit bound of `Object?`.

Should the `_ToastLength` type be related to `String` or not, and if so, how?

If we don't make it as subtype of `String`, we just allow those particular constants to be assignable to `_ToastLength`, not the other direction. It's compile-time decidable whether a constant is one of those constants. You can't assign them back.(You can always do `as String` anyway.)

If we make `_ToastLength` a subtype of `_String`, then the toast lengths can be assigned back to `String`. Still want the assignability of constants in the other direction.

If we make `_ToastLength` a supertype of `_String`, then any string can be assigned to `_ToastString`, which we probably do not want, because then we can't prevent other values. So no relation or subtype only.

I'd go for being a subtype.

Then it's also clear that you can use any member of the supertype on every value.

## Subtype checking

Can you do `anyValue is _ToastType`? If you can, it requires comparing the value to a finite set of constants, which all have primitive `==`, which usually just means identity checks. Maybe compilers can do even better by using hash codes to narrow the constants to compare to, but that can easily be more expensive than just doing five identity checks.
Definitely possible, but different from any other type check, so implementations will need a special code path for it.

If you cannot, then things get weird. You probably cannot have a `List<_ToastLength>` because `List.add` is coviariant, so it does an `is E` check on the argument.
So, probably do need to allow `is` checks, which will be more complicated than usual type checks.
And it requires reifying the type at runtime, so it can be bound to the `E` type variable of `List`.

The alternative is to not reify the type at runtime, and just erase it to the shared supertype. At that point, there is no longer any way to ensure that another string doesn't get "cast" to `_ToastLength` at runtime, and the compiler cannot assume switches over all the official values to be exhaustive. (Which it otherwise can, like a proper enumerated type.)

I'd recommend reifying the type, so it exists at runtime too.
Which likely means not using `typedef` for the declaration.

## Other ponderings

An `enum` is really just a special case of this, where then constants' types and the super-type are the same, and we ensure you cannot introduce more instances of the type, so the `is` check can be a normal type check.

This feature may be useful for some things, but I'm not sure replacing normal enums with string constants is the use-case that sells it to me.
I'd rather make enum values easier to use, like #357.

**Comment by rubenferreira97** [comment]
@lrhn Not 100% about this issue, but a "sub-problem". Could Dart ever have "literal types" (more concrete sub-type of a collective type) so developers could express a more correct API? With unions this might be useful.

Some examples (horrendous syntax I know):
```
final 1 one = 1;

final 1 | 2 | 3 | 4 | 5 | 6 diceRoll = 3;

final 'yes' | 'no' answer = 'yes';

void printDiceResult(1 | 2 | 3 | 4 | 5 | 6 diceRoll, 1 | 2 | 3 | 4 | 5 | 6 diceRoll2) {
  print(diceRoll + diceRoll2);
}

printDiceResult(diceRoll, diceRoll);
```

**Comment by eernstg** [comment]
> Could Dart ever have "literal types"

An enum type does have this nature: It is a statically known, finite set of objects. You can't subset them in the traditional sense, but you can use type arguments to do so:

```dart
abstract class All {}
abstract class SomeA implements All {}
abstract class SomeB implements All {}
abstract class SomeOverlap implements SomeA, SomeB {}

enum E<X extends All> {
  a<SomeA>(1),
  b<SomeB>(2),
  c<SomeOverlap>(3);

  final int i;
  const E(this.i);
}
```

This means that `E<SomeA>` has two elements and is a subset of `E<All>` which has 3 elements, etc.

You can use fields on the enum declaration in order to turn those sets of enum values into sets of other kinds of values. In the example above, `a` is mapped to `1` by the getter `i`, `b` is mapped to `2`, so `E<SomeA>` indirectly models the finite set `{1, 2}`.

Of course, this might look like an overly verbose and indirect exercise, but if you really need this typing structure then the technique where you are using an enum type is one possibility that should at least be on the radar.

**Comment by rubenferreira97** [comment]
There are some differences between using `Enums` and `literal types`. Literal types are opaque, meaning that the API consumer does not care about other person code (I don't need to pass a specific declared enum from X library).

This might avoid "dumb" enums from multiple libraries that can't be reused like:
```dart
enum Answer {
   Yes,
   No
}
```

Another question I have @eernstg, how would you extend a Enum, like `typedef 8SidedDiceRoll = DiceRoll | 7 | 8;
` since you can't do this in dart:

```dart
enum DiceRoll {
  One(1),
  Two(2),
  Three(3),
  Four(4), 
  Five(5),
  Six(6),

  final int i;
  const DiceRoll (this.i);
}

enum 8SidedDiceRoll extends DiceRoll {
  Seven(7),
  Eight(8),

  const 8SidedDiceRoll (super.i);
}

```

**Comment by eernstg** [comment]
> There are some differences between using `Enums` and `literal types`.

Certainly, usages would be quite different. It's only relevant if you _really_ need that typing structure, and you are willing to pay the syntax that it takes to get it.

> how would you extend a Enum

You cannot extend an enum type. That's exactly the reason why I wasn't modeling subsets of a given finite set of values by declaring several enum types with a subtype relationship among them: That won't happen, because it is crucial for enum types that they are at the bottom of the subtype hierarchy (except for `Never` and its ilk).

But you _can_ use a type argument to organize the values of a given enum type into subsets, and that graph can be tailored to any DAG you might want (that is, it can model all possible subset relationships). This is what I did in the example [here](https://github.com/dart-lang/language/issues/2711#issuecomment-1351104963), based on the type hierarchy `All`, `SomeA`, `SomeB`, and `SomeOverlap`.

I didn't say it was convenient. Just possible. :smile_cat:

**Comment by topperspal** [comment]
Enums are great for some cases. Here I am talking about literal unions types.

For example making a http request basically require an url and a method (get, post, put etc.). Now I can achieve this by creating an enum `RequestType`
```dart
enum RequestType { get, post, put, patch, delete }
```
and then call the method
```dart 
final res = await Request(url, RequestType.get).call();
```

**Comment by cedvdb** [comment]
string unions are great for typing object paths too.

For example, in firestore you query with string paths: `where('total.amount', isEqualTo: someAmount)`. In typescript it's possible to write an utility that makes this kind of query safe, you can't do that with dart.

**Comment by mraleph** [comment]
> In typescript it's possible to write an utility that makes this kind of query safe, you can't do that with dart.

Of course you can. Just don't use raw strings. Define objects which represent fields and assign proper type to them instead.

**Comment by cedvdb** [comment]
> Of course you can. Just don't use raw strings. Define objects which represent fields and assign proper type to them instead.


And how do you keep this object in sync with your fields ? It cannot be kept in sync without some form of reflection.

Here is a typescript typing for this use case, it's UGLY, I don't understand it, but it works and it's safe:

```typescript
// Allows dot separated properties of <T>
// for firebase updates
export type UpdatePath<T, K extends keyof T> =
  K extends string
    ? NonNullable<T[K]> extends Record<string, any>
      ? NonNullable<T[K]> extends ArrayLike<any>
        ? // handle arrays separately
          K | `${K}.${UpdatePath<NonNullable<T[K]>, Exclude<keyof NonNullable<T[K]>, keyof any[]>>}`
        : // handle nested objects
          K | `${K}.${UpdatePath<NonNullable<T[K]>, keyof NonNullable<T[K]>>}`
      : // primitive property
        K
    : never;

export type Path<T> = UpdatePath<T, keyof T> | keyof T;
```


In dart we use enums to represent fields, eg: `AccountField.id` and then join them to create a path for nested properties. This isn't safe, because the enum has to be kept in sync with the actual class fields.

**Comment by mraleph** [comment]
> And how do you keep this object in sync with your fields ? It cannot be kept in sync without some form of reflection.

If you want full type-safety you code-gen both the model and helper objects for building queries from the schema.

**Comment by cedvdb** [comment]
> If you want full type-safety you code-gen

Exactly, "without some form of reflection". I guess that, if it's doable with `build` it instantly diminish the need for having it in the core language, but that's yet another use case for static meta programing, `komp` and all those proposals.

This one is quite common too, eg for json serialization, you want strings to match the field names. Something like

```
type AccountField = keyof Account
// type AccountField = 'id' | 'name' | ...;

map[AccountField.id.name]
```

> both the model and helper objects for building queries from the schema.

Although in good faith, this is general and inaccurate for our setup.

**Comment by mraleph** [comment]
> This one is quite common too, eg for json serialization, you want strings to match the field names. Something like

I understand the appeal, but Dart is not a typesystem on top of `Map` objects - which is what TypeScript is: it is a typesystem created for typing otherwise untyped dictionaries (and then crossing fingers and hope that you typed enough to not crash in runtime).

In Dart if you want strong typing you convert dictionaries to proper classes, one way or another. After which everything is strongly typed and safe. Thus most of these complicated TypeScript type system features have no place in Dart and Dart will likely never have any of them.

**Comment by andry-brill** [comment]
@mraleph @eernstg @lrhn 

Using the `dynamic` type feels similar to using `any` in TypeScript. By modern standards, however, `any` is discouraged (https://www.typescriptlang.org/docs/handbook/declaration-files/do-s-and-don-ts.html).

What do you think about the following approach? Any feedback would be appreciated.


```dart
import 'package:union_type_annotation/union_type_annotation.dart';

typedef VoidCallback = void Function();
typedef OnTapCtx = void Function(BuildContext);
abstract class IOnTap { void onTap(BuildContext context, dynamic data); }

@UnionType([VoidCallback, OnTapCtx, IOnTap])
typedef OnTap = dynamic;

class TestClass {
  final OnTap? onTap;
  const TestClass(this.onTap);
}

void notify(OnTap fn) {
  print('notify: $fn');
}

void main() {
  // ✅ Valid assignments (no warnings)
  final valid1 = TestClass(() => print('callback'));
  final valid2 = TestClass((BuildContext ctx) => print('with context'));
  final valid3 = TestClass(const MyOnTap()); // implements IOnTap

  // ❌ Invalid assignments (analyzer warnings)
  final invalid1 = TestClass((int value) => print('invalid'));
  final invalid2 = TestClass(const MyInvalidOnTap()); // doesn't implement IOnTap

  // ✅ Valid function parameter
  notify(() => print('valid'));

  // ❌ Invalid function parameter (analyzer warning)
  notify((double v) => print('invalid'));
}
```

In practice, Dart’s union types are not needed to the same extent as in TypeScript. The primary requirement is type checking - specifically, preventing `dynamic` from being used with unsupported types. It is perfectly acceptable for this validation to work only at analysis time.

To address this, I created an analyzer plugin:
https://pub.dev/packages/union_type_lint

That said, my experience with AST is superficial, so the implementation is not as efficient as it could be. Nevertheless, it works for certain cases and demonstrates the concept.

**Comment by eernstg** [comment]
We could consider introducing finite types based on constant sets.

```dart
const ToastLength = <String>{
  'short',
  'long',
};
```

The name of the constant set would then be considered to be a type (as well as an object of type `Set<T>` for some `T` which is specified or inferred at the declaration).

The element type of the set would be the most specific type which is a supertype of this type (so `ToastLength` is a subtype of `String`); the type `Never` would be a subtype; and the type `Null` would be a subtype if and only if the null object is a member of the set.

We could introduce subtype relationships based on subset relations, but I actually think it's a more useful choice to avoid this. In particular, I don't think it's likely to be helpful that `ToastLength` is a subtype of an arbitrary other finite type that happens to contain the strings `"short"` and `"long"`. In other words, I think it's more useful to keep finite types nominal rather than structural. Two finite types would be the same type if they contain exactly the same elements, though, so we might want to make those constant sets distinct in order to maintain the nominal semantics, or it might be acceptable to have this element of structural typing.

Backends would need to generalize the object layout such that a finite type can be the value of a type parameter.

Subtype tests, `T <: S`, would proceed by comparing the two types - if `T` is `Never` or a subtype thereof then the subtype relationship is true; if `T` and `S` is the same finite type then it's true; otherwise, if `S` is a finite type then the result is false; otherwise, if `T` is a finite type then we change the query to `T1 <: S` where `T1` is the supertype that we get from the set type argument.

Membership tests, `o is T`, should be compiled as `T.contains(o)` when `T` is a finite type. If `T` is a type argument then there will be a thunk that implements the membership query, and this thunk would need to perform the `contains` query.

Not trivial, but also not impossible. Do we have some really compelling use cases?

**Comment by andry-brill** [comment]
@eernstg 

Could this work like this? I have concerns about using strings, as refactoring might skip them when renaming.

```dart
typedef VoidCallback = void Function();
typedef OnTapCtx = void Function(BuildContext);
abstract class IOnTap { void onTap(BuildContext context, dynamic data); }

const OnTap = <Type>[VoidCallback, OnTapCtx, IOnTap];
```

I’m trying to avoid writing code that could impact runtime performance. 
With typedef, it’s just syntactic sugar, but here it seems like it becomes part of the codebase.

Here’s a possible real-world use case 🙂

https://github.com/flutter/flutter/issues/154197

and 

<img width="767" height="478" alt="Image" src="https://github.com/user-attachments/assets/0273bbb7-ec30-4ef0-8043-ee6cf102341f" />

**Comment by eernstg** [comment]
> ```dart
> typedef VoidCallback = void Function();
> typedef OnTapCtx = void Function(BuildContext);
> abstract class IOnTap { void onTap(BuildContext context, dynamic data); }
>
> const OnTap = <Type>[VoidCallback, OnTapCtx, IOnTap];
> ```

This would be a different idea: It doesn't specify a type that has a finite number of values, it attempts to use the list (or it could be a `Set`, that doesn't matter much here) of types as a kind of union type operator. So, as I see it, `OnTap` would then be intended to denote a type which is often written like `VoidCallback | OnTapCtx | IOnTap` in languages where general union types are supported. This calls for a completely different treatment than the one that I outlined for finite types. That's more like https://github.com/dart-lang/language/issues/83.

I think https://pub.dev/packages/union_type_lint is interesting! In particular, checking the static type of an actual argument which is passed to a parameter whose type is declared as `OnTap?` should be rather straightforward as long as the static type of that argument is one of the operand types (or a subtype thereof). It gets more convoluted if the actual argument has a static type which is itself a union type. For example, `IOnTap | VoidCallback` could be a subtype of `VoidCallback | OnTapCtx | IOnTap`, but it takes a bit of extra work to detect this kind of subtype relation. This is not surprising, the structural subtype relationships of union types are typically not supported in approaches where we don't actually add full-fledged union types to the language.

One thing to note with the approach where the union type checking is handled on specific APIs, e.g., by metadata on parameters, is that it is difficult to ensure that the union type flows through the data dependencies like other types. For example:

```dart
@UnionType([VoidCallback, OnTapCtx, IOnTap])
typedef OnTap = dynamic;

X identity<X>(X x) => x;

f(OnTap? callback) {
  final localCallback = callback ?? (BuildContext _) {};
  localCallback.argleBargle; // No compile-time error?
  identity(callback).argleBargle; // No compile-time error?
}
```

In this case I suspect that it will require quite an effort to allow the inferred type of `localCallback` to use anything other than the basic meaning of `OnTap`, that is, `dynamic`. So, presumably, `localCallback.argleBargle` is accepted with no errors or warnings (except that `avoid_dynamic_calls` might be enabled, and hence the invocation would be linted because it's a method invocation on a receiver of type `dynamic`).

This basically implies that the union type may seem effective as long as we're using the particular API element whose type annotation has the associated `UnionType` metadata, but you could say that this type easily evaporates in situations where the regular Dart types would propagate implicitly.
