### ISSUE TITLE
[patterns] Warn in case of useless non-null assertion/check?

### ISSUE THREAD

**Issue by eernstg** [dart-lang/language#2716]
Consider the following program:

```dart
void main() {
  switch (1) {
    case int i!: print('Not null!');
  }
}
```

A non-null assertion which is known to always complete normally gives rise to a warning (that is, we can't have null according to the static type, ignoring unsound null safety).

Should a `<nullAssertPattern>` cause a warning, too, when it is statically known to complete normally?

Similarly, `1?.isEven` causes a warning to be emitted because `1` can't be null. Should `<nullCheckPattern>` cause a warning, too?

**Comment by munificent** [comment]
Yes, warning makes sense to me too. I didn't put it in the proposal since I think we want to move towards warnings being handled outside of the language specification and leave it to the tools.

@bwilkerson, what do you think?

**Comment by eernstg** [comment]
Perhaps it would make sense to decide on the matter now, then put the decision into the patterns specification, and then later deal with the question about whether or not it should be in the language specification? The mention in the patterns spec would serve as a useful reminder during work on the implementations, and during creation of language tests.

**Comment by lrhn** [comment]
I think we should not specify *warnings*.

If it's inherently useless, or even dangerous, make it an error.
If it's potentially or hypothetically useful, don't say anything prescriptive, but suggest that "it might be reasonable for the Dart analyzer to issue a warning if this construct is being used in a way that doesn't seem intentional." It's usability at that point, not language design.

Oneissue with making useless things into errors is that it makes migrations harder, because they can't pass from "required" to "disallowed" by going trough a "allowed but useless" stage.

I'm open to allowing every useless operation, and letting it be up to the analyzer team to decide which warnings are useful to users. We can definitely give our input to that, but the language doesn't have to care.
(And every warning should be ignorable in some way.)
I'm also fine with completely disallowing some constructs, like patterns which cannot possibly match (`Record _ & Function  _`), but quickly gets back to why we then allow `if (false) ...`.

Allowing useless code, and unreachable code, is *safe*, so the language is happy. If we help the user notice, so they won't do it by accident (but still can if they really want to), then they're probably also happy.


Maybe we should just have a paragraph stating "Where this document states that a particular code construct causes a warning, that warning will at least be displayed by the Dart analyzer, unless it has a reason not to."

**Comment by eernstg** [comment]
We do have a reasonably firm intention to handle warnings as a tool issue, not as a specified part of the language. However, we haven't done that yet. I was just worried that we might forget about this warning if we insist that this is the time to stop specifying warnings in any language specification document, but we aren't removing the existing warnings from any of those documents at this point.

After all, I think it's confusing, and not helpful, if we carefully ensure that an expression `a!` causes a warning because the type of `a` is non-nullable, but the pattern `a!` doesn't.

**Comment by rrousselGit** [comment]
This does not sound specific to patterns. 
The same problem could happen with other kinds of assignments, such as:

```dart
void fn(int? a) {}

void main() {
  int? a;
  fn(a!);
}
```

**Comment by eernstg** [comment]
> This does not sound specific to patterns.

Technically it is actually very specific to patterns because it's concerned with a diagnostic message which is emitted during static analysis of a pattern. My point is that we shouldn't treat patterns differently.

Sidetracking a bit:

`fn(a!)` is an interesting example: It would compile without any errors/warnings, because it's perfectly OK to insist that the actual argument to `fn` isn't null, even though it's allowed to be null according to the formal parameter declaration in `fn`. We don't perform any checks (errors, warnings, hints, lints, anything) of this nature.

Another example could be this one:

```dart
void f(num n) {}

void main() {
  num n = ...;
  f(n as int);
}
```

The cast is allowed, and no diagnostic messages are emitted, but it does introduce a potential dynamic failure which is "unnecessary", in the sense that the parameter type of `f` is `num`, and `n` already has the type `num`.

We could consider detecting this kind of situation, perhaps, but the other side of this coin is that this kind of "unnecessary" constraint could be intentional, for reasons other than the type of the parameter (e.g., somebody else is going to want an `int` and not a `double`, in some invocation performed by `f`).

**Comment by eernstg** [comment]
For creation of tests this question remains relevant (no matter where and whether those warnings are specified).

So are we going to have a warning for an unnecessary null-assert pattern (`!`) and/or for an unnecessary null-test pattern (`?`)? When/where will such warnings be emitted? Are they going to be emitted by the analyzer alone, or by the analyzer and the CFE?

@johnniwinther, @stereotype441, @scheglov, @chloestefantsova, WDYT?

**Comment by johnniwinther** [comment]
The warning is triggered by shared analysis, so as of https://dart-review.googlesource.com/c/sdk/+/280086 this is emitted by both the analyzer and the CFE.
