### ISSUE TITLE
Remove `CyclicInitializationError` from Dart Language Specification

### ISSUE THREAD

**Issue by sgrekhov** [dart-lang/language#2720]
`CyclicInitializationError` is deprecated and removed from Dart 3.0. But Dart Language specification still has a reference to `CyclicInitializationError`

https://github.com/dart-lang/language/blob/3f426648cac29f3e99621bfaf75ecfb658b33bd0/specification/dartLangSpec.tex#L1540

**Comment by lrhn** [comment]
I believe that's because the null-safety patch to the specification has not yet landed. There is also no reference to `late` in the linked section.

The null safe behavior is to recurse infinitely on cyclic references in late/lazy variables, so no replacement error has been specified. (And repeat-assignment to late final variables is an unspecified error.)

**Comment by eernstg** [comment]
> I believe that's because the null-safety patch to the specification has not yet landed.

Exactly, this change has already been performed in https://github.com/dart-lang/language/pull/2605.

But, in order to get #2605 landed we could take it one word at a time. ;-) @lrhn, perhaps we should just make all those small changes in tiny PRs as they come up? With a rebase across each of these tiny PRs, #2605 will simply get smaller and smaller because we have just done one small piece of it.

**Comment by eernstg** [comment]
I'll close this issue because the requested change is part of the upcoming null safety updates performed in #2605.
