### ISSUE TITLE
[Class Modifiers] Specify capability modifier interactions with older language versions.

### ISSUE THREAD

**Issue by leafpetersen** [dart-lang/language#2725]
The current version of the [capability modifiers proposal](https://github.com/dart-lang/language/pull/2722) addresses the interactions of the `mixin` modifier with older language versions explicitly (see https://github.com/dart-lang/language/issues/2724) but is silent on the behavior of the other modifiers.  By implication, it is likely intended that these modifiers are not *available* in libraries with older language versions, but that such libraries must nevertheless respect the restrictions imposed on classes declared with capability modifiers.    That is, if the language version of this feature is `N`, then a class declared as `interface` in a library from language version `N` or greater may not be extended outside of its own library, even in a library with language version less than `N`.  Assuming this is the behavior we want (I think it is) we should make this explicit at least in commentary, and ensure that it gets tested.

cc @munificent @lrhn @eernstg @kallentu @stereotype441 @jakemac53 @natebosch @mit-mit @srawlins

**Comment by lrhn** [comment]
I agree that it's probably what we want.

No existing code is broken by introducing the language feature, things only break when people start using it.

Adding restrictions is necessarily breaking. There is no way around that, and allowing old code to ignore the breakage, only postpones the problem. You will likely need a major version increment on packages that start adding restrictions.

**Comment by eernstg** [comment]
Agreed, this is probably what we want.

Nevertheless, let's consider the situation where `class C` is exported by library _L_ in version 4.4 and is changed to `interface class C` in version 5.0 of _L_. This means that all subclasses in client code are now errors with the new version of _L_.

It is indeed known at the declaration of `C` that this is a breaking change. However, this again means that existing code is breaking when it is updated to use the new version of _L_, and it would have been possible to delay the enforcement of the new constraints until the existing code switches to the relevant language version.

Is this the new black for language features?: "New features mean the same thing everywhere!" and hence "Always break legacy code!"

"New features mean the same thing everywhere" is indeed tempting!

**Comment by lrhn** [comment]
I'm not worried about packages. You can always stay on the older major version.

I *am* worried about the platform libraries. If we want to add modifiers to any of the platform library classes (and we surely would, at least a few of them), we will break users with no option except going back to Dart SDK 2.19. 
Such changes are not on our breaking-change list, so we probably can't add any restrictions.

That's not usually how we treat SDK updates, so maybe that suggests letting legacy code extend new code classes. They'll still get warnings, and the code won't be able to be optimized as much, but it's no worse than today.
(But they can't extend sealed classes, breaking exhaustiveness is a soundness issue.)

**Comment by stereotype441** [comment]
I definitely think applying the restrictions to all libraries, regardless of language version, is the right thing to do.  If we delayed enforcement of the new constraints until the existing code switches to the relevant language version, I think that would be bad because (a) it would create an incentive for people *not* to upgrade their language version, and (b) I think it would be very surprising for users to add a capability modifier to a class whose *specific purpose* is to prevent other libraries from doing something, and find that other libraries were still allowed to do that thing.

Of course, any time a package makes a breaking change, that's an incentive for clients not to upgrade, but I want to keep that incentive isolated to the package itself.  I don't want it to bleed out and create an incentive not to upgrade language version.


@lrhn:
> I _am_ worried about the platform libraries. If we want to add modifiers to any of the platform library classes (and we surely would, at least a few of them), we will break users with no option except going back to Dart SDK 2.19. Such changes are not on our breaking-change list, so we probably can't add any restrictions.
> 
> That's not usually how we treat SDK updates, so maybe that suggests letting legacy code extend new code classes. They'll still get warnings, and the code won't be able to be optimized as much, but it's no worse than today. (But they can't extend sealed classes, breaking exhaustiveness is a soundness issue.)

If we adopt the rule that "capability modifiers are only enforced on legacy libraries", then that doesn't really work for package authors.  Because if I depend on package P, and I upgrade my code's language version before the authors of package P do, then I won't experience a breakage until later, when the authors of package P upgrade their language version and add the capability modifiers.

So we'd be effectively solving the problem only for ourselves as SDK authors, not for package authors.  If we think this is a big enough problem to be worth solving for ourselves, I want a solution that works for package authors, because there's way more package code out there than SDK code.

Personally I would rather create an annotation (and corresponding hint) that means "this class is going to have such-and-such capability modifier in a future release, so you'd better stop using it this way", similar to how `@deprecated` works.  Then we could put these annotations on classes in the SDK in 3.0, and add the capability modifiers in a future SDK release.

There's some implementation cost here (since we'd have to implement a set of annotations and hints that parallel the capability modifier system), but only the analyzer would have to pay that cost.  And the benefit would be that both we *and* package authors would have a migration path for adding these modifiers, both now and in the future.

**Comment by leafpetersen** [comment]
> So we'd be effectively solving the problem only for ourselves as SDK authors, not for package authors. If we think this is a big enough problem to be worth solving for ourselves, I want a solution that works for package authors, because there's way more package code out there than SDK code.

I'm very sympathetic to this, but I want to push back just slightly.  Eagerly reporting errors here is useful for package authors *now* but it provides zero value to package authors going forward, and it provides zero value to future package authors.  Whereas having the SDK core libraries correctly mark the intended and supported uses of classes defined there provides value to *every future package author* (and provides value to every user of modular compiles in the future).  And it's not clear to me how much value this actually provides our current package authors.  The set of classes which can be mixed in is fairly small, and mixins are fairly uncommon.  I'm worried we're doing our users a mostly theoretical favor with a very real cost.

> Personally I would rather create an annotation (and corresponding hint) that means "this class is going to have such-and-such capability modifier in a future release, so you'd better stop using it this way", similar to how `@deprecated` works. Then we could put these annotations on classes in the SDK in 3.0, and add the capability modifiers in a future SDK release.

Yes, this is an option, but note that when we add the capability modifiers in the future, it will be a non-language versioned breaking change.  **This is our one unique opportunity to add capability modifiers to the core libraries and have it be language versioned.**

**Comment by lrhn** [comment]
I think Leaf put it succinctly: This is our one unique opportunity to add capability modifiers to the core libraries and have it be language versioned.

If we don't allow legacy libraries to ignore class modifiers (legacy relative to the introduction of class modifiers), then we cannot add class modifiers to the platform libraries. Our platform libraries will be used by code back to language version 2.12. If that code uses a platform class in a way it was not intended (extending or implementing something we'd _want_ to mark as `base`, `interface` or `final`), adding the modifier is a breaking change.

We can do breaking changes in the 3.0.0 release, but we've already listed the ones we plan to do. Adding more at this point is outside of our breakage scope. We can do it anyway, but it's much, much easier to just allow legacy libraries to extend and implement any class. We won't get the full optimization benefits of the `base`, `interface`, `final` modifiers until everybody has upgraded to language version 3.0, but with patterns and records, everyone will *want* to do that.

I *would* make `sealed` apply to legacy libraries too, because it affects soundness, not just access to features. 

Every other restriction, even mixing in a non-`mixin` `class`, is just temporary, until the libraries doing so migrate to 3.0.
We don't expect any new libraries to start at a language version below 3.0.
We expect every used and maintained library to migrate to 3.0.

And we can still give warnings if a legacy library does something that it won't be able to continue doing after upgrading.
Basically "extending the interface class Foo is deprecated".

My vote is now on allowing legacy libraries to keep working, with warnings, if they do things disallowed by new class modifiers, except `sealed`. And I'm saying that *entirely* for the platform libraries. 

The thing that worries me about it, is that entirely new code, which nobody has every used from legacy code before, can still have its modifiers ignored. That's not necessary.

So maybe we should only allowing such disallowed use for platform library declarations. It's the only code you cannot version your way out of. And then the cost of having to code defensively against potential legacy code violating my supposed invariants will only fall on the Dart team, not every package author out there.
It's not a boon to be able to have your modifiers ignored. It's a cost. Everybody else should use versioning to opt in to it, and not let others opt hem back out.
The platform libraries is in a unique position where you cannot easily choose a different version, *and* we don't want people to give an `<3.0.0` SDK constraint and *mean* it. 

Or maybe we can just do `@base class IterableBase<T>` in the platform libraries, and have it special cased to mean `base` to new libraries and nothing to legacy libraries. We already special case implementability for platform classes, it wouldn't be entirely new. It would just be nicer to write `base class ...` and not have to change it later when we drop support for `<3.0` code.

**Comment by leafpetersen** [comment]
> So maybe we should only allowing such disallowed use for platform library declarations. It's the only code you cannot version your way out of. And then the cost of coding defensively against potential legacy code violating my supposed invariants will only fall on the Dart team, not every package author out there. They can trust that `final` means `final`.

This is definitely a possibility, and probably less effort than implementing an entirely separate set of lints and annotations.

The more I think about this, the more I feel that we really should take advantage of this opportunity.  We suffer a lot from not being able to update our core libraries, so when we have the chance it feels like we should take it.

**Comment by leafpetersen** [comment]
In the January 11 language team meeting, we decided that we should allow classes defined in sdk core libraries (but not in dart:ui) to ignore class modifiers in pre Dart 3 code (except `sealed` which cannot be ignored ever).  
  - @kallentu is this on your radar to implement?
  - Has this made it into the feature spec?

It might be nice to emit some non-fatal diagnostic to warn pre Dart 3 users when they do this. 
  - We could choose to simply downgrade the error to a warning when appropriate
  - We could have a separate analyzer warning
  - We could have a lint.

Thoughts on how to deal with the diagnostics here?  cc @pq @bwilkerson @srawlins

**Comment by lrhn** [comment]
Just for the record, legacy (pre-3.0) code is only allowed to ignore *new* restrictions on *existing* platform library classes, so it's still not going to be possible to extend, implement or mix-in `int`, `double`, `num`, `String`, `bool`, `Null`, `dynamic`, `Never`, `void` or `FutureOr`, and not possible to extend or mix in `Function`. (We could use this opportunity make it not possible to implement `Function` either, but it'll be `final` so we get that for free when the code migrates.)
And I probably missed something.

I'd be fine with adding an internal annotation, like `@LegacyIgnoreClassModifier('base')`, on every restriction that can be ignored by legacy code. It'll be defined in `dart:_internal`, so not available to the public. Then `dart:ui` can choose to use it too, if they want to.

Also, legacy code is never allowed to mix in a non-`mixin` post-3.0 `class`. (The specification already states this.)

Legacy code will not be allowed to implement, extend or mix-in `Record`, because it's a new class with no backwards compatibility requirements (and if we had added it before class modifiers, it would have been as locked down as the rest of the special types).


About the handling, downgrading to warning is fine, if the warning can be ignored with an `// ignore:` comment.
Only downgrading to a warning in the analyzer, and ignoring in compilers, would probably satisfy this.

**Comment by pq** [comment]
> I'd be fine with adding an internal annotation, like @LegacyIgnoreClassModifier('base'), on every restriction that can be ignored by legacy code. 

This sounds good to me.  (Definitely preferable over an allow-list.)

> About the handling, downgrading to warning is fine, if the warning can be ignored with an // ignore: comment.

This sounds good to me too.  I think implementing this as an analyzer diagnostic is better than a lint here and a warning sounds like the right severity.

**Comment by lrhn** [comment]
The current implementation approach is to ignore every `interface`/`base`/`final` class modifier in platform libraries when using them from pre-3.0 libraries. 

That means we also have a second list of _enforced_ restrictions, precisely those we had already (no subclassing `int`, `num`, typed-data, etc., and now also including `Record`).
We could change that list to annotations, but for now it's probably not worth it.

It's not possible to ignore `sealed`, because that would break exhaustability in switches.

It's not possible to ignore lack-of-`mixin`. We could ignore that from pre-3.0 libraries too, but then we must be very careful about not breaking or changing mixin-ability of any platform library class. We'd *really* prefer to not have to do that. It seems viable.

**Comment by munificent** [comment]
I believe that we've sorted out everything we want to do here, so I'm going to close this. But if there's a corner that's still undecided, feel free to re-open.
