### ISSUE TITLE
[💡 Idea] Enum extends another enum

### ISSUE THREAD

**Issue by dinbtechit** [dart-lang/language#2733]
Dart doesn't allow to extend other `enum`s it would be nice if we could extend another enum. 

## Psuedo Code

```dart

enum Align {
 start
 end
 center
}

enum FlexAlign extends Align {
 spaceAround,
 spaceBetween
}
```
Usage:
```dart
FlexAlign.start
FlexAlign.end
FlexAlign.center
FlexAlign.spaceAround
FlexAlign.spaceBetween
```

**Comment by munificent** [comment]
I'm certain this has been discussed before, but I can't find the original issue.

On the surface, yes, this does seem like a useful feature. Unfortunately, it goes against the idea that enums are a *closed* set of values. Consider:

```dart
```

**Comment by munificent** [comment]
I'm certain this has been discussed before, but I can't find the original issue.

On the surface, yes, this does seem like a useful feature. Unfortunately, it goes against the idea that enums are a *closed* set of values. Consider:

```dart
String describeAlign(Align align) {
  switch (align) {
    case Align.start: return 'start';
    case Align.end: return 'end';
    case Align.center: return 'center';
  }
}
```

Right now, this function is fine. But if we allowed enums to be extended with new values, then it's possible to call `describeAlign(FlexAlign.spaceAround)`. If you do, no case will match, and the function won't have any valid string to return. The language would have to throw a runtime exception or break soundness.

If you want to have something that is enum-like, but allows a more open-ended set of values, you're better off creating class:

```dart
class Align {
  static const start = Align('start');
  static const end = Align('end');
  static const center = Align('center');

  final String _name;

  const Align(this._name);
}

class FlexAlign extends Align {
  static const spaceAround = FlexAlign('space around');
  static const spaceBetween = FlexAlign('space around');

  const FlexAlign(super._name);
}
```

**Comment by dinbtechit** [comment]
Thank you for the great response. That's a good point. Although one downside of that approach is... it makes the code hard to read tho.

**Comment by munificent** [comment]
> it makes the code hard to read tho.

Yeah. :-/ It's hard to optimize the language's syntax for all possible use cases. Making some more terse comes at the expense of others.

Related to this request is: https://github.com/dart-lang/language/issues/2647. If we were to do that, then we could also conceivably allow those enums to be extended too.

**Comment by nguyenngocanh79** [comment]
> ```dart
> class Align {
>   static const start = Align('start');
>   static const end = Align('end');
>   static const center = Align('center');
> 
>   final String _name;
> 
>   const Align(this._name);
> }
> 
> class FlexAlign extends Align {
>   static const spaceAround = FlexAlign('space around');
>   static const spaceBetween = FlexAlign('space around');
> 
>   const FlexAlign(super._name);
> }
> ```

I tried this code, but can not use FlexAlign.start because the static members can not be inherited. Am I doing something wrong?

**Comment by eernstg** [comment]
It could have been possible to access a static member of any superinterface, all it takes is that the compiler must search those superinterfaces for static declarations with the given name when it encounters a static member access like `FlexAlign.start`. However, Dart never did this; here's a snippet of the language specification about that choice:

> Inheritance of static methods has little utility in Dart. Static methods cannot be overridden. Any required static function can be obtained from its declaring library, and there is no need to bring it into scope via inheritance.

In other words, it isn't by accident. This means that you need to write `Align.start` if that's what you want, because `FlexAlign.start` is not just one more way to write the same thing, it's a completely different thing (and, in this case: an error).

You could of course write forwarders:

```dart
class FlexAlign extends Align {
  static const start = Align.start;
  static const end = Align.end;
  static const center = Align.center;
  static const spaceAround = FlexAlign('space around');
  static const spaceBetween = FlexAlign('space around');

  const FlexAlign(super._name);
}
```

However, this might not work as expected. For instance, `FlexAlign.start` is not an object of type `FlexAlign`, and this means that you can't have a variable of type `FlexAlign` and expect it to be able to hold a value like `FlexAlign.start`.

I can see that it might be tempting to try to create enum-like classes with a subsetting relationship (like `Align = {start, end, center}`, `FlexAlign = {start, end, center, spaceAround, spaceBetween}`), but in reality there are many reasons why it doesn't just work. For instance, the subtype should be the subset, not the superset.

**Comment by nguyenngocanh79** [comment]
Thank you very much

**Comment by bbottema** [comment]
The use case I have is that a third party A's library responsible for create calls to another thirdparty B's api, which works perfectly, didn't upkeep their enum and as a result, I can't use all of the features of API B. If I could extend the enum somehow, I would have access to all the features from B.

In my specific example, I'm using a plugin for Dart that integrates AWS Polly. The problem I'm having now is that I can't select all available voices from the voices enum, and some voices have become invalid.
