### ISSUE TITLE
Inline classes and class annotations

### ISSUE THREAD

**Issue by lrhn** [dart-lang/language#2734]
The combination of inline classes and class modifiers should be specified, in one of the proposals or a third meta-document.

Inline classes are special types that are not classes, and do not introduce interfaces.

Inline classes can only be subtyped by other inline classes, by writing `implements SuperInlineClass`. As currently specified, such subtypes "inherit" all member implementations (treated as non-virtual/extension members which are also available on subtypes unless shadowed by another declaration).

It's not clear whether `base` or `interface` make sense, since there is only one thing you can do to subtype.

Most likely using `final` should prevent subtyping, and the other modifiers do not apply.

The `sealed` modifier is also unusable, since it relies on runtime type checks to detect exhaustiveness, but all inline class types are erased at runtime. Switching can only work on the underlying representation type, and exhaustive switching based on the inline class type isn't meaningful.

So `final` or nothing.

Even `abstract` is probably meaningless, since you can always do `representationObject as InlineClassType` directly, without going through the constructor.

-----

If we later choose to allow an inline class type to "implement" an interface type (one already implemented by its representation type), which would allow upcasting/assigning to the interface type, and possibly "inheriting" members (forward members directly to the representation object), then that probably still doesn't make any difference for modifiers.

Such an inline class will not actually introduce any new objects implementing the interface, it's entirely a static assignability and forwarding feature. An inline class type should be able to implement sealed/final interfaces without restriction, because it's more of a has-a relationsship than an is-a.

**Comment by eernstg** [comment]
It is tempting to think about `abstract` and see if we can support some kind of abstraction (sharing common methods among inline classes that `implement` the abstract inline class), but the firm decision that inline class member invocation is resolved statically makes it somewhat awkward to support any kind of abstract members.

```dart
abstract inline class A<X> {
  abstract final X it; // Abstract representation object.
  bool get b;
  bool get notB => !b; // Use the 'template method' design pattern.
}

inline class B implements A<int> {
  final int it;
  bool get b => it.isEven;
  // Implicitly generate a `notB` calling `B.b`.
}

void main() {
  A<int> a = B(2);
  print(a.notB); // No: Every member access on a receiver of type `A<...>` is a compile-time error.
}
```

In any case, that would be inline-classes-later, not now.

I think `base` is meaningless, because inline classes do not have the associated relation to anything (they don't even `extend` an interface type which is the representation type or a superinterface thereof, if we do introduce that feature).

I think `interface` is redundant, because inline classes support `implements` (at this point they can implement other inline classes, and we might very well introduce a similar relation to superinterfaces of the representation type).

`final inline class I` can be used to prevent other inline classes from doing `implements I` (and it would also prevent regular classes from doing `implements I`, if we introduce that feature).

Note that we don't need `mixin`, because the inline class mechanism which is similar to inheritance actually supports "inheritance" from multiple superinterfaces.

So I agree that we'd allow `final`, with semantics that it prevents `implements` from others. No other type modifiers are allowed.
