### ISSUE TITLE
The remainder of a negative number is incorrect

### ISSUE THREAD

**Issue by Do-Eternally** [dart-lang/language#2747]
The remainder operator gives incorrect results for negative numbers。Such as:-185%200.The correct answer is -185。But 15.
It`s the result of 200-185. 
Dart SDK version: 2.14.4 (stable) (Wed Oct 13 11:11:32 2021 +0200) on "windows_x64"

**Comment by water-mizuu** [comment]
The `%` that Dart uses, _as specified in the documentation_, is the remainder from Euclidean division. As stated, 

> Returns the remainder of the Euclidean division. The Euclidean division of two integers `a` and `b` yields two integers `q` and `r` such that `a == b * q + r` and `0 <= r < b.abs()`.
> 
> The Euclidean division is only defined for integers, but can be easily extended to work with doubles. In that case, `q` is still an integer, but `r` may have a non-integer value that still satisfies `0 <= r < |b|`.
> 
> The sign of the returned value `r` is **always positive**.

If you want the behavior that is shown by languages such as Javascript which does *not* implement the remainder operator, you can use the `num.remainder` method.

```dart
print(5 % 3); // 2
print(-5 % 3); // 1
print(5.remainder(3)); // 2
print(-5.remainder(3)); // -2
```

**Comment by lrhn** [comment]
Correct, this is working as intended and documented.

The Dart `~/` and `.remainder` operations match up, so that `n == (n ~/ k) * k + n.remainder(k)` for all `n` and `k`.

There is no division matching `%`. You can add one as:
```dart
extension IntDiv on int {
  int div(int divisor) => (this - (this % divisor)) ~/ divisor;
  // or, to avoid doing `%`:
  int div(int divisor) {
    var r = this ~/ divisor;
    if (this < 0 && r * divisor != this) r += r.sign;
    return r;
  }
}
```
and have `n == n.div(k) * k + n % k`.

(For consistency, I'd have preferred `~/` and `%` matching, and then possibly a `.div` and `.remainder` too, but it's too late for that now.)
