### ISSUE TITLE
Another backdoor around base/final with mixin on clauses

### ISSUE THREAD

**Issue by munificent** [dart-lang/language#2757]
With `base` and `final`, the goal is that an author of library L can choose to create an invariant that every subtype of a type T in A either inherits from T or inherits from another type in L. And, critically, no code outside of L can break that invariant.

There is one loophole already (#2755). There's another one with `on` clauses in mixins. An `on` clause also establishes a subtype relation between the mixin and the type in the `on` clause. If the mixin also exposes an interface, it means that you can create a type that implements the mixin which in turn means you now have a subtype of the type in the `on` clause but don't inherit from it.

Concretely:

```dart
// lib_a.dart
base class C {}
// Since C is `base`, every instance of C should concretely inherit from C.

// lib_b.dart
import 'lib_a.dart';

mixin M on C {}

class Nefarious implements M {}

main() {
  print(Nefarious() is C); // Prints "true".
}
```

I think probably just need another rule in there that says that if a mixin has a `base`/`final` type in its `on` clause, then the mixin must be `base`/`final` too. But I wanted to file this so that we can take it into account when also figuring out how to close the other loophole.

**Comment by lrhn** [comment]
The tricky part here is that the `on` type of a mixin is not *really* related to implementation inheritance. It's more like a type bound than a real interface type - it just has to be an interface type, because the bound must be satisfied by a superclass at the mixin application, and superclasses can only implement interface types.
It still does become a superinterface of the mixin type's interface, which is why there is a potential loophole problem here.

Not really being inheritance means that there is no need to restrict the `on` type based on whether that type is `interface`, `base`, `final` or even `sealed` in its declaring library. It's not a problem that a mixin has an `on`-type which is a sealed type, because it's not a class that you can subtype directly. The mixin must be applied to another class, which must be a valid, non-`final`/`sealed`/`interface` sub-class of the `on` type, and then there is no problem.

Except that mixins also introduce interfaces, which you can subtype unless we prevent it, so if the `on` type doesn't allow implementing, then the `mixin` itself also mustn't, which means being `base`, `final` or `sealed`.

**Comment by leafpetersen** [comment]
This is currently broken.  https://github.com/dart-lang/sdk/issues/52160 and https://github.com/dart-lang/sdk/issues/52161 .

**Comment by leafpetersen** [comment]
This has been fixed.
