### ISSUE TITLE
Should bounds and promoted types be treated as always-exhaustive?

### ISSUE THREAD

**Issue by munificent** [dart-lang/language#2765]
The patterns proposal [defines a set of "always-exhaustive types"](https://github.com/dart-lang/language/blob/master/accepted/future-releases/0546-patterns/feature-specification.md#exhaustiveness-and-reachability). If you switch on one of these types in a switch statement, then it's an error if the statement isn't exhaustive. All other types are treated as not always-exhaustive and a switch statement on them can be non-exhaustive without error:

```dart
test(int i) {
  switch (i) {
    case 1:
    case 2:
      print('smol');
    case 3:
    case 4:
      print('big');
    // No error.
  }
}
```

Currently, we do not treat any type parameters with type bounds or promoted intersection types as always-exhaustive. Should we? Concretely, given:

```dart
sealed class A {}
class B extends A {}
class C extends A {}
```

### Bound type

```dart
test<T extends A>(T t) {
  switch (t) {
    case B(): print('is B');
    // Error here?
  }
}
```

### Promoted type

```dart
test(Object obj) {
  if (obj is A) {
    switch (obj) {
      case B(): print('is B');
      // Error here?
    }
  }
}
```

This is definitely outside my area of expertise, but it seems reasonable to me to treat these both as always-exhaustive.

cc @johnniwinther

**Comment by lrhn** [comment]
Seems reasonable in both cases.

The only thing we know about `t` in the bound type example is that it's a `T`. It can be any subtype of `T`, but if being a subtype of a sealed type is relevant, then that type being sealed is probably also relevant.
If you *can* exhaust it, you probably *should* exhaust it.

The only thing we know about `obj` in the promoted type case is that it's a subtype of `A`. If that's relevant, then again it's probably relevant that `A` is sealed. Here I'd expect it to work as currently specified, because the type of `obj` *is* `A`. A more relevant case is:
```dart
test<T>(T obj) {
  if (obj is A) {
    switch (obj) {
      ...
```
because here the type of `obj` is `T & A`, which should be treated exactly the same as `T`-with-bound-`A` in every way.

I see no soundness issues with requiring these switches to be exhaustive. I can't come up with a case where it would be a problem. (Also because you can always add `default:` as a case.)

So the rule will be: A type is _always-exhaustive_ iff it is:
* `bool`
* `Null`
* An `enum` declared type
* `T?` where `T` is always-exhaustive
* `FutureOr<T>` where `T` is always-exhaustive
* A record type where every field type is always-exhaustive.
* Declared by a class or mixin declaration with the `sealed` modifier.
* A type variable `X` with bound `T` and `T` is always-exhaustive.
* A promoted type variable `X & T` and `T` is always-exhaustive.


We will declare `num` as `sealed`, with `int` and `double` being `final`.

We can declare `bool` and `Null` as sealed too without any problem, and we can say that enum classes are always implicitly marked sealed. These are all handled by *value*-exhaustion, not subtype-exhaustion, so it's not the same as `sealed`, and we should probably make them `final` instead. (An `enum` declaration cannot have any of the new modifiers, it's always non-`abstract` and `final`.)


We could make `int` be always-exhaustive, and require you to use `<`/`>` ranges to exhaust it. 
If we don't, it'll be hard to add it later, so we may want to consider whether we want that now,
(It also allows an `int` switch to be exhaustive without a default case.)
Another option is to make `int` always-exhaustive now, but not implement exhaustion by ranges, so you'll always need a default case until we do implement exhaustion-by-ranges.
Or we can just never make it always-exhaustive, and allow exhaustion-by-ranges later anyway.

(We should special case a NaN constant pattern to do `isNaN` instead of always failing.)

I worry _a little_ about `FutureOr<T>`, because 
```dart
FutureOr<A> f = ...;
switch (f) {
  case B b: ...
  case C c: ...
  case Future<B> fb : ...
  case Future<C> fb : ...
}
```
looks exhaustive, but fails to cover `f = Future<A>.error("gotcha");`.
The exhaustion of `FutureOr<A>` means exhausting `A` *and* matching `Future<A>` directly.
In practice, you probably *want*:
```dart
FutureOr<X> f = ...;
switch (f) {
   case X x: ...
   case Future<X> fx: ...
}
```
to be exhaustive (and needing to be exhaustive) for *any* type.
Which means the rule should probably be that a type is always-exhaustive if it is:
```dart
* `FutureOr<T>` for any type `T`.
```
(But that suggests it should also be always-exhaustive for `T?` for any type `T`, because you can always exhaust it by `case T t: ...; case null: ...`, and you probably should!)

-----

We *could* delegate the "must be exhaustive" rule to a lint, and allow you to do whatever you want (for non-expression switches). That would be maximally flexible. If it's not exhaustive, then it's completely equivalent to having the final `default:` case, which would make it exhaustive, so there is no extra power, just fewer errors.
I'd expect everybody to have that line enabled, and having it in the core set, so we might as well have it in the language.

Or we could introduce `switch! (e)` which must be exhaustive, so you can opt in to a switch needing to be exhaustive.
Again, I'd expect most style guides to tell you to use `switch!` by default.
