### ISSUE TITLE
Are nullable types allowed as type literals?

### ISSUE THREAD

**Issue by leafpetersen** [dart-lang/language#278]
Is the following a syntactically valid post-nnbd program?

```dart
void main() {
  print(int?);
  var x = int?;
  var y = {int? -3 : 4};
}
```
cc @lrhn @munificent @eernstg

**Comment by eernstg** [comment]
I think we have a similar amount of freedom here as we do with `identifier<type,arguments>` for literals denoting parameterized types (and, coincidentally, generic function instantiations): We can add support for that kind of syntax, and it makes no difference for anything _other_ than the syntax (because the underlying runtime support needs to exist anyway). This would presumably allow us to make that decision independently (no need to hurry).

We would have stuff like `{x == int?? 2 : 3}` which could be a set (containing `2` if `x` is `int?` and otherwise `3`) or a map (namely `{b: 3}` where `b is bool`), so there's certainly a potential for ambiguities.

**Comment by munificent** [comment]
In general, yes, I think it would be nice to support all type annotations as type literals. In ambiguous cases, can we simply always prefer the *non*-type literal interpretation and then if you want the type literal, you parenthesize it?

> We would have stuff like `{x == int?? 2 : 3}`

I think that one is easy because we can and should always lex `??` a single token without doing the magic "split in two only if needed" that we do for `>>`.

**Comment by leafpetersen** [comment]
Closing this in favor of the [existing issue](https://github.com/dart-lang/language/issues/123) on type expressions.  We won't land this as part of NNBD.

**Comment by mateusfccp** [comment]
It seems #123 has been generally solved but this specific case was not handled. Have we decided that this is not worthy at all?
