### ISSUE TITLE
Why do we don't have anything like the satisfies thing in typescript ?

### ISSUE THREAD

**Issue by S-P-Ks** [dart-lang/language#2782]

**Comment by lrhn** [comment]
I'm assuming this refers to https://www.typescriptlang.org/docs/handbook/release-notes/typescript-4-9.html

I'm not sure that operators makes sense in Dart type system. We just declare the type of variables or objects, and we don't try to treat the same object as both a map and a class-instance with the same keys/properties.

**Comment by munificent** [comment]
Closing this because I don't think there's enough here to be actionable.

**Comment by eernstg** [comment]
I agree that this is not a very good fit for Dart. I have one more comment, though:

The `satisfies` construct seems to play a role in TypeScript which is based on having types that contain a finite set of specific values. So `{"a", "b"}` would be the type, call it `N`, that just includes those two strings. `N` is a subtype of `String` because it's a subset (you may wish to say that in a more convoluted way if you don't want to think of a type as a set ;-).

However, we might want to maintain such a very narrow type as `N`, and at the same time check that it contains only `String`s (that is, we haven't by accident included a non-`String`). This sanity check is even more useful when the type contains a set of instances of a more complex type.

In order to get that sanity check in TypeScript, and still have a precise analysis where the type checker knows that an expression of this type `N` is either `"a"` or `"b"` (which is useful, e.g., when checking exhaustiveness), we can use `satisfies`.

I'd say that the natural way to achieve a similar result in Dart is to use an enum type:

```dart
// Simple:
enum E { a, b }

// With the string:
enum E {
  a('a'),
  b('b');
  
  final String name;
  const E(this.name);
}
```

The enum type is known by the type system to contain exactly the objects denoted by `E.a` and `E.b`, so we can have exhaustiveness checks on them. And if you really need the actual strings, they can always be included as an instance variable in `E` (here: `name`).

Surely, TypeScript type level computations are far, far more expressive than Dart type level computations, but I think this covers an important part of the typical usages.
