### ISSUE TITLE
[Patterns] Cast pattern type check issue

### ISSUE THREAD

**Issue by sgrekhov** [dart-lang/language#2787]
In https://github.com/dart-lang/co19/issues/1686 we agreed that 
```dart
main() {
  num d = 3.14;
  Expect.throws(() {
    (d as double) = "one";
  });
}
```
is a runtime error, not a compile-time error.
But lets's take look at [Type checking and pattern required type](https://github.com/dart-lang/language/blob/master/accepted/future-releases/0546-patterns/feature-specification.md#type-checking-and-pattern-required-type).

> To type check a pattern `p` being matched against a value of type `M`:
> ...
> **Cast**:
> i. Resolve the type name to a type X. It is a compile-time error if the name does not refer to a type.
> ii. Type-check the subpattern using X as the matched value type.
> ...
> If `p` with required type `T` is in an irrefutable context:
> 
> - It is a compile-time error if `M` is not assignable to `T`
 
According the above `(d as double) = "one";` should be a compile-time error. We need to either change the spec or change the test, mentioned in https://github.com/dart-lang/co19/issues/1686

Another possible issue. I didn't find in the spec what we should expect in the following case.
```dart
final int v1 as String = "string";
```
We have in the spec `Type-check the subpattern using X as the matched value type.` Ok, subpattern is `final int v1`, `X` is `String` match fails. Do I understand right that it is a compile-time error in irrefutable context (no matter what value we are going to assign to this pattern) and the case which never match in refutable context? Where this case is specified?

**Comment by lrhn** [comment]
I think @munificent already has changed the spec in one place to make `cast` patterns accept any input, in https://github.com/dart-lang/language/pull/2779.
It removed the "or cast" from:
 
> *   The matched value type for a variable or cast pattern is not assignable to
>    the corresponding variable's type.

I don't know if that changes this issue.

The way I read the rules quoted here, they should not cause any compile-time error.

To type check `(d as double)` with matched value type `String`:
1. Resolve `double` to a type `X` (success).
2. Type check `d` with matched value type `double`.
    * `d` is a variable pattern, it's required type is its declared (unpromoted) type `num`. 
    * Since `double` is assignable to `num`, there is no compile-time error.

It should still fail at runtime, because the actual string value won't be castable to `double`, but it's a dynamic error like any other `as` assertion. In this particular case, because `String` is sealed, we can say that it cannot possibly succeed, but the spec doesn't account for that.

**Comment by sgrekhov** [comment]
@lrhn thank you for the clarification!

**Comment by eernstg** [comment]
I believe we can close this issue now.

@lrhn, do you wish to create a proposal that the patterns feature spec is clarified? I tend to think that it is sufficient to change some occurrences of 'is prohibited' to 'is a compile-time error', plus a few fixups to the enclosing sentence, but that could in any case be handled as a PR.
