### ISSUE TITLE
Enhance the feature extension

### ISSUE THREAD

**Issue by Suebersson** [dart-lang/language#2788]
Olá meu no é Suebersson Montalvão. Gostaria dar umas sugestão de melhoria para a feature 'extension' do dart
Sendo possível, seria muito produtivo se a 'extension' pudesse implementar método, get e set em múltiplos objetos(class)
Seria algo parecido como a feature mixin, que nos permite criar uma classe mixando com múltiplas classes.

Hello, my name is Suebersson Montalvão. I would like to make a suggestion for improving the 'extension' feature of dart
If possible, it would be very productive if the 'extension' could implement method, get and set in multiple objects (class)
It would be something like the mixin feature, which allows us to create a class by mixing with multiple classes.

Ficaria assim:
Would be like this:

    extension AnyName on A, B, C {
        void anyFunction(String str) {
            // run ...    
        }
    }
    class A{}
    class B{}
    class C{}

Sendo possível, gostaria de sabe o caminho de como criar essa feature ou a própria equipe do dart poderia criar 
If possible, I would like to know the way to create this feature or the dart team itself could create

Desde já agradeço algo retorno.
Thank you in advance for something in return.

my email: suebersson.dev@gmail.com

**Comment by lrhn** [comment]
The practical problem with allowing this is that we then don't have a type for `this`.

The type of `this` would be `A` *or* `B` *or* `C` which is a general union-type, which the Dart type system doesn't have.

Or it could be a shorthand for effectively declaring three different extensions, one on each of `A`, `B` and `C`.
At that point error messages might become confusing. We'd have to re-analyze the same code in three different contexts, and if there is an error in one of those contexts, we need to report that in some way that makes it obvious that `int x = this.bar();` is not valid because `this.bar()` returns `int?`, but only when `this` is a `C`.


I can see the saving, but allowing you to copy code to different contexts, and reanalyze it in each context, sounds mostly like metaprogramming, not how Dart otherwise works. Like a syntactic macro.
And if do something like this, I'd prefer to get complete syntactic macros, not just special-cased `extension` declarations.

**Comment by Suebersson** [comment]
Fiz um teste, e realmente vi que essa estrutura de código teria um problema com o tipo do objeto mesmo que fossem classes abstratas. Basicamente não tem como implementar isso na ‘extension’

Obrigado pelo returno

I did a test, and I really saw that this code structure would have a problem with the object's type even if they were abstract classes. Basically there is no way to implement this in the 'extension'

Thanks for the feedback

**Comment by Wdestroier** [comment]
If all you want is to share a common method body, then you can try `extension Name on Object? {}`. After a while, code completion suggestions will show a bunch of stuff if you add methods to `Object?`. You shall add a check for unknown types.

```dart
extension Name on Object? {
  void function(String str) {
    switch (this) {
      A() || B() || C() => print(str),
      _ => throw 'Invalid argument type.'
    }
  }
}
```

**Comment by Suebersson** [comment]
OK thank you
