### ISSUE TITLE
What happens with the .fromEnvironment constructors in an NNBD world

### ISSUE THREAD

**Issue by leafpetersen** [dart-lang/language#279]
How do we deal with the .fromEnvironment constructors which sometimes return null? 

cc @munificent @eernstg @lrhn

**Comment by eernstg** [comment]
We could, e.g., try to scan for current usages where the `defaultValue` named parameter of `String.fromEnvironment` is non-null. If that rarely happens than we could conclude that it is already an established fact that `String.fromEnvironment` uses the return value null to indicate that there is no such value. The caller would then have to deal with this, which seems appropriate anyway, so the return type would be `String?`. `int.fromEnvironment` is similar, 

But `bool.fromEnvironment` is in a better position for using the return type `bool`, because it uses a default of `false`.

Do we have any other `fromEnvironment`s?

**Comment by lrhn** [comment]
More generally: How do we handle factory constructors which return `null`. The `fromEnvironment` constructors are special only because they are `const` constructors, any other factory constructor can also currently return `null`, and I'm sure some does.

We can't write a return type on constructors. Do we want to? We could introduce:
```dart
class C {
  factory C?() { .... return null; ... }
}
```
to allow a factory constructor to return a `null`. However, that would mean that such a constructor cannot be converted to a generative constructor, and we have factory constructors *only* because they allow you to switch between generative and factory constructors.

Without such syntax, I see no way we can default factory constructors to nullable, so we would have to default to non-nullable.

My personal preference is to do that and  break all factory constructors that return `null`. It was always a bad design - nobody expects `new Foo()` to be `null`, and nobody expects to have to write `new Foo()!.bar()`.
Those libraries would have to migrate their code to static methods instead of factory constructors, which can break existing calls that use `new`, or change their behavior when they would otherwise have returned `null`, which can obviously also break things.

**Comment by eernstg** [comment]
@lrhn wrote:
> break all factory constructors that return `null`

+1, it really does feel wrong for a constructor to return null (and I think `factory` should be an implementation detail as far as possible, e.g., to cover the case where someone needs to change a generative constructor to a factory constructor, and not break existing code).

**Comment by leafpetersen** [comment]
I am also on board with breaking factory constructors that return null.  I think the `defaultValue` approach can work for the specific cases here that I was worried about.  Basically `defaultValue` becomes a required parameter.

**Comment by rakudrama** [comment]
If you are to force `const String.fromEnvironment("foo")` to yield a String, then there needs to be a constant expression for testing for whether the environment parameter is provided or absent. This will be clunky to use (like always calling `map.contains(key)` as a guard to `map[key]`), and doubly-clunky in a potentially constant expression since you will be forced to duplicate the name or name it in a separate constant declaration to make it a constant expression.

As an example, I use `-DDUMP_IR   ` or ` -DDUMP_IR=  ` on the VM command line when running dart2js to dump info for all methods, and `-DDUMP_IR=foo  ` for the foo method. If the flag is missing, the option dumping feature is turned off and the file is not created.

```dart
String? pattern = const String.fromEnvironment("DUMP_IR")

--->

String? pattern = const bool.isInEnvironment("DUMP_IR") : const String.fromEnvironment("DUMP_IR") : null
```

It might be a lesser evil to allow `null` in this one already-magical case.

**Comment by munificent** [comment]
> we have factory constructors only because they allow you to switch between generative and factory constructors.

They also give you a "natural" way to create an instance of a generic class where you don't want to use a generative constructor, but where you do want the type argument to be on the class and not on a static method:

```dart
SomeGenericClass<int>.create(); // Reads nice.
SomeGenericClass.create<int>(); // Seems weird if it returns a SomeGenericClass<int>.
```

+1 for having factory constructors always be non-nullable. Factory constructors are already an odd feature now that we have optional new, so I don't think it adds enough value to give them more weird special magic to allow nullable factory constructors.

If we're already talking about adding support for required named parameters, would making the `defaultValue` parameter to `fromEnvironment()` required be enough to fix that API?

**Comment by lrhn** [comment]
I was leaning towards keeping the `defaultValue` parameters optional, but giving them a default value (hah!) of empty string, zero and false.

It does mean that you cannot detect whether a flag is absent or present-and-empty.
We could just say that that is fine. The only case where it should make a difference is flags that are only checked for presence, not value, which means they are implicitly boolean flags.
I would just (still) prefer if `-Dfoo` would be equivalent to `-Dfoo=true`, not `-Dfoo=`. Then you can use `bool.fromEnvironment` to check "boolean" flags, and anything with a `=` would then be a string property (which may or may not be an integer numeral).

There is also the option of throwing if the property isn't there and `defaultValue` is `null`. That's similar to making the parameter required, but you can omit the default value if you are sure the property is defined.

Letting the constructors have default values different from `null` is more *subtly* breaking than just making `defaultValue` required. The latter would break all code not passing a `defaultValue` and force it to migrate. Just returning `0` where we used to return `null` can make the code do something unexpected.

Now, for migration, it is hard to have two different behaviors of the same function. Can we make parameters required in migrated code only? That would mean that they can still be omitted from non-migrated code, and the call omitting the now required argument should ... fail at runtime? That would mean that it's still a breaking change to non-migrated code to make the parameter required.

(I guess anything marked as `@required` should be safe, it has documented the expected protocol, so code that breaks is in violation of that and, by definition, broken code. That won't help us here, it really used to be optional).

**Comment by leafpetersen** [comment]
> Can we make parameters required in migrated code only?

Yes.  They'll just get null, as now.

> That would mean that they can still be omitted from non-migrated code, and the call omitting the now required argument should ... fail at runtime?

That depends on what the body of the method does with the unexpectedly null value.  

The default value approach seems reasonable to me.

**Comment by lrhn** [comment]
I've been thinking more about this, and I'm coming to prefer required parameters (and until NNBD: throwing if the `defaultValue` is `null`, which is what post-NNBD required non-nullable parameters will do in legacy code).

Introducing new default values is perhaps too subtle a way of breaking, where a hard throw when the behavior has changed is easier to find in your code.

Using non-null default values is mainly convenient (required named parameters are just annoyingly verbose to write). You can just write `var x = String.fromEnvironment("x"); if (x.isNotEmpty) ...` If the parameter is optional. I just fear that a lot of existing code with `if (x != null) ...` will just start behaving slightly differently without anyone noticing.

I want to start sending out "Breaking change" proposals for the change soon, to get people migrating their code to be impervious to the change. That will mean explicitly passing a non-`null` `defaultValue`, which is a valid intermediate step if we go to non-`null` default values, and the correct migration if we make `defaultValue` required (per-NNBD: make it throw if `null`).

So: I want required parameters, and I want to start pushing for it *soon*. Any opinions?

**Comment by eernstg** [comment]
@lrhn wrote:
> Any opinions?

Makes sense.

@rakudrama [mentioned](https://github.com/dart-lang/language/issues/279#issuecomment-474974174) that a full emulation of the current behavior would then call for a new `bool.isInEnvironment(_)`.

But it might also turn out to be sufficient in practice to choose a suitable default string:

```dart
String someOption = const String.fromEnvironment("SOME_OPTION", "qux");
```

This should work if the given program is required to behave exactly the same when `SOME_OPTION` is unset and when it has the value `"qux"`. It seems likely to me that many programs could specify the response to a missing environment variable in this manner.

**Comment by lrhn** [comment]
If the `defaultValue` is `required`, then you should always use it and not care if the default value comes from a declaration or an omission. That's new recommended behavior, not just a migration of the existing behavior.

You can desugar `isInEvnironment("foo")`  to `(const String.fromEnvironment("foo", "1")==const String.fromEnvironment("foo", "2"))` if necessary.

**Comment by leafpetersen** [comment]
> I want to start sending out "Breaking change" proposals for the change soon, to get people migrating their code to be impervious to the change.

Do we really need to do this is a breaking change now?  My initial strawman would be that:
  - We make the parameter non-nullable and required
  - Callers in non-opted code can still call it with no defaultValue (or with a null one) (this is the default behavior)
  - The constructor just returns defaultValue if it doesn't get something from the environment

This means that:
  - in non-opted in code, if don't specify a defaultValue you will continue to `null` as before
  - when you migrate, you have to add a defaultValue

What goes wrong here?

**Comment by lrhn** [comment]
The main issue I see is that the constructor itself is in migrated code. It would check eagerly whether its argument is non-null in weak-nnbd mode. That check is there to ensure that the rest of the body won't see a `null` in its otherwise `null`-safe code, so we can safely return the default value as a non-null return value.

It might not actually be true that the implementation is in migrated code, because the `fromEnvironment` constructors are magic implemented, at least partly, in the compiler. Some platforms still do not allow dynamic invocation of the constructor, so they are doing things entirely in the compiler.

I guess it would be possible to hack this constructor implementation to accept incoming `null` values from non-migrated code and return them. We just need some compiler people to ensure that this is the behavior.

**Comment by leafpetersen** [comment]
What's the current thinking on this?

**Comment by leafpetersen** [comment]
This is resolved in favor of adding default values to the optional parameters.
