### ISSUE TITLE
Avoid redundant typing in list patterns on switch?

### ISSUE THREAD

**Issue by mnordine** [dart-lang/language#2799]
Was just trying something like this out on `master`:
```dart
final result = switch ('1990-02-23:100'.split(':')) {
  [date, amount] => (DateTime.parse(date), num.parse(amount)),
  _ => null,
};
```

Unfortunately, I got a static error:
```
The expression of a constant pattern must be a valid constant. Try making the expression a valid constant.
```
And needed to add the `String` types, like so:
```dart
final result = switch ('1990-02-23:100'.split(':')) {
  [String date, String amount] => (DateTime.parse(date), num.parse(amount)),
  _ => null,
};
```

Shouldn't the analyzer/compiler be smart enough to know all the types are `String`?

**Comment by eernstg** [comment]
You're using a plain identifier to indicate that a new variable should be introduced. This works in a declaration context, but not in a matching context: `var [date, amount] = ...;` is fine, but with `case [date, amount]`, the two identifiers are taken to denote `const` variables in scope (one reason for this is that `case myVariable: ...` in pre-pattern Dart is a reference to a constant variable, and we didn't want to break that).

So you need to make it a variablePattern rather than an identifierPattern, but you can still get the type from inference:

```dart
final result = switch ('1990-02-23:100'.split(':')) {
  [var date, var amount] => (DateTime.parse(date), num.parse(amount)),
  _ => null,
};
```

**Comment by mnordine** [comment]
Thanks, I kind of figured I'd need the `var`, `final`, or type, but wasn't sure why. I now remember the `const` issue.

Current syntax isn't ideal for longer lists, what about this?
```dart
final result = switch ('1990-02-23:100'.split(':')) {
  final [date, amount] => (DateTime.parse(date), num.parse(amount)),
  _ => null,
};
```
Similar to a declaration context?

I almost never program with Lists of mixed types, so having this shorthand would be nice.

**Comment by eernstg** [comment]
I'm pretty sure we discussed this kind of abbreviation (`var [a, b]` rather than `[var a, var b]`) quite early in the process, and it wasn't accepted. @munificent, do you remember more?

**Comment by munificent** [comment]
Yes, an earlier version of the proposal supported that. It was inspired by Swift, which has similar syntax. When we discussed it, the vibe on the language team was that it made it even harder to tell when you needed `var` before a variable and when you didn't, so I removed it from the proposal.

I could see us adding it in a future release of the language if it turns out that users really want it. But for now, I think it's good to ship something simple and not try to guess too much about which features users will want.
