### ISSUE TITLE
What is the type of Iterator.current in NNBD Dart?

### ISSUE THREAD

**Issue by leafpetersen** [dart-lang/language#280]
The `.current` getter on `Iterator` returns `null` when `moveNext` has not been called, or when the last call to `moveNext` returned `false` (that is, when there is no current element).

If we preserve this behavior, then it's return type must become nullable.

If we change this behavior, it will be breaking.  We would need to somehow special case this based on whether we are calling from opted in code or not to avoid breakage.

cc @munificent @lrhn @eernstg

**Comment by eernstg** [comment]
It seems completely natural to me that the meaning of the value returned from `current` can be "there is no such thing", and the null object is used to convey that meaning. So this is a case where we would use a nullable type because that's exactly what we need.

We can get rid of the nullable type again in a for-in statement, and that is also a natural thing: The additional structure allows us to maintain additional invariants, e.g., "this value is not null".

For that, we may rely on provable properties, but since we can't use types to express the property that "`current` will _never_ return null when the previous operation on that iterator was a `moveNext`, and it returned true", (and we can't in general expect any help from types in proving that any particular invocation of `moveNext` was actually the most recent operation), we have to accept that the desugaring of the for-in statement is unsafe. In particular, we'll have to use `var n0 = it.current!;` in the desugaring, and we can't stop some rogue iterator from returning a spurious null there.

Still, even that part could be made statically safe if the compiler has special knowledge about the kind of iterator that we are using (it could be known to be a platform class), and in that case we might be able to compile away that `!`, in those special occurrences of a for-in where we have enough special knowledge.

So I think this is just the way it should be.

**Comment by leafpetersen** [comment]
> In particular, we'll have to use `var n0 = it.current!;` in the desugaring,

This isn't a valid desugaring, unless we forbid iterators on nullable types.  You need to do something like `var n0 = it.current as E` where `it` has static type `Iterable<E>`.

**Comment by eernstg** [comment]
Of course, sorry! But I don't think this contradicts the claim that `current` needs a nullable type, because that's the actual semantics of that getter.

It is then a bit confusing that the null object is used in two different ways: (1) "the iteration at this point does not have a 'current' object", and (2) "at this point in the iteration, the object which is 'current' is the null object" (because that's how the given collection wants it), but I guess we can't expect to eliminate that situation entirely. If we are going to have null for _any_ reason, anywhere, then we can have it for more than one reason. And we don't want `OptionReasonOne<OptionReasonTwo<Something>>`. ;-)

**Comment by leafpetersen** [comment]
Just a note that for both Java and C#, the equivalent operation throws (or has undefined behavior) in the equivalent situations.  For Swift, the equivalent of `.current` and `moveNext` are combined into a single method, which returns an option (their version of nullable type).

**Comment by munificent** [comment]
> It is then a bit confusing that the null object is used in two different ways: (1) "the iteration at this point does not have a 'current' object"

The `null` object isn't really used for that. The iterator protocol normally relies on the return value of `moveNext()` to tell when there is an available object. The documentation for `Iterator` does say:

> The Iterator is initially positioned before the first element. Before accessing the first element the iterator must thus be advanced using moveNext to point to the first element. If no element is left, then moveNext returns false, current returns null, and all further calls to moveNext will also return false.

And:

> current property
>
> Returns the current element.
>
> Returns null if the iterator has not yet been moved to the first element, or if the iterator has been moved past the last element of the Iterable.
>
> The current getter should keep its value until the next call to moveNext, even if an underlying collection changes. After a successful call to moveNext, the user doesn't need to cache the current value, but can keep reading it from the iterator.

So, unfortunately, the behavior of calling `current` both before and after walking the sequence is specified to return null. It would have been nice if that was considered undefined behavior (like modifying the sequence during iteration is) because then we could turn it into a runtime error to call `current` before the first call to `moveNext()` or after calling `moveNext()` returns false.

In practice, I don't think returning null is practically useful, so it would be a shame to have to insert casts and jump through weird hoops to allow `null` to be returned. It would be good to see how much actual code is broken if we make the return type `E` instead of `E?`.

**Comment by lrhn** [comment]
The original reason for choosing `null` over throwing was simplicity of implementation.
You should never access `current` unless you have just called `moveNext` and gotten a `true` result.
By making the value `null` before the first `moveNext` and after a `false` result, it's possible to implement the `current` as a simple field (OK, a getter returning a simple private field, but that's still easily optimizable by a JIT compiler). If it had to throw, we would have to do a state-check on each access, duplicating the logic (or storing the result) of the previous `moveNext` call, so that we can throw when needed.
There was no need for that extra cost because all types were nullable anyway. Returning `null` was always an option if you had no good value to return.

The Dart landscape is much different now, with AOT compilation (that is not targeting a JIT platform like JavaScript) and now non-nullable types. It's not obviously true that the same tradeoffs are still the best choices.

With non-nullable types, an always-nullable `current` getter means that manual iteration will be more cumbersome. You will need to write `it.current!` every time you iterate an iterable with a non-nullable element type, even if you *know* that it will never fail. (That's a protocol promise, not a physical requirement, any class not implementing `iterator` correctly could return a `null` from an `Iterator<int>` after a true `moveNext()`, so the runtime needs to do the check).

The only salvation here is that we can automatically introduce the `!` for `for-in` iteration, which is how most iterables are consumed.
A `for (var x in someIterable<int>) {..}` can choose to infer `int` for `x` and do the `var x = $it.current!;` for you. It must only do that when the element type is not nullable, so `for-in` is no longer a simple syntactic sugar for a `while` loop with an iterator, the implicit downcast is introduced in some cases, and not in other cases, based on the static type.
This should happen even with no-implicit-downcasts.

If we change the behavior to return the element type directly, and throws on invalid `current` accesses, then we need to *rewrite all iterator implementations*. 
It won't be *breaking* for client code, as long as that code follows the rule of "no access to `current` except after a successful `moveNext()`".
The `Iterator` signature won't "change", we'll just migrate the original `T get current` to non-nullable `T get current` instead of `T? get current`. Non-migrated code is unaffected. Migrated code will see the new type, and have to migrate to match before they can be considered migrated. 
It will make migration *harder*, though, it's no longer just adding `?` or `!` as appropriate.

Example issue:

```dart
class ListIterator<T> {
  final List<T> _list;
  int _index = 0;
  T _current = null;
  int moveNext() {
    if (_index < _list.length) {
      _current = _list[_index++];
      return true;
    }
    _current = null;
    return false;  
  }
  T get current => _current;
}
```
This is a classical example of an iterator implementation.

To migrate this, we'd have to write it differently, perhaps:
```dart
class ListIterator<T> {
  final List<T> _list;
  int _index = 0;
  bool hasValue = false;
  T? _current = null;
  int moveNext() {
    if (_index >= _list.length) {
      _hasValue = true;
      _current = _list[_index++];
      return true;
    }
    _hasValue = false;
    _current = null;  // Still avoid leaks.
    return false;
  }
  T get current => _hasValue ? _current as T : throw StateError("No current element");
}
```
We can't just check if `_current` is `null` because the `T` type may be nullable, we need an extra sentinel value on the side.

Or we could say that it returns `null` if `T` is nullable and throws if it's not, so we just change the original to:
```dart
...
  T? _current = null;
  ...
  T get current => _current as T;
```
In either case, there will be an extra overhead on the current getter.

Maybe we'll need a construct like this to avoid the extra type checks when we cast from `T?` to `T`:
```dart
class _Box<T> {
  T value;
  _Box(this.value);
}

class ListIterator<T> {
  final List<T> _list;
  int _index = 0;
  _Box<T>? _current = null;
  int moveNext() {
    if (_index < _list.length) {
      T vale = _list[_index++];
      if (_current != null) {
         _current.value = value;
      } else {
         _current = _Box(value);
      }
      return true;
    }
    _current = null;
    return false;  
  }
  T get current => _current != null ? _current.value : throw StateError("No current value");
}
```
(Here `_current` looks a bit like a lateinit variable, except that we also need to clear it again, and be in control of the thrown exception. We do need to clear it to not keep the last element alive).

This change is doable, but non-trivial, and it might jeopardize the migration velocity. 
It's within our migration strategy to require some code to be rewritten for NNBD, and iterator implementations could be such code. However, we have tried to make it so that only code that is not currently `null`-correct needs rewriting. If the `null`-behavior of an API is known, and you rewrite your code to match that, and the API rewrites to match that, then you should only need to insert the occasional `?` and `!` to migrate. 
Having to rewrite classes makes that more expensive, which increases the risk that code will not be migrated.
Maybe most of that expense is in SDK libraries and Dart-team controlled packages, but probably not all of it.

So, we'd have to do a risk/cost assessment. My personal preference is to migrate the return type of `current` to `T`, not `T?`. It's cleaner. It's also costlier up front, but improves user experience in the long run.

**Comment by eernstg** [comment]
@munificent wrote:
> So, unfortunately, the behavior of calling current both before and
> after walking the sequence is specified to return null.

Right, which is the reason why I described null from `current` as an indication that "there is no current element". The problem is, of course, that we can't fully trust that indication for a collection whose element type is nullable.

@leafpetersen wrote:
> Just a note that for both Java and C#, the equivalent operation throws

Right, we could do that as well, and it certainly makes sense. But that's a breaking change, so we'd have the usual trade-off about whether to do such a thing (and @lrhn's [description of the situation](https://github.com/dart-lang/language/issues/280#issuecomment-475151833) adds a lot of detail about why the throwing design might actually incur additional trade-offs, e.g., by making `current` more expensive).

I tend to think that it could be a reasonable solution to keep `current` nullable, and then rely on abstractions like for-in statements to hide this fact, in particular by using `current!` in cases where the iteration variable has a non-null type and the collection has a non-null element type. (In that case, only a buggy iterator could cause `current!` to fail.)

**Comment by munificent** [comment]
> If we change the behavior to return the element type directly, and throws on invalid current accesses, then we need to rewrite all iterator implementations.

I wouldn't propose that we *require* an implementation to throw. Instead, I'd say that it is unspecified what happens if you call `current` before calling `moveNext()` or after `moveNext()` returns `false`. Having a return type of T instead of T? implies that you probably *would* have to throw if the element type is not nullable, but, who knows, maybe an implementation has some reasonable sentinel value it can return or something.

Leaving the behavior unspecified is what we do for modification during iteration, and I think gives implementers the most flexibility.

> We can't just check if _current is null because the T type may be nullable, we need an extra sentinel value on the side.

You need some state on the side anyway, today. You can't use the value of the current element itself because `null` could be an element, so the requirement already exists to store that state somewhere else. In ListLiterator, you already have `_index`. Could you not just do:

```dart
class ListIterator<T> {
  final List<T> _list;
  int _index = -1;
  int moveNext() {
    if (_index < _list.length) _index++;
    return _index < _list.length;
  }
  T get current => _list[_index];
}
```

?

**Comment by eernstg** [comment]
But, given the documentation that we have had for quite a while on this topic (current: 'Returns null if the iterator has not yet been moved to the first element, or if the iterator has been moved past the last element of the Iterable', nothing undefined here), wouldn't a developer be justified in writing code like the following and expecting it to work?:

```dart
main() {
  Iterator<int> it = ...;
  if (complex stuff) it.moveNext();
  more complex stuff;
  do {
    // Make sure `moveNext` has been executed and the current element is not null.
    while (it.current == null && it.moveNext()) {}
    ...
  } while (it.moveNext());
}
```

It may be rare and ugly (not unlike grumpy cat ;-), but the change to 'the behavior of current is undefined [in the cases where it currently returns null]' could introduce some subtle bugs.

**Comment by natebosch** [comment]
Would it be feasible and reasonable to have `.current` return null if the element type is nullable, and throw otherwise? Existing usage of Iterable would not be broken because the only Iterables that can exist from non-migrated code have a nullable type. I worry that the behavior would be confusing in the long term - but it might be worth the tradeoff for a nonbreaking migration?

**Comment by eernstg** [comment]
That's a cool idea!

**Comment by leafpetersen** [comment]
@natebosch That is an interesting idea.  It does have the problem that @lrhn points out that it makes the implementation of `.current` a bit heavier, but it might give the best user experience.

**Comment by rakudrama** [comment]
I'm not clear on how allowing not-started-`null` and already-finished-`null` terminators for nullable elements helps migration. It certainly helps code that is confused and probably buggy about `null` values in the Iterable.

I saw an example very much like this:
```
var iter = "Hello".codeUnits.iterator;
...
if (iter.current == null) ...
```
This code stands less chance of being buggy in confusing elements with terminators, since the code units are never `null`.
I do think this pattern is very rare, I found only pkg/test/lib/src/util/string_literal_iterator.dart with a direct comparison of _something_`.current == null`.
What I could not grep for easily is code that uses a null check to see if it ran off the end of the iterator.

I think it could be implemented easily enough. Consider this Iterator:
```dart
class FooIterator<T> {
  T _current = null;
  T get current => _current;
  bool moveNext() {
    if (...) {
      _current = ...
      return true;
    }
     _current = null;
    return false;
  }
}
```
Would we be able to rewrite this to accommodate the suggestion like so?
```dart
class FooIterator<T> {
  T? _current = null;
  T get current => _current as T;
  // bool moveNext() same
}
```
I think the compiler(s) could be trained to recognize ` e as T` where `e` has static type `T?` as a conditional form of `e!`, that is `T.isNullable ? e : e!` without exposing `T.isNullable`.

**Comment by leafpetersen** [comment]
Yes, `_current as T` was my thinking of how you might implement this in general, or in cases where you explicitly return `null` you do something like:

```dart
  E get current {
    if (_remaining < 0) return null as E;
    return _iterator.current;
  }
```

It's still not free, but if the `T? as T` pattern can be made reasonably fast then it might be ok.

**Comment by leafpetersen** [comment]
We have chosen to make this non-nullable and made the behavior implementation defined when called in any circumstance other than after a call to `moveNext`  which has returned `true`.
