### ISSUE TITLE
Should FutureOr<T> and T? be always-exhaustive types regardless of T?

### ISSUE THREAD

**Issue by munificent** [dart-lang/language#2810]
The patterns proposal defines a set of "always-exhaustive" types for which it's an error to have as the matched value type in a switch statement and not have the cases be exhaustive. (Or put another way, the language allows you to have non-exhaustive switch statements for *some* types.)

The choice for which types are always-exhaustive is somewhat ad hoc since this isn't strictly needed for soundness. It's a software maintenance feature. We want to require switch statements to be exhaustive in places where flagging a missing case helps a user find and fix bugs. But we want to allow switch statements to be non-exhaustive in places where a default case feels pointless or where requiring exhaustiveness would break a lot of existing code. (Currently, switch statements never have to be exhaustive and you only get a warning for non-exhaustive switches on enum types.)

For the two union-like types in Dart, the proposal says:

> But switch statements must only be exhaustive when
the matched value is an *always-exhaustive* type, defined as:
>
> *   `T?` where `T` is always-exhaustive
> *   `FutureOr<T>` for some type `T` that is always-exhaustive

This means:

```dart
enum Color { red, blue, yellow }

void test1(Color? maybeColor) {
  switch (maybeColor) {
    case null: ...
    case Color.red: ...
    case Color.yellow: ...
  } // Error, doesn't handle "blue".
}

void test2(FutureOr<String> stringNowOrLater) {
  switch (stringNowOrLater) {
    case Future<String>(): ...
  } // No error even though some strings not handled.
}
```

If we expect that switches on FutureOr<T> and nullable types will generally have cases that distinguish the two branches, then I think it makes sense to treat those types as always-exhaustive regardless of the inner type. That would mean `test2()` has an error and you have to write:

```dart
void test2(FutureOr<String> stringNowOrLater) {
  switch (stringNowOrLater) {
    case Future<String> _: ...
    case String _: ...
  }
}
```

If we expect that switches on these types generally treat the union as just an extra branch added to the possibly-non-exhaustive other set of values, then the current proposal is probably more aligned with what users want.

I don't have data on how often FutureOr<T> or nullable types are switched on. I suspect it's fairly uncommon.

If it were my code, I think I'd prefer that we treat FutureOr<T> and nullable as always-exhaustive. But, then... I'd probably prefer that *all* switch statements be exhaustive, so I'm not sure if my intuition here is just an extension of that.

Thoughts? @dart-lang/language-team

**Comment by jakemac53** [comment]
Fwiw I do run into nullable types being switched over a fair bit, at least in migrations. Possibly less likely in new code though.

**Comment by rrousselGit** [comment]
The FutureOr examples are a bit unclear. Does that mean with the current proposal we could do the following?


```dart
int fn(FutureOr<String> futureOr) {
  switch (futureOr) {
      case Future<String>(): return 42;
  } // Apparently no error?
}
```

If so that definitely sounds unexpected.

**Comment by rrousselGit** [comment]
At the same time, it sounds inappropriate to have a compilation error in the Color example:

```dart
void test1(Color? maybeColor) {
  switch (maybeColor) {
    case null: ...
    case Color.red: ...
    case Color.yellow: ...
  } // Error, doesn't handle "blue".
}
```

That code works today, so I don't see why we'd have a compilation error tomorrow.

At the same time, I'd expect:
```dart
int test1(Color? maybeColor) {
  switch (maybeColor) {
    case null:
    case Color.red:
    case Color.yellow:
      return 42;
  }
}
```

To have an error.

And following the same logic I'd expect:

```dart
int? test1(Color? maybeColor) {
  switch (maybeColor) {
    case null:
    case Color.red:
    case Color.yellow:
      return 42;
  }
}
```

to not have an error. But instead, the linter would warn that there's an implicit "null" return, where this function would be equivalent to:

```dart
int? test1(Color? maybeColor) {
  switch (maybeColor) {
    case null:
    case Color.red:
    case Color.yellow:
      return 42;
  }
  return null;
}
```


And writing the `return` null` explicitly would fix the warning.



In that sense, I wouldn't expect a non-exhaustive check to cause a compilation error directly.
Instead, I'd expect the compilation error to code from a side-effect of the usage of a non-exhaustive check.

**Comment by natebosch** [comment]
I prefer that `FutureOr` and `?` are conditionally-exhaustive as specced, not always-exhaustive.

I don't see a reason to use a `switch` over `if` to handle the two branches of either union type. I'd use a switch if I want to include other cases for the (non-null, or non-future) value. Since we don't force switches which include general cases for the value to be exhaustive, I don't see a reason to force these to be exhaustive just to have the option of adding a different case for `null`.

**Comment by lrhn** [comment]
Nate has a good point, if `T` isn't required-exhaustive, why should `T?` be. 
We can require you to handle `null`, and let you decide how to handle `T`. But a pretty likely use-case for a nullable value is that you don't want to do anything for `null`.

For `FutureOr`, it's more likely that you should handle both cases, but if it's a `FutureOr<void>` or `FutureOr<Null>`, maybe you won't care about the other branch.

As also pointed out, for these two-element union types, a `switch` is not the natural decomposition. Still, if it's something I can't promote, I'd be likely to do `switch (_field) { case Future<T> f: .... case T v: ... }` rather than creating a new local variable, or casting in the `else` branch. (And I'll complain if the `T v` does any runtime type check.)

It's more likely that a union-type value will occur as a part of a larger composite value (even if just a record). At that point, exhausting all options can be useful, but requiring it is again not always reasonable.

We should recognize that the types `Future<T>` and `T` exhaust the `FutureOr<T>` type, but not require it to be exhausted, unless `T` is required to be exhausted (because then you shouldn't loose that by merging `T` with a single other type).

**Comment by eernstg** [comment]
### Why do we have 'always-exhaustive'? How useful is it?

The characterization of some types as always-exhaustive is used to provide the guarantee that a switch statement/element will execute one of its cases, it won't just do nothing. It's based on history (e.g., enums have received that treatment for many years), and the rationale would be that it's likely to be a bug if a switch statement/element switches over some, but not all, the variants that add up to the always-exhaustive type.

(In the following I'll just say 'switch' when I mean 'switch statement or switch element', to avoid some verbosity.)

It's a rather weak guarantee, because it isn't made explicit anywhere in the switch that the scrutinee type is always-exhaustive, which means that the construct may well do nothing, unexpectedly, just because the type was expected to be always-exhaustive, but it actually wasn't.

The fact that the set of always-exhaustive types is now enlarged makes this even more error-prone: Each developer who reads or maintains this kind of code will now have to keep a much longer list of types in their head (or they need to look up declarations to check whether they have the `sealed` modifier), in order to catch the cases where the switch _isn't_ exhaustive and "skip" is a bug.

I tend to conclude that we must have the notion of always-exhaustive types because of the history, but going forward we should also acknowledge that this concept is rather soft around the edges.

### Are we going to ask for explicit default cases?

Switch expressions must be exhaustive for soundness reasons, and this will cause developers to get into a habit of writing an `_` case at the end whenever the compiler says so, even in cases where this catch-all case should be unreachable (based on business rules, or based on any kind of reasoning that our tools can't replicate). So they're typically going to be `throw Something`.

I think this implies that everybody who's writing a substantial amount of Dart code will get used to this approach: "Add a default case whenever it may be needed", albeit only for switch _expressions_.

Each of these default cases will be a burden on every reader and maintainer of the code, because they remind us that there could be a dynamic error at this location. On the flip side, every switch expression that _doesn't_ have such a default case is then a relief because it is known to be safe.

To provide that relief more globally, we might want to lint non-exhaustive switches (now we're back to switch statements/elements) at some point in the future. Developers/organizations who choose to enable that lint will then develop a habit of adding a default case to any switch which isn't recognized as being exhaustive, and this means that we shouldn't gratuitously omit a detection of a safe switch: This will destroy said relief for no good reason.

Hence, I'd expect that we are likely to support a safe style (with explicit default cases), at least as a style that certain organizations/developers can _choose_ to apply.

### Why aren't union types too rare or too small to matter?

As @lrhn mentions, exhaustiveness is of course particularly important in the composite case (because a lack of exhaustiveness at any level may destroy exhaustiveness for the switch as a whole):

```dart
class A {
  final FutureOr<int> fut;
  ...
}

void main() {
  var a = A(...);

  switch (a) { // Exhaustive, if union types are.
    case A(: Future<int> fut): ...
    case A(: int fut): ...
  }
}
```

As we discussed at the language team meeting, a union type provides exactly the same guarantee as a `sealed` type: `T1 | ... | Tk` is a type where it is guaranteed that every value of that type will have at least one of the types `Tj`, `1 <= j  <= k`.

So for `x` of type `FutureOr<T>` it is guaranteed that a match with `Future<T>` and with `T` is exhaustive, and for `y` of type `T?` it is guaranteed that a match with `T` and with `Null` is exhaustive.

Just like multi-layer `sealed` declarations, this of course allows for further partitions: If `A` is a sealed class which is exhausted by `B1`, `B2`, `B3`, then `A?` is exhausted by `B1`, `B2`, `B3`, and `Null`.

I don't see why we wouldn't consider the union type as always-exhaustive. We would automatically cover the case which includes the next step down (like `B1`, `B2`, `B3`, and `Null` being the next step down from `A` and `Null`), and we would also support case lists like `case A(): ...; case null: ...;`.

If we do _not_ consider the union types as always-exhaustive then I would expect `case A(): ...` to be spuriously accepted with no diagnostics, whereas `case B1(): ...; case B2(): ...; case B3(): ...;` would (correctly) be reported as "missing a case for null!".

Who is it going to help if we let `case A(): ...` without the null case slip through silently?

**Comment by munificent** [comment]
We discussed this in the language meeting. We've decided to keep the current definition of always-exhaustive types. That means:

```dart
sealed class C {}
class C1 extends C {}
class C2 extends C {}

// Sealed type is always-exhaustive.
test1(C c) {
  switch (c) { // Error. Not exhaustive.
    case C1 _:
  }
}

// Nullable sealed type is always-exhaustive.
test2(C? c) {
  switch (c) { // Error. Not exhaustive.
    case C1 _:
    case C2 _:
  }
}

// FutureOr of sealed type is always-exhaustive.
test3(FutureOr<C> c) {
  switch (c) { // Error. Not exhaustive.
    case C _:
  }
}

// Unsealed type is not always-exhaustive.
test4(String s) {
  switch (s) { // No error even though not exhaustive.
    case 'str':
  }
}

// Nullable unsealed type is not always-exhaustive.
test5(String? s) {
  switch (s) { // No error even though not exhaustive.
    case 'str':
  }
}

// FutureOr of unsealed type is not always-exhaustive.
test6(FutureOr<String> s) {
  switch (s) { // No error even though not exhaustive.
    case 'str':
  }
}
```

Note that the "always-exhaustive" flag is only used to determine which statement statements produce compile errors when not exhaustive. Switch expressions must always be exhaustive regardless of type. And, even though we don't require a `T?` or `FutureOr<T>` to be exhaustive in a switch statement if `T` isn't always-exhaustive, we *do* expect that the exhaustiveness checking algorithm does understand that those types are unions and are covered if their branches are covered:

```dart
int test1(C c) => switch (c) {
    case C1 _ =>  1,
    case C2 _ => 2
  };

int test2(C? c) => switch (c) {
    case C1 _ =>  1,
    case C2 _ => 2,
    case null => 3
  };

int test3(FutureOr<C> c) => switch (c) {
    case C1 _ =>  1,
    case C2 _ => 2,
    case Future<C> _ => 3
  };

int test4(String s) => switch (s) {
    case String _ =>  1,
  };

int test5(String? s) => switch (s) {
    case String _ =>  1,
    case null => 2
  };

int test6(FutureOr<String> c) => switch (s) {
    case String _ =>  1,
    case Future<String> _ => 2
  };
```

These examples should all compile without error because they are exhaustive over the branches of the unions.
