### ISSUE TITLE
Is it possible to destructure fields from a Class?

### ISSUE THREAD

**Issue by mnordine** [dart-lang/language#2822]
Tried this:
```dart
class Point {
  final int x;
  final int y;

  Point(this.x, this.y);
}

void main() {
  final (:x, :y) = Point(1, 5);
  print('$x, $y');
}
```
Got:
```
The matched value of type 'Point' isn't assignable to the required type '({Object? x, Object? y})'.
Try changing the required type of the pattern, or the matched value type.dart(pattern_type_mismatch_in_irrefutable_context)
```

**Comment by mateusfccp** [comment]
I think the specified syntax for destructuring classes would be:
```dart
final Point(:x, :y) = Point(1, 5);
```

**Comment by mnordine** [comment]
Yep, the analyzer does seem to accept that. Shouldn't this be inferred, though?

**Comment by mateusfccp** [comment]
I think this is a way to disambiguate from regular records destructuring? I don't know if there's any implication in allowing your proposed syntax.

**Comment by munificent** [comment]
There was a point in time when the proposal did allow the name to be inferred, yes. But we removed that because it broke being able to actually match a record *object* in places where the matched value is a supertype of Record. I would very much like to get it back (#2563) but we won't in time for 3.0.

**Comment by mnordine** [comment]
Thx, in that case I'll close this dupe.
