### ISSUE TITLE
Can patterns match an enum field?

### ISSUE THREAD

**Issue by rubenferreira97** [dart-lang/language#2844]
Trying the latest dart version I came across this example:
```dart
enum class Difficulty {
  easy(1, "Easy"),
  medium(2, "Medium"),
  hard(3, "Hard");

  const Difficulty(this.id, this.designation);
  final int id;
  final String designation;
}

final json = jsonDecode('{"difficultyId": 1}');

// The expression of a constant pattern must be a valid constant.
if (json case {'difficultyId': Difficulty.easy.id}) {
   print("Got easy!);
}
```

Is there an alternative syntax that can solve this problem or this is not possible at all?

**Edit:**
Is this the correct solution?
```dart
if (json case {'difficultyId': int difficultyId} when difficultyId == Difficulty.easy.id) {
   print("Got easy!);
}
```
Still don't know how to express this statement (check case `{'difficultyId': int difficultyId}` and multiple `when` branches):

```dart
// Ugly, old syntax except case
if (json case {'difficultyId': int difficultyId}}) {
   if (difficultyId == Difficulty.easy.id) {
     print("Got easy!");
   } else if (difficultyId == Difficulty.medium.id) {
     print("Got medium!");
   } else if (difficultyId == Difficulty.hard.id) {
     print("Got hard!");
  } else {
    throw Exception('Id must be 1,2 or 3');
  }
}

```

**Comment by munificent** [comment]
> Is this the correct solution?
> 
> ```dart
> if (json case {'difficultyId': int difficultyId} when difficultyId == Difficulty.easy.id) {
>    print("Got easy!);
> }
> ```

Yes. You can't match directly on `Difficulty.easy.id` because calling `.id` on an object isn't a valid constant expression. (We have discussed extending const to understand that getters on enums are (probably?) constant, but we haven't made any motion on that yet.)

> Still don't know how to express this statement (check case {'difficultyId': int difficultyId} and multiple when branches):

It's a little hard with your particular example because you're getting strings from JSON and not converting them to enum values first, but the integer values for each enum value are also not stored in constants. Even without patterns, you'd have similar problems trying to write this code today using a switch statement.

With the new pattern stuff, you could do:

```dart
switch (json) {
  case {'difficultyId': int id} when id == Difficulty.easy.id:
     print("Got easy!");
  case {'difficultyId': int id} when id == Difficulty.medium.id:
     print("Got medium!");
  case {'difficultyId': int id} when id == Difficulty.hard.id:
     print("Got hard!");
  default:
    throw Exception('Id must be 1,2 or 3');
}
```

That's fairly verbose (though still better than what you'd write today). Really, the map patterns aren't accomplishing much since you're only accessing a single element and it's always the same one in each case. Maybe better as:

```dart
switch (json['difficultyId']) {
  case int id when id == Difficulty.easy.id:
     print("Got easy!");
  case int id when id == Difficulty.medium.id:
     print("Got medium!");
  case int id when id == Difficulty.hard.id:
     print("Got hard!");
  default:
    throw Exception('Id must be 1,2 or 3');
}
```

Or even (pretty weird):

```dart
var id = json['difficultyId'];
switch (null) {
  case _ when id == Difficulty.easy.id:
     print("Got easy!");
  case _ when id == Difficulty.medium.id:
     print("Got medium!");
  case _ when id == Difficulty.hard.id:
     print("Got hard!");
  default:
    throw Exception('Id must be 1,2 or 3');
}
```

But, really, I'd do:

```dart
enum class Difficulty {
  static Difficulty fromId(int id) => const {
    1: Difficulty.easy,
    2: Difficulty.medium,
    3: Difficulty.hard,
  } ?? throw ArgumentError('Id must be 1,2 or 3');

  easy(1, "Easy"),
  medium(2, "Medium"),
  hard(3, "Hard");

  const Difficulty(this.id, this.designation);
  final int id;
  final String designation;
}
```

And then:

```dart
switch (Difficulty.fromId(json['difficultyId'])) {
  case Difficulty.easy: print("Got easy!");
  case Difficulty.medium: print("Got medium!");
  case Difficulty.hard: print("Got hard!");
}
```

**Comment by munificent** [comment]
One thing that would help here is if you could call an arbitrary conversion function in the middle of pattern matching and destructuring. F# has something called [active patterns](https://learn.microsoft.com/en-us/dotnet/fsharp/language-reference/active-patterns) that let you do this and Scala lets you define your own [extractors](https://docs.scala-lang.org/tour/extractor-objects.html). I had hoped to get something similar into Dart (and initial versions of the proposal had something along those lines) but it didn't pan out. I still hope we can get it in as a last extension because as you note, they come in handy in some cases like this.

**Comment by rubenferreira97** [comment]
Nice, that seems to solve this particular problem in a more generic way (allowing many more use cases). Fingers crossed and looking forward for that feature. If it happens I hope it gets a more Darty syntax tho 😄.
