### ISSUE TITLE
Type tightening without `covariant` via generics

### ISSUE THREAD

**Issue by Zekfad** [dart-lang/language#2866]
In language we have `covariant` that allows type tightening, but I find following case:
```dart
abstract class Base {}

abstract class A<T extends Base>  {
  void method(T a);
}

class B extends A<B> implements Base {
  @override
  void method(B a) => null;
}
class C implements Base {}


void main(List<String> args) {
  final A<Base> a = B();
  a.method(C()); // type 'C' is not a subtype of type 'B' of 'a'
}
```
Following snippet does compile, but produces error. 
Is it possible to catch such a thing in compile time via type system?

**Comment by lrhn** [comment]
The behavior you see is a consequence of Dart's (unsafe) covariant generics.

One solution could be variance annotations, which can make `A` invariant or contravariant, and `B` not assignable to `A<Base>`.

**Comment by eernstg** [comment]
> Is it possible to catch such a thing in compile time via type system?

Concretely, using #524:

```dart
// Use `--enable-experiment=variance`.

abstract class Base {}

abstract class A<inout T extends Base>  {
  void method(T a);
}

class B extends A<B> implements Base {
  @override
  void method(B a) => null;
}
class C implements Base {}


void main(List<String> args) {
  // final A<Base> a = B(); // Compile-time error.
  final A<B> a = B(); // No error at compile time nor at run time.

  // a.method(C()); // Compile-time error.
  a.method(B());
}
```

Note that the declaration-site variance feature has not been fully implemented and is not even firmly in the pipeline for inclusion in the language. So we may or may not get it. (But voting for that feature _is_ working at this time. ;-)

I'll close this issue because it reports on a situation which is already targeted by #524 and similar issues.
