### ISSUE TITLE
[Class Modifiers] Overlap in lint and base/final subtyping restriction

### ISSUE THREAD

**Issue by kallentu** [dart-lang/language#2871]
In the spec, it mentions in the "**Disallowing implementation**" section:
`It is a compile-time error if a subtype of a declaration marked base or final is not marked base, final, or sealed. This restriction applies to both direct and indirect subtypes and along all paths that introduce subtypes: implements clauses, extends clauses, with clauses, and on clauses. This restriction applies even to types within the same library.`

Then in the "**reopen lint**" section it states:
`Extends or mixes in a class, mixin, or mixin class marked interface or final and is not itself marked interface or final.`

Doesn't the error cover the `final` case in the lint already? 
Is the lint supposed to only cover `interface` types? And if so, do we want a lint or annotation at all for just this one scenario?

cc @pq @bwilkerson @dart-lang/language-team

**Comment by lrhn** [comment]
No, not entirely. The error case allows a `base` class which has a `final` superinterface and `interface` superclass.

The 3D (4x4x4) table of superclass, relation, subclass and effect would be:

| subclass | relation | superclass | effect |
|:-------:|:------:|:-----:|:------:|
| _none_ | `extends` | _none |         |
| _none_ | `extends` | _none |         |
| _none_ | `extends` | _none |         |
| _none_ | `extends` | _none |         |

**Comment by eernstg** [comment]
Big tables is hard work. ;-)  Looking at it now.

**Comment by lrhn** [comment]
I think so. 

Let me try my own words:
* A `sealed` class or mixin *prevents implementation* if it has an immediate superinterface which is marked `base` or `final`.
* A `sealed` class or mixin *prevents inheritance* if it extends or mixes in a declaration which is marked `interface` or `final`.
* A `sealed` class or mixin is implicitly marked:
    * `final` if it prevents implementation and prevents inheritance.
    * `base` if it prevents implementation, but not inheritance.
    * `interface` if it prevents inheritance, but not implementation.
    * nothing, if it prevents neither.


Not sure it's the same thing.

**Comment by eernstg** [comment]
I think it's the same thing: The properties 'prevents implementation and prevents inheritance' are sufficient to ensure that we're in the first bullet in my rule; 'prevents implementations, but not inheritance' ensure that we are not in the first bullet, but we are indeed in the second bullet; and so on.

Nice! This also serves as a double check on the sanity of the rules.

**Comment by pq** [comment]
Thanks so much for all the clarification!

A few questions as I work through this...

**1.** The tables suggest we should lint equally on `extends` and `with` but I can't wrap my head around the `with` cases.

Specifically, it seems to read that we want to lint when a class marked `base` or is otherwise unmodified mixes in a `final` class or `interface` but I didn't think either of these were valid mixins.

For example:

```dart
interface class I {}

base class B with I {}
```

yields a diagnostic that reads "The class 'I' can't be used as a mixin because it isn't a mixin class nor a mixin."

While,

```dart
final class F {}

base class B with F {}
```

reports the same "The class 'F' can't be used as a mixin because it isn't a mixin class nor a mixin".

(But mixins can't be marked `final` or `interface` right?)

Sorry in advance for probably misunderstanding something obvious!

**Comment by kallentu** [comment]
I'd like to take another look at this and clarify my understanding with the specification.

@eernstg @lrhn How does the base/final subtype restriction come into play with induced modifiers? It seems like any class/mixin with a supertype that is base or final would be induced either base or final.

Does this example induce any modifiers? From the two comments above, I'm a little confused on what happens here.
```
base class A {}
sealed class B extends A {} // Does not induce any modifiers?
```

Same with this example:
```
final class A {}
sealed mixin B implements A {} // should produce error that B must be base or final because A is final, but induces base?
```

Could you help me clarify how the `sealed` induced modifiers that you've specified above work with the base/final errors with induced modifiers on sealed? Are the base/final subtyping errors separate to the induced modifier definition?
Maybe I'm missing something!

**Comment by eernstg** [comment]
> How does the base/final subtype restriction come into play with induced modifiers?

The implicitly induced modifiers are just as good as the explicitly written ones.

I'd prefer to say that we have a program with modifiers `base`, `interface`, `final`, `sealed`; we check the `sealed`ness separately (it's an error to have a direct subinterface in a different library); next, we compute the implicitly induced modifiers on every `sealed` declaration and every mixin application; from this point in time, `sealed` is ignored; finally, we check 'It is a compile-time error if a subtype of a declaration marked base or final is not marked base or final', and 'it's a lint if a subtype extends or mixes in a class, mixin, or mixin class marked `interface` or `final`, and is not itself marked `interface` or `final`.

This means that we apply a very simple local check, which is possible because we have changed the program such that it has `interface`, `base`, and `final` modifiers on every class that semantically needs to satisfy the associated constraints. I find this approach simpler to understand than an approach where we compute the missing modifiers on sealed classes and mixin applications on the fly, based on traversals of part of the superinterface graph.

**Comment by munificent** [comment]
There's a lot in these comments. :) Is this all sorted out now, or is there more to do here?

**Comment by kallentu** [comment]
Lint and error are now completed, we can close this out now.
