### ISSUE TITLE
Relational pattern with bitwise operations

### ISSUE THREAD

**Issue by Zekfad** [dart-lang/language#2881]
Currently patterns proposal have Relational pattern that allows to do checks with constant values, but that check does not includes bitwise ops:
For example we can currently check high bit like that:
```dart
import 'dart:typed_data';

int getMultiByteNumber(Uint8List bytes, int offset) =>
  switch (bytes[offset]) {
    < 0x80 => bytes[offset],
    >= 0x80 => ((bytes[offset] & 0x7f) << 8) + bytes[offset + 1],
    _ => throw Exception('Bad data'),
  };


void main(List<String> args) {
  print(getMultiByteNumber(Uint8List.fromList([0x80 + 0x7f, 0xff]), 0).toRadixString(16));
}
```
But such solution wont work with non high bit, e.g. 2nd bit or most low bit in first byte.
It would be great to have bitwise operations, so we could do this:
```dart
int getMultiByteNumber(Uint8List bytes, int offset) =>
  switch (bytes[offset]) {
    !& 0x80 => bytes[offset],
    & 0x80 => ((bytes[offset] & 0x7f) << 8) + bytes[offset + 1],
    _ => throw Exception('Bad data'),
  };
```

**Comment by lrhn** [comment]
There are lots of operations we can allow on the extracted values before testing them. Patterns are just not a very good place for computations. 

I'd argue for more expressive selectors in object patterns, but introducing specialized notation for some operations, and not other, doesn't feel like the way to go (to me).

You can already define
```dart
extension Bits on int {
   bool get bit0 => this & 1 != 0;
   bool get bit1 => this & 2 != 0;
   bool get bit2 => this & 4 != 0;
   // ....
}
```
and do
```dart
var bytes = bytes[offset];
switch (byte) {
  int(bit7: false) => byte,
  int(bit7: true) => ((byte & 0x7f) << 8) + bytes[++offset]
}
```
You even get exhaustiveness, because `int.bit7` can only have the values `true` or `false`.

You can probably also get the same effect here by ` >= 0 && < 0x80 => byte, _ => ((byte & 0x7f) << 8) + bytes[++offset]`, but that only really works for the most significant bit.

**Comment by Zekfad** [comment]
Looking at your solution, I found some workaround, though I don't really think that it's generally a good one, but it can work with more complex bitmasks:

<details>
<summary>mask.dart</summary>

```dart
import 'package:meta/meta.dart';


@immutable
class Mask {
  const Mask(this.mask, [
    this.strict = true,
  ]) :
    value = null;

  const Mask._value(this.value) :
    mask = null,
    strict = true;

  final int? mask;
  final int? value;
  final bool strict;

  @override
  bool operator==(Object? other) {
    if (identical(this, other))
      return true;
    if (other is! Mask)
      return false;

    final int _mask, _value;
    if (mask != null && other.value != null) {
      // Mask with value comparison
      _mask = mask!;
      _value = other.value!;
    } else if (other.mask != null && value != null) {
      // Value with mask comparison
      _mask = other.mask!;
      _value = value!;
    } else {
      // Not enough data.
      return false;
    }

    final _res = _value & _mask;

    return strict
      ? _res == _mask
      : _res != 0;
  }

  @override
  String toString() => 'Mask(mask: $mask, value: $value)';

  // There are no good way to produce some meaningfully hash code, such that
  // follows [operator==] semantics.
  @override
  int get hashCode => strict.hashCode;
}

extension MaskExtension on int {
  Mask get mask => Mask._value(this);
}
```

</details>

```dart
import 'dart:typed_data';
import 'mask.dart';

int getMultiByteNumber(Uint8List bytes, int offset) =>
  switch (bytes[offset]) {
    int(mask: const Mask(0x80)) => ((bytes[offset] & 0x7f) << 8) + bytes[offset + 1],
    _ => bytes[offset],
  };
```

**Comment by munificent** [comment]
I'm with Lasse. We want patterns to be expressive and cover lots of things, but it gets harder and harder to allow all possible expressions in there without colliding with syntax that we might want to use for actual *patterns*.

Allowing bitwise operators as relational patterns is unlikely to be helpful because the relational operator really needs to return *bool* so that we know whether the pattern is refuted or not, but bitwise operators generally return ints. I definitely do not want to introduce any notion of implicit truthiness for integer values.

Often, you can make patterns work by hoisting some of the computation up to the value expression, like:

```dart
int getMultiByteNumber(Uint8List bytes, int offset) =>
  switch (bytes[offset] & 0x80) {
    0 => bytes[offset],
    1 => ((bytes[offset] & 0x7f) << 8) + bytes[offset + 1],
    _ => throw Exception('Bad data'),
  };
```

Or if you want to do the computation separately for each case, you can move it into guards:

```dart
int getMultiByteNumber(Uint8List bytes, int offset) =>
  switch (bytes[offset]) {
    var b when b & 0x80 == 0 => b,
    var b when b & 0x80 == 0 => ((b & 0x7f) << 8) + bytes[offset + 1],
    _ => throw Exception('Bad data'),
  };
```

But, honestly, sometimes, it's just better to stick with a series of `if` statements.

**Comment by Zekfad** [comment]
Thanks for reply!
You're right guards seems like a better solution if there are some non-trivial masks.
