### ISSUE TITLE
Non-Null Type constraint is invalid on specific code

### ISSUE THREAD

**Issue by techwnn** [dart-lang/language#2887]
I’m using Dart 2.19, and I write code like below:
```dart
import 'dart:convert';

void main() {
  Map<String, String> map = (jsonDecode('''{"name":null}''') as Map<String, dynamic>).cast<String, String>();
  print(map["name"]);
  print(map["name"].runtimeType);
}
```

These code can run successfully and output:
 ```
null
Null
```
So the non-null String type constraint of ```Map<String, String>``` is invalid.

**Comment by ykmnkmi** [comment]
```dart
abstract class Map<K, V> {
  V? operator [](Object? key);
}
```

**Comment by lrhn** [comment]
Working as intended. The values are all non-nullable, but if you look up a key which isn't in the map, you get `null` back.

**Comment by mmcdon20** [comment]
@lrhn, If you add

```dart
  print(map.keys);
  print(map.values);
```

it prints

```
(name)
(null)
```

which suggests that the key/value pair is being stored in the map.

**Comment by mateusfccp** [comment]
You used the `cast` method, so you have a `Map<String, String>` view on top of a decoded `Map<String, dynamic>`. This means that the underlying map _is_ dynamic.

And, as documented by the `cast` method:

> Methods which accept Object? as argument, like containsKey, remove and operator [], will pass the argument directly to the this map's method without any checks. That means that you can do mapWithStringKeys.cast<int,int>().remove("a") successfully, even if it looks like it shouldn't have any effect.

**Comment by techwnn** [comment]
> You used the `cast` method, so you have a `Map<String, String>` view on top of a decoded `Map<String, dynamic>`. This means that the underlying map _is_ dynamic.
> 
> And, as documented by the `cast` method:
> 
> > Methods which accept Object? as argument, like containsKey, remove and operator [], will pass the argument directly to the this map's method without any checks. That means that you can do mapWithStringKeys.cast<int,int>().remove("a") successfully, even if it looks like it shouldn't have any effect.

Make sense, It seems that dart generic type grammar not constraint like what the source code intuition shows, but currently it seems like that all language with generic type grammar not has so intuition grammar like this:

```dart
class NoneNullGeneric<T> {} //define T represent for non-nullable.
class NoneNullGeneric<T?> {}//define T? represent for nullable.  dart not allow for define T? as generic type.
```

**Comment by lrhn** [comment]
We don't actually say it, but the `cast` map's `toString` is one of the methods which doesn't check types, because it doesn't need to.

Every place a `V` or `K` occurs in the the `Map` API, the `cast` map will do a type check on entry or exit, to ensure that propagating the arguments or return values to the underlying map is sound.

A `cast`'ed `Map` is sound, but not safe. It adds just enough runtime type checkes to avoid a value of a type to flow into a position where that type is not accepted, while making the result satisfy the static type system.

Where no `K` occurs, like in `containsKey`, the input is not tested. Similarly, anywhere a value is used, without needing it to be typed as `V`, we don't check it either. That includes both `toString` and `containsValue`, which only use `Object` methods on the values (`.toString()` and `==`).
