### ISSUE TITLE
[patterns] Promote the matched value type in logical-or patterns?

### ISSUE THREAD

**Issue by eernstg** [dart-lang/language#2912]
I noticed that promotions do not take place in certain situations involving a logical-or pattern (`p1 || p2`). The opportunities for doing any such thing are small, because the matching steps taken for `p2` can only rely on checks performed in `p1` insofar as they are unavoidable. As soon as `p1` checks anything which is able to fail, we must assume that the check did not take place or did not succeed.

For example:

```dart
void main() {
  int? i = 1 as dynamic;
  switch (i) {
    case var _! || > 0: print('Positive!'); // Compile-time error!
  }
}
```

The error messages report that `>` is not in the interface of a receiver of type `int?` (or that `>` cannot be invoked unconditionally, which is a symptom of the same underlying problem).

The conclusion is that the `!` in the left operand of `||` does _not_ give rise to a promotion of the matched value type which is used with the right operand, even though it would be sound to do so.

@stereotype441, @johnniwinther, do you consider this to be working as intended? (That is my first assumption.) Alternatively, do you consider the missing promotion to be a bug, possibly an exception in a sea of cases where it does work?

If it is working as intended, or this kind of promotion was planned, but hasn't been (nearly fully) implemented, then I'd recommend that we conclude that the promotion should not occur.

**Comment by lrhn** [comment]
It appears to work:
```dart
    int? q = 2 as dynamic;
    if (q case (< 0)! || > 0) print("q OK");

   FutureOr<int> f = 2 as dynamic;
   if (f case Future<int> _ || > 0) print("f OK");
```
succeeds. All my other tests also all show promotion along the failure branch of a `||` pattern.

I think the issue with the example of `var _! || > 0` is that `_!` either throws or matches, so there is no control flow into `> 0` at all, and therefore no control flow to pass promotion along. The second branch of `||` is dead code.

That's our usual dead-code problem. Dead code is unreachable, but we analyze it anyway.
We then have to decide an environment to analyze it in, and since we pass promotion information along control flow, and no control flow goes into dead code, no promotions can reach dead code. So dead code sees unpromoted values and variables only.

Confusing, but that's what analyzing dead code gives you. "This cannot happen, but if it happens ... something is wrong!" (Yeah, duh :wink:).

We could probably sometimes choose some branch as the hypothetical control flow into the dead code.

**It's less clear to me whether we can/should/do have control flow *out of* dead code.**
And to our implementations too, maybe:
```dart
    int? q = 2 as dynamic;
    if (q case (var x! || String x)) print(x);
```
This (on current DartPad, master branch) gives an analyzer error that `x` is introduced with two different types,
but runs in dart2js and prints "2". Turns out `x` has static type `dynamic`, so something is definitely off.
(And tip-of-tree VM and dart2js has same behavior.)

**Comment by eernstg** [comment]
Great, so it is working already after all!

No need to question that: Closing the issue.

**Comment by eernstg** [comment]
@lrhn, it looks like a separate issue about the "flows out of dead code" issue could be useful.
