### ISSUE TITLE
Don't perform value-transforming coercions during destructuring

### ISSUE THREAD

**Issue by munificent** [dart-lang/language#2914]
There are four implicit-coercion-ish things in Dart:

1. Int-to-double.
2. Implicit casts from dynamic.
3. Implicit call tear-offs.
4. Implicit generic function instantiation.

In the current proposal, any of these coercions may be inserted in code using patterns. In particular:

1. In pattern declarations and assignments, the context type of the pattern is used for downwards inference on the matched value. For example:

    ```dart
    T id<T>(T t) => t;

    var (int Function(int) f,) = (id,);
    ```

    Here, we calculate context type `(int Function(int),)` for the pattern and push that over to the initializer expression. That gets pushed into the field and `id` is coerced to `int Function(int)`, as if the user had written:

    ```dart
    T id<T>(T t) => t;

    var (int Function(int) f,) = (id<int>,);
    //                              ^^^^^
    ```

2. When a value is destructured by some pattern and passed to a subpattern. For example:

    ```dart
    T id<T>(T t) => t;

    var r = (id,);
    var (int Function(int) f,) = r;
    ```

    Here, the downwards inference context has no effect since `r` is just a variable lookup. Instead, the coercion of `id` to `int Function(int)` happens *after the record pattern extracts the field*. It's as if the user had written:

    ```dart
    T id<T>(T t) => t;

    var r = (id,);
    var (f_temp,) = r;
    int Function(int) f = f_temp;
    ```

Coercions from 1 are already implemented because the implementations already understand how to insert coercions based on context type. We get that "for free". In fact, the implementations don't even know or care if a context type applied to an expression came from a declared variable's type annotation, a pattern, or something else.

For scenario 2, int-to-double doesn't apply. That "coercion" only happens to integer *literals* based on context type.

Casts from `dynamic` do apply but don't require the compiler to insert an actual coercion. Instead, they are handled the same way other pattern type tests work where the pattern is refuted if the value isn't of that type. In an irrefutable context, that refutation becomes a runtime exception.

The other two coercions, call tear-offs and implicit generic function instantiation are not implemented for destructuring yet. What I've heard from @eernst and @johnniwinther is that doing so will be a significant amount of work.

It's not clear that it's useful to support either of these coercions during destructuring. We are considering removing support for call tear-offs from the language entirely because it causes a lot of implementation complexity for very little user value. If we do that, not supporting them in destructuring now will give us less to migrate if we remove support for them later.

I don't know how often implicit generic function instantiation is used, but I feel fairly confident we can live without it in destructuring. If it ends up being something users really want, we can always add it later.

Therefore, I suggest that we change the proposal to *not* insert value-transforming coercions during destructuring. This means that we do support:

1. All coercions when applied to a matched value expression based on the context type of the pattern, as already works today. So this works:

    ```dart
    class Callable {
      int call(int x) => x;
    }

    T id<T>(T t) => t;

    main() {
      var (double a,) = (123,);
      var (int b,) = (123 as dynamic,);
      var (int Function(int) c,) = (Callable(),);
      var (int Function(int) d,) = (id,);
    }
    ```

2. Implicit casts from `dynamic` during destructuring. This is allowed and works:

    ```dart
    var r = (123 as dynamic,);
    var (int f,) = r;
    ```

    And this is allowed but throws at runtime:

    ```dart
    var r = ('not int' as dynamic,);
    var (int f,) = r;
    ```

But we do not support:

1. Inserting call tear-offs when destructuring a value. So this is a compile-time error:

    ```dart
    class Callable {
      int call(int x) => x;
    }

    main() {
      var r = (Callable(),);
      var (int Function(int) c,) = r;
      // Error because Callaback is not a subtype of `int Function(int)`.
    }
    ```

    And this prints "No match":

    ```dart
    var r = (Callable(),);
    switch (r) {
      case (int Function(int) c,): print('Function record');
      case _: print('No match');
    }
    ```

2. Inserting implicit generic function instantiation when destructuring a value. So this is a compile-time error:

    ```dart
    T id<T>(T t) => t;

    main() {
      var r = (id,);
      var (int Function(int) d,) = r;
    }
    ```

    And this prints "No match":

    ```dart
    var r = (id,);
    switch (r) {
      case (int Function(int) c,): print('Function record');
      case _: print('No match');
    }
    ```

How does sound, @dart-lang/language-team, @johnniwinther, and @scheglov?

**Comment by eernstg** [comment]
Sounds great!

**Comment by scheglov** [comment]
Implicit call tear-off works in the analyzer, because I think it is also based just on the context type, and we know from where it came from. Just like when we do `(id,)`.
```dart
  solo_test_issue2914_1() async {
    await assertNoErrorsInCode(r'''
class A {
  T call<T>(T t) => t;
}

void f(A a) {
  // ignore:unused_local_variable
  var (int Function(int) v,) = (a,);
}
''');

    final node = findNode.singlePatternVariableDeclaration.expression;
    assertResolvedNodeText(node, r'''
RecordLiteral
  leftParenthesis: (
  fields
    ImplicitCallReference
      expression: SimpleIdentifier
        token: a
        staticElement: self::@function::f::@parameter::a
        staticType: A
      staticElement: self::@class::A::@method::call
      staticType: int Function(int)
      typeArgumentTypes
        int
  rightParenthesis: )
  staticType: (int Function(int))
''');
  }
```

De-composing and re-composing `RecordType` indeed does not work, and it would be a special resolution node kind, just like `FunctionReference` is a special node kind.
```dart
  solo_test_issue2914_2() async {
    await assertErrorsInCode(r'''
T id<T>(T t) => t;

main() {
  var r = (id,);
  // ignore:unused_local_variable
  var (int Function(int) d,) = r;
}
''', [
      error(CompileTimeErrorCode.PATTERN_TYPE_MISMATCH_IN_IRREFUTABLE_CONTEXT,
          87, 19),
    ]);

    final node = findNode.singlePatternVariableDeclaration.expression;
    assertResolvedNodeText(node, r'''
SimpleIdentifier
  token: r
  staticElement: r@35
  staticType: (T Function<T>(T))
''');
  }
```

**Comment by eernstg** [comment]
Thanks, @scheglov! This confirms what I expected at this point. In the first example, coercions take place in the initializing expression because of its context type schema, and we can get the same behavior by declaring a record:

```dart
class A {
  T call<T>(T t) => t;
}

void f(A a) {
  var (int Function(int) v,) = (a,); // Performs coercions on a, yielding `(a.call<int>,)`.
  (int Function(int),) record = (a,); // Ditto, "I don't care where that context came from".
}
```

This kind of coercion is not being debated, it's just a special case of the type of coercion we have had for years, and nobody is suggesting that we should change that.

In the second example, the intention was actually never to decompose and recompose the record (the language team specifically did not want to introduce that kind of semantics).

The intention was that the coercions should occur as part of the semantics of pattern matching. The language team supported the interpretation (as a rough approximation, not as a specification), that this mechanism should work in a way which is similar to standard coercions applied to variable declarations which are created by a desugaring step that eliminates patterns:

```dart
T id<T>(T t) => t;

main() {
  var r = (id,);
  {
    var (int Function(int) d,) = r; // Compile-time error, as implemented.
  }

  {
    // Desugared code, showing how it could work. This particular pattern declaration
    // desugars to just one single variable declaration.
    int Function(int) d = r.$1; // Coercion applied as usual, yielding `r.$1<int>`.
  }
}
```

One point which is worth noting is that coercions could occur in the initialization of temporary variables rather than the ones that are introduced explicitly by variable patterns or identifier patterns. For example:

```dart
class A {
  X call<X>(X x) => x;
}

void f(A a) {
  {
    var Function(call: int Function(int) f as X Function<X>(X)) = a;
    f(1);
  }
  // Desugar-ish illustration.
  {
    Function tmp1 = a; // Coercion occurs, yielding `a.call`.
    var tmp2 = tmp1 as X Function<X>(X);
    int Function(int) f = tmp2; // Coercion yields `tmp2<int>`.
  }
}
```

In this example, `a` is coerced into `a.call` in order to become the matched object for the `Function` object pattern, and in a subsequent step that matched value is subject to a type cast, confirming that it is an `X Function<X>(X)`, which is then subject to generic function instantiation, `...<int>`. The 'desugar-ish' block shows how these steps can be expressed in code.

This illustrates that it is possible for some of these coercion results to be implicit in the pattern (e.g., we're applying a coercion to `tmp2` above, but `tmp2` has no explicit representation in the pattern syntax).

**Comment by lrhn** [comment]
If we want to get rid of implicit `.call` tear-off, the this is only really about generic instantiation.

My guess is that it won't matter, because the pattern of doing `var (InstantiatedFunctionType, ...) = recordWithGenericFunctionType;` is simply not going to happen in practice.

If you expect an `int Function(int)`, you probably won't be creating a separate record containing a `T Function<T>(T)` first and the destructuring it.

It makes sense in a parallel assignment with a record literal like `var (int Function(int) f, int i) = (id, 2);`, but there you get the context type on the RHS and do the instantiation before creating the record.

Creating a composite value containing a generic function *without* a context type, and then trying to coerce part of it during destructuring, is simply not a pattern I can see a use for.

So :+1: to just not allowing it until it turns out to be actually useful. Especially if it makes implementation easier.

**Comment by eernstg** [comment]
Just in case: https://github.com/dart-lang/language/pull/2916.
