### ISSUE TITLE
[void] Extensions on values of type void could be compile-time errors.

### ISSUE THREAD

**Issue by modulovalue** [dart-lang/language#2919]
Consider the following:

```dart
extension VoidExtension on void {
  int get foo => 1;
}

void main() {
  void a = 0;
  a.foo;
}
```

As expected, it doesn't compile because it fails on `a.foo`.

~Since no member of a value of type void is meant to ever be invoked, being able to declare static extensions on values of type void seems quite literally useless~?

Edit: This is not entirely correct see: [comment](https://github.com/dart-lang/language/issues/2919#issuecomment-1472164755)

This behavior ~is~ _seems_ slightly inconsistent with the treatment of void wrt typeCasts and typeTests where void on the rhs is a compile-time error. I personally think that either extensions on void (_and castPatterns on void_) should be a compile-time error **or** that typeCasts and typeTests should support void on their rhs.

Cf. https://github.com/dart-lang/language/issues/2897
Cf. https://github.com/dart-lang/language/issues/2898

_Note: It could be useful to use such extensions on void to simulate namespaces, but extensions on Never can be used instead which would make more sense to me._

**Comment by eernstg** [comment]
The choice of `void` as the on-type of an extension is actually not the same thing as having a receiver of type `void`, and trying to invoke an extension member (which is always an error, cf. [this commentary](https://github.com/dart-lang/language/blob/abca38c39e9bea0af2ff47fce55d6686207178e7/specification/dartLangSpec.tex#L6266)). Consider this example:

```dart
extension on void {
  void foo() => print('Does not use this!');
}

void main() {
  1.foo();
}
```

This works, because it is possible to invoke an extension method on a receiver of type `int` (any type whatsoever would work). The extension declaration itself behaves in a particular way when the on-type is `void`, because this means that it is (with the usual exceptions) a compile-time error to use `this`. In other words, it serves as a hint that this extension doesn't use the receiver.

**Comment by jakemac53** [comment]
Is there any difference between an extension on `void` and an extension on `Object?`?

**Comment by eernstg** [comment]
The original idea in this issue was to rule out extensions on `void` because they are useless; I think this idea is applicable to `Never`:

```dart
extension on Never {
  // Whatever. It's all dead code, unless `static`.
}
```

The reason why this kind of extension is useless is that the receiver is required to have the static type `Never`, which by soundness implies that it will never evaluate to an object (it could be an infinite loop, and it could throw), and this implies that no instance members in the body could ever be executed. On top of that, they won't even be applicable in the first place, because a receiver of type `Never` is assumed to have all instance members, with all signatures, so there will always be an instance member which will shadow each of the extension instance members in that extension on `Never`.

**Comment by modulovalue** [comment]
> The reason why this kind of extension is useless is that the receiver is required to have the static type Never,

We can use extension on Never to simulate namespaces:

```dart
extension FooNamespace on Never {
  static int get foo => 0;
}

void main() {
  FooNamespace.foo;
}
```

That way, FooNamespace does not introduce any declaration that can be implemented mixed in or instantiated. (I'm not saying that this should be used, but it's not entirely useless.)

**Comment by mateusfccp** [comment]
We had this proposal in Flutter: https://github.com/flutter/flutter/pull/105210

But with the upcoming closed classes it will be better.

**Comment by modulovalue** [comment]
In any case, I think Never is a different type that is not really related to this issue.

---

Erik said:
> The original idea in this issue was to rule out extensions on void because they are useless;

That is only partially true.

void already gets special treatment in many other ways. According to the grammar, it can't be nullable (void?). It is a compile-time error for it to appear on the rhs of typeTests and typeCasts, but it can appear on the rhs of castPatterns. The main idea idea of this issue (_and the ones that I've linked at the bottom of the issue description_) is to make void behave in a way that is easier to understand and teach.

As I said in https://github.com/dart-lang/language/issues/2919#issuecomment-1472274864

> It appears to me that currently, the main purpose of void is to be a return type that stands for returning nothing.

I think it would make sense to focus on making void best for that objective. And being able to declare extensions on void is not helpful in that regard.

**Comment by lrhn** [comment]
There are lots of unnecessary things we could make compile-time errors. Dead code, `implements Object`, `extension on Never`, `Never x;`, `Null x;`, `if (true) { ... }`.

We don't make it errors for two reasons:
* Sometimes such things occur during development or refactoring, and you'll be fixing it anyway. Making things errors too soon just forces you to do more work before you can get to a useful intermediate state.
* It's easier and more maintainable to not add extra code to catch these cases to all our tools.

The analyzer can still warn about anything that looks weird, without it having to be written into the language specification.
If anything, they can do *better* than what we could possibly specify, because they can run more complicated analyses on your code than we could ever specify into the language. They can recognize specific patterns, maybe something that is used in Flutter and nowhere else, and choose to not warn in that case.

I think the best design goal for the *language* is to not try to prevent something for stylistic reasons, if we can assign it a perfectly well-defined semantics. Might not be useful, but deciding what's useful and what is not, is a never-ending task.
Better to just not go there in the formal specification, and let tools with better heuristics give users the warnings they actually need./

**Comment by modulovalue** [comment]
> There are lots of unnecessary things we could make compile-time errors. Dead code, implements Object, extension on Never, Never x;, Null x;, if (true) { ... }.

I agree with everything you said. Of course there's no reason to make any of them compile-time errors, but I don't think that your argument applies here because `implements void`, `extends void`, `with void`, `mixin ... on void` are already compile-time errors. Disallowing the last remaining clause `extension on void` from being able to contain void is not unnecessary, but makes the language (in my opinion) feel more consistent.

---

I have looked at this issue from a different angle and now I think that it doesn't go far enough because `dynamic` is in a very similar position. Considering void alone here would introduce confusing "inconsistencies" in other places, therefore I'm going to close it for now.
