### ISSUE TITLE
`JDK 12 like switch` with `sealed class` can't use default case. 

### ISSUE THREAD

**Issue by jpoh281** [dart-lang/language#2928]
Include a permanent link to the error if possible.

https://help.github.com/en/articles/getting-permanent-links-to-files

sealed class
```dart
sealed class Either {}

class Left extends Either {}

class Right<T> extends Either {
  T data;

  Right(this.data);
}

```

It's not error.

```dart
  switch (either) {
    case Right() when either.data is String:
      return true;
    default:
      return false;
  }
```

it's error. with this message
"The type 'Either' is not exhaustively matched by the switch cases.  Try adding a default case or cases that match Either."

```dart
 var switchResult = switch (either) {
    Right() when either.data is String => true,
    _ => false
  };
```

Did I use the wrong switch?
Or I wonder if this  is error.

**Comment by lrhn** [comment]
This is expected behavior.

The `Either` type is sealed, so you are expected to do exhaustive switches on it.

The switch you wrote is not exhaustive, because it doesn't cover, for example, `Right<int>(1)`.

In general, any `case` with a `when` clause does not count towards exhaustiveness, because the compiler does not believe it's smart enough to understand general expressions. Patterns are limited in what they can express, which is why exhaustiveness has a chance of working, but a `when` clause can call arbitrary functions. This one doesn't, but again, the compiler just doesn't try to be clever when it sees a `when`.

**Comment by jpoh281** [comment]
I understand what you mean. Thank you for your answer.

But wouldn't it be a little confusing if the existing switch and JDK12 like switch don't say the same error?

**Comment by mraleph** [comment]
@jpoh281 I think what you were seeing was just a bug. If you have `_ => ...` case - then you should not get any exhaustiveness errors. 

It does not reproduce on the current version (3.0.0-336.0.dev). Which version were you using?

**Comment by jpoh281** [comment]
I use 236.0.dev.
I'll try this 336.0.dev!

**Comment by jpoh281** [comment]
> @jpoh281 I think what you were seeing was just a bug. If you have `_ => ...` case - then you should not get any exhaustiveness errors.
> 
> It does not reproduce on the current version (3.0.0-336.0.dev). Which version were you using?

I used 3.0.0-236.0.dev.
and I try 3.0.0-322.0.dev. no problem! Thank you.
