### ISSUE TITLE
It is possible for initialization order to result in infinite recursion

### ISSUE THREAD

**Issue by lukehutch** [dart-lang/language#2932]
The following code results in infinite recursion at the line `final b = X(2)..y();`:

```dart
class X {
  int n;
  X(this.n) {
    print('X($n)');
  }
  void y() {
    print('b.n: ${b.n}');
  }
}

final a = X(1)..y();
final b = X(2)..y();

void main() async {
  print(a);
}
```

There should be no infinite recursion here -- instead `X(1)` and `X(2)` should be initialized first, then in a second pass, `X(1)..y()` and `X(2)..y()` should be run.

**Comment by eernstg** [comment]
This is actually working as intended. There used to be a `CyclicInitializationError` which would kick in at the point where the evaluation of the initializing expression of `b` is ongoing, and `b` is evaluated again (which is what we have here). But this feature had a non-trivial performance/complexity cost, and it was removed as of Dart 2.12.

There is no way we could introduce a semantics whereby the initialization of `a` and `b` could be interleaved (such that we'd obtain the result `X(1)` and the result of `X(2)` first, and then initialize `a` and `b` to refer to those two objects, and then invoke `y()` on each of them). That would be a radical departure from Dart as we know it.

It may seem more correct or convenient to detect the cyclic initialization as a language feature, but today's trade-off is that we need to debug this kind of infinite loop just like any other infinite loop.

**Comment by julemand101** [comment]
@lukehutch
It is a major change to the language because of the following design choice:

> Top-level and class variables are lazily initialized; the initialization code runs the first time the variable is used.
https://dart.dev/language/variables#default-value

Dart does not have the concept of side effects just by importing a file since static/global fields will first be initialized at first access.

**Comment by eernstg** [comment]
Agreeing with @julemand101, there's actually one more layer to this characterization as a radical change:

`var b = X(2)..y();` could not be initialized without evaluating all of the initializing expression `X(2)..y()`, which means: Evaluate `X(2)` to an object `o`, then invoke `o.y()` and discard the result returned from `y`, then yield `o`. This means that the value of the initializing expression can only be obtained by taking actions that include the invocation of `y()`, and this again means that we need to know the value of `b` during the evaluation of the expression that initializes `b`.

It would in principle be possible to perform parts of this computation, then suspend (like `await` in an `async`/`async*` function body) and do other things (e.g., initializing `a`), and then at some point return to the initialization of `b`, in this case by calling `o.y()`.

But this is a radical change because Dart code doesn't arbitrarily suspend and switch to other activities, you have to explicitly write `await` in order to achieve interleaved execution (and you'd use futures in order to control the ordering dependencies and data flow). Another issue is that we can't say in general that the value of an expression is available in the middle of the evaluation of the expression. For instance, `x..y()` could change the state of `x` during the execution of `y()`, and this means that it would be semantically wrong to just evaluate `x` and deliver it to the receiver of the value of the whole expression, and then execute `y()` at some later point in time. If we do that then the receiver of the value of `x` would see the object in a state which is different from the one that it should have received, and all kinds of bugs could occur because those changes made by `y()` haven't yet occurred.

I'll stick to 'radical'. ;-)

**Comment by lukehutch** [comment]
OK, good point that y could have side effects that change x. Thanks for explaining.

Could cycle detection be implemented more cheaply by marking objects that are currently being initialized, in-place, rather than using a set or similar to track the nodes in the initialization path?

**Comment by eernstg** [comment]
Thanks!

> marking objects that are currently being initialized

That was exactly how it was done. A special value would be stored in the variable storage location (violating the Dart level type system, because it would be a primitive value, not an instance of the declared type --- but the runtime was able to handle that). However, it wasn't considered valuable enough to keep, and this means that it isn't likely to be re-introduced.
