### ISSUE TITLE
Allow empty switch expressions

### ISSUE THREAD

**Issue by munificent** [dart-lang/language#2939]
The switch expression grammar requires there be at least one case. I'm certain that almost all switch expressions should and will have cases, so this isn't much of a restriction. However:

Imagine you have a `sealed` class that currently has no subclasses. You are beginning to sketch out code to work with that class and its yet-to-be-created subclasses. You'd like to write a placeholder that consumes values of that `sealed` type, matches all of their subtypes, and produces a value. If we allowed empty switch expressions, you could write:

```dart
int doSomethingWithSealedClass(MySealedClass s) => switch (s) {};
```

The type of an empty switch would be `Never`, so this code is valid. Also, the switch should be reported as exhaustive because the zero cases do cover all zero values that can ever flow into it.

Then, later, you start adding some subtypes of the sealed type. When you do, the compiler will now tell you that all of the empty placeholder switches you wrote are no longer exhaustive and point you to all the places in the code that need to be updated to handle the new subtype.

This is certainly not the most important use case for Dart, but it does seem reasonable.

**Comment by mateusfccp** [comment]
What would happen if I try to use the value returned by `doSomethingWithSealedClass`? Will we get a runtime exception?

**Comment by leafpetersen** [comment]
> What would happen if I try to use the value returned by doSomethingWithSealedClass? Will we get a runtime exception?

If `MySealedClass` has no subclasses (if it did, the switch would have an exhaustiveness error), then it has no instances, and hence there is no way to call `doSomethingWithSealedClass`.

**Comment by lrhn** [comment]
And since we've dropped support for non-null-safe code and unsafe null-safe mode, there should be no way for a `null` to flow into the `MySealedClass` variable.
(And if we do end up in unsafe null-safe mode for any backwards compatible reasons, it's "not-more-unsafe" to yield `null` from the switch expression.)

**Comment by stereotype441** [comment]
The current behaviour of the implementations is:
- front end: an empty switch expression leads to an error.
- analyzer: an empty switch expression is allowed, and has type `dynamic`.

We've marked this issue as `patterns-later`, but given that the analyzer and front end behave inconsistently, we ought to fix the inconsistency now.  And I suspect that fixing the CFE to allow empty switch statements might be just as easy as fixing the analyzer to prohibit them.

I'll make a quick experimental CL to see if I can get the CFE to allow empty switch statements.  If that works, I think we should just go ahead and do it now.

**Comment by lrhn** [comment]
An empty switch expression must have static type `Never`. 
Obviously it could have any type, since it won't complete with a value anyway, but using `dynamic` seems wrong. (No more implicit dynamics, please.)

A switch expression must be exhaustive, and the only way to be exhaustive is to have a known empty type to switch over. I assume that's currently only sealed classes with no subtypes. (Could include `Never` too, don't know if we count it.)

That means that we can't just change the front-end to match the analyzer, we also need the analyzer to change its type inference.

**Comment by stereotype441** [comment]
> An empty switch expression must have static type `Never`. Obviously it could have any type, since it won't complete with a value anyway, but using `dynamic` seems wrong. (No more implicit dynamics, please.)
> 
> A switch expression must be exhaustive, and the only way to be exhaustive is to have a known empty type to switch over. I assume that's currently only sealed classes with no subtypes. (Could include `Never` too, don't know if we count it.)
> 
> That means that we can't just change the front-end to match the analyzer, we also need the analyzer to change its type inference.

Good point.  Fortunately that's a one-line change, and it's in logic that's shared between the CFE and the analyzer.  I'll include it in my experimental CL.

**Comment by stereotype441** [comment]
As I suspected, changing the front end to allow empty switch expressions (and changing the shared analysis to give them a static type of `Never`) was pretty straightforward.  Here's my CL that does it: https://dart-review.googlesource.com/c/sdk/+/290907.  It passes all tests except for one failure on dart2js (which crashed the compiler).  I'll send it to @johnniwinther and @chloestefantsova for review, but I won't land it unless I get a consensus from the language team that this is the direction we want to go in.

**Comment by lrhn** [comment]
Sure, ship it. I seriously doubt it will be used for anything (we haven't allowed it in statement switches until now, and nobody noticed), but it also doesn't hurt. 
We *can* give it a semantics, and I'm sure a compiler can omit generating extra code for an empty switch, should one occur.

And it does means that an intermediate program is valid and *parses*, before you add any cases to a switch, which means you can format it.  (It's annoying if you can't format a program because of a non-grammatical error.)

**Comment by leafpetersen** [comment]
LGTM.
