### ISSUE TITLE
Dart is not LR(1)?

### ISSUE THREAD

**Issue by modulovalue** [dart-lang/language#2972]
I'm trying to write a grammar for Dart that is meant to be consumed by a custom LR-style parser generator.

Consider the following incomplete Dart program:

```dart
void foo(int Function() Function...
```

It looks like a straightforward and unambiguous LR(1) Dart grammar can't exist because a single token of lookahead is not enough to disambiguate whether the example above contains e.g.:

* A parameter called `'Function'` where `'Function'` has the type `'void Function()'`:

```dart
void foo(void Function() Function) {}
``` 
or
* A parameter `P` where `P` is a function that returns `'int Function()'`:

```dart
void foo(int Function() Function() P) {}
``` 

I think I've captured this observation in the following CFG (_i.e. a Function with arbitrary many function tails where the last tail can be followed by a Function identifier_):
```
# This uses Grammophone (https://mdaines.github.io/grammophone) syntax.
S -> Fn Identifier.
Identifier -> 'Function'.
Fn -> ReturnType Tails.
ReturnType -> 'Function'.
Tails -> Tails Tail.
Tails -> Tail.
Tail -> 'Function'.
```

If we paste this snippet into [Grammophone](https://mdaines.github.io/grammophone), we can see that it isn't LR(1).

---

If this observation is correct, I'm wondering what a clean way to resolve this ambiguity would be? Has this ever been discussed by the Dart team and/or is there a simple solution to this issue that I'm missing? I'm currently considering either going the 2-token lookahead route where I think even SLR(2) should be enough to resolve this ambiguity, or explicitly maintaining the ambiguity via GLR.

**Comment by eernstg** [comment]
That is true, Dart isn't LR(1). One reason is that there is a plain ambiguity: `f(a<b,c>(d))` could be an invocation of `f` passing two actual arguments (both relational expressions), but it could also be an invocation of `f` passing one actual argument which is an invocation of a generic function `a` passing two actual type arguments and one actual value argument. This ambiguity is specified outside the grammar to be resolved in favor of the second choice.

Another ambiguity arises when a local function declaration has an annotation:

```dart
const c = 0;

void main() {
  @c(int, int) f() => throw "The return type isn't always obvious";
}
```

This ambiguity arises because `@c` could be metadata, but so could `@c(int, int)` (where `c` would be a class with a constructor that accepts two positional parameters of a type that admits `Type`). Under the first choice the local function would return a record of type `(int, int)`, and under the second choice the return type would have been omitted.

This ambiguity could be expressed in a grammar where whitespace is handled more explicitly, but it is currently specified outside the grammar to be resolved in favor of the second choice when there is no whitespace (including comments) between `@c` and `(`, and in favor of the first choice when there is some whitespace.

A third reason is that the Dart syntax has always been specified in terms of a grammar where the rules are prioritized in textual order (like ANTLR). You could probably model this by adding a priority to every alternative in every rule of the grammar (or by using some other pseudo-grammatical device, whatever your tool chain supports).

This probably illustrates that the development of the Dart syntax has given a higher priority to the ability to use familiar syntactic forms (e.g., passing actual type arguments to a function call just before the `(...)` part, not before the function name), rather than staying within the boundaries of foundational language classes.

I hope you'll be able to do what you need to do anyway, but it is a non-trivial problem to parse Dart using any kind of LR parser.

**Comment by lrhn** [comment]
Originally it was the idea that the identifier `Function` followed by a `(` or `<` token should always and only match the function-type production. I don't think that ever made it into the specification, because the parsers handled the parsing without that escape.

The Dart *lexical* grammar is also ambiguous, since `>>` should be a single token, but in `List<List<int>>`, it's not.

The parsers have various strategies to make parsing easier, one being counting and matching braces during tokenization (with the above issue making that harder), so that when seeing `identifier(`, it can quickly check whether the closing `)` is followed by `{` or `=>` or another token suggesting a function declaration, and if not, parse it as a function invocation.
Often, but not always, a single token-after-closing-delimiter lookahead is enough.

**Comment by modulovalue** [comment]
Erik, thank you for the examples of other ambiguities that one needs to be aware of. (_And for all the other examples that you have shared throughout the years in various places, they are all very helpful._).



> The Dart lexical grammar is also ambiguous, since >> should be a single token, but in List<List<int>>, it's not.

Erik has proposed a simple solution to this problem in a different issue that I have successfully implemented. (The idea is not to lex any composites '>>>' but only '>' and to parse '>>>' as `'>' NO_WS '>' NO_WS '>'` where `NO_WS` is a hint to the NFA generator not to create epsilon transitions to whitespace there.)

> Originally it was the idea that the identifier Function followed by a ( or < token should always and only match the function-type production.

I see, this seems to make sense to me and I haven't considered this approach yet, I'll have to think more about how this fits into my current system, thank you.

**Comment by modulovalue** [comment]
Given that there are quite a few ambiguities, it might be more productive for me to directly try to use GLR, and to deal with improving its performance by resolving ambiguities manually later.

I think that GLR would also solve the `Function` ambiguity by effectively giving me unbounded lookahead. I'm going to try to take that approach.

**Comment by eernstg** [comment]
Thank you for the kind words! I hope it works!
