### ISSUE TITLE
Purpose of required before named non-nullable arguments

### ISSUE THREAD

**Issue by MohammedAsaadAsaad** [dart-lang/language#2989]
I'm wondering what is the purpose of 'required' key word used with named non-nullable arguments?!
After null-safety, do really we need to put 'required' before the non-nullable named argument?
Implicitly, the compiler consider it as required and forces the developer to use it, so. why we need to write it?
Thanks.

**Comment by mateusfccp** [comment]
Duplicate: #1502, #878.

**Comment by lrhn** [comment]
Yep, as discussed before, the `required` is still required in function *types*, because it's possible to have an optional non-nullable parameter with a default value, and function types don't include the default value.
In actual functions, it's technically only needed if you have a nullable required parameter, because the presence of a default value would mean optional, and its absence would then imply required for non-nullable types.

But for consistency and simplicity, `required` is required on every required named parameter, everywhere.
