### ISSUE TITLE
Create a "bytecode" for Dart

### ISSUE THREAD

**Issue by feinstein** [dart-lang/language#2992]
Currently dart can be compiled to native or run as a script. This script has to be interpreted and this (I suspect) isn't very perfomant.

If we could also compile dart to an intermediate representation, like other languages have, such as Java bytecode, .NET Common Language Infrastructure, etc. I suspect we could gain a big performance leap while running Flutter apps in debug mode, with hot reload.

I know there's a big effort right now to compile dart to WASM, and WASM could even be that intermediate representation, but AFAIK it can only be run inside a browser, not in the dart VM.

I don't know what's the best path forward, if it's to create dart bytecode, or make the dart VM run WASM, I just want to plant the seed of this new idea, as I think it would be very positive for the Flutter development experience and even enable Code Push for iOS, without affecting so much the app's performance.

PS: This is all based on my assumption that scripts are slower than bytecode, which I believe it's true, since WASM or Java are, in many cases, faster than Javascript. But you are the language experts, not me, so I would love to know your opinions on this.

**Comment by feinstein** [comment]
> Dart is also never interpreted from the source - the VM always runs from a kernel file

So you are saying I can generate a kernel file and give the dart VM a command to execute that kernel file? So I could achieve Code Push using kernel files right now?

> As for code push, that would actually be less performant as it would require bundling a compiler into an app/program, which takes up both time when the program is running and space in the resulting file. It would be a (relatively) huge performance loss.

But if we are dealing with bytecode there's no need to a compiler, the VM can execute the bytecode directly. As I understand that's what the VM already does with the kernel files.

**Comment by abitofevrything** [comment]
> So you are saying I can generate a kernel file and give the dart VM a command to execute that kernel file? So I could achieve Code Push using kernel files right now?

No, code push is not possible to precompiled apps as those required code to be compiled down to platform-specific code, which the kernel is not, hence the need for a compiler.

> But if we are dealing with bytecode there's no need to a compiler, the VM can execute the bytecode directly. As I understand that's what the VM already does with the kernel files.

I'm not sure if the VM in debug mode can directly run kernel files, but in release mode you will always need to compile to native code.

If you want to create a kernel file, use `dart compile kernel <my_program>` which will generate a `.dill` file you can pass to `dart run` to execute it.

**Comment by feinstein** [comment]
I see... So I guess dart kernel files would behave similarly to WASM. Do you want me to close this issue?

**Comment by munificent** [comment]
> Currently dart can be compiled to native or run as a script. This script has to be interpreted and this (I suspect) isn't very perfomant.

It is probably much more performant than you expect. The VM is compiling the script to machine code either way, it's just a question of whether it does so ahead of time, or [when the script is run](https://en.wikipedia.org/wiki/Just-in-time_compilation).

> If we could also compile dart to an intermediate representation, like other languages have, such as Java bytecode, .NET Common Language Infrastructure, etc. I suspect we could gain a big performance leap while running Flutter apps in debug mode, with hot reload.

Most JVM and CLR implementations are also just-in-time compiling to machine code before running, so they all have similar performance characteristics. Whether you JIT compile from source, a kernel-like format, or bytecode, has little effect on the resulting runtime performance. (It may affect *compile* time performance.)

> I don't know what's the best path forward, if it's to create dart bytecode, or make the dart VM run WASM, I just want to plant the seed of this new idea, as I think it would be very positive for the Flutter development experience and even enable Code Push for iOS, without affecting so much the app's performance.

Code push is a separate goal and definitely an interesting one, though it's a hard, complex problem.

> PS: This is all based on my assumption that scripts are slower than bytecode, which I believe it's true, since WASM or Java are, in many cases, faster than Javascript.

WASM and Java are faster than JavaScript mainly be JS is dynamically typed and extremely mutable. JVM and JS implementations work fairly similarly under the hood. (And, in fact, the dominant JVM and JavaScript VM implementations
were created by some of the same people using the same techniques.)

I'm going to close this because I don't think there's anything actionable here at the language level.
