### ISSUE TITLE
In dart3, the use of break in the case of the switch should prompt warning?

### ISSUE THREAD

**Issue by Silentdoer** [dart-lang/language#3068]
Because of dart3, the switch's case is also broken by default without break keyword.

**Comment by munificent** [comment]
I'm not sure what you mean by "broken by default". An empty switch case behaves exactly the same in Dart 3.0 as it did before: It falls through to the next case.

If you want a switch case that does nothing but exits the switch, you have to write a `break;`. That was true before Dart 3.0 (because *all* cases needed a break) and is still true in 3.0 even though other switch cases no longer need breaks.
