### ISSUE TITLE
Implicit conversions for records

### ISSUE THREAD

**Issue by listepo** [dart-lang/language#3069]
It would be nice to be able to automatically convert one record to another if the first contains all the fields of the second.
For example:
```dart
typedef User = ({String firstName, String lastName});
typedef UserWithBalance = ({String firstName, String lastName, double balance});

final UserWithBalance userWithBalance = (firstName: 'Jane', lastName: 'Doe', balance: 34.3);
final User user = (firstName: 'Jane', lastName: 'Doe');

String getFullName(User user) {
  return '${user.firstName} ${user.lastName}';
}

final fullName = getFullName(userWithBalance); // should work

```

**Comment by lrhn** [comment]
There are two kinds of conversions possible: Projections and spreads.

We should get spreads, where you inject one record into a larger space: `(int, int) p1 = (1, 2); (int, int, int, int) p2 = (...p1, ...p1);`.
That seems like a no-brainer. (And spreading records into argument lists too.)

Projections, where you take *some* of the fields of a record, but not all, are not as obvious syntactically.

First of all, is should definitely be an entirely compile-time operation. We do not want to check at runtime whether one record type has a shape which is somehow compatible with another record type. We want to be able to compile away all the unnecessary structure information at runtime (like, say, names of fields).

And we do not want `User` to be a supertype of `UserWithBalance`. The two records are completely separate, because that allows code to inline and unbox a `User user` variable and rebuild a `User` object from it later if necessary. If the unboxing started with a `UserWithBalance` and threw away some of the fields, it could never rebox and get the original back.


The suggested approach here *can* work: We make record types *assignable* to a smaller record type, one that has a subset of the original record type's fields (fewer positional fields, fewer named fields), by taking the values of the fields that the smaller type has.
That introduces an implicit coercion, so `getFullName(userWithBalance)` is implicitly equivalent to `getFullName((firstName: userWithBalance.firstName, lastName: userWithBalance:lastName))`.

It should work recursively, so:
```dart
 ((int, int), (int, int)) pairs = ((1, 2), (3, 4));
 ((int,),) single = pairs; // equivalent to: = ((pairs.$1.$1,),)
```
It's not type based, so `(int, String, bool) trip = (1, "2", false); (int, bool) dup = trip;` would fail because the `$2` of type `String` is not assignable to `bool`.

It can work, but implicit coercions can be dangerous.
It can hide bugs.
It can be more costly than expected.
It's harder to debug, because it introduces code that isn't there in the original program.

Also, *why stop there*. If an `(int, int)` record is assignable to `(int,)`, why not make it assignable to `int` directly. We're not preserving structure anyway. It's not converting a record to a record, but why should that be special to begin with? It's just a convenient and safe conversion. (Sure, it's a bad idea, but what makes it bad, and assignment between records not bad?)

In the other direction, we could also allow record-coercion from non-records. Say:
```dart
class Point {
  final int x, y;
  Point(this.x, this.y);
}

Point point = Point(1, 2);
({int x, int y}) coordinates = point;
```
The coercion from "something which has `x` and `y` getters assignable to `int`" to `({int x, int y})` is precisely the same as the one suggested above from records. Records are just unrelated classes in that regard.

But it's a much harder sell, because it has even more risk of accidental assignment of something which shouldn't have been converted to a record. 
Maybe because classes have a meaning other than being the collection of its getter values, and that is lost in the conversion, where a record is just its data, and extracting some of that data is not omitting anything.

I'm split, but mostly against adding such coercions (also because I'm slightly against adding very general coercions to begin with).


I don't think introducing an explicit projection syntax is worth it.
If you could write:
```dart
  getFullName(userWIthBalance{firstName,lastName});
```
to extract the `firstName` and `lastName` fields from the record, I don't think it's general, or powerful, enough, compared to the verbosity that it still requires.

**Comment by listepo** [comment]
Thanks for the reply, very interesting suggestions.

**Comment by listepo** [comment]
```dart
getFullName(userWIthBalance{firstName,lastName});
```
 doesn't look too bad in my opinion

**Comment by munificent** [comment]
We're definitely interested in spreading records into other records, and I think there are other open issues to track that. I think it's unlikely that we'd want to allow *implicitly* converting a record of one shape to another, so I'm going to go ahead and close this out, but thank you for the suggestion.
