### ISSUE TITLE
Dart's increasing complexity (Question)

### ISSUE THREAD

**Issue by renlite** [dart-lang/language#3070]
It is good and necessery Dart gets new language features but it seems this happens to the disadvantage of consistency and compiling performance.

As an example there are the new "Class Modifiers". To offer a stricter API-description is a good way but still support the old flexible Class/Mixin syntax rises the complexity.

From: https://github.com/dart-lang/language/blob/main/accepted/future-releases/class-modifiers/feature-specification.md
`With order and duplication out of the way, that leaves 127 possible combinations of the 7 keywords. The remaining error cases (and their associated IDE fixups) are:`

The trend of most new programming lanquages is simplicity and the try to offer a better manual memory management or to switch from GC to compiler managed manual memory.

Are there plans to reduce the complexity and to make Dart a more multi purpose programming lanquage, so Dart could be a simpler alternative in some areas of C/C++ in the future?

**Comment by munificent** [comment]
I agonized over the increasing complexity of the new features in Dart 3.0. I literally lost sleep over it.

It's a very hard balancing act to decide which features carry their weight, and I constantly worry that the language is becoming too complex.

At the same time, most of the world's successful languages *are* fairly large and users seem to be able to handle the complexity OK. When I look at other professions, it seems to be a given that you'll have to invest a decent amount of time learning complex tools in order to do the job.

Thanks to language versioning, we *do* have the technical capability to simplify the language over time in a way that doesn't immediately break users. At the same time, there is still a migration cost to doing that and it can be hard to justify it.

**Comment by rrousselGit** [comment]
@munificent I do wonder why we got so many class keywords though.

I don't remember the community asking for that many. "Sealed" was highly requested for pattern matching, but I can't remember the others being popular.   

What's unexpected to me is how we got so many class keywords at once. I wonder if some of those couldn't have been annotations instead.

**Comment by munificent** [comment]
> @munificent I do wonder why we got so many class keywords though.

The thought process that led to it was basically:

* We knew we wanted to have exhaustive class hierarchies to go with pattern matching. That way we can support an algebraic datatype style with the soundness and exhaustiveness that functional users expect. That requires being able to define classes that can't be directly subtyped outside of their compilation unit. It also requires those classes to be abstract.

* I was worried that if that was the *only* way to prevent extending and/or implementing, then users would start using `sealed` when they didn't care about exhaustiveness at all. And then the other restriction that the `sealed` class also has to be abstract would a frustrating limitation if you simply wanted a concrete class that was closed to extension.

    I didn't want to *just* give `sealed` because then users might reach for it when it wasn't what they were actually trying to express. So we wanted other modifiers to let you control extending and implementing.

* Before we could pick modifiers, we had to think about what the *default* capabilities are. What behavior do you get if you don't use a modifier? There's something appealing about saying classes have no capabilities by default and you have to add modifiers to opt in to stuff. But that's the opposite of how Dart works today and would have been *massively* breaking. Also, users *like* the current permissive default behavior. It seems like the right default.

    And, for new users of Dart, it's nice that they don't immediately have to learn a bunch of modifiers before they can start writing a class. We wanted to avoid the problem in Java where you have to learn `public class Foo { public static void main() { ...` before you can get to "Hello, world!".

*   So we kept the current defaults where classes can be extended and implemented. That means we need modifiers that *remove* those capabilities. Coming up with nice short words that mean "can *not* extend" and "can *not* implement" is *really* hard. (I tried, for weeks.)

    The best we could come up with is words that describe the capability you have *left*:

    *   `interface` really means "no extends", but you can think of it in terms of "yes implements".
    *   `base` really means "no implements", but you can think of it as "yes extends".

*   We want people to think of those positive capabilities, because that's more intuitive and fits the words. But that means *combining* them gets very confusing. `base interface` would logically *remove* both capabilities but if you interpret them positively, it reads like a class that you can extend (it's `base`) and you can implement (it's `interface`).

    To route around that, we came up with a third keyword `final`, that means "no extends or implements" and then we disallow combining `base` and `interface`. This means more keywords to learn, but in return you avoid confusing combinations and you avoid classes that have particularly long lists of modifiers (though there are still some others you can combine).

* When looking just at extends and implements, you're left with four combinations that are expressed like:

    ```
                Implement no     Implement yes
    Extend no   final class    | interface class
                ---------------+----------------
    Extend yes  base class     | class
    ```

* There are two remaining capabilities for a class: Can it be constructed? Can it be used as a mixin? For the former, `abstract` already lets you control that and seems to be working fine, so we kept that and allow you to combine it with `base`, `interface`, or `final`.

* For mixing in classes, we *did* flip the default. We found very very uses of classes as mixins that we felt were intentional and compelling. And we couldn't come up with *any* sort of word that conveyed "can't be used as a mixin". (My suggestion of "immiscible" was, alas, no well received.) So we said that classes can't be used as mixins by default.

    But there are a few classes out there that are being used both as classes (i.e. either constructed or extended) *and* being used as a mixin (in `with` clauses). In particular, there are a couple in Flutter. We needed to be able to continue supporting that, so we let you put `mixin` on a class declaration to specifically opt in to that.

The result is probably more keywords than I would like. But classes *do* have a lot of capabilities and giving API authors fine-grained control over that seems useful, so we went ahead and tried to cover all of the combinations that made sense.

We could have *just* done `final`, but then users would have very likely asked for the ability to prevent extending while allowing implementing or vice versa. So we just did it all.

**Comment by renlite** [comment]
Besides the emerging programming languages like Carbon, Val, cpp2 as successor of C++ Dart has 
the potential to play a role in areas of C/C++ if there would be a simple C++ FFI, optional support of manual memory management like in Mojo or V and a fast compilation process. In general complexity is a burden for compilation performance. 
I think "100% sound null safty" or records are a big step forward and getting system programming features in Dart would help Dart to be more popular.

**Comment by Silentdoer** [comment]
> > @munificent I do wonder why we got so many class keywords though.
> 
> The thought process that led to it was basically:
> 
>     * We knew we wanted to have exhaustive class hierarchies to go with pattern matching. That way we can support an algebraic datatype style with the soundness and exhaustiveness that functional users expect. That requires being able to define classes that can't be directly subtyped outside of their compilation unit. It also requires those classes to be abstract.
> 
>     * I was worried that if that was the _only_ way to prevent extending and/or implementing, then users would start using `sealed` when they didn't care about exhaustiveness at all. And then the other restriction that the `sealed` class also has to be abstract would a frustrating limitation if you simply wanted a concrete class that was closed to extension.
>       I didn't want to _just_ give `sealed` because then users might reach for it when it wasn't what they were actually trying to express. So we wanted other modifiers to let you control extending and implementing.
> 
>     * Before we could pick modifiers, we had to think about what the _default_ capabilities are. What behavior do you get if you don't use a modifier? There's something appealing about saying classes have no capabilities by default and you have to add modifiers to opt in to stuff. But that's the opposite of how Dart works today and would have been _massively_ breaking. Also, users _like_ the current permissive default behavior. It seems like the right default.
>       And, for new users of Dart, it's nice that they don't immediately have to learn a bunch of modifiers before they can start writing a class. We wanted to avoid the problem in Java where you have to learn `public class Foo { public static void main() { ...` before you can get to "Hello, world!".
> 
>     * So we kept the current defaults where classes can be extended and implemented. That means we need modifiers that _remove_ those capabilities. Coming up with nice short words that mean "can _not_ extend" and "can _not_ implement" is _really_ hard. (I tried, for weeks.)
>       The best we could come up with is words that describe the capability you have _left_:
>       
>       * `interface` really means "no extends", but you can think of it in terms of "yes implements".
>       * `base` really means "no implements", but you can think of it as "yes extends".
> 
>     * We want people to think of those positive capabilities, because that's more intuitive and fits the words. But that means _combining_ them gets very confusing. `base interface` would logically _remove_ both capabilities but if you interpret them positively, it reads like a class that you can extend (it's `base`) and you can implement (it's `interface`).
>       To route around that, we came up with a third keyword `final`, that means "no extends or implements" and then we disallow combining `base` and `interface`. This means more keywords to learn, but in return you avoid confusing combinations and you avoid classes that have particularly long lists of modifiers (though there are still some others you can combine).
> 
>     * When looking just at extends and implements, you're left with four combinations that are expressed like:
>       ```
>                   Implement no     Implement yes
>       Extend no   final class    | interface class
>                   ---------------+----------------
>       Extend yes  base class     | class
>       ```
> 
>     * There are two remaining capabilities for a class: Can it be constructed? Can it be used as a mixin? For the former, `abstract` already lets you control that and seems to be working fine, so we kept that and allow you to combine it with `base`, `interface`, or `final`.
> 
>     * For mixing in classes, we _did_ flip the default. We found very very uses of classes as mixins that we felt were intentional and compelling. And we couldn't come up with _any_ sort of word that conveyed "can't be used as a mixin". (My suggestion of "immiscible" was, alas, not well received.) So we said that classes can't be used as mixins by default.
>       But there are a few classes out there that are being used both as classes (i.e. either constructed or extended) _and_ being used as a mixin (in `with` clauses). In particular, there are a couple in Flutter. We needed to be able to continue supporting that, so we let you put `mixin` on a class declaration to specifically opt in to that.
> 
> 
> The result is probably more keywords than I would like. But classes _do_ have a lot of capabilities and giving API authors fine-grained control over that seems useful, so we went ahead and tried to cover all of the combinations that made sense.
> 
> We could have _just_ done `final`, but then users would have very likely asked for the ability to prevent extending while allowing implementing or vice versa. So we just did it all.

Why is there no error when my class extends an interface

**Comment by Silentdoer** [comment]
And the base class can also be implements

**Comment by mateusfccp** [comment]
@Silentdoer You are probably extending it in the same library, which is allowed. The limitations only apply to outside of the library, as described in the documentation:

<img width="924" alt="image" src="https://github.com/dart-lang/language/assets/4605213/f985abc9-8f91-4dfb-b52f-c236b804091c">

If this is not the case, please open a new issue with detailed information and a minimal reproducible example.
