### ISSUE TITLE
Macro authors need an API to know whether an `augment super` call is valid or not

### ISSUE THREAD

**Issue by jakemac53** [dart-lang/language#3078]
Today we expose `hasExternal`, `hasAbstract`, etc which tell you if the keywords are present, but that isn't enough information to know if a given member has an implementation or not.

The keywords could exist just on the class and be implicitly applied to the members, in which case you can't tell which ones are actually abstract/external and which ones have an implementation.

Also, the body could have been filled in by another augmentation that is running before the current macro.

**Comment by lrhn** [comment]
Sounds like we need a semantic model, not a syntactic one. (Which is almost always the case, unless you need to manipulate source, which only dart-fmt really needs to, or need to report error locations.)

A class declaration can have member declarations that introduce various degrees of actual member implementations to the semantic class. Augmentations modify the class so it no longer matches a single class declaration, which is why it's useful to have a model for the result of an augmentation, different from the augmentation declaration itself.

The member declarations of a class declaration can be any of:

* A complete absence of declaration of a given name means the class adds nothing. It might still inherit an interface or implementation from the superclass, but *this class* has an open hole where a member declaration might go.
* An abstract declaration introduces no implementation, it only adds to the interface of the class. It can still inherit an implementation from the superclass.
* An `external` declaration introduces an empty scaffold for a member, but with no actual content. That content must be provided before the code can be run, but it counts as a declaration and shadows super-class implementations.
* And concrete declaration introduces a concrete member implementation.

It sounds like an augmentation can do a number of different things depending on what the class does already, generally moving up that chain of declaration levels.

It should distinguish between adding a concrete implementation to fill in an `external`-shaped hole (cannot call augment super) and augmenting (wrapping) an existing concrete implementation (can call augment super).
Or just adding implementation where there wasn't any before, if that's allowed.

These are *different* operations. It should be possible to see the current state of the class, and maybe it should even be different operations in the model to do the different things (even if an augmentation file uses similar syntax for them all).

And it should also be possible to see whether the member has been augmented by the current augmentation already (because an augmentation can only augment each member once).

**Comment by jakemac53** [comment]
Capturing a discussion with @munificent today:

- We want to keep the _current_ meaning of external - that is to say that external tools are expected to fill in the bodies.
- An augmentation applied to an external member is allowed to _assume_ there is some concrete implementation already there. If there is not, and an `augment super` call exists, then it will fail at runtime (with a `noSuchMethod` error).
- We will add an API to check if an `augment super` call would be valid - but this will just always return `true` for all external members. We don't want the answer to be different on different platforms, as this would cause generated code to be different between the analyzer and other tools.

**Comment by lrhn** [comment]
If an augmentation cannot fill in an `external` declaration with an implementation, then it means that augmentations cannot be used as a substitute for patch files in the SDK &mdash; which would be nice, but is not essential.

It's simpler that way, that's for sure, because otherwise we'd need some syntax to distinguish between filling in an external declaration, and just augmenting the implementation provided by the compiler.

**Comment by jakemac53** [comment]
> If an augmentation cannot fill in an `external` declaration with an implementation

So, I actually was careful to not explicitly block this. An augmentation _can_ still provide an implementation, and it can be a valid one if they know enough to not try to call `augment super`.

The downside is they can freely call `augment super` without any static error.

**Comment by lrhn** [comment]
Ah. I'm still thinking that it should be a compile-time error to have an external declaration with no supplied implementation, whether it's called or not. We don't do that, probably because it's hard to compile modularly, or just because we are still using the Dart 1 specification which made everything a runtime error.

If an `external` declaration with no implementation supplied just throws `noSuchMethod`, then an augmentation which doesn't call `super` can shadow it just like it can any other concrete method. (Which is questionable behavior in almost any other case.)

It's not filling in the missing implementation, it's just paving over the hole :grin:.

If there is any runtime-visible difference between an augmented method and a non-augmented method, then that's a problem, but I'll assume there isn't from anywhere outside of the augmentation itself.

**Comment by jakemac53** [comment]
Yeah, I would as always prefer a static error, but given the behavior of `external` today this didn't seem outrageous as it is just doubling down on that.

But, if we do want to try and make it a static error to not fill in an `external` body instead of a runtime one, I would feel differently about it.

**Comment by jakemac53** [comment]
Ok, I have what I think is a relatively simple and implementable proposal here - add a `hasBody` getter to `FunctionDeclaration`. This gives macro authors the ability to decide what to do for `external` things, so we don't have to hard code any behavior there.

In the definition phase, we follow the already defined ordering of macros, and if any of them fills in a body where one did not previously exist, the value of this should be `true` for the next macro.

If a single macro wants to provide multiple augmentations of the _same_ function (maybe as a result of macro composition), they would need to pass some extra flag along informing later code that a body has already been filled in, since the original FunctionDeclaration will still claim `false` for this getter. We could possibly alleviate this by returning a new FunctionDeclaration instance from any `FunctionDefinitionBuilder.augment` call, but I don't think that is really necessary?

**Comment by jakemac53** [comment]
The API for this has now landed (although there is no implementation yet)
