### ISSUE TITLE
Scoped Extension Methods

### ISSUE THREAD

**Issue by srawlins** [dart-lang/language#3105]
I don't know if that's the best title, but here goes:

I often find myself wanting to convert a little helper _class instance method_ to an extension getter, because it takes 0 parameters, and seems to act only on one object. But then I find that it actually requires access to one, sometimes two, of the nearby class members in order to make the computation. In the analyzer/linter code base this is often an instance of the "TypeSystem" class that knows how to work with our various type systems (pre null safety, post), or an instance of the "ResourceProvider" class which is how we mock out file I/O. So what I'm looking for is to define an extension, with methods, inside a class:

```dart
class SomeLintRule {
  final TypeSystem typeSystem;

  extension on DartType {
    bool get isNonNullable => typeSystem.isNonNullable(this);
  }
}
```

This would be _the exact same syntactic sugar_ as today's extension methods. The literal translation could be:

```dart
class SomeLintRule {
  final TypeSystem typeSystem;

  bool _$DartType_isNonNullable(DartType $this) {
    return typeSystem.isNonNullable($this);
  }
}
```

This feature is purely for aesthetics (as were extension methods? Modulo the explicit extension overrides?). I just really really love using extension methods for getters and for zero-parameter methods, like `toJson()`, and often find myself in this pickle of needing to use some class members (instance fields, instance methods, ...) in the extension method body.

(You could even imagine being allowed to declare an extension with methods as a statement, so that `package:test` tests could use an extension that references shared variables declared in `main` or a `group` 😮 . I don't think it really ups the complexity, because it's a simple translation to a local function.)

**Comment by lrhn** [comment]
This would be *instance extensions* since the declaration can refer to the `this` of the surrounding class.

That means that you can only invoke the extension member when you know *which* instance of `SomeLintRule` it comes from.
Which again means it can probably only be invoked by code declared inside the `SomeLintRule` class.
(That's consistent with the extension being unnamed, and therefore not invokable by name.)

That is one approach, require the extension to be unnamed, and only make it available to the scope where it's defined. (What about subclasses? Probably not.)
I'd probably still allow both a `static` and an instance declaration.

We can also allow the extension to be named, but then you can probably still only apply it implicitly from inside the class, and code outside will have to do explicit extension invocations like `someLintRule.DartTypeNullable(dartType).isNonNullable` ... which isn't improving readability much.

If the extension is only available inside member bodies of the declaring class, then I'm not sure the feature has enough impact to be worth it.
We'd introduce a completely new member resolution strategy, new syntax for nested member declarations, and all to convert `_isNonNullable(dartType)` to `dartType.isNonNullable`. It cannot affect the public API of anything, it's only use is to make the internal implementation of a single class more readable (maybe, or at least prettier).
(Well, and extension getters can be used in object patterns.)

**Comment by srawlins** [comment]
> This would be instance extensions since the declaration can refer to the `this` of the surrounding class.

Ooh I  had not considered that there is an ambiguity regarding `this`.

> Which again means it can probably only be invoked by code declared inside the SomeLintRule class.

Ah yeah, that would fit my expectations, but I guess is a new odd scoping/visibility concept.

> If the extension is only available inside member bodies of the declaring class, then I'm not sure the feature has enough impact to be worth it.

Yeah it's pretty narrow. And the new scoping and resolution stuff is bigger than I had guessed. Thanks for the discussion and consideration though. I'll close this out 😄

**Comment by eernstg** [comment]
I think it's worth considering the potential extra expressive power that we'd get out of extension instance members.

Here is a description of the approach taken in Kotlin: https://kotlinlang.org/docs/extensions.html#declaring-extensions-as-members.

For example:

```kotlin
class Connection {
    fun Host.getConnectionString() {
        toString()         // calls Host.toString()
        this@Connection.toString()  // calls Connection.toString()
    }
}
```

You can call this kind of extension method in the class where it is declared, and in subclasses, and it can be overridden. The extension receiver (a `Host` in the example) is provided syntactically, and the dispatch receiver (a `Connection`) is obtained from the value of `this` in the context.

In short, it all makes sense when we consider that `receiver.extensionMethod(otherArgs)` is transformed into `this.extensionMethodDesugared(receiver, otherArgs)`, and it may be an interesting feature that it can be abstract and overridden.

However, we will get the same behavior in Dart via a regular extension method if we are willing to pass the dispatch receiver explicitly. Kotlin example from the link above:

```kotlin
open class Base { }

class Derived : Base() { }

open class BaseCaller {
    open fun Base.printFunctionInfo() {
        println("Base extension function in BaseCaller")
    }

    open fun Derived.printFunctionInfo() {
        println("Derived extension function in BaseCaller")
    }

    fun call(b: Base) {
        b.printFunctionInfo()   // call the extension function
    }
}

class DerivedCaller: BaseCaller() {
    override fun Base.printFunctionInfo() {
        println("Base extension function in DerivedCaller")
    }

    override fun Derived.printFunctionInfo() {
        println("Derived extension function in DerivedCaller")
    }
}

fun main() {
    BaseCaller().call(Base())   // "Base extension function in BaseCaller"
    DerivedCaller().call(Base())  // "Base extension function in DerivedCaller" - dispatch receiver is resolved virtually
    DerivedCaller().call(Derived())  // "Base extension function in DerivedCaller" - extension receiver is resolved statically
}
```

Corresponding Dart example:

```dart
class Base {}
class Derived extends Base {}

extension BaseCallerExtension on Base {
  void printFunctionInfo(BaseCaller $this) =>
      $this.printFunctionInfoBase(this);
}

extension DerivedCallerExtension on Derived {
  void printFunctionInfo(DerivedCaller $this) =>
      $this.printFunctionInfoDerived(this);
}

class BaseCaller {
  void printFunctionInfoBase(Base base) =>
      print("Base extension function in BaseCaller");
  void printFunctionInfoDerived(Derived derived) =>
      print("Derived extension function in BaseCaller");

  void doit(Base b) {
    b.printFunctionInfo(this); // Call the extension function, passing `this`.
  }
}

class DerivedCaller extends BaseCaller {
  void printFunctionInfoBase(Base base) =>
      print("Base extension function in DerivedCaller");
  void printFunctionInfoDerived(Derived derived) =>
      print("Derived extension function in DerivedCaller");
}

void main() {
  // "Base extension function in BaseCaller"
  BaseCaller().doit(Base());
  // "Base extension function in DerivedCaller" - dispatch call virtual
  DerivedCaller().doit(Base());
  // "Base extension function in DerivedCaller" - extension call static
  DerivedCaller().doit(Derived());
}
```

Note that Kotlin will also provide a dispatch receiver (that is, `this` has a value and may be used implicitly) in other contexts via its functions with receiver. For instance, `with(myReceiver) { ... }` will allow invocations of instance extension methods where `myReceiver` is the dispatch receiver and the syntactic receiver will become the actual first argument.

This does make it less narrow. @srawlins, perhaps it's worth reopening this issue in order to have this idea on the table?
