### ISSUE TITLE
[inline-classes] Allow enhanced usage of type variables?

### ISSUE THREAD

**Issue by eernstg** [dart-lang/language#3140]
Do we wish to allow an enhanced applicability of type variables of inline classes, given that the type variable is a purely static phenomenon? In particular, we could allow a type variable to occur as a superinterface:

```dart
inline class V<X> implements X {
  final X x;
  V(this.x);
}
```

This implies that the computation of the interface of a type like `V<T>` depends on the value of `T` in a new way: Different values of `T` can give rise to different sets of members (not just a fixed set of members whose signatures may vary with different values of `T`).

**Comment by lrhn** [comment]
My initial thought is that it is too dangerous. Not because I can think of a concrete problem, but because I cannot convince myself that I can imagine all the possibilities.

If we do allow inline classes to implement class interfaces, but not to implement two different instantiations of the same interface, then an online class which `implements List<int>, T` may or may not be valid depending on the type bound to T. That seems potentially problematic.
An `implements List<int>, Iterable<T>` would be easier to reject eagerly, because `T` might not be `int`.

**Comment by eernstg** [comment]
Sure, this is new. However, they managed to handle this kind of feature in C++ for many years, so it shouldn't be intractable.

**Comment by lrhn** [comment]
If we assume it works, then `inline class V<X> implements X {...}` is definitely covariant in `X`.

We know that the representation type is a subtype of `X`. It may not be precisely `X`, we could have `inline class W<X, Y extends X> implements X { final Y _; }`, but then it'll be another type variable or `Never`, because that's the only types that are subtypes of type variables. Which means it's very likely always going to be the representation type itself, so what we have is a *completely general wrapper* which can add/overlay members on any type.

That probably does have some use.
Take:
```dart
inline class Logable<T> implements T {
  final T _it;
  Logable(this._it);
  void log() {
    Logger.current.logObject<T>(_it);
  }
}
```

I'm not seeing much use-case that isn't already handled by an `extension <T> on T`, but it's probably also not any more dangerous than that. Just a different way to do the same thing.

(I think we require all type parameters to an inline class to occur covariantly in the representation type. We may also want them to occur covariantly in `implements` clauses. But `inline class V<X> implements void Function<X> {...}` isn't new to this, so it's not an argument in either direction.)

**Comment by eernstg** [comment]
> a completely general wrapper .. on any type

Right, that was exactly the kind of situation I had in mind.

> I'm not seeing much use-case that isn't already handled by an `extension <T> on T`,

The most obvious difference is that the members added by this kind of inline class are sticky, so we can have a library where some return type is a `Logable<int>`, and it will remain loggable as long as we're using type inference to remember that it has type `Logable<int>` rather than just `int`, and we don't have to import any extra libraries just because we need to know about an extension.

> I think we require all type parameters to an inline class to occur covariantly in the representation type.

We do. The point is that if `V2 <: V1`, but `V2` is erased to `void Function(int)` at run time and `V1` is erased to `void Function(num)` then we'd need to generate dynamic type checks at up casts involving type variables (or we'd violate soundness).

```dart
inline class V<X> {
  final void Function(X) it;
  V(this.it);
  List<void Function(X)> unsound() {
    print('it is void Function(X): ${it is void Function(X)}');
    return [it];
  }
}

Y doCast<X extends Y, Y>(X x) => x; // Check `x is Y` at run time?

void main() {
  V<num> v = doCast(V<int>((int i) {}));
  var list = v.unsound();
  print(list.runtimeType); // List<void Function(num)>.
  print(list.first.runtimeType); // void Function(int).
}
```

This program compiles and runs because this variance error hasn't yet been implemented. It prints `it is void Function(X): false`, which shows that we can reach a situation where `void Function(X)` can be denoted, but `it` does not have that type, and there is no dynamic type error.

Then we proceed to create a list of type `List<void Function(num)>` which contains an element of type `void Function(int)`. This is a soundness violation.

Similarly for the requirement that type variables can only occur covariantly in superinterfaces: We don't want to have dynamic checks on up casts.

But I agree that there is nothing new here in that respect: `implements X` is a covariant occurrence of `X` in a superinterface.

**Comment by eernstg** [comment]
For every parameterized type of the form `V<T>` where `inline class V<X> implements X {...}`, it is known that every member in the interface of `T` is accessible on a receiver of type `V<T>`.

I think this should make it possible for every member invocation `e.m()` to determine statically whether or not it is an invocation of this kind, and then transform it to `(e as T).m()` and proceed with that. Backends would get a note that this cast need not occur at run time.

If `T` is again an inline type then the process may be repeated. It is a separate check on the inline class declarations that this process will terminate.

**Comment by munificent** [comment]
> However, they managed to handle this kind of feature in C++ for many years, so it shouldn't be intractable.

Is it relevant that C++ only type-checks *after* template instantiation? C++'s type system essentially has no notion of generics at all.

**Comment by eernstg** [comment]
It is not very likely that we will support this feature, in particular because of the complexity associated with conflicts among members of interfaces where some members are introduced as declarations in the extension type, and other members are introduced as members of the interface of the actual value of the type variable `X` which is the one that occurs as `implements ... X ...`.

```dart
extension type E<X> implements X {
  void isEven() {}
}

E<int> e; // Error?
```

We could report an error at the type `E<int>` because it contains a conflict between an `isEven` getter on the non-extension type superinterface `int` and the extension type member declared in `E`. We could also allow the type as such, and raise the error on every occurrence of `isEven` as a member access on an expression of type `E<int>`.

The basic issue here is that the ability to have a type variable as a superinterface (and as a supertype) makes the extension type declaration itself a mere syntactic entity rather than a semantic entity. The latter can be subjected to static analysis, and it is known that the semantic entity can be used with all parameterizations as long as the specified constraints are satisfied (in this case: `E<T>` is a well-bounded type, that's all).

In contrast, when the extension type declaration is just a syntactic entity (that is, when we allow `implements ... X ...`), we can only check that the syntax of `E` is correct. At least part of the static analysis of `E` must be performed afresh for every occurrence of a parameterized type (that is, `E<T>` for some type `T`), based on the interface of the given `T`, and this is not a good match for Dart. For example:

```dart
class C<X> {
  final E<X> e;
  C(this.e);
}

void main() {
  C<num> c = C<int>(42);
  c.isEven; // OK, a tear-off of the extension type method.
  if (c is C<int>) c.isEven; // Error, the interface of `c` has a conflict at this name.
}
```

**Comment by eernstg** [comment]
Closing: This issue was not included in the upcoming extension types feature (and I don't support it any more).
