### ISSUE TITLE
How should primary constructors work with augmentation libraries?

### ISSUE THREAD

**Issue by jakemac53** [dart-lang/language#3177]
- Generally, augmentation libraries allow augmenting field initializers as well as implicit getters and setters for fields. We should discuss which if any of these capabilities is allowed for fields introduced by primary constructors.
- Augmentation libraries also allow augmenting constructor bodies and initializer lists. Presumably we just wouldn't allow this for primary constructors? Or does this provide a way of customizing the primary constructor that is useful and allows more use of them?
- Do `augment class` declarations have to reproduce the primary constructor syntax or do they just omit it? They are required to reproduce all the class modifiers today.

**Comment by lrhn** [comment]
* There should be absolutely no difference between the constructors and fields introduced by a primary constructor, and the existing syntax it would desugar to. If there is a difference, it should be considered a bug.
That's for classes. If inline classes, extensions or other future non-class declarations can use primary-constructor-like syntax, it *might* not desugar to a constructor and an instance field. In that case it should either desugar to something else, or it should be a fundamental part of the declaration that is accessed directly by a name relevant to its role (if an inline class must use a primary constructor-like syntax to define its representation type and representation object name, then those should be the properties exposed, not "primary constructor", which is a syntactic concept).

* Ouch, good one. By my previous answer, there should be no doubt: If an augmentation can add things to the initializer list of a non-primary constructor, then it can also do it to the constructor induced by primary constructor syntax. That is probably the best answer, which means you can use primary constructor syntax, which doesn't allow asserts or other initializer list entries, and then augment it with an initializer list.
And that's OK. We're giving you a shorthand syntax, not a straightjacket. There is nothing you can do with primary constructor + augmentation that you couldn't write yourself with a normal constructor anyway. The syntax should only matter to the person editing the library, for everybody else, the API and DartDoc should be the same, no matter how it's written.

* Which means that `augment class` should not need to *know* whether the class it augments uses primary constructor shorthand syntax or not. It just works on the result.

**Comment by lrhn** [comment]
The class modifiers affect the public API and the capabilities of the augmented class too.
The primary constructor is an implementation detail.

The same way I wouldn't require an augmentation on `Future<int> foo(int x) async { .... }` to be an `async` function, it only needs to match the public signature `Future<int> foo(int x)`, how the body creates the returned future is an implementation detail.

**Comment by eernstg** [comment]
I agree completely with @lrhn: Primary constructors should be treated according to their nature as constructors, not imposing any particular limitations because of their syntactic form. In particular:

> Or does this provide a way of customizing the primary constructor that is useful and allows more use of them?

I would certainly expect that to be the case, and it might be quite powerful.

**Comment by munificent** [comment]
We discussed this in a meeting a while back. My feeling at the time and now is that not having both `part` and `augment` would be nice because the latter largely makes the former redundant.

But I don't think we can *replace* part files with augmentations and reuse the syntax. That would make for a harder migration. Users would be forcibly dragged off part files and have to migrate (with automation, of course) when they want to use the language version that augmentations ship in.

I could see us making that in place switch if part files were rarely used and the migration wouldn't affect many users. But that doesn't seem to be the case. Looking at a large corpus of pub packages:

```
-- File (56652 total) --
  45719 ( 80.701%): no part files    ===================================
   7759 ( 13.696%): is part file     ======
   3174 (  5.603%): uses part files  ===
Took 28.870s to scrape 12900509 lines in 56652 files. (288 files could not be parsed.)

-- By package (1968 total) --
   1477 ( 75.051%): Does not use part files  ===========================
    491 ( 24.949%): Uses part files          =========
```

While most files are Dart libraries that don't use part files, for any given package, there's about a one in four chance that it contains at least one part file. So this migration would affect a lot of users.

It may be that most of these part files are coming from generated code and would go away in a world with macros anyway. But to me, that's another argument for *keeping* part files. It will be easier for code generation package authors to migrate to macros if they can do so at their leisure and aren't immediately forced to do so because their code generator stops working since it can't generate part files anymore.

I could *still* see us doing reusing the `part` syntax if *we really liked it* and felt like it was a good fit for augmentations. I don't think that's the case though. I don't particularly love `augment` and `augmented`, but it seems to work OK. I think `part` and `part of` work well for defining and applying a part/augmentation file. But if we were to reuse part syntax, I don't know what syntax we would use on a declaration to mark an augmentation (currently `augment`) or to access the original declaration (currently `augmented`). `part`, `part of`, and even `partial` don't seem to fit that well.

So, given that it would be a hard migration to reuse the syntax and the existing syntax doesn't actually work that well for augmentations semantics anyway, I think it's best to just leave part files alone for now. My hope is that after augmentations ship users will gradually migrate away from part files and maybe we can deprecate and remove them in a later version.
