### ISSUE TITLE
Full `void` type, including support for use in generics

### ISSUE THREAD

**Issue by appgurueu** [dart-lang/language#3194]
Proper "void" (zero-memory) types (the empty struct in Go; the empty tuple, also called "unit" in Rust) are extremely useful when you want to express a simpler data structure in terms of a more powerful one with zero overhead.

The prime example of this is implementing `Set`s in terms of `Map`s: A `Set<T>` is effectively just a `Map<T, void>`. You usually want your compiler to optimize the void type out completely (e.g. through monomorphization), such that you waste no memory and time on it.

Without a proper void type, you either need to waste time and space for unnecessary values, such as using `bool` instead of `void` and setting the values to a constant `true`/`false`, or you need to duplicate your code and remove all instances where the values are being used, effectively performing the monomorphization "by hand".

Proper metaprogramming (such as Zig's powerful `comptime`) poses a viable (though generally more cumbersome) alternative to a void type. This [seems to be in the works](https://github.com/dart-lang/language/blob/main/working/macros/feature-specification.md)?

See also https://github.com/dart-lang/sdk/issues/2231. To answer the questions posed there:

> What about a method that takes T as an argument? What does this mean if T = void?

`void` variables and arguments should only have one value: `void` - thus the argument would just be a constant `void`

>What is List<void>?.

The list would be a list of contant `void`s. Since `void`s take no memory, the `List` would need no memory except for storing its length. Getting elements would return constant `void`s, adding elements would only modify the length. Effectively the list would pretty much degrade to an awkward counter. This isn't terribly useful; programmers will always be able to use features for nonsense however.

And it does come in handy if you're implementing B-Trees, where you might want to maintain a list of values for a B-Tree based map: To implement a set in terms of this map, you'll have to set `V = void`, thus this list of values will become a list of `void`s. Ideally, to make this list of `void`s take zero memory, Dart would have to provide an array type where the size is known at compile time, like Go's arrays.

**Comment by mateusfccp** [comment]
It seems you want a _singleton type_ (also called _unit type_). In Dart, `void` is (one of the) _top type_. This means that turning it into a _singleton type_ would change the type system by a lot.

A _singleton type_, on the other hand, could be introduced without many hassles, AFAIK. I don't know however, how it would fit in the Dart's current type system, as Dart already has a _singleton type_, which is `Null`. `Null` has a single possible value, which is `null`.

IMO we already have a lot of confusion with _top types_ (we have `dynamic`, `Object?` and `void`[with some limitations]), so having two _singleton types_ doesn't seem like something positive to me.

(Diverging a little, I would rather go in the direction of dropping `void` and `dynamic` entirely, but that's another discussion.)

I am not sure how the compiler treats `Null`, so I can't say if it is completely optimized out.

**Comment by appgurueu** [comment]
Thanks for the answer. I wasn't aware of the `Null` type and would intuitively have expected `void` to act as a singleton type. This is indeed confusing and perhaps `void` should be dropped (in favor of `Null`?) as you suggest.

*Might* make a follow up issue on arrays with comptime size and monomorphization when I get to implementing my B-Trees :)

**Comment by eernstg** [comment]
@appgurueu, as others have already mentioned, the meaning of the type `void` in Dart is very different from the zero-memory model that you took as the starting point.

You might want to take a look at the section '20.9 Type Void' in the [language specification](https://spec.dart.dev/DartLangSpecDraft.pdf). (Note that the updates to include null safety are under review, so the link I just mentioned refers to the language specification that specifies the language _before_ null safety. However, that doesn't make much of a difference in this particular section.)

The main point is that an expression of type `void` in Dart is an expression whose value should be discarded. It is not because there is no value&mdash;Dart avoided introducing the notion of a 'procedure' in order to avoid having two kinds of computational abstraction, which would duplicate the size of the language in many ways. So _every_ function call returns a value (or it throws, or it runs in an infinite loop, but it doesn't just return without a value).

The returned value is a perfectly valid object. It is null in most cases, but it could be anything. The point is that the type `void` is used, say, as a return type of a method, in order to indicate that this method does not return an object which is useful or meaningful for any purpose. If you're using it then you misunderstood something (or you know what you're doing, and it's a very special exception). Consequently, it is a compile-time error to use the value of an expression of type `void` (further details about this are given in the previously mentioned section in the language specification).

The potential ability to detect that a particular type carries no information and generate special-cased code that avoids allocating any memory for any such non-informative entity is basically concerned with monomorphization, cf. https://github.com/dart-lang/sdk/issues/52722.
