### ISSUE TITLE
Primary constructors with curly brackets for user-named fields

### ISSUE THREAD

**Issue by Cat-sushi** [dart-lang/language#3198]
For consistency with records, like
```dart
typedef R = (int, {int a, int b});
R r = /* R */(1, a:2, b:3);
main(){
  print(r.$1);
  print(r.a);
  print(r.b);
}
```
, I think that primary constructors should have syntax with curly brackets for user-named fields, like
```dart
data class D(int, {int a, int b});
D d = D(1, a:2, b:3);
main(){
  print(d.$1);
  print(d.a);
  print(d.b);
}
```
.

My understanding is that data classes are records with class names, both of them share characteristics of simple, immutable, unboxing optimization friendly, without persistent identity, and with structural equality, in other words value types, then syntactic consistency is important.

**Comment by lrhn** [comment]
A primary constructor is, as discussed so far, very much a parameter list with extra keywords allowed (because each parameter is also going to declare a field, and the fields may need more keywords).

What you describe is how named parameters are already written, so it's pretty much a given that the syntax for primary constructors will use that for named parameters. 
(Meaning that wrt. curly braces, you can probably closed this issue as "fixed", because that's how it's going to be, if it is at all.)

I'm less enthusiastic about omitting the name for a positional field, because `$1` is not a _good_ name for something that you can easily give a better name. And you can still name it `$1` if you really mean that.

Records got the `$1` names because they are structural, so there is no single declaration which can name the first positional element, and because we hope you'll be using patterns to destructure instead of `.$1` most of the time.


And there is no way that primary constructors will *not* allow `class D(int $1, {int a, int b});` as syntax.
(But if it's a class, you probably want to add `final` too. For a `data class` where fields must be `final`, if that becomes a thing, the `final` can probably be omitted.)

**Comment by Cat-sushi** [comment]
I'm relieved.
Is there a proposal which specify this syntax as "fixed" one?

**Comment by Cat-sushi** [comment]
this one?
[language/working/extension_structs/overview.md at main · dart-lang/language](https://github.com/dart-lang/language/blob/main/working/extension_structs/overview.md#fields-and-primary-constructors "language/working/extension_structs/overview.md at main · dart-lang/language")

Is "Alternative:" user selectable option, or language designers option?

**Comment by lrhn** [comment]
I believe the most current proposal for primary constructors is the open PR https://github.com/dart-lang/language/pull/3023

**Comment by Cat-sushi** [comment]
Thank you.
I'm closing this issue.
