### ISSUE TITLE
How do extension types interact with sealed?

### ISSUE THREAD

**Issue by munificent** [dart-lang/language#3199]
The runtime type of an instance of an extension type (née inline class) is identical to its representation type. Is that fact visible to the exhaustiveness checker?

Consider:

```dart
sealed class A {}
class B extends A {}
class C extends A {}

extension type WrapC(C c);

test(A a) {
  print(switch (a) {
    B() => 'b',
    WrapC() => 'c-ish',
  });
}
```

Is this switch exhaustive?

**Comment by jakemac53** [comment]
Is there any reason to say it isn't exhaustive? Given it is literally exhaustive (a default case would be dead code), I think it should be treated as such.

**Comment by rrousselGit** [comment]
This feels weird to me. If WrapC and C are the same thing, why do we even need WrapC?

I may be misunderstanding the related features. But I would assume that C wouldn't be assignable to WrapC.
As I'd expect in-line classes to be able to define asserts on their constructor. And a random C instance would bypass those asserts

**Comment by lrhn** [comment]
It's invisible to the exhaustiveness checker, which should only work on the ultimate representation type.

The object still is the representation object, it's just a different view on it.

If we do not allow an extension type to make its representation type opaque, then there is no issue here.

The reason sealed exhaustiveness works it's that we know that all _instances_ of the sealed type are instance of one of the known direct subtypes.
Extension type do not count towards that, since they have no instances of their own at runtime. 
An extension type can only implement a sealed type if it's representation object is an instance of a subtype, and that's all the runtime type check in the switch is going to see.

(Should we use `view type` for those that do not implement the representation type, and `extension type` for those which do? Might reduce confusion? Might increase it, too.)
(Should we disallow having an extension type as representation type? You should just use the same normal type as representation type, and implement the other extension type instead. Would make things easier to specify, possibly easier to explain and understand. If we disallow using a type parameter as representation type, which we do, there should be no way to skirt that restriction, and if an extension type cannot hide its representation type, the only thing which matters is its ultimate representation type anyway.)

**Comment by lrhn** [comment]
@rrousselGit 
The point of extension types, nee online classes, is to provide a different static view of an object. Like a sticky extension, which can take precedence over the original members as long as you keep the extension type as the static type of the object.
It's only static, at runtime it's like calling an extension method.

You can have constructors, but mainly for convenience. They cannot limit which objects of the representation type can be viewed at the extension type, any more than you can limit which objects of a type that an extension can be applied to.
You can always do `o as ExtType` or `list as List<ExtType>`, which cannot fail at compile tone. At runtime those casts still only check for the representation type, to ensure that the later extension type member invocations are valid.

**Comment by rrousselGit** [comment]
Indeed. It's just that I feel like a common use-case would be something akin to UInt, which would be a view of int, with `assert(this >= 0)` in the constructor

And for safety, we wouldn't want an int to be assignable to UInt

**Comment by eernstg** [comment]
> And for safety, we wouldn't want an int to be assignable to UInt

That is indeed exactly the level of support for representation object vetting we have: You can always do `-1 as Uint` if you insist, but if you _want_ to maintain the invariant that the constructor(s) are checking then you wouldn't perform a cast like that. Of course, we can't even lint `e as X` where `X` is a type variable whose value is `Uint`. As usual, if you want firm guarantees then you'd need to pay the price and have an actual wrapper object.

I'd like to have further support via lints: `anyExpressionOfTypeInt as Uint` should be lintable when `Uint` is an extension type that doesn't `implement T` for any `T` which is a non-extension type (here: `int`, `num`, and so on).

Similarly, we could lint `anyExpressionOfTypeUint as int`. That one is more important if we're trying to protect the representation object from being used in terms of its run-time type (e.g., a `Map<String, dynamic>` where we have information beyond the type information that the `dynamic` part has a certain structure). So they should be two separate lints.

All in all, it's going to be helpful for correctness by giving a heads-up in a lot of situations, but there's no way we can close all the loopholes. That's the nature of this mechanism, and the value proposition is that it's better than nothing, and cheaper than a real wrapper.

For the "sticky extension methods" use case I believe there's no reason to try to make it hard to enter or leave the abstraction: With `FancyInt <: int` (where `FancyInt` is an extension type that `implements int`) we can directly assign any fancy int to an int (that just means "forget the sticky extension methods"), and we can promote as usual ("please add those sticky extension methods").

**Comment by lrhn** [comment]
@rrousselGit 
You can still create a `Uint32` extension type that treats its underlying `int` values as 32-bit integers,
but you *cannot* prevent any `int` to be cast to `Uint32`. 
If that's a problem, check for it in every member where it matters.

An extension type on `int` is a view on *any* `int`. It's not a subset of `int` values, it's not designed to be able to be that. 
If really need encapsulation and forced checking, use a class.

```dart
// TODO: Make it work on web.
extension type Uint32._(int _value) {
  static const int _mask = 0xFFFFFFFF;
  factory Uint32(int value) {
    if (value != (value & _mask)) throw ArgumentError.value(value, "value", "Not in range 0...2^32-1");
    return Uint32._(value);
  }
  Uint32.fromInt(int value) : this._(value & _mask);
  Uint32 operator +(Uint32 other) => (_value + other._value) & _mask;
  Uint32 operator -(Uint32 other) => (_value - other._value) & _mask;
  Uint32 operator *(Uint32 other) => (_value * other._value) & _mask;
  Uint32 operator ~/(Uint32 other) => (_value * _mask) ~/ (other.value ~/ _mask); // Defensive masking!
  Uint32 operator %(Uint32 other) => (_value & (other.value & _mask));
  String toString() => (_value & _mask).toString();
  String toRadixString(int radix) => (_value & _mask).toRadixString(radix);
}
```

**Comment by eernstg** [comment]
About the actual topic of this issue:

>Is this switch exhaustive?

It does introduce an implicit dependency into client code that `WrapC` has representation type `C` (it's really weaker than that, by the way, we only depend on the fact that the given set of cases is exhaustive).

However, I wouldn't have a problem with this: It is sound, and I don't think it's going to help anyone write code that's more correct or more comprehensible if we refuse to recognize that the switch is exhaustive.

After all, I don't think it's typical that any correctness considerations (other than exactly exhaustiveness itself) for a switch statement/expression would rely on knowing that all the other cases are "sibling" types (they'd typically have the sealed type as a shared direct superinterface).

On the other hand, we might still want a lint/warning to flag this kind of switch case because it is similar to a cast to an extension type (at least if the extension type doesn't declare `implements C`, which it did not do in the given example).

**Comment by eernstg** [comment]
Closing: We decided that exhaustiveness is determined based on the ultimate representation type of extension types. In other words, we'll use all the knowledge we can get in order to recognize that a given switch is exhaustive.
