### ISSUE TITLE
`typedef` isn't allowed in statement blocks

### ISSUE THREAD

**Issue by Hixie** [dart-lang/language#3200]
I like to be explicit about types everywhere and not rely on inference.

I wish I could do something like the following, where I use a typedef to avoid having to duplicate a record's type, without the typedef having to be far away from the one code block where I use it:

```dart
    ...
    case 'create-new-triage-labels':
      if (arguments.length != 1) {
        print('Usage: dart run github_tools create-new-triage-labels');
        exit(1);
      }
      typedef LabelDescription = ({String name, String color, String description});
      final List<LabelDescription> newLabels = <LabelDescription>[];
      for (final String team in teams.keys) {
        if (team != 'ecosystem' && team != 'infra' && team != 'release' && team != 'google-testing' && team != 'news' && team != 'codelabs') {
          newLabels.add((name: 'team-$team', description: 'Owned by ${teams[team]}', color: '198022'));
        }
        newLabels.add((name: 'triaged-$team', description: 'Triaged by ${teams[team]}', color: 'b8ccba'));
        newLabels.add((name: 'fyi-$team', description: 'For the attention of ${teams[team]}', color: '29cc36'));
      }
      for (final LabelDescription label in newLabels) {
        await engine.createLabel(label.name, label.color, label.description);
      }
    ...
```

**Comment by lrhn** [comment]
There should be no big issue with allowing a `typedef` anywhere, after all it's just an alias, so it should go away the moment it's used and unaliased.

The one difference between top level and inside a local body is that the latter can have type parameters in scope.

That's not a significant problem, just a difference. Currently a type alias must be closed, not contain any type variables not declared by itself. There may be implementation assumptions about that, which need to be addressed.

If not, it should be a fairly trivial change.
A type alias can be allowed the same # places a `const` declaration can: as a top level, static, and local declaration.

The "static" feels like it should be included, otherwise it's a weird exception. That may require bigger changes, though, because there is then no longer a limit on the length of a `Foo.Bar.Baz.Qux...` chain that can denote a type, where is currently limited to `optPrefix.Identifier`.
Again not a big or difficult difference, but one actually encoded in the grammar.

**Comment by mateusfccp** [comment]
Seems like a duplicate of #67.
Also, related: #2952

**Comment by Hixie** [comment]
Yes, this is a duplicate of #67, good catch. I looked for others but couldn't find them. Closing as dupe. Thanks!
