### ISSUE TITLE
Make a decision about whether or not we allow `extends` in type augmentations 

### ISSUE THREAD

**Issue by jakemac53** [dart-lang/language#3230]
The proposal currently doesn't allow `extends` in augment declarations, but has a TODO to possibly allow it when the augmented type does not already have an `extends` clause.

I feel pretty strongly that we shouldn't allow you to _replace_ an existing `extends` clause, but filling in one where it didn't exist before isn't much different than adding a mixin, which is allowed.

**Comment by jakemac53** [comment]
Spawned from discussions in https://github.com/dart-lang/language/issues/3229 (see the off topic discussions).

**Comment by lrhn** [comment]
Could you be allowed to replace a superclass with a subclass of that superclass?
That way `class C extends S ...` could be changed to `extends T`,  but _only_ if `T` extends, directly or transitively, `S`.

It's still not guaranteed to work. `T` doesn't have to have the same generative constructors, or even compatible method implementations (can be more restrictive using `covariant`).
It's safer to not allow it, but if you can insert a mixin, you can still change the superclass of `C`, so the only difference is really the constructors.

**Comment by rrousselGit** [comment]
Honestly the primary case is likely to be "adding an extends when one is missing".  
I'm fine with not allowing the replacement if an existing extends with a different one.

I do think that given the goal of augmentation libraries, we _should_ be able to add a new extends to a class though.
That's probably one of the most common use-case when annotating a class.

**Comment by jakemac53** [comment]
> Could you be allowed to replace a superclass with a subclass of that superclass?

I could see that being feasible but I don't know if it's worth the extra complexity? It's also something that could be added later pretty easily, if some good use cases came up.

**Comment by jakemac53** [comment]
@johnniwinther and @scheglov do you have any implementation concerns about allowing an augmentation to fill in an `extends` clause if there was no original one?

**Comment by rrousselGit** [comment]
Not sure if that'd be a possible issue, but I'd expect to be able to also use `super` in the user-defined constructors:


```dart
@annotation
class Foo {
  Foo(): super(initialState: 0);
}

augment class Foo extends Notifier {}

// from a package:
abstract class Notifier {
   Notifier({required Object initialState}): state = initialState;

  Object state;
}
```

**Comment by jakemac53** [comment]
Yes I think we would allow that - there would be no discernible difference between the extends being in the user library or the augmentation.

**Comment by lrhn** [comment]
If we allow adding a superclass (`extends` clause) where none existed, we're changing the existing superclass (`Object`) to a subclass. 
It makes sense to allow this special case if we look at the class declaration and augmentation syntactically, rather than semantically. That's fine if it's the same principle we use everywhere (it probably is). "This was something you could have written in the original class instead."

In that case, the augmentation needs to be able to add arguments to the existing constructors' super-constructor invocation. Maybe even retarget it if the new superclass doesn't have an unnamed generative constructor. Again, that's adding something syntactically, so it fits. ("Adding" a constructor name is a little misleading, unless we allow it in other cases too, which we shouldn't. Maybe we'll just say that you shouldn't have any `super()` in the initializer list to begin with if you want the augmentation to work.)

It's unlikely, but not physically impossible, that the superclass makes an existing super-method invocation invalid. That requires overriding `noSuchMethod` or `operator==` with a covariant parameter, so probably won't happen, but we should be ready for it 
Probably the program just stops compiling, and if that's a problem for someone, they asked for it.

**Comment by jakemac53** [comment]
> If we allow adding a superclass (`extends` clause) where none existed, we're changing the existing superclass (`Object`) to a subclass.

Depends on how you think of an augmentation I suppose - certainly its presence alters what the superclass would otherwise be, but I am not sure that qualifies as "changing it", if it was never actually Object in the first place.

> It makes sense to allow this special case if we look at the class declaration and augmentation syntactically, rather than semantically. That's fine if it's the same principle we use everywhere (it probably is). "This was something you could have written in the original class instead."

Yes, exactly. At least my mental model is a syntactic merge only. For instance this text `Fortunately, augmentations can be applied purely syntactically. In order to merge augmentations into the main library, we only need to match declarations by name.`. This helps simplify the mental model I think. Note that augmentations do have their own scope though, so it isn't truly a pure syntactic merge.

It might make sense to update the proposal to make this mental model very explicit up front?

> In that case, the augmentation needs to be able to add arguments to the existing constructors' super-constructor invocation.

We do allow augmentations to modify the initializer list of a constructor. It actually looks under specified right now though, as it isn't clear if this _replaces_ or _adds to_ the current initializer list. I think either would be OK here - if we are only allowing adding `extends` where it didn't exist before, then there would be no need for a pre-existing call to `super()` in the initializer list.

**Comment by scheglov** [comment]
It should be easy to get the supertype from the augmentation, we already [merge](https://github.com/dart-lang/sdk/blob/ba005169c5147693134d0d46598038d252231873/pkg/analyzer/lib/dart/element/element.dart#L151) implemented interfaces, adding redirection for the supertype can be done just the same way.
