### ISSUE TITLE
Enum name throws error after being added to map 

### ISSUE THREAD

**Issue by marqueurs404** [dart-lang/language#3232]
I have stumbled on a weird behaviour today which I believe is a bug. Essentially, after adding an Enum to a Map, calling `.name` on the enum in the map throws a NoSuchMethodError.

You can try it out on https://replit.com/@marcusong/EnumBug#main.dart

Same behavior when I tried on Dart versions 2.18.0 and 3.0.5.

**Comment by julemand101** [comment]
This is not a bug. The `.name` property on enums comes from the following extension method:
https://api.dart.dev/stable/3.0.6/dart-core/EnumName.html

Extension methods in Dart are resolved when compiling and they are not part of the objects at runtime. Since your `Map` is typed `Map<dynamic, dynamic>`, the compiler can't know what type you would get out of the map when compiling happens and can therefore not handle the `.name` call. Since `.name` is not part of the enum object itself, you get the error `NoSuchMethodError`.

The limitation of extensions methods is detailed here: https://dart.dev/language/extension-methods#static-types-and-dynamic

So with this knowledge, we can fix your program by either do:
```dart
print((someMap['key'] as SomeEnum).name);
```
Or change the type of the `Map` to: `Map<dynamic, SomeEnum>`:
```dart
import 'dart:io' show Platform;

enum SomeEnum {
  A,
  B,
  C;
}

void main() {
  Map<dynamic, SomeEnum> someMap = {};
  someMap['key'] = SomeEnum.A;

  print('${Platform.version}');

  // works
  print(SomeEnum.A.name);

  // unexpectedly throws an error
  print(someMap['key']!.name);
}
```
Both solutions works since the Dart compiler is now able to tell you expect a `SomeEnum` object and can therefore apply the extension method.

**Comment by marqueurs404** [comment]
Wasn't aware of this limitation. TIL. Thanks!
