### ISSUE TITLE
Record type is not a Type?

### ISSUE THREAD

**Issue by wujek-srujek** [dart-lang/language#3241]
I have a map keyed by Type, and this concept doesn't work for record types, or at least I can't make it work. For example:
```dart
void main() {
  final map = <Type, dynamic>{};
  map[String] = 'foo';
  map[int] = 17;
  map[(String, int)] = ('foo', 17);
}
```
The last line doesn't work as `(String, int)` is not a `Type` but rather a `(Type, Type)`. But shouldn't it also be a `Type`?

**Comment by leafpetersen** [comment]
There is a difference between types (e.g. `int in `int x`) and type literals (e.g. `int` in `Type t = int`).  Record types cannot be used directly as type literals, because, as you note, it would be ambiguous as to whether `var t = (String, int)` meant "bind t to a record containing two type literals", or "bind t to a type literal corresponding to a record type".  (Function types can also not be used as type literals, for different reasons).

There are (at least) two ways to work around this: via a typedef, or via a use of generics.  
```dart
  typedef RecordType r = (String, int);
  Type typeLiteralFromType<T>)() => T;
```
Given those definitions, you can then write `map[RecordType]` or `map[typeLiteralFromType<(String, int)>]` .

**Comment by mateusfccp** [comment]
With #2393 this kind of confusion would be eliminated.
