### ISSUE TITLE
Clarification on recent language changes?

### ISSUE THREAD

**Issue by mnordine** [dart-lang/language#3252]
I understand this is an odd issue, but was just confused with some recent changes, and would appreciate some clarification, if possible.

Based on some commits in `sdk`, and the [changelog](https://github.com/dart-lang/sdk/blob/main/CHANGELOG.md#language-1) it looks like `macros` have been [pushed out again](https://github.com/dart-lang/language/commit/e3b4d8436dfbc90ed853a2e1763248977c275424), and perhaps `inline-classes` were [changed to](https://github.com/dart-lang/language/commit/bb001dc06b2909d16221baa5a91c348b0718c712) `extension-types`, and pushed out as well?

> Modify the inline class feature specification to specify extension types. This is a feature renaming

Are there any language changes slated for 3.1?

**Comment by jakemac53** [comment]
Macros aren't being "pushed out" - they have no "experimental release version" which means to keep you have to keep updating your language version to the absolute latest to use them, so that is all that commit was doing. They aren't planned as a part of any specific release right now.

inline classes were renamed to extension types, not sure on the release date but presumably it isn't 3.1 as they are n[ot enabled yet](https://github.com/dart-lang/sdk/blob/main/tools/experimental_features.yaml#L124). In general if you want to understand when a feature is going to make it into the next release, that file is the canonical status. Once a feature gets the `enabledIn` field, it will be enabled by default in the next release.

**Comment by jakemac53** [comment]
👍 I am going to go ahead and close this
