### ISSUE TITLE
[proposal] Checking a variable's type via `is` should promote it even if the types are unrelated

### ISSUE THREAD

**Issue by jellynoone** [dart-lang/language#3255]
Consider the following example:
```dart
abstract interface class A {}

abstract interface class B {
  void doSomething();
}

void doSomethingWithA(A a) {
  if (a is B) {
    a.doSomething();
  }
}

class AB implements A, B {
  void doSomething() {
    print('AB');
  }
}

void main() {
  doSomethingWithA(AB());
}
```

The analyzer warns of an error at: `a.doSomething();`, however, we know that `a` is of type `B`, due to the previous `is` check.

It should, however, be noted that if we redefine, the `doSomethingWithA` to:
```dart
void doSomethingWithA(A a) {
  if (a is AB) {
    a.doSomething();
  }
}
```
The analyzer and compiler are then happy.

**Dart SDK Version (`dart --version`)**
`Dart SDK version: 3.0.7 (stable) (Mon Jul 24 13:17:56 2023 +0000) on "macos_x64"`
`Dart SDK version: 3.1.0-262.3.beta (beta) (Mon Jul 24 13:07:00 2023 +0000) on "macos_x64"`

I first thought of this as being an issue, but the more I thought about it I think it is a language feature instead.

However, at least to me, it seems odd that the initial example doesn't work. From the perspective of the developer the type was explicitly checked and even if it is unrelated to the initial type, we made sure it is of the right type.

My proposal here is that this kind of promotion be allowed, and if this isn't something the language wants to allow, then I would suggest if the error reporting be improved, possibly, on the `a is B` check, rather than on the method call.

For instance, if the language doesn't allow promoting types in this way it would be more helpful to get an error message saying this isn't allowed instead of seeing an error that the message doesn't exist, when the programer is clearly checking for the type.

**Comment by munificent** [comment]
To understand why we don't promote to unrelated types, consider:

```dart
abstract interface class A {
  void doSomethingElse();
}

abstract interface class B {
  void doSomething();
}

void doSomethingWithA(A a) {
  if (a is B) {
    a.doSomething();
    a.doSomethingElse(); // <--
  }
}
```

If the `a is B` promoted `a` to `B`, then now the `doSomethingElse()` call would be erroneous, since `B` doesn't define that method. It would be *quite* surprising to get a compile error on a call to a method that is clearly available on the *static* type of some variable.

So, to avoid that, the rule is that we only promote to types that will *add* methods but never *remove* them from what's available to be called.

If the language had real structural intersection types, then we could promote to `A & B`, which would have the methods of both types. But union and intersection types are a big can of worms and, so far, we haven't gone in that direction.

In the absence of that, the best thing we can do is not promote to types that would cause you to lose methods.

**Comment by jellynoone** [comment]
Thank you for the explanation. Makes sense.
