### ISSUE TITLE
Type inference failure?

### ISSUE THREAD

**Issue by lukehutch** [dart-lang/language#3279]
**Describe the bug**

I'm not sure if this is an issue, but:

```dart
    MemoryImage? img;
    String url = 'some URL';
    ImageProvider<MemoryImage>? x = img;
    ImageProvider<NetworkImage> y = NetworkImage(url);
    var z = x ?? y;
    var w = img ?? NetworkImage(url);
```

Given this code, `img` is a `MemoryImage?`, and `MemoryImage` extends `ImageProvider<MemoryImage>`, so `img` has supertype `ImageProvider<MemoryImage>?`.

The type of `z` is `ImageProvider<Object>`, as expected.

However, the type of `w` is just `Object`.

Manually assigning `img` and `NetworkImage(url)` to local variables of the correct supertype allows `z` to correctly infer its type. However `w` is not able to infer its type.

Maybe this is by design, but it is surprising.

Dart 3.0.6

**Comment by lukehutch** [comment]
Note that in VS Code, replacing the expression for `w` with 

```dart
var w = (img as ImageProvider<MemoryImage>?) ?? (NetworkImage(url) as ImageProvider<NetworkImage>);
```

gives "unnecessary cast" errors on both halves of the expression, and upon Save, VS Code replaces this with the original expression for `w`.

**Comment by eernstg** [comment]
This is working as specified, though not quite as desired. Check https://github.com/dart-lang/language/issues?q=is%3Aopen+is%3Aissue+label%3Aleast-upper-bound for the broader discussion.

In short, the type of `img ?? NetworkImage(url)` is the least upper bound of `MemoryImage` and `NetworkImage`. The particular case which is used to compute the upper bound of those two types is the [last one](https://github.com/dart-lang/language/blob/main/resources/type-system/upper-lower-bounds.md#:~:text=UP(C0%3CT0%2C%20...%2C%20Tn%3E%2C%20C1%3CS0%2C%20...%2C%20Sk%3E)), and that computation will select a type which is a common supertype (here: `Object`). It does _not_ detect that both of those types have a supertype of the form `ImageProvider<...>`. The discussion mentioned above aims to find better upper bounds in exactly this kind of situation.

In this particular case the story is slightly longer: The two "similar" supertypes are `ImageProvider<MemoryImage>` and `ImageProvider<NetworkImage>`. By covariance we can find some supertypes of these types, for instance: `ImageProvider<MemoryImage> <: ImageProvider<ImageProvider<MemoryImage>> <: ...`, and similarly for the other type.

```dart
// I'm assuming that `ImageProvider` has an F-bounded type parameter, like this:
class ImageProvider<X extends ImageProvider<X>> {...}
```

So we could claim that a shared common supertype is the infinite type `ImageProvider<ImageProvider<ImageProvider<...>>>>`.

The fact that there is no _finite_ shared superinterface of the form `ImageProvider<T>` for any `T` is one of the main reasons why this algorithm doesn't make an attempt to just call itself recursively on the type arguments.

We do have a mechanism in the language to mitigate this issue: Super-bounded types. In particular, `ImageProvider<ImageProvider<dynamic>>` is a type (it is not an error, even though it violates the type parameter bound, because it does so in a way which is specifically allowed), and it is a supertype of both of the types that we're considering.

So you can use `as ImageProvider<dynamic>` to resolve the conflict. This is exactly what you are already doing, because `ImageProvider` is just a concise notation for `ImageProvider<ImageProvider<dynamic>>` (that's the result of a computation which is known as instantiation to bound).

**Comment by eernstg** [comment]
I'll close this issue because it shows properties of the upper-bound computation which are already well-known and under discussion.

**Comment by lukehutch** [comment]
Thank you for the thorough and clear explanation! I hadn't considered the infinite type aspect here, that makes a lot of sense.
