### ISSUE TITLE
implicit_this_reference_in_initializer should be allowed in lambda

### ISSUE THREAD

**Issue by yelliver** [dart-lang/language#3284]
https://dart.dev/tools/diagnostic-messages?utm_source=dartdev&utm_medium=redir&utm_id=diagcode&utm_content=implicit_this_reference_in_initializer#implicit_this_reference_in_initializer

I have this class:

```Dart
class Person {
  String firstName;
  String lastName;
  String Function() fullName = () => '$firstName $lastName';  //ERROR: The instance member 'lastName' can't be accessed in an initializer

  Person(this.firstName, this.lastName);
}
```

But because `lastName` is accessed in a lambda -> it is not accessed yet until the lambda is evaluated/called -> it is not accessed in the initializer yet -> possible.

On the other hand, although `lastName` appears in the initializer, it is not accessed yet.

The funny part is here, I trick the compiler by adding the `late` modifier into `fullName` then it works:

```Dart
class Person {
  String firstName;
  String lastName;
  late String Function() fullName = () => '$firstName $lastName'; 

  Person(this.firstName, this.lastName);
}
void main() {
  var person = Person("John", "Doe");
  log(person.fullName());

  person.firstName = "Jack";
  log(person.fullName());
}
```
The output is:
```
[log] John Doe
[log] Jack Doe
```

So it is some kind of hidden feature of Dart! please unlock it.

**Comment by munificent** [comment]
> But because `lastName` is accessed in a lambda -> it is not accessed yet until the lambda is evaluated/called -> it is not accessed in the initializer yet -> possible.

It can be very hard to prove that in general. Consider:

```dart
class C {
  final int x;
  final int y = (someComplexConditional() ? (() => x + 1) : () => 0)();

  C(this.x);
}
```

> The funny part is here, I trick the compiler by adding the late modifier into fullName then it works:

It's not a trick. The `late` feature was designed specifically to enable this pattern. When variable is marked `late` (including an instance field), the initializer is run lazily on first use. Since you can't access an instance field until after the instance has been created and made accessible, this means it's always safe to allow accessing other instance members in the initializer for a late instance field, so we let you.

Note that using `late` *does* mean there is some risk of runtime errors. If you have a cycle between them, it will throw an exception.
