### ISSUE TITLE
Allow pattern matching on "spreaded" items

### ISSUE THREAD

**Issue by rrousselGit** [dart-lang/language#3285]
Hello! Not sure what the best title for this would be, but anyway.

Consider a `List<num>`. Currently we can write:

```dart
List<num> list = <num>[1, 2, 3, 42.1];
switch (list) {
  case [....List<int>(), double()]:
    print('A list of ints which ends with a single double');
  default:
    print('failed to match');
}
```

This code runs, but it prints "failed to match".   
It appears that `case [...List<Type>(), 42]` is not different from `case List<Type>() && [..., 42]`

This feels unexpected to me. I would've expected the spread operator to mean that we want to check for every items' type.

**Comment by TimWhiting** [comment]
This would mean that types which implement lists would have to specify how to check the elements' type for a subrange or the pattern desugaring would have to iterate through the elements checking each element's type. This seems like it might create an unexpected performance problem. I guess that you could argue that if you didn't want to check the element's type you would just use a variable pattern to capture the elements from the spread rather than using a type pattern. 

However, what if in the future the captured spread is implemented with an iterable rather than a list. Is a captured spread guaranteed to be a list, and if not it seems like a type pattern should not be allowed?

I'm curious about the use case that prompted this. Is it really a dynamically sized list or is it something you could use a record for?

**Comment by munificent** [comment]
> It appears that `case [...List<Type>(), 42]` is not different from `case List<Type>() && [..., 42]`

Sort of. What's actually going on is that a rest pattern (`...`) is specified to extract the elements by calling `sublist()` on the underlying list. That method (on the core library's `List` type, at least, your own implementation of `List` can do whatever it wants) preserves the runtime type argument of the original list. So, since the original list is a `List<int>`, that's what `sublist()` returns too.

This is working as intended. As @TimWhiting says, we don't want the overhead of iterating over every extracted list item and checking its type.

There isn't really a good pattern for "match if all elements in this list meet this predicate". If I were you, I would do, maybe:

```dart
List<num> list = <num>[1, 2, 3, 42.1];
switch (list) {
  case [...var leading, double()] when leading.all((e) => e is int):
    print('A list of ints which ends with a single double');
  default:
    print('failed to match');
}
```

**Comment by mateusfccp** [comment]
@munificent nit: I think you meant `leading.every` instead of `leading.all`.

**Comment by munificent** [comment]
Oops, yes!
