### ISSUE TITLE
Public, Private and Protected Access Modifiers

### ISSUE THREAD

**Issue by offensive-penetrator** [dart-lang/language#3289]
Please add this to the language, because I'm done with that.
If I'll get no fair response, I'll just move on to another language.

**And thanks for all of the supporters.**

**Comment by lrhn** [comment]
If your problem is that you don't like writing `_`s in front of names, then I will suggest finding another language.
We have no current active plans to change that. We might, in the depth of time, but that can be said about anything.
And it's been discussed for a long time, e.g., in dart-lang/sdk#33383 or #1446. Nothing has changed.

If there is something you want to do with public or private declarations, that you cannot achieve with Dart's existing public (default) or library private (`_`-named) access control, I'd like to know what that is. If anything, having a declaration be private to its compilation unit is _more_ flexible than just private to a single class. After all, you can always put a single class into each library, and then library privacy *is* class privacy.

The access control that Dart is actually *missing* is `protected`, and I do miss it too.
But again, while we are always pondering if there is something we can do about it, it's not currently considered a high priority.
Look at any of: #2571, #1026, #835, #757 for ideas.
(Personally, as someone who writes libraries for others to extend and who could use `protected`, I'd still rather spend resources on https://github.com/dart-lang/language/issues/1076, than on adding `protected`.)

Closing this issue, and deferring to the existing issue #835. Feel free to engage there.
