### ISSUE TITLE
void should be a subtype of dynamic in compile time

### ISSUE THREAD

**Issue by yelliver** [dart-lang/language#3294]
`void` should be a subtype of `dynamic` in **compile time**:
```Dart
void foo() {}

dynamic bar() {}

void main(List<String> arguments) {
  print(foo()); // ERROR here!, because foo() return void, so it can't be used as a param of print()
  print(foo() as dynamic); // it works
  print(bar());
}

```
I have some conclusions:
- `bar()` function does not return anything, so it actually has the `void` return type -> we can replace by `dynamic` -> `void` **IS-A** `dynamic`.
- It works when we call `print(foo() as dynamic)` while `foo()` returns `void` -> we can cast `void` as `dynamic` -> `void` **IS-A** `dynamic`.

Then why can't we call `print(foo());`?

**Comment by lrhn** [comment]
Why do you do `print(foo());`.
Which value do you expect it to print?

The type `void` is actually a subtype of `dynamic`. 
You're just not allowed to use the value of an expression with static type `void`. That's a special rule specifically for `void`, not something related to subtyping.
An expression with static type `void` should be considered as having _no_ value. There is nothing to print. It's a non-value.

You're allowed to _cast_ the result of a `void` expression to another type, including `dynamic`. (That was a bad idea IMO, but it's allowed.) There still is no useful value, if you're lucky it's going to be `null`, if you're unlucky it's some random value that got returned by a `void foo() => expression;` declaration.

All in all, working precisely as specified. The only change I'd consider is to disallow casting from `void` too.

**Comment by yelliver** [comment]
> You're just not allowed to use the value of an expression with static type void. 
Then why can I do like this?
```
void foo() {}

void bar() {
  return foo();
}
```
In the above example, I don't expect the return result of `foo()` but I expect that `foo()` is executed.

**Comment by eernstg** [comment]
Agreeing with @lrhn's response, I can add a few extra comments on these examples:

> why can I do like this?

```dart
void foo() {...}

void bar() {
  return foo();
}
```

Technically, this is a case where it is not an error to use the value of an expression with static type `void` because it is specified explicitly [here](https://github.com/dart-lang/language/blob/39efdc7f6b693bb096a82a243970c3711f9cd240/specification/dartLangSpec.tex#L18952). In other words, this situation is on the whitelist&mdash;and it's a non-error because we say so. ;-)

The _reason_ why we have this situation (and several other similar situations) on the whitelist is primarily that the updates to the treatment of `void` happened during the evolution of the language, and we did not want this change to be breaking in ways that could easily be avoided. Another reason, and a more specific one, is that the value of `foo()` in `return foo();` is expected to be discarded  shortly after being passed as the return value because that function has the return type `void`, so all callers should discard the returned value. Most other elements in the whitelist are similar: We can allow the result of an expression of type `void` to be used when that usage will in turn cause the object to be discarded "almost immediately". The big exceptions are that we can assign a `void` expression to a `dynamic` variable/parameter, and we can cast the expression. The former is again included in order to avoid breakage (also: if you're using the type `dynamic` then you're on your own anyway). The latter is included because we wanted to give developers the ability to escape the type `void` for whatever reason, as long as they are willing to use an explicit `as`, hence marking the expression explicitly as a special and dangerous expression.

```dart
var result = foo();
```

In this case the inferred type of `result` will be `void`. The situation is the same as before: The value is stored in the local variable `result`, but every usage of that value will again be subject to the standard static checks intended to ensure (softly) that this value is discarded.

> I am creating a function like this:

```dart
run2<T>(dynamic exp0, T exp1)  => exp1;
```

The ability to write a function similar to `run2` was _exactly_ one of the main reasons why we made it a non-error to pass the value of an expression with static type `void` to a parameter with type `void`. However, with that particular declaration of `run2` you will encounter a compile-time error (passing a `void` value to a `dynamic` parameter isn't on the whitelist). You could use the parameter declaration `void exp0`, which would allow invocations like this one:

```dart
void main() {
  run2(print('first'), print('second')); // OK.
}
```

However, you would then get a compile-time error for `run2(1, 2)`, which is inconvenient (you would surely want to be able to evaluate two expressions and discard the value of the first one even in some cases where that first expression has a non-voidy type. But you can use this declaration:

```dart
run2<S, T>(S exp0, T exp1)  => exp1;

void main() {
  run2(print('A'), print('B')); // OK.
  run2(1, 2); // OK.
}
```
