### ISSUE TITLE
How do augmentation libraries work when applied on sync*/async/async* functions?

### ISSUE THREAD

**Issue by rrousselGit** [dart-lang/language#3317]
Hello!

I was wondering how the gritty details of augmenting a function works. Does it work like function composition, or does it enable modifying the annotated function?

Say we have:

```dart
Stream<int> example() async* {
  yield 1;
}
```

For augmenting it, which one do we write?

```dart
augment Stream<int> example() async* {
  print('Before');
  augment super.example();
}

// or:

augment Stream<int> example() async* {
  print('Before');
  yield* augment super.example();
}
```

Also, I'm wondering if the final code looks like:

```dart
Stream<int> newFunction() async* {
  print('Before');
  yield 1;
}
```

Or:

```dart
Stream<int> newFunction() async* {
  print('Before');
  yield* example();
}
```

This matters for async*/async functions, as it changes when that `print` happens.
With the former, the `print` happens when the augmented stream starts. But with the latter, there is a small delay between the `print` and the stream actually starting.

I'd quite like if it was the former. But I assume it's going to be the latter, right?

**Comment by jakemac53** [comment]
To answer your original question, the augmenting function definition only needs to match the original signature, if the augmented one is a `sync*` function it does not have to also be a `sync*` function. If it is a `sync*` function then you would want to use `yield* augment super()` to call the original. And otherwise you would want to do some manual adding of the original stream to some stream controller etc.

**Comment by rrousselGit** [comment]
> Otherwise you are doing something very unexpected. But it isn't likely feasible for us to enforce that you actually call it (or even necessarily desirable).

It certainly isn't desirable :)
One such example would be a `@Debounced(duration)`

____


Does that mean overall that it is equivalent to function composition in the end? So an augmentation using `async*` on a function which also uses it involves creating 2 Streams, and therefore delays the async process twice?

**Comment by jakemac53** [comment]
> Does that mean overall that it is equivalent to function composition in the end?

Yes, exactly. It works almost identical to an override, except that instead of calling `super.<method>()` you call `augment super()`. You can still also call `super.<method>()` so you actually have a choice as to which you invoke.

> So an augmentation using `async*` on a function which also uses it involves creating 2 Streams, and therefore delays the async process twice?

Correct, you would end up with two streams - but I don't know actually the details of `yield*` to confidently speak on the exact timing implication. It would be no different than two normal async* methods being used in the same way though.

**Comment by rrousselGit** [comment]
I see, thanks! Slightly unfortunate, but I guess my use-case is too rare anyway
