### ISSUE TITLE
Drop the `var` in `for ...in ` loop

### ISSUE THREAD

**Issue by He-Pin** [dart-lang/language#3344]
```
      for (var element in it) {
        yield* TinyJson(element).leaves;
      }
```

I think it can be simpler with :
```
      for (element in it) {
        yield* TinyJson(element).leaves;
      }
```

The `var` is not needed.

**Comment by lrhn** [comment]
Currently you are allowed to omit the `var`, then the name has to be an existing variable, and the loop assigns to that variable on each iteration.

I wouldn't mind removing that feature, and require you to do that assignment in the body instead, but it is a breaking change.

**Comment by benthillerkus** [comment]
I think the assignment to existing variables is surprising - I've been using Dart for years now and just learned about it.

Not sure about making `var` implicit though. If making anything implicit, `final` would make more sense imo.

**Comment by munificent** [comment]
> I wouldn't mind removing that feature, and require you to do that assignment in the body instead, but it is a breaking change.

This is one of those features where I think it would have been good to do it before Dart 1.0 (in fact, [one of my oldest blog posts](https://journal.stuffwithstuff.com/2009/05/15/loops-in-magpie/) was about exactly this for a hobby language) but now the change wouldn't be worth the cost.

> It would also break the current rule that no variable is introduced without a `var`, `final` or type.

Parameters and catch clauses break that already. :)

**Comment by lrhn** [comment]
> Parameters and catch clauses break that already. :)

They do. Mostly parameters, it's not a coincidence that the catch clause was made to look like a parameter list.
The locations where we introduce variables are after a type, `var`,  `final` or `const`, and _before_ a `=>` or body `{...}`.
We could probably argue that the variable of a `for`/`in` loop is "like a parameter". 

Heck, we could provide a completely new syntax for iterating, where it looks much more like parameters, like:
```dart
xs.for(x) => print(x);
xs.for(x) {print(x);}
xs.for=>print(it);
xs.for{print(it);}
xs.for:print(it)
```
(I'd prefer `xs.each:...` to `xs.for:...`, but `for` is a reserved word.)

And maybe say that if the iteratee is a record, we spread-call it, so you can do:
```dart
var sums = [listOfPairs.for(x, y) => x + y];
```
I don't think that, very top-of-my-head, syntax is a good fit for Dart today. If we get method parameter blocks in general, like `xs.forEach{ body using it}` being equivalent to `xs.forEach((it) {body using it})`, that might change.

I also think we *could* do the change to the existing `for`/`in` loops **if** we can piggy-back it on a larger change that require migration anyway.
Something like "final by default" might be big enough. (But also so big that it's doubtful wheter we can get away with doing it.)

I don't think iterating using an existing variable is at all common, so disallowing it wouldn't be *that* expensive a migration.
But allowing you to omit the `var` is also not a big impact, so we wouldn't bother doing it *by itself*.

(If we had a continuous migration tool, that allowed you to migrate any language version to any later language version, so that `dart upgrade --language=3.5` would auto-migrate your entire package to 3.5 and update SDK constraint to ^3.5.0, then I think we could get away with more syntactic changes. Nobody should ever just change their pubspec.yaml to change langauge version, they should run the migration command, and it would "just work" for any change where meaning _can_ be preserved.)

**Comment by munificent** [comment]
I'm going to go ahead and close this because I think it's very unlikely that we'd take a breaking change here just to eliminate 3-5 characters.
