### ISSUE TITLE
can't extend class that only has a private constructor

### ISSUE THREAD

**Issue by lastmeta** [dart-lang/language#3360]
consider this simple class
```
@immutable
class FloatingLabelAlignment {
  const FloatingLabelAlignment._(this._x) : assert(_x >= -1.0 && _x <= 1.0);

  final double _x;
  static const FloatingLabelAlignment start = FloatingLabelAlignment._(-1.0);
  static const FloatingLabelAlignment center = FloatingLabelAlignment._(0.0);

  @override
  int get hashCode => _x.hashCode;

  @override
  bool operator ==(Object other) {
    if (identical(this, other)) {
      return true;
    }
    if (other.runtimeType != runtimeType) {
      return false;
    }
    return other is FloatingLabelAlignment
            && _x == other._x;
  }

  static String _stringify(double x) {
    if (x == -1.0) {
      return 'FloatingLabelAlignment.start';
    }
    if (x == 0.0) {
      return 'FloatingLabelAlignment.center';
    }
    return 'FloatingLabelAlignment(x: ${x.toStringAsFixed(1)})';
  }

  @override
  String toString() => _stringify(_x);
}
```

how can I extend it? maybe it's a design of the language that I cannot?

```
class SpecialFloatingLabelAlignment extends FloatingLabelAlignment {
  const SpecialFloatingLabelAlignment._(super._x): super._(0.0);
}
```

well that doesn't work.

"""
The class 'FloatingLabelAlignment' doesn't have a constructor named '_'.
"""

I have to create a an extension of this because I've extended the InputDetector, and overridden the entire file, actually which, in a roundabout way calls `FloatingLabelAlignment._x` in a couple places... anyway... I need to extend it in my file or basically override an entire other file, which is what I ended up doing anyway.

Is this by design or do I just not know how to extend a private-constructor-only class?

**Comment by lrhn** [comment]
This is by design.

You cannot extend a class which does not expose an accessible generative constructor. Accessible means not having a library private name in a different library.

To extend a class, your class's constructor needs to invoke the superclass's constructor, and you can't do that if you can't refer to the constructor, because it's private.

The class isn't `final`, so you can implement it, but if other code is reading `_x` directly, even that is going to be tricky.

The code simply does not appear to be designed or intended to be extended.
If you really need to, either copy it all (license permitting), or talk to the author about making it extendable.
