### ISSUE TITLE
Implicit cast-and-construct from dynamic to extension type?

### ISSUE THREAD

**Issue by srawlins** [dart-lang/language#3369]
The (only?) implicit cast we have left (I think I'm not including coersions...) is "from dynamic to anything". So in this code:

```dart
extension type E(int it) {}

void main() {
  dynamic i = 7;
  E j = i;
}
```

Is this legal? Does `i` get implicitly cast to `E` which invokes `E`'s primary constructor? I think this is all expected and fine, but it's not really spelled out in the spec, I think.

 CC @eernstg

**Comment by eernstg** [comment]
Yes, I would expect `E j = i;` to be accepted without errors. At run time it would check that `i` is an `int` (and it wouldn't do anything beyond that).

I think it's fair to say that this treatment is covered by the existing specification of assignability, so there shouldn't be a need to put anything into the extension type specification about it.

However, I would also hope that this initialization could be flagged by a lint saying that a cast to an extension type is a questionable action (cf. https://github.com/dart-lang/linter/issues/3625#issuecomment-1669844104).

**Comment by lrhn** [comment]
> ```dart
> extension type E(int it) {}
>
> void main() {
>  dynamic i = 7;
>  E j = i;
>}
> ```
> Is this legal? 

Yes. 

> Does `i` get implicitly cast to `E` 

Yes.
After type inference, this should be equivalent to:
```dart
 extension type E(int it) {}
 void main() {
   dynamic i = 7;
   E j = i as E; // Implicit downcast from dynamic to context type.
}
```
There is an implicit downcast from `dynamic` to the non-top context type, like always.
It doesn't matter that the context type is an extension type.

> which invokes `E`'s primary constructor? 

No. It just gets cast.

Casts are *runtime* operations. At runtime, extension types do not exist. They're completely gone, replaced by their representation type.

The code that actually runs will be:
```dart
void main() {
  dynamic /*aka Object?*/ i = 7;
  int j = i as int;
}
```

> I think this is all expected and fine, but it's not really spelled out in the spec, I think.

I think it is. It might be implicit, because it is a consequence of the interaction of how extension types work at compile-time and at runtime, and completely standard behavior.

* Implicit downcasts do not care about extension types. They will downcast to any type.
* Casts to extension types happen at runtime where it will be a cast to the representation type.

**Comment by srawlins** [comment]
Thanks! Filed https://github.com/dart-lang/linter/issues/4760
