### ISSUE TITLE
Should augmentation libraries re-use the `part` and `part of` syntax? 

### ISSUE THREAD

**Issue by jakemac53** [dart-lang/language#3371]
See original discussion in https://github.com/dart-lang/language/issues/3367.

I think there is a general agreement that we don't want to end up with both part files and augmentation libraries.

## Current strategy, eventually delete part file support

We would have both around for some time and eventually remove part files.

This provides a gradual migration path, and we can control the timing as we see fit. But it also means users might continue using part files in the meantime.

## Alternative strategy, just re-use `part` syntax

An alternative solution would be to language version a change where part files just become augmentation libraries. This would avoid any duplicate syntax. Augmentations have all the same functional abilities of part files (and more), so all part files can be replaced by an augmentations library.

This would be breaking because the import scope is not shared between augmentation libraries and the original library. For hand written code we could probably write a quick fix to copy all imports from the original library over (and possibly then remove unused ones).

Code generators are a bit trickier, and they are one of the primary users of part files. They would have to know to add imports when generating code for part files that are actually augmentations (they would have to do this conditionally based on the language version of the original library). 

## Other considerations

- Which syntax do we think is best in the long term? I personally think "import augment" more accurately describes what is happening, since augmentation libraries can actually modify existing declarations instead of being purely additive. I don't love that it is two separate keywords though. I could also see just doing `augmentation '<uri>';`.

- What about all the documentation for `part` files that exists today? Would it be better for them to just be completely out of date (documenting a non-existent feature), or just somewhat wrong in terms of the semantics?

**Comment by rrousselGit** [comment]
I'm not sure I understand what would be breaking by reusing "part"?

Is it that the augmentation libraries need to import things even if the augmented library already imports it?
If so, is that limitation necessary?

**Comment by jakemac53** [comment]
> Is it that the augmentation libraries need to import things even if the augmented library already imports it?

Yes, this is the breaking part.

> If so, is that limitation necessary?

It is imo desirable, but it is not strictly necessary. One of my biggest gripes about part files is how they share an import scope with the main library. It causes a lot of unnecessary context switching.

We also definitely do need the ability to add new imports to augmentation libraries, so having both is weird and opens up a whole lot of stylistic choices which will lead to more lints (maybe conflicting ones) and more churn in code reviews etc. You now have to ask yourself, "should I put this import in the augmentation library or the main library?".

**Comment by jakemac53** [comment]
Pragmatically it would also make generating augmentation libraries harder overall. You need some knowledge of the original to ensure you aren't creating duplicate import prefixes.

**Comment by rrousselGit** [comment]
I personally was thinking that imports could be shared only in one way.

Such that imports in the file containing `parts` would be accessible in the `part of`. But imports inside of `part of` files would not be accessible in the `part` side.
So that wouldn't pollute namespace. At least not in the context of code-generation.

Code-generators may be creating duplicate imports this way. But I don't think that's a big deal.

**Comment by jakemac53** [comment]
The namespace of code generators themselves would be polluted though with anything from the parent library.

> Code-generators may be creating duplicate imports this way. But I don't think that's a big deal.

Duplicate imports might be OK but duplicate import prefixes is not ok.

**Comment by lrhn** [comment]
I think the augmentation library should see the present file's imports. Those are potentially there because the types are used in the signatures of the declared members, which the augmentation file does see.

I'll try to write up a proposal for how to define the scopes of such hierarchical part files.

**Comment by jakemac53** [comment]
> Those are potentially there because the types are used in the signatures of the declared members, which the augmentation file does see.

This isn't an issue though you just have to import the types that you actually interact with in the augmentation as well. This keeps the namespace for the augmentation library limited to the imports it is actually using, instead of unnecessarily polluted.

I strongly believe that the implicit behavior of parts is just entirely wrong here, and that in fact this behavior is the primary reason that almost nobody uses them. It seems like a small thing but once you actually try using parts for a large package they are a terrible experience.

**Comment by lrhn** [comment]
And I think that if parts could have their own imports, which don't leak out to the surrounding library, and maybe exports, people would be very happy using parts instead of separate libraries. I know I would.
I'd be *annoyed* if I didn't get the imports of the parent library in the part. Most of the time, they're exactly what I need. That's why parts work at all today.

**Comment by scheglov** [comment]
I would prefer for augmentation libraries to have their own imports, not inheriting any from the library, or the other augmentation library. No need to pollute augmentations with unnecessary imports.

Adding imports is easy, the analysis server will help you with quick fixes and completion suggestions from not-yet-imported libraries.

**Comment by rrousselGit** [comment]
Thinking about this more, what about private symbols?

From what I remember, augmentation libraries could define private symbols without them being accessible in the augmented library – Although I may misremember.
But if that's the case, wouldn't this conflict with `part`?

**Comment by jakemac53** [comment]
All symbols including private ones are available, it works the same as parts in that regard.

**Comment by joranmulderij** [comment]
From a code generation point of view, it makes a lot of sense for the augmentation library to have it's own namespace, and thus also it's own imports. Generating code without a fresh namespace makes it impossible to guarantee that nothing will clash. It does indeed make code generation harder in some cases, especially when you need to explicitly use a symbol that is imported to the augmented library.

At that point I think you could even just use normal imports, where the augmentation library imports the augmented library and also the other way around.

I'd say reuse the syntax only if their semantics are completely backwards compatible. That includes private declarations in the augmentation libraries. If that is not the case then it is probably better to use different syntax. Otherwise people that don't know about this change will end up in really difficult-to-debug situations with the semantics of existing syntax suddenly changed.

**Comment by lrhn** [comment]
I'd let parts have their normal semantics, and then add things on top, which no existing part will have.

The declarations of the main library, and the imports of the main library, are available in the part file. The declarations of the part file are available in the main library file. Since it's currently a compile time error to declare the same name twice, there is no conflict.
There's really just two scopes, the import scope (of the library file, which is the only one which can have imports) and the declaration scope(of the entire library, all parts include.).

Then allow part files to declare their own imports. Those will build on top of the parent file's import scope, and if prefixed, the prefixes are not part of the library declarations. The resulting scope of the part file is:
- parent imports
- parent import prefixes 
- own imports
- own imports prefixes
- library declarations

A part file can not make a member declaration which conflicts with a parent declaration or prefix. If it declared a prefix with the same name as a parent import prefix, it's a new local import scope, it cannot add to their parent import scope.

If the part file declares no imports, it can still just be textually inserted in the main library. If it does, a rewrite into a single file might need to give all the imports fresh prefix names.

We can also allow part files to have part files themselves (and exports, but let's postpone that for later). Each part extends the imports of their parent.


Then we add augmentation declarations.
Any file in a library can contain an augmentation declaration for a declaration of the library.
An augmentation is applied to an existing declaration, possibly after a number of other augmentations.
Every library can have at most one top -level non-augmentation declaration for each name. That one is globally known. Each part file sees a declaration with that name. Which signature it has depends on how many augmentations have been applied before reaching that part.

The order of augmentation application is: augmentations in the same file as the original declaration first. Augmentations of a file are applied in source order if it contains more than one.
Then the part files of that file, if any, are processed in declaration order.
Then the parent file is processed, if any, just skipping the already visited part file.

So depth first, pre-order, but not necessarily starting at the top of the part tree.

No augmentation imports or files. Everything is just part files, and augmentations can occur anywhere, even in the same fine as the main declaration, or in the library file, when the main declaration is on a part file.

And even without using augmentations, we still get the ability to have imports in parts.

**Comment by rrousselGit** [comment]
Maybe we should have an annotation to mark symbols are "should be used only by the defining file". And maybe the analyzer could pick it up to hide those from autocompletion.

Macros are bound to generate some "should not be used" elements.

**Comment by lrhn** [comment]
Give them a name like `_$macro_foo$banana`, and I'm sure people will know not to use them.

But it might be useful to allow a part file to declare *part-local* declaration, which is not exported into the scope of the entire library.
Complete strawman:
```dart
part int x = 42;
part int banana() => x;
```
would declare names that are visible in the `part` file (and its sub-part-files), but which do not become part of the "library declarations", the exported declarations that the rest of the library can see.
It's not name-mangling like "library private", just scope control. The name is just not visible in the scope of the file that included the part file.

Only works for top-level declarations, maybe static declarations too. Not instance methods, those exist on the object, not just in a namespace.

**Comment by joranmulderij** [comment]
@lrhn I like the proposal, however I do think it has some issues.

If part files build on top of the imports of the parent library, then generators don't get to build on an empty namespace, which means that generators could end up generating code that clashes with the import namespace of the parent file.

> Macros are bound to generate some "should not be used" elements.

In my opinion part files should not bleed their private declarations into the parent file. This way generators can just make use of private declarations without those polluting the parent namespace. I think this issue is relatively minor, because the generator can just make those elements private, which would mean they only infect the parent library. It could even be useful to be able to create declarations that the parent file can use (apart from augmentations).

**Comment by rrousselGit** [comment]
> In my opinion part files should not bleed their private declarations into the parent file.

Macros often want to share some private declarations with the parent file.

This usually happens when a user declares something as private in their annotated code.
Say a user defines:

```dart
@freezed
class Example {
  factory Example(int _value) = _Example;
}
```

This would generate:

```dart
augment class Example {
  int get _value;
}
```

And it is totally legitimate for folks to use the generated `Example._value` within the library it is defined in.

**Comment by joranmulderij** [comment]
> No augmentation imports or files. Everything is just part files, and augmentations can occur anywhere, even in the same fine as the main declaration, or in the library file, when the main declaration is on a part file.

I think this would be nice. I'm pretty sure this could be made to be backwards compatible with the current part system. If you compare the current part system and the one as proposed in https://github.com/dart-lang/language/issues/3371#issuecomment-1826826067, it can be seen that they overlap when analyzed on current code.

| Current part scope | New part scope | Equal for current code |
|--------|--------| - |
| Parent imports | Parent imports | Yes |
| Parent import prefixes | Parent import prefixes | Yes |
| Not possible | Own imports | Yes |
| Not possible | Own import prefixes | Yes |
| Same scope | Parent declarations (including private) | Yes (I think) |

Doing the same analysis on the parent file results in the following:

| Current part scope | New part scope | Equal for current code |
|--------|--------| - |
| Imports | Imports | Yes |
| Import prefixes | Import prefixes | Yes |
| Same scope | Part declarations (including private) | Yes (I think) |

I'm pretty sure this makes it completely backwards compatible. If that is the case, I would be in favor of this option.

**Comment by lrhn** [comment]
> could end up generating code that clashes with the import namespace of the parent file.

That shouldn't be a problem.
If the generated declaration's name is the same as one of them imports, then it's a public name which is exported by the library itself.
That's not a name that the main library file can reasonably expect to be oblivious of. It's one of the public declarations of the library it's defining, not just some internal detail. If that shadows a main library import name, the main library will have to use a prefixed import.

**Comment by jakemac53** [comment]
In general I don't see any technical issue with your proposal, and macro generated code is going to use its own prefixed imports anyways. So it is really just a design choice. cc @munificent may want to weigh in here.

Personally, I just don't think it is desirable for parts to inherit the import scope from their parent libraries. I think it makes code less readable, and more of a pain to update. It adds more choices whenever you want to import a new thing (should this go in my current library or a parent library, and should I be de-duping imports by pushing them up to the parent or duplicate them in multiple parts, even if the parent doesn't actually need the import, etc). You also get a much more polluted namespace in each of these parts. In return I don't think you really get anything other than a bit less typing, but I think future maintainers of the library would prefer to see all the imports immediately in the current file anyways.

**Comment by rrousselGit** [comment]
The flip side of the argument would be that parts would likely often need to import what their parent libraries import too.

Say a user writes:

```dart
import 'user.dart' as user;
@data
class Example {
  Example(this.user);
  user.User user;
}
```

For the macro to generate a `Example copyWith({user.User? user})`, it would need to know about the import.

**Comment by jakemac53** [comment]
> The flip side of the argument would be that parts would likely often need to import what their parent libraries import too.

Some subset of them, yes, but quite often not all of them.

> For the macro to generate a `Example copyWith({user.User? user})`, it would need to know about the import.

They don't _need_ to use the same prefix, and can always rely on the auto-generated ones. It is true though that where a prefix was used, if parent library import scopes were inherited, you could re-use that prefix and not add a new import, which would likely result in a more readable prefix.

**Comment by rrousselGit** [comment]
That's putting more logics onto macros though. It adds new possible error cases.
This could be especially tricky when considering type-manipulation utilities such as `leastUpperBound`. In the build_runner world, those utils tend to strip the prefixes which mess-up the output.
But of course, that could also be automatically handled by a well-designed library.

I'm just not sure what the value is here. I personally never cared about generated files having a polluted namespace.

**Comment by joranmulderij** [comment]
I personally find the polluted namespaces in generated libraries quite annoying. I would prefer code generators take a more systematic approach and having control of what symbols they operate with and not just hope that the end user has the correct stuff imported into scope. I also kinda hate the idea of code generators just going with the import prefixes that the user went with, which is what happens with `build_runner` right now. I would much rather see a process like this:

```dart
// user.dart
import 'user.dart' as user;
@data
class Example {
  Example(this.user);
  user.User user;
}

// user.g.dart
import 'package:myapp/dataclasses/user.dart' as i1;
augment class Example {
  // is able to use i1.User
}
```

A significant downside that needs to be noted with taking such an approach would be that backwards compatibility would be broken. This would mainly impact existing code generators, but would also effect normal codebases casually using parts. Especially the code generators would be very hard to port, since you would not be able use automated migration tooling, though it would be possible for `build_runner` to import these temporarily to smoothen out migration.

**Comment by rrousselGit** [comment]
I like the `part of "parent.dart" as p;`. That feels like a good compromise

Although what happens if the parent library also has import using prefixes? Do we end-up with `p.p2.User`?

**Comment by joranmulderij** [comment]
I agree that inheriting imports is better for the manual use case. The idea of "import shadowing" is really nice in my opinion and really fits the manual use case well. The `part of "parent.dart" as p;` syntax would be a nice addition for both the manual and code-gen use cases. I was wondering the same thing about import prefixes in the parent file. I think `p.p2.User` is the only viable option if you want to put both the parent imports and parent declarations behind a part prefix (you cannot really call them import prefixes anymore right?).

Another reason to keep inherited imports would be backwards compatibility. As I explained above I'm pretty sure you could keep backwards compatibility.

**Comment by jakemac53** [comment]
I will just re-iterate what I said before, for the last time though. Yes, I agree there is no _technical_ challenge or issue with inheriting the imports. That doesn't make it the right choice on its own, lots of things could be sound but not a good idea.

I would rather have all the available libraries to a given _file_ available immediately in that file. It results in a less polluted namespace, an obvious place to put new imports, and it makes it easier to figure out where some symbol is imported from when not using an IDE.

I consider `part` files as they currently exist to be a failure. They are actively discouraged everywhere that I know of and only really used in legacy parts of the SDK. This is not because they are unsound. It is because they are a pain to use, and it is precisely because they inherit the scope of the parent library, IMO.

**Comment by lrhn** [comment]
People fighting over "the one true coding style", where the choice should be semantic, not syntactic, are causing their own problems.

I'd rather have a language which allows me to make the choice that works best for my code, than one which hard-codes a choice which doesn't work well for me.

Then people who want only one thing, can choose that one thing and make lives to enforce it.

If you don't want to inherit the parent file imports, then move all the parent imports and declarations into a separate part too, and have only an empty file with parts at the top. That's a valid style, and an option.

Or explicitly import every make that a part uses, so you never use a name from the parent imports, maybe even have a lint to enforce it. Also valid and possible style. It's what I would do for macros or other code generation, where I'm not the same author working on both files.

Or work like parts today, where you do get all the common and relevant imports from the parent file.
I do use parts, and that actually works well, especially with IDE support for name discovery. All I really need is the ability to make _some_ names local. Names that are _implementation_ details, usually.

But we can give you more flexibility in controlling import inheritance.
- as mentioned, an `as` clause on the `part of` declaration could make it possible to namespace the parent imports.
- `show`/`hide` modifiers on the `part of` declaration.
- some marker on imports which makes them non-inherited. Strawman: `local import ...`. That import is not automatically inherited by part files.

Scope _control_ can be useful in many places, but again, it needs a solid base to work on.

**Comment by munificent** [comment]
Hierarchical imports between parent libraries and augmentations sound like a solution in search of a problem. Yes, technically, it would work. And, yes, technically it would make some code shorter. But it's complexity and mechanism in a language that is adding complexity and mechanism pretty rapidly already. I really do think we should strive for simplicity wherever we can find it because our complexity budget isn't infinite.

> Say a user writes:
> 
> ```dart
> import 'user.dart' as user;
> @data
> class Example {
>   Example(this.user);
>   user.User user;
> }
> ```
> 
> For the macro to generate a `Example copyWith({user.User? user})`, it would need to know about the import.

Think about *how* the macro will generate that. To build the parameter signature for that method, it will use introspection to iterate over the fields on the class. Then it will look up the type annotations on those fields and insert those type annotations into the generated code. The macro API will then ensure that the type annotation is converted to Dart syntax with a non-colliding prefix which is implicitly imported in the generated augmentation library. No need to use the same prefix as the main library, and no chance for problems if the augmentation has something that could collide with that prefix.

As much as possible, macro authors should be using actual introspection objects and identifier references to generate code. Macro others shouldn't be in the business of worrying about import prefixes or identifier hygiene. That path leads to pain and suffering.

> (Or we could allow the party library to make the parent scope:
> 
> ```dart
> part of "parent.dart" as p;
> ```

If we go with the current design where augmentations don't inherit the parent library's namespace, then you can spell that like:

```dart
import "parent.dart" as p;
```

My experience is that almost no users derive positive excitement from mucking around with namespaces, so it's not a feature area where adding more mechanism adds more user delight. It's just plumbing and, like plumbing, if users have to think about it at all, they're probably not having a good time. Given that, I think it's an area where we want just enough mechanism to solve the user's problems and otherwise we should try to just keep it simple and stay out of the way, even if it requires a little more verbosity in some cases.

**Comment by munificent** [comment]
We discussed this in a meeting a while back. My feeling at the time and now is that not having both `part` and `augment` would be nice because the latter largely makes the former redundant.

But I don't think we can *replace* part files with augmentations and reuse the syntax. That would make for a harder migration. Users would be forcibly dragged off part files and have to migrate (with automation, of course) when they want to use the language version that augmentations ship in.

I could see us making that in place switch if part files were rarely used and the migration wouldn't affect many users. But that doesn't seem to be the case. Looking at a large corpus of pub packages:

```
-- File (56652 total) --
  45719 ( 80.701%): no part files    ===================================
   7759 ( 13.696%): is part file     ======
   3174 (  5.603%): uses part files  ===
Took 28.870s to scrape 12900509 lines in 56652 files. (288 files could not be parsed.)

-- By package (1968 total) --
   1477 ( 75.051%): Does not use part files  ===========================
    491 ( 24.949%): Uses part files          =========
```

While most files are Dart libraries that don't use part files, for any given package, there's about a one in four chance that it contains at least one part file. So this migration would affect a lot of users.

It may be that most of these part files are coming from generated code and would go away in a world with macros anyway. But to me, that's another argument for *keeping* part files. It will be easier for code generation package authors to migrate to macros if they can do so at their leisure and aren't immediately forced to do so because their code generator stops working since it can't generate part files anymore.

I could *still* see us doing reusing the `part` syntax if *we really liked it* and felt like it was a good fit for augmentations. I don't think that's the case though. I don't particularly love `augment` and `augmented`, but it seems to work OK. I think `part` and `part of` work well for defining and applying a part/augmentation file. But if we were to reuse part syntax, I don't know what syntax we would use on a declaration to mark an augmentation (currently `augment`) or to access the original declaration (currently `augmented`). `part`, `part of`, and even `partial` don't seem to fit that well.

So, given that it would be a hard migration to reuse the syntax and the existing syntax doesn't actually work that well for augmentations semantics anyway, I think it's best to just leave part files alone for now. My hope is that after augmentations ship users will gradually migrate away from part files and maybe we can deprecate and remove them in a later version.
