### ISSUE TITLE
Switch-expression infers `Object` instead of LUB when all branches return a class that implements the same interface but with different generics

### ISSUE THREAD

**Issue by mateusfccp** [dart-lang/language#3379]
I'm not sure if this was already reported, but I didn't find anything.

## Problem

Consider the following sample code:

```dart
void main() {
  final a1 = A1();
  final a2 = A2();
  final a3 = A3();

  final a = switch (10) {
    0 => a1,
    1 => a2,
    _ => a3,
  };

  printA(a);
}

void printA(A<Object> a) => print(a);

abstract interface class A<T> {}

class A1 implements A<int> {}

class A2 implements A<double> {}

class A3 implements A<String> {}
```

The code above does not compile. `a` is inferred as `Object`, which causes the error: `The argument type 'Object' can't be assigned to the parameter type 'A<Object>'`.

I would expect the `switch` to infer the type as `A<Object>` instead, as all branches returns a `A<Object>`.

The same does not happen if the interface has no type parameters. For instance, the following works:

```dart
void main() {
  final a1 = A1();
  final a2 = A2();
  final a3 = A3();

  final a = switch (10) {
    0 => a1,
    1 => a2,
    _ => a3,
  };

  printA(a);
}

void printA(A a) => print(a);

abstract interface class A {}

class A1 implements A {}

class A2 implements A {}

class A3 implements A {}
```

## Workaround

Currently, we can workaround this by using `switch` statement instead:

```dart
void main() {
  final a1 = A1();
  final a2 = A2();
  final a3 = A3();

  final A<Object> a;
  
  switch (10) {
    case 0:
      a = a1;
    case 1:
      a = a2;
    case _:
      a = a3;
  }

  printA(a);
}

void printA(A<Object> a) => print(a);

abstract interface class A<T> {}

class A1 implements A<int> {}

class A2 implements A<double> {}

class A3 implements A<String> {}
```

**Comment by mateusfccp** [comment]
Thanks, sorry for the duplicate.

I am closing this in favor of the other issues.

**Comment by lrhn** [comment]
The (increased) frequency of this issue being reported is itself a clear signal that improving this would have a big impact.
Also, since it's never very clear *why* you get the useless type, you can't be expected to find the existing issue about it.

(We should make a template answer for this, redirecting to a canonical issue with a good explanation.)

**Comment by srawlins** [comment]
Drive by comment on based on "the (increased) frequency of this issue being reported":

I think we deferred a few pattern features to "later". I don't remember too many specifics, but, an await pattern, this issue, integer range support (I think?), destructuring a function parameter similar to a variable declaration (🙏 🙏 🙏 ). IMHO it would be so sweet to jump on these sooner rather than later. While there is a lot of Dart code now in the universe, maybe there are not many patterns in play, and any breaking change (maybe none are breaking?) would be easier to swallow sooner.

**Comment by munificent** [comment]
> IMHO it would be so sweet to jump on these sooner rather than later. While there is a lot of Dart code now in the universe, maybe there are not many patterns in play, and any breaking change (maybe none are breaking?)

My hope is that none of the patterns changes/additions that we kicked down the road would be breaking changes.
