### ISSUE TITLE
[extension types] platform independence

### ISSUE THREAD

**Issue by modulovalue** [dart-lang/language#3387]
I've been thinking about how I would use extension types with platform dependent types (that is, those that are only available on, e.g., a wasm or ffi target platform) while not restricting myself to a single platform, and it's not quite clear to me how that will work:

Consider the following situation in pseudocode:

library_export.dart
```dart
import 'library_a.dart'
  if (wasm) 'library_b.dart'
  if (ffi) 'library_c.dart';
```

library_a.dart
```dart
// What is the common interface between a wasm integer and an ffi integer that one can depend on without depending on the underlying platform? 
```

library_b.dart
```dart
// ... import wasm ...

extension type MyInteger(wasmi32 int) {
  // do things
}
```

library_c.dart
```dart

// ... import ffi ...

extension type MyInteger(long int) {
  // do things
}
```

library_user.dart
```dart
import 'library_export.dart';

void main() {
  // ?
}
```

It shows 4 libraries:
- library_b is a custom MyInteger for wasm targets
- library_c is a custom MyInteger for ffi targets
- library_a is intended to contain a shared interface between the wasm and ffi implementations
- library_user is a library that is meant to use extension types with platform dependent representation types while not being forced to depend on a specific platform

If we were to use plain old classes, we could have a common interface that does not depend on a specific platform that everybody can depend on, and have the platform dependent code implement that interface. Since extension types can't implement arbitrary interfaces, it seems like there's no way to guarantee that all platform dependent implementations actually implement a common interface.

Of course, since both implementations are intended to run on different platforms, a common interface is not needed. This issue looks at it from a UX perspective. We would like both implementations to implement a common interface so that, e.g., the analyzer can report any missing members. But it seems like that is not possible and one would have to manually check whether all implementations implement the members that we want them to implement without any help from the analyzer.

**Comment by jakemac53** [comment]
One extension type can "implement" another, but that actually "brings along" any implementations.

One possible solution could be to allow `abstract extension type` declarations, and if you implement one of those, then  your extension type must have concrete implementations of any abstract members (or be itself abstract?).

Abstract extension types would not actually come with a "constructor" or be directly castable, but you could use them to type your APIs.

It might be quite niche, although I think for conditional imports it makes sense, since we don't provide any other mechanism to ensure consistency.

**Comment by jakemac53** [comment]
Actually, it looks like you can "redeclare" any method from an extension you implement, without matching the API signature at all. So the notion of an `abstract extension type` would not work for enforcing any kind of specific API.

**Comment by jakemac53** [comment]
Yeah, there are various problems though with this approach. I updated a previous comment as I realized it was also misleading.

These extension types only have any meaning when they are actually the static type of the receiver. So users need to actually be able to see the `MyIntWasm` and `MyIntFfi` types, in order for them to have any effect at all.

So, all the extension types really need to have exactly the same name, although on each platform they will actually be different extension types entirely.

I think you would need to write a custom tool to enforce that they expose the same API, until/unless we changed how configurable imports work such that they do this validation (but actually doing that validation has its own issues and may not be feasible or even desirable, once you have nested platform specific types).

**Comment by lrhn** [comment]
> but it does solve the issue of exposing an interface in `library_a` that can match `library_b` and `library_c`.

My recommendation is to stop thinking the word `interface` together with extension types.

And that's one reason `implements` might not be the best word, because it implies "interface".

What I'd do is, basically, also what I'd do without extension types:
```dart 
import "generic_impl.dart"
  if (dart.library.ffi) "ffi_impl.dart"
  ...;

library ffi_impl;
extension type MyInterface(FfiInt i) {..}
...
library wasm_impl;
extension type MyInterface(WasmInt i) {...}
```

Each program gets its own declaration, they all have the same type, and compatibility is ensured by only using the types in ways that work for all implementations.
May want to add 
```dart
typedef MyInt = FfiInt;
...
typedef MyInt = WasmInt;
```
And maybe injection functions for the types, so users can use them with the same names everywhere.

There is nothing to ensure that the implementations have the same API, other than testing it.

**Comment by modulovalue** [comment]
Thank you, Jake and Lasse.

> There is nothing to ensure that the implementations have the same API, other than testing it.

I hope that eventually the analyzer will be able to do that.

**Comment by eernstg** [comment]
In some of the earlier proposals for the extension types feature there was support for declaring that a given extension type implements the interface of a given interface type. This would amount to a regular override correctness check for each member (yielding a compile-time error if a member was missing or wasn't a correct override). There was no subtyping relationship between the extension type and the types in its `implements` clause, so that's a completely different mechanism than the current meaning of `implements ...` in an extension type.

However, over time the extension type feature evolved in the direction of allowing redeclarations to differ in arbitrary ways from the redeclared declaration (there is no requirement that it must be a correct override relationship, and we can even redeclare a method as a getter and vice versa). This basically meant that there are no superinterface related constraints on the set of member signatures for an extension type.

One reason for this is that it is a constraint which is not justified by the actual semantics of the code: Every invocation of an extension type member is resolved statically, so there is no requirement that different declarations with the same name must have the same signature, or even be the same kind of member.

Another reason is that it allows an extension type to resolve a conflict which would otherwise not be resolvable (say, one superinterface has a getter `foo` and another superinterface has a method `foo`, or they are both methods, but have incompatible signatures). Also, we can use things like `void get foo => throw "Don't call this";` to indicate that a given member `foo` is _taken away_ from the interface (which could otherwise be copied from the representation type `R` by means of `implements R`, where `implements` has the current meaning).

Finally, it was simply a syntactic trade-off: If we use the `implements` clause to express subtype and inheritance relationships among extension types and relative to class/mixin types, then we don't have that syntax available for specifying conformance to a given set of member signatures.

One way to describe this situation is that an extension type `E` has an interface (that is, there is a well-defined set of member signatures that you can use with a receiver whose static type is `E`), but it is unconnected to other interfaces (we can't ask the compiler to check that they are conforming to anything else). This is similar to the interface of a library: We have it for any given library, but we can't specify that it must be the same (or have any conformance relationship) for two given libraries.

This means that member signature conformance checks really don't fit very well into the extension types feature today.

@modulovalue wrote:
> I hope that eventually the analyzer will be able to do that.

Unfortunately, this is then not very likely.

Given that the language as such doesn't need conformance relationships among extension types (and among library namespaces, and possibly other things), we could consider checking it using something like a lint and an annotation:

```dart
@conformsTo(Iterable)
extension type E1<E>(...) {
  bool any(bool test(E? element)) {...} // Lint: `E?` doesn't match `Iterable.any`.
  ... // Other members.
  // Perhaps lint: Missing members: `join`, `forEach`.
}
```

**Comment by modulovalue** [comment]
There's a more general inconvenience with conditional directives that includes this one. I've filed an issue in the SDK repo (https://github.com/dart-lang/sdk/issues/53724) with two possible approaches to solving it.

I think a solution to that issue could be considered a solution to this issue.

**Comment by modulovalue** [comment]
I'm going to close this issue because:
- as Jake pointed out, an extension type implementing an extension type can be used to support platform independence.
- the "safety" issue here is not exclusive to extension types (see: https://github.com/dart-lang/sdk/issues/53724). It might make more sense not to focus on just extension types, but on the fact that there's no way to specify interface-related constraints between libraries (i.e., something like OCaml modules).
