### ISSUE TITLE
Make extension type non-nullability not be implicit.

### ISSUE THREAD

**Issue by lrhn** [dart-lang/language#3415]
The current extension type specification makes an extension type be non-nullable (subtype of `Object`) whenever its representation type is non-nullable.

That made more sense when it wasn't possible to implement non-extension types.

Now you can, so it's possible to write `implements Object` if being a subtype of `Object` is desired, and allowed by the declared representation type being non-nullable.

Making the "being a subtype of `Object`" implicit has two issues:

* It's not possible to *not* be a subtype of `Object` if the representation type is non-nullable. There is no opt-out.
* There are generic extension type declarations where being a subtype of `Object` depends on the *instantiation*, not the declaration.

The former has the effect that changing representation type may also changes non-nullability. 
While the representation type of an extension type is not strongly encapsulated, it's still something authors could recommend/instruct people to not depend on, so that the representation can be changed as a non-breaking change later. (If someone did depend on it, and got broken, they'd be using implementation details that were explicitly not covered by semver promises, aka, asking for it.)
For example, changing a representation type of `extension type Maybe<T>` from `Option<T>` to `T?` would change whether `Maybe<int>` was assignable to `Object` or not.

The latter is more of an implementation complication. 
For all other types, whether it's assignable to `Object` can be determined by looking at the _kind_ of type it is, every type except `T?`, `FutureOr<T>` and type variables are non-nullable, `T?` is not, `FutureOr<T>` is iff `T` is, and a type variable is if its bound or promotion is, which is just structural recursion (type parmeter bounds being a little less trivial). 
But for an extension type, it's necessary to look at the actual instantiation, push that through into the representation type, and then look at that type again. It's not limited to structural recursion, which is likely why https://github.com/dart-lang/language/issues/3263 happens.

So, **should we change that**?

That is: Don't make any extension type automatically implement `Object`.

You can still add `implements Object` explicitly if you want to, if the declared representation type is non-nullable, just as you can always implement any other interface that is a super-type of the representation type.

What you can't do then, is having
```dart
extension type E<T>(T value) { ... }
```
which is a subtype of `Object` if `T` is, and not if it isn't. An `E<int>(1)` won't be assignable to `Object`.
I'm not sure that's actually a problem in practice. It's also not assignable to `int`, and haven't made any attempt to make it be so. In fact, it's a feature that it *isn't*.

I believe that the actually good reasons for making some extension type implicitly non-nullablle, came from not having a way to make them *explicitly* non-nullable. It would definitely be too impractical if all extension types were non-nullable.

That's no longer the case, so the implicit rule is only making things harder,  both to reason about, and likely to implement (although that's probably mostly a sunk cost by now). The one thing it allows is not a use-case that I think we ever actively wanted to support, it just fell out of the definition.

**Comment by scheglov** [comment]
FWIW, from the implementation point of view, even though it is already implemented to look at the instantiated representation type, if we can remove it, I think it is still beneficial in the long run.

**Comment by leafpetersen** [comment]
I think this is a really good suggestion.   There's a direct analogy to variance: we can infer the variance of a type variable by looking at all of the uses of the type variable, but in general we find it more robust and usable to instead declare the intended variance (and check that the actual variance is compatible with the declared variance).

**Comment by eernstg** [comment]
Agreed, this is a very useful proposal!

In particular, the fact that the superinterface graph of an extension type depends on the type, not just the declaration, is a source of complexity in various ways (for the developer who uses extension types as well as tool implementers), and I don't think we gain anything useful in return. Also, as @lrhn mentioned, it is a violation of the (admittedly weak) encapsulation of the representation type.

Ship it!

I hope the analyzer and CFE teams will forgive us for not doing this from the very beginning. ;-)

**Comment by lrhn** [comment]
This has been decided as what we're doing, and is being specified.

An extension type will never implicitly implement `Object`, but can choose to explicitly implement it when the representation type is non-nullable.

**Comment by nshahan** [comment]
This makes sense to me except for the cases where there is a concrete representation type that is non-nullable but no implements:

```dart
extension type MyInt(int i) {...}

main() {
  Object o = MyInt(10); // valid or requires a null check first?
}
```

Does this imply that you must null check a value that can never be null to make it assignable to `Object`? I feel like that might surprise people. Would we want to lint these kinds of extension type declarations and suggest that they `implements Object` or some non-nullable type explicitly?

**Comment by lrhn** [comment]
Neither valid nor fixable by a null check.

An expression of type `MyInt` is not a subtype of `Object`, and it's also not nullable, so doing a null check won't make it non-nullable. The type of `MyInt(1)!` is still `MyImt`, just like `(x as FutureOr<int?>)!` still has type `FutureOr<int?>`, because there is no type in the type system which can represent "that, but not `null`".

If you want `MyInt` to be assignable to `Object`, you need to add `implements Object`, just as if you want it to be assignable to `num` or `int`.
There is nothing special about `Object` in that regard, not any more.

**Comment by eernstg** [comment]
```dart
extension type MyInt(int i) {...}
```

I'd like to add a conceptual remark to @lrhn's description: You could consider this treatment of `MyInt` as potentially nullable as a kind of _encapsulation_.

Of course, it's very easy to break the encapsulation of an extension type because `myInt as int` will strip off the extension type entirely, and nobody will know that this `int` used to be encapsulated in the extension type `MyInt`. Also, there's no trace of the extension type at run time (other than the fact that we may be able to detect that the compiled representation of some extension type members are being invoked with that `int` as the receiver). So, as we all know, this is a very weak kind of encapsulation.

However, I've consistently been pushing in the direction of maintaining the distinction between an expression of an extension type like `MyInt` and an expression of the corresponding representation type `int` during static analysis. In other words, in spite of the fact that developers can easily eliminate the encapsulation provided by an extension type, the static analysis should not do the same thing gratuitously.

One aspect of encapsulation is representation independence. Again, we only have it "weakly", but we may well have the effect that it's easier to change `MyInt` such that its representation type is nullable (or changing it from nullable to non-nullable) than it would be if this property of the representation type were propagated to the enclosing extension type implicitly.

> (It is a little curious that MyInt? x;...; if (x != null)... well promote x to something which is still not -nullable.)

It should promote `x` from `MyInt?` to `MyInt`, and the latter allows us to invoke members of `MyInt` without `?.`, so in that sense it actually works pretty much like a regular class type. We still can't assign an expression of type `MyInt` to a variable of type `Object`, but that's probably a very small part of what we might want to do.

So maybe it's surprising, but it doesn't really matter?

**Comment by eernstg** [comment]
Closing: This proposal was accepted and the specification was updated in #3434.
