### ISSUE TITLE
Change how `augmented` works for operators

### ISSUE THREAD

**Issue by jakemac53** [dart-lang/language#3417]
Follow-up to the conversation [here](https://github.com/dart-lang/language/pull/3404#discussion_r1364307569).

We likely want to change completely how `augmented` works, at least for operators but also possibly for getters/setters.

We should also clarify how `augmented` works for the various types of constructors (see [this comment](https://github.com/dart-lang/language/pull/3404/files/97d637f8a293c01c0ea649919ccfd2f2e2cb6b56#r1365544242)).

**Comment by jakemac53** [comment]
@lrhn had mentioned keeping the existing syntax for getters/setters, @munificent did you have an opinion on that?

My main thought is just that if we are going to do something a bit weird (force normal function invocation syntax), it might just be best to go all in so it is at least consistent, which would mean function syntax for getters/setters as well.

**Comment by jakemac53** [comment]
Another weird case here is for variable initializers, should that also be `augmented()` instead of just `augmented`? That seems even more weird since it doesn't refer to a function at all, just an expression (the original initializer expression).

**Comment by lrhn** [comment]
The variable initializer case is slightly curious because, as you say, it's not a function being referred to, or even a member, only an expression.

The `augmented` doesn't consistently refer to a _member_. It refers to "whatever is relevant" in the super-declaration, where "relevant" means what you need to effectively wrap the _code_ of the augmented declaration.

To wrap a method body, you need to provide valid for it's parameters.
We can do that using function-call syntax.
We can _could_ also just say that you use the pain identifier `augmented`, and it uses the _same_ parameter values as the augmenting member. Basically, it's inlined at the `augmented` operator, with parameters hygienically renamed if necessary.
That's be entirety consistent, and would ensure that the wrapper can't change parameters. The arguments that a caller provides are the arguments that reaches the code they are looking at. Something may happen before or after, but they are still calling that method as well.

That also, obviously, reduces the power of an augmentation. It cannot wrap an argument on the way in, which can surely be useful. But reduced power may also mean increased readability.
Do we know of any use-cases where intercepting and replacing parameters is necessary?
(Could we make the augmented member body use the same parameter variables, then the wrapper can just mutate them? Probably tricky, then an assignment somewhere else can affect promotion. So, no.)

(It's an implementation challenge to avoid code duplication of `augmented` occurs more than once in a member.)

**Comment by munificent** [comment]
> @lrhn had mentioned keeping the existing syntax for getters/setters, @munificent did you have an opinion on that?

I'm OK with that. So basically:

```dart
// Field initializer, variable, getter:
augmented;

// Setter:
augmented = value;

// Function or operator:
augmented(arg, arg, arg);
```

> My initial thought is that if we are going to do something a bit weird (force normal function invocation syntax), it might just be best to go all in so it is at least consistent, which would mean function syntax for getters/setters as well.

It's going to be a somewhat special-case syntactic form that users have to learn no matter what, so it seems reasonable to not require `()` on field initializers and getters since they don't really do anything anyway. Dart has always had a principle of not having extra `()` on getter calls because that can be very confusing if the getter itself returns a closure.

**Comment by lrhn** [comment]
I would use `augmented + v` for invoking an operator then 

I'd mildly inconsistent to have to use both the name of the augmented operator _and_ the word `augmented`, but `_ + _` is the syntax for invoking an `operator+` member, just like `_=` is for invoking a setter, and `_(...)` is for invoking a function.
It follows the same pattern as `augmented=...`, the selector is the entire `augmented+`, so `augmented` is not referring to the receiver, just like `augmented=` refers to the augmented setter without `augmented` referring to the variable.

**Comment by jakemac53** [comment]
> I would use `augmented + v` for invoking an operator then

And `augmented ==` for equality then? Or would we just special case that one?

**Comment by lrhn** [comment]
The `==` is tricky. 
I'd say that `augmented == v2` will *directly* invoke the augmented `operator==`, and not to `null`-checking first. 

That is, the `augment op operand` syntax is not a normal operator invocation, it's a special syntactic form for invoking the augmented implementation. (And an implementation choice could be inlining.)

That means that you _can_ pass `null` as an actual argument to an `operator ==(Object? o)` as `augment == null`.
Nice side-channel, but not something that should be a problem. You're inside the same library, if you _want_ to break the code, you can just rewrite it directly.

**Comment by munificent** [comment]
> I would use `augmented + v` for invoking an operator then

This isn't a hill I will die on, but I do worry that would lead users down a false believe that `augment` is itself an expression because it looks like an operand subexpression here. But it's not, the whole `augment +` is a single conceptual thing.

**Comment by lrhn** [comment]
It is slightly different from `super`, which is also not an expression, but also very similar.
I think people have generally accepted that `super` is not an expression, and `super + 2` is a special form for invoking a specific `operator+`.

The difference is that when augmenting a non-operator, you don't need to repeat the name, it's `augmented(2)`, not `augmented.foo(2)`.
I think that can adequately be explained by "you can only invoke one thing, and you can't tear it off, so it's unambiguous what your street referring to", and the reason you have to write the operator is that it's part of the call syntax itself, it's not for naming.

**Comment by munificent** [comment]
> I think people have generally accepted that `super` is not an expression, and `super + 2` is a special form for invoking a specific `operator+`.

Honestly, I think almost no users have ever actually encountered `super + 2` so they simply don't know that it even exists.

**Comment by jakemac53** [comment]
@leafpetersen would you mind weighing in on this one? I am quite split on it personally, and I don't think we generally have any consensus, so some more opinions/thoughts would be good.

**Comment by jakemac53** [comment]
Fwiw, I took a quick poll of 3 Dart team members and they all had a preference for just using function invocation syntax for operators.

Especially if we aren't allowing trade-offs of `augmented`, that seems to be the least error prone, even if it looks a bit weird for operators to invoke them that way. Specifically:

```yaml
class A {
  operator==(Object other) => other == this;
}

augment class A {
  // Good
  augment operator==(Object other) => augmented(other);
  
  // Error - tearoff of `augmented` is not allowed.
  augment operator==(Object other) => augmented == other;
}
```

If we don't make tearoffs an error I think it is very error prone.

**Comment by leafpetersen** [comment]
I don't really see the argument for using the operator name in the calling syntax.  Did I miss something in the discussion above?  Within a class, the declaration of operators just uses method declaration syntax, so it seems natural to me to just use method call syntax to call them (since it is unambiguous what is being called).  It seems inconsistent to have to say `augmented + 3` when calling an augmented `+` operator, but not `augmented.foo(3)` when calling an augmented `foo` method.

**Comment by lrhn** [comment]
Function call syntax can work for operators. It's even better than `augmented == x` because it doesn't look like it special cases `null`.

Question is then whether to do it for setters too, which has a function-like declaration syntax (a parameter list).

If yes, next question becomes getters, which do not have a parameter list.
Maybe follow the declaration and don't have an argument list then. 

Initializer expressions shouldn't have an argument list. 

Constructor bodies are weird, not sure we have a consistent story there.

**Comment by leafpetersen** [comment]
> > Question is then whether to do it for setters too, which has a function-like declaration syntax (a parameter list).
> 
> Yes, I think we should. At least, I can't think of a reason we shouldn't. What makes this fundamentally different from operators?

I'm not strongly set on this, but my intuition was also with Lasse's proposal (use `augmented = e` and `augmented` for setting and getting respectively).  There's not a solid justification for this.  If you think of defining a setter as defining an `operator=`, then yes, the consistent thing is to use `augmented(e)`, but that isn't how it's defined.  Instead we define a `set` operation, which defines code that is invoked when the name of the property is used with the `=` selector.  The general pattern we are using here is that `augmented` replaces the name of the member in question, so there's at least some logic to saying `augmented = e` then.   

> > Constructor bodies are weird, not sure we have a consistent story there.
> 
> I did try to clarify this recently, for regular constructor bodies you always just call `augmented()` and the current parameter scope is used. Not sure if that actually landed yet I need to find it 🤣

Did we consider turning all augmented constructors into factory constructors, which then must call the original generative constructor (or some generative constructor) if they wish to produce a new instance?  Maybe too restrictive, but it would potentially avoid some complexity?

**Comment by jakemac53** [comment]
I am definitely fine with `augmented = ` for setters, and it does make it easier to justify just `augmented` for getters too.  

> Did we consider turning all augmented constructors into factory constructors, which then must call the original generative constructor (or some generative constructor) if they wish to produce a new instance?

The problem is then you can't generate a regular constructor, so users have to write those. And they can't be used by subclasses etc either. I think it is just too restrictive.

**Comment by lrhn** [comment]
I'd be fine with `augmented(value)` for setters too, but I think using `=` is probably more directly understandable for users.

(I don't see a *big* difference between having special syntax `id = e` for invoking a setter and `id + e` for invoking an `operator+` method, other than setters usually being used and treated slightly differently. We could even use `augmented()` for getters too, even if the declaration has no `()`s, that still shows that it's an expression evaluated for its value, not ... well, something assignable. So nobody tries to do `augmented += 2`, which won't work anyway.)

My only tangential worry is that `operator[]=`, which we generally treat as setter-like, would use `augmented(a, b)`, not `augmented(a) = b`. But the latter looks horrible, so we wouldn't want that, and then we're getting to the point where we need to special case `augmented[e]` and `augmented[e1] = e2`, just to make `[]=` behave like a setter.
And again it's not like you can do `augmented[e] += e2` anyway, since you can only call one of them from any augmentation body. So probably best to just treat `[]=` as a method too.
