### ISSUE TITLE
what does break keyword do in the switch?

### ISSUE THREAD

**Issue by Silentdoer** [dart-lang/language#3419]
Why doesn't it output bbb with or without break keyword here, and what does break keyword do in the switch?
```dart
int a = 0;
  switch(a) {
    case 0:
    print("aaa");
    // Why doesn't it output bbb with or without break keyword here, and what does break keyword do in the switch?
    break;
    case int _:
    print("bbb");
  }
```

**Comment by lrhn** [comment]
The `break` breaks the switch. It does that wherever it's put in a case, including at the end.

Since Dart 3.0, you don't *need* a switch at then end of a case, it will just exit the switch normally if you reach there, with or without a break.
Before that, you would get an error if control flow could reach the end of a case. It has never fallen through to the next case in Dart.

It's not an error to put a break there, it does exactly what it says on the box: Breaks the switch at that point, *just* before reaching the end of the switch ... where it would also break automatically. It's just not necessary.

**Comment by mateusfccp** [comment]
So it could basically be removed from the language? Is it still here because of backward compatibility or what?

**Comment by munificent** [comment]
> So it could basically be removed from the language?

You need it if you have an empty case and you *don't* want fallthrough:

```dart
test(int i) {
  switch (i) {
    case 0:
      // No break, so fall through:
    case 1:
      print('zero or one');

    case 2:
      break; // No fallthrough.
    case 3:
      print('three');
  }
}

main() {
  test(0); // Prints "zero or one".
  test(1); // Prints "zero or one".
  test(2); // Prints nothing.
  test(3); // Prints "three".
}

> Is it still here because of backward compatibility or what?

Mostly, yes.
