### ISSUE TITLE
Adding interfaces during buildTypesForMethod() ?

### ISSUE THREAD

**Issue by scheglov** [dart-lang/language#3436]
We can do
```dart
macro class AddInterfaceA implements ClassTypesMacro {
  const AddInterfaceA();

  buildTypesForClass(clazz, builder) async {
    builder.appendInterfaces([
      NamedTypeAnnotationCode(
        name: await builder.resolveIdentifier(
          Uri.parse('package:test/a.dart'),
          'A',
        ),
      ),
    ]);
  }
}
```

And use it as
```dart
@AddInterfaceA()
class X {}
```

but we cannot do something like
```dart
macro class AddInterfaceB implements MethodTypesMacro {
  const AddInterfaceA();

  buildTypesForMethod(method, builder) async {
    builder.definingType.appendInterfaces([
      NamedTypeAnnotationCode(
        name: await builder.resolveIdentifier(
          Uri.parse('package:test/a.dart'),
          'B',
        ),
      ),
    ]);
  }
}
```
and use it as
```dart
@AddInterfaceA()
class X {
  @AddInterfaceB()
  void foo() {}
}
```
Note that I used not existing `builder.definingType`.

Do I miss an existing way to do this?
Or is it a known limitation?

@jakemac53

**Comment by jakemac53** [comment]
Yes, this is intentional. A macro can't modify anything in a higher "scope" than the thing it is applied to. They also can't alter sibling declarations. So a library macro can alter anything, a macro on a type can alter the type directly as well as the members, and a member macro can only alter that member.

Note that they can add new things in some cases but not alter existing ones.

I don't know that this is a hard requirement, but it is how the current API design is set up.

**Comment by scheglov** [comment]
OK, thank you.

I wanted to test that during the types phase applications to a methods are applied before applications to the enclosing class. But reading [the rule](https://github.com/dart-lang/language/blob/main/working/macros/feature-specification.md#rule-2-augmentations-are-sorted-by-phase-application-then-source-order) it seems that I can just rely on the order of generated code and emit two separate classes instead.

**Comment by jakemac53** [comment]
Yes, just emitting separate classes should work for that 👍

**Comment by scheglov** [comment]
Thanks!
