### ISSUE TITLE
Covariance / Contravariance Expected Ability Unavailable

### ISSUE THREAD

**Issue by tcf909** [dart-lang/language#3445]
The following should be valid tightening / extensibility scenarios for covariance / contravariance situations. Why is it not?

```
abstract class A {
  named({required int a});

  namedWithExtra({required int a, int? b});

  positional(int a, [covariant int? b]);
}

abstract class B extends A {

  @override
  named({required int a, required int b}); // Analyzer Error
  
  @override
  namedWithExtra({required int a, required covariant int b}); // Analyzer Error

  @override
  positional(int a, covariant int b); // Analyzer Error
}

**Comment by lrhn** [comment]
They should not.

Subtyping requires substitutability.

For example `B.named` has two required parameters. That means than a `B` instance cannot be used where an `A` instance is expected, because that code will only call `named` with one argument.

Subclasses can add more parameters, but they must be optional, so that when upcasting to the supertype, all member invocations at the supertype's interface are also valid invocations of the subtype implementation.
