### ISSUE TITLE
Spread for classes

### ISSUE THREAD

**Issue by Reprevise** [dart-lang/language#3448]
I have this nice little const [TextStyle](https://api.flutter.dev/flutter/painting/TextStyle-class.html) variable here:

```dart
const TextStyle kHeaderStyle = TextStyle(
  fontSize: 24,
  fontWeight: FontWeight.bold,
  color: Colors.white,
);
```

Now, I want to make a very similar `TextStyle` variable but I want the color to be a nice yellow, there's a couple ways of doing this.

```dart
// Manually copying the above parameters, but at least it's const.
const TextStyle kHeaderStyle = TextStyle(
  fontSize: 24,
  fontWeight: FontWeight.bold,
  color: Colors.yellow,
);

// Less copying, but also not const :(
final TextStyle goldHeaderStyle = kHeaderStyle.copyWith(
  color: Colors.yellow,
);
```

I'm proposing a spread operator for classes. Notice how this can be const?

```dart
const kGoldHeaderStyle = TextStyle(
  ...kHeaderStyle,
  color: Colors.yellow,
);

// It results in the exact same code as this:
const kGoldHeaderStyle = TextStyle(
  fontSize: 24,
  fontWeight: FontWeight.bold,
  color: Colors.yellow,
);
```

At runtime it can get a bit complicated, Dart would have to keep track of the exact value that was passed in for each parameter.
```dart
double fontSize = 24;
final headerStyle = TextStyle(
  fontSize: fontSize,
  fontWeight: FontWeight.bold,
  color: Colors.white,
);
fontSize *= 2;
final goldHeaderStyle = TextStyle(
  ...headerStyle,
  color: Colors.yellow,
);
print(goldHeaderStyle.fontSize); // 24
```

Dart would not call any getters for this, as getters would be able to transform the value that was passed into the constructor. What I am proposing here is basically a `const`-able copyWith method (and it'll respect `null` being passed in 😉).

### Challenges

Dart is going to have to keep track of the constructor. Let's use a slightly modified `dart:ui` Color class as an example:

```dart
const myGreatColor = Color(value: 0xFFFFFFFF);
// Let's imagine fromRGBO has only named parameters (red, green, blue, opacity).
const myTransparentGreatColor = Color.fromRGBO(...myGreatColor, opacity: 0); // Wouldn't work, has to be the same constructor.

const myGreatColor = Color.fromRGBO(red: 255, green: 255, blue: 255, opacity: 1);
const myTransparentGreatColor = Color.fromRGBO(...myGreatColor, opacity: 0); // Works.
```

All in all, perhaps this would be better solved with methods that could return `const`, like `Color#withOpacity` or a const `copyWith` method, though that would require some slight migration.

**Comment by jakemac53** [comment]
I have wonder if expression level macros could solve this problem (and the record spread problem)? It wouldn't be quite as intuitive syntactically but that might also remove some ambiguity, maybe something like:

```dart
const kGoldHeaderStyle = @spreadInto(kHeaderStyle, TextStyle(color: Colors.yellow));
```

It is particularly interesting imo because this somewhat solves the age old question of knowing whether a null was explicit or implicit. The macro could see the function invocation in its original form, and know that `color` is already being provided, so it would only spread in the additional parameters.

**Comment by TekExplorer** [comment]
This seems like a bad idea, dart shouldnt need to keep track of what was passed in, as objects that normally get GC'd suddenly stay alive for the entire life of the class unecessarily

instead, why dont we split this into two parts
1. object spread operator, which could return a `Iterable|Map|Record`
```dart
({String foo, int bar}) operator ...() => (foo: foo, bar: bar);
List<dynamic> operator ...[] => [foo, bar];
Map<String, dynamic> operator ...() => {'foo': foo, 'bar': bar};
```
3. Record-parameter spreading => `fn(...record)`

combined, this would allow you to implicitly foward the spread like `fn(...object)` which aquires then spreads the record

**Comment by lrhn** [comment]
I'll give a strong "no" to remembering which arguments were passed to which parameters in the creation of a constant object, or any object.

The API for destructuring an object is _getters_. The same object can be created in several ways using different constructors, for canonicalized constants that can _literally_ be the same object.
Some arguments to a constructor may not be part of the object at all, some may not be publicly visible, some may not be constantly accessible (you can create records on potentially constant expressions, you can't destructive them again).
All in all, the parameters to a constructor is not what defines an object after it has been created.

I'd rather imagine a syntax that allows more concisely accessing multiple getters, or accessor functions, without repeating the receiver, like cascades do for invoking members for effect.

Consider a record expression like:
```dart
receiver.(.foo, :.bar, sup: .baz)
```
Which would be equivalent to
```dart
(let tmp = receiver in 
    (tmp.foo, bar: tmp.bar, sup: tmp.baz))
```
which you can then spread into an argument list.

The syntax can be used as:
```
expr.(single expression)
expr.(record fields)
expr.[list elements]
expr.{set or map elements}
```
And inside the delimited area, an unqualified `.foo` member access is implicitly on the implicit receiver.

(Not a big win over inline variable declarations, like
```dart
((var r = receiver).foo, bar: r.bar, sup: r.baz)
```
or similar `let` expressions, but a small win might still be a win.)

**Comment by AlexanderFarkas** [comment]
@jakemac53 I like the macros idea. IMO, it would be nice to have some `extension` macro:
```dart
kHeaderStyle.@copyWith(
  color: Colors.yellow
);
```

So, `copyWith` by definition takes default constructor and maps public `getters` from `kHeaderStyle` to this constructor.

**Comment by munificent** [comment]
I agree it would be nice to have a better mechanism to create a new immutable object from some existing one with a couple of fields tweaked, but I think this is a non-starter:

> At runtime it can get a bit complicated, Dart would have to keep track of the exact value that was passed in for each parameter.

This would mean that for every instance of every class, we would store additional hidden fields for every single parameter passed to every constructor the class defines. That's a *lot* of memory being mostly wasted. Also, I don't think what you proposed is sound. Consider:

```dart
class Foo {
  final String _s;

  Foo.fromInt({required int param}) : _s = n.toString();
  Foo.fromString({required String param}) : _s = param;
}

main() {
  var foo = Foo.fromInt(123);
  var foo2 = Foo.fromString(...foo);
}
```

I do like the idea of some sort of "class spread" like you propose, but I'm going to close this issue because there are other issues open around object update and object spreading that I think cover it and this specific approach I believe won't work.

**Comment by cedvdb** [comment]
An use case not covered by `asList` is to sugar spread into a constructor:

```dart
class A {
   final One one;
   final Two two;
   final Three three;
   final Four four;
}

class B {
   B(this._a);

   final A _a;
   late final C c = C(...a);
   late final D d = D(...a);
   // ... e, f, g ...
   late final Z z = Z(...a);
}

class C {
   C({required One one});
}

class D {
   D({ required Two two, required Four four});
}

// maybe handle positional params too ?
class Z {
   Z(One one, {  Two? two });
}
```

Or copy with with `null`:

```dart
class Copiable {
   final int i = 3;
   final int? y = 2;
   Copiable({ this.i, this.y });
}

void main() {
  final a = Copiable();
  final  b = Copiable(...a, y: null);
}
```

**Comment by TekExplorer** [comment]
It may be more useful to have Record spreading instead, and some kind of special `RecordSpreadable<T extends Record>` Interface to let you do it durectly

Then, record spreading into functions gives you this "for free"

**Comment by cedvdb** [comment]
> It may be more useful to have Record spreading instead, and some kind of special `RecordSpreadable<T extends Record>` Interface to let you do it durectly
> 
> Then, record spreading into functions gives you this "for free"

 On what metric would that be more useful ? 

  - You'd have to implement it
  - it requires memory
  - it does not solve the use case I mentioned above.

**Comment by TekExplorer** [comment]
> > It may be more useful to have Record spreading instead, and some kind of special `RecordSpreadable<T extends Record>` Interface to let you do it durectly
> > 
> > Then, record spreading into functions gives you this "for free"
> 
>  On what metric would that be more useful ? 
> 
>   - You'd have to implement it vs "..."
>   - it requires memory vs no cost (just syntactic sugar)
>   - it does not solve the use case I mentioned above.
> 

Because you can't just assume that all getters on an object can be accepted, so simply spreading blindly can be dangerous.

If you define your own record getter, you specify exactly what matters, (easy to macro) and *that* can spread into arguments, since records and function parameters are very similar.

**Comment by cedvdb** [comment]
> Because you can't just assume that all getters on an object can be accepted, so simply spreading blindly can be dangerous.

```dart
final C c = C(...a);
```

Is just sugar for:

```dart
final C c = C(one: a.one, two: a.two);
```

**Comment by TekExplorer** [comment]
Hm. I suppose. The problem I see is that it may invite low quality code, especially since if you aren't using a parameter, but the class which may not be under your control, or perhaps you accidentally name-collide, what happens? Does the spread fail with a type error? Or worse, if the types line up, you could have a near impossible to debug bug.

I would much rather spread a record, since it's much more reliable - adding a better to a class isn't breaking (unless it's meant to be implemented i guess) but changing a records shape is as breaking as it comes.

**Comment by cedvdb** [comment]
This proposal isn't about record spreading.

----------

The collision argument is interesting. Having an error when the spread is used for eg `C(...a, ...b)` spreading the same fields seems like the most sensible solution to me. However, other languages have similar features and the last declaration wins, which may make more sense.

**Comment by TekExplorer** [comment]
Perhaps, but again, it's a dangerous syntax, since we're getting implicit getter calls we may not be able to see and can escape code review really easily and entirely implicitly.

That's why I suggest focusing on record spreading instead. It adds a step, but it's worth it for safety, and you can't accedentally pass parameters unintentionally.
