### ISSUE TITLE
Question: should I return null or use exceptions?

### ISSUE THREAD

**Issue by stephane-archer** [dart-lang/language#3465]
Hi, I'm a Go programmer and am not used to exceptions.
I would like to know when should I decide if my function should return null or if I should use exceptions.
Returning null is safe in Dart and can be used to indicate an error
On the other hand, exceptions mean you need to catch it somewhere. So today I feel every OnPress function needs a try statement around the body of the function. I'm not sure I'm doing it right.

**Comment by lrhn** [comment]
Dart has two kinds of throws: Exceptions and errors.

Errors are reserved for when something is wrong, in a way that just shouldn't happen.
Typically it represents a programming error, which the author should have avoided. A bug in the program.
You shouldn't try to catch errors, because there shouldn't be any. If there is, they'll crash your program, which is working as intended. That's how you recognize that there is a bug.

Exceptions are for situations where a function cannot do what it's intended to do, but due to circumstances outside of the author's control. It's not for something you can check for first, but it's also not the *intended* behavior. It's a failure.
Typical examples are network or other I/O failures. You just checked that a file existed, now you try to read it, but someone removed it in-between. That's not intended, probably not even likely, but it *can* happen.
The exception can contain further information that can be used to recover, or just log.
You can catch an exception immediately, or higher up in your own code stack, where it makes most sense.
A function which throws an exception (at an API boundary, at least) should always be documented with precisely which exceptions it may throw. It should not be a surprise to the caller.


If not producing a value is *intended* and predictable behavior in some cases, like looking up a key in a map which doesn't have that key, returning `null` is a way to *not* have to throw. There is no need to throw an exception to say what's wrong, because it's completely deterministic what is "wrong", and getting a `null` is a way of returning that information. 
It's not an error, it's specified and designed behavior for a predictable situation where there just was no valid value to return.

Your `OnPress` functions probably shouldn't be catching anything, unless the functions they call are *documented* as throwing specific exceptions. You shouldn't catch errors. You should never catch plain `Exception`, because you should know which exceptions are thrown (and they should never be plain `Exception` instances), they should be tailored to the exceptional occurrence they're reporting, so the code catching them can *properly* handle the event.

**Comment by stephane-archer** [comment]
Thank you @lrhn for this great answer!
