### ISSUE TITLE
Support implicit property extraction (aka tear-off) of `call` for extension types?

### ISSUE THREAD

**Issue by eernstg** [dart-lang/language#3467]
Thanks to @nshahan for coming up with this issue. Consider the following example:

```dart
extension type Ext(Function _) {
  void call() => print('call from Ext');
}

class C {
  void call() => print('call from C');
}

class D {
  Function get fgetter => Ext(C()); // Implicitly transformed into `Ext(C()).call`?
}

void main() {
  var d = D();
  d.fgetter();
}
```

We have specified that implicit property extraction of a method named `call` occurs on an expression whose static type is an interface type that declares a method named `call`, in the case where the context type is `Function` or a function type.

For example, `Ext(C())` above would be implicitly transformed into `Ext(C()).call` if `Ext` had been a class.

Note that we allow `extension` methods to be implicitly torn off in this manner as well.

The question is then: Should we treat receivers whose type is an extension type the same, and allow `Ext(C())` to be implicitly transformed into `Ext(C()).call`?

We may wish to lessen the role played by this kind of implicit property extraction and possibly get rid of it entirely at some point in the future. However, at this time it seems more consistent to me to allow it for extension types, just like it's allowed for all the other types that equip a receiver with a set of statically known members.

If it turns out to be a significant effort then it could make sense to make it an error now, and support it later.

Note that the analyzer supports it, but the CFE doesn't, at least as far as I can see from a few experiments.

@dart-lang/language-team, WDYT?

**Comment by munificent** [comment]
I don't have a strong opinion, but I lean towards "no". It has almost zero practical user value. We almost removed `call` tear-offs entirely in Dart 3.0 but didn't quite manage to pull it off. But I do still hope that eventually we can, since it's not a feature that carries its weight. Given that, I'd rather not increase the surface area of the feature.

**Comment by nshahan** [comment]
And does the spec already cover this case?

```dart
extension type Ext(C _) implements C {}

class C {
  void call() => print('call from C');
}

main() {
    Function f = Ext(C());
}
```

This appears to have the same inconsistency currently between the analyzer (no error) and the CFE has a compile time error:
```
Error: A value of type 'Ext' can't be assigned to a variable of type 'Function'.
 - 'Function' is from 'dart:core'.
  Function e = Ext(C());
               ^
```

**Comment by natebosch** [comment]
I agree that we should not add implicit call tearoffs in this situation for the sake of consistency. It would be good if we had a more specific error for this, but I do not think we should have authors start writing implicit tearoffs from extension types only to (hopefully) remove them later.

**Comment by eernstg** [comment]
@nshahan wrote:
> And does the spec already cover this case?

No, there is no rule about being able to perform an implicit `call` tear-off based on having a type that has a supertype that satisfies the requirements for implicit `call` tear-offs, the rule only talks about the type of the given expression.

(Of course, we haven't had any types before where a supertype supports this mechanism and a subtype doesn't, so there was no need to include an extra clause like "if this doesn't work with the given type then try all supertypes".)

**Comment by lrhn** [comment]
I think we should support `call` tear-off from extension types.

The reasoning being that the behavior is well-defined and consistent.
If we want to make it work any other way, we'll have to specify that, in sufficient detail to clearly separate the exceptions from the non-exceptions. That's not unlikely to be more work, and more risk of errors, than just doing the same thing as for every other type.

The current behavior is: If `e` has static type *S* in context *C*, *S* is not assignable to *C*, _the type signature of *S* has a method named `call`, or *S* has an applicable extension method named `call`_  and *C* is a non-bottom subtype of `Function`, then treat `e` as `e.call` with a static type which is the function type of `S.call`.

If we try to make an exception for extension types, we need to defined where that exception ends.

We can say:
* the type signature of *S* has a method named `call` **which is not an extension type method**, or *S* has an applicable extension method named `call`

That would rule out tearing off extension type methods named `call`, but would allow an extension type implementing a callable non-extension type to have its non-extension-type `call` method torn off.

* the type signature of *S* has a method named `call` and *S* is not an extension type, or *S* has an applicable extension method named `call`.

That rules out inherited non-extension-type `call` methods too, but still allow extension `call` methods. We can try to remove those as well:

* *S* is not an extension type, and either the type signature of *S* has a method named `call` or *S* has an applicable extension method named `call`.

That rules out extension `call` methods on extension types. But not on `Ext?` or `FutureOr<Ext>`, which are not extension types, and which the extension type *is* a subtype of.
In fact, it would mean that:
```dart
extension type Ext(Object _) {}
extension ECall on Ext? {
  int call(int x) => x;
}
void main() {
  Function f = (Ext(0) as Ext?); // Works
  Function f = Ext(0); // Does not work, even though _the same_ extension `call` method applies.
}
```

One of the earlier two definitions would be more consistent.

(The definition is honestly not as complicated as I had feared.)

I don't think we're saving ourselves much implementation-wise (correct me if I'm wrong), because we'll just have to recognize the same cases in order to *omit* them, and then we have to do something else. And maybe even add proper error messages.

I don't think having omitted extension types will help us if we try to remove implict `call` tear-off from the language.
Probably won't hurt either. There'll just be slightly fewer places where we have to automatically insert a `.call`, but it shouldn't be more or less complicated to do it. (I think.)

**Comment by scheglov** [comment]
Not a big deal in the analyzer.

**Comment by osa1** [comment]
This shouldn't be a problem for dart2wasm as the only place we implicitly use `call` is in dynamic invocations when the object being called is not a function. Other than dynamic invocations we rely on kernel to have the `call`s in the right places.

**Comment by johnniwinther** [comment]
Currently the CFE doesn't handle any implicit tear-off, neither of extension type member `call` nor class member `call` on implemented type, so some work is needed. It doesn't matter which.

**Comment by leafpetersen** [comment]
It's hard for me to follow exactly what is being argued above because the text isn't always consistently talking about **implicit** call tear offs, which I think is all that is being discussed here.  But just to be sure, let me write up some specific examples of the different uses (explicit and implicit) of call methods.

```dart
class C {
  void call() => print('call from C');
}
extension type Ext1(C _) implements C {}

extension type Ext2(int _) {
  void call() => print('call from Ext2');
}

main() {
    Ext1 e1 = Ext1(C());
    Ext2 e2 = Ext2(0);
    e1(); // 1
    e2(); // 2
    e1.call(); // 3
    e2.call(); // 4
    (e1.call)(); // 5
    (e2.call)(); // 6
    Function f1 = e1; // 7
    Function f2 = e2; // 8
}
```

Currently lines 1 to 6 are accepted by both analyzer and CFE, and run correctly in dartpad.  **This is the behavior I would expect**.

Currently lines 7 and 8 are both rejected by the CFE, and both accepted by the analyzer.
  - **I strongly feel that we should either accept both or reject both**
  - I don't care too much about whether we accept or reject them, but in general it feels inconsistent to reject them, given that we accept them for regular interface types.  On the other hand, if this involves extra work, I could see the argument for just rejecting both, and considering the existing support for implicit call method tearoffs to be legacy.  The inconsistency is a kind of tech debt though.

**Comment by nshahan** [comment]
I expect there will be little to no implementation required by DDC to support the implicit tearoffs as they will probably be desugared by the CFE.

There will be some small updated needed in DDC to fully support call methods on extension types that are inherited from their implements clause. The changes will be minimal, we just need to know what to support.

For example field and getter accesses that return a value of a type that is callable need to be transformed into `.call()` in the backend and that is failing in DDC right now.

**Comment by lrhn** [comment]
I would add to Leaf's example:
```dart
    Function f3 = e1.call; // 9
    Function f4 = e2.call; // 10
```
which should also work everywhere (like any other extension method tear-off).

In the example, only 1+2 and 7+8 are in any way special, the remaining cases treat `call` like any other method, and should work just the same with any other method name.

The 1+2 cases is implicit `call` invocation, where a non function typed expression being invoked like a function is implicitly invoking the `call` method of the static type, if there is one (which can be an instance, extension type or applicable extension member).

There has been no discussion about making that not work for extension types.

The 7+8 cases is implicit `call` tear-off, where a non-function-typed expression with a context type which requires a function (context type is bounded by a function type or the type `Function`), is implicitly treated like a tear-off of that noon-function-type's `call` method, if it has one. (Extension methods named `call` do not apply here, they were explicitly excluded when we introduced the "extension methods" feature).
 
(These two together can be thought of as "implicit `.call`-insertion", but they're different enough that it's safer to consider them as separate features.)

There is discussion about whether that case should be specified as working or not working when the non-function-type is an extension type.
That discussion exists because we have considered, and still are, whether we should remove the implicit `call` tear-off feature from the language entirely, and there is precedence in how we have already opted extension `call` methods out of the feature.
If we weren't considering removing the feature, we'd likely just have said that 7+8 should work the same way as for class types, and not even have considered not doing so as an alternative.

Making it not work now is only to discourage people from using it, in case it will stop working later anyway.
But allowing it probably won't make discontinuing the feature much harder, since we'll have to do the same necessary migration for class types anyway.

Which is why we are asking what is easier for implementors, because that is more important, overall, than the other considerations. It's a choice where the design can go either way, without much lasting impact.


> For example field and getter accesses that return a value of a type that is callable need to be transformed into `.call()` in the backend and that is failing in DDC right now.

Not sure I understand that example. Nothing here requires inserting `.call()`, it's only ever inserting `.call` (whether to be called or to be torn of). Unless that's JavaScript code, in which case that's why I don't understand it 🤔

**Comment by eernstg** [comment]
@leafpetersen wrote:
> the text isn't always consistently talking about **implicit** call tear offs

It is all about implicit call tear-offs, at least everything I wrote here.

I agree with everything @lrhn said, and with @leafpetersen about

> I strongly feel that we should either accept both or reject both

This reference to 'both' was about having a receiver whose static type is an extension type and then

- case 7: implicitly tearing off a non-extension method named `call`, and
- case 8: implicitly tearing off an extension member named `call`.

I think we might want to **allow these implicit tear-offs after all** (and then possibly get rid of the entire feature, for all kinds of receivers, simultaneously at some point in the future).

The main reason for this is that it seems inconsistent and surprising if we don't allow case 7. For example:

```dart
class C {
  // This makes `C` callable.
  void call() {}
  // This declaration stands for "a bunch of useful members".
  void normal() {}
}

extension type FancyC(C it) implements C {
  // This declaration stands for "a bunch of nice extras".
  void extra() {}
}

void main() {
  C c = C();
  FancyC fancyC = FancyC(c);

  // In general, we can use `FancyC` where we would otherwise use `C`,
  // which will just add some nice extras.
  c.normal();
  c.extra(); // Error, no such member.
  fancyC.normal();
  fancyC.extra();

  // However, `fancyC` isn't callable, and we can't fix that.
  Function f = c; // OK.
  Function notSoFancyF = fancyC; // Error.
}
```

So the point is that we can't use `FancyC` as a fancy version of `C`, it's going to be a _slightly broken_ fancy version of `C`.

**Comment by nshahan** [comment]
Did we reach a conclusion here about what will be supported or specifically not supported?

>Not sure I understand that example. Nothing here requires inserting .call(), it's only ever inserting .call (whether to be called or to be torn of).

Sorry about that, my wording wasn't very clear. The more I looked into how DDC handles all the examples Leaf listed I started noticing cases where we may be producing incorrect code when using some extension types (depending on what we need to support ). There are already exceptions in place to work with existing JavaScript interop code where we need to decide if we should insert a `.call` or not and those might need to be updated.

**Comment by leafpetersen** [comment]
We discussed this in the language meeting today, we will support this.  @eernstg do we have tests for this or do we need to add/modify something?

**Comment by eernstg** [comment]
Coming: https://github.com/dart-lang/co19/issues/2428.

**Comment by eernstg** [comment]
I think I can close this issue because subsequent steps are organized via the implementation issue https://github.com/dart-lang/sdk/issues/54339 and the specification issue in https://github.com/dart-lang/language/issues/3512.
