### ISSUE TITLE
Require that the type in an `on` clause of a mixin must be regular bounded

### ISSUE THREAD

**Issue by eernstg** [dart-lang/language#3491]
```dart
class A<X extends num> {}
mixin M on A<Object?> /*a super-bounded type*/ {}
```

It is currently not an error for the type in a mixin `on` clause to be super bounded (as opposed to types in `extends`, `with`, or `implements` clauses: they must all be regular bounded).

However, we should probably just add the mixin `on` clause in this list of places where the type must be regular bounded. Note that it is never useful anyway. Let's try to use the above mixin `M`:

```dart
class B extends A<S> with M {}
```

`S` would have to be `Object?` in order to avoid having the error which is caused by having multiple different instantiations of the same generic class as superinterfaces ("you can't implement `List<int>` and `List<num>` at the same time!"). At the same time, `S` cannot be `Object?`, because it is an error to use a super bounded type in an `extends` clause.

I believe it is impossible to use a mixin whose `on` clause has a super bounded type. With this in mind, I'd recommend that we make it a compile-time error.

**Comment by lrhn** [comment]
Agree. The mixin introduces an interface, that interface has the `on` type as superinterface. If you're not allowed to have a superbounded type on an `implements` clause, you shouldn't be allowed to have it on an `on` clause.

(I would have expected it to be an error with the current specification, because of the definition of combined superinterface, but maybe we dodge that by having only one `on` type.)

**Comment by eernstg** [comment]
As of Dec 29 2023, this has been implemented.

**Comment by eernstg** [comment]
The specification has this rule as well: https://github.com/dart-lang/language/blob/0ecd65a8988520dd5bec097056d1657f7b4b6d54/specification/dartLangSpec.tex#L21371.
