### ISSUE TITLE
Optional or no parentheses in control flow statement, eg: if true { }

### ISSUE THREAD

**Issue by threeid** [dart-lang/language#350]
Hi dartlang team,
Is there any chance in the future, we can code like this in dart:

```
if true {
  print("It's awesome")
}
```

just like in Python, Go, Swift.

**Comment by munificent** [comment]
I think this is very unlikely. I like the syntax in those languages, but this is a corner of Dart's syntax that is very entrenched at this point. Removing those parentheses could possibly cause ambiguity with other parts of the grammar. There's some stuff that after 1.0 you're pretty much stuck with, for better or worse.

In practice, I somewhat prefer Dart's syntax because it makes single-line if statements look cleaner:

```dart
if (min > max) throw "Bad range";
```

Also, the familiarity to users coming from C++, Java, C#, and JavaScript is a significant value.

**Comment by NatoBoram** [comment]
While it's surprising at first to see `if err != nil { return; }` for the first time, I'm pretty confident it would not impede C++, Java, C#, and JavaScript users in a meaningful way, particularly if parenthesis are *optional* but *allowed*.

One way to remove ambiguity would be to require either `()` or `{}`.

```dart
if err != null { return; }
```

```dart
if (err != null) return;
```
