### ISSUE TITLE
Exhaustiveness and abstract classes

### ISSUE THREAD

**Issue by scheglov** [dart-lang/language#3511]
Why the code below requires branches for `NamedType`  and `TypeImpl`? These are abstract final classes, we cannot instantiate them, and there can be no other not abstract implementations of `Type` than `NamedTypeImpl`.

```dart
sealed class Type {
  void foo();
}

abstract final class NamedType implements Type {}

abstract final class TypeImpl implements Type {}

final class NamedTypeImpl extends TypeImpl implements NamedType {
  @override
  void foo() {}
}

void f(Type type) {
  switch (type) {
    case NamedTypeImpl():
      break;
    case NamedType():
      // TODO: Handle this case.
    case TypeImpl():
      // TODO: Handle this case.
  }
}
```

**Comment by srawlins** [comment]
This looks a lot like my https://github.com/dart-lang/language/issues/3135, but I did not have the abstract subtypes (here, `NamedType`, and `TypeImpl`) as `final`.

**Comment by lrhn** [comment]
That's because those types are not sealed. 

Exhaustiveness is not about which instances a type has in the current program.
It's about which instances it's *able* to have without a breaking change to the program.

Any change which can change exhaustiveness compuations is a breaking change.
We don't want adding another concrete subclass of `NamedType` or making `TypeImpl` non-`abstract` to be breaking changes, therefore exhaustiveness computation must act as if those things have already happened. The worst-case of changes that affect which instances can exist, is what we have to assume.

Changing which subtypes a `sealed` type has is *defined* as breaking, so therefore exhautsiveness can assume that there are no other subtypes than the ones it can see right now.

No `sealed`, no exhaustiveness by subtype elimination.

**Comment by munificent** [comment]
Good question! I had to think about this one for a while. Here's a slightly different version of the program:

```dart
// other_package.dart:
sealed class Type {
  void foo();
}

abstract final class NamedType implements Type {}

abstract final class TypeImpl implements Type {}

final class NamedTypeImpl extends TypeImpl implements NamedType {
  @override
  void foo() {}
}

// my_library.dart:
void f(Type type) {
  switch (type) {
    case NamedTypeImpl():
      break;
    case NamedType():
      // TODO: Handle this case.
    case TypeImpl():
      // TODO: Handle this case.
  }
}
```

The only change here is that I've moved to the switch into a separate library. Let's assume that these two files are maintained by different people.

The owner of `other_package.dart` declared `NamedType` to be `final`. But they didn't declare it `sealed`. That means that the owner of `other_package.dart` is free to add new subclasses of `NamedType` to their library without it being a compile-time breaking to users of the library. By marking the class `final` and *not* `sealed`, the author of `other_package.dart` is reserving for themselves the freedom to add new subclasses in the future.

By taking that freedom, anyone *using* `other_package.dart` is now required to have a case in their switches to match `NamedTyped` and not just `NamedTypeImpl`. By choosing to *not* use `sealed`, the author is saying "Hey, a new subtype of `NamedType` could appear at any time! You have to be ready to handle that (by matching all values of type `NamedType` itself)."

If you don't *want* that freedom, you can eliminate the need for those otherwise-pointless cases by doing:

```dart
sealed class Type {
  void foo();
}

sealed class NamedType implements Type {}
//^^^^

sealed class TypeImpl implements Type {}
//^^^^

final class NamedTypeImpl extends TypeImpl implements NamedType {
  @override
  void foo() {}
}

void f(Type type) {
  switch (type) {
    case NamedTypeImpl():
      break;
    // No errors!
  }
}
```

It looks a little strange to have a `sealed` class with only a single subtype, but it works just fine and the exhaustiveness checker understands it.
