### ISSUE TITLE
Assign value to a first-class member function in the constructor

### ISSUE THREAD

**Issue by SharbelOkzan** [dart-lang/language#3514]
_Example in [Dartpad](https://dartpad.dev/?fa2a41390716d21c1170cb76340b2de6)_

Why does the following code raise an error
```
class Bar {
  final int Function() foo;

  Bar() : foo = () => 1;
}
```
While this works fine
```
class Bar {
  final int Function() foo = () => 1;

  Bar();
}
```

For the first code, the analyzer is raising all the following:

- The initializer type '()' can't be assigned to the field type 'int Function()'.dart[field_initializer_not_assignable](https://dart.dev/diagnostics/field_initializer_not_assignable)
- Constructors can't return values.
Try removing the return statement or using a factory constructor.dart[return_in_generative_constructor](https://dart.dev/diagnostics/return_in_generative_constructor)
- A value of type 'int' can't be returned from the constructor 'Bar' because it has a return type of 'Bar'.dart[return_of_invalid_type](https://dart.dev/diagnostics/return_of_invalid_type)

**Comment by SharbelOkzan** [comment]
In case someone is wondering about the usecase, here's an example 

```
import 'package:flutter/material.dart';

class MyWidget extends StatelessWidget {

  MyWidget.greeting({super.key}) :
   label = (context) => AppLocalizations.hello,
   color = (context) => Theme.of(context).primaryColor;
  
  MyWidget.error({super.key}) :
   label = (context) => AppLocalizations.errorMsg,
   color = (context) => Theme.of(context).colorScheme.error;
  
  final Color Function(BuildContext) color;
  final String Function(BuildContext) label;

  @override
  Widget build(BuildContext context) {
    return Container(
      color: color(context),
      child: Text(label(context)));
  }
}
```

**Comment by rrousselGit** [comment]
Function initializers need to be encapsulated in parenthesis:

```dart
class Class {
  Class():
    field: (() => 42);
}
```

**Comment by SharbelOkzan** [comment]
Thanks @rrousselGit !. Closing

**Comment by munificent** [comment]
And the "why" answer is because of function expressions like:

```dart
class Bar {
  final int Function() foo;

  Bar() : foo = (x) {
    some;
    very;
    large;
    body;
    of;
    code;
  }
}
```

In this example, when the parser sees `(x)`, it could either be:

1. Initializing `foo` with a parenthesized expression containing the value of `x`, followed by the body of the constructor.

2. Initializing `foo` with a function expression that takes parameter `(x)` and has a large block body.

The parser won't know which of those is the case until much later when it reaches the end of the constructor body and can see if there's a `;` or `{}` after the `}`.

It's hard for a *person* to read this code correctly too. So, to avoid that confusion, we require function expressions in constructor initializers to be parenthesized. It technically wouldn't be necessary to require `=>`-bodied functions to be parenthesized since we don't allow constructors to use `=>` for their body, but we require both just for consistency.
