### ISSUE TITLE
Do extension types follow their representation type in being always-exhaustive?

### ISSUE THREAD

**Issue by eernstg** [dart-lang/language#3524]
[Edit: The language team [decided](https://github.com/dart-lang/language/issues/3524#issuecomment-1875649080) that the answer is yes.]

The pattern feature specification defines the notion of an [always-exhaustive](https://github.com/dart-lang/language/blob/main/accepted/3.0/patterns/feature-specification.md#exhaustiveness-and-reachability) type and specifies that a switch statement must be checked for exhaustiveness when the static type of the scrutinee is always-exhaustive.

Exhaustiveness properties of patterns involving extension types is achieved by taking the extension type erasure of all the relevant types, as specified [here](https://github.com/dart-lang/language/blob/main/accepted/future-releases/extension-types/feature-specification.md#:~:text=V%3E.empty()\).-,An%20extension%20type%20V,-(which%20may%20include).

The intention behind that paragraph in the extension type feature specification was that extension type erasure should apply to all aspects of exhaustiveness, but it has not been spelled out that the matched value type should be extension type erased as well.

If we do that then it follows that a switch statement must be checked for exhaustiveness when the static type of the scrutinee is an extension type whose erasure is always-exhaustive.

The conceptual justification would be that extension types should only be used in association with pattern matching in the case where it is OK to adopt the extension type (that is, casting from the representation type or a subtype to the extension type). We can have other devices (say, lints) to check that this is OK in the first place. Assuming that it is OK, it seems reasonable to me to say that the property of being always-exhaustive should also be allowed to propagate from the representation type to the extension type.

@dart-lang/language-team, WDYT?

**Comment by lrhn** [comment]
I'll say "no" as default, "yes" if the extension type implements a sealed class type.

And that's still work caveats.

If the extension type implements an `enum` type (or `bool`), it'l be tested as that.

If it implements a sealed type, then it matters how.
If it writes `implements SealedType` and the representation type is `SealedType`, then yes.

If the representation type is not `SealedType`, then no. Having a subclass of a sealed class as representation type, and implementing the sealed type, is a way to create a wrapped _alternative_ to a sealed type direct subclass. It doesn't represent the entire sealed type hierarchy.

If it's not _all_ of the sealed type, because of generics, then _probably_ still yes.
Say there is an `Option<T>`/`Value<T>`/`None` sealed class hierarchy. If an extension type only applies to `Option<int>`... then that's still a sealed sub-hierarchy. Maybe.

If it doesn't implement the `SealedType` interface, then no, it's not telling you that it's exhaustive. Don't assume what the representation type is.

If it implements the desired type, but doesn't do it directly, say it implements another extension type which does, then it should probably count.

So the representation type _is_ the stairs class, or an instantiation of it, and the extension type implements that sealed class' interface, then inheriting "must be exhaustive" is ok. Otherwise I wouldn't.

(But this is really just another example showing that "must be exhaustive" types is a hack, a heuristic trying to guess what the user might want absent of any signs of intent, and what we should really have is switches that must always be exhaustive. Possibly with an easy opt-out to get a switch which is not assumed to be exhaustive, and doesn't have to be. Then the author chooses the exhaustiveness of every switch, and all we have to do is validate.)

**Comment by eernstg** [comment]
> in short: "always exhaustive" is bad because it's type based, but types don't always imply intent.

My starting point is usually that we should set out from an assumption that a type implies a certain amount of intent, in addition to being a "technical" specification (for instance, that an object representation needs to contain a certain amount of storage in order to have the specified state, which is a kind of information that could be identical for many different types with very different intent). For starters, we do not know the intent, but we need to make sure that it does not get ignored gratuitously.

For this reason I'm usually arguing that we should _not_ erase an extension type and proceed to use the representation type, unless there is a good enough reason to do so.

In this particular case I do think we have a reason: We're considering exhaustiveness.

In general, extension types don't have any guarantees about being exhaustive based on anything other than a catch-all case. In particular, extension types do not have the ability to specify exhaustiveness (we don't have a notion of `sealed` extension types). They basically _can't_ specify exhaustiveness properties independently of the representation type because the actual exhaustiveness is fully determined by run-time properties, that is, it is fully determined by the extension type erasure.

So we can't even introduce `sealed` extension types or similar notions unless they will just repeat something which can be shown to hold for the extension type erasure in the first place (and, conversely, the only thing a `sealed` modifier could really do would be to deny knowledge about a specific actual exhaustiveness property which is known for the erasure, but which has (intentionally?) been kept away from the extension type itself.

Note that we have already decided a while ago that exhaustiveness relative to a given matched value type and set of cases is determined based on the extension type erasure. The only question which is on the table here is whether we should also let the status of being 'always-exhaustive' propagate back from the erasure to the extension type, and this is only used for (1) switch statements (not expressions), to determine (2) whether the switch statement must be exhaustive.

So if we refuse to do this then we gain exactly one thing: The ability to **let a non-exhaustive switch statement go under the radar** if it has a _scrutinee_ whose type is an extension type and a representation type which is always-exhaustive.

It isn't going to matter for the exhaustiveness analysis (the result will be the same with and without this behavior), it just turns off the exhaustiveness analysis for these particular switch statements. It doesn't matter whether each case uses the erasure or the extension type (or some intermediate form with a mixture of extension types and non-extension types), the outcome of the exhaustiveness analysis will be the same. It is _only_ about the scrutinee, and it won't ever make anything safer, it just makes scrutinees with an extension type somewhat dangerous.

**Comment by lrhn** [comment]
We can also just make all extension type switches "must exhaust".

It's the way I'd like to go with switches in general, and to say that a switch statement with an extension type as matched value type must always be exhaustive, is not breaking.
The only side-effect is that every such switch statement which isn't otherwise exhaustive must have an empty `case _:` or `default:` at the end. That's the same as a switch expression on the same type would require.

So, my issue is that I don't think "must exhaust" is really a well-behaving concept to begin with, and I'd loathe to add more cases where we try to infer whether something should be exhausted or not, every time risking making a mistake because the author has no way to *control* it. You can't have a sealed type or enum which *doesn't* need to be exhausted, not even if you want to. And now, you can't even have an extension type on `bool?` which mustn't necessarily be exhausted, even if you don't think it's necessary. 

So, I suggest either allowing `sealed extension type`, which must be exhausted, and non-sealed extension types don't need to,
or making all extension type switch statements "must exhaust".

If every switch must be exhaustive, nothing needs to be special-cased, and the author doesn't have to worry about whether their extension type must be exhausted or not - because it always must.
(But it might be better to make all switches exhaustive then, as a breaking change which is trivially and automatically migratable, because then it won't be the same kind of breaking change to convert a final class into an extension type.)

We can add a `switch! (expr) { ... }` which doesn't need to be exhaustive, if we really want to avoid `default: /* do nothing */`, but I doubt it's worth it.

**Comment by eernstg** [comment]
The language team just decided (Jan 3, 2024) that we should indeed let the property of being [always-exhaustive](https://github.com/dart-lang/language/blob/main/accepted/3.0/patterns/feature-specification.md#exhaustiveness-and-reachability) for an extension type follow the same property of the corresponding extension type erasure.

This seems to be the behavior which is already implemented, in which case there is no implementation effort:

```dart
// Does not have `implements bool`.
extension type Bool(bool b) {}

void main() {
  switch (Bool(true)) {
    case true: print('Got true!');
  }
}
```

This program has an error at `switch` which shows that the type `Bool` is considered to be always-exhaustive (as it should, because the erasure `bool` is always-exhaustive).

**Comment by sgrekhov** [comment]
> @sgrekhov, I think this implies that a couple of co19 PRs can be unblocked?

I think so! I'll check

**Comment by sgrekhov** [comment]
@eernstg does the decision that was made by the language team affect https://github.com/dart-lang/language/issues/3534 as well?

**Comment by eernstg** [comment]
No, the question about flow analysis hasn't been resolved yet.

We should be able to get good coverage anyway by ensuring that the flow analysis doesn't cause tests to fail. That is, some switch statements will be able to complete normally according to the flow analysis, even though they are exhaustive and will be recognized as such if we change the scrutinee type such that, for example, `switch (ET(myBool)) { case .... }` becomes `switch (myBool) { case .... }`. We could then change `switch (ET(myBool)) { case .... }` to something like `switch (ET(myBool).it /*TODO: remove `.it` when #3534 is settled*/) { case .... }`. This means that we can test exactly the rule handled in #3534 by performing that removal, and the test should succeed today with the extra `.it`.

Please double-check, but something like that should work. ;-)

**Comment by eernstg** [comment]
Closing: The specification is updated in https://github.com/dart-lang/language/pull/3568, and tests and implementation is handled from there.
