### ISSUE TITLE
Type inference in sealed class switch expressions

### ISSUE THREAD

**Issue by LeoBound** [dart-lang/language#3610]
I'm on Dart 3.2.0 and have had a quick look around for other issues but I'm not too sure what to search for 🙂

I think I would expect the below to be valid code but the analyzer says it isn't with an error message that isn't that helpful.
This can be fixed by adding explicit casts on each branch of the switch expression

```
sealed class Parent<T> {
  T value;

  Parent(this.value);

  // Analyzer error: "The property 'a' or 'b' can't be unconditionally accessed because the receiver can be 'null'."
  String get childString => switch (this) {
        // Would expect value to be inferred as A
        ChildA() => value.a,
        // Would expect value to be inferred as B
        ChildB() => value.b,
      };
}

class A { String a = "A";}
class ChildA extends Parent<A> {
  ChildA() : super(A());
}

class B { String b = "B";}
class ChildB extends Parent<B> {
  ChildB() : super(B());
}
```

This can be fixed by adding explicit casts on each branch of the switch expression e.g.
```
  String get childString => switch (this) {
        ChildA() => (this as ChildA).value.a,
        ChildB() => (this as ChildB).value.b,
      };
```

But I'm surprised this can't be inferred from the type matcher on the LHS.
Thanks

**Comment by leafpetersen** [comment]
I think this is working a intended for at least two reasons:  first that we don't do promotion on `this` (which is something we've considered changing, there's an issue for it somewhere), and secondly that even if we did, I believe we don't promote the scrutinee of a switch statement based on the type tests in the branches (@munificent and @stereotype441 might have better recollection of the reasoning behind that design choice).

I believe a more idiomatic way of writing what you are trying to do above is as follows:

```dart
  String get childString => switch (this) {
        ChildA(:var value) => value.a,
        ChildB(:var value) => value.b,
      };
```

**Comment by stereotype441** [comment]
> I think this is working a intended for at least two reasons: first that we don't do promotion on `this` (which is something we've considered changing, there's an issue for it somewhere), and secondly that even if we did, I believe we don't promote the scrutinee of a switch statement based on the type tests in the branches (@munificent and @stereotype441 might have better recollection of the reasoning behind that design choice).

You're right that we don't promote `this`. As I recall there wasn't really a strong technical reason for that, other than the fact that it would entail a nontrivial amount of engineering effort, because `this` shows up implicitly in a lot of different places, so we would have to track them all down and make sure they all work. The feature request is here: https://github.com/dart-lang/language/issues/1397.

By the way, it so happens that we _do_ promote the scrutinee of a switch statement based on the type tests in the branches (assuming the scrutinee is something that's promotable, like for example a local variable). However, one of the requirements for type promotion is that the type being promoted _to_ must be a subtype of the type being promoted _from_. So even if we implemented https://github.com/dart-lang/language/issues/1397, the example above wouldn't work, because `ChildA` and `ChildB` aren't subtypes of `Parent<T>`.

_(A reasonable person might ask, why aren't `ChildA` and `ChildB` subtypes of `Parent<T>`? It kind of seems like they ought to be, since they extend `Parent<A>` and `Parent<B>` respectively. I had to dig around the source code for a while before I remembered the reason. The reason is because subtype checks involving type variables only answer "yes" if the subtype relation is guaranteed to hold regardless of what gets filled in for the type variable at runtime. So `ChildA` isn't a subtype of `Parent<T>` because `T` might be, `int`, for example, and `ChildA` isn't a subtype of `Parent<int>`.)_
