### ISSUE TITLE
Final fields in final/sealed classes aren't promoted?

### ISSUE THREAD

**Issue by bramp** [dart-lang/language#3615]
This example

```dart
class C {
  final int? n;
  C(this.n);
}

test(C c) {
  if (c.n != null) {
    print(c.n + 1); // ERROR
  }
}
```

Has a error, and points to https://dart.dev/tools/non-promotion-reasons#private to explain why. `n` must be private to avoid it being overridden.

However, I expected this to work:

```dart
final class C { // <<< Final keyword here. 
  final int? n;    // Now n can't be overridden.. right?
  C(this.n);
}

test(C c) {
  if (c.n != null) {
    print(c.n + 1); // ERROR
  }
}
```

Is this a bug in the flow analysis? or am I misunderstanding something? and/or perhaps an opportunity to add a extra case to https://dart.dev/tools/non-promotion-reasons?

thanks

**Comment by lrhn** [comment]
There are two things at work here.

One is that there is no way we can allow *another* library to promote `c.n`.
That required that other library to be able to know, and trust, that `n` is implmented by a `final` instance variable on a class with no subclasses.
That's true right now, but it's *not* part of the contract for the library. The library author is allowed to change `n` to a getter, or add a subclass with a getter with the same name. If someone in a nother library could promote a final variable that's not implemented elsewhere, then the library author loses this ability.

Generally, that's what abstraction buys you: The ability to change *implementation*. Any time we make behavior depend on implementation, not just interface signatures, more things become breaking changes.

On the other hand, we *do* allow some promotions inside the same library, because that code is inside the abstraction. (And if the library author breaks that promotion, they'll know *immediately*, and will be in a position to fix it.)

Currently, the only promotions we allow are *private* instance fields which are only implemented as (stable) final instance variables (and extension type representation variables). 
If `n` had been a private `final int ?_n;`, the promotion would have worked.

One reason only private variables can be promoted, is that this works independently of `final` modifiers.
If we allowed public names to be promoted too, then we'd have to be *very, very* certain that nobody, anywhere, can possibly implement that getter in a non-stable way. That means that all subclasses must be `final`/`enum`s or `sealed`. A class which is only `base` might get overridden. Also, we don't want to decide whether a privately-named class can escape in some way, including through type aliases.

(Promoting *static* variables would be safe, though.)

**Comment by bramp** [comment]
Thanks for the quick and comprehensive reply. 

To check my understanding, the tl;dr is, In theory we know it's not null, but we don't promote in that case, because it could break other users in future if class `C` was ever changed.

I'm curious where the line is. I could rename `C` to `D` and break everyone that depends on that class. Is the line obvious breakages are ok, but subtle ones are not?

BTW Does this example warrant updating https://dart.dev/tools/non-promotion-reasons. If so I'm happy to send a PR.

**Comment by julemand101** [comment]
The example in https://dart.dev/tools/non-promotion-reasons#property does also look wrong?
```dart
class C {
  int? i;
  void f() {
    if (i == null) return;
    print(i.isEven);       // ERROR
  }
}
```
It states the solution is to upgrade to Dart 3.2 but even with this version, this code are not correct?

**Comment by lrhn** [comment]
> I'm curious where the line is

Generally, at the "public API", which is a circular definition, because the public API is what we call the things you can depend on, separate from the "implementation details", which you should not depend on.

For a class, the public API is:
- for static access on the declaration:
    - the name at which you can access it. This is so fundamental that we usually don't even mention it. If you change the name, it's more like deleting the old class and creating a new one.
    - the _public_ static members and constructors accessible on the class declaration. Includes their names and function signatures.
    - whether a public static variable or constructor is `const`.
- for the type introduced by the declaration:
    - which public types that the class's type is a subtype of (aka., which interfaces it implements).
    - the member signatures of public instance members in the class's own interface. This includes getters and setters, but not whether they come from field declarations, were written explicitly, or were inherited.
    - if its `sealed`, then which immediate subclasses it has in the same library, and their exhaustiveness behavior.
- as a class:
    - wherever it can be implemented, mixed in or extended, and whether a subclass must be marked `base`.
    - if the class can be extended then also:
        - whether a public constructor is generative
        - the signature of the _implementation_ of a public interface member (for `super.member()` calls), and if the class is abstract, whether there is an implementation at all.

These are the things that, if you change them, existing valid code may stop compiling.
(You can always change what a method does, and break everybody using it, there is no way the compiler will catch that if you don't change it's function signature. This is about changes that the compiler will notice.)

Even among these, there are some changes that are _considered_ non-breaking, like adding an optional parameter to a static function. That won't break any _calls_ to the function, but because of type inference and function tear-offs, it's possible to create a program that will break.

Changing properties of a class that are not mentioned here, should not cause references to the class in other libraries to fail to compile.
That's not written explicitly anywhere, it's an emergent property of the rules not treating implementation details as relevant. It comes from the absences of semantics that depend on anything other than the above properties of a class defined in another library. That's why it's so important to not add an exception by accident, even if it locally looks like a good idea.

(As an example, it used to be possible to mix in a class declaration, if it's superclass was `Object` and it declared no constructor. That was based because other libraries shouldn't need to know what a class's immediate superclass is. It was a property that was easy to satisfy by accident, and then easy to break again because normally accepted refactorings could change the superclass or add a constructor declaration. That's why you now have to declare that a class is a `mixin class`.)

The only exception I'm aware of, is that there are some rules against a mixin application overriding a _private_ instance variable of another library.
It's a bad rule, similarly to the old mixin behavior, but luckily it rarely matters because mixins with private fields are rare.

**Comment by bramp** [comment]
Awesome. Thanks for sharing all the context.

So my issue is working as intended.
