### ISSUE TITLE
Optional type parameters / Default values for type parameters

### ISSUE THREAD

**Issue by rrousselGit** [dart-lang/language#363]
Consider the following class:

```dart
class Foo<T, S> {}
```

There is currently no way to instantiate `Foo` by specifying `T` but not `S`.

This causes an issue because to solve this use-case, we have to fork the class for each possible variations.
To express an optional `S` we'd solve it using two classes:

```dart
class Foo<T> {}

class Foo2<T, S> {}
```

But that's bad because the implementation is technically the same.

Here are some examples:
- https://github.com/rrousselGit/provider/blob/master/lib/src/consumer.dart

- https://github.com/ReactiveX/rxdart/blob/b8503a3be81b1bbece808e5888e202bc10595318/lib/src/streams/combine_latest.dart

That use-case could be solved much more elegantly using optional type parameters.
Some potential syntaxes can be:

```dart
class Foo<T, S = void> {}
```

or 

```dart
class Foo<T, S?> {}
```

which would then allow us to do:

```dart
Foo<int>();
Foo<int, String>();
```

This could be especially useful when combined with https://github.com/dart-lang/language/issues/362

**Comment by eernstg** [comment]
The language team has had discussions about default type parameter values several times (but we haven't spelled out the details, it's just been a topic that emerged now and then).

I can't immediately see how this feature alone would help you very much with the `Consumer`, `Consumer2`, ... `Consumer6` issue, because they have different implementations of `build` and different `builder` signatures, and the `combine` ... `combine9` static methods also seem to differ in ways that are non-trivial. It might be possible to make `Consumer6` do the work of all the others when the last `k` type arguments have their default value for `k` in 0..5, but I'll just comment on the plain notion of default type parameters and not worry about how to handle the details of `Consumer` and `combine`.

Default type parameter values could indeed do certain things that we can't otherwise express. In particular, we have no other features (today, or being proposed) that would allow for passing a non-empty part of a type argument list, you have to pass _no_ type arguments or _all_ type arguments.

However, it's worth mentioning a couple of related features.

Dart uses [instantiation to bound](https://github.com/dart-lang/language/blob/0e6111c01e7f35ad358c01570e5c865bd5269ce3/specification/dartLangSpec.tex#L5351) to compute the values of type parameters which are not specified and not inferred, and that mechanism might be considered to be a kind of default type argument:

```
class Bar<T extends Iterable<S>, S extends num> {}
Bar bar; // Means `Bar<Iterable<num>, num>`.
```

Also, there is an upcoming feature which might be helpful: Type aliases will be generalized to allow non-function types on the right hand side of `=`. This feature has not yet been implemented, but it has been decided that we will have this feature, and it is only a matter of priorities. Cf. the [implementation plan](https://github.com/dart-lang/language/blob/master/accepted/future-releases/generalized-typedef-2018/implementation-plan.md).

When we have that feature, you could declare abbreviated types as follows:

```dart
typedef Foo1<T> = Foo<T, void>;
```

You'd need to use a separate name (like `Foo1`), but in return you get the ability to define several short forms, omitting some type arguments that don't have to be the rightmost ones, and also to declare defaults that depend on the given type arguments (in ways that default type parameters might not support, e.g., because they are unlikely to allow dependency cycles):

```dart
class Bar<X> {...}
class Foo<T, S extends Bar<T>> {...}

typedef Foo1<T extends num> = Foo<T, Bar<T>>;
typedef Foo2<S extends Bar<Object>> = Foo<Object, S>;

Foo1<int> x1; // Has type `Foo<int, Bar<int>>`.
Foo1 x2; // Has type `Foo<num, Bar<num>>`.
Foo2<String> x3; // Has type `Foo<Object, Bar<String>>`.
```

So the ability to use the _same name_ and omit one or more of the rightmost type arguments seems to be the most prominent new feature that default type parameter values would give us.

**Comment by rrousselGit** [comment]
> When we have that feature, you could declare abbreviated types as follows:
> 
> ```dart
> typedef Foo1<T> = Foo<T, void>;
> ```

That's a very good point. I suppose that it covers most of the use-case.

>  and the combine ... combine9 static methods also seem to differ in ways that are non-trivial.

We can do something like `if (T == Null)`.

**Comment by srawlins** [comment]
Previously opened as https://github.com/dart-lang/language/issues/283.

**Comment by rrousselGit** [comment]
Oh, indeed sorry. I failed to find it during my searches.
