### ISSUE TITLE
Grammar rule adjustments for augmentation libraries

### ISSUE THREAD

**Issue by eernstg** [dart-lang/language#3644]
I think we should adjust the grammar rule:

```
libraryName ::= metadata 'library'
    ( dottedIdentifierList? | 'augment' uri ) ';'
```

This adds the question mark, allowing for `library;`, which is currently supported and used.

Similarly, `topLevelDeclaration` should have a case for `extensionTypeDeclaration`, `'external' finalVarOrType identifierList ';'`. Class declarations and mixin declarations need to have class modifiers.

`declaration` should have `'external' ('static'? finalVarOrType | 'covariant' varOrType) identifierList` and `'abstract' (finalVarOrType | 'covariant' varOrType) identifierList`, and several adjustments to the remaining cases.

I think the general picture is that the specified rules need to be adjusted to include recent language features.

**Comment by lrhn** [comment]
I think we should move away from conflating libraries and augmentations. It's a third kind of file, next to libraries and parts.

It should have its own 
```
<augmentOf> ::= 
 `augment` `of` <URI string> `;`
```
declaration at the top, which is not a "library name" declaration.

(I use "of" instead of "library" because augmentations can augment other augmentations, and they are not libraries.)

**Comment by davidmorgan** [comment]
I think this is obsoleted by #3848
