### ISSUE TITLE
Pattern matching allows you to refer to its own scope

### ISSUE THREAD

**Issue by victor-tinoco** [dart-lang/language#3652]
So, if you declare a class with a getter, like this:

```dart
class A {
  String get name {
    return switch (this) {
      // Notice that while declaring the name getter, I can access it here.
      A(name: final name) => name,
    };
  }
}
```

Pattern matching does not throw a static error for this, so, you can refer to the getter you're declaring (on its declaration scope body). Would that be expected to be allowed? The same occurs when you create a getter through an extension. 

I fell in this case because of my copilot, when I tried to build it by running the tests, it just crashed with a non-descriptive error, probably because it is like a recursion. It is not supposed to be allowed since it will always fall in a _runtime_ error.

**Comment by lrhn** [comment]
This is only a runtime error because the instance you're calling on is the same, and it's assumed to have the same implementation.
If `A` was abstract, and `foo` was marked `@subclassMustOverride` (or whatever that annotation is called), then it might not be an error.

I don't see the language wanting to specify when code like this is going to definitely be a problem, it's more of an analyzer job, which is also where the current watching for `get foo => foo;` comes from.

**Comment by victor-tinoco** [comment]
Yea, maybe an analyzer warning, and not an error, would be proper, mostly because of the overriding stuff you mentioned.

It should be able to identify the same way it does:

<img width="592" alt="image" src="https://github.com/dart-lang/language/assets/49794086/8a0c8943-7917-46e2-b786-b8a54d59f10d">

**Comment by munificent** [comment]
> Should it be opened on the `linter` repo, then?

Yes, that's not a bad idea. Thanks!
