### ISSUE TITLE
Improved null-aware parsing

### ISSUE THREAD

**Issue by nate-thegrate** [dart-lang/language#3685]
`foo ?? bar` and `foo!.bar` are fantastic, but I think `foo?.bar` has room for improvement.

<br><br>

We have 2 problems:

### Nullable function types

`onChanged!(value)` works great, but `onChanged?(value)` doesn't—you need to write it out as `onChanged?.call(value)`

### Future dot syntax

If we end up implementing a convenient dot syntax (#357, #417 or #3616), we first need to address the [syntax ambiguity concern](https://github.com/dart-lang/language/issues/417#issuecomment-504680660):

| the same thing | could be interpreted as | what the compiler expects afterward |
|---|---|---|
| `foo?.bar` | `foo is Object?` (null-aware operator) | `foo?.bar ?? baz` |
| `foo?.bar` | `foo is bool` (conditional expression) | `foo ? .bar : .baz` |

<br><br>

## Proposal

~Interpret x? differently based on whether it's a nullable type~ apparently this isn't feasible ☹️

Insist that `?.` is a single token, so that `? .` can always be treated as a conditional expression.  
(This doesn't help with nullable function types, but that's something I can live with.)

**Comment by lrhn** [comment]
The problem here is that parsing comes (way) before type inference.

Asking whether `e` has a nullable type before deciding how to _parse_ a following `?.x:y`, assuming we allow `.x` as an expression, is going to complicate the compiler, because it needs to keep those tokens _unparsed_, or as a superposition of the two different parsings, until very late in the compilation.

And if the type inference of `e` depends on the context, then whether `e` is even _in_ that context depends on how the following tokens are parsed.

The more likely approach would be to pick a default and require parentheses for the other option. (And the default is likely to be the one that parses today, so existing code won't change meaning.)

**Comment by nate-thegrate** [comment]
> The problem here is that parsing comes (way) before type inference.

Thanks for letting me know! I've updated the proposal to account for this information.

**Comment by nate-thegrate** [comment]
The main intent of this issue was to facilitate progress toward solving issue #3616, in which there's currently a link to a fleshed-out [design proposal](https://github.com/dart-lang/language/blob/main/working/3616%20-%20enum%20value%20shorthand/proposal-lrhn.md). I'm good with closing this and deferring to those. :)
