### ISSUE TITLE
Incorrect difference.inDays value after time change

### ISSUE THREAD

**Issue by milik27** [dart-lang/language#3692]
In the Europe/Vilnius time zone, after changing the time 2024-04-01 from +02:00 to +03:00 difference.inDays returns the wrong number of days in this interval

    DateTime date1 = DateTime.parse('2024-03-30');
    DateTime date2 = DateTime.parse('2024-04-01');
    Duration difference = date2.difference(date1);
    print(difference.inDays); // -> 1

Dart 3.3.3

**Comment by julemand101** [comment]
Lithuania changed to DST March 31, 2024 which means one of your days are 23 hour long. Since `inDays` counts days defined by counting 24 hour, it is expected behavior what you have observed. You can read more about this in the documentation for `difference`: https://api.dart.dev/stable/3.3.3/dart-core/DateTime/difference.html

I recommend using time defined in UTC if you are going to use the `difference` method since it will be more predictable.

**Comment by lrhn** [comment]
Correct. The `Duration` class doesn't know anything about calendars, so its "days" are always 24 hours. `DateTime` represents points in time, which can be displayed either as local time or as UTC time. There were not two full days between the two points in time here, only 47 hours.
