### ISSUE TITLE
Extension types should implements record types

### ISSUE THREAD

**Issue by kranfix** [dart-lang/language#3693]
The documentation doesn't explain why this is not possible and I don't find a reason in `Dart v3.3.3`.

```dart
typedef Cartesian = ({double x, double y});
extension type Position(Cartesian _) implements Cartesian {}
extension type Velocity(Cartesian _) implements Cartesian {}
```

![](https://github.com/dart-lang/language/assets/1251381/4177c896-eb75-4739-bc18-d8fe1a01f7da)

**Comment by lrhn** [comment]
It's mainly an abundance of caution.

The "implements" relation is special. It's used by the least-upper-bound operation, and so far the only types that a type can implement are _named_ types, classes (including mixins and enums) and now extension types.

There are other types that, if an extension type can implement them, central assumptions in the language and implementations may become invalid.
Or it might give users the wrong impression about how it should work.

For example, if an extension type could implement `Never`, then it would be a _proper subtype_ of the bottom type, which is a contradiction in terms.

There were other cases that looked or behaved surprisingly, but the **Up** algorithm was the main reason for disallowing implementing a non-named type, because it's currently written in a way that handles structural, non-named types first, and then recuses until it has only named types left, and then does something else with those, based on their super interfaces. If a named type can have a non-named type as superinterface, then that algorithm breaks down.

So it's not that it's necessarily impossible to make an extension type implement a record type, but it's not as easy as just saying that it's allowed. It may have significant repercussions for the specification, and maybe the implementation.
