### ISSUE TITLE
How to do error handling with exception and async code?

### ISSUE THREAD

**Issue by stephane-archer** [dart-lang/language#3716]
We have two ways of dealing with errors (that I'm aware of):

- by return value (Go, Rust)

- by exception

if you look at Go or Rust code, basically every function can fail and most of your code is dealing with errors over focussing on the happy path.

This is tedious over having a big `try {}` and catch each type of error separately, grouping your error handling for a group of functions and having the error and happy path quite separate. You can even catch a few function calls lower to make things simpler for you and group even more functions in your error handling.

Now let's introduce "async / await" in the equation...

with the return value approach, when you need the value, you await, you check for error then use the value if there is no error or you deal with the error.

with the exception you get a future that would make you leave the catch block then you will continue code execution but then an exception occurs and this is where I'm so confused. Who catches the exception?

Is it the catch block where my original call was? is it some catch block that doesn't exist in the rest of my code because I'm supposed to guess when my async call will throw? Does the "main" code execution stop even if it has moved forward? I just can't understand how things work and how to do good error handling in this context, can someone explain to me?

**Comment by Wdestroier** [comment]
You can await the Future in the try block: https://dart.dev/codelabs/async-await#example-async-and-await-with-try-catch.

```dart
try {
  print('Awaiting user order...');
  var order = await fetchUserOrder();
} catch (err) {
  print('Caught error: $err');
}
```

or set a `catchError` callback: https://dart.dev/guides/libraries/futures-error-handling.

```dart
myFunc().then((value) {
  doSomethingWith(value);
  ...
  throw Exception('Some arbitrary error');
}).catchError(handleError);
```

> This is the asynchronous equivalent of a "catch" block.
> https://api.flutter.dev/flutter/dart-async/Future/catchError.html

**Comment by lrhn** [comment]
> when you need the value, you await,

That goes for both cases.
When you need the *result*, you await. If the result is a thrown error, that is what the `await future` expression results in, that error being thrown again.

A future represents the (eventual) result of a computation, which can be either a value or a thrown error.
It can temporarily be passed around as a value, but you must quickly await it (using `await` or one of the `Future` callbacks, which then gives you another future), so that *if* it completes with an error, the future can trust that someone will handle that error. (Otherwise it'll report it as unhandled, and you don't want that.)

**Comment by stephane-archer** [comment]
Thanks, @lrhn and @Wdestroier for your great answers.
You said that:
> A future represents the (eventual) result of a computation

But an async task can represent things like moving a file. In that case, the result could be a `Future<void>`.
In that case, should we "await" the Futur to handle any eventual exception? Should we "await" every Futur in our code even if we are not interested in the result? What happens if we forget to "await" a Futur? Can someone lower in the call stack handle the exception in some ways? 

you also mentioned:
> but you must quickly await it

From my understanding, an async task in Dart starts as soon as you as possible, and "await" is waiting for the value, so I would expect to be a good strategy to start the task as quickly as possible and to "await" at the last minute, when you need the value. Do I miss something?

**Comment by stephane-archer** [comment]
Can you please check if my mental model is correct?
```
var a = asyncTask1();
var b = asyncTask2();
var c = SyncTask3();
print(await a, await b, c)
```
from my understanding, the actual execution would be:
- asyncTask1 until the async operation
- asyncTask2 until the async operation
- SyncTask3 complete execution
- finish asyncTask1
- finish asyncTask2
- print

```
var a = await asyncTask1();
var b = await asyncTask2();
var c = SyncTask3();
print(a, b, c)
```
from my understanding, the actual execution would be:
- asyncTask1 complete execution
- asyncTask2 complete execution
- SyncTask3 complete execution
- print

await every Futur immediately does not result in any "smart scheduling" regarding the async operation and would result in the same code execution order if the operation were synchronous.
`var a = await asyncTask1();` is equivalent to `var a = task1Sync();`

**Comment by lrhn** [comment]
> In that case, should we "await" the Futur to handle any eventual exception?

Yes

> Should we "await" every Futur in our code even if we are not interested in the result? 

Pretty much. Unless: 
- You don't care about the result.
- You don't care about knowing when it's done.
- You know for a fact that it won't complete with an error.

Then there is no need to await the future, or otherwise handle it's completion.

> What happens if we forget to "await" a Futur? 

Worst case, it completes with an error and crashes your entire program.
There are ways to harden against that and recover from uncaught errors, but you need to do something.

> Can someone lower in the call stack handle the exception in some ways?

No. If you don't await the future, the error never comes back to a call stack, it gets reported directly to the event loop, which can then crash and take down the rest of the program.

About execution of asynchronous functions, calling an `async` function does, as you say, run synchronously until the first synchronous await in the body. Then it (still synchronously) returns the future.
This is the first moment where the calling code has access to the future, and the list moment where it's safe to make sure the future handles errors.
The only provides that futures provide is that they won't spontaneously complete in the middle of something else. They'll complete as some kind of async event, likely a later microtask, or event loop event. Quite possibly the very next microtask, if the async function threw in the initial synchronous execution. 
But it can be any later event.

Starting two async computations, producing two futures, means that you cannot predict which future will complete first. Awaiting one before the other risks the other completing with an error before you get to it. It's inherently unsafe. 

Either use `await (future1, future2).wait` to wait for both at the same time, or do `future2.ignore(); await future1; await future2;` to make the service future's error be non-fatal, which is OK because you will look at it later.

**Comment by stephane-archer** [comment]
Thanks a lot, @lrhn for your answer. 
I didn't understand you should "await" all the future except in some rare cases so you can properly handle the error handling attached to them. (I think updating the documentation about it would be great, I only saw await has a way to get a value in a Future https://dart.dev/codelabs/async-await)

Is there a way like putting a breakpoint in a Future destructor to quickly find in your program, a Future that has not been "await"?

There is still something I don't understand looking at the end of your answer.
To me, the point of async is to be able to continue the execution of the main program while a file IO is happening in the background. You get a Future, do some stuff then continue the execution of your async function when you "await" the Future, hoping that the file IO has been done (or you wait). 
If you "await" as soon as you receive the Future and don't see how it is different than the Synchronus version? When you await the Futur (and in the case, you are still waiting for this IO to finish), something else might be executed in the event loop. Is it the only difference (it doesn't sound like a big deal)?

> Starting two async computations, producing two futures, means that you cannot predict which future will complete first. Awaiting one before the other risks the other completing with an error before you get to it. It's inherently unsafe.

I understand you can't predict which one will finish first. But I don't understand why `await future1; await future2;` is unsafe. If you return while doing the error handling of future1 when you will miss the errors on future2 but if you continue and `await future2;` then you will see errors of future2 at this time, even if it finished first. Do I miss something? I'm confused about the `future2.ignore();` part.

**Comment by lrhn** [comment]
Usually, the point of making a function asynchronous is not to do other things in the function that called it, but to let other, more unrelated, asynchronous computations make progress while this computation is blocked.

It allows code written similarly to single threaded code, with explicit yield points at `await`s, cooperative multitasking. 
Code written that way would want to insert an `await` at every possible point, the moment a future is created. 

The ability to create a future and _not_ `await` it immediately, is there, but that's advanced control flow, and requires much more care. 
The most common way to do that is to start two or more computations, by calling multiple async functions in the same synchronous execution, and then combining them into one using `.wait`. That "join" of individual computations again happens immediately, and then the resulting future is awaited, ensuring that no future is left unhandled across an asynchronous gap.

The general rule for safely using futures is to always await a future _when_ you receive it, no later than as the next await.

Anything else is for experts.

**Comment by stephane-archer** [comment]
Thanks a lot, @lrhn for your great answer.

> Usually, the point of making a function asynchronous is not to do other things in the function that called it, but to let other, more unrelated, asynchronous computations make progress while this computation is blocked.

> The general rule for safely using futures is to always await a future when you receive it, no later than as the next await.

I start to understand but there are still a few things that don't click for me yet. Let's say I work on a CLI app (no Flutter).
If my program is:
```
void main() {
var a = await asyncTask1();
var b = await asyncTask2();
var c = await asyncTask3();
var d = SyncTask4();
print(a, b, c, d)
}
```
I don't see here any cooperative multitasking...
When you yield at the first `await` nothing else runs and you just wait for asyncTask1 to complete and the story repeats itself each time until the end.

But this program (from my understanding):
```
void main() {
var aF = asyncTask1();
var bF = asyncTask2();
var cF = asyncTask3();
var d = SyncTask4();
a,b,c = await (aF,bF,cF).wait
print(a, b, c, d)
}
```
would launch each task until they have to wait for an IO then wait for the different results back.
This sounds to me like a more cooperative multitasking thing.

yielding is only useful if there is another computation waiting in the background and I don't see how the `var a = await asyncTask1();` pattern can create these conditions.

-------------

Just to rephrase your explanation to make sure I understood.
In the program:
```
void main() {
var aF = asyncTask1();
var bF = asyncTask2();
var cF = asyncTask3();
var d = SyncTask4();
a = await aF;
b = await bF;
c = await cF;
print(a, b, c, d)
}
```
if `asyncTask2` or `asyncTask3` finish quicker (with an error) than `asyncTask1`, the Runtime would consider these errors uncaught because the try-catch around `b = await bF;` and `c = await cF;` has not been reached since we are still waiting at `a = await aF;` for `asyncTask1` to finish. Is this explanation correct?

I understand that when using flutter yielding often is important.

**Comment by stephane-archer** [comment]
> There is a lint that warns about unawaited futures, which catches most common mistakes inside sync functions. It's enabled by default.

I'm not sure what is wrong with my setup but I had to activate manually the lint rule to see these errors in Vscode
```
include: package:flutter_lints/flutter.yaml

linter:
  rules:
  - unawaited_futures
```
with `flutter_lints: ^3.0.0` as a dev dependency.
I have a lot of errors, I wish this was activated by default for me

**Comment by lrhn** [comment]
Yes, this sounds correct. 

Your simple program doesn't have any multitasking, it's entirely serialized. 
More complicated programs are more likely to have multiple things going on at the same time, like a timer event running and causing a UI update while a network request is in progress, or any number of other independent parts of an application all doing their own things. 

If you want to increase parallelism, and your code is ready for it, the example using `.wait` is exactly how to do that. 


Dart futures are designed to avoid an error getting ignored by accident. 
That's a choice, and it was taken deliberately.
Since it's impossible to perfect the future, the way a future determines whether its error is being ignored, is to check whether the future had any listener, from `await` or added using the future API, when it completes.
That's why it's a problem when the `await b` happens after an `await a`, because there is no listener on `b` until the `await b` is reached. If it completes with an error before, the "this error must not be ignored" guard kicks in and reports the error as uncaught to the zone that the future was created in. This is special code, outside of the normal flow of futures. 
If you later evaluate `await b`, that will still raise the error again, every await of the future will do that, it's just too late to prevent the error from being considered uncaught.

So always handle a future immediately, because "immediately" is the only time that's guaranteed to be before the future completes.

**Comment by stephane-archer** [comment]
Thank you so much @lrhn for your explanation. I missed a lot of points before this conversation
https://dart.dev/codelabs/async-await is not talking about all of that.
> So always handle a future immediately, because "immediately" is the only time that's guaranteed to be before the future completes.

"immediately" is quite misleading because it's even better to launch a few other (independent) async tasks and then do `await (future1, future2).wait`. The rule could be don't await another future if you already have one.

But regarding `await (future1, future2).wait` if future1 and future2 succeed everything is great but what about one of them fail? From my understanding, if one of them fails you get `ParallelWaitError`. so you just lost everything, the exception thrown and the success values. Did I understand correctly?

Do you know any better alternative to `await (future1, future2).wait` to increase parallelism and not lose your results if one of them fails? (usually, if you can do things in parallel it's because the tasks are independent so loosing all the results if one of them fails is not the most convinient behavior)

you mentioned previously `furure2.ignore(); await future1; await future2;`. Would this be the best pattern?
`await future2` would return the same value that was given to `furure2.ignore();` previously and ignore. Do I understand correctly?

**Comment by lrhn** [comment]
The `ParallelWaitError` contains both the values and the errors of all the waited futures. They are not lost. 

Using `ignore` works too, but that does risk losing the result of the second future of the first future throws. You'll have to recover and await the second future in that case too, and then it doesn't look as simple any more.

**Comment by stephane-archer** [comment]
I will then use `await (future1, future2).wait` extensively. ;)
@lrhn you are the best! thanks for taking the time to share these tips and your great explanation about `Future`
I wish you the best! :D

**Comment by concatenation2** [comment]
@stephane-archer https://angular-strap-dissertati.github.io/getvalue/
