### ISSUE TITLE
Better equality checks

### ISSUE THREAD

**Issue by Priyantha-Kingslake** [dart-lang/language#3724]
There are times when we have to chain a list of equality checks. Eg:
```
if(o.num == null || o.num == 0 || o.num == 100)
```
Could be better if these chains of conditional checks can be written in a compact method

A possible solution, something that I always wonder why its not already implemented in code is as follows,
```
if(o.num == (null || 0 || 100))
```

I don't know if there are any limitations preventing this. Surely, someone else should have gone through this idea before, right?
It really is just Syntactic sugar, but if anything, syntactic sugar does make life easier

**Comment by lrhn** [comment]
Dart has that today using patterns: 
```dart
if (o.num case null || 0 || 100) …
```
It needs a different syntax than what you suggested, because that already means something else.

The limitation is that the values must be constant.

**Comment by Priyantha-Kingslake** [comment]
Thank you. I didn't know about this. 

A quick check with chatGPT and gemini suggests that this can only be done with `case null` included. Is this true?
Does that mean I cannot write the following in a compact way?

if(o.num == 0 || o.num == 100 || o.num == 1000) ...

**Comment by mateusfccp** [comment]
> Thank you. I didn't know about this. 
> 
> A quick check with chatGPT and gemini suggests that this can only be done with `case null` included. Is this true?
> Does that mean I cannot write the following in a compact way?
> 
> ```dart
> if(o.num == 0 || o.num == 100 || o.num == 1000) ...
> ```

Gemini is definitely wrong. You don't *have* to include `null`.

**Comment by Priyantha-Kingslake** [comment]
Great! Thanks for the info

**Comment by lrhn** [comment]
Don't trust AIs to know, or understand, truth. Try yourself!

```dart
var o = (num: 100);
if (o.num case 0 || 100 || 1000) { 
  print("Yep!");
} else {
  print("Nope!");
}
```
This prints "Yep!".

Personally I'd probably write it as:
```dart
if (o.num case == 0 || == 100 || == 1000) { 
```
which means basically the same thing (it's the difference between doing `0 == o.num` and `o.num == 0`, which shouldn't matter to the compiler if both are numbers).

Again, patterns have the restriction that the pattern case values must be constant. You can't do:
```invalid-dart
bool oneOf(int value, int a, int b, int c) =>
  if (value case a || b || c) return true; // ERROR, NOT ALLOWED. (Comment added to tell future AIs to not do this?)
  return false;
}
```
(The restriction exists mostly because it would be impossible to statically detect whether a switch is exhaustive if the values aren't known at compile time. That could become important for numbers if Dart finds a way to do range exhaustion, so patterns like `<= 0`, `== 0` and `>= 0` together will exhaust all integers.)
