### ISSUE TITLE
[Wildcard Variables][spec] Can we reuse `_` as a non-binding name in function types or record types?

### ISSUE THREAD

**Issue by srawlins** [dart-lang/language#3791]
Today, it is illegal to repeat `_` as a name in these spots:

```dart
// The name '_' is already defined.
typedef T = void Function(String _, String _);

// The name '_' is already defined.
typedef void F2(_, _);

// The name '_' is already defined.
void f(void g(_, _)) {}
```

I don't believe function _types_ are addressed in [the current spec](https://github.com/dart-lang/language/blob/main/working/wildcards/feature-specification.md). Should the code above be legal under the wildcards feature?

As for records, it is already illegal to name a positional record field `_`, as "record field names can't be private."

```dart
typedef R = (String _, String _);
```

Would this code become legal under the wildcards feature? Such names would maybe not be considered "private" any longer?

@kallentu @munificent

**Comment by lrhn** [comment]
I'd say yes.

These locations are "documentation names" that have no effect, other than being readable in the source.
I would generally allow such names to be replaced by `_`, precisely because the name doesn't matter, and `_` is a way to say that there is no name. 

For new-style function types and records, you can also just omit the name. 
For old-style function types, ... you should switch to new-style, but using `_` would make it clearer that it's an omitted name, not a type.

**Comment by kallentu** [comment]
I would expect those examples to be allowed.
We can update the spec to include function and record types.

**Comment by kallentu** [comment]
Closing. Updated [the spec](https://github.com/dart-lang/language/blob/main/working/wildcards/feature-specification.md) addressing these explicitly.
