### ISSUE TITLE
[Wildcard Variables][spec] `_` in imports

### ISSUE THREAD

**Issue by kallentu** [dart-lang/language#3799]
Do we allow an import statement like `import ... as _;`? And if so, what does this do? Is this also non-binding?

@dart-lang/language-team 

### Previous Discussion

> Maybe we should make `_` non-binding as an import prefix?
> 
> It's like a top-level declaration, but it's also only available in the lexical scope. If you want to import a library only for it's extensions, you may want to import it with a prefix, and never need to refer to it, and `as _` would work for that.

 _Originally posted by @lrhn in [#3791](https://github.com/dart-lang/language/issues/3791#issuecomment-2104073807)_

**Comment by eernstg** [comment]
Make it non-binding such that it can be used to provide access to just the extensions (and possibly other declarations that get a similar treatment, e.g., implicit constructors).

This would make it possible to use `import 'a.dart' as _; import 'b.dart' as _;` etc. to import a bunch of extensions (and "similar things", if any, but nothing else). We wouldn't have to think about the appropriateness of using `_` all over the place as an import prefix (because it doesn't work), and the developer wouldn't have to avoid name clashes among all those `_`.

Sounds like an OK job for a wildcard.

**Comment by kallentu** [comment]
Great. Adding a section on the spec. https://github.com/dart-lang/language/pull/3819
