### ISSUE TITLE
Callback based API for declaring macro implementations

### ISSUE THREAD

**Issue by lrhn** [dart-lang/language#3824]
The current API for a macro implementation is to be a class which implements some number of interfaces.
From `_macros/lib/src/api.dart`:
```dart
/// The marker interface for all types of macros.
abstract interface class Macro {}

/// The interface for [Macro]s that can be applied to a library directive, and
/// want to contribute new type declarations to the library.
abstract interface class LibraryTypesMacro implements Macro {
  FutureOr<void> buildTypesForLibrary(Library library, TypeBuilder builder);
}

/// The interface for [Macro]s that can be applied to a library directive, and
/// want to contribute new non-type declarations to the library.
abstract interface class LibraryDeclarationsMacro implements Macro {
  FutureOr<void> buildDeclarationsForLibrary(
      Library library, DeclarationBuilder builder);
}

/// The interface for [Macro]s that can be applied to a library directive, and
/// want to provide definitions for declarations in the library.
abstract interface class LibraryDefinitionMacro implements Macro {
  FutureOr<void> buildDefinitionForLibrary(
      Library library, LibraryDefinitionBuilder builder);
}

// ... 30+ interfaces omitted ...

/// The interface for [Macro]s that can be applied to any type alias
/// declaration, and want to contribute new non-type declarations to the
/// program.
abstract interface class TypeAliasDeclarationsMacro implements Macro {
  FutureOr<void> buildDeclarationsForTypeAlias(
    TypeAliasDeclaration declaration,
    DeclarationBuilder builder,
  );
}
```

There is a marker interface, which has no real effect, and lots of *single method* interfaces.
That's something Dart Style [mentions](https://dart.dev/effective-dart/design#avoid-defining-a-one-member-abstract-class-when-a-simple-function-will-do), and recommends using a function value instead.

Each such interface method is specialized to a single phase of macro execution. The three `Library...` interfaces above are for the three phases. It's possible that a macro may only want some of the phases, but it's also very likely that it wants all three, and has to implement all three interfaces and declare all three methods.

So this is my recommendatation:

* Don't have require the macro implementation to implement any interfaces.
    * In fact, don't require it to be a class which needs to be instantiated before it can be used.
    * Maybe just let it be a *function* that takes a single "macro context" object as argument.
* Instead of implementing interfaces, have the macro implementation code register callbacks, using just function values, on the macro context. This set-up can be done before further macro execution begins. (Maybe it has to call an "I'm done" method when it's all set up.)
* Instead of having three methods to declare library callbacks, it can just be one:
    ```dart
    macroContext.libraryMacro(types: buildTypes, declarations: buildDeclarations, definitions: buildDefinitions);
    ```
    which registers this macro as one that can work on a library, and do so in all three phases.

    This already cuts things down from 30+ interfaces to ~12 methods, and significantly less typing.
*  I'd allow a macro to add callbacks for later phases during earlier phases too. Maybe a macro doesn't know
    from the start whether it needs to add definitions, but after seeing the types in phase 2 it decides that it does.
    If using interfaces, the macro would have to always implement `LibraryDefinitionMacro`. Here it can decide
    as late as in phase 2 whether it wants to run in phase 3 or not. Or it can update the callback it registered
    (only allow one per phase, setting it again overrides the prior one), if it decides it needs more, or less.

This still allows later language versions to add more kinds of callbacks. The user doesn't have to implement any interface, they just use methods to add callbacks.

**Comment by jakemac53** [comment]
I prefer the current approach (unsurprisingly, because I designed it 🤣 ), here are some reasons:

- How does a macro get a "macro context"? Presumably, this essentially adds a 4th phase (for registering which phases you want to run in), with additional round trips and overhead (to register your macro in each phase) that isn't required with the current approach.
- Knowing all the phases a macro wants to operate in ahead of time allows you to more easily only run the necessary phases. As an example, the first phase cannot do introspection and never needs to be re-ran unless the _current file_ changes. If you have to (or have the ability to) register which later phases you are going to run in during that phase, then it is more challenging to avoid redoing this work.
- The callback approach encourages retaining state between phases which we do not want macros to do. The (const) class based approach means you can only share _global_ state, and won't implicitly capture local state like a callback would. In particular, objects retrieved from macro APIs are only valid in the current zone, attempting to cache them and use them in a later phase will cause problems.
- Similarly the callback approach is more prone to memory leaks - these callbacks have to be retained potentially indefinitely (especially if you want to try and avoid re-running earlier phases).  And it is very easy for them to retain a bunch of state that isn't actually necessary, or shouldn't have been retained.
- I don't believe it actually makes the code meaningfully better. It won't be significantly shorter (the callbacks will be essentially the same as the implemented methods),  the class header is short and replaces the explicit register calls.
- When written as a class the tooling is better because you write the interfaces you want to implement, and the tooling will create the stubs for you to fill in.
- Classes also enable the use of mixins etc which makes them easily composable.

**Comment by jakemac53** [comment]
I am going to close this one as not planned.
