### ISSUE TITLE
Deprecated properties should be Strikedout

### ISSUE THREAD

**Issue by shinayser** [dart-lang/language#386]
_(Probably this is not the place to post this issue, but some guidance could be welcome where to post it)_

Deprecated properties should be visually 'strikeouted'. For example:

![image](https://user-images.githubusercontent.com/1146982/58809380-33412d00-85f2-11e9-858c-8ef46e791586.png)

In the code above, the `resizeToAvoidBottomPadding` is deprecated but there is no visual indication for that like there are for methods:

![image](https://user-images.githubusercontent.com/1146982/58809480-64b9f880-85f2-11e9-9cf0-8a5d84092250.png)

Since Dart is a language the proporse itself to be a "UI-as-code" language, this is a must have feature since deprecated properties will become very commom as time passes.

**Comment by munificent** [comment]
Yeah, this isn't the correct repo, since this is really a feature in the UI of an IDE. Which IDE are you using? Can you re-file this bug here: https://github.com/dart-lang/sdk

I'm not sure if that's the ideal repo either (we may want to route it to something IntelliJ or VS Code specific), but that's a start. Thanks!
