### ISSUE TITLE
Infer generic classes in subclasses

### ISSUE THREAD

**Issue by rubenferreira97** [dart-lang/language#3894]
When working with generic classes in Dart, the compiler currently requires explicit type arguments for subclasses, even when the type can be clearly inferred from the constructor parameters. This issue arises from the need to manually specify the generic type parameter when extending a class, leading to redundant type declarations and potential for errors if mismatched types are used.

Consider the following code example:

```dart
abstract class Foo<T extends num> {
  Foo({required this.number});
  final T number;
}

class DoubleFoo extends Foo/*<num>*/ { // Could we infer `double` here?
  DoubleFoo() : super(number: 2.0);

  double getDouble() => number; // Error here since number is num, writing Foo<double> fixes it
}

class IntFoo extends Foo/*<num>*/ { // Could we infer `int` here?
  IntFoo() : super(number: 1);

  int getInt() => number;  // Error here since number is num, writing Foo<int> fixes it
}
```
In the `DoubleFoo` and `IntFoo` classes, the type argument for `Foo` could logically be inferred as `double` and `int` respectively based on the constructor parameters. However, Dart currently requires these type arguments to be explicitly specified as `Foo<double>` and `Foo<int>`.

I know the following example is quite different, but it illustrates a situation where Dart is able to infer types, suggesting that similar inference could be beneficial in other contexts as well:
```dart
T Function() callback<T extends num>(T number) => () => number;

void main() {
  final /*int Function()*/ foo = callback/*<int>*/(1);
}
```

**Considerations:**
I'm not entirely certain if enabling such a feature might have unintended consequences or introduce complexities in the type system that could lead to issues in other parts of the codebase or in specific use cases.

**Comment by lrhn** [comment]
> the type argument for `Foo` could logically be inferred as `double` and `int` respectively based on the constructor parameters.

Not really. Since `num` is a valid solution, it's not obvious that using `double`/`int` is a _better_ solution. 
It is in this case, but it might as well have not been. And if there is more than one constructor, then it becomes even less obvious which type relations should be constraints, and what should not. 

But how far should it go?
```dart
abstract class S<T extends num> {
  abstract final T value;
}
class T extends S {
  final value;
  T([this.value = 1]);
}
```

In this case one could (maybe) infer that `final value;` should inherit the type `int` to match the default value, so `S` should be `S<int>`.

But you don't know the type of `1` before you know the type of `value`. If the type of `value` was `double`, the `1` would have had type `double` too, so this is actually a cyclic dependency in the type inference algorithm.

There is a reason Dart decided to require the superclass types to be determined before trying to do type inference on members.

**Comment by rubenferreira97** [comment]
Thanks @lrhn for the clear explanation 🙏.

The inference algorithm I described can indeed become very complex when multiple constructors are involved, and in those cases (among others), I assume that might infer differently for what people would want.

Making your example clearer in practice:

```dart
abstract class S<T extends num> {
  abstract final T value;
}

class T extends S/*<int> assuming value is inferred as int */ {
  T([this.value = 1]);

  int getInt() => value;
}

void main() {
  final foo = T(2.0); // Error: value is already inferred as int, so we can't accept a double here. T cannot be both an int and a double.
}
```
---
I guess this inference algorithm would only be beneficial if, as in my example, the value is constant within the subclass. Such an edge case might not be a good reason to change the current behavior.
