### ISSUE TITLE
Can you implement a desugared protocol with an extension method?

### ISSUE THREAD

**Issue by munificent** [dart-lang/language#391]
There are several places in the language where the runtime semantics are defined in terms of some user-defined protocol. The ones I know of are:

* The for-in statement desugars to casting the sequence to Iterable and then calling `iterator` on it.

* Likewise, the for collection element does something similar.

* The await for statement does something analogous using the Stream API.

* Likewise await for collection elements.

* I'm not sure about await.

These are, as of Dart 2.0, all nominally typed. The object must declare it implements the right protocol for the desugaring to proceed. In Dart 1.0, they were done purely dynamically, naturally.

In a world with extension methods, should we consider doing something a little less nominal? Concretely, can an extension method take an existing type and allow it to be used in a for-in statement?

```dart
extension IntStuff on int {
  Iterator<int> get iterator => Iterable<int>.generate(this).iterator;
}

main() {
  for (var i in 10) print(i); // Prints 1 - 10.
}
```

This seems potentially useful. Leaf points out this has good performance benefits: a protocol implemented in terms of an extension method can always be statically dispatched and thus potentially inlined more easily.

If we *do* allow extension methods to implement these protocols, this raises questions about how that interacts with null-shorting spreads. Given:

```dart
extension Weird on Object? {
  Iterator<int> get iterator => [1, 2, 3];
}

main() {
  Map map = {};
  print([...map?.[key]]);
}
```

Does this print `[]` or `[1, 2, 3]`? What do users *want* this to do?

**Comment by leafpetersen** [comment]
Regardless of the answer we decide on, we should be specific about the behavior of things defined via de-sugaring, as in this de-sugaring of a `for in` loop:

```dart
T id1 = e;
var id2 = id1.iterator;
while (id2.moveNext()) {
D id = id2.current;
{ S }
}
```

`T` is currently specified as being assignable to `Iterable`.  If we maintain this, then `.iterator` can't be an extension method call, but I think `moveNext` and `current` could be, if the `.iterator` method is overridden with a return type of `Null`, unless we explicitly call out that those are intended to be instance calls.

**Comment by lrhn** [comment]
I can see the lure, but I think mixing static extensions into what is, from the user's side, thought of as interfaces might be dangerous. You cannot implement an interface using static extension members (it's not traits).

Giving some language features an advantage is nice, but it weakens the distinction between interfaces and static extension members.

I'm also afraid that we will lose some inference if we allow "any object" to be used in a specific position, as long as there is static extensions supporting the operation. That means that we can't use `Iterable<int>` as context type for `e` in `for (int x in e) ...` (do we? should we?).

I am also worried where the turtles stop. If I do:
```dart
extension _ on int {
   int get iterator => this;
   bool moveNext() => true;
   int get current => Random().nextInt(this);
}
...
  for (var i in 42) {
    print(i);
    if (i == 0) break;
  }
```
would it work?
*Should it*?
The code is completely incomprehensible, so I'm not sure who we are helping here.

**Comment by eernstg** [comment]
We basically just made some changes in order to make for-in more strictly typed (20087c8e330ad34025885d6a141122ac0f1efb22), and similar changes have been made earlier on for other language-defined protocols. The effect was that we would not just accept an arbitrary object `o` with an `iterator` etc, we insist that the _meaning_ of those methods can be assumed to be relevant, because the class of `o` has `Iterable<T>` as a superinterface.

So we can just undo those changes and then the extension methods will work. If we drop the type related constraints and blindly desugar the code then we get optimal flexibility, and it's still statically typed because the desugared code will be checked just like any hand-written Dart code.

I suspect that we won't actually do this, because we probably agree on the general direction: We often rely on **static types** because they give developers some provably correct hints about what their code will do, that is, it helps improving correctness.

We might not agree to the same extent on the next step, but I like to add the following: **Nominal types** are safer than structural types, because they imply a conceptual "contract" between the provider and user of an entity which goes beyond the technical parts: The classes `Foo` and `Bar` may both have a `baz` getter of type `int`, but there's a better chance that they are both suitable for a given domain specific _purpose_ if `baz` is added to the interface of both classes by one of them or by a common supertype.

Apart from the correctness issue there is also **encapsulation**: If we start playing games with code that was produced by desugaring for one of these protocols then it will be necessary for developers to _know exactly_ which code the desugaring yields, and only then can they start reasoning about what their code will do. This is costly, because it is impossible to know from the syntax of a for-in or similar construct whether it's necessary to envision the desugared code and think hard about how it might work.

I'm sure we can find smart ways to specify that desugared code can either rely on a nominal type, or it could invoke some static extension methods, but I'm not convinced that it will be worth the price in terms of overall code comprehensibility.

**Comment by leafpetersen** [comment]
I think the decision on this was no.
