### ISSUE TITLE
Unable to call super method on an object.

### ISSUE THREAD

**Issue by darkstarx** [dart-lang/language#3928]
Hello!

I have some class hierarchy.
```dart
class User {
  final String id;

  const User({ required this.id} );

  Map<String, dynamic> toJson() => { 'id': id };
}

class ServerUser extends User {
  final String secretField;

  const ServerUser({
    required super.id,
    required this.secretField,
  });

  Map<String, dynamic> toJson() => { ...super.toJson(), 'secretField': secretField };
}
```

Next, I have an instance of `ServerUser`, like that:
```dart
  final ServerUser user = await getServerUser();
```
and I need access to the method `User.toJson` from the instance of `ServerUser` to respond with, like that:
```dart
  return Response(body: { 'user': user.toJson() });
```
but without extra secret fields of the `ServerUser` class.

How can I achieve this?

In c++ I can simply specify the class whose method I want to call, like `user->ServerUser::toJson()`.
In Dart I have to implement all hierarchy in derived classes like that:
```dart
class User extends BaseModel {
  ...
  Map<String, dynamic> toBaseModelJson() => super.toJson();
}

class ServerUser extends User {
  ...
  Map<String, dynamic> toUserJson() => super.toJson();
}
```
It's redundant and inconvenient.
Can you hint any good idea about that? Thanks!

**Comment by lrhn** [comment]
What you are doing is what I'd suggest. 

Dart does not allow you to call other methods than the ones implemented by the object's runtime type. Only the class itself can call a `super.` method, and only of its own superclass.

I'd probably do it as: 
```dart
class  User { 
  // ...
  Map<String, Object?> toUserJson() => { ... }
  Map<String, Object?> toJson() => toUserJson();
}
class ServerUser extends User { 
  // ...
  Map<String, Object?> toServerUserJson() => { ... super.toJson(), ... }
  Map<String, Object?> toJson() => toServerUserJson();
}
```
so classes won't need to mention each other.

**Comment by lrhn** [comment]
Since this is a language request, a language feature which would allow you to do _something_ like this could be (strawman syntax!):
```dart
  user.User::toJson()
  // or
  user.super<User>.toJson()
```
The former is more traditional, the latter uses existing Dart keywords in a non-conflicting way.

The reason I'd be against this feature is that it assumes that the `ServerUser` has `User` as a superclass, and that `User` has a concrete implementation of `toJson`.

Today, it's a valid refactoring to change `ServerUser` to _implement_ `User` instead of extending it. If it does that, then running the `User` class' `toJson` on the `ServerUser` instance must not be allowed, it's running an instance method on an object that it may not be compatible with. 

Similarly, a valid refactoring of `User` could be to make it an abstract class or interface with a factory constructor creating a concrete subclass, a classical interface/implementation split. 
Then trying to invoke `User::toJson` would be invalid since `User` doesn't have any such method at all.

In both cases a valid refactoring today becomes a breaking change if a user of the class can make assumptions about the class hierarchy.

When Dart restricts access to objects to the methods defined by their interface, not their entire class hierarchy, it's enforcing an abstraction precisely to ensure that you can refactor things freely below that abstraction.

Any time a user of a class is able to depend on _implementation_, that implementation becomes part of the public API, and changing the implementation becomes a breaking change. 
(That's also why the interface doesn't distinguish final fields from getters.)

**Comment by jakemac53** [comment]
Note that you could refactor this code to use extensions, and then you would be able to explicitly select the less specific extension. The tradeoff is all serialization would be done in terms of static types and not runtime types, which could be surprising.

Example [code](https://dartpad.dev/?id=bd07eeb63401ccf35ee5219a9ebc116b)

**Comment by darkstarx** [comment]
> When Dart restricts access to objects to the methods defined by their interface, not their entire class hierarchy, it's enforcing an abstraction precisely to ensure that you can refactor things freely below that abstraction.
> 
> Any time a user of a class is able to depend on _implementation_, that implementation becomes part of the public API, and changing the implementation becomes a breaking change. (That's also why the interface doesn't distinguish final fields from getters.)

I would probably agree with these arguments.

This syntax is new for me ))
```dart
UserToJson(this).toJson()
```

Great, thanks for advice!
