### ISSUE TITLE
hashCode for enums are different each time

### ISSUE THREAD

**Issue by quoc-huynh-cosee** [dart-lang/language#3955]
Every time I call the following code, I get a different value. Is this to be expected?

```dart
void main() {
  print(Test.a.hashCode);
}

enum Test { a }
```

**Comment by quoc-huynh-cosee** [comment]
Okay, I didn't know that. But why is the hashCode of the same string always the same?

**Comment by mraleph** [comment]
>  But why is the hashCode of the same string always the same?

Because it is defined based on the string content and we don't mix any randomness into it, but we could. 

Unless you have control over `hashCode` implementation you can only rely on `hashCode` being consistent with equality (e.g. if `a == b` implies `a.hashCode == b.hashCode`), but not on its actual value or its stability over different runs.
