### ISSUE TITLE
Allow a variable initializer to be unresolved, following the treatment of abstract members

### ISSUE THREAD

**Issue by eernstg** [dart-lang/language#3977]
It is not obvious from the [augmentations feature specification](https://github.com/dart-lang/language/blob/main/working/augmentation-libraries/feature-specification.md) whether or not it's possible for a non-local variable declaration consisting of an introductory and zero or more augmenting declarations can have an _unresolved_ initializing expression during augmentation.

If we do allow an unresolved initializing expression then we would allow the following:

```dart
int i;
augment int i = 42;
```

This augmenting declaration stack leaves the initializing expression of `i` unresolved at the introductory declaration, but it is resolved as `42` at the augmenting declaration. Of course, it would be an error if the augmenting declaration used `augmented` in the initializing expression, because it would be a reference to an initializing expression that doesn't exist.

But the point is that it would _not_ be an error to have a variable declaration with an unresolved initializer and a potentially non-nullable type, as long as the missing parts are added by augmentation.

This differs from the current behavior of the analyzer:

```
  error • n016.dart:1:5 • The non-nullable variable 'i' must be
          initialized. Try adding an initializer expression. •
          not_initialized_non_nullable_variable
```

However, the support for an unresolved initializer is in line with the fact that a concrete class can contain an abstract member declaration (that's a kind of "unresolved member implementation"):

```dart
// No errors, `a` can be abstract at first because it is concrete after augmentation.
class A { int get a; }
augment class A { augment int get a => 0; }
```

For a variable whose type is nullable we can choose to say that the introductory variable declaration with no initializing expression is considered to have the initializer `= null`. That's a different issue (#3725).

But when the type of the variable is potentially non-nullable then we can't invent an initializing expression in the case where it isn't physically present, and that's the reason for talking about "unresolved" initializing expressions.

It looks like the implementation (so far, it isn't anywhere near complete) does not allow a variable to have an unresolved initializer. This seems at least conceptually inconsistent with the specified and implemented treatment of abstract members. 

So I'd recommend that we _do_ allow those unresolved initializers to exist. However, I cannot see anything in the feature specification that confirms or contradicts this statement, so if we do decide to do this then we may need to add a short paragraph about it in the spec.

@dart-lang/language-team, WDYT? Can a variable initializer be abstract? ;-)

**Comment by lrhn** [comment]
Not sure what "unresolved" means here.

As to whether we should allow:
```dart
int i;
augment int i = 42;
```
then yes, we should.

There should be no rule *preventing* it.

The rule saying that a variable with a non-nullable type must have an initializing expression should only apply to *fully augmented* declarations. It's not a syntactic restriction, it's a consistency restriction, which means it should only apply to the actual definition that the rest of the program can see. No part of the program can see `int i;` without an initializer, other than the `augment int i = 42;` declaration, which is the only declaration that can refer to the `int i;` declaration.

It's not that `int i;` has an "unresolved initializer". It has *no* initializer expression. That's not a problem, it doesn't have to have one. The definition of the `i` variable *after* all augmentations have been applied has an initializer expression, and a type of `int`, and that's fine, there is no requirement before that.

**Comment by eernstg** [comment]
> Not sure what "unresolved" means here.

It is simply intended to indicate that the omission of an initializing expression which is an error today is not an error for a declaration which is followed by an augmenting declaration that provides an initializing expression.

We have to be able to talk about the properties of each declaration in a chain of augmentations in order to be able to specify the meaning of `augmented`, so we can't just jump to the top-level view and say "my eyes are closed until merging is done, so there is an initializing expression and there's no problem". In particular, we must be able to say that `augmented` is an error in this situation:

```dart
// A class that does not use augmentation (that is, a pre-feature class).
class A {
  static int i; // Error, must be initialized.
}

// A class that does use augmentation.
class B {
  static int i; // There is no initializing expression, and it is not an error.
}

augment class B {
  augment static int i = 1; //
}
```

We need to make a clear distinction between each individual declaration (introductory or augmenting) in a chain of augmentations and the declaration which is the result of merging. We can have errors in none of them, in one of them, or in both.

For example, the assignability check on the initializing expression must be performed locally on each element in the augmentation chain:

```dart
int i = 'Hello';
augment int i = augmented.length;
```

In this case, a compile-time error is reported at the introductory declaration because `String` isn't assignable to `int`. It does not suffice that `augmented.length` is well-typed (because the type of `augmented` is `String`, and its `length` has return type `int`, which is assignable to the type of `i`), we require that each of the elements in the augmentation chain satisfies the assignability requirement.

On the other hand, we do not report an error for the introductory declaration based on the fact that it doesn't have an initializing expression. This is checked on the merged declaration only.

```dart
// Merged declaration OK.
int i;
augment int i = 1;

// Merged declaration not OK: Missing initializer, not a nullable type.
int j;
augment @metadata int j;
```

Perhaps we could find a better word than 'unresolved'? The situation of special interest is that the initializing expression is omitted in the introductory declaration (and possibly in some augmenting ones as well), but it is present in the merged declaration. This is accepted during the local check (of the introductory declaration and each of the augmenting ones), but it is reported as an error on the merged declaration.

What we really need is a terminology that makes this local and global check explicit. We should probably simply specify that the checking takes place in two steps.

**Comment by lrhn** [comment]
We do need some terminology.
I've tried a few times. Maybe this one will work:

* A non-augmenting (syntactic) declaration introduces a definition. The definition has some properties derived from the declaration.
* An augmetning declaration, if valid, is applied to a definition, producing a new definition.
* Each kind of declaration introduces its own kind of definition.

Example:  A non-augmenting function declaration introduces a function definition (unless it has compile-time errors, like two parameters with the same name). A function definition has:
* A parameter list, which has a number of positional and named parameter definitions, each having:
    * a name,
    * possibly a type clause,
    * may be convariant,
    * may be required or optional (satisfying the usual constraints on positional optionals), and
    * may have a default value expression.
* A return type clause.
* A type parameter list, each having:
    * a name
    * may have a bound type clause
* May have a body, or may be `external`. (Can't be both.)
* A *kind*, one of: static method, top-level function, instance method, extension method, or extension type method.
* A list of metadata definitions, can be empty.

If the declaration is an instance method declaration, the definition may inherit return and parameter types from a super-interface.

Applying an augmenting function declaration to a function definition requires:
* Having the same name.
* Having the same kind.
* Having the same parameter positions/names.
* Having the same type parameters
* If declaration specifies return or parameter types, must specify "same type" as the type clauses of the definition.

The result of applying an augmenting function declaration to an augmented function definition is a function definition with:
* The same name.
* The same parameter list.
* The same return type.
* The same type parameter list.
* If the augmenting declaration has a body, then that is the body of the definition. If that body refers to `augmented`, invoking `augmented` invokes the augmented definition with the provided argument list.
* If the augmenting declaration has no body, and is declared `external`, then so is the new definition.
* If the augmenting declaration is neither declared `external` or has a body, then the new defintion
   is external if the augmented definition is, or has the same body as the augmented definition if that has 
   a body, and otherwise it has no body and is not `external`.
* Has a list of metadata annotations that is the concatenation of the metadata definitions of the augmented
   definition, and the metadata definitions introduced by the metadata annotation declarations on the augmenting
   declaration in source order.

And so on.

In the case of a variable definition, introduces a variable definition, a getter definition and possibly a setter definition. Each can be augmented separately.
For each base (non-augmenting) declaration, it introduces an (immediate) definition, and the library in total defines a  (fully augmented) "complete definition" for that declaration, which is derived by iteratively applying augmenting declarations to the prior definition in augmentation application order, until there are no further augmenting declarations.

Then it's a compile-time error if a non-local, non-instance, non-`late` variable's complete definition has a non-nullable type and no initializer expression.
