### ISSUE TITLE
Inheriting a type parameter bound?

### ISSUE THREAD

**Issue by eernstg** [dart-lang/language#3986]
Type inheritance in augmenting declarations includes support for inheriting type parameter bounds, but in return requires that the type parameter names are identical to the names of the type parameters of the augmented declaration:

```dart
class A {
  void foo<X extends Comparable<X>>() {}
  void bar<X extends Comparable<X>>() {}
}

augment class A {
  augment void foo<X>() {} // OK.
  augment void bar<Y extends Comparable<Y>>() {} // Error, the name is `X`.
}
```

With override inference (which is a mechanism that doesn't depend on augmentations and that we've had for several years), we have the opposite approach:

```dart
class C {
  void foo<X extends Comparable<X>>() {}
  void bar<X extends Comparable<X>>() {}
}

class D extends C {
  void foo<X>() {} // Error, must have the same bound.
  void bar<Y extends Comparable<Y>>() {} // OK.
}
```

Should we strive for more consistency in this area?

Augmenting declarations are not overrides, so we _can_ treat them differently. But we could also require identical type parameter declarations in augmenting declarations for now, thus maintaining a higher degree of consistency. We can always relax it later on if we decide that this would be useful (possibly for both situations).

**Comment by jakemac53** [comment]
I see that it is a bit weird that this behaves differently from overrides, but augmentations generally do work differently:

- All types must match _exactly_ the original types
- They can't add optional arguments

So, while it is tempting to try and have the same semantics I think it is not worth while. We should instead choose the desired semantics for augmentations, and accept that they might be different in ways that are a bit confusing.

In this case, the bounds are always known. There is no value in requiring the user to re-state them (or at least, this is the argument, I could see some arguments that there is value).

Ultimately, I would be pretty happy with either decision here, but we do need to make a decision, sooner than later.

@lrhn @munificent @leafpetersen @eernstg do any of  you feel strongly that we should change this, to require re-writing the exact bounds instead of allowing them to be omitted?

**Comment by lrhn** [comment]
If we allow other types to be omitted (parameter/return types) then I am fine with allowing you to omit bounds too.

I'll even allow you to omit the type parameters entirely, but then I wouldn't allow referring to them by name.

We'd not be consistent on this, though. For modifiers we usually require the augmenting declaration to repeat the modifiers it cannot change. Og er allow omitting types that you can't change, why do we have that difference? Are the two things fundamentally different? Or is it just that we are used to types being and to be omitted and inferred. On that case, we're not used to type parameter bounds bring omitted and inferred.
That would be an argument against showing that.

You should be able to invoke `augmented` with a different type argument than the calling invocation.
If you couldn't, I'd also allow you to omit the type argument and default to the same type. But if you can pass a different type argument, then it should instantiate to bound as normal of omitted.

**Comment by jakemac53** [comment]
In general we want you to be able to look at an augmentation and have all the information you need, without going to the original declaration. We also want to remove any ambiguity, so forcing duplication of modifiers makes it explicit that an augmentation cannot _remove_ them by omitting them. It is also generally useful to know that a function is generic.

I do agree the bounds could be required following the same logic, they _can_ be useful (knowing the bounds is potentially useful). And if omitted somebody could mistakenly think the bounds were _altered_, which they aren't.

But, it can also add a fair bit of boilerplate to the declaration, and they aren't necessary for scoping reasons since they don't introduce anything into the scope.

**Comment by lrhn** [comment]
So what is we allow omitting the type, but not the extends? 
```dart
int foo<X extends, Y extends>(...)...
```
That makes it clear that there is a type here, and that it's omitted, the same way the presence of a parameter means that it must have a type, whether you write one or not.

**Comment by eernstg** [comment]
I think we have support for maintaining the current wording of the specification in this area, with the interpretation that I mentioned at first, and @jakemac53 confirmed:

```dart
class A {
  void foo<X extends Comparable<X>>() {}
  void bar<X extends Comparable<X>>() {}
}

augment class A {
  augment void foo<X>() {} // OK.
  augment void bar<Y extends Comparable<Y>>() {} // Error, the name is `X`.
}
```

So we can indeed omit the bound, and we can restate it precisely ('same type' as in [here](https://github.com/dart-lang/language/blob/main/accepted/2.12/nnbd/feature-specification.md#runtime-type-equality-operator)), and we can't rename type variables.

We would then close this issue, noting that there is no need to change anything.

@dart-lang/language-team, any strong feelings to the contrary?

**Comment by jakemac53** [comment]
Sounds like everybody is OK with the current status, I am going to go ahead and close this
