### ISSUE TITLE
Allow `augmented` to be a regular identifier inside an augmenting declaration?

### ISSUE THREAD

**Issue by eernstg** [dart-lang/language#4009]
The augmentation specification currently makes it an error for `augmented` to be used as a regular identifier inside an augmenting declaration. However, it would be possible to allow it in a few cases, without ambiguity. This issue raises the question.

```dart
var augmented = 1;

class A {
  void bar() {}
}

augment class A {
  void foo() => augmented = 2;
  augment void bar() => augmented();
}
```

The body of `foo` in `augment class A` is currently an error because `augmented` occurs inside a declaration that carries the modifier `augment`. The rationale for specifying the rule in this manner was that `augmented` should have the semantics of invoking the augmented declaration (in particular, it should never be looked up as an identifier in the enclosing scopes) when it occurs inside any augmenting declaration. It's simply too much of a footgun to use it as a regular identifier, even in the cases where it cannot possibly invoke any augmented declaration (because there aren't any).

However, we could actually allow `augmented` to be used as a regular identifier in cases like the body of `foo`. The argument in favor of doing this is that it would have a well-defined semantics, consistent with other usages of identifiers (and `augmented` is indeed a regular identifier everywhere else). @lrhn makes this argument [here](https://github.com/dart-lang/language/issues/3967#issuecomment-2214081226), as part of another discussion.

We could allow it and have a lint that flags every occurrence of `augmented` which is resolved as an identifier. This would help developers who really need to access a declaration named `augmented` inside a non-augmenting member declaration which is inside an augmenting declaration. It still wouldn't help us in the case where the member declaration is also augmenting. https://github.com/dart-lang/language/issues/3899 might be a better solution.

@dart-lang/language-team, WDYT?

**Comment by jakemac53** [comment]
I think it is both easier to specify and easier to understand as a user if we don't make this distinction. And I also don't think the extra functionality afforded would be widely used. We already know that `augmented` is a pretty rare name for members (based on searching our internal code base).

Are we sure that we will never want `augmented` to be used directly inside a type or extension declaration? For example, lets say we wanted to allow you to control the order of interfaces, instead of just appending to them, we could allow `implements SomeThing, ...augmented` in the future. I don't have plans for this, but maybe we would want the ability to do similar things later on.

So, I would lean against allowing this. But, I also don't feel super strongly about it.

**Comment by lrhn** [comment]
I think it's *easier* to explain that `augmented` means something specific inside the function bodies (or initializer expression) of augmenting declarations, the places where it can actually be used to reference something.

If you have:
```dart
int augmented = 0;
class C {
  void inc() { augmented += 1; }
  int foo() => 21;
  augment int foo() => augmented() * 2;
}
```
and decide to move `augment foo` into a separate augmentation:
```dart
int augmented = 0;
class C {
  void inc() { augmented += 1; }
  int foo() => 21;
}
augment class C {
  augment int foo() => augmented() * 2;
}
```
then it keeps working the same way.

If you do the same to `inc`:
```dart
int augmented = 0;
class C {
  int foo() => 21;
}
augment class C {
  void inc() { augmented += 1; }
  augment int foo() => augmented() * 2;
}
```
then the meaning of the body of `inc` *changes meaning* if we let the outer `augment class C` determine whether `augmented` is special. In does so in a place where `augmented` has no actual meaning (the error will be something like "Cannot use `augmented` inside non-augmenting declaration").

I strongly believe that 
1. It's a significantly simpler model to only use the function/member declaration's `augment` to determine whether its body/initializer treats `augmented` specially, which it does precisely in the cases where `augmented` can be used. Simpler to define and simpler to explain. The meaning of a non-augmenting declaration doesn't change because it's moved from a `class` to into an `augment class`, because that context has no *effect* on the non-augmenting declaration.
2. Nobody, or very close, will actually care in practice, since there won't be anything named `augmented`.

So we might as well make it simpler for ourselves: Let `augmented` be special in precisely the cases were it can be used, where the surrounding top-level or member-level function/variable declaration is marked `augment`, and let all other methods be unaffected. (Implementation-wise, it should be less to keep track of.)

**Comment by jakemac53** [comment]
> 1. It's a significantly simpler model to only use the function/member declaration's `augment` to determine whether its body/initializer treats `augmented` specially, which it does precisely in the cases where `augmented` can be used. Simpler to define and simpler to explain.

If we can delete lines from the spec or at least not overly complicate it with this change I am all for it.

> 2\. Nobody, or very close, will actually care in practice, since there won't be anything named `augmented`.

I definitely agree that nobody cares or will care (or close enough). So, whatever is simplest is what we should do imo.

**Comment by munificent** [comment]
Yeah, I think Lasse's argument makes sense. Treating `augmented` as special only inside the members where it actually is special is consistent with how `await` works too:

```dart
main() {
  var await = 'weird but ok';

  outer() async {
    inner() {
      print(await);
    }

    inner();
  }

  outer();
}
```

Here, the use of `await` is immediately inside `inner()`, which is *not* an async function. But `inner()` is surrounded by `outer()`, which *is* async. Even so, within `inner()`, `await` is treated as an identifier even though it is textually surrounded by a non-immediate async function.

Treating `augmented` as an identifier inside a *non*-augumenting which is itself inside an augmenting type would be consistent with that.

**Comment by lrhn** [comment]
Yes, but ...
We do (or at least may) want to make `augmented` usable inside a nested function: 
```dart
  augment int foo(int arg) {
    return _specialZone.run(() =>
        augmented(arg));
  }
```
We can't tear off the augmented function, but we can close over a call to it. (At least that's what I've so far expected, because it allows something like the above, and if the body can be `async`, anything after the first `await` is effectively inside a closure anyway.)

**Comment by jakemac53** [comment]
The rules are definitely different from async/await but I think @munificent brings up a good point that there is prior precedent for making something only have a special meaning exactly in the places where it would actually be useful.

**Comment by eernstg** [comment]
OK, I'm hearing arguments in favor of allowing `augmented` to be a regular identifier in every location where it cannot possibly be an invocation of an augmented entity, and no worries about readability.

So let's go for that.

```dart
var augmented = 1;

class A {
  void bar() {}
}

augment class A {
  void foo() => augmented = 2; // OK, `augmented` is a regular identifier here.
  augment void bar() => augmented();
}
```

@dart-lang/language-team, any strong feelings against this outcome?

**Comment by eernstg** [comment]
We aren't doing this after all! The feature specification stays the way it is, and this means that `augmented` is basically considered to be a contextual reserved word, not usable for anything other than referring to the augmented declaration when inside an `augment` declaration.
