### ISSUE TITLE
Should implicit conversion work below nullable types.

### ISSUE THREAD

**Issue by lrhn** [dart-lang/language#401]
Currently we have some type based implicit conversions:

```dart
int Function(int) x = callableClassInstance;
double d = 1;
```
These should probably work work through union types, including nullable types.
Consider:
```dart
CallableClass? c;
int Function(int)? x = c;  // tearoff or nothing. Or should you write `x = c?.call;` explicitly?

double? d = 1;
```

The double literal will definitely work as written, but the callable class one might not when the RHS type is nullable (it is not the type of a nullable class, it is merely a union of one with `Null`).

**Comment by eernstg** [comment]
I agree that the `double?` case just works, and I think that's fine. We immediately forget that this `double?` isn't null, but that's just a normal upcast, nothing wrong about that.

I'm not so happy about the `CallableClass` example, it seems a bit too magic that we would extend the tear-off to be a conditional tear-off (otherwise we have sugar for `e` ==> `e.call`, not `e?.call`). But we could easily allow for these "epsilon supertypes" of function types as a context type to trigger the tear-off:

```dart
CallableClass c = e;
int Function(int)? x = c; // Desugared to `c.call`.
```

Again, I think it's OK to keep this `call` magic confined to a rather small area, for instance by not adding any desugaring to a construct that uses `?.`.

**Comment by lrhn** [comment]
I agree that `CallableClass?` assigned to `Function?` is a stretch. We do not allow `FutureOr<Callable>` to be assigned to `FutureOr<Function>` either, although that's not necessarily comparable.
The workaround would be to write `?.call`.

I also think that `CallableClass` assigned to `Function?` could be made to work. We currently do the tear-off when assigning to `FutureOr<Function>`, so it should work for the `Function?` union type too.

**Comment by leafpetersen** [comment]
I am specifying this to allow the tear-off when the LHS is a union type, but not the RHS.
