### ISSUE TITLE
generic type should be non-null by default ,instead of requiring `<T extends Object>` to mandate non-null

### ISSUE THREAD

**Issue by airai-ad-117** [dart-lang/language#4012]
hi ,

`type? function<type>()` is very dangerous ,because `type` can be `int?` ,while the return type is also nullable ,hence distinction is impossible ,

current behavior :
`type? function<type>()` is equal to `type? function<type extends Object?>()`

proposed behavior :
`type? function<type>()` is equal to `type? function<type extends Object>()` (`Object` vs. `Object?`)

thanks

**Comment by mateusfccp** [comment]
All types are subtypes of `Object?`, but not all types are subtype of `Object`, so it's only natural that we expect `extends Object?` to be the default behavior.

Also, it would be very breaking to do it now, and I don't think the potential benefits (your post does not make it clear what they would be) surpasses the hassle of such a breaking change.

**Comment by lrhn** [comment]
Unlikely to happen. Even if it's desirable, it would _far_ be too breaking.
A class like `class List<E>` would suddenly not allow `List<int?>` any more. Every class can be fixed by adding `extends Object?`, but every class would *need* to be fixed. Migrating every generic class ever written, that just isn't worth it.

Whether it is desirable is another question. As @mateusfccp says, having *no bound* suggests that any type is a valid argument.
