### ISSUE TITLE
Should a static extension method `call` work.

### ISSUE THREAD

**Issue by lrhn** [dart-lang/language#402]
Dart allows "callable classes", classes declaring a `call` method, to be used where a function is expected:
```dart
class Callable {
  int call(int x) => x;
}
Callable c = Callabe();
int x = c(42);  // implicitly `c.call(42)`.
Function f = c;  // implicitly `c.call`.
```

We generally plan to allow [extension methods](#41) to act like instance methods, so if I declare:
```dart
extension Slices<T> on List<T> {
  List<T> call([int start = 0, int end]) {
     int length = this.length;
     if (start < 0) start = length + start;
     if (end == 0) {
       end = length;
     } else if (end < 0) {
       end = length + end;
     }
     if (end < start) end = start;
     return this.sublist(start, end);
  }
}
```
Should it work? 
That is, should the following work:
```dart
List<String> names = [ "alpha", "bravo", "charlie", "delta", "echo" ];
var sublist = names(1, -1);
print(sublist);  // prints: bravo, chalie, delta
```

The code was chosen deliberately as something that might actually happen.

Or should extension members only work on explicit member access. 

We do allow other operators to work, like `operator[]`, so the syntax isn't much different for the "operator" `call`.

It gets less readable when we look at implicit `call` method tear-off.
Then:
```dart
List<String> names = ...;
List<String> Function(int, int) slicer = names;
```
Here there is nothing suggesting to the reader why `names`, with the well recognized type of `List` is suddently assignable to a function type. There is no name introduced which can hint to the reader what is going on.

It gets even less readable if we start using even more well-known types:
```dart
extension Range on int {
  Iterable<int> call(int to) => Iterable<int>.generate(to - this + 1, (x) => x + this);
}
...
  for (var i in 1(10)) print(i); // prints 1 through 10.
  ...
   Iterable<int> Function(int) from10 = 10;
```
This is night unreadable because the reader has a clear preconception about a value like `10`. it's OK to add new methods to `int`, but the reader will require *some* hint to understand what is going on.

Maybe we can allow this, and just tell people to not do silly things. Leave it as a style matter, not a language issue, whether you use static extension `call` methods.

**Comment by eernstg** [comment]
We already have a limit on the flexibility of this mechanism: A getter named `call` is not considered when we perform a dynamic invocation of an object of type `Function` or `dynamic`, we will only use a method.

The ability to perform a tear-off of a static extension method seems to be another point where we could "just say no" ;-)

```dart
List<String> names = ...;
List<String> Function(int, int) slicer = names; // Error.
List<String> Function(int, int) slicer2 = names.call; // OK.
```

Similarly, it's tempting to say that you can't call weird things just because there is a static extension somewhere:

```dart
var x = 1(10); // Error.
var y = 1.call(10); // OK.
```

So we'd need some really compelling examples where we _do_ want to allow it.

**Comment by lrhn** [comment]
I think looking at bad examples may prejudice us in the wrong direction.

Consistency would say that when every other operator works, so should the "call" operator. Static extension methods should act as close to instance methods as possible. Making an exception to that for entirely *stylistic* reasons is not a good idea, and is likely to come back and haunt us when people want to make extension `call` methods for *good* reasons that we haven't thought of.

So, I see no *technical* reason to prohibit `call` as a fully functional extension member, the same way we do `operator[]` or `operator+`. That would at least allow the invocation.
Not allowing the tear-off then is just another non-technically based exception.

We can definitely do it. I think we should. For great consistency!

**Comment by eernstg** [comment]
> Making an exception to that for entirely stylistic reasons is not a good idea

I envision developers getting completely baffled, like "WAT, we just called an `int`?!", but you're of course right that it is possible to do terrible things with any language construct.

Also, consistency yields simplicity and power at the same time, and that's obviously wonderful.

But given that `o.m()` can invoke an instance method `m`, or a getter `m` returning a function object which is then called, instance method invocations cannot be distinguished syntactically from indirect calls via a getter. We have **already decided** that the `e` --> `e.call` sugar is strictly **limited to instance methods**, both for invocations and for tear-offs.

So I'm not convinced that allowing that sugar for extension methods is more consistent than disallowing it.

We might still want to go ahead (maybe tolerating some minor inconsistencies) if we have some compelling examples. What might they look like?:

We're presumably talking about situations where somebody wants to use instances of some class that they don't own (so they can't just add a `call` method to that class) in a way that resembles the use of a function. This could be because they want to control equality or `toString`, or they want to add some other methods (maybe in order to modify the behavior of the "function"). It won't quite work, because any extra features that they added would be stripped off as soon as this "function" is accessed under a function type (we'd just have a regular function object, torn off that "rich function" object), but as long as they are just calling it, it might work OK.

Are there any compelling examples of this kind of scenario where the "rich function class" is inadvertently suitable for the purpose, and we just want to add that `call` method, and an extension method saves the day?

**Comment by lrhn** [comment]
I believe that consistency here means that any declaration you can do with an instance member, you can do with an extension member instead and get the same behavior. Any exception to this is an exception that users will need to remember. 
We can definitely make such exceptions, but they come at a cost.

We decided that the "call operator" is an instance method named `call`, instead of something like C++'s `operator()`. A `call` getter does not count towards being callable.
That's an exception because `o.m()` works whether `m` is a getter or a method, but `o()` is not just a shorthand for `o.call()`. It's only a shorthand if `o`'s `call` is a method.

It's true that we could extend that restriction to say "only if `call is an *instance* method" (and thereby exclude *extension* methods), and it might not even be much extra overhead for users.

It is, howevre, an orthogonal restriction. We could restrict to only instance members and allow both `call` methods and getters, or we can restrict to only methods and allow both instance and extension methods, or we can do both. The two choices are entirely orthogonal, so our choice along one dimension does not dictate our choice along the other dimension.

For that reason, I think we should consider whether to allow extension `call` methods independently of whether we allow `call` getters (we already decided not to).

For that, I don't think there is any compelling reason *not* to allow `call` extension methods.

Potential bad style is not a *good* reason, as long as you can use the feature in good style. A feature where every usage is definitely bad style *would* be a bad feature. I do not believe this is the case here.

Providing user power is a reason for allowing it. Users might find a use that we haven't thought of.

Technical issues could be an argument against, but I don't see any.

In situations where we use implicit `call` semantics, we have first checked that the value is not a function. We then check whether the static type has a `call` method. If it doesn't, we would now also check whether an extension `call` member applies, and it is a method. That's no different from what we would do if there was an explicit `.call` (except that it must be a method), so the functionality is already there.
(We should do extension conflict resolution first, then reject a non-method, not pre-reject non methods before doing extension conflict resolution).

**Comment by eernstg** [comment]
> we could extend that restriction to say "only if `call` is an _instance_ method"
> (and thereby exclude extension methods),

'Method' very frequently means 'instance method' in the spec, but we shouldn't split hairs about whether the spec already has an opinion about static extension methods. Surely it's better to reach a useful decision, and then adjust the spec and implementations as needed.

But I hear you say that it's at least desirable for consistency to allow an extension method to be the `call` in an `e` --> `e.call` desugaring, and I agree that it does not seem to give rise to any significant technical issues.

**Comment by leafpetersen** [comment]
I'm fairly inclined to allow extensions methods to make something callable by adding a call method.  This seems like a potentially powerful tool for writing DSL based APIs, and we are increasingly in a position where people are trying to tune APIs to look in particular ways.  It feels pretty natural to me to allow this. 

I do think I'm coming down on the other side for implicit tear-offs though.  I'm not a huge fan of implicit tear-offs to start with - we added the feature to minimize the migration cost of disallowing callable objects to inhabit function types, not because we thought it was a great feature on its own.  I don't see the existing feature as broadly useful, not broadly used, so I'm fairly disinclined to double down on it for extension methods.

**Comment by lrhn** [comment]
Good point that we can separate implicit callability and implicit conversion.

If we had defined the call operator as `operator()` instead of the method `call`, would that change how we think about it?
For one, it wouldn't be possible to do an explicit tear-off (until we introduce operator tear-offs). If we need conversion, then we would *need* to allow implicit conversion (but not necessarily *want* it). Now that we have `call` as a method, we can just do explicit tear-off instead.

I guess it would be safe to start out without implicit coercion from extension `call` method to function type. We can always add it later, because the coercion would only apply where it would be a compile-time error without it.

So: Allow invocations to hit extension `call` methods when the value does not have a `call` itself (functions do, classes with `call` do, `dynamic` does because it has everything). Do not allow assignments of a non-callable object to a function type ot check for an extension `call` method.
?

**Comment by leafpetersen** [comment]
SGTM.

**Comment by lrhn** [comment]
OK, I have updated the feature spec.
