### ISSUE TITLE
Should reading of wildcard variables be allowed in the inferred code?

### ISSUE THREAD

**Issue by chloestefantsova** [dart-lang/language#4027]
Consider the following code:

```dart
// File: /tmp/asdf.dart

abstract class A {
  List<T> method<T>();
}

class B extends A {
  method<_>() => [];
}

main() {
  A a = new B();
  print(a.method<int>().runtimeType);
  print(a.method<String>().runtimeType);
}
```

When run with the `wildcard-variables` experiment enabled, it produces the following output:

```
$ xcodebuild/ReleaseX64/dart-sdk/bin/dart --enable-experiment=wildcard-variables /tmp/asdf.dart
List<int>
List<String>
```

Judging by the program behavior, the type argument in the return type of `method` and the type argument of the list literal in its body is inferred to the type variable marked as the wildcard `_`. Indeed, in the Kernel code provided by the CFE on the output, we see that the wildcard variable is renamed into `_#wc0#type`, and the reference to that variable is used both in the return type and in the type argument to the list literal as `self::B::method::_#wc0#type%`.

```
  method method<_#wc0#type extends core::Object? = dynamic>() → core::List<self::B::method::_#wc0#type%>
    return core::_GrowableList::•<self::B::method::_#wc0#type%>(0);
```

_**The question is whether this behavior is expected or not.**_

On the one hand, a wildcard variable is being referenced, and its value is being read. That goes against the intuition about the wildcard variables: that their values should never be read.

On the other hand, the reading of the wildcard variable happens in the inferred code, not in the code written by the programmer. We had similar discrepancy between the inferred and the written code before: the record types could "leak" into the legacy libraries due to inference. By that analogy, it's ok to allow the wildcard variables to be read in the inferred code.

**Comment by kallentu** [comment]
cc @dart-lang/language-team

**Comment by stereotype441** [comment]
My gut feeling is that it's ok for the inferred type to "refer" to the wildcard type variable in this case. The idea of wildcard variables, as I see it, is not that they don't exist, it's that they don't introduce `_` as a name into the lexical scope. Which means that they can still be referred to by inferred code.

**Comment by johnniwinther** [comment]
We can also generate code that reads a wildcard variable:

Consider this:
```Dart
class A {
  void method(int a, int b) {}
}
abstract class B {
  void method(covariant num a, covariant num b);
}
class C extends A implements B {
  void method(_, _);
}
```
for this the CFE will generate a "semi-forwarding stub" for `C.method`:
```Dart
class C extends A implements B {
  void method(_, _) => super.method(_ as int, _ as int);
}
```

**Comment by leafpetersen** [comment]
Yeah, I don't think there's any expectation that wild card variables "don't ever get a value".  We discussed this a bit in the context of covariance checks at one point:
```dart
class A<T> {
  void foo(T _) => 3;
}

void main() {
  A<Object> a = A<int>();
  a.foo("hello"); // Should throw an error
}
```

There is an implied covariance check on the wildcard variable despite the fact that it cannot be referenced, which means using the value.  The inference example feels a little more surprising but in practice I'm not really worried about it.

**Comment by nshahan** [comment]
In general the ability for type inference to introduce code that would otherwise be an error if you typed it yourself feels uncomfortable to me. This wildcard example reminds me of the difficulty introduced by types leaking across the boundary of deferred imports. Inference can introduce the use of a type before calling `.loadLibrary()` but if you wrote the type explicitly yourself it would be a compile time error. 

I see how we got here because the entire idea of the wildcard feature is to make some variables impossible to reference but is it helpful if type inference can introduce those references for you?

**Comment by leafpetersen** [comment]
> I see how we got here because the entire idea of the wildcard feature is to make some variables impossible to reference but is it helpful if type inference can introduce those references for you?

Is it harmful?  The point of wildcard variables is that it is inconvenient to have lexical name clashes for variables that you don't care about (hence the convention of doing things like `(_, __) => null)` in Dart.  I don't think any users care about whether wildcards are actually unused or not.  In that sense, I disagree that the point of the feature is "to make some variables impossible to reference".  The point of the feature is "to allow users to not have to choose a name for variables they don't care about using".

**Comment by nshahan** [comment]
> Is it harmful?
It kind of depends on who you ask, some people think that type inference makes code harder to read because it allows the author to omit type annotations that others find helpful (or repetitive and noisy). The common refrain I hear a lot is that if you are bothered by the lack of type annotations we have tooling in the analyzer and IDE that will tell you the inferred type when you hover over values. Have we settled on what the analyzer shows when a wild card variable appears in an inferred type? In the example that started this thread, what should it show if you hover over the list literal?

I could potentially say that it is harmful if we lose the ability to easily inspect and see some inferred types because they include wild card type variables.

**Comment by lrhn** [comment]
I'm not worried 
You _can_ write obtuse code using unnamed variables, but you can also choose not to. A type variable whose type occurs in the return type of the function isn't one I'd normally make anonymous. You can, but that doesn't mean you should.

If you think of unnamed variables as actually having a _fresh_ private name, then there is nothing surprising going on here.
There are no fresh names, it's more like variable names are all compiled away, and everything is referenced logically. Inference is not a source transformation, it's inserting types, not syntactic type clauses. We add the names back in when we print the types for users, and we may need to be more clever if there was no name on the program source.

It's not that you can't write what type inference does here. You just have to add some things, and one of those things is a name.

So, not worried. Names are just syntactic ways to represent references. The references can exist without a source name.

**Comment by bwilkerson** [comment]
> Have we settled on what the analyzer shows when a wild card variable appears in an inferred type?

I don't think we've discussed it. I suspect that the explicit or implicit assumption was that if we treat it like any other type parameter then that's probably the right answer. That assumption might have been wrong.

> In the example that started this thread, what should it show if you hover over the list literal?

I don't know about 'should', but it currently displays `List<_>`. I'm not sure what a better way to represent the type would be.

**Comment by lrhn** [comment]
I think showing `_` as the "name" of the type is fine. If you want something else, you can give it a name.

If `foo<_, _>();` has a return type of `Map<_, _>` and you don't know which is which ... then don't do that!

It's still inherently a *display* issue. The real type may be `Map<foo::[[typeParameters]]#1, foo::[[typeParameters]]#2>`, and that is the type no matter what name we gave those type parameters in the source. It's all alpha equivalent. (The types are at least **NORM** equivalent, `typedef type<T> = T; void main() => print(type<T Function<T>(T)> == type<R Function<R>(R)>);` prints `true`.)
Source names do not have to exist at runtime at all, and it's better if they don't - debugging aside. (The only place we have visible type variables at runtime are generic function *types*. Any other place where a type variable is in scope, it's also bound.)

So `List<_>` is a representation of the type. It's not wrong. And it may be different from another `List<_>` when the underlying type is 

(So that's, like, my opinion. Treat the type variables as *existing*, but not having an expressible name. Any inference should happen *after* resolution, and refer to the "type introduced by type parameter #​1", not the name that it doesn't have. Which is indistinguishable from having a fresh private name that we never reveal, and we just print `_` instead if asked.)

**Comment by kallentu** [comment]
We seem generally okay with this behaviour from the original post. Will close out the issue now.
Thanks for surfacing this discussion @chloestefantsova
