### ISSUE TITLE
check null value of property nested should be cast not nullable

### ISSUE THREAD

**Issue by bigboss27051** [dart-lang/language#4075]
when I check null property in object in if scope  I using that property in if scope null cast type to not nullable 

```
if(object.firstname != null) {
String firstname = object.firstname;
}

this code error because object.firstname can nullable
````

**Comment by mateusfccp** [comment]
Fields are not promotable[^1], for technical reasons.[^2]

[^1]:(Private fields are promotable in some cases. See [this issue](https://github.com/dart-lang/language/issues/2020)).

[^2]: As far as I know, the main reason is because of field-getter symmetry.

There's a label with many issues regarding this limitation, called [`field-promotion`](https://github.com/dart-lang/language/labels/field-promotion).

Currently, the two workarounds you have for this are:

```dart
final firstname = object.firstname; // Assignining to a local so it can be promoted

if (firstname != null) {
  // firstname is promoted here to non-nullable
}
```

```dart
if (object.firstname case final firstname?) {
  // firstname is introduced here as a non-nullable local
}
```
