### ISSUE TITLE
Static extension methods migration.

### ISSUE THREAD

**Issue by lrhn** [dart-lang/language#408]
For static extension methods (#41), we will introduce the feature in a version of the language after introducing language versioning (#94).

That means that a library cannot declare extension methods until it opts in to a language version which supports extension methods. The syntax is simply not available otherwise.

If a legacy library (one not opted in to the extension method language version) imports a migrated library which declares an extension method, how do the two interact?

* Can the legacy library *use* an extension method: `someObject.foo` where `foo` is an extension method declared by the imported extension `MyExt`.
* Can the legacy library use the *extension* declaration
    * For static members: `MyExt.staticMember`
    * For overrides: `MyExt(object).foo`
* Can the legacy library re-export an extension.

The simplest solution is to say that the legacy library cannot access the extension at all.
Any reference to `MyExt` is considered invalid, just as if there was a name conflict in the import, and extension methods never apply to otherwise invalid invocations.
This is a valid approach.

If the extension can be referenced, if `MyExt` is allowed, then it must mean something to the legacy library. 
Accessing static members should definitely be allowed then, but the extension does not introduce a type, so the legacy library cannot simply see the declaration as a class or mixin declaration. It must understand that it's a new kind of declaration, just one that it cannot write itself. 
If the legacy library *understands* extensions, then they should probably just work completely.
This too is a valid approach. 

I do not believe that there is any reasonable middle ground.
Allowing extension method invocations without overrides leaves the user with half the functionality, and no good way to correct for problems.
Allowing access to static members, but not to the functionality they support, is again half a solution, which may be worse than no access at all, at least in encouraging clever workarounds.

So, either legacy libraries must be oblivious to the existence of static extension members, or they must understand them and be able to use them.
If a legacy library uses a static extension method, then it depends on a library declaring such, and therefore its SDK version dependency is effectively raised to a version supporting extension methods.

Since extension methods are effectively an incremental change to the language, there is no reason to not migrate to the newest language version when they are released. As such, I recommend that we say that extension methods are completely inaccessible to legacy libraries, which will encourage SDK version upgrading.

**Comment by icatalud** [comment]
I believe extension methods should override the behavior of the object even in his original type, at least for functions that are overridden. Or at least they should give this option, like extensionType.wrap(class_instance).

I think Dart is currently missing the option of wrapping/mutating class instances functionality, which would add an incredible amount of versatility to using external libraries. I think that this versatility is one of the main reasons "open languages" like python or JS have been so successful. It would be differentiating factor of Dart in comparison to Java for example.
This is not a desired programming pattern, but rather a necessity when dealing with external libraries and there is a desire to adapt their functionality.

That said, about your questions my opinion is the following:

I agree 100% with your statement that Legacy libraries should not be able to access extension types at all, so no is the answer to all the questions. They are incompatible with those types, however they should call the overridden extension methods in case you allowed wrapping/mutating objects, because this should silently change the object methods (they are “invisible”).

I can write a whole column about why there should be a way to mutate objects, but it has mainly to do with adaptation of external libraries. For protection from “bad patterns” this could be allowed only when dealing with objects coming from external libraries.

In any case, what is your opinion about the issue I posted about private members? #409

**Comment by leafpetersen** [comment]
As discussed offline, either solution satisfies the key constraint that package developers cannot accidentally write code which will silently work on their version of the SDK, but fail on some other version of the SDK.  @lrhn I'm fine with either allowing uses (but not definitions), or disallowing references to the name and not applying extensions.

**Comment by lrhn** [comment]
I've documented the restrictive version now: Extensions do not work unless your library is at a language level which understands them. You cannot declare them. Imported extensions do not work, and referring to their name is a compile-time error.

This ensures that no interaction between extensions methods and any future feature can happen, because no interaction with extension metods is possible at all. 
If we allowed uses of extensions methods, then we might be forced to allow uses of a future feature which interacts with extensions as well, and that may or may not be practically useful without allowing supporting syntax. This is purely specualtive, but disabling the feature completely seems like the safest speculative choice.
