### ISSUE TITLE
Documentation imports and new dependencies

### ISSUE THREAD

**Issue by scheglov** [dart-lang/language#4121]
@bwilkerson, @srawlins and I had a discussion about expanding support for documentation imports in the analyzer.

```dart
/// @docImport 'foo.dart' as foo;
/// @docImport 'bar.dart' as foo;
library;

/// [foo.A]
void f() {}
```

One of the questions that we had is whether it is OK to treat documentation imports are normal imports, specifically as actual dependencies of the current library. Sometimes this might cause changes to the dependencies graph, and including new libraries into the current library cycle. I had a vague recollection that this might change the semantics, but cannot construct anything specific. Something about inferring types and dependencies. But it is quite possible that I mis-remember.

Can the language team please clarify if it is always safe from the semantics point of view to add new libraries to library cycles?

**Comment by bwilkerson** [comment]
@stereotype441 @eernstg

**Comment by lrhn** [comment]
It's safe to have dependencies. It's not safe to have actual imports of it affects the import namespace in any way.

A "library cycle" is not a thing from the language's perspective, it just has a set of libraries, the transitive dependencies of the entry point, and that's the program. 
Every library is on its own from there, getting its own imports from is own import statements, not caring about what's happening downstream in the dependencies.

If the whole program is one dependent cycle, out should still run the same way. 
(Please don't tell me I'm wrong!)

Because of exports, finding the export scopes of all libraries in a cycle may require a fixed point computation, but these are imports, not exports.)

If you treat your doc imports like prefixed imports with fresh prefixes, so there is no name clash, I see no problem.

**Comment by eernstg** [comment]
It is certainly possible to change the semantics of code in a given library if an import is added.

```dart
// --- Library 'lib.dart'.
void foo() => print('Reformatting the hard disk');

// --- Library 'my_library.dart'.
class A { void foo() {/*No harm done here*/}}
class B extends A { late danger = foo(); }
```

If we add an import of 'lib.dart' to 'my_library.dart' using a DartDoc kind of import, and it works exactly like `import 'lib.dart';`, then we will get a new behavior.

@lrhn mentioned that such imports would use fresh import prefixes, but it wasn't obvious to me how that would be enforced. Also, in a large project, it could be a non-trivial task to maintain a large number of import prefixes of this kind if various updates would make such names non-fresh now and then.

Another issue would be that even a fresh import prefix would not prevent imported extensions from being used by regular code in the same library, which could also be an unintended change of the semantics.

I would tend to recommend that the DartDoc related import mechanism should make names available to DartDoc comments only.

**Comment by bwilkerson** [comment]
> I would tend to recommend that the DartDoc related import mechanism should make names available to DartDoc comments only.

We agree, and that's already the way it works.

The question isn't whether adding a doc import can change the semantics of the importing library; we designed it so that it can't. But having a doc import adds a new compilation dependency (by adding another library to the library cycle). The question is whether the addition of such a compilation dependency can impact the semantics of the library.

We're just trying to make sure that we haven't overlooked anything that might cause problems in the future.

**Comment by lrhn** [comment]
The one issue I see is macros. It likely *shouldn't* be a problem, unless a macro is so specialized that it tries to refer to the code that applies it 
```dart
/// This macro is used only by [Foo] of this package,
/// @docImport "package:foo/foo.dart" show Foo;
class MySpecialMacroImpl extends SomethingMacroSomething { ... }
```
where 
```dart
@MySpecialMacro 
class Foo { ... }
```

That *should* cause an error if it's considered a real dependency, because the macro implementation program must not depend on any library that applies the macro.

Inside a single program, having more dependencies that you don't actually refer to, should not cause any differences.
The rules for, fx, promotion of private instance variables are as restrictive as they are, because behavior should not depend on whether some code *exists* elsewhere in the program or not.

Code that is not referenced has no effect outside of the library it's declared in.

**Comment by eernstg** [comment]
> We agree, and that's already the way it works.

OK, then I misread this part of the OP:

>> One of the questions that we had is whether it is OK to treat documentation imports are normal imports

I thought being a normal import would imply "adds imported names to the top-level scope".

But why would a documentation import even be considered to be part of the program during compilation? I'd assume that the CFE could ignore documentation imports completely.

About the effect on the program semantics if a library is imported in this special way (and there are no normal imports of the same library): @lrhn mentioned macros, whose implementation might be able to enumerate all reachable libraries, which would include documentation-imported ones (if they are treated in the same way as normal imports). However, the same consideration would be relevant for all kinds of metaprogramming, such as mirrors or code generation.

**Comment by bwilkerson** [comment]
> I thought being a normal import would imply "adds imported names to the top-level scope".

The key phrase was the following:

> > ... specifically as actual dependencies of the current library.

Documentation imports work like normal imports in terms of name spaces only in the context of documentation comments, and we knew that that couldn't impact the semantics of the code, but they add a dependency between libraries in the same way that normal imports do and we wanted to ensure that the dependencies couldn't impact the semantics of the code.

> But why would a documentation import even be considered to be part of the program during compilation? I'd assume that the CFE could ignore documentation imports completely.

Yes, the CFE can completely ignore documentation imports. It impacts the analyzer because we resolve the `[ ... ]` references in the documentation comments at the same time as we resolve everything else (because most of the scopes are already built at that point).

> ... whose implementation might be able to enumerate all reachable libraries ...

I don't believe that there's any way for a macro to get any information about the content of a documentation comment (or at least not the way in which the references have been resolved), and I believe that documentation imported libraries won't be returned when a macro asks for the imported libraries.

I also wouldn't expect this to impact mirrors.

Non-macro code generators, however, if they're built on the `analyzer` package, would have access to this information, which is part of why we have to consider documentation imports to add a dependency. Given a library L1 that contains a documentation import of L2, if a code generator is run over L1 to produce a part of that library, then a change to L2 could theoretically change the information that the code generator used to produce the part, necessitating the generator to be run again.

**Comment by eernstg** [comment]
> The key phrase was the following:
>
>>> ... specifically as actual dependencies of the current library.

OK, I think I'll just drop the assumption that documentation imports are normal in any particular sense. 😄

> I believe that documentation imported libraries won't be returned when a macro asks for the imported libraries.

That seems to be the right thing to do.

> I also wouldn't expect this to impact mirrors.

Right, this is consistent with the assumption that the CFE will ignore the documentation imports entirely.

> Non-macro code generators, however, if they're built on the `analyzer` package, would have access to this information, which is part of why we have to consider documentation imports to add a dependency.

Perhaps the documentation imports could be treated as a completely separate property of each library? Any client of the analyzer would then have to use the techniques they are using today in order to inspect the regular imports, and they would need to use a new API in order to get hold of the documentation imports.

I'm just guessing here, but I would assume that documentation related lookups have to be specialized anyway (because, for instance, `[C.foo]` can be looked up even in the case where `foo` is an instance member of `C`), so the requirement that documentation imports must be obtained from a new API might be tolerable.

If this is true then the non-macro code generators could get access to the documentation imports if and only if they actively specify that this as what they need.

**Comment by scheglov** [comment]
> > Non-macro code generators, however, if they're built on the `analyzer` package, would have access to this information, which is part of why we have to consider documentation imports to add a dependency.
> 
> Perhaps the documentation imports could be treated as a completely separate property of each library? Any client of the analyzer would then have to use the techniques they are using today in order to inspect the regular imports, and they would need to use a new API in order to get hold of the documentation imports.

Yes, this is the plan - separate getter for documentation imports, and normal `LibraryElement.libraryImports` will not return them.

> If this is true then the non-macro code generators could get access to the documentation imports if and only if they actively specify that this as what they need.

We were looking into something non-obvious, when the fact of pulling a new library into a library cycle changes the semantics, even though everything else is intact - existing properties that return imports are the same, all scopes are the same, etc.

**Comment by jakemac53** [comment]
> We were looking into something non-obvious, when the fact of pulling a new library into a library cycle changes the semantics, even though everything else is intact - existing properties that return imports are the same, all scopes are the same, etc.

I will propose one - if the presence of a doc comment referencing a top level field would cause that field to be evaluated (to perform inference?), then it could be observable due to the side effects of said evaluation.

However, I don't know if this could ever be visible in a meaningful way to the analyzer, outside of very weird situations like asserts failing in constant constructors (but not idea if analyzer runs those).

**Comment by lrhn** [comment]
Constant evaluation can be a problem. So can referencing unavailable libraries.

It can make sense to reference something declared in a library that is not available on the current platform. Say "This web code works just like \[sleep\] from `dart:io`" and then doc-importing `dart:io` in a web program.
The way the analyzer currently handles imports, I don't think there is any problem importing both `dart:js` and `dart:io`, but it might cause a warning.

Similarly, importing something that's not available can give errors from `bool.fromEnvironment('dart.library.io')` being false in a library that requires it to be true (and which shouldn't be imported if not). That's ... probably a problem anyway, it just spreads through more imports this way.

**Comment by bwilkerson** [comment]
> ... if the presence of a doc comment referencing a top level field would cause that field to be evaluated ...

> Constant evaluation can be a problem.

We don't evaluate any of the names in a documentation reference. The only thing we do is to look the name up in the doc comment scope to determine what it refers to.

> Similarly, importing something that's not available can give errors from bool.fromEnvironment('dart.library.io') being false in a library that requires it to be true (and which shouldn't be imported if not).

We never evaluate any of the `fromEnvironment` constructors no matter where they occur. Our constant evaluation engine has support for a "valid but unknown" value that we use as the value of `fromEnvironment`. But even if we did, as I said above, we don't evaluate anything in a doc reference and nothing else is impacted by doc imports.

**Comment by bwilkerson** [comment]
I think we have our answer, so I'm going to close this. Thanks for the help in thinking this through!
