### ISSUE TITLE
Make flow control treat final vars immutable

### ISSUE THREAD

**Issue by dmitry-fbm** [dart-lang/language#4131]
Here is sample code:

```dart
@immutable
class C {
  final int? i;
  const C({required this.i});
}

void f(C c) {
  late int i;
  if (c.i != null) {
    i = c.i;
  }
}
```
Despite the var `i` is final, the container class is declared `@immutable` and there is explicit `if (c.i != null)` check, the IDE considers this code invalid:
![image](https://github.com/user-attachments/assets/d2c36e16-0bd2-4ea8-8648-c35fc2bee2a3)
Wouldn't it be possible to promote nullable vars to non-nullable implicitly inside the `if` block in such cases?

**Comment by hydro63** [comment]
pretty sure that's an edgecase that hasn't been considered. AFAIK, the reason why members are not promoted is because of possible sideeffects that can occur. Still, i don't see a reason not to promote it, since the immutability means that there are no sideeffects, even when working in async.

**Comment by tatumizer** [comment]
`@immutable` is out of play in this example. You have declared the variable `final` anyway.
The usual reason for non-promotion is that you can create a subclass D where `i` is a getter that (sometimes) returns different values on each invocation.
You could hope that if you declare C as `final class C`, then the compiler's concerns about possible override might be addressed, but no. You can still create a subclass in the same library. Sure, the compiler could see that there's no such thing, but even in this case, the promotion would be brittle. 
AFAIK, there's no modifier that says: I will never subclass C, even in this library 
This is my speculation (based on the previous discussions on similar topics).

**Comment by hydro63** [comment]
> If you try to subclass C and make i non-final there, the compiler will produce a warning, but not an error.

I didn't consider this. Perhaps we should allow promoting in sealed classes, where non of the subclasses change the mutability of the variable. I know that currently this code doesn't work (tested in dartpad):
```dart
sealed class SuperClass {
  final int? i;
  const SuperClass(this.i);
}

class ChildClass extends SuperClass {
  int? b;
  ChildClass(super.i, this.b);
}

void f(SuperClass c) {
  late int i;
  if (c.i != null) {
    i = c.i;
  }
}
```
AFAIK, `sealed` class prevents this problem by having information about every class, compiler would know when sideeffects can occur and when not. Still, i think it is feasable to do it for `sealed` classes.

**Comment by tatumizer** [comment]
> Still, i think it is feasable to do it for sealed classes.

Normally, similar requests (to implement something based on "holistic" knowledge) were rejected because such logic would be brittle (if subclasses don't exist today, it doesn't mean they won't emerge tomorrow).

For this promotion to become feasible, `immutable` should become a language feature (as opposed to an annotation)

**Comment by lrhn** [comment]
What @tatumizer says.
If the language allows a final variable to be promoted, but doesn't allow a getter to be promoted (which it clearly shouldn't), then whether a declaration is one or the other becomes part of the API contract. 
That breaks variable/getter symmetry, and prevents an author from switching between the two, even though they never _intended_ to make a promise.

That's why anything that would treat the two differently must be opt-in. 

Being a final class only affects the current program. We can know that nobody overrides the variable with something non-stable, but we still don't know if the author intended to promise that the property will always be stable.

**Comment by dmitry-fbm** [comment]
> For this promotion to become feasible, immutable should become a language feature (as opposed to an annotation)
@tatumizer hope this will come true one day.

**Comment by dmitry-fbm** [comment]
> where non of the subclasses change the mutability of the variable.

@hydro63 I'd say, this has to be default behavior even for non-sealed. At least, subclasses can be allowed to introduce immutability, but not ignore it.
