### ISSUE TITLE
Specify recommended dart:mirrors behaviour for extension methods 

### ISSUE THREAD

**Issue by mraleph** [dart-lang/language#421]
This is a request to specify how (and if) extensions and their methods are visible through `dart:mirrors`. 

This does not have to be a normative specification, but can simply be a recommendation for implementations.

**Comment by lrhn** [comment]
*This will be a suggestion, but people actually using `dart:mirrors` are invited to chip in!*

Dart mirrors straddle the gap between run-time object mirrors and declaration mirrors.
Since extensions have no run-time presence, they are neither objects nor types, I guess they should only be available as declaration mirrors.

Also, since the name does not have any value or type associated, it's not possible to `reflect(extension)` or `reflectClass(extension)`. So, there can be no direct access to the extension, you have to find the declaring library and look through the declarations, or tear off an extension method, reflect on that, and traverse the mirrors to the declaring `ExtensionMirror`.

Reflecting on such a torn off closure would give a `ClosureMirror` and the `function` of that would give a `FunctionMirror`. (Maybe `FunctionMirror` should get an `isExtension` flag to distinguish instance methods from extension methods). The `owner` of that will then have to be an `ExtensionMirror` instead of a `ClassMirror`.

Extension declarations look like a class declarations. They have static and instance members (no constructors, no fields, but that's a proper subset). As such, the API for an `ExtensionMirror` should likely mimic a subset of the `ClassMirror` API. It is not a `TypeMirror`, though. It *is* an `ObjectMirror` because you can invoke static members on it.

So, perhaps an API for `ExtensionMirror` could look like:
```dart
abstract class ExtensionMirror implements DeclarationMirror, ObjectMirror {
  Map<Symbol, DeclarationMirror> get declarations;                         
  Map<Symbol, MethodMirror>      get instanceMembers;                 
  TypeMirror                     get onType;           
  Map<Symbol, MethodMirror>      get staticMembers;                   
  List<TypeVariableMirror>       get typeVariables;                  

  // From DeclarationMirror:
  bool                           get isPrivate;  
  bool                           get isTopLevel; 
  SourceLocation                 get location;             
  List<InstanceMirror>           get metadata;                   
  DeclarationMirror              get owner;                   
  Symbol                         get qualifiedName;
  Symbol                         get simpleName;   

  // From ObjectMirror:
  dynamic                        delegate(Invocation invocation);
  InstanceMirror                 getField(Symbol fieldName);
  InstanceMirror                 invoke(Symbol memberName, List positionalArguments, 
                                       [Map<Symbol, dynamic> namedArguments]);
  InstanceMirror                 setField(Symbol fieldName, Object value);
}
```
An extension can be unnamed, and then it might not have a `simpleName` or `qualifiedName`. The system is free to introduce a fresh private name for unnamed extensions if that makes things easier.

That's a completely naïve design, simply based on making every part of the declaration available.

**Comment by mit-mit** [comment]
Issue moved to [dart-lang/sdk #37433](https://github.com/dart-lang/sdk/issues/37433) via [**ZenHub**](https://www.zenhub.com/)
