### ISSUE TITLE
How does type object equality work in mixed opted in/opted out NNBD code?

### ISSUE THREAD

**Issue by leafpetersen** [dart-lang/language#428]
How do we deal with equality on type objects (that is, the result of calling `.runtimeType`, or of evaluating a type literal) in a mixed NNBD world?  Suppose I have the following:

```dart
// opted in
Map<Type, int> registry = {};
void registerSomethings() {
  registry[List] = 3;
}

// opted out
void main() {
  print(registry[List]);
}
```

What should that code print?  `null`?  Or `3`?  Note that the lookup in opted out code will, by default, be looking up `List<dynamic*>*`, whereas the code inserting into the registry is inserting `List<dynamic>`.   If we want opting in to be non-breaking to code like this, I think we need to erase all of the `*`s in runtime type objects when not doing strong checking. 

A question is whether we should also do so for `?`.  That is, should the following work?

```dart
// opted in
Type typeOf<T>() => T;
Map<Type, int> registry = {};
void registerSomethings() {
  registry[typeOf<List<int?>>] = 3;
}

// opted out
void main() {
  print(registry[List]);
}
```

It seems like the most forgiving thing to do would be to erase all `*` and `?` annotations from type literal representations when not in strong checking mode.

cc @rakudrama

**Comment by eernstg** [comment]
If we go with a fine-grained equality then we may have bugs like "crashing because of a failed lookup", as a variant of printing `null` at `print(registry[List]);`.

If we go with a coarse-grained equality (anything up to recursively erasing both `?` and `*` before comparing) then we may be more likely to get subtle bugs based on confusing several objects that ought to be kept apart. E.g., we might accidentally overwrite bindings in a `Map` or entries in a `registry`, and then receive and use the wrong object. We might for instance call a wrong callback in response to some event.

Presumably we will have a semantics where `int != int?` and the end of this process, so the code will need to work with a fine-grained semantics by then.

Hence, I tend to think that a fine-grained equality will often cause crashes when misapplied, and a coarse-grained equality could be more prone to cause subtle bugs. On top of that, a fine-grained equality will prepare the code for the approach which _must_ be used when NNBD has been fully deployed. So it is probably better to have a fine-grained than a coarse-grained reified-type equality.

Legacy types (e.g., `int*`) could be considered equal to both variants (`int` and `int?`). But that would give equality some really weird properties so it might be safer to make them equal to the nullable variant, only.

**Comment by leafpetersen** [comment]
Closing this in favor of https://github.com/dart-lang/language/issues/444
