### ISSUE TITLE
Static extension methods: wrong example

### ISSUE THREAD

**Issue by sgrekhov** [dart-lang/language#435]
Please see https://github.com/dart-lang/language/blob/master/accepted/future-releases/static-extension-methods/feature-specification.md#scope
There is an example
```dart
import "all.dart";  // exposes extensions `Foo`, `Bar` and `Baz`.
import "bar.dart";  // exposes another extension named `Bar`.
import "bar.dart" as b;  // Also import with prefix.
class Foo {}
main() {
  Foo();  // refers to class declartion.
  Baz("ok").baz();  // Explicit reference to `Baz` extension.
  Bar("ok").bar();  // *Compile-time error*, `Bar` name has conflict.
  b.Bar("ok").bar();  // Valid explicit reference to `Bar` from bar.dart.
}
```
If `Bar` and `Baz` are extension names, then `Baz("ok")` is wrong, because you cannot declare constructor in extension. So, seems, extension `Baz` introduces method `baz()` on class `Baz` defined somewhere else. But it is not said in the example that 
`import "all.dart";  // exposes extensions Foo, Bar,  Baz and the class with the same name Baz`

So, please, change the example to be more clear

**Comment by eernstg** [comment]
`Baz("ok")` is a synthetic constructor invocation](https://github.com/dart-lang/language/blob/master/accepted/future-releases/static-extension-methods/feature-specification.md#overriding-access), which does not denote an invocation of any declared constructor and does not run any code. It is just there in order to explicitly disambiguate the invocation of `baz` as an invocation of the extension method of that name declared by the extension `Baz`.

**Comment by sgrekhov** [comment]
@eernstg , thank you for clarification.  I haven't reached this part the spec yet. Sorry for false alarm, no issue here
