### ISSUE TITLE
Static extension methods: static members of the extensions with ommited names

### ISSUE THREAD

**Issue by sgrekhov** [dart-lang/language#452]
Documentation [link](https://github.com/dart-lang/language/blob/master/accepted/future-releases/static-extension-methods/feature-specification.md) 
```dart
extension<T> on List<T> {
  static void quadruple() { ... }
}
```
This case is not described in the specification. Accorling to the [spec](https://github.com/dart-lang/language/blob/master/accepted/future-releases/static-extension-methods/feature-specification.md#static-members-and-member-resolution)

> Static member declarations in the extension declaration can be accessed the same way as static members of a class or mixin declaration: By prefixing with the extension's name.

But the extension above has no name, so static member became a dead code. So, may be it makes sense to produce a compile error here?

**Comment by rrousselGit** [comment]
Isn't it s'oppose to be used this way? 

```dart
List.quadruple();
```

**Comment by sgrekhov** [comment]
An example taken from the [specification](https://github.com/dart-lang/language/blob/master/accepted/future-releases/static-extension-methods/feature-specification.md#static-members-and-member-resolution)

```dart
extension MySmart on Object {
  smart() => smartHelper(this);  // valid
  static smartHelper(Object o) { ... }
}
...
  MySmart.smartHelper(someObject);  // valid
```

**Comment by lrhn** [comment]
The specification states that you can omit the name of an extension declaration, and that is equivalent to giving the extension a fresh private name.
Effectively nobody can refer to the extension by name, which means that you also cannot access any static member from the outside.

You can access the members from *inside* the extension declaration, using an unqualified name:
```dart
extension<T> on List<T> {
  void foo() { ... helper(this, true); ... }
  void bar() { ... helper(this, false); ... }
  static helper<T>(List<T>list, bool fooNotBar) { ... }
```
Here the `helper` invocations inside the extension methods work because they refer to the static member in their lexical scope by unqualified name.
There is no way to refer to the static helper as `something.helper` because the name of the extension is not available to the program. (The name exists and is private, so the extension is also not exported by the declaring library).
@rrousselGit No, there is no way to extend class declarations with static methods.

**Comment by sgrekhov** [comment]
@lrhn, thank you. I missed that static methods of the unnamed extension can be accessed inside an extension. No issue then
