### ISSUE TITLE
Errors and warnings around `Never`

### ISSUE THREAD

**Issue by leafpetersen** [dart-lang/language#455]
The current specification makes it an error to call a method, setter, or getter on an expression of type `Never`, or to apply an expression of type `Never`.   Using a value of type `Never` in other expression positions is permitted. 

Partially in response to questions from @MichaelRFairhurst around how to interpret various operators with respect to the above, we spent some time discussing this in person.  This issue is intended to capture that discussion, and provide a place for us to iterate to a resolution.

### Non-receiver expressions of type `Never`

There seems to be consensus that allowing non-receiver expressions of type `Never` is useful, at least during development.  Examples:

```dart
int f(int x) => throw “Unimplemented”
require(a) || throw "Requirement not met";
int x = a ?? throw "Unexpected Null";
```

### Receiver expressions of type `Never`

It is less clear whether it is useful to allow receivers of type `Never`.  There are no semantic issues with allowing it: an expression of type `Never` will never complete to a value, so any operation on it is fine.    So should we allow:

```dart
f(throw “Unimplemented”)
(throw "Unimplemented").getter
(throw "Unimplemented").foo(a)
(throw "Unimplemented")(3) 
(throw "Unimplemented").z = 2
(throw "Unimplemented").map(.....) 
```

It's less clear that these are useful, and there's some concern that this could hide misuses of an API from the programmer until runtime.  If the programmer incorrectly thinks that an API that returns `Never` actually returns something useful, then they will be permitted to use the value arbitrarily, and only discover the failure at runtime.  

### Operator positions

Dart has various operators, some of which are defined in terms of method calls and some of which are not.  How should we treat all of these?

```dart
(throw "Unimplemented") && a
a && throw “Unimplemented”
a ?? throw "Unimplemented"
throw "Unimplemented" ?? a
(throw "Unimplemented) == a
a == (throw "Unimplemented")
(throw "Unimplemented") + 3
3 + (throw "Unimplemented")
!(throw "Unimplemented")
(throw "Unimplemented")!
(throw "Unimplemented")..foo..bar
Never x = throw "Unimplemented; x++; x+=2
```

Pure operators like `&&` seem most natural to model as "uses as expressions" rather than "uses as receivers".  We could consider distinguishing between unconditional uses and only conditional uses.  That is, we might allow `a && (throw "Unimplemented")` but not `(throw "Unimplemented") && a` since the former might complete but the latter never will.  This could also fall out of reachability warnings (see below).

The `==` operator is a little different, since in the case that neither argument is `null` it eventually bottoms out in a method call on the left operand.  The default interpretation if we disallow receivers of type `Never` but allow expressions of type `Never` is that `Never` as a left operand is disallowed, but `Never` as a right operand is allowed.

Operators like `+` are defined as method calls, so without special casing they would fall under the treatment of receivers when `Never` is the left operand and under the treatment of general expressions when `Never` is the right operand.  The asymmetry is odd, but consistent.

### Unreachable code

A proposal from @munificent is to never issue any warnings directly about `Never`, but instead to do fairly fine grained dead code analysis and warn if an expression contains computation that is dead.  So then we would have something like:

```dart
int f(int x) => throw “Unimplemented”  // Ok
require(a) || throw "Requirement not met"; // Ok, code after this is still reachable
int x = a ?? throw "Unexpected Null"; // Ok, code after this is still reachable
f(throw “Unimplemented”) // Unreachable code warning, since call to `f` is unreachable
(throw "Unimplemented").getter  // Unreachable code warning
// etc
```

From an implementation standpoint, this might require more detailed reachability analysis than we had previously planned on implementing. 

### Behavior in other languages

Kotlin, Typescript and Scala all have some kind of bottom type.  All of them disallow using something of bottom type as a receiver, but allow using something of bottom type as an expression.  In addition, Kotlin gives unreachable code warnings as proposed by @munificent  above.

## Kotlin

Receivers of type `Nothing` give an error.
Using an expression of type `Nothing` is valid, but unreachable code warnings are issued.

```kotlin
fun nn() : Nothing = throw Error("");  
fun i(x : Int) {}
fun nntest() {
    nn() // Ok
    3;  // Unreachable code warning
    i(nn()) // Unreachable code warning
    nn().length() // Unreachable code warning + error on unresolved symbol length
    nn()() // Unreachable code warning + error on application
    nn() == "hello"; // Unreachable code warning
    "hello" == nn() // Unreachable code warning
    "hello" + nn() // Unreachable code warning
    nn() + "hello" // Unreachable code warning + overload resolution error
}
```

## Typescript

No unreachable code warnings.
Receivers of type `Nothing` give an error.
Using an expression of type `Nothing` is valid.

```typescript
function nn() : never { throw Error(""); }  
function i(x : Number) {}
function nntest() {
    nn()
    3; 
    i(nn())  // Ok
    nn().length() // Error
    nn()() // Error
    nn() == "hello"; // Ok
    "hello" == nn() // Ok
    "hello" + nn()  // Ok
    nn() + "hello"  // Ok
}
```

## Scala

```scala
def nn() : Nothing = { throw new Error(""); }  
def i(x : Int) {}
def nntest() {
    nn() // Ok
    i(3);  // Ok
    i(nn()) // Ok
    nn().length() // Unreachable code warning + error on unresolved symbol length
    nn()() // Unreachable code warning + error on application
    nn() == "hello" // Ok
    "hello" == nn() // Ok  
    "hello" + nn() // Ok
    nn() + "hello" // Error
}
```

**Comment by lrhn** [comment]
Instead of just talking about `Never`, we can also say that this applies to "any subtype of `Never`".
That would allow the synthetic types `X & Never` and `X extends Never` to be recognized as being equivalent to `Never`. 

Not sure what to do for `Never*`. It's a subtype of `Never`, but it might terminate with `null`.

**Comment by eernstg** [comment]
We have this **basic issue** again and again, for various _X_: "**We could allow _X_**! It's well-defined what it would do, but it essentially cannot be used for anything meaningful. So should we allow it because someone could find a really useful variant of it, or should we prohibit it because it's better for the community to warn developers when they write things which are likely to be unintended?".

One example is `extension on Never {...}` which is OK, even though it's not likely to be useful; `extension on void {...}` and `extension on dynamic {...}` are OK as well, even though no member access would implicitly resolve to any such extension method. Another example is local variables of type `void`, and yet another one is the type `X & Never` (which would presumably never arise but for promotion to `Never`, where the promoted scope must be dead code). And so on.

In several such cases we have chosen to use a principle that we could describe as **"avoid exceptions"**, allowing the dubious construct: This leaves the language simpler, and someone might still find an absolutely wonderful way to use it.

With that in mind, I'd tend to propose that expressions of type `Never` are not an error (just like everybody else), and receivers of type `Never` are also not an error (and the member access is type checked as if the receiver had had type `dynamic`). Among other things, this allows us to avoid making the distinction between receivers as a syntactic category involving a period (like `.`, `?.`, and `..`) and receivers as a semantic category (such as the left operand of a binary operator); I think that distinction is just an unnecessary source of confusion.

Separately, we can then put in a second line of defense to help developers avoid constructs which are very likely to be bugs: Lints or warnings could flag receivers of type `Never` in general, or they could flag any construct which would imply that some snippet of code is unreachable. This is compatible with the approach taken in Kotlin, TypeScript, and Scala, easing the life for developers who are working with several languages.

In the end, `throw 0` will throw, but evaluation of just about _any_ expression `e` _may_ throw, and we aren't going to give developers any guarantees against throwing completion anyway. So being really strict on "you can't do `(throw 0).length`, it will throw" seems unjustified given that `e.length` may throw for almost any `e`.

If we do this then we'd need to adjust [this part](https://github.com/dart-lang/language/blob/master/accepted/future-releases/nnbd/feature-specification.md#static-errors) of the NNBD feature spec:

> It is an error to call a method, setter, or getter on a receiver
> of static type `Never` (including via a null aware operator).

**Comment by eernstg** [comment]
Note the proposal to make `extension E on Never {...}` an error in #716.

**Comment by lrhn** [comment]
I'm still no convinced either way.

The `Never` type is deliberately designed to be assignable to every type. If we don't want it to be that, we should not make it so in the type system. It means that you can override a method returning `int` with one returning `Never`. That's the only real case where an expression of type `Never` can occur without us knowing it&mdash;when it's seen as a supertype.

In all other places where `Never` occurs, any code that would execute after that is obviously dead code. We should warn about dead code, but I'm not sure it's worth making it a compile-time error. That easily gets annoying while developing.

If we don't disallow dead code, then we need to give it a static semantics.
Just using `Never` for arguments is easy. For a receiver context, where we invoke members of the `Never`-typed expression, we have to decide no the type of that invocation (accept any operands/arguments and return type is `Never` would be the obvious default). 
If we get the dead-code warning, that should be sufficient.

So, my vote is on dead-code warnings, no errors, no reference to `Never` as being the problem. The `Never` is fine, it's the code after it that is useless.

**Comment by munificent** [comment]
> So, my vote is on dead-code warnings, no errors, no reference to `Never` as being the problem. The `Never` is fine, it's the code after it that is useless.

+1!

**Comment by eernstg** [comment]
> +1!

+1! ;-)

**Comment by MichaelRFairhurst** [comment]
+1!

**Comment by leafpetersen** [comment]
This has landed.
