### ISSUE TITLE
Type equality with NNBD legacy types

### ISSUE THREAD

**Issue by lrhn** [dart-lang/language#464]
Like #444 states, legacy types like `int*` are both equal to and not the same as `int` and `int?`.

How does that affect generic function bounds. Can
```dart
T Function<T extends Object>(T);
```
be the type of
```dart
T id<T extends Object>(T value) => value;
```
if one is written in a legacy library and the other in an NNBD library?

We require type parameter bounds to be "the same" for function subtyping, but a legacy `Object*` bound should be satisfiable by `Object`, `Object?` and `Object*`.
Likewise an `Object` (non-nullable) bound should be satisfiable by both `Object` and `Object*`,
and `Object?` by both `Object?` and `Object*`.

Is this an issue for our typing algorithms, or will it just work because bound-checking is done by mutual subtype checks?

**Comment by eernstg** [comment]
I believe that [the subtyping.md feature spec with updates for NNBD](https://github.com/dart-lang/language/blob/master/resources/type-system/subtyping.md) deals with relationships among types (presumably, this issue is not about instances of `Type`, it's about types at the language level).

With respect to bounds in generic function types, I'd prefer if we switch to use mutual subtyping for consistency.

The language specification relies on alpha-equivalence, i.e., it requires the same type up to renaming of type variables, but explicitly notes that terms like `C` and `p.C` can denote the same type. In 'subtyping.md' the requirement is `===` among the bounds (which means 'the two types are structurally equal up to renaming of bound type variables, and equating all top types'). So that's again alpha-equivalence.

But the analyzer and dart2js use mutual subtyping, at least in some cases:

```dart
main() {
  Function<X extends Object>() f1;
  Function<X extends dynamic>() f2;
  f1 = f2; // OK!
}
```

So I think we're in a good position to switch to mutual subtyping for bounds. It's not a soundness problem (given that we have soundness, i.e., full opt-in + strict checks), and it may well be non-breaking.

**Comment by leafpetersen** [comment]
This has been specified and tests have landed.
