### ISSUE TITLE
How should flow analysis based type promotion treat back edges?

### ISSUE THREAD

**Issue by leafpetersen** [dart-lang/language#474]
Consider the following program:

```dart
void test(Object x) {
  if (x is int) {
    while (x >= 0) { // #0
       if (x.isEven) { //#1
       }
       x = "hello"; //#2
    }
  }
}
```

In Paul's proposal, the back edge to the loop header in this example causes all variables assigned in the loop (including `x`) to be reset to their declared types, so `#0` and `#1` would be errors, but `#2` would not.  Is this really the behavior we want/need?  It seems to me to be valid instead to just disable demotion for the duration of the loop.  Any promotions that happen in the loop will only allow assignments that are still valid under the initial assumptions of the loop, since they will only promote to subtypes.  However, a demotion can of course violate the initial assumptions of the loop.  If we did this, then `#2` becomes the error, but the other two are allowed. 

Is this reasonable?  Desirable?  Are there places where this gets too unexpected?

cc @lrhn @johnniwinther @stereotype441 @munificent @eernstg

**Comment by stereotype441** [comment]
My concern with disabling demotion is that there are code patterns where demotion is really what the user wants, they just don't necessarily want the demotion to cover the entire body of the loop.  If we prohibit demotion it's not obvious how the user can fix their code.  For example:

```dart
class ListNode {
  ListNode? next;
  int value;
}
void f(ListNode? node) {
  if (node != null) { // (1)
    int total = node.value;
    while (true) { // (2)
      node = node.next; // (3)
      if (node == null) break; // (4)
      total += node.value;
    }
  }
}
```
(1) promotes `node`'s type from `ListNode?` to `ListNode`.  In an ideal world (where promotion iterates to a fixed point), (3) would demote, (4) would re-promote, and then a fixed point would be reached because the type has been re-promoted by the time the back edge is reached.  Unfortunately, iterating to a fixed point probably isn't feasible for reasons we've discussed previously.

Under my proposal, the assignment to `node` at (3) causes it to be demoted back to `ListNode?` at (2), which gives almost the same analysis result as the fixed point analysis would, except that read of `node` at (3) is no longer promoted to non-nullable.  So to avoid an error, the user needs to do `node = node!.next;`.  That's annoying, but it's a small change, and it's a change the migration tool should be able to do automatically.  If the user really cares about the performance hit of the `!`, they are welcome to unroll the loop slightly, e.g.:
```dart
void f(ListNode? node) {
  if (node != null) {
    int total = node.value;
    node = node.next;
    while (node != null) {
      total += node.value;
      node = node.next;
    }
  }
}
```
But honestly I think it will be very rare than anyone cares.

If instead we disable the demotion, then the error at (3) is "you can't assign int? to int", and both the user and the migration tool will be tempted to fix it by changing it to `node = node.next!` (which is definitely *not* a correct migration).  To do a correct migration the user would either be forced to unroll the loop as above, or make some other clumsy workaround like this:
```dart
void f(ListNode? node) {
  if (node != null) { // (1)
    int total = node.value;
    ListNode? node2 = node;
    while (true) { // (2)
      node2 = node2!.next; // (3)
      if (node2 == null) break;
      total += node2.value;
    }
  }
}
```
I don't really like how this looks, and I'm pretty confident that the migration tool won't be smart enough to suggest fixes like this.  Which means that if we disable demotions in loops, code patterns like this would need to be manually migrated.

**Comment by leafpetersen** [comment]
Closing this as not intended.
