### ISSUE TITLE
instance variable masked by global variable

### ISSUE THREAD

**Issue by trinarytree** [dart-lang/language#476]
it's possible for an instance variable to be masked by a global variable, which isn't expected.  this can happen when the instance variable is inherited from the base class.  here's a toy example:

```dart
String x = 'global var';

class A {
  String x = 'instance var';
  
  String f() => x;
}

class B extends A {
  @override
  String f() => x; // is this the global x or the instance x?
}

void main() {
  print(A().f()); // 'instance var'.  expected.
  print(B().f()); // 'global var'.  wtf.
}
```
the same behavior happens when the outer x is imported from another library.

i'm not certain this is a "bug" - maybe the spec says this is what should happen.  but is it the right thing to do?  i would have expected global vars (especially imported ones) to have lower priority than anything else, otherwise, importing a library could break existing code without so much as an analyzer warning about a name conflict.  (and yes, this happened in my project)

playing my own devil's advocate, if the semantics were flipped so that instance vars took precedence, it would be possible to break code by adding to the base class a new instance var that masked some global var you were already using.  but this seems like a rarer case since you're usually more intimately familiar with the classes you are extending than with every symbol of every library you are importing.

Dart VM version: 2.4.0 (Wed Jun 19 11:53:45 2019 +0200) on "macos_x64"

**Comment by munificent** [comment]
> it's possible for an instance variable to be masked by a global variable, which isn't expected. this can happen when the instance variable is inherited from the base class.

That's correct. Name resolution on a bare identifier inside a method body goes:

1. Look for local variable inside method body.
2. Look for member on surrounding class.
3. Look for top level variable or function in library where class is defined.
4. Look for inherited member.

>  it would be possible to break code by adding to the base class a new instance var that masked some global var you were already using. 

Right. And, in particular, if this did happen, you would have little recourse to resolve the issue. By making the global scope take priority over the inherited one, you can still get to the inherited name when you want to by using `hide` or `this.`.

This is a hard problem for any language that has a lexical scope surrounding classes. The identifier really is ambiguous and there's no perfect answer for which path to walk first. Dart picked the above resolution order and it mostly seems to work OK. Either way, it's a settled part of the language and would be significantly breaking to change it at this point.

**Comment by trinarytree** [comment]
thanks for the response, bob.
you said that if priorities 3 and 4 were reversed and the base class added a new instance var that masked a global "you would have little recourse to resolve the issue".
is this true?  why couldn't you just use a named import to retain access to the global?:
```dart
import 'foo.dart' as foo;
```

**Comment by munificent** [comment]
> is this true? why couldn't you just use a named import to retain access to the global?:

Good point! :)

Either way, the language has to pick one or the other and Dart already picked.

**Comment by jamesderlin** [comment]
> That's correct. Name resolution on a bare identifier inside a method body goes:
> 
>     1. Look for local variable inside method body.
> 
>     2. Look for member on surrounding class.
> 
>     3. Look for top level variable or function in library where class is defined.
> 
>     4. Look for inherited member.

The behavior I observe (with Dart 2.10.1) is that step 3 seems to look for a top-level symbol in scope, not just in the library (or even package) where the class is defined.  Is that right?  That seems dangerous and surprising since a library that I import could add a global that coincidentally collides with an inherited member in my class hierarchy.  If the types happen to be compatible, that would silently(!) break name resolution in my class hierarchy.  Attempting to be defensive by pre-emptively using `this.x` in `B` would trigger the `unnecessary_this` lint.

I realize that the ship has sailed, but IMO preferring the inherited member over the global would have been a safer option.

**Comment by munificent** [comment]
> is that step 3 seems to look for any top-level symbol, not just in the library (or even package) where the class is defined. Is that right? 

It looks for any top-level symbol *that you have imported into your library.*

> That seems dangerous and surprising since a library that I import could add a global that coincidentally collides with an inherited member in my class hierarchy.

If we *didn't* do this and instead preferred inherited members over lexically surrounding global identifiers, then the opposite danger occurs. A new method in a base class that you inherit from could collide with a top-level variable that you were previously using.

No matter which prioritization you pick, you can get unexpected collisions from changes to code you don't control. By preferring the lexical scope, you at least have an easy solution: you can hide the imported name.

> Attempting to be defensive by pre-emptively using this.x in B would trigger the unnecessary_this lint.

If you really want to be defensive, you can use `show` or prefixes on every library you import. But, in practice, libraries do not spontaneously change under you. We have a package manager and lockfiles deeply wired into the ecosystem. That means libraries you import only change on you when *you* choose to upgrade them and you can deal with any collisions that occur at that point in time.

> I realize that the ship has sailed

That ship has sailed, reached the New World, discovered tomatoes, brought them back to Italy, invented marinara sauce, and made a pasta bolognese by now.

**Comment by jamesderlin** [comment]
> If we _didn't_ do this and instead preferred inherited members over lexically surrounding global identifiers, then the opposite danger occurs. A new method in a base class that you inherit from could collide with a top-level variable that you were previously using.

I concur with the assessment in https://github.com/dart-lang/language/issues/476#issue-474169771 that the opposite danger would be less bad.  You'd have to worry about names introduced only in the class hierarchy, much of which is often under your own control.  In contrast, with the current system, you have to worry about names introduced in *any* imported library (without `as`/`show`/`hide`), of which there usually are many that are not under your control.  The scope of the second situation seems larger to me than that of the first.

> No matter which prioritization you pick, you can get unexpected collisions from changes to code you don't control. By preferring the lexical scope, you at least have an easy solution: you can hide the imported name.

With the opposite choice, there are easy workarounds too.  In addition to `import` trick from https://github.com/dart-lang/language/issues/476#issuecomment-516171644, you also could disambiguate by adding another reference:

```dart
var _theGlobalX = x;

class B extends A {
  @override
  String f() => _theGlobalX;
}
```

> If you really want to be defensive, you can use `show` or prefixes on every library you import. 

Using `show` for every symbol eventually would turn into a maintenance nightmare.  However, using `as` seems like a reasonable defensive approach. (I think this issue reinforces my belief that `import`s typically should use `as`.)

> But, in practice, libraries do not spontaneously change under you. We have a package manager and lockfiles deeply wired into the ecosystem. That means libraries you import only change on you when _you_ choose to upgrade them and you can deal with any collisions that occur at that point in time.

That's nice in theory, but I'm skeptical if that works in practice.  When updating my dependencies, I don't personally inspect all of their diffs.  Dealing with collisions assumes that you're actually aware of those collisions, but under the right circumstances, a collision could result in a silent failure where the program (perhaps subtly) misbehaves at runtime.

I agree that either choice can break code and potentially be terrible.  How about a third terrible option of splitting the baby in half:  if there's name collision between a global variable and an inherited name, *fail*. (Or since we're probably not willing to make that intentionally breaking change, maybe the analyzer could lint that.)

**Comment by munificent** [comment]
> That's nice in theory, but I'm skeptical if that works in practice. 

I think we have good empirical evidence for this. Dart has had this name resolution rule forever, most users don't use prefixes or `show` on imports (around 90% of imports were unrestricted last I checked), and yet we rarely hear from users that problems occur.

> When updating my dependencies, I don't personally inspect all of their diffs.

That's OK. Collisions in practice are rare.

> under the right circumstances, a collision could result in a silent failure where the program (perhaps subtly) misbehaves at runtime.

Sure. But by that same token, a single pub upgrade could give you new versions of *two* packages, one of which removed an identifier you were importing and the other of which added the same identifier but with a different type that was statically compatible but failed at runtime. In practice cases like this almost never seem to occur.

> How about a third terrible option of splitting the baby in half: if there's name collision between a global variable and an inherited name, fail. 

That means that adding *either* a top level variable or an instance variable is now a potentially breaking change to users, which is strictly worse.

My experience is that many programmers get really worried about the *potential* for name collisions. That want a hermetic system that with a mathematical proof that unintended collisions cannot occur and feel any system less than that is doomed to failure. I'm sympathetic to that mindset. But designing a system that works that way without significantly harming usability is *really* hard. What we've found is that we can give users a much more usable system that *theoretically* allows name collisions but identifiers are generally unique enough that actual collisions almost never happen.

**Comment by jamesderlin** [comment]
Anecdotally, I *did* run into this.  It was very confusing when it happened.  In my case, I was fortunate that:
1. Tests provided good coverage and caught the change in behavior.
2. The global name was a getter that in the testing environment attempted to dereference a null pointer.  Were it not for this, it would have been much harder for me to tell that the global name was being used instead of the inherited one.

It also was confusing because I'm used to C++, which made the opposite choice (possibly because it has the `::` scope resolution operator to allow explicitly choosing the global version of a name).

> > under the right circumstances, a collision could result in a silent failure where the program (perhaps subtly) misbehaves at runtime.
> 
> Sure. But by that same token, a single pub upgrade could give you new versions of _two_ packages, one of which removed an identifier you were importing and the other of which added the same identifier but with a different type that was statically compatible but failed at runtime. In practice cases like this almost never seem to occur.

Yes, that's true, but I think that scenario would be orders of magnitude more rare: it'd require a coincidental change in multiple packages, and a client would need bad timing for the breakage to occur silently.

> > How about a third terrible option of splitting the baby in half: if there's name collision between a global variable and an inherited name, fail.
> 
> That means that adding _either_ a top level variable or an instance variable is now a potentially breaking change to users, which is strictly worse.

I personally think that hard breakage is better than silent misbehavior.   I agree that this is a rare situation that requires a name collision *and * matching types.  But since this is rare, causing those situations to break would be rare too.

But as I said, if we're not willing to introduce breakage, would you be opposed to a lint that detects potentially ambiguous cases?  I don't think that the workarounds for explicitly choosing the global name (or just adding an `// ignore` comment) are too onerous to hurt usability too much.  My main concern is less that such cases could happen; it's that when they do happen, they can be hard to diagnose.

**Comment by munificent** [comment]
> But as I said, if we're not willing to introduce breakage, would you be opposed to a lint that detects potentially ambiguous cases? 

I'm probably not the right person to ask about lints. And I don't know if we have any data on how often this lint would be useful and/or have false positives.

> or just adding an // ignore comment

Personally, I'm strongly opposed to lints with false positives. I don't want to train users to `// ignore` them because then they'll start ignoring true positives too.
