### ISSUE TITLE
Can a static method in an extension be named `toString`?

### ISSUE THREAD

**Issue by eernstg** [dart-lang/language#479]
A static method in a class cannot have a basename which is also the basename of an instance method in the interface of `Object` (such as `toString` and `hashCode`), cf. [this text](https://github.com/dart-lang/language/blob/54c7e33580df7d43b98ad30022c630a7c5b2acf8/specification/dartLangSpec.tex#L3814). So there's no question that it is an error for a static method in a class.

However, it is not strictly necessary to make it an error to have such declarations in an `extension` declaration (because it does not have any mechanisms resembling the inheritance from `Object` that every class is subject to). Similarly, it is allowed to have a local function and a library function with such names, and they may "capture" any occurrences of `toString()` in the body of a class, based on standard scope resolution rules in Dart (so we already "allow dangerous/messy things" in this area).

The feature spec on static extension methods has the following:

> The member declarations [of an extension] can be any non-abstract static or
> instance member declaration except for instance variables and
> constructors, and they cannot have the same name as a member
> declared by `Object`

which makes it slightly ambiguous whether the error applies to instance methods only, or to both instance methods and static methods.

I'd suggest that we make it an error, in part because an `extension` declaration resembles a class in several ways already, and in part because we might want to consider similar mechanisms which are even more similar to classes, and the ability to have these extension methods is unlikely to be helpful.

[Edit: deleted wrong claim about how/where such methods could be invoked.]

WDYT @lrhn, @leafpetersen, @munificent?

**Comment by bwilkerson** [comment]
Note that I'm not actually arguing either way on this issue, just adding a couple of thoughts.

> ... an extension declaration resembles a class in several ways already ...

True, but it doesn't define a class, nor does it define an interface, so it is also different from a class in several ways. I think an equally strong argument could be made for making them as distinct from classes as possible in order to discourage users from thinking that they _are_ classes.

> ... the ability to have these extension methods is unlikely to be helpful (the instance methods will _always_ win for invocations outside the extension itself).

The only way to invoke a static method outside the extension is by referencing the name of the extension (`E.m()`), in which case the instance methods wouldn't "win" because they wouldn't even be considered. There's only one choice for how to resolve the method, so it isn't clear that there's any need for the restriction.

**Comment by eernstg** [comment]
> The only way to invoke a static method .. (`E.m()`)

Right, there is no conflict after all, and static extension methods named like members of `Object` could actually be used from anywhere. So the only reason to make them an error is actually an opinionated "we just don't like it".

In similar situations we have made the choice to say that a particular construct is allowed (e.g., extension methods on `Never`), because it is well-defined and someone might come up with a useful way to use it.

**Comment by leafpetersen** [comment]
I believe this was clarified offline: this is not allowed.
