### ISSUE TITLE
Question about dart gc and memory leaks

### ISSUE THREAD

**Issue by jkmpariab** [dart-lang/language#490]
I've just asked this question on stackoverflow ([link](https://stackoverflow.com/questions/57329299/how-garbage-collector-decide-to-collect-a-bunch-of-memory)). no reply yet.
I have a problem on understanding how gc works and how to prevent memory leaks. absolutely i'm a newcomer
say we have following code

```dart
void main() {
  // initialize a Wrapper object
  var wrapper = Wrapper(999999999);

  // now if i set wrapper to null, will underlying _nums become null
  // or what? will gc collect memory of underlying List<int> or i should
  // set _nums to null beforehand to trigger gc to collect memory allocated
  // to _nums and prevent memory leaks
  // wrapper._nums = null;
  wrapper = null;
}

// Its just a wrapper for underlying List<int> object
class Wrapper {
  // Underlying object
  List<int> _nums;
  // Constructor
  Wrapper(int len) {
    // allocate memory to _nums
    _nums = List.generate(l, (i) => i);
  }
}
```
how gc/dart treats in this situation?

**Comment by munificent** [comment]
You do not have to set `_nums` to null.

A [tracing garbage collector](https://en.wikipedia.org/wiki/Tracing_garbage_collection) (which is what Dart, Java, Go, etc. all use), works roughly like this:

1. Start with a list of known reachable objects. These are things like values stored in global variables, and local variables on the stack. They're called the "roots".
2. Mark all of them as "reached".
3. Then for every field in those objects, trace those references and mark all of those objects as reached too.
4. Do step 3 recursively until you've traced through every path that can get you from a known live object to another object.

At the end of this, you'll have a set of every object that can possibly be used by the program. Any object that is *not* in this set is now known to be garbage, and the GC will deallocate them.

So, in your case:

```dart
void main() {
  var wrapper = Wrapper(999999999);
  // 1.
  wrapper = null;
  // 2.
}
```

If a GC happens while the program is at `// 1.` then `wrapper` is a root, so the Wrapper gets marked reachable. Then it traces into that and marks the list referenced by `_num`.

Now, if a GC happens while the program is at `// 2.`, then `wrapper` is still a root, but it doesn't reference anything. The Wrapper does not get marked. The List doesn't get marked either because there are no other paths to it. So both of them will get freed.

Note that setting `wrapper = null` does not mean memory will be freed *right then*. Garbage collectors generally don't run immediately because doing so isn't efficient. They tend to wait awhile so that more garbage can accumulate because that optimizes the total time spent managing memory.

**Comment by jkmpariab** [comment]
@munificent thank you for your in details description. but by these supports from gc, how we can get into memory leaks problem. memory leaks cannot happen in gc languages?

**Comment by munificent** [comment]
> memory leaks won't happen in gc languages?

That's correct.

**Comment by FrankHB** [comment]
> 
> 
> > memory leaks won't happen in gc languages?
> 
> That's correct.

That's certainly incorrect and a popular red herring. [Memory leaks](https://en.wikipedia.org/wiki/Memory_leak) are unneeded resource leaks where the meaning of "unneeded" depends on the intention of the programmers (or even the end-users), which can't be addressed totally by the language semantics implicitly. Tracing garbage collectors are essentially non-deterministic on resource reclamation without hacking by additional explicit resource management primitives. In practice, GC only guarantee unreachable objects will be collected sooner or later, but it has no ability to respond reclamation requests *always in time*. So at this point, a program depending on a global tracing garbage collector *will* always leak once there are memory resources owned by the GC. In most times, users will not feel bad for that because collections are not too late, but it does leak in a few cases and it can't be totally (in deterministic manner) avoided, even in theory. This is the real problem @jkmpariab met here.

In fact, nondeterministic collection to unreachable objects only meets a minimal requirement of leakage avoiding: avoiding the *definite leaks*. More strong mechanisms (with deterministic reclamation) can still leak. For example, stack frame deallocations to release the resource out of the automatic objects in ALGOL-style language leak the frames not needed in tail recursion contexts if the implementation fails to provide the proper tail recursion guarantee. There are even more strict criteria, c.f. [the theory on space efficiency](https://www.researchgate.net/profile/William_Clinger/publication/2728133_Proper_Tail_Recursion_and_Space_Efficiency/links/02e7e53624927461c8000000/Proper-Tail-Recursion-and-Space-Efficiency.pdf). Nevertheless, automatically avoiding non-definite leaks more strict than proper tail recursion can incur significant cost, so they are mostly handled manually and locally in practice (if any).

**Comment by munificent** [comment]
> [Memory leaks](https://en.wikipedia.org/wiki/Memory_leak) are unneeded resource leaks where the meaning of "unneeded" depends on the intention of the programmers (or even the end-users), which can't be addressed totally by the language semantics implicitly.

I'm using "memory leak" in the classic sense of allocated memory you can no longer reach. It has *leaked* because you no longer have a handle to it to deallocate even if you wanted to. This is a memory leak:

```c
void main() {
  void* p = malloc(100);
  p = NULL;
  // Lost ability to free memory allocated on first statement.
}
```

Garbage collected languages (and memory safe languages in general) do not leak memory. Certainly a program may retain objects that it turns out it will not use in the future, but that's true of all programs across all languages. I don't think it illuminates to refer to any object that never gets used in the future to be a "leak". The way you deal with a real memory leak is fundamentally different from how you handle unneeded memory. For the former, you need to go out of your way to *retain* a pointer to the object so that you *can* free it. For the latter, it's mostly a question of how your application is architected.

**Comment by FrankHB** [comment]
@munificent I think I understand things you are talking about. But they don't solve the original problem. Consequently, they *introduce* different problems. Users don't benefit from your reasoning and illustration.

There are even a few more, in practice.

It is true that a tracing GC can make sure all known allocated memory are reachable *immediately after a proper (often full) collection*. Since the collection is allowed to delay, it is not necessarily the case that users must expect *at any time*, even sticking with the classical sense of the leaks. So, defining leaks by the temporal property like reachable is not that useful.

And for a language implementation running on some hosted environment which usually comes with an underlying multitasking resource-sharing operating system, the GC does not own the universe of the system resources. As a component of an ordinary userland application, such a GC will not likely have a fixed hard limit of memory they can consume by default. That means the GC can easily waste system-wide resources unnecessary (regardless to the users' intention) and even interfere other applications on the same system. Users should not be obliged to dig into the details of the resource management, and no applications nor the OS itself can reclaim the resources. From the system-wide view, this must be a kind of leak, and it can't be guaranteed eliminated *in* the language implementation relying on the tracing GC once the language runtime is alive (e.g. as a process or a thread).

All these additional aspects contribute more troubles to the original problem. They can't be solved by garbage collection, both in theory and in practice.

(Nevertheless, the classical sense is still bad for its technical imprecision and overly-loosed guarantees in similar cases.)
