### ISSUE TITLE
Exports and extensions

### ISSUE THREAD

**Issue by bwilkerson** [dart-lang/language#503]
The language specification states (section 18.2 Exports):

> For each entry mapping key k to declaration d in NSn an entry mapping k to d is added to the exported namespace of L unless a top-level declaration with the name k exists in L.

The extension methods proposal states (https://github.com/dart-lang/language/blob/master/accepted/future-releases/static-extension-methods/feature-specification.md#syntax):

> It is a compile-time error to export two declarations, including extensions, with the same name, whether they come from declarations in the library itself or from export declarations (with the usual exception when all but one declaration come from platform libraries).

Is it the case that the extension methods proposal is just being less precise, and that the same rules apply. That is, if a name `E` is declared in the library then there is no conflict with any declaration named `E` in any of the exported libraries?

**Comment by leafpetersen** [comment]
The analyzer and the CFE seem inconsistent about this case for regular declarations.  I filed an issue [here](https://github.com/dart-lang/language/issues/504) to clarify and resolve it.  

My interpretation though (for regular declarations) is that the intent of the specification is that it is not an error.

In either case, I believe that the intent of the extension method specification is that the treatment of the extension names here should the same as for other declarations.

**Comment by eernstg** [comment]
#### Spec PR

I created PR #510 to clarify the spec section on 'Exports'. This change implies that a declaration named _n_ in a library _L_ will shadow all re-exported declarations named _n_, and the latter can't have any conflicts among each other, because we can't see them anyway. Otherwise, if there are conflicts among re-exported names then declarations from non-system libraries shadow declarations from system libraries, and otherwise the conflicts is an error.

---

#### Generalization to cover extensions

If we generalize this approach to cover extensions then we'd need to do more: The feature specification already [says](https://github.com/dart-lang/language/blob/master/accepted/future-releases/static-extension-methods/feature-specification.md#scope) that

> An extension is in scope if the name is shadowed by another declaration

The semantics implied by this rule matches an approach whereby each extension has its declared name `E` as well as a fresh public name as an alias. This means that even in the cases where the declared name cannot be found by standard lookup (say, because the current library imports two libraries, both of which export something named `E`), compiler generated code can still look up the fresh name.

This makes it possible to specify that, say, `e.m()` is resolved as an extension method invocation as `F(e).m()` where `F` is the fresh name of the selected extension. That will allow us to specify that type inference is performed on the explicitly resolved form, as if it had been a constructor invocation (as described [here](https://github.com/dart-lang/language/blob/master/accepted/future-releases/static-extension-methods/feature-specification.md#extension-member-resolution) in the feature spec).

(An extension with a private name would need a fresh private name as well, in order to be able to resolve extension method invocations explicitly in cases where an enclosing declaration, say, a private instance variable, shadows the extension).

This means that we avoid having a completely new concept of "just for extensions, a namespace can somehow have more than one binding for a given name", or "just for the name of an extension, we don't follow the scope rules", because we just treat namespace conflicts involving extensions exactly like all other namespace conflicts.

The disambiguation can also be achieved by introducing imports with a fresh prefix `fp`, in which case `e.m()` would desugar to `fp.E(e).m()`.

---

#### Specifically, exports

If we maintain the rule "treat namespace conflicts involving extensions exactly like all other namespace conflicts" we'd get the following for exports:

If a library _L_ declares an extension with the public name `E` then all re-exports of a declaration named `E` are shadowed, so we export that extension.

If the library scope of a library _L_ does not have any declarations with the public name `E`, it is an error to have multiple re-exported declarations named `E` (extensions or not).

But _if we wish to extend the "magic"_ where extensions are allowed to have clashing names also in an export then we can do this based on fresh names: If `E` is a name which is re-exported by two exports _E1_ and _E2_, denoting two distinct extensions, then we _could_ silently remove `E` from the exported namespaces and allow the fresh names to exist. This would make the following two examples work the same:

```dart
// 'libB.dart'.
import 'lib1.dart';
import 'lib2.dart';
...
```

```dart
// 'libA.dart'.
export 'lib1.dart';
export 'lib2.dart';

// 'libB.dart'.
import 'libA.dart';
...
```

It seems somewhat surprising that this wouldn't work, but it will fail in the case where the import magic resolves a conflict, but the exported namespace can't offer the same feature.

In order to do this we can't use a fresh prefix, because there is no notion of export prefixes (or, alternatively, we could introduce export prefixes).

**Comment by bwilkerson** [comment]
How do these fresh public names interact with combinators? If there is file libA.dart:
```
extension E on Object { ... }
```
and another file libB.dart:
```
import 'libA.dart' hide E;
```
Are the members of E visible because the fresh public name of `E` wasn't hidden?

**Comment by eernstg** [comment]
The generation of a fresh public name for a given extension `E` should be suppressed whenever hide/show clauses have been used to remove access to `E` itself.

Otherwise it would be difficult to disable `` (for imports we'd have to import the relevant library _L_ with a prefix, which might require a lot of other changes and disable implicit resolution of other extensions from _L_). Also, it would surely come as a big surprise if a given invocation `e.m()` is resolved to a member of `E` when `E` has been hidden.

**Comment by eernstg** [comment]
@bwilkerson wrote:
> That is, if a name `E` is declared in the library then there is no conflict
> with any declaration named `E` in any of the exported libraries?

Right, if the current library _L_ has a declaration whose basename is `n` then no declaration whose basename is `n` is re-exported, and no error is raised in case of name clashes among re-exported libraries: Such bindings are removed from the exported namespace of each export directive before we consider name clashes.

The fresh names of extensions are never exported (they are private names), and we create new fresh names ;-) in each library for each extension which is imported and not removed using hide/show.

I believe this means that this issue has been resolved, so I'll close it.

@bwilkerson, please re-open it or create a new one if you think something still needs to be resolved.
