### ISSUE TITLE
Consider updating "language-versioning/feature-specification.md" with build version example

### ISSUE THREAD

**Issue by jonasfj** [dart-lang/language#506]
The example:
```
quiver:../../.pubcache/quiver/1.3.17/lib#dart=2.5.3-dev.2
```
Is very useful, but it might be nice to give an example that highlights the use of escaping, using a "build version" would do this. Example: (`2.5.3-dev.2+1`)
```
quiver:../../.pubcache/quiver/1.3.17/lib#dart=2.5.3-dev.2%2B1
```
It might even be wise to give an example that includes keys that might be introduced in the future.
```
quiver:../../.pubcache/quiver/1.3.17/lib#dart=2.5.3-dev.2%2B1&future_value=ignore_this
```

It might also be useful to reference the spec:
https://url.spec.whatwg.org/#application/x-www-form-urlencoded
(maybe there is a better spec, but wikipedia isn't the most exact source)

Getting this wrong is a problem as `+` will be decoded to space. Similar, if someone was to get decoding wrong that could cause problems.

**Comment by jonasfj** [comment]
I know this just nits, feel free to close... there is probably not many consumers of this document.

**Comment by srawlins** [comment]
CC @jakemac53 who notes that various tools consume `.packages` files, like the build suite of packages. I think this would be good to clarify.

**Comment by jakemac53** [comment]
As I update packages I intend to switch them to use the [package_config](https://pub.dev/packages/package_config) package and I would recommend everybody do so to make sure we all agree on these things now that the format has significant edge cases that didn't exist before.

Maybe we should add some utilities to that package for generating these files as well?

For google3 my hope is we won't have to deal with this for the most part. We create these files inside of starlark code today and doing escaping etc there is going to be very difficult.

**Comment by natebosch** [comment]
Should we strip build numbers for dart versions? Do we think they will have meaning to the compilers?

**Comment by jakemac53** [comment]
I believe it will be important to be able to include `-dev.x` versions at least so that you don't have to wait for a stable release in order to use new language features.

**Comment by natebosch** [comment]
cc @leafpetersen - can you help us understand plans for different "channels" of SDK releases, and how that might impact this?

We need to have an absolute ordering for language versions. The tools will need to be able to check a package language version and compare to the version which enabled any given feature. I strongly doubt that the build number (following a `+`) is something we want to try to absolutely order, so I think we should strip it rather than escape it.

If we have 2 SDK versions, `2.5.3-dev.2` and `2.5.3-alpha.1`, the pub implementation of semver would order `-alpha.1` higher than `-dev.2` from the language feature standpoint will we order them the same?

**Comment by jonasfj** [comment]
> Should we strip build numbers for dart versions?

As I understood the "language versioning doc" the _language version_ is a major and a minor version, and thus, is a subset of the SDK version.

As I understood it, the `.packages` files should contain the minimum required SDK version for each package. Deriving the language version from the SDK version is left for Dart and other tooling to do.
(In practice the language version is always just major and minor version of the SDK version)

I assume it was done this way because @lrhn (or someone smart) could imagine that having minimum SDK version in the `.packages` files is more useful than having only the language version. Perhaps one could imagine other use-cases in the future.

See the [revisions section](https://github.com/dart-lang/language/blob/master/accepted/future-releases/language-versioning/feature-specification.md#revisions).

**Comment by leafpetersen** [comment]
Are there still open questions here?

**Comment by lrhn** [comment]
The entire format and file location has changed, so the `.packages` file is no longer used for language versioning.
There should be no language markers in that file, it exists entirely for backwards compatibility.

The `.dart_tool/package_config.json` file contains only language versions, not SDK release versions.

There is `package:package_config` for creating and reading the `package_config.json` file. It may need a few more tweaks to allow nested packages to exist in the same package config, but otherwise I believe it's done (well, the tests run, but nobody has used it in practice yet).
