### ISSUE TITLE
Please keep `T == dynamic` working.

### ISSUE THREAD

**Issue by escamoteur** [dart-lang/language#530]
Hi,

I have an `assert` in one of my generic functions that should enforce that either a real type or a string as parameter is used:

```Dart
  /// retrieves or creates an instance of a registered type [T] depending on the registration function used for this type or based on a name.
  T get<T>([String instanceName]) {
      assert(!(T == dynamic && instanceName==null), 'You have to provide either a type or a name. Did you accidentally do  `var sl=GetIt.instance();` instead of var sl=GetIt.instance;');
```

Which works fine after I had to find out that `T is dynamic` is always true.

In https://stackoverflow.com/questions/51208022/detect-dynamic-type-in-dart  it is stated that this works is actually a bug and will be removed in future

IMHO T == dynamic would make sense so that you can do asserts in generic functions. like assert(T!= dynamic). I also think `is of type` should be different from equality because `concreteType == dynamic` should be `false` while `concreteType is dynamic` should be `true`.

Thanks for your awesome work!!!

**Comment by eernstg** [comment]
@lrhn's response in the [StackOverflow question](https://stackoverflow.com/questions/51208022/detect-dynamic-type-in-dart) already indicates how you could test for `T` being a top type rather than just `T` being `dynamic`, namely like this:

```dart
  /// retrieves or creates an instance of a registered type [T] depending
  /// on the registration function used for this type or based on a name.
  @mustCallSuper
  T get<T>([String instanceName]) {
    assert(const Object() is! T || instanceName != null),
        'You have to provide either a type or a name. ...');
  }
```

The assert (when enabled, of course) will then raise an error whenever `get` is called such that the actual type argument (written or inferred) is a top type and the name is null. I wouldn't be surprised if this is actually a good fit for the purpose: It will catch `dynamic` (because that's a top type); it will also catch `Object`, and `FutureOr<void>`, and a bunch of other types that are all just different ways of specifying "any object whatsoever" (because they are all top types). But you might want to exclude those types anyway, for the same reason that you wish to exclude `dynamic`.

(When we add non-nullable types the test may need to be adjusted to `const Object() is! T || null is! T || instanceName != null` in order to correctly test for top types, or you could leave it as `const Object() is! T || instanceName != null` because you're still happy about excluding the type `Object` as the value of `T`, even though it isn't a top type any more.)

However, it _shouldn't_ matter for the body of `get` whether the actual type argument is `dynamic` or any other type: The compile-time error checking for the body of `get` will rely on the knowledge that `T` can be any type whatsoever (because all types satisfy the implicit bound `Object`). The dynamic behavior must satisfy that `dynamic` is just another top type (so there is no difference in the behavior of expressions like `e is T` when `T` is `dynamic` and when it is `Object` or some other top type, and similarly for everything else that is concerned with subtyping). The only distinction that you may encounter is that `T.toString()` could be `"dynamic"` or in some other way reveal that the actual type argument was `dynamic`. But `toString` is not specified, so you should not rely on getting a specific return value from `toString` of a `Type`.

So in this sense `T == dynamic` _is_ working (apart from the bug that makes it evaluate to false in some situations where it should be true, e.g., `Object == dynamic`), but it won't tell you whether `T` was spelled as 'dynamic' when the actual type argument was passed, it will just tell you whether it's a top type.

**Comment by escamoteur** [comment]
Why does `const Object() is! T` evaluate to false if T is dynamic? I thought every type `is` dynamic?

**Comment by eernstg** [comment]
> Why does `const Object() is! T` evaluate to false if T is dynamic?

`const Object()` is an instance of `Object`, so the only types that this object has are the top types. The other side of that coin is that `const Object() is T` is only true when `T` is a top type, so `const Object() is! T` is only true when `T` is _not_ a top type. So `const Object() is! X` is false when `X` is a type variable whose value is `dynamic`.

> every type `is` dynamic

It's somewhat misleading to say that. An `is` expression takes an _instance_ to the left and a type to the right, so `x is T` will check whether `x` is an instance whose type is a subtype of `T`.

If you try to use two types (for instance `int is num`, or `X is Y` where `X` and `Y` are type variables) then you won't get a meaningful result: It will simply be true if and only if the right hand operand (`num` or `Y`) is a supertype of `Type`, and it makes no difference _which_ type the left hand operand denotes.

If you wish to test dynamically whether a given type is a subtype of another type then you might want to think again (because it's not that likely that you really need to do that ;-), but it isn't impossible:

```dart
bool typeLessEqual<X, Y>() => <X>[] is List<Y>;

main() {
  print(typeLessEqual<int, num>()); // 'true'.
}
```

You need to provide an instance of a relevant type, and we can't create an instance of an arbitrary type (`X` could be any type, e.g., an abstract class), but we can create a list with any given type as its type argument. So we can transform the subtype test into a test on the corresponding list types and thus get the result indirectly.

**Comment by escamoteur** [comment]
Thanks a lot for that explanation
