### ISSUE TITLE
Should getter/setter type relationships be symmetric?

### ISSUE THREAD

**Issue by eernstg** [dart-lang/language#531]
The language specification [requires](https://github.com/dart-lang/language/blob/1a85be7311dac0f23698385b36992a81b75abf00/specification/dartLangSpec.tex#L2660) that whenever we have a pair of a getter and a corresponding setter, the return type of the getter must be assignable to the parameter type of the setter.

(This is specified to be a warning, but tools currently make it an error, and we're [considering](https://github.com/dart-lang/sdk/issues/36127) whether it should also be tightened to be an error in the specification. In any case, we're flagging this situation as problematic.)

This issue is concerned with whether we want to require the opposite as well, that is, that the parameter type of the setter must be assignable to the return type of the getter. That question comes up because NNBD makes assignability asymmetric, which means that we don't get both directions automatically any more.

The current rule implies that we do not flag `x = x` as a warning/error. Similar expressions like `x++` will also be OK, as long as `operator +` has a return type that similarly preserves the assignability.

```dart
abstract class A {
  int get x;
  void set x(num value);
  void foo() {
    x = x; // OK.
    x++; // OK.
  }
}
```

However, the old notion of assignability was symmetric, so this requirement also implied that the type of value which would be accepted as input to the setter would also be suitable to return for the getter.

Let's call the currently specified property _assignability for a getter/setter pair_, and then this symmetric property can be called _reverse assignability_.

Reverse assignability isn't required for the same kind of reasons: there is no "simple" expression (in particular, no simple expression produced during desugaring) which will fail to type check when the parameter type of the setter is not assignable to the return type of the getter, as long as we have the plain assignability.

For instance, with NNBD, the example given above has the assignability property, but not the reverse assignability property (`num` isn't assignable to `int`).

Reverse assignability is associated with _implementations_: If we implement the getter/setter pair by declaring a variable of some type `T` which is either the setter parameter type or the getter return type, and then make the setter set that variable and the getter return the value of that variable, then we get a compile-time error:

```dart
class B implements A {
  T _x; // NNBD error in setter if `T` is `int`, in getter if `T` is `num`.
  get x => _x;
  set x(value) => _x = x;
}
```

But it's not obvious that we need to have a message from the type checker which duplicates an error message that some of the possible implementations would incur.

Because of that, I'd propose that we consider regular assignability as the primary requirement, and then we may choose to require reverse assignability as well.

One reason for adopting reverse assignability for a getter/setter pair is that we wish to ensure that it is _possible_ to implement any given getter/setter pair as a variable. We would then flag any getter/setter pair where this is not possible with an error/warning, because it's considered to be a mistake. Is that important enough to justify enforcement?

@lrhn, @munificent, @leafpetersen, WDYT?

**Comment by munificent** [comment]
If I were to design Dart from scratch, a class would define a collection of named *properties*, each of which may support a few operations: getting, setting, invoking. A getter/setter pair would be a single property and would thus have a single type. This is how C# works and I think other modern OOP languages. Trying to cram Smalltalk semantics into Java syntax has always been really weird in Dart.

So I think it would be acceptable to require a getter's return type and a setter's parameter type to be *identical* in Dart. I'm not sure if we can get there practically, though, because of potential breakage.

In the absence of that, I think the next most reasonable behavior is allowing the getter's return type to be a subtype of the setter's parameter. My justification is that this aligns with the general API design credo that an API is easier for a user to consume if it is [liberal in what it accepts and conservative in what it returns](https://en.wikipedia.org/wiki/Robustness_principle).

* A tighter getter type gives the caller a more useful object. It tells the caller more about what it is, and it increases the set of methods they can call on it.

* A looser setter type give the caller a more permissive operation. It means there are more objects that the user may correctly pass in.

I also think this behavior plays nicer with inheritance/implementing. A subclass can reasonably override a getter to return a tighter type. That gives a user of that subclass more information. At the same time, it doesn't break substitutability. Tightening a setter in a subclass would break substitutability.

In practice, I think code like this is somewhat rare because it means the subclass has to do some runtime validation to ensure that the values flowing in *are* the proper subtype. But in cases where users want to do that validation, allowing them to tighten the getter can be useful.

> One reason for adopting reverse assignability for a getter/setter pair is that we wish to ensure that it is possible to implement any given getter/setter pair as a variable. 

I don't think that's very important. If a user wants to do that while having a getter/setter pair with different types, they can always do an explicit cast or conversion or something. The fact that they chose the getter/setter to have different types implies that they are deliberately doing something more complex than a simple backing field. That complexity is on them to deal with.

**Comment by leafpetersen** [comment]
Any further comments on this?

**Comment by leafpetersen** [comment]
Closing this in favor of https://github.com/dart-lang/language/issues/331 .
