### ISSUE TITLE
Specification of deferred loading `loadLibrary` function is lacking.

### ISSUE THREAD

**Issue by lrhn** [dart-lang/language#567]
The specification doesn't actually specify the signature of `loadLibrary`, but just talks about "calling" it in the abstract, and says that the future completes "successfully", but not with which value, or that it completes with an error if loading fails (if it does). 

> We do not specify which object the future returned resolves to.

Not sure what that even means, perhaps just that we may return the same future object again, or perhaps "resolves" meant to say "completes".

The way the `loadLibrary` method on the prefix object is specified, it should be possible to tear it off and look at its run-time type.
The VM allows this, but dart2js does not, and the analyzer seems to consider it to have type `Function` or something (https://github.com/dart-lang/sdk/issues/38281).

The function should be specified to have an acual function type, and that function type should probably be `Future<void> Function()`, `Future<dynamic> Function()` or `Future<Null> Function()`.  The VM's type is `Future<dynamic> Function()` (both statically and dynamically) and it's completed with `null`. Keeing this type is probably the *simplest*. Changing it to a static type of `Future<void> Function()` is better design, but potentially breaking.

It should be specified that if loading fails, the returned future completes with an `Error`. That is never specified. Not sure it can even happen any more, but I guess it's possible for JS compilation where the second compilation artifact can go missing.

**Comment by eernstg** [comment]
Cf. language PR #568.

**Comment by sigmundch** [comment]
> The VM allows this, but dart2js does not

Note, both VM and dart2js allow it. This program prints `() =>  Future<dynamic>` on both:

```dart
import 'b.dart' deferred as b;
main() => print(b.loadLibrary.runtimeType);
```

For both the type is defined by how the lowering of loadLibrary is done in the CFE. There we inject a top level method called `__loadLibrary_prefix` that is then used to create the tearoff. We purposely typed it as returning dynamic when we first implemented this. See:

https://github.com/dart-lang/sdk/blob/b0fa0aebb7064b3af60a7504df832fe3bf4c9a44/pkg/front_end/lib/src/fasta/kernel/load_library_builder.dart#L58

**Comment by eernstg** [comment]
Changing the return type to `Future<void>` would indicate the intended usage of `loadLibrary`. Changing it to `Future<Null>` would be truthful, but has the well-known problem that it can silently be assigned to a `Future<T>` for any `T` (with NNBD: any nullable `T`).

However, the only way a change from `Future<dynamic>` to `Future<void>` will break existing code is if a call site obtains the object that completed this future and uses it for some (arbitrary) member access: `(await p.loadLibrary()).fooBar()`. If it is using one of the few members that null has then this may be working code (say, `.toString()`), otherwise it's just an error that's waiting to happen.

I think this makes a change to `Future<void>` preferable, in which case we'd just need to decide on how much of a breaking change process it would entail to do that.

**Comment by cedvdb** [comment]
Not sure if this type of feedback is appreciated here or not, but I was just caught of guard by this as I supposed that the typing  `dynamic` was some sort of library object, so that this would work: `(await p.loadLibrary()).fooBar()`. I found this thread only because I wanted to complaint about dynamic because I couldn't see what was inside my library, (yeah I'm like that, I can't help it).

**Comment by eernstg** [comment]
@cedvdb wrote:
> I was just caught off guard by this as I supposed that the typing `dynamic`
> was some sort of library object, so that this would work: `(await p.loadLibrary()).fooBar()`.

Thanks for the input @cedvdb! This is exactly the reason why it would be nice to have the specified behavior (using the signature `Future<void> loadLibrary()` rather than the currently implemented `Future<dynamic> loadLibrary()`). When the return type is `Future<void>` it is clearly indicated that the object which is used to complete the future should be ignored (there is no meaningful way to use it), but when the return type is `Future<dynamic>` it is left up to anyone's imagination how that object could be made useful.
