### ISSUE TITLE
'boolean expression must not be null' error

### ISSUE THREAD

**Issue by antekone** [dart-lang/language#632]
Most languages today are casting null's to false.

Consider this code:

```
void main() {
  bool flag = null;
  if(flag) {
    print("flag is true");
  } else {
    print("flag is false");
  }
}
```

This will throw an exception, because `flag` is `null`. For the code to work without throwing exceptions, the expression inside `if` should look like this: `if(flag == true) {...`.

Is this verbosity really needed?

For comparison, JavaScript works with nulls:

```js
flag = null
if(flag) {
    console.log("flag is true");
} else {
    console.log("flag is false");
}
```

The output of the above snippet is `flag is false`.

Can dart implicitly cast nulls to false? Or, can `if` cast `null` expression to false? Would this be a breaking change in the language?

**Comment by eernstg** [comment]
Dart could definitely treat the null object as yet another representation of falsehood, and it probably wouldn't be considered a serious breaking change (it will change the semantics of a huge amount of code, but we generally do not consider it to be a breaking change when a dynamic error changes to any non-throwing behavior; still, it could break programs that catch the error).

However, with [NNBD](https://github.com/dart-lang/language/issues?q=is%3Aissue+is%3Aopen+label%3Annbd) the language will have static checks that prevent null from occurring in a lot of situations, including as a guard in an `if` statement, so the very idea that null should work as a falsey value is a move in the opposite direction of many of the recent developments in Dart.

However, there is one kind of feature that fits perfectly with this idea, and which has been extended substantially in Dart over time: Null-aware constructs. For example, `e1?.foo(e2)` will evaluate `e1`; if the result `o` is null then the whole expression will evaluate to null, otherwise `o.foo(e2)` will be evaluated. One consistent property of these mechanisms is that they are explicit (you have to put the `?` into the member access syntax, `e1.foo(e2)` will just be a compile-time error if the type of `e1` shows that it might be null).

If you are willing to make the treatment of null as falsey explicit then you could do the following:

```dart
extension FalseyNull on bool { // With NNBD it's `on bool?`.
  operator ~() => this == null ? false : this;
}

main() {
  bool b = null;
  if (~b) return;
  print("~b was false");
}
```

**Comment by antekone** [comment]
Thank you for your detailed answer! Also thank you for mentioning NNBD, I'll read about Dart's future plans in this area.

The example code you've provided is useful, and I'll definitely explore the topic of Dart's extension methods, but it still requires the developer to provide an explicit handling of null case when testing the boolean type. I know from my own experience, and other developers' experience, that it's not a problem *when* we remember to do it; it's a problem *when* we forget about it.

I'm closing this issue, since you're already aware of the nullability issue, and you have it described much better than I did it in this post ;).
