### ISSUE TITLE
Is it an error to have a late final field in a const class?

### ISSUE THREAD

**Issue by leafpetersen** [dart-lang/language#657]
Should we allow late final fields in constants?  If so, what are the semantics?  Presumably we require that any initializers be evaluated eagerly?  This seems consistent with const top level variables which are otherwise lazy, so perhaps this is ok?

Late fields don't seem very useful independently in const objects, but allowing a class to have a const constructor even when it has late fields does seem useful: the const constructor must initialize them (or they must have const initializers) but other constructors can leave them to be initialized later.

```dart
const dynamic s = "hello";

class A {
  late final int x = s.length;
  const A() : y = 3;
  late final int y;
}
```

cc @munificent @eernstg @lrhn

**Comment by lrhn** [comment]
I'd say no.

If the field has no initializer, it' a definite no.
If it has an initializer, then you need to evaluate that initializer at "some point" during constant creation. It can't be later because we need to canonicalize immediately after creation.
That means that the initializer expression must be compile-time evaluable, meaning it must be a potentially constant expression. Unless we extend the defintion of that to having access to instance fields, the initializer expression can't depend on the constructor parameters, making it just plain constant and therefore not needing `late` for anything. Other constructors can't do anything about that - a late final field with an initializer expression cannot be initialized differently, and if the expression is const, there is no advantage in allowing `late` (any competent compiler would initialize the field eagerly anyway).

To make the late field initializer practically useful, we would need to give the expression access to something that varies with the construction. If we allow `is T` and `as T` as potentially constant, then the field initializer can also use those (the class type parameters are in scope). Otherwise we'd have to allow access to other class fields on the same object (fields only, not getters), because we know they have just been initialized with constant values, and then force-initialize the late field after instance creation, but before canonicalizing (which is even more fun because the initializer has access to `this`, so we'd have to be clever about canonicalizing `class C {late final o = this; const C(); }`).

All in all, I don't think allowing late final fields in const classes is useful without extending the capabilities of the initializer expression.






Constant objects must be canonicalized at compile-time. A lazy field is not initialized until

**Comment by eernstg** [comment]
I don't quite see why

@lrhn wrote:
> If the field has no initializer, it' a definite no.

because

@leafpetersen wrote (about a `late final` instance variable with no initializer):
> the const constructor must initialize them ..
> but other constructors can leave them to be initialized later.

As far as I can see this makes a `late final` instance variable with no initializer equivalent to a plain `final` instance variable during constant expression evaluation; and for dynamic instance creation they are just like any other `late final` instance variable. If this is a correct characterization then we obviously do not need to worry about the implications for constant evaluation. Similarly, there's nothing new about this kind of dynamic instance creation.

(Of course, the implementation would still need to have a companion boolean `y$isInitialized` to go with `late final int? y;`, because the `y` getter would check that `y$isInitialized` is true and otherwise throw, and conversely for the `y=` setter. In other words, the `late final` field is still implemented as any other `late final` field in the constant object, but the observable properties are equal to the ones of a plain `final` field.)

I don't have an obvious use case where this is crucial, but I do think it would work.

For the `late final` instance variable with an initializer, I agree that it would be really tricky to handle canonicalization of things like `class C {late final o = this; const C(); }`, so we probably don't want to allow that in a class that has a constant constructor.

**Comment by lrhn** [comment]
Good point. So, the initializer case seems to be the "no" case because the expression must be constant anyway.

The other case is actually one I hadn't considered before: A late final field with no initializer which is initialized in the constructor initializer list/initializing parameters.

We can allow that. I'd prefer not to, because currently "const classes" are known to have only final fields and never change their state. We're not using that for anything, but I'd like to try (for example for recognizing deeply immutable objects). If we allow a late final variable, we loose that opportunity.
So, mainly to be careful, I'd still prefer not to allow it, even though we can without breaking anything.

**Comment by leafpetersen** [comment]
I've landed a change making this an error.
