### ISSUE TITLE
Extension methods meet operator overloading and literals

### ISSUE THREAD

**Issue by davidmorgan** [dart-lang/language#667]
With extension methods we have a new, powerful way to build on the core SDK.

We can use them to make immutable collections from literals in a much more natural way than before:

`BuiltList.of([1, 2, 3])` becomes e.g. `[1, 2, 3].build()`.

But if we designed immutable collections into the SDK, we'd probably end up with something still more concise. And we can _almost_ achieve that with extension methods plus operator overloading:

`BuiltList.of([1, 2, 3])` becomes e.g. `~[1, 2, 3]`.

But, it doesn't quite work. The `~` operator binds less strongly than `.`, which means

`~[1, 2, 3].map(...)`

is

`~([1, 2, 3].map(...))`

and not

`(~[1, 2, 3]).map` which is what we need for `~[1, 2, 3]` to behave as a literal.

So, finally, to the request/idea. Could we have a new unary operator intended specifically to allow extension methods to be used to form new types of collection literal? The only requirement is that it bind more strongly than anything else, so that the new construct acts like a literal.

I imagine a practical barrier is finding a symbol that can be used without breaking anything else. My best guess is `#`. If that worked, we'd end up with

`#[1, 2, 3]`

as a new type of collection literal that can be used-defined via extension methods.

Thanks :)

**Comment by lrhn** [comment]
You want one user-definable instance prefix operator which binds stronger than suffix operators.

Would it be easier to have a suffix operator instead? 

Or should we consider introducing "collection builder expressions" where you provide a builder factory somehow, so you can write, say, `BuiltList{1, 2, 3}` directly and it creates a `BuiltList<int>` by creating a value sink with a `close` method returning the built result. That may be more generally usable than just having one free operator.

**Comment by davidmorgan** [comment]
I think prefix is slightly more readable but don't have a strong preference.

Having a way to pipe literals into factories would allow us to avoid copying, which is nice, but seems less readable that just using a normal constructor/factory, so it's not particularly tempting in the context of this request.

Thanks!

**Comment by munificent** [comment]
My opinion is that we should not add new punctuation with undefined, novel semantics.

Punctuation is the *least* readable syntax you can add to a language. When a user sees something like `$#` for the first time, it means absolutely nothing to them. They can't even pronounce it. With a named method, the text of the name itself at least conveys information in English.

The only time I see punctuation working well is when either:

* It is some symbol almost all users laboriously learned in school already. `+` for addition, `/` for division, `()` for grouping, etc. There are relatively few of these and we have them basically all covered.

* Some behavior that is *so* powerful and frequently used that we are willing to accept forcing all users to learn it before they can read Dart code just to unlock the brevity it provides. In theory, that's the justification for `..` and `?.`. This is always a risky move. Everyone loves their own syntax and thinks it's worth the cost to learn. They undervalue the cost because they've already learned it, since they designed it.

Every language I can think of with user-defined operators also has a strong reputation for unreadability and user hostility: APL, Scala, Haskell. Java has no operator overloading at all, has a reputation for verbosity, and is also the world's most popular language. I think the takeaway is that most language designers overvalue brevity and undervalue clarity.

In the specific case here, I think `.build()` and `.toBuiltValue()` are pretty short, clear, and look nice.

**Comment by davidmorgan** [comment]
Thanks Bob! I'm convinced. And we can always add symbols later if it seems to be a reeeally good idea for some reason.

Lasse, feel free to close :) thanks.
