### ISSUE TITLE
Should we add `Any` as an alias for `Object?`

### ISSUE THREAD

**Issue by leafpetersen** [dart-lang/language#670]
In migrating the core libraries, one common observation was that except in a few places, the correct migration of `Object` was `Object?`.  This is verbose, and something that users are likely to consistently make mistakes with.  Should we consider adding `Any` as an abbreviation for `Object?` and encourage users to use that?  We would want to treat this like `FutureOr` - as a type defined in `dart:core`, so that in the future we could migrate this to a simple type alias of the form `typedef Any = Object?`.  

One argument against this is that we would then have one more name for a top type, in addition to our existing three ways of naming the top type (plus an unbounded number of equivalent types).

cc @eernstg @munificent @lrhn

**Comment by munificent** [comment]
> plus an unbounded number of equivalent types

Fortunately, Cantor tells us that ∞+1 = ∞, so adding "Any" as yet another name does not increase the complexity of the language by any measurable amount. :)

My impression is that if a user *does* want to write a method that takes any value, including `null`, then `Object?` is not a very intuitive way to do that. If we think users will do that frequently and we want to make that more natural, then adding `Any` is a good solution. On the other hand, if we want to discourage `null` flowing around, maybe we *should* make them expressly opt into it by writing `Object?`.

**Comment by lrhn** [comment]
I think the ship has sailed on discouraging `null`. A significant number of our core APIs (collection, async) accept nullable types, and fully generic functions like `print`, `StringBuffer.write`, etc. all accept `null` as a value. In Dart, `null` *is* an object (even if it's not an `Object`).

(I'm seriously considering whether it was a mistake to make `Object` not nullable because I almost never need to write `Object`, but often need to write `Object?`).

I'll propose one alternative: Introduce `Any` as a type which means `Object?` when it occurs covariantly and `Never` when it occurs contravariantly. That will allow you to write `Any Function(Any)` to represent any unary function. It is a "wildcard" type.
(The argument against this is that you should never actually write that function type because you can't use it for anything, you should make it `Any Function(T)` for some `T` that you are parameterized with instead. And if users never need the feature, it's not worth the complexity).

**Comment by eernstg** [comment]
I'd say: why not?

One possible counter argument is that 'dart:core' is using these most general references very frequently (e.g., because collections may have a type argument that allows them to contain null). Any domain specific code out there is much more likely to have an interest in an interface, in which case most references will have a non-top type annotation. We have no proposals for shortcuts (shorter than 1 character ;-) to replace the syntax `T?` for that, and it is likely that (1) `T?` will be relatively rare because it is better in so many ways to design the code for non-nullability.

So maybe `Object?` comes up all the time and looks bulky in platform code, but other code doesn't have a problem?

**Comment by a14n** [comment]
Disclaimer: I haven't already play with NNBD

I have more and more issues understanding all the _special_ types and when to use them : `Null`, `Never`, `Void`, `Object`, `dynamic`... (especially combined with generics and NNBD)

I don't think adding `Any` will lower this feeling :-/

The postfix `?` looks like an easy way to detect nullability and I'd rather stick with `Object?`. Perhaps after some migrations to NNBD this feeling will change ;)

BTW: what would mean `Any?` :) ?

**Comment by munificent** [comment]
> BTW: what would mean `Any?` :) ?

It would normalize to just `Any` in the same way that `Null?` normalizes to `Null`.

**Comment by rrousselGit** [comment]
For what it's worth, "any" as a quite negative connotation for typescript users.
In that language, it means the same thing as "dynamic".


Typescript uses the word "unknown" to represent what `Object?` would be.

**Comment by leafpetersen** [comment]
> I'll propose one alternative: Introduce `Any` as a type which means `Object?` when it occurs covariantly and `Never` when it occurs contravariantly.

I am strongly opposed to this. Note that this would need to be implemented in the runtime semantics:

```dart
class A<T> {
  void applyAnyFunctionToAnyArg(T Function(T), T x) {
    // There had better be an implicit cast to Object? Function(Never) here or bad stuff
    // will happen.  This means that the runtime semantics need to compute a different 
    // result when substituting Any into contravariant positions at runtime.
    f(x);
  }
}

void test() {
  var a = newA<Any>();
  // a.test : void Function(Object? Function(Never), Object?)
  // so this call is well-typed 
  var b = a.applyAnyFunctionToAnyArg((int x) => x.isEven, "hello");   
}
```

**Comment by natebosch** [comment]
I'm opposed on the principle of not adding multiple ways (well, even more than we already have) to express the same thing. If we add `Any` then we'll also likely need to add a recommendation that say "never use `Object?`, always use `Any`". That means that when I am refactoring an API and adding nullability I have to take two paths. If my API currently takes anything other than `Object` I add a `?`. If my API takes `Object` I rewrite to `Any`. That feels strange to me. I also suspect that `Object?` will show up less outside of the SDK than within.

**Comment by lrhn** [comment]
I was not expecting to have the behavior occur at run-time, but I can see that it likely has to in order to bit surprise users. I's have just changed the original `Any` to `dynamic` because it occurs covariantly, but it really is invariant, and it doesn't work for that. Even with variance support, I can't say what it should do there.

So, I retract that suggestion.

I do think that a shorthand for `Object?` would be nice. I've written it enough (and forgotten the `?` enough) to think that the concept of "all values" needs a name for itself.

Then our three primary top types would be `Any`, `dynamic` and `void`, each equivalent to `Object?` with or without some extra rules. (The `Any` does stand out by being the only capitalized one, but for symmetry with `Never`, I think it's unavoidable).

**Comment by munificent** [comment]
This does raise the unpleasant spectre of what name to show in things like runtime and compile-time errors. Whatever we pick will likely confuse some users who expected the other synonym.

**Comment by tatumizer** [comment]
What will you show if the user declares `String?? x` ?
`Any` should be a canonical name IMO (like in Kotlin and Swift), so as a general rule, canonical name is preferred: `String?`, rather than `String??`; `Any`, rather than `Object?`.

**Comment by munificent** [comment]
> What will you show if the user declares `String?? x` ?

That's a syntax error. We only allow a single `?` after a type. You can synthesize such a type using generics, in which case it should get normalized down to the simpler form with only a single `?`. But you can never *write* a type like that, so it shouldn't be surprising when the error doesn't have double question marks.

**Comment by tatumizer** [comment]
And what if you disallow `Object?` in user's code? Then the only way this type can come into play is through "synthesis" in generics. This hypothetical situation arises in the following scenario: 
we have some parametrized type Foo<T>, and the following code in user's program:
```
Foo<Object>.m();
```
For the problem to materialize, the implementation of method m should somehow make use of type `T?`. I think this is a very rare phenomenon in generic code (I cannot immediately come up with a reasonable example). In any case, the situation doesn't look grave enough to sacrifice the convenience of Any (IMO). You can always say that `Object?` gets "normalized" to `Any` :)

**Comment by munificent** [comment]
> And what if, in a similar manner, you disallow `Object?`, requiring `Any ` to be used instead ?

I think that would possibly be *more* confusing because then it would obscure that `Any` really is just nullable `Object`. If users try to write that directly and we yell at them, it may lead them to believe there is something special about `Any`.

**Comment by tatumizer** [comment]
OK, agreed, error is no good, but how about warning? E.g., **info:** so and so, use `Any` as a shorter synonym to `Object?`... 
Speaking of confused users, we can imagine 2 situations:
1) the user writes `Object?` under the illusion it means something different from Any. Then the above message quickly disabuses the user of this fallacy.
2) the user writes `Any` but deep inside, still entertains the illusion that somewhere, there might be another type `Object?`, which is completely different from Any. I think that's no big deal because, for any practical purposes, this misconception is harmless. 
How about that?

**Comment by leafpetersen** [comment]
My take on this based on the discussion above is that adding yet another way to write a top type is not worth any marginal benefit.  We can add this as a type alias later if desired.  @munificent @eernstg @lrhn do any of you want to push for this further, or can I close this out.

**Comment by eernstg** [comment]
I'm not pushing.

**Comment by leafpetersen** [comment]
Closing this out.
