### ISSUE TITLE
Clarify several corner cases around late fields

### ISSUE THREAD

**Issue by leafpetersen** [dart-lang/language#681]
Two points around `late` fields to be clarified in the specification:

Per `Question 2` in [this comment](https://github.com/dart-lang/language/issues/146#issuecomment-480364642), there should be an exception thrown if evaluating an initializer expression causes a second write to a `late final` field. 

Per [discussion](https://github.com/dart-lang/language/issues/523), clarify that `late final` fields with an initializer do not induce a setter in the class in which they are defined.

cc @lrhn @munificent @eernstg @johnniwinther @liamappelbe

**Comment by lrhn** [comment]
For the former, that can only happen due to recursion in the initializer, right?

```dart
int ctr = 0;
late final int x = ctr < 5 ? ++ctr + x : ctr;
try {
  print(x); // throws 
} catch (e) {
  print(x); // prints 5
}
```
This keeps recursively reading `x` until `ctr` is 5, then it sets `x` to 5, returns and tries to set `x` to 10 (`ctr` + `x`), which fails and throws.

The initializer cannot store to `x` because `x` has no setter, so it must be a read-while-reading for it to initialize twice.

(In practice, that kind of issues will most likely only happen because of accidental mutual recursion, not something as obvious as depending on yourself).

**Comment by eernstg** [comment]
> clarify that `late final` fields with an initializer do not induce a setter

PR #560 clarifies exactly that.

**Comment by leafpetersen** [comment]
Fixes for both of these are either landed or in flight.
