### ISSUE TITLE
Late variables not supported with a for-in statement?

### ISSUE THREAD

**Issue by eernstg** [dart-lang/language#692]
@johnniwinther raised the following issue: The nnbd specification currently makes it an error for a formal parameter to be `late`, but there is no such error for any other kind of variable (there are errors for not being initialized etc., but no errors for any other kind of variable as such).

The variable of a for-in statement is somewhat ambiguous in this respect:

```dart
class A implements Iterable<int> {...} //  The associated `current` is expensive.

void main() {
  A xs = ...;
  for (late final x in xs) {
    if (unlikelyCondition) print(x);
  }

  // Desugared to the following:
  A id1 = xs;
  var id2 = id1.iterator;
  while (id2.moveNext()) {
    late final x = id2.current;
    {
      if (unlikelyCondition) print(x);
    }
  }
}
```

The example is clearly contrived, but there could be cases where `current` is actually expensive, and we'd only want to evaluate `x` a few times and skip the rest. We are basically sampling the iterator, looking at maybe 1 out of 1000 elements.

But the example is not just contrived, it is also a feature which could be non-trivial to implement, because the front end compiles a for-in to a for statement in kernel, and each backend would then need to deal with the `late` variable semantics directly.

So I'd suggest that we make it an error for a for-in variable to be `late`, and then we can always add support for it, if it turns out to be needed after all.

@lrhn, @munificent, @leafpetersen, WDYT?

**Comment by leafpetersen** [comment]
Agreed, I think this should be an error.  I think the semantics of that are completely non-obvious - if someone wants that behavior they can write the while loop directly.

Are there other places we haven't thought of that we should forbid late variables?

**Comment by munificent** [comment]
> Are there other places we haven't thought of that we should forbid late variables?

Places off the top of my head where variable syntax kicks in:

* Function parameters
* Catch clauses
* For elements in collection literals

**Comment by eernstg** [comment]
Right, I forgot for elements, and I think they should follow for statements. Catch clauses can't declare a type (it is just `'(' identifier (',' identifier)? ')'`), and function parameters already have an error.

So it sounds like we'd agree to make `late` on the variable of for-in statements and for-in elements an error.

C-style for statements and for elements still need to be clarified. The language specification has had no updates in the section about C-style for statements; it says very little about the static analysis, and covers only a single case for the dynamic semantics (`var v = e0`). So we need to perform substantial updates to this section, and it is currently not well prepared for allowing a late iteration variable.

I'd recommend that we make it an error for a C-style for statement/element to declare a `late` variable in a `<localVariableDeclaration>` which is its `<forInitializerStatement>`, and then we can again add this feature later if needed.

**Comment by lrhn** [comment]
The trend here seems to be that in any place where assignment is necessary for entry, where the variable is definitely assigned before any reading is possible, making the variable `late` is definitely unnecessary and therefore we should disallow it.

That includes, as Bob listed:
* function parameters (you cannot enter the body without assigning values to all parameters).
* constructor parameters included.
* catch clauses (you cannot enter the catch block without assigning values to catch variables).
* for-in iteration (you cannot enter the body without assigning a value to the loop variable). Includes `await for` and collection literals too, it's the `var x in ...` that matters.

I can't think of any other case either.

I guess the "variable with initializer" is the exception here because the declaration and the value computation happens in the same place, so we can choose to delay the evaluation. For the other cases, the value is computed somewhere else and then assigned.

**Comment by eernstg** [comment]
Covered by https://github.com/dart-lang/language/pull/702.

**Comment by leafpetersen** [comment]
Spec fix landed.
