### ISSUE TITLE
do constant short-circuit operators eagerly type-check?

### ISSUE THREAD

**Issue by sigmundch** [dart-lang/language#696]
This test: co19_2/LanguageFeatures/Constant-update-2018/ShortCircuitOperators_A01_t1
```dart
const nil = Null;

class MyClass {
final bool b;
const MyClass() : b = false && nil;
}

main() {
const res = MyClass();
}
```

fails in the CFE because the type of the unevaluated subexpression is not bool. Since the constant will not be evaluated, should its type also be ignored by the short-circuiting operator?

If yes: this may require a fix in CFE
if no: this may require a clarification in the spec and a follow up to amend the test.

**Comment by sigmundch** [comment]
analyzer also has the same semantics as the CFE

**Comment by eernstg** [comment]
The expression `false && nil` is a compile-time error based on [this](https://github.com/dart-lang/language/blob/58518773eab01ebcf8a57ec16e07a5d9588b7e71/specification/dartLangSpec.tex#L12953), because the inferred type of `nil` is `Type`. That's applicable to it as an expression, and then any requirements based on rules about constants would just be added to the mix.

**Comment by sigmundch** [comment]
Thanks! I'll file a bug to let them know that the test needs to be fixed

**Comment by lrhn** [comment]
A guess would be that the `const nil = Null;` should have been `const nil = null;`. That would make the code not be an error in current Dart, but will still be an error in NNBD when the boolean operators require non-nullable `bool` operands.
