### ISSUE TITLE
Implicitly induce a throwing setter for late-final getter override?

### ISSUE THREAD

**Issue by eernstg** [dart-lang/language#705]
The nnbd spec [says](https://github.com/dart-lang/language/blob/master/accepted/future-releases/nnbd/feature-specification.md#late-fields-and-variables) that

> Overriding a field which is marked both `late` and `final` with a member which
> does not otherwise introduce a setter introduces an implicit setter which throws.

The example in the specification goes as follows:

```dart
class A {
  late final int x;
}
class B extends A {
  int get x => 3;
}
class C extends A {
  late final int x = 3;
}
void test() {
   Expect.throws(() => new B().x = 3);
   Expect.throws(() => new C().x = 3);
}
```

This rule has caused some discussion, hence this issue.

The motivation for inducing a throwing setter (in `B` and in `C`) is that the semantics of _not_ inducing such a setter is confusing: The overridden getter makes it difficult to get access to the value of `A.x`, but without this rule it is possible to assign a value to `A.x` by calling the setter, which may already be surprising because a subsequent evaluation of the getter does not return the assigned value, but the situation is even more confusing because the next invocation of the setter `A.x=` will throw. In short: the inherited setter is too weird, so we must hide it.

The argument _against_ implicitly inducing a throwing setter is that this is the behavior that other parts of Dart exhibits: It is always possible to declare a variable or a separate getter and setter with the same basename, and then we will get a similar effect if a subclass inherits the setter and overrides the setter. In short: these are just getters and setters, no exceptions needed.

So this issue is concerned with that choice: Should we implicitly induce a throwing setter? Or should we follow the rules that we otherwise use for getters and setters, and not induce it?

@leafpetersen, @munificent, @lrhn, WDYT?

**Comment by lrhn** [comment]
I vote strongly for consistency.

One of the most common reasons for adding an override of a getter or setter is to intercept and wrap the access to the super-setter/getter. Intercepting the getter, which still makes the value available, should not block access to the still-necessary setter.

We will also have to remember whether an inherited setter is the implicit setter of a late final instance variable, and treat that case specially, something that is not stable under reasonable refactorings. An seemingly unrelated change, that should be semantics preserving, can be breaking because of this odd side effect of what should be an implementation detail.

Example:
```dart
class C {
  final late int x;
}
class D extends C {
  void set x(int value) { super.x = value; }
}
class E extends D {
  int get x => super.x;
}
```
Here we would *not* introduce a throwing setter in `E` because `D` overrides the implicit setter of the late final field of `C`.

If we remove the declaration from `D`, it should not change anything. After all, it's just acting exactly like the superclass getter. However, we would be inserting the throwing setter now, changing the behavior of `E`. That makes removing a forwarding setter in a class potentially breaking in a subclass.

**Comment by eernstg** [comment]
I prefer the simplicity of treating these getters and setters just like all other getters and setters as well. However, I think the example might still introduce a throwing setter in `E`:

> Overriding a field which is marked both `final` and `late` with a member
> which does not otherwise introduce a setter introduces an implicit setter which throws.

So does `E.x` override the field `C.x`? You could argue that this is true if and only if `E.x` overrides a getter which is implicitly induced by `C.x`, which it does. However, in that case we cannot set the field `C.x` because any attempt to do so would just throw (because `E.x=` always throws), both before and after the refactoring (where we still have a throwing `E.x=`). So you could argue that the developer just has to write an explicit `E.x=` which uses `super.x=` to invoke `D.x=` respectively `C.x=`.

So it's not an impossible situation, but I also don't think it's particularly more comprehensible than just overriding setters and getters using the standard rules.

**Comment by lrhn** [comment]
> does `E.x` override the field `C.x`?

That's not evan a meaningful question. You cannot override "a field", the concept does not exist.
You can only override getters and setters.

If we define "override a field", aka "overriding an instance variable", as "overriding any of an implicit getter or setter induced by the instance variable declaration", then `D` does that, but it also "otherwise introduces a setter", so it doesn't trigger.

Then `E` would trigger, because it overrides the implicit getter of a late final instance variable and does not otherwise introduce a setter, so we override the setter of `D` - even though that setter is *not* the one from the instance variable.

Either interpretation leads to spuriously overriding a setter for no particular reason. Just don't do it.

**Comment by eernstg** [comment]
> That's not evan a meaningful question

Which is exactly the reason why I state it explicitly (in order to determine the intentions in the original text 'Overriding a field..') and then immediately switch over to talking about overriding in terms of getters and setters only. So there's no disagreement here, we shouldn't introduce the notion of "overriding a field".

**Comment by leafpetersen** [comment]
I'm ok with removing this.  If one of you gets a chance, could you please update the spec and and communicate this to @stefantsov and @johnniwinther since I believe this only affects the front end?  If there are backends for which the CFE would not be generating this automatically, then we should be sure to communicate with them as well.  Also any co19 tests that test for this should be updated.

**Comment by eernstg** [comment]
Cf. PR #720. I talked to @stefantsov and @johnniwinther, and they hadn't done this yet, so the task has simply been canceled.

**Comment by eernstg** [comment]
Done. ;-)
