### ISSUE TITLE
Polymorphic inline caching

### ISSUE THREAD

**Issue by a5l3** [dart-lang/language#713]
Hi. 
How is this used in Dart as a language feature. My best guess would be the overloaded types and operators part of Superclasses.
Reading the 2.2 specification and nothing on polymorphic inheritance.

**Comment by eernstg** [comment]
Hi, Dart language specification maintainer here. You're right, there is nothing in the spec about polymorphic inheritance.

Usually, inheritance is a mechanism that allows for reusing a member implementation (that is, a method/getter/setter/operator/etc. declaration with a body) in a subclass without duplicating the code. Polymorphism is the ability of an expression to evaluate to results of more than one type, and subsumption is the permission to use an expression of a type _T_ in a location where a value of type _S_ is used, as long as _T_ is a subtype of _S_.

So subsumption is the reason why polymorphism can occur, and inheritance is the ability to run the same code for some of those objects that we can encounter at a given point due to polymorphism (rather than duplicating the code).

But 'polymorphic inheritance' is not a concept that I've seen anywhere, so what would that mean?

Another issue is that Dart doesn't do static overloading (long discussion, won't go there now ;-), so we don't have overloaded operators in that sense. We do, for performance reasons and in order to get better typing in numeric code, have special treatment of `+` and a few other operators (so `a + b` has type `int` if both `a` and `b` have type `int`, plus a few other cases). Otherwise Dart doesn't do anything that could be described as 'overloaded operators'. 'Overloaded types' is also not an established concept.

So we're not quite aligned on the concepts here, but it would be very helpful if you could give an example of some code with the properties that you are interested in, and explain how it doesn't do what you want.

**Comment by a5l3** [comment]
Hi,
Thanks so much  for taking the time to reply.

I meant to say Polymorphic inline caching :), not sure how polymorphic inheritance came about, maybe worth exploring, no wonder I couldn't find  it :)

All the code is doing whats its supposed to be doing,  picked up the specification to dig deep (learning a  lot!) and looked at some talks discussing dart, one of the more subtle but recurring things pointed out is 'polymorphic inline caching', so I've wanted to better understand it, its interesting.

So by being able to identify where this is being used can I write more readable optimised code? And is there a section in the language specification that reflects this as a product of dart having polymorphic inline caching?

**Comment by eernstg** [comment]
Ah, OK! Polymorphic inline caching is an implementation technique (where the invocation of an instance method jumps to the right method body based on an inlined test, a bit like `if (receiver.class == C1) call m1 else if ...`). This [is used](https://mrale.ph/blog/2015/01/11/whats-up-with-monomorphism.html) by the Dart vm, and if Dart is compiled to Javascript then a virtual machine like v8 uses it as well. So you can certainly run Dart in a way where this kind of optimization is used, but it won't be so easy to map it directly to the Dart source code: It's not obvious at any given call site `x.foo()` whether `x` will always be an instance of the same class or it's going to alternate between a large number of classes. Polymorphic inline caching works best when the number of target types is low, and that is not something that you're likely to be able to control or predict by writing you code in a specific way locally, that's a property of the software at a much more global level. However, if you're interested you could always check the generated code to see whether it is using an inline cache in any given case.

**Comment by a5l3** [comment]
This is fantastic, no wonder the widget tree in Flutter can rebuild efficiently. Will try to find some inline caches as homework.
Thanks!

 (renaming to Polymorphic inline caching because Polymorphic inheritance isn't a thing)

**Comment by eernstg** [comment]
Thanks!
