### ISSUE TITLE
How to get total value of item list in a Future async operation

### ISSUE THREAD

**Issue by camillo777** [dart-lang/language#717]
Hello, I am trying to make a getter that will return the total amount of a list of items that I am retrieving from the web with an async API call; this is the code:

```
// the list of item IDs
final List<int> _itemIds;

// get the list of products based on the list of IDs
Future<List<Product>> get items async => await Future.wait(_itemIds
      .map((id) => api.getProduct(id))
);

// get the total amount of items
Future total(l) async { return (await items).fold(0, (a, b) => a + b.price); } // --> here is the error
```

I have got an error on the plus sign "**a + b.price**".

**ERROR MESSAGE:**
The operator '+' isn't defined for the class 'FutureOr'.
Try defining the operator '+'.

I am using:
Visual Studio Code, 
VS Dart extension 3.6.0,
Flutter 1.9.1.hotfix6, 

Thank you!

**Comment by munificent** [comment]
For future reference, this repository is just for tracking the evolution of the Dart language itself. For issues using a specific API or core library, https://github.com/dart-lang/sdk is the repo you want.

In this case, I think type inference is having trouble guessing the correct type for the `fold()` call and it gives you `FutureOr<int>` instead of `int`. You can help it by providing an explicit type:

```dart
Future total(l) async { return (await items).fold<int>(0, (a, b) => a + b.price); } 
```
