### ISSUE TITLE
NNBD Implicit downcast from `Function`

### ISSUE THREAD

**Issue by lrhn** [dart-lang/language#754]
NNBD removes implicit downcast except from `dynamic`.
Maybe it should also allow implicit downcasts from `Function` to any function type, for all the same arguments that applied to `dynamic`. The `Function` type is used to represent a function with some type, and it allows dynamic invocation of that function. As such, you gain no power from downcasting that you don't have already, you can get a run-time error when casting to the type, or when calling it at that type without casting first.

So, because `Function` is "dynamic" in behavior, it should probably also be allowed to do dynamic downcasts.

**Comment by eernstg** [comment]
Yes, we have actually described `Function` as "`dynamic` for functions" in various discussions, and even in the language specification ([e.g., here](https://github.com/dart-lang/language/blob/575f301c9947fff50e612af8dd245ad6600ff674/specification/dartLangSpec.tex#L11220)), so it would make sense to allow these downcasts.

Conversely, this could also imply that `Function` should be targeted in a way that resembles the treatment of `dynamic`, e.g., perhaps as part of [strict-raw-types](https://github.com/dart-lang/language/blob/master/resources/type-system/strict-raw-types.md#conditions-for-a-raw-type-hint).

**Comment by leafpetersen** [comment]
I'm not sure I'm convinced this pulls its weight.  How common is this really?

**Comment by munificent** [comment]
> So, because `Function` is "dynamic" in behavior, it should probably also be allowed to do dynamic downcasts.

Another way to think of "Function" is that it's the *union* of all function types, which also happens to support a dynamic invoke operation. If you think of it is a union type, then I don't think I would expect it to allow implicit downcasts to a specific function type any more than I would expect `int | bool` to allow an implicit downcast to `int`.

**Comment by eernstg** [comment]
@leafpetersen wrote:
> How common is this really?

It's not hard to find more than a thousand usages of `Function` as a type internally, so it does occur. But I actually think this is about consistency: `Function` and `dynamic` are special in that they allow for performing operations whose existence is checked dynamically rather than guaranteed statically, so it seems reasonable to treat them in the same way when possible.

In particular, implicit downcasts from `Function` (maybe: only to a function type) could be allowed with the same justification that justified such downcasts from `dynamic`, and any diagnostics (hints/lints) aimed at helping developers to avoid dynamic code should flag the type `Function` in a similar way as they flag the type `dynamic`.

@munificent wrote:
> it's the _union_ of all function types

That's an interesting take on it (and I can see that the relationship `void Function() <: Function` is similar that of union types in that there's no `implements` or similar edge in the subtype graph), but I still think the ability to turn a static check into a dynamic check is a more significant property of `Function` than the lack of a "clausal" subtype relationship.

**Comment by lrhn** [comment]
> Another way to think of "Function" is that it's the union of all function types,

It is a least upper bound of all function types, so it is equivalent to the union of all function types. That doesn't really say much, though. All types are the least upper bound of all their subtypes (themselves included if they do not have two unrelated subtypes),  and `dynamic` can also be seen as the union of all interface and function types (anything except itself and `void`).

I think it's more relevant to look at the:

> which also happens to support a dynamic invoke operation.

like Erik does. 

It is an object with statically unsafe behavior ranging over all functions&mdash;you can invoke it using `fun(args)` or `fun.call(args)`&mdash;so it is reasonable to be able to also use it equally unsafely as any function type in other ways than just doing invocations. If you can *call* it as a `Function(int, int)` without any fuzz, why can't you assign it to `Function(int, int)` and then call it?

**Comment by leafpetersen** [comment]
cc @natebosch

**Comment by natebosch** [comment]
The trend has been away from implicit behavior, it the explicit cast draws attention to the places where the code may fail at runtime which is desirable.

> it is reasonable to be able to also use it equally unsafely as any function type in other ways than just doing invocations

The existing of one trap (which may be hard to fix) shouldn't block us from fixing another trap which is easy to fix. We wouldn't be taking away anything that can be expresses otherwise, only making unsafe things look unsafe.

**Comment by lrhn** [comment]
We *can* remove `dynamic`. It's technically possible. It'd be a breaking change, but we have language versioning to support that.
If we did that, then `dynamic` would become `Object?` and you would have to explicitly down-cast to a correct type before you can call a method.

Migration would be tricky to automate because the code doesn't contain the information about which interface you should be downcasting to. That's a practical argument against doing this.

We don't do that because `dynamic` servers a real purpose. It is an escape hatch in the type system which allows you to write code which is *correct* even if it is not *typable*. It does mean that when someone uses `dynamic`, the author is in charge of ensuring that things are correct, not the type system. You don't need to down-cast before calling a method, or calling it as a function because *you are assumed to know what you are doing*. It's not implicit behavior, there is no implicit cast when doing invocations, it's just dynamic behavior.
I see allowing downcasts as being consistent with this. It's not as much *casting* as it is *dynamically checking* that the value has the type the author claimed it would have.

**Comment by leafpetersen** [comment]
This is not planned.
