### ISSUE TITLE
Immutable instance variables should be type promoted.

### ISSUE THREAD

**Issue by Cat-sushi** [dart-lang/language#775]
Currently instance variables cant't be type promoted, because method/ function call might modify them between type checking and reference.
To put it the other way, immutable instance variable such as final fields, getters without respective setters.
Especially for non-null promotion of NNBD, I think immutable variable should be type promoted.

If there is no function call between type checking and a reference, the instance variable also should be type promoted.

#757 might widen the target of type promotion, even more. 

note: this issue is derived from dart-lang/sdk#40077

**Comment by lrhn** [comment]
Sadly, even that is not sound.
Since Dart does not have final declarations or sealed classes, it is possible for a subclass to override the field getter with a new getter which returns different values each time. The compiler cannot know that this hasn't happened when compiling the original method. (Not without a whole-program analysis to check that the getter is not overridden anywhere, and that's a little too fragile in practice. Adding a getter in one place can cause a method in a superclass to no longer be valid. That's the wrong direction for that kind of dependencies).

**Comment by Cat-sushi** [comment]
Thank you for your explanation.

**Comment by Cat-sushi** [comment]
another discussion
dart-lang/language#1188
