### ISSUE TITLE
Implicit function parameter

### ISSUE THREAD

**Issue by Afsar-Pasha** [dart-lang/language#784]
Allow implicit function parameters on overridden functions and anonymous function.
What I meant is,
```dart
class Base {
  void f(List list) {
    ...
  }
}

class Derived extends Base {
  @override
  void f {   // no parenthesis
    ...  // "list" is available in this scope
    list.map({ return e*2; });
    // map is defined as "map<T>(T f(E e))", so here "e" is available 
  }
}
```

**Comment by munificent** [comment]
Dart *does* support inheriting the *types* of overriding parameters:

```dart
class A {
  method(int a) {}
}

class B extends A {
  method(b) {

  }
}

main() {
  B().method("s");
}
```

You get an error passing "s" to B.method() because `b`'s type is `int`, which it "inherits" from `a`.

I don't think it would be good to inherit the entire parameter list including the names, though. Imagine if Base is declared in a separate package from Derived. Right now, the parameter names of positional parameters in a method are implementation details of that method and not part of its public API. The maintainer of Base can change `list` to `whatever` without affecting any users of the program.

But with this feature, the entire signature, including names of parameters, becomes part of the API. An even harder case is this:

```dart
class A {
  method(int a) {}
}

class B {
  method(int b) {}
}

class C implements A, B {
  method {
    // What name here?
  }
}
```

**Comment by Afsar-Pasha** [comment]
@munificent 
We currently have, class name, method name, method return type, parameters type and named parameters names as a part of API. I think it wouldn't hurt much to have every parameter names as a part of API.
In your example I think `B` should take precedence over `A` similar to mixins.

**Comment by MrCreeper1008** [comment]
This makes code less readable imo as it's not clear where a parameter is coming from.

**Comment by Afsar-Pasha** [comment]
@MrCreeper1008 

> This makes code less readable imo as it's not clear where a parameter is coming from.

Something similar to extending a class or using a class with mixins.
