### ISSUE TITLE
In subtype judgments, should legacy named parameters be allowed to pretend that they are required?

### ISSUE THREAD

**Issue by eernstg** [dart-lang/language#812]
Cf. https://github.com/dart-lang/co19/issues/520#issuecomment-580899039.

Correct overrides where the overrider is opted in and the overridee is opted out allows the overrider to use any placement of `?` in types:

```dart
// Opted out.
class A {
  int foo(int i) => i;
}

// Opted in.
class B implements A {
  int? foo(int i) => null; // or `int foo(int? i)`, anything goes.
}
```

This allows the migrated code (like `B`) to express the intended development of the system as a whole, even though it depends on legacy code (like `A`) which hasn't yet been migrated. As long as the right people communicate to align the plans, `B` can go ahead and declare the nullability properties that will make it work correctly with `A` now, and also with the future `A` which is the intended result of migrating `A` to nnbd.

However, we don't have the same freedom with `required` named parameters:

```dart
// Opted out.
class C {
  int foo({int i}) => i;
}

// Opted in.
class D implements C {
  int? foo({required int i}) => null;
}
```

In this case we don't equip the legacy type with magic powers that allows it to be a supertype of nnbd subtypes where some named parameters are `required`.

So even if the desired properties for `D.foo` call for a `required` parameter, and even if the plans for migrating `C` are perfectly aligned and its `foo` will also get a `required int i` when it is migrated, it will be an error for `D.foo` to override `C.foo`, because the rules about subtypes and `required` imply that the necessary subtype relationship does not exist.

So is this just a non-problem, or do we want to change the function type subtype rules such that a named parameter whose type annotation is a legacy type can play the role of a required parameter in an nnbd type?

```dart
void Function({required int i}) <: void* Function({int* i})
```

Of course, this is yet another relaxation and yet another source of unsoundness, but it seems consistent with the treatment of `?`: When it comes to things that legacy code can't talk about, it gets to pretend that it has whatever it needs.

@lrhn, @munificent, @leafpetersen, WDYT?

**Comment by lrhn** [comment]
As I understood things, the answer is "yes".

At least, the **LEGACY_SUBTYPE** relation works that way. I can see that the general `<:` relation does not, even if the function type is a legacy function type.

A legacy function type cannot *declare* required named parameters. It can act as if a named parameter is required anyway (and even mark it `@required`).

Like nullability, we should treat the requiredment of named parameters as something that the legacy type is agnostic about. A null-safe method with a required named parameter can override, and be overridden by, a legacy method with the same named parameter (which is necessarily not required).

Ditto for function types. A legacy function type with a named parameter can be satisfied by both a null-safe function with a required named parameter, and one with an optional parameter.

So, I think the subtype relation should recognize whether a function is a legacy function type (as an inherent property of the type, not just checking for a trailing `*`) and treat all named parameters as "required*", meaning that they can count as required.

**Comment by scheglov** [comment]
I don't understand what "as an inherent property of the type", when the comment "not just checking for a trailing `*`" is made. At least in analyzer the way we know that a type is a legacy type is by looking at its nullability suffix, it should be `*`.

Initially I thought that we will allow any named parameter with legacy type to satisfy a required named parameters. Then I read about your statement about "function is a legacy function type", and thought that we should look not on the parameter type itself, but the nullability suffix of the whole function type. But the last comment about "inherent property" leaves me confused.

Could you please clarify?

**Comment by lrhn** [comment]
I was thinking, but might be mistaken, that there should be a difference between a legacy function type and a non-legacy function type.
Say:
```dart
/// Not null safe
typedef Unsafe<T> = dynamic Function({@required T x});  // @required just for emphasis.
T id<T>(T arg) => arg;
```
and then:
```dart
/// Null safe:
typedef Safe<T> = dynamic Function({T x});
late Unsafe<int?> f1;
late Safe<int?> tmp;
late var f2 = arg(tmp);
```

The static type of `f1` is the *legacy function type* `dynamic Function({int? x})`. I don't know if you put a `*` at the end to mark that or not. It doesn't actually matter. Let's assume you do, so it's the type `dynamic Function({required int? x})*`.

The static type of `f2` is the `*` of the null-safe function type `dynamic Function({int? x})`, so `dynamic Function({int? x})*`.

I believe those two types are *not the same*. 
That is because I *want* to be able to do the following (while I'm aware that that's not what the current spec says):
```dart
f1 = ({required int? x}) => null; 
```
and *not* be allowed to do:
```dart
f2 = ({required int? x}) => null; 
```
because that would be violating the null-safe type.

The types of `f1` and `f2` *appear* to be the same, but the `f1` type is the `*` of a legacy function type and the `f2` type is the `*` of a null-safe function type. 

I think there should be a difference, which is why I think that needs to be an internal part of the function type itself, not just something you derive from the presence or absence of `*` marker on the type or on parameter types. A legacy function type is *inherently* different from a null-safe function type. Or maybe it's only around required parameters, so what I want is probably more like all legacy function types having a `required*` marker on all named parameters, one that can satisfy, and be satisfied by, both a required and an optional named parameter. Legacy erasure would *add* that, just as it adds `*` to types. But since it's all named parameters of legacy types, it's probably easier to just mark the function type itself as being a legacy function type.

In any case it would allow overriding a `@required` legacy class parameter with a `required` null-safe parameter, and allow assigning a function to `f1` above.
It's similar to how the `type*` works wrt. `type?` and `type`, a `required*` matches both `required` and "not required". And it would interact with subtying in such a way that `Function({required* int? x})` is a subtype and supertype of both `Function({required int? x})` and `Function({int? x})`.

For the override example, take the legacy class 
```dart
// Not null safe
class C<T> {
  dynamic foo({@required T x}) => "$x".length;
}
```
and the overriding class.
```dart
// Null safe
class D extends C<int?> {
  dynamic foo({required T x}) => 42;
}
```
This looks like it should be allowed because it is the correct migration of a `@required` parameter.

Again, I know this is not what the specification currently says (well, I think it's not, I have a hard time finding the exact details). I think we are using the legacy erasure and then embedding the result into null-safe code, but that erases the `required`, which is the wrong thing to do in these examples.

**Comment by scheglov** [comment]
@leafpetersen I'd like to know your opinion of this issue. Is it decided what we do here? Will you update the specs for subtyping, UP and DOWN?

**Comment by scheglov** [comment]
FYI, after discussing with @leafpetersen, we [updated subtype check](bdf14543576ad2e40e31b48a382d87ab29c66286) in analyzer so that required named parameters match (not-required) named parameters in legacy function types. This fixes the override issues, even though does not support additional safety described in the previous discussion.

**Comment by eernstg** [comment]
With support from @lrhn [here](https://github.com/dart-lang/language/issues/812#issuecomment-581265337) and @leafpetersen [here](https://github.com/dart-lang/language/issues/812#issuecomment-603949185), the **decision** is that the answer to the question in the title is "Yes", for example: `void Function({required int p}) <: void* Function({int* p})`.

**Comment by lrhn** [comment]
Does this mean that you can distinguish a legacy function type from a null-safe function type independently of the component types?

That is:

```dart
/// legacy
typedef F<T> = T Function({@required T arg});
/// null-safe
F<int> x = ({required int arg)) => arg;  // F<int> is `int Function({int arg})` with not * or ?.
```
is valid?

**Comment by eernstg** [comment]
My take on this is that type normalization is only applied in specific situations, which means that the type denoted by `F<T>` for any given `T` is `T* Function({T* arg})`, and in particular `F<int>` denotes `int* Function({int* arg})`, and the initialization is accepted.

PS: We have to apply `*` to all non-top-level type terms in a legacy type alias, because the intended meaning of such a term can be nullable, also in the case where it is a type variable whose value is a non-nullable type, and the legacy code cannot express this without the `*`. Cf. #868.

**Comment by leafpetersen** [comment]
I believe that the solution we discussed is essentially equivalent to adding a special case rule for `R0 Function({required T}) <:  (R1 Function({S}))*` which ignores the `required` in that case only.  Note that the `*` on the RHS is on the entire function type, not necessarily on any component.

This means that we have:

//opted out
```
class A {
  int m({int x}) => x;
}

typedef F<T> = T Function({T x});
F<int> legacy;
```
// opted in
```
import 'opted_out.dart`

class B extends A {
  int m({required int x}) => x;  // Should be no error here
}

int f({required int x}) => x;

void main() {
  F<int> g = f; // Error, `F<int>` is int* Function({int* x}) (no * on the outside)
  legacy = g; // Ok, legacy has type (int* Function({int* x}))*.
}
```

@scheglov does that match your understanding?

**Comment by scheglov** [comment]
@leafpetersen Yes.

**Comment by lrhn** [comment]
How does this interact with *not* putting `*` on the types of legacy typedefs when referenced from null-safe code?

**Comment by eernstg** [comment]
I do not think we have support for indicating that a function type as such is a legacy type. We discussed briefly whether we should have that concept, but never went far in that direction. A type like `(R1 Function({S p}))*` is a type whose extension includes null, and there is nothing that supports a claim that the function type itself should have the property of being a legacy type:

```dart
// Legacy.
class A<X> {
  X get x => null;
}

// With null-safety.
class R1 {}
class S {}

void main() {
  A<R1 Function({S p})> a = A();
  a.x; // Type `(R1 Function({S p}))*`.
}
```

So unless we wish to introduce this notion that a function type itself is a legacy type (@lrhn suggested using a `*` on `Function` for that: `R1 Function*({S p})`), we can't use the top level `*` to say anything about the function type itself.

However, I do not think it is necessary to introduce this new concept. I would suggest that we use the type of the parameter itself to determine whether `required` can be omitted in the supertype:

```dart
R0 Function({required S p}) <: R1 Function({S* p})
```

There is a danger that normalization will eliminate the `*` in some cases (e.g., `dynamic*` --> `dynamic`), and hence give rise to a compile-time error which is unwanted. This will only arise in the case where a null-safety conflict in implemented superinterfaces or inherited member signatures exists, so we might choose to live with it.

But does this make a difference for the examples?:

```
// Legacy, 'opted_out.dart'.
// @dart = 2.6

class A {
  int m({int x}) => x;
}

typedef F<T> = T Function({T x});
F<int> legacy;

// Opted in, 'main.dart'.
import 'opted_out.dart`

class B extends A {
  int m({required int x}) => x;  // Still no error.
}

int f({required int x}) => x;

void main() {
  F<int> g = f; // Now OK, `F<int>` is `int* Function({int* x})`.
  legacy = g; // Still OK, legacy has type `(int* Function({int* x}))*`.
}
```

So the difference is that a legacy type alias denoting a function type can be used in a library with null-safety and preserve its ability to "pretend" that it has `required` where needed, and that to me seems to be a property that is more tightly associated with the type of the parameter than it is with the ability of the reference `g` to be null.

**Comment by leafpetersen** [comment]
> How does this interact with _not_ putting `*` on the types of legacy typedefs when referenced from null-safe code?

Precisely as shown in my example .

**Comment by eernstg** [comment]
@leafpetersen, do you really want to allow the following?:

```dart
// Legacy.
class A<X> { X x; }

// Opted in.
void main() {
  A<void Function({int p})>().x = ({required int p}) {}; // OK!
}
```

The setter `x=` takes an argument of type `(void Function({int p}))*`. If we use the `*` on the function type as a whole to decide whether or not it is a legacy function type, I think we will have far too many situations where an nnbd function type is considered to be a legacy function type, and developers would very likely be surprised by situations like the one above.

At this point I actually think we should introduce the notion of "a legacy function type", for instance `void Function*()`. This is not the same thing as `(void Function())*`, but rather a function type which was created based on syntax that is located in a legacy library. So it's exactly the function types where `required` could not be specified, which are also exactly the ones where this special exception is appropriate.

(We could also rely on the type of the parameter, as I mentioned, but that's actually a bit inconvenient in the cases where that type has been obtained using member signature mitigation, because we would then use normalization and `NNBD_TOP_MERGE`, and they would erase `*` from several types).

**Comment by leafpetersen** [comment]
> @leafpetersen, do you really want to allow the following?:

Per discussion today, I don't particularly **want** it, but I don't see much value in forbidding it.  You have no guarantees that `required` is honored when running in mixed mode.   The approach taken by @scheglov enables users to migrate to `required` freely.

**Comment by leafpetersen** [comment]
This has been resolved.
