### ISSUE TITLE
Is a late local variable in scope in its own initializer?

### ISSUE THREAD

**Issue by munificent** [dart-lang/language#828]
A pretty common use of `late` local variables I find when migrating tests is code like this:

```dart
  late StreamSubscription subscription;
  subscription = foo2(controller.stream).listen((event) {
    if (event == 2) {
      subscription.pause();
      scheduleMicrotask(() {
        subscription.resume();
      });
    }
    if (event == 5) {
      subscription.cancel();
    }
  });
```

The variable `subscription` is declared without an initializer because the initializer body refers back to itself. You can fix the nullability error using `late` like I did here. It does still require splitting the initialization into two statements, though.

One of the nice things about late *fields* is that we let you access `this` in their initializer. Since accesses have to be checked at runtime anyway, it seems like it could be a very useful feature to allow a late local variable to refer to itself. As far as I can tell, this isn't currently supported.

Should it be?

**Comment by lrhn** [comment]
I see no technical reason that late local variables can't be allowed to see themselves. 

I even thought we already discussed this and decided that it should, but ... can't find it. Might be thinking of https://github.com/dart-lang/language/issues/545.

We allow non-local late/lazy variables to refer to themselves (and diverge if they do so eagerly in the initializer). A `late` marker suggests that the user is in charge of ensuring proper access protocols, so that's not something we should be messing with.

There is no risk of seeing a final local variable in its pre-initialization state because that's exactly what `late` variables are there to check for dynamically. That's the only reason to not allow the self-reference in non-late variables, but for late variables, the initializer is always run later than the declaration anyway.

Now, the caveats:

* Typically situations like the one above are expected to evaluate *eagerly*. Making the expression *late* also makes it *lazy*, so the listen call won't happen until some code below actually reference `subscription`. There is a *high risk* that users will forget to reference the subscription entirely (because it is only accessed from inside the listeners created by the initialization), and then they'll be confused when nothing happens.

* Even where that is not an issue, we might start seeing more late variables with self-referencing initializers. That means that we need to retain the full init-state for the variable because we cannot possibly expect to detect whether the callbacks will re-read the variable before initialization is done. That's an overhead that you can avoid with the 

I've moved to doing:
```dart
var subscription = foo2(controller.stream).listen(null);
subscription.onData((event) {
  ...
});
```
It's not much worse (if only we could have optional positional and named parameters on the same function, then I wouldn't have to pass the initial `null`).

**Comment by eernstg** [comment]
I agree that it would make sense to allow this kind of self-reference, if it does not cause significant difficulties (say, if it takes a lot of work to implement, or if it causes reduced performance, especially in declarations where the feature isn't used, or even where it seems to be used, but a very clever static analysis would be able to see that the performance hit can be avoided).

I suspect that this mechanism would allow a very restricted kind of mutual recursion. If we can allow this without causing said difficulties then it might be a good reason for having it: Developers couldn't even emulated it using local declarations (without extra tricks like storing a function literal in a local variable, just like the old work-around for declaring two mutually recursive local functions).

@johnniwinther, do you expect this feature to cause performance degradation? Or does it make other difficulties come to mind that we haven't mentioned?

**Comment by johnniwinther** [comment]
The late lowering would need to hoist the variable declaration to avoid the self reference which I don't expect the backends to handle (it would at least be completely new to them that variables can be read in their own initializer).

I'm more worried about the semantics of this code pattern, though. If we changed the example to use the late variable in its initializer:
```Dart
  late StreamSubscription subscription = foo2(controller.stream).listen((event) {
    if (event == 2) {
      subscription.pause();
      scheduleMicrotask(() {
        subscription.resume();
      });
    }
    if (event == 5) {
      subscription.cancel();
    }
  });
```
we would actually never see a triggering read access of `subscription` and the variable and its initializer would surprisingly be dead code.

**Comment by lrhn** [comment]
I'm increasingly less (decreasingly?) convinced that late local variables with initializers is a good idea at all.

It seemed like a great idea at the time, but while migrating, I found very few uses for the feature. In almost all cases where I could lazily create something, I needed to know afterwards whether I had done so or not (to release or handle it). So, I needed the "has been initialized" logic to be explicit instead of implicit anyway, and I ended up using a nullable type and `??=` instead.

The foot-gun here (make a late variable with self-references, then forget to read it, or the anti-pattern of having to add a spurious `subscription;` read) is scary. We can avoid that by making the initializer not be able to be self-referencing.

Then there is the rule that you can't use `await` inside the initializer expression. That's another design smell (one thing is not like the others ... but it looks almost exactly the same).

So, how about we simply *disallow* local late variables with initializer expressions.
I spot none of them in the migrated platform libraries (`git grep -B4 -E '\blate\b.*=' sdk_nnbd` lists only top-level or class-level declarations).

**Comment by eernstg** [comment]
I'm not so worried about the fact that if there's a `late` modifier on a variable declaration then an initializing expression won't get evaluated unless you evaluate that variable. This is inherently what you'd expect from a `late` variable, and the word 'late' occurs at the very beginning of the declaration.

We could of course emit a warning/hint/lint a situation where a late variable is declared, but never used. The initializing expression would then be dead code, and flagging that as such seems like a natural reaction when this situation is detected. So why would we outlaw these variables entirely, when we can just do that?

But the ability for a late local variable to refer to itself in the initializing expression is rather tricky, because it would be a dynamic error unless the reference occurs from some code that runs after the initializer evaluation has completed. In other words, that reference has to be located in the body of a function literal, or in dead code, otherwise we'd have a dynamic error when we read the variable before the initializing expression evaluation is complete.

So maybe we'd want to disallow this kind of self-reference (because it's so error-prone), or maybe we should make it an error _unless_ the self reference occurs in the body of a function literal?

**Comment by lrhn** [comment]
*I* know that a late variable is not initialized immediately, but I fear that it will be a foot-gun for users.
If they learn that "you can't refer to a variable in its initializer, but you can if it's late", then they may blindly add `late` to get that effect, and in many cases it will work because they refer to the variable later.

They will then fall flat when they do the 
```dart
late var subscription = something.listen(
  onData: (e) { if (test(e)) otherController.add(e); },
  onError: otherController.addError,
  onDone: otherController.close);
```
and never read the `subscription` again.


Maybe it's sufficient to just not allow the self-referencing. Then people will only use late variables for actual late initialization. I do fear that giving it some *other* benefit will just make users use it for that benefit alone, and I do not want that.

**Comment by munificent** [comment]
OK, I'm persuaded that this is a bad idea. I didn't think about how lazy evaluation means the pattern I suggest simply doesn't work at all. Oops!

**Comment by leafpetersen** [comment]
The answer remains `no` here.
