### ISSUE TITLE
I can't call extension methods on function that return num

### ISSUE THREAD

**Issue by zmofsx** [dart-lang/language#832]
I have a extension methods  on dynamic:

`  
_getCartAccount() {
    return 334444.99999999;
  }

  _main() {
    num v = _getCartAccount();
    print(v.toSimpleCurrencyString()); //OK
    print(Extension_ToString(_getCartAccount()).toSimpleCurrencyString()); //OK
    print(_getCartAccount().toSimpleCurrencyString()); //Error: Class 'double' has no instance method 'toSimpleCurrencyString'.
}
`
The third print() error:

Syncing files to device SM N9002...
I/flutter (12465): $334,445.00
I/flutter (12465): $334,445.00

════════ Exception caught by widgets library ═══════════════════════════════════════════════════════
The following NoSuchMethodError was thrown building Cart(dirty, state: _CartState#a3cb1):
Class 'double' has no instance method 'toSimpleCurrencyString'.
Receiver: 334444.99999999
Tried calling: toSimpleCurrencyString()

**Comment by zmofsx** [comment]
`
    var fn = () => 334444.99999999;
    print(fn().toSimpleCurrencyString()); //OK

    var f = _getCartAccount;
    print(f().toSimpleCurrencyString()); //Error: Class 'double' has no instance method 'toSimpleCurrencyString'.
`

**Comment by eernstg** [comment]
> I have a extension methods on dynamic:

Note that you can define an extension on `dynamic`, but this doesn't change the fact that static extension methods (which is the full name of 'extension methods') cannot be invoked on a receiver of type `dynamic`, ever:

```dart
extension on dynamic {
  void foo() { print("Running foo!"); }
}

void main() {
  dynamic d = 42;
  d.foo(); // 'NoSuchMethodError'.
}
```

The reason for this is that a receiver of type `dynamic` is considered "to have all members", that is, if you call `d.foo()` where `d` has static type `dynamic` then `foo` is assumed to be a method that accepts zero arguments on `d`, and we generate code to call that. Then at run time you'll get the `NoSuchMethodError` because there was no such instance method.

In order to call an extension method it must be selected statically, that is, you must have the relevant extension in scope (could be declared nearby, could be imported), the receiver type must match the `on` type of the extension, and there must _not_ be an instance member with the name that you're accessing (so the receiver type can't have a `foo`, or in your example: it can't have a `toSimpleCurrencyString`).

So the example you show is working as intended.

**Comment by zmofsx** [comment]
Thank you. Sorry I didn't read the documentation carefully.

But,I always work with JSON data from server every day,
in DART it is LinkedHashMap<String, dynamic> or List<dynamic>.dynamic,

The dynamic is int, double or String, 
I want to use extension methods to format them, for example: 

```
this.data['Goods']['Price'].toSimpleCurrencyString(). 
```
Now I have to change them into(FD is my class):
```
FD.toSimpleCurrencyString(this.data['Goods']['Price'])
```

But in C# extension methods support any types.

**Comment by eernstg** [comment]
> Sorry I didn't read the documentation carefully.

Don't worry, there's always a tricky corner case. ;-)

> in DART it is LinkedHashMap<String, dynamic> or List.dynamic

Would you be able to choose a different typing, or do those types get chosen by some code that you can't/won't touch? If you can change that type (other than using `as SomeType` at all call sites) to `Object` (with nnbd, you might need to use `Object?`) then you would be able to invoke extension methods on `Object` (with nnbd perhaps `Object?`), and then you would have the guarantee that all those invocations will call extension methods (because `Object`/`Object?` has only a few, well-known members).

The underlying cause of your difficulties is that instance members will prevail when an invocation could call both an instance member and an extension method. This choice was made very carefully, and it won't change, so it's a fact of life in Dart that you can't call an extension method on a receiver of type `dynamic` (short of using the explicit extension invocation syntax `MyExtension(target).extensionMethod()`).

> But in C# extension methods support any types.

I get the following failure from the program below:

```
Run-time exception (line 14): 'string' does not contain a definition for 'WhoAmI'

Stack Trace:

[Microsoft.CSharp.RuntimeBinder.RuntimeBinderException: 'string' does not contain a definition for 'WhoAmI']
   at CallSite.Target(Closure , CallSite , Object )
   at System.Dynamic.UpdateDelegates.UpdateAndExecute1[T0,TRet](CallSite site, T0 arg0)
   at Program.Main() :line 14
```

```C#
using System;

public static class MyExtensions {
    // The WhoAmI method "extends" anything deriving from System.Object.
    public static string WhoAmI(this object obj) {
        return obj.GetType().Name;
    }
}
					
public class Program
{
	public static void Main()
	{
		Console.WriteLine(((dynamic)"I think I am a string").WhoAmI());
	}
}
```

So you get the same problem in C#: If the receiver has type `dynamic` then the extension method will not be executed, and the invocation fails at run time because the type `string` doesn't have an instance method called `WhoAmI`.
