### ISSUE TITLE
We currently cannot use `late` without non-nullable experiment

### ISSUE THREAD

**Issue by rrousselGit** [dart-lang/language#833]
The `late` keyword is currently associated with the `non-nullable` experiment.

This is inconvenient because if we want to use the keyword we have to enable NNBD, which is for the most part unusable as not everything is migrated yet.

It would be great if we could use `late` _without_ enabling NNBD.

**Comment by lrhn** [comment]
Being under an experiment flag is *deliberately* inconvenient. It was designed so that you have to go out of your way to enable the experiment so that you can play around with it, but you should not be making any permanent code which depends on an experiment.

Until the "null safety" feature is released, graduating it from being an experiment, you should not be *using* any part of it, including late variables, for anything serious (nor should you expect it to be bug-free).

Enabling the "late variables" feature without the rest of null safety, extracting it as its own feature, is unlikely to happen. 

Late variables is part of a large number of related features around null safety, and they won't work very well individually, nor are they built to be separated. Late variables interact with, for example, the improved type promotion and definite assignment analysis that are also part of null-safety, so even if we somehow manage to enable late variables by themselves, you still won't get the full experience.
You'd still have to migrate the late variables to null-safety later.

The work to extract the "late variables" feature from the rest would probably be better spent just completing null safety. That's why I don't expect that to happen&mdash;it is not a priority to release late variables before null safety, so I doubt we'll spend the necessary extra resources.

**Comment by rrousselGit** [comment]
Does that mean a library won't be able to use `late` unless it opt-in for NNBD?\
Or we would still be able to opt-out from NNBD (to migrate) but use that keyword?

**Comment by lrhn** [comment]
Yes, `late` variables will be part of the same language version which introduces NNBD/null safety. 
It's all-or-nothing, you have to use either that language version, or opt out of new features and use an earlier language version for your code. 
When more features are released in the future, they will be based on null-safety and will also only be available if you use the even newer language version.

We very deliberately did not make it possible to cherry-pick features because that would increase the combinatorial complexity of our implementation to exponential in the number of features, not linear in the number of releases, and it would risk fragmenting the ecosystem.

The goal is not to allow people to be *happy* about not migrating to NNBD. You should be migrating, the only question is "how fast". 
Eventually, when the vast majority of the ecosystem has migrated, we'll remove support for language versions prior to the release of null safety, and then we can finally trust that Dart code is null-sound.

**Comment by rrousselGit** [comment]
That's fair.
