### ISSUE TITLE
NNBD spec: What should the type of generic method tear-offs?

### ISSUE THREAD

**Issue by nshahan** [dart-lang/language#847]
The existing spec describes replacing instantiated type arguments with `Object` in 
**16.20.3 Ordinary Member Closurization** (thanks @munificent for the digging up the relavant information).

> For each parameter pj , j ∈ 1..n + k, if pj is covariant (9.2.3) then Tj is the built-in class Object.

When you tear off the method, what should the type be now? `Object?` seems like the obvious choice but should it be `Object*` in legacy libraries?

In discussions around the office we seem to agree that the library where the tear off is performed should not matter. It should be the site where it was originally defined, but it isn't clear if the method is inherited should the legacy status be based on the library where the method is defined or the class that inherited it.

```
class Foo<T> {
  method(T param) {}
}

class Bar<T> extends Foo<T> {}

var f = Foo<int>().method;
var g = bar<int>().method;
```

What should the types of `f` and `g` be if classes `Foo` and `Bar` are defined in either a legacy or null safe libraries? 

@leafpetersen @lrhn @eernstg 

cc @sigmundch @crelier @fishythefish

**Comment by crelier** [comment]
The VM sets the parameter type to `Object?` if the function belongs to an opted-in library and to `Object*` otherwise.
In your example, both signatures becomes `(Object?) => dynamic` if in a null-safe library or  `(Object*) => dynamic` in a legacy library.

**Comment by eernstg** [comment]
@nshahan, I basically agree with everything you said. @crelier, sounds good that the vm does the right thing already!

The reified type of a torn-off instance method must be a function type where each covariant parameter has a top type. This used to be `Object`, and it needs to be updated with nnbd.

I think we should use `Object?` with a method implementation whose declaration occurs in an opted-in library, there is no other reasonable choice.

When the declaration occurs in an opted-out library, we can use `Object*`, because that is also a top type.

We could also use `Object?` for the opted-out method, but I think this would just be a source of confusion (for a person who is trying to understand how such a type could arise). The case where it could make a difference is when reified types are compared for equality (cf. https://github.com/dart-lang/language/issues/821): With the specification of `Type.==` for reified types, a torn-off legacy method with a covariant parameter would be considered to have a type which is not equal to a torn-off nullsafe method, but equal to a different nullsafe method which will behave differently:

```dart
// In a nullsafe library.
class A {
  void m1(Object o) {}
  void m2(Object? o) {}
}

// In a non-nullsafe library.
class B {
  void foo(covariant Object o) {}
}

// In any library.
void main() {
  print(A().m1.runtimeType == B().foo.runtimeType); // 'true'.
  print(A().m2.runtimeType == B().foo.runtimeType); // 'false'.
}
```

However, I still think we should use `Object*` for the reified covariant parameter type, and then consider `Type.==` separately.

It should not make a difference whether the method is inherited: If the declaration occurs in an opted-out library then this is still true even if it serves as the implementation of that method for an instance of a subclass, so it shouldn't be given a new meaning.

**Comment by leafpetersen** [comment]
I believe this is resolved.
