### ISSUE TITLE
Non-function type aliases: Add restrictions

### ISSUE THREAD

**Issue by eernstg** [dart-lang/language#848]
Working on non-function type aliases, we have some interactions with type inference. I believe that we need to reduce the expressive power of this mechanism in order to maintain tractability, that is, the language design needs to be refined/restricted.

In particular, we aimed to allow a type alias to be used for instance creation (that is, it should be possible to use it as a constructor), because this would be required in order to allow a type alias to work as a "rename" on a class, or as a shorthand for passing a specific pattern of type arguments to a class (for instance, `typedef C<X> = p.C<X, int>` could allow us to add a type parameter to an existing class `C`, and then have existing code import the new class with a prefix and pass the extra type argument using a typedef -- and then the existing code wouldn't have to be updated).

But the ability to use a type alias for instance creation creates some new situations that we might not want to address, and possibly inherently intractable situations. The core problem is that instance creation is subject to type inference. There are other situations where a type alias is similarly subject to inference, in particular when a generic mixin is specified using a raw type alias. The constructor case is probably the most problematic, so I'll use that for illustration.

The following kind of type alias introduces a new kind of inference:

```dart
// Questionable kind of type alias: Right hand side is a type variable.
typedef F<X, Y extends Iterable<X>> = X;

// Illustration of issue.
class Foo { Foo.named(); }
class Bar { Bar.named(); }

void main() {
  // Infer `F<Foo, Iterable<Foo>>` because `Foo.named` denotes a constructor,
  // and because `Y` is unconstrained by the right hand side, but has a bound?
  Foo foo = F.named();
}
```

**We could say** that it is simply an error for a type alias to have a right hand side which is a type variable.

In general, a non-function type alias could have another non-function type alias as its right hand side, so we would have a function from a list of types to another list of types, composed from any number of such functions. Each of them could omit some of its arguments or use some of its arguments more than once, or in some other parameterized type (type alias or class).

This gives rise to a function that may not have an inverse (if a type variable is unused in one of these steps, the value is unconstrained; if it is used twice then it creates an equality constraint; constraints on the declared bounds may exist as well, at each step).

```dart
// Setup with type aliases affecting inference. 
typedef F1<X> = F2<X, List<X>>;
typedef F2<X, Y> = Map<X, Y>;

void main() {
  Map<num, Iterable<int>> map = F1(); // Infer type argument `int`?
}
```

**We could say** that a type alias can never be subject to inference. Thus, it can never be used raw (that is, omitting the type arguments) as a constructor when the context type is non-trivial, nor can it be used raw as a mixin in a class declaration. Instantiation to bound should not be a problem, because it starts from the actual type alias declaration denoted, and proceeds forwards through the type aliases until the type is fully unaliased.

**We still have the option** to extend the language to support some special cases where the associated type function can easily be seen to have an inverse. In that case we can just note that inference is "requested" at the use-site because the type alias was used raw as a constructor, and then we perform inference on the ultimate class type denoted by that type alias, apply the inverse type function on the result, and check that the bounds of the type alias are satisfied.

@leafpetersen, @lrhn, @munificent, WDYT?

**Comment by lrhn** [comment]
> *We could say* that it is simply an error for a type alias to have a right hand side which is a type variable.

*Please* say that. That's not practically useful for defining a shorthand for a type, and I *do not* want to see the hacks people might try with it.

I'd even say that a type alias cannot declare a type parameter that isn't used in the alias type (no unrestricted type parameters like `typedef F<X> = int;` because that's just useless).


Making the type alias not subject to inference is ... tricky. But likely a good idea.
I'm tempted. Since we don't usually do inference in type positions (preferring raw types), it might be sufficient to disallow using `new` on type aliases? (And statics too, then, for consistency)?

We could require that type parameters occur exactly once, but that's annoying because `typedef IdFunc<T> = T Function(T);` is exactly the kind of thing you'd want to use aliases for.

**Comment by leafpetersen** [comment]
On the question of type aliases with just a type variable on the RHS, this is something that is definitely useful with abstract type aliases (aka extension types).  It's less useful with type aliases as defined here, but still can be useful for documentation purposes.

I agree that such a type alias should not be usable in an instantiation expression though - that's very "macro" like in a way that I don't think we want.  Basically, there are two notions of resolution: resolving something as a type, and resolving something as a class.  In an expression of the form `new C<T>`, `T` is resolved as a **type**, and then `C<"the type referred to by T">` is resolved to a **class**.  So if we have `typedef C<X> = X`, then resolving `C<"the type referred to be T">` doesn't give you a class, it gives you a type, which is not valid.

**Comment by leafpetersen** [comment]
> This gives rise to a function that may not have an inverse (if a type variable is unused in one of these steps, the value is unconstrained; if it is used twice then it creates an equality constraint; constraints on the declared bounds may exist as well, at each step).

I don't understand the issue you're trying to get at.  All of the above can already arise via subclassing, what's new here?  Concretely to the example you give, I would expect inference to proceed as follows (in the downwards phase).

```
- F1<X> <# Map<num, Iterable<int>> // solve for X -> ? <: X <: num &&  ? <: X <: int
- F2<X, List<X>> <# Map<num, Iterable<int>> // solve for X -> ? <: X <: num &&  ? <: X <: int
- Map<X, List<X>> <# Map<num, Iterable<int>> // solve for X -> ? <: X <: num &&  ? <: X <: int
  - X <# num // solve for X -> ? <: X <: num
  - List<X> <# Iterable<int> // solve for X -> ? X <: int

  So we resolve to `? <: X <: GLB(int, num)` and choose `int` for `X`.
```

I see no issues here - it's essentially the exact same process that I would go through if the example was instead:

```dart
class F1<X> extends F2<X, List<X>> {}
class F2<X, Y>  implements Map<X, Y> {...}

void main() {
  Map<num, Iterable<int>> map = F1(); // Infer type argument `int`?
}
```

Am I missing something?

**Comment by eernstg** [comment]
> Am I missing something?

Nope, I agree that a context type which is an instantiation of an indirect superinterface creates the same situation, I just hadn't noticed that this new task matches the existing machinery so perfectly.

That's really nice, by the way! Type inference on a type alias used as a constructor is definitely useful (in that it makes the type alias work much more like the underlying constructor).

**Comment by lrhn** [comment]
I guess there is a use-case for a single-type-variable RHS when combined with configurable imports.If one library declares
```dart
 typedef M<T> = T?;
```
and the other declares
```dart
 typedef M<T> = T;
```
then it does make sense to use `M<Foo>` and getting `Foo`.
I'm not particularly fond of an unconditional alias like
```
  typedef Meters<T> = T;
```
just to allow you to write `Meters<int> length;` instead of just `int lengthInMeters;`. I'm sure some people will still do it.

There is also the conditionally imported `typedef Choose<S, T> = S;` and `typedef Choose<S, T> = T;` to write generic code that works on two different types depending on what else is imported.
Probably not particularly useful in practice.


As for instantiation of a type alias, and the distinction between a type and a class, we need to be very sharp on how we define this distinction. I see it. I'm just not sure I can explain it.
Maybe something like:

Writing `new D<T>(...)` is disallowed if `D` does not denote a class. 
`D` denotes a class iff
* The (possibly qualified) identifier `D` resolves to a class declaration, or
* The (possibly qualified) identifier `D` resolves to a type alias declaration where the RHS is of the form `Q` or `Q<type args>` where `Q` denotes a class.

Writing `D<T>(...)` is equivalent to `new D<T>(...)` iff `D` denotes a class.

**Comment by eernstg** [comment]
The inference issues have been resolved. With respect to the ability to create an instance based on a type variable, cf. https://github.com/dart-lang/language/issues/848#issuecomment-589753023, we decided that this is not supported:

```dart
class C {}
typedef F<X> = X;
typedef G<X, Y> = F<Y>;

var x = F<C>(); // Error.
```

We say that a type alias `F` _expands to a type variable_ when the body of `F` is a type variable, or if the body of `F` is a type alias `G` that expands to a type variable, or a parameterized type `G<T1, .. Tk>` where `G` expands to a type variable.

The underlying rule is then that it is a compile-time error if the instantiated class `C` in an instance creation `C(...)` or `C.name(...)` denotes a type alias that exands to a type variable.
