### ISSUE TITLE
Consider allowing extension applications on type literals

### ISSUE THREAD

**Issue by simolus3** [dart-lang/language#860]
Let's say I had an extension like the following:
```dart
import 'dart:mirrors';

extension IsSubtypeExtension on Type {
  bool isSubTypeOf(Type other) => reflectType(this).isSubtypeOf(reflectType(other));
}
```

Now, I want to write something like `int.isSubTypeOf(num)`. This doesn't work, and the specification points out why:

> __Applicability__
> An extension `E` is applicable to a [...] member invocation with corresponding member basename `m` and target expression `e`, where `e` has static type `S`, if
> * The invocation is an instance member invocation. That is the case if the expression e does not denote a prefix or a class, mixin or extension declaration (_then the member invocation would be a static invocation_)

Maybe this restriction can be softened so that `e.m` with `e` being a class or mixin declaration still applies the extension provided that the class referred to by `e` doesn't have a static member `m`?

I'm aware that I can use `IsSubtypeExtension(int).isSubTypeOf(num)`, but having to use that syntax defeats the point of extensions. Writing `(int).isSubTypeOf(num)` feels awkward as well.

**Comment by eernstg** [comment]
The reason why `int.isSubTypeOf(num)` fails is that `int` is a type literal, and when `t` is a type literal an invocation like `t.isSubTypeOf(...)` must be an invocation of a static method or a named constructor. 

Dart has had that restriction from the very early days, and the standard example in the language specification is that `int.toString()` could invoke the `toString` instance method of an instance of `Type` obtained by evaluating `int` as an expression, but since `TypeLiteral.name()` will otherwise always invoke a static method or instantiate a new object and run a named constructor on it, this would be more confusing than helpful. So `(int).toString()` it is.

**Comment by simolus3** [comment]
> so you would only need that parenthesis in a few cases.

Right. I was thinking about how I could add seemingly static properties to classes if we ever have generic types, but I agree that this is more confusing than helpful.
```dart
extension OfExtension<T> on Type<T> {
  T of(BuildContext context) => Provider.of<T>(context);
}
// could now use MyClass.of(context)
```
But I'm aware that there are other issues to track that use case, so I'll close this one.
