### ISSUE TITLE
Should inference use the promoted type as context?

### ISSUE THREAD

**Issue by johnniwinther** [dart-lang/language#867]
Consider the following code in face of the new type promotion algorithm:
```Dart
T f<T>(T t) => t;
method(String? s) {
  if (s == null) {
    return;
  }
  s = f(s); // <---
}
```
At the call `s = f(s)` we need to infer a type argument and we have two choices: 

1. We use the declared type `String?` of `s` as type context for `f(s)` and therefore infer the call to be `f<String?>(s)` which in turn will end the non-null promotion of `s` after the assignment.
2. We use the promoted type `String` of `s` as type context for `f(s)` and therefore infer the call to be `f<String>(s)` which in turn will continue the non-null promotion of `s` through the assignment.

For the case of non-null promotion it seems like we should use option 2 but I'm not sure if that is still the case for general promotion:
```Dart
T f<T>(T t) => t;
method(Foo s) {
  if (s is! Bar) {
    return;
  }
  s = f(s); // Should we infer `f<Foo>(s)` or `f<Bar>(s)>` here?
}
```

**Comment by johnniwinther** [comment]
cc @stereotype441

**Comment by munificent** [comment]
I think the user's mental model is that all three of these functions are semantically equivalent:

```dart
T f<T>(T t) { print(T); }

method1(Object s) {
  if (s is String) {
    f(s);
  }
}

method2(Object s) {
  if (s is! String) {
    ;
  } else {
    f(s);
  }
}

method3(Object s) {
  if (s is! String) {
    return;
  }
  f(s);
}

main() {
  method1("s");
  method2("s");
  method3("s");
}
```

In particular, I think most users believe that they can transform any of these functions to the other without changing their semantics. I'd like that to be true. In `method1()`, we do use the promoted type, so I think we should in the other two cases too.

**Comment by leafpetersen** [comment]
I agree with @munificent .  See my comment [here](https://github.com/dart-lang/sdk/issues/39641#issuecomment-620371958) for my specific take.

**Comment by johnniwinther** [comment]
The point here is not whether `s` has type `String` in `f(s)` (we know that it does in all three cases) but whether the type context used for the inference of the type argument to `f(s)` is the promoted type of `s` or the declared type of `s`. Whatever the choice is, it will apply in all three variants:

```Dart
T f<T>(T t) => t;

method1(Object s) {
  if (s is String) {
    s = f(s); // Is this 1) `s = f<String>(s)` or 2) `s = f<Object>(s)` ?
    // Is `s` String here ? 1) yes 2) no
  }
}

method2(Object s) {
  if (s is! String) {
    ;
  } else {
    s = f(s); // Is this 1) `s = f<String>(s)` or 2) `s = f<Object>(s)` ?
    // Is `s` String here ? 1) yes 2) no
  }
}

method3(Object s) {
  if (s is! String) {
    return;
  }
  s = f(s); // Is this 1) `s = f<String>(s)` or 2) `s = f<Object>(s)` ?
  // Is `s` String here ? 1) yes 2) no
}

main() {
  method1("s");
  method2("s");
  method3("s");
}
```

**Comment by johnniwinther** [comment]
There is an interplay between using the promoted type as type context and local function type inference:
```Dart
dynamic d = (int a, int b) => a;
if (d is int Function(int,int)) { // Promote `d` to type `int Function(int, int)`
  d = (a, b) { // Function expression inferred to have type `int Function(int, int)`
      return '$a'; // Compile-time error String is not assignable to int.
  };
}
```
Is this unforeseen or acceptable?

**Comment by stereotype441** [comment]
@leafpetersen FYI

**Comment by leafpetersen** [comment]
I agree that the interplay with inference is a bit surprising, but I think on balance it's probably the best available choice.

**Comment by johnniwinther** [comment]
We have the same problem with literals:
```Dart
main() {
  dynamic i = [0];
  if (i is List<int>) {
    i = ['String']; // Error: A value of type 'String' can't be assigned to a variable of type 'int'.
  }
}
```

**Comment by munificent** [comment]
That example definitely looks surprising. But I suspect that cases like this are rare enough in the wild that it's not worth adding complexity to handle them more gracefully.

**Comment by lrhn** [comment]
The error here comes from inferring the type of the list literal from the context alone. That's usually fine because the not satisfying the context would be an error, but here it isn't.

So, what if type inference would push down the type context as usual, but not use it for the object creating unless the code would then be *valid*. If it wouldn't be valid, say because it would try to create `<int>["string"]`, then it would use upwards inference instead to infer `<String>["string"]`. 
That would be treating the downward type context as more of a hint (a strong hint when it would be a valid choice, but still just a hint), rather than always using the context type, even when it's wrong.

That shouldn't change the types currently successfully compiled code, because it would act the same as now for code that isn't locally a compile-time error, but it would allow the assignment above to succeed as well.
(If it's correct that it won't change currently correct code, then it should also be safe to make this change later).

Any obvious things I've missed?

**Comment by eernstg** [comment]
I'd expect [this approach](https://github.com/dart-lang/sdk/issues/39641#issuecomment-620371958) to be used, based on [this decision](https://github.com/dart-lang/sdk/issues/39641#issuecomment-621548516), in which case we have already settled that inference of `x = E` uses the static type of `x` including promotions as the context type for `E`. (If the type of `E`-after-inference is assignable to `x` then we're done, otherwise demotion or an error may occur, but we don't retry inference using a different context type).

However, if we're revisiting this topic then I think there's yet another reason why we'd want to use the promoted type as the context type:

Consider a notion of **type stability**: How many times does a variable get pro/de-moted in a given piece of code? I think this kind of stability is desirable, because developers won't need to keep track of many changes of the type of a variable when that type is stable, which frees the mind to deal with other topics. Conversely, if this choice forces the code to indicate more explicitly that a change-of-type for a given variable is intended then it may seem inconvenient at first, but it is probably good for readability.

**Comment by leafpetersen** [comment]
> So, what if type inference would push down the type context as usual, but not use it for the object creating unless the code would then be _valid_.

I don't know how to answer the question of whether a given inference choice is valid without introducing fairly arbitrary amounts of backtracking: try one solution, does it work, if not back it out and try again.  I'm not very keen to go there.

**Comment by lrhn** [comment]
I don't think backtracking should be necessary, or at least only very local backtracking.
Example:
```dart
class Foo<T> {
  Foo(T x, List<T> y) : ...
}
...
x = Foo(1, ["ab"]);
```
If the current type of `x` is `Foo<int>`, then the context type for `e1` is `int` and the context type for `e2` is `List<int>`.
Then the context type for `"ab"` is `int`, but the value is a `String` anyway.
When we come back to look at `["ab"]`, we have a context type of `List<int>` and an inferred element type of `String`. Those are not compatible, so the element type wins (the context type is only a hint) and it becomes `<String>["ab"]`.
Then we get back to `Foo(1, ["ab"])` which has context type `Foo<int>` and argument types `int` and `List<String>`. Again those are not compatible (it would be a compile-time error to infer `Foo<int>`), so we instead infer `Foo<Object>(1, <String>["ab"])`.

Then we get back to the assignment to `x`, and if the `Foo<int>` type of `x` was due to promotion, then assigning `Foo<Object>` might not be an error. If it is an error, then that's where we get told that a `Foo<Object>` cannot be assigned to `Foo<int>`.

If the context type had been compatible with the argument types, then we would have chose the context type.
Example; `List<num> l = [1];`. Here `[1]` has an element type of `int` and a context type of `List<num>`, and because of covariance, that's compatible. We infer `<num>[1]` because we can - use the context type hint when possible, but not when invalid.

If I am right, this should be completely compatible with the current behavior, because it only differs in the case where the current behavior would introduce a compile-time error by strictly sticking to a context type which is incompatible with the elements/arguments. It might move the point where the error is reported.

**Comment by eernstg** [comment]
Even if it turns out to be possible to avoid/limit the backtracking, I still tend to think that it isn't very _helpful_ for developers if we are eagerly helping `x` to get demoted back to `Foo<Object>`.

I suspect that both the overall type stability and the avoidance of yet another bit of language rule complexity will be a net advantage for code comprehensibility. By the way, demotion is considerably worse for type stability than promotion, because it _cancels_ some promises that were given up to this point, and hence it isn't safe for a reader or writer of the code to ignore a demotion.

**Comment by leafpetersen** [comment]
> I don't think backtracking should be necessary, or at least only very local backtracking.

backtracking is necessary.

```dart
  T foo(T Function(T) f, T x) => f(x);
  void test() {
     Object x = 3;
      if (x is int) { // promote to int
        x = foo((f) => f(3), ("hello as Object"));
     }
```

Analyzing `f = f(3)` with context type `int` succeeds, analyzing `"hello" as Object` doesn't, try to choose `Object` for `T`, that means you need to backtrack and re-infer the lambda. which may or may not succeed.  I'm pretty sure you can nest the lambdas and calls to foo to get repeated backtracking.  

Not necessarily disqualifying, but it feels like there's a lot of complexity lurking here that I don't know whether works out or not.

**Comment by leafpetersen** [comment]
I believe this is resolved, closing this out.
