### ISSUE TITLE
How the nullability of the right-hand side of typedefs should be handled

### ISSUE THREAD

**Issue by stefantsov** [dart-lang/language#868]
I'm [trying](https://dart-review.googlesource.com/c/sdk/+/138087) to fix https://github.com/dart-lang/sdk/issues/40714.  That is, I'm trying to combine the nullability of the right-hand side of a type alias with the nullability at the use site, so that the following example code compiles:

```dart
typedef F = void Function()?;

foo(F x, F? x) {}
bar() => foo(null, null);
```

It makes some of the tests fail: https://github.com/dart-lang/sdk/issues/40874.  Specifically, the legacy nullability from opted-out files is now "captured" by typedefs and being combined with the "non-nullable" nullability from the use sites in opted-in libraries remains "legacy".  That makes it possible to assign null to the variables of such types, for example.   Consider the following code:

```dart
// Opted-out library "opted_out.dart".
typedef F = void Function();  // The nullability of the RHS is legacy.

// Opted-in library "main.dart"
import "opted_out.dart";

F f;  // Should have initializing expression if F is non-nullable,
      // but ok if F is legacy.
```

My question is: is that the expected semantics of typedefs?  If not, how the nullability of the RHS should be combined with the nullability from use sites across NNBD feature boundaries?

As a side note, my current interpretation has an interesting effect when combined with the non-function type alias feature.  Consider the following code:

```dart
// Opted-out library "opted_out.dart".
class A {}
typedef B = A;  // The nullability of the RHS is legacy.

// Opted-in library "main.dart".
import "opted_out.dart";

A a; // Error: A is non-nullable.
B b; // Ok: the legacy nullability was captured by the type alias,
     //     so B unaliases into A*, which allows null.
```

**Comment by leafpetersen** [comment]
> ```dart
> typedef F = void Function()?;
> ```

This is not a valid typedef (at least until we get generalized type aliases).  The RHS of a typedef is required to be a function type.

> ```dart
> // Opted-out library "opted_out.dart".
> typedef F = void Function();  // The nullability of the RHS is legacy.
> 
> // Opted-in library "main.dart"
> import "opted_out.dart";
> 
> F f;  // Should have initializing expression if F is non-nullable,
>       // but ok if F is legacy.
> ```

I think there are two reasonable interpretations of `F f` here:  
  - One is to interpret it as `int Function(int) f` 
  - Another is to interpret it as `int* Function(int*) f` (note, no `*` on the outermost type).

One could choose to interpret it as `int* Function(int*)* f`.  I'm not keen on that, for any number of reasons, notably that we otherwise have no way of silently introducing an implicitly nullable variable in migrated code.

Either of the first two approaches feels reasonable to me, but I think the first is more consistent with the way we treat inference.  We [have specified](https://github.com/dart-lang/language/blob/master/accepted/future-releases/nnbd/feature-specification.md#importing-legacy-libraries-from-opted-in-libraries) that inference erases legacy types, and so the most consistent approach to me seems to be to erase legacy types when expanding typedefs as well.

On the other hand, I can see that pragmatically this may cause difficulty with error messages, since it requires expanding out the RHS (or duplicating the typedef in some way).  In either case though, I don't think that the *variable* itself should be made legacy, any more than we would if `F` were a class type from a legacy library.

**Comment by lrhn** [comment]
I agree that `in* Function(int*)*` should be avoided.
It means that when we do get non-function type alises, `typedef Int = int;` will be generally useful and not introduce legacy types. All references to the type in legacy libraries will be `*` types anyway, but null safe libraries can choose.

I think that component types should probably be kept as legacy.

A legacy `typedef void Action(Object o)` declaration should be allowed to match `print`, which has `Object?` as argument type in the null-safe SDK. 
If writing `Action f = print;` would fail in a null-safe library, I fear it's going to cause problems. 
The legacy type should be maximally permissive so that it allows anything it could potentially be migrated to.

**Comment by eernstg** [comment]
```dart
// Opted-out library "opted_out.dart".
typedef F = int Function(int);

// Opted-in library "main.dart"
import "opted_out.dart";

void m(F f) {}
```

I think we should think about the treatment of superinterfaces as well (considering a type alias unfolding step to be similar in nature to a step from a class to one of its superinterfaces).

If we do this then the occurrence of the syntax `int Function(int)` in a legacy library ought to denote `int* Function(int*)`, because there is no way for the legacy code to express a plain `int`, nor the nullable `int?`, and the intended usage of `F` is not guaranteed to match the interpretation `int Function(int)`.

Similarly, with `class C {}` in a legacy library a variable/parameter declared as `C c` in an opted-in library would give `c` a non-nullable type, so this also justifies the decision to avoid putting a `*` outermost.

So I think @leafpetersen's second interpretation is the best match, and `f` should have type `int* Function(int*)`. This also matches with @lrhn's comment:

> I think that component types should probably be kept as legacy.

**Comment by leafpetersen** [comment]
I'm ok with going with my second interpretation.  I'll get a spec update together.

**Comment by eernstg** [comment]
I asked for an implementation in the cfe in https://github.com/dart-lang/sdk/issues/41505.

**Comment by leafpetersen** [comment]
I think this is resolved and landed.
