### ISSUE TITLE
keyof and Lookup Types

### ISSUE THREAD

**Issue by listepo** [dart-lang/language#876]
It would be very nice to have `keyof and Lookup Types` like https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-1.html
It will be very useful for implementation for `Fluent interface`

**Comment by lrhn** [comment]
The "Lookup Types" feature is a way to express a type as the type of *something*. Similar to C's `typeof`, you can write an expression and express the static type of that expression.
That does sound potentially useful in some situations. It would not express anything that you cannot otherwise express explicitly. In fact, simple type inference could be explained by `var x = e;` being equivalent to `typeof(e) x = e;`.
However, since Dart is *statically typed*, it won't actually provide much power. In most cases, you can just use inference instead.

The `keyof` hinges on the TypeScript ability to name a set of strings. It's basically an enum type of string value, like `"foo" | "bar" | "baz"`, and `keyof` defines such a type from the keys of an interface.
That makes much less sense for Dart where property names are not strings, and properties cannot be accessed using a string. Even if we added such checked enums, and made them `Symbol`s, there isn't much you can actually *do* with such a symbol enum type.

What it could be used for, instead, would be restricting `Map` keys to a fixed set, but that's not particularly normal Dart code (just declare a proper class instead of keeping structure in maps). It would only really be useful for JSON-like structures where you know the structure ahead of time, and unlike TypeScript which conflates objects and maps, Dart does not have interfaces for maps, so there is nothing for `keyof` to operate on.

**Comment by listepo** [comment]
@lrhn thanks for the answer

**Comment by tolotrasamuel** [comment]
@lrhn 

This is one application
How can this be achieved in Dart? 
```

interface Foo {
    fooId: string,
}

interface Bar {
    barId: string,
}


export interface FooBarMap {
    foo: Foo,
    bar: Bar
}

function register<K extends keyof FooBarMap>(code: K, fooBar: FooBarMap[K]){
    // somework
}
register('foo', {fooId: 'fooId'}) // valid
register('bar', {barId: 'barId'}) // valid
register('bar', {fooId: 'barId'}) // invalid foodId does not exists in type Bar
register('nor_foo_nor_bar', {fooId: 'fooId'}) // invalid "nor_foo_nor_bar"' is not assignable '"foo" | "bar"'.
```

**Comment by lrhn** [comment]
It probably cannot. Dart does not provide any way to statically link between type or member names and map keys. This is a very dynamic program.
That's not something I'd write in Dart to begin with.

What I'd do is:
```dart
abstract class Foo {
  String get fooId;
}
abstract class Bar {
  String get barId;
}

void register<K>(String getId(K value), ...);
main() {
  register<Foo>((foo) => foo.fooId, ...);
  register<Bar>((Bar) +> bar.barId, ...);
  register<Bar>((x) => x.fooId, ...);  // invalid, Bar does not have a fooId.
}
```
That is, if you want to abstract over operations, *use code* instead of strings. Dart does not allow member access using strings. Passing strings around should be restricted to things that actually work with strings.
