### ISSUE TITLE
Null safe async returns are currently unsound

### ISSUE THREAD

**Issue by leafpetersen** [dart-lang/language#944]
The following program results in a variable of type `int` containing `null` (as implemented on the VM, and I believe as currently specified):

```dart
Future<int>? foo() async {
  return Future<int?>.value(null) as dynamic;
}
void main() async {
  Future<int>? f = foo();
  if (f != null) {
    await f.then((x) => print(x.isEven));
  }
}
```

The issue is that `flatten(Future<int>?) = int?`, and so the dynamic semantics is specified to check if the returned value is `Future<int?>` (which here it is) and if so use the contents of the future to complete the return future, which has an incompatible type.

I believe we need to either use something like the future value type that @eernstg has proposed, or else possibly just disallow these odd return types for asynchronous functions.

cc @eernstg @lrhn @munificent

**Comment by lrhn** [comment]
I think Erik rewrote the "future value type" thing to account for this.

The future value type of `Future<int>?` is `int` because you are actually returning a `Future<int>`. Picking a supertype of that, like `Future<int>?` or `FutureOr<int>`, or even `FutureOr<int>?`, does not change the type of the actual future being returned.
That's one of the reasons we need that change, to disallow bad code like this which was not caught by the existing specification - which was reasonably fine when `flatten` didn't have to account for anything except `Future` and `FutureOr`. Adding `?` to the mix means that flatten, which matches the behavior of *await*, is no longer also correct for finding the future value type of an `async` function.

So internally in the function, the future value type will be `int`, and we are checking `return Future<int?>.value(null);` against that. It will be a compile-time type error because `Future<int?>` is not assignable to `int` and `int?` is not a subtype of `int` ("model 1" requirements).

**Comment by leafpetersen** [comment]
I've signed off on the latest proposal from @eernstg which resolves this, are you happy @lrhn ?

**Comment by lrhn** [comment]
I've approved it with only nitpicks left.

**Comment by eernstg** [comment]
@leafpetersen wrote:
> The issue is that `flatten(Future<int>?) = int?`..

Yes, this was exactly the reason why I introduced the 'future value type' of an `async` function, and I agree with @lrhn that it is now a compile-time error (btw, it would also be a compile-time error in model 2). We could make the silly return type an error in itself (so `T? f() async ...` is a compile-time error for all `T`), but I think that this could as well be handled by a lint.

**Comment by lrhn** [comment]
Async functions might be used to implement existing function types, so the `T?` could have been inferred rather than written. Like:
```dart
abstract class C<T> {
   T? blah();
}
class D implements C<Future<int>> {   
  Future<int>? blah() async { ... }
}
```
or 
```
Future<int> foo({FutureOr<int>? bar()}) => ...

foo(bar: () async { ... });
```
so even a lint could give false positives.

**Comment by eernstg** [comment]
Right! Arguably, even these false positives would flag some really twisted designs (making them very nearly true positives because it might be a good idea for the developer to explicitly override that inherited return type with `Future<int>` and no question marks ;-), but this still means that we shouldn't make it an error.

**Comment by leafpetersen** [comment]
> Async functions might be used to implement existing function types, so the `T?` could have been inferred rather than written. Like:

I don't think this is a big issue.  If we wanted to do this, we could.  We already infer principal types for lambdas, so there's flat out no issue at all there.  For override inference, yes, we'd either have to specify something similar, or probably better, just make it an error.

In any case, I think this is resolved by Erik's PR now landed, so closing.
