### ISSUE TITLE
[FEATURE REQUEST] Dynamic Map

### ISSUE THREAD

**Issue by angelhdz** [dart-lang/language#952]
It would be nice to have Dynamic Maps, or that all maps are dynamic in Dart, because having to create a class in every project, or create a package to solve this issue, is not practical.

My need is to be able to call maps properties with dot notation and not with square brackets/array access notation. 

Current:

`myMap['name'] = 'Angel';`

Ideal:

`myMap.name = 'Angel';`

Thank you and thanks to the creators for giving us Dart, this beautiful language.

**Comment by lrhn** [comment]
There are no current plans to support that as a language feature. Dart makes a distinction between property names and strings, and normal maps can be used with keys that aren't even strings.

What I'd (not really) suggest doing is something like:
```dart
class SymbolMap {
  Map<String, dynamic> _values = {};
  static String _baseName(Symbol symbol) => symbol.toString().replaceAll("=", "");
  dynamic operator[](Symbol key) => _values[_baseName(key)];
  void operator[]=(Symbol key, dynamic value) {
    _values[_baseName(key)] = value;
  }
  dynamic noSuchMethod(Invocation i) {
    if (i.isGetter) return this[i.memberName];
    if (i.isSetter) {
      this[i.memberName] = i.positionalArguments.first;
      return;
    }
    return super.noSuchMethod(i);
  }
}
```
This class allows you to do:
```dart
dynamic map = SymbolMap();  // Needs to be dynamic.
map.foo = 42;
print(map.foo);  // 42
```
Since it's based on member access of *undefined* members, you can't assign to the members of `Object` (`hashCode`, `toString`, `runtimeType` and `noSuchMethod`). Those are off-limit.

The type of the map variable must be `dynamic` to prevent Dart from rejecting the member access, I didn't bother putting a `<V>` on the class for the value type. It wouldn't do anything helpful in practice anyway.

I added `[]` and `[]=` so you can also access the members using symbol values, so `map[#foo]` would return 42 as well, but I didn't add any other members because they would block that name from being usable as a key.

It's still a little icky because it depends on converting the symbol to a string, and then assuming that the difference between the string for `#foo` and `#foo=` is just a `=`. I'm not sure that's always true for dart2js compiled code with minimized or obfuscated variable names.

**Comment by angelhdz** [comment]
> There are no current plans to support that as a language feature. Dart makes a distinction between property names and strings, and normal maps can be used with keys that aren't even strings.
> 
> What I'd (not really) suggest doing is something like:
> 
> ```dart
> class SymbolMap {
>   Map<String, dynamic> _values = {};
>   static String _baseName(Symbol symbol) => symbol.toString().replaceAll("=", "");
>   dynamic operator[](Symbol key) => _values[_baseName(key)];
>   void operator[]=(Symbol key, dynamic value) {
>     _values[_baseName(key)] = value;
>   }
>   dynamic noSuchMethod(Invocation i) {
>     if (i.isGetter) return this[i.memberName];
>     if (i.isSetter) {
>       this[i.memberName] = i.positionalArguments.first;
>       return;
>     }
>     return super.noSuchMethod(i);
>   }
> }
> ```
> 
> This class allows you to do:
> 
> ```dart
> dynamic map = SymbolMap();  // Needs to be dynamic.
> map.foo = 42;
> print(map.foo);  // 42
> ```
> 
> Since it's based on member access of _undefined_ members, you can't assign to the members of `Object` (`hashCode`, `toString`, `runtimeType` and `noSuchMethod`). Those are off-limit.
> 
> The type of the map variable must be `dynamic` to prevent Dart from rejecting the member access, I didn't bother putting a `<V>` on the class for the value type. It wouldn't do anything helpful in practice anyway.
> 
> I added `[]` and `[]=` so you can also access the members using symbol values, so `map[#foo]` would return 42 as well, but I didn't add any other members because they would block that name from being usable as a key.
> 
> It's still a little icky because it depends on converting the symbol to a string, and then assuming that the difference between the string for `#foo` and `#foo=` is just a `=`. I'm not sure that's always true for dart2js compiled code with minimized or obfuscated variable names.

Thank you very much! Very kind!

That's exactly what I use to do in languages like Python. I make a class and override the [] and the get/set, and create a DynamicMap class. I guess I'll have to stick to doing that then.

Be safe!
