### ISSUE TITLE
List lookups should return a nullable type like Maps

### ISSUE THREAD

**Issue by IchordeDionysos** [dart-lang/language#955]
With NNBD map lookups return a nullable type.
However, List lookups do return a NON-nullable type.

This can be really confusing for new developers, wo may wonder, why this works:
```dart
List<int> a = [1, 2];
int b = a[1];
```

But this does not:
```dart
Map<int, int> a = <int, int>{1: 1};
int b = a[1];
```

The lookup for both looks exactly the same, but they do two different things.

Take for example Swift, there null is returned for out of bound list entries instead of throwing an "Index out of range" error.

I might understand the reasons for doing this.
With a map you are more likely to try to access the value for a key which does not exist, whereas in a List you know how long it is and what indexes are save to access.

**Comment by mateusfccp** [comment]
Why not the opposite? Make map return non-nullable like lists?

**Comment by IchordeDionysos** [comment]
Then why make the effort to introduce NNBD if you won't use it for such obvious cases?

In basically every language trying to access the value for a key which does not exist returns a billable value, including Java, Swift, Javascript and most importantly Dart even before NNBD became a thing.

Changing that Dart will throw instead would probably be an unnecessary breaking change.
In my opinion even more so than changing the behavior for list lookups.

**Comment by lrhn** [comment]
There are no plans to change the `Map` or `List` interfaces at the current time.

We did not change `Map.operator[]` to throw because it would be too breaking.
We'd then also have added a method like `V? tryGet(K key)` that wouldn't throw, but changing the `Map` interface itself is a breaking change on a different level than the semantic changes of Null Safety, and it was considered as too much to include that in the Null Safety changes.
So, we had to make `Map.operator[]` return a nullable type.

A `List<E>` is effectively a map from `int` to `E` which throws (an `ArgumentError`) on invalid keys. 
As such, its lookup doesn't need to be nullable. `Map`'s lookup does need it.
Making `List.[]` nullable would force *every* list lookup to handle `null`, even though the vast majority of uses will be known to be non-null. Because a `Uint8List` is a `List<int>`, it too would have a nullable `[]` operator, which would be bloody annoying for everyone.
