### ISSUE TITLE
Are extensions applicable to receivers of type `Never`?

### ISSUE THREAD

**Issue by leafpetersen** [dart-lang/language#996]
The extension method proposal was written assuming that accessing members on `Never` would be forbidden:

```
The type S does not have a member with the basename m. For this, the type dynamicis considered as having all member names, and an expression of type Never or void cannot occur as the target of a member invocation, so none of these can ever have applicable extensions. 
```

We have subsequently specified that any access on a variable of type `Never` is permitted, and has type `Never`.  Should we specify that extensions apply or not?  The difference is observable in mostly trivial cases:

```
extension on Never {
  int get foo => 3;
}
main() {
  Never x = throw "hello";
  var y = x.foo;
  y.arglebargle;  // Error if the extension applies, not an error if the extension does not apply
}
```

cc @munificent @lrhn @eernstg

**Comment by eernstg** [comment]
I can't see how we could conclude that any extension method can be selected: A receiver of type `Never` would be considered to have all members with all signatures, so every extension method is deselected because the assumed instance member gets top priority.

Btw, then `x.foo` would have type `Never`, `y` would have inferred type `Never`, and `y.arglebargle` would also be accepted. Right?

In any case, it seems like we still can't have any applicable extensions.

**Comment by lrhn** [comment]
Good point. If `Never` is considered as having all members, like `dynamic`, then no extension applies. It makes no difference except for the return type of the thing that is never getting called.

**Comment by natebosch** [comment]
> We have subsequently specified that any access on a variable of type `Never` is permitted, and has type `Never`.

Which issue contains this discussion?

**Comment by leafpetersen** [comment]
Spec was landed, extensions do not apply.
